### ISSUE TITLE
2.1 功能点

### ISSUE THREAD

**Issue by liudongmiao** [brevent/Brevent#1]
- [x] ~主动低电耗~
由于低电耗（doze）针对整个设置，只会带来更多问题，放弃。
但是会在进入黑域时，退出强制 doze 状态。

- [x] 搜索

- [x] 排序
    - [x] 按名称
    - [x] 按上次使用时间
    - [x] 按更新时间
    - [x] 按使用时长

- [ ] 日志分析
     - [x] 加入电量 （如 `dumpsys batterystats` 等）
     - [ ] 过程记录
            顺延到子版本
     - [ ] 唤醒统计
            顺延到子版本

**Comment by iTry** [comment]
有bug无法开启， 原生8.0 nexus5x
