### ISSUE TITLE
我下载了你的代码但是有异常

### ISSUE THREAD

**Issue by as7212325** [brevent/Brevent#10]
我下载了你的代码运行和编译都没问题但是在真机测试的时候出现了如下提示
/data/data/me.piebridge.brevent/brevent.sh[37]: syntax error: 'elif' unexpected

**Comment by liudongmiao** [comment]
你的 shell 有毒...

**Comment by liudongmiao** [comment]
这个脚本只是增强一些兼容性。
你可以直接执行第一行的那个路径。

**Comment by cv0cv0** [comment]
我也遇到过这个问题。

**Comment by liudongmiao** [comment]
也遇到过，表明现在没有嘛...

**Comment by cv0cv0** [comment]
@liudongmiao 我是先用root开启，开启不了然后试命令报这个错，root能开启这个也能开启，现在没有试过这个命令。

**Comment by vvb2060** [comment]
用git就把自动换行符转换关掉。当初安装git时认真看说明啊……

**Comment by cv0cv0** [comment]
@vvb2060 怎么关？

**Comment by liudongmiao** [comment]
@cv0cv0 
> 当初安装git时认真看说明啊……

而且，这个东西，随便一搜，一大堆。
黑域不欢迎提了关键字，还问的人自编译。
