### ISSUE TITLE
Android O无法使用

### ISSUE THREAD

**Issue by Sherlock-Holo** [brevent/Brevent#10]
Android O dp2，运行了adb之后，黑域能够使用，但是一旦拔掉USB连接，然后切一下任务窗口，再回到黑域，就会提示重新adb

**Comment by sykh2011** [comment]
我的方法是一直不关adb debugging的开关

**Comment by Sherlock-Holo** [comment]
从来不关，咱说的是断开USB连接，就是手机和电脑的USB线拔掉

sykh2011 <notifications@github.com>于2017年5月26日周五 11:17写道：

**Comment by liudongmiao** [comment]
来点日志吧。然后无法处理的时候，查看黑域进程是否已经退出：

```
ps | grep brevent_
```

如果没有退出，看看测试版：https://piebridge.me/br/next/

**Comment by Sherlock-Holo** [comment]
拔掉USB后，ps -e | grep brevent发现所有跟黑域有关的都没了
日志是这个
angler:/ $ logcat -b main -d -s BreventLoader BreventServer
05-27 13:49:32.019  8204  8204 I BreventServer: Brevent Server 1.1.11
started
05-27 13:49:32.034  8204  8204 I BreventServer: brevent user: 0, uid: 2000
05-27 13:49:32.037  8204  8204 I BreventServer: brevent data directory:
/data/user_de/0/com.android.shell
05-27 13:49:32.072  8204  8204 I BreventServer: android providers:
{com.android.providers.calendar, com.android.providers.media,
com.android.providers.downloads, com.android.providers.downloads.ui,
com.android.providers.partnerbookmarks,
com.android.providers.blockednumber, com.android.providers.userdictionary,
com.android.providers.contacts}
05-27 13:49:32.072  8204  8204 I BreventServer: loading brevent list
05-27 13:49:32.079  8204  8204 I BreventServer: load
/data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 4
05-27 13:49:32.117  8204  8204 D BreventServer: Force stop
com.sankuai.meituan(load brevent)
05-27 13:49:32.130  8204  8204 D BreventServer: Force stop
com.tencent.tim(load brevent)
05-27 13:49:32.140  8204  8204 D BreventServer: Force stop com.anyview(load
brevent)
05-27 13:49:32.144  8204  8204 D BreventServer: Force stop
com.chaozh.iReader(load brevent)
05-27 13:49:32.144  8204  8204 I BreventServer: loading brevent conf
05-27 13:49:32.459  8204  8204 D BreventServer: check and brevent
05-27 13:49:32.948  8204  8204 D BreventServer: check again in 3600s
05-27 13:49:32.949  8204  8204 D BreventServer: check and brevent, took
488ms
05-27 13:49:33.038  8204  8204 D BreventServer: handled status
05-27 13:49:33.038  8204  8204 D BreventServer: sent first status
05-27 13:51:00.639  8204  8204 D BreventServer: update current to
com.google.android.googlequicksearchbox
05-27 13:51:02.787  8204  8204 D BreventServer: update current to
com.sonelli.juicessh
05-27 13:51:03.640  8204  8204 D BreventServer: check and brevent
05-27 13:51:03.913  8204  8204 D BreventServer: check again in 3600s
05-27 13:51:03.913  8204  8204 D BreventServer: check and brevent, took
272ms
05-27 13:52:32.038  8204  8204 D BreventServer: update current to
com.google.android.googlequicksearchbox
05-27 13:52:34.277  8204  8204 D BreventServer: update current to
me.piebridge.brevent
05-27 13:52:34.418  8204  8204 D BreventServer: handled status
05-27 13:52:34.418  8204  8204 D BreventServer: checking feelgood
05-27 13:52:35.040  8204  8204 D BreventServer: check and brevent
05-27 13:52:35.340  8204  8204 D BreventServer: check again in 3600s
05-27 13:52:35.340  8204  8204 D BreventServer: check and brevent, took
299ms
05-27 13:52:36.699  8204  8204 D BreventServer: update current to
com.google.android.googlequicksearchbox
05-27 13:52:39.703  8204  8204 D BreventServer: check and brevent
05-27 13:52:40.022  8204  8204 D BreventServer: check again in 3600s
05-27 13:52:40.023  8204  8204 D BreventServer: check and brevent, took
319ms
05-27 13:54:18.578  9790  9790 D BreventLoader: loader path:
/data/app/me.piebridge.brevent-4ec8iezWoxWeSV4vIZGbig==/base.apk
05-27 13:54:19.205  9802  9802 I BreventServer: Brevent Server 1.1.11
started
05-27 13:54:19.217  9802  9802 I BreventServer: brevent user: 0, uid: 2000
05-27 13:54:19.226  9802  9802 I BreventServer: brevent data directory:
/data/user_de/0/com.android.shell
05-27 13:54:19.248  9802  9802 I BreventServer: android providers:
{com.android.providers.calendar, com.android.providers.media,
com.android.providers.downloads, com.android.providers.downloads.ui,
com.android.providers.partnerbookmarks,
com.android.providers.blockednumber, com.android.providers.userdictionary,
com.android.providers.contacts}
05-27 13:54:19.248  9802  9802 I BreventServer: loading brevent list
05-27 13:54:19.255  9802  9802 I BreventServer: load
/data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 4
05-27 13:54:19.259  9802  9802 D BreventServer: Force stop
com.sankuai.meituan(load brevent)
05-27 13:54:19.267  9802  9802 D BreventServer: Force stop
com.tencent.tim(load brevent)
05-27 13:54:19.297  9802  9802 D BreventServer: Force stop com.anyview(load
brevent)
05-27 13:54:19.301  9802  9802 D BreventServer: Force stop
com.chaozh.iReader(load brevent)
05-27 13:54:19.302  9802  9802 I BreventServer: loading brevent conf
05-27 13:54:19.480  9802  9802 D BreventServer: check and brevent
05-27 13:54:19.946  9802  9802 D BreventServer: check again in 3600s
05-27 13:54:19.946  9802  9802 D BreventServer: check and brevent, took
466ms
05-27 13:54:19.996  9802  9802 D BreventServer: handled status
05-27 13:54:19.996  9802  9802 D BreventServer: sent first status
拔掉前是这个，拔掉后重新插USB开启adb看日记也还是这个

Liu DongMiao <notifications@github.com>于2017年5月27日周六 上午7:27写道：

**Comment by Sherlock-Holo** [comment]
Sherlock Holo <sherlockya@gmail.com>于2017年5月27日周六 13:55写道：

**Comment by Bob021** [comment]
把/sdcard/Android/data/me.piebridge.brevent/files文件夹删除掉，重新ADB启动黑域，启动后不要关闭USB调试。试试看。

**Comment by liudongmiao** [comment]
如果没有相关进程，那就没有丝毫办法。
