### ISSUE TITLE
荣耀magic 输入命令后出现如下情况，是系统不支持吗？

### ISSUE THREAD

**Issue by adrinvor** [brevent/Brevent#100]
checking for server...fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-2/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '09-14 20:08:53.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-14 20:08:53.000' -d -s BreventLoader BreventServ
er
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
09-14 20:08:55.392 27348 27348 I BreventServer: starting Brevent Server 2.1.8
09-14 20:08:55.522 27348 27348 I BreventServer: brevent user: 0, uid: 2000
09-14 20:08:55.525 27348 27348 I BreventServer: brevent data directory: /data/us
er/0/com.android.shell
09-14 20:08:55.564 27348 27348 E BreventServer: Could not access appwidget. Is t
he system running?
09-14 20:08:55.580 27337 27337 E BreventLoader: worker 27348 exited with status
1
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by adrinvor** [comment]
checking for server...fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-2/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '09-14 20:08:53.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-14 20:08:53.000' -d -s BreventLoader BreventServ
er
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
09-14 20:08:55.392 27348 27348 I BreventServer: starting Brevent Server 2.1.8
09-14 20:08:55.522 27348 27348 I BreventServer: brevent user: 0, uid: 2000
09-14 20:08:55.525 27348 27348 I BreventServer: brevent data directory: /data/us
er/0/com.android.shell
09-14 20:08:55.564 27348 27348 E BreventServer: Could not access appwidget. Is t
he system running?
09-14 20:08:55.580 27337 27337 E BreventLoader: worker 27348 exited with status
1
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above


然后按商店说明索取日志也出错。

**Comment by liudongmiao** [comment]
这....

> Could not access appwidget. Is the system running?

难不成，你的系统没有 appwidget 服务？给下我这个的输出吧：

> adb -d shell cmd -l

**Comment by adrinvor** [comment]
D:\迅雷下载\adb>adb -d shell cmd -l
/system/bin/sh: cmd: not found

D:\迅雷下载\adb>adb -d shell cmd -l
/system/bin/sh: cmd: not found

D:\迅雷下载\adb>adb -d shell cmd -l
/system/bin/sh: cmd: not found

D:\迅雷下载\adb>

**Comment by liudongmiao** [comment]
居然没有 cmd 命令，那就这个指令吧。

> adb -d shell dumpsys -l

**Comment by adrinvor** [comment]
D:\迅雷下载\adb>adb -d shell dumpsys -l
Currently running services:
  BastetService
  Binder.Pged
  DockObserver
  HsmStat
  Hwmedia.monitor
  SurfaceFlinger
  UserProfilingService
  accessibility
  account
  activity
  alarm
  android.hardware.fingerprint.IFingerprintDaemon
  android.security.keystore
  appops
  assetatlas
  attestation_service
  audio
  authentication_service
  backup
  battery
  batteryproperties
  batterystats
  bluetooth_manager
  carrier_config
  clipboard
  com.huawei.bd.BDService
  com.huawei.harassmentinterception.service.HarassmentInterceptionService
  com.huawei.netassistant.binder.notificationcallbackbinder
  com.huawei.netassistant.service.netassistantservice
  com.huawei.permissionmanager.service.holdservice
  com.huawei.systemmanager.netassistant.netnotify.policy.NatTrafficNotifyService

  com.huawei.systemmanager.netassistant.netpolicy.NatNetworkPolicyService
  com.huawei.systemmanager.preventmode.PreventModeService
  com.huawei.systemmanager.rainbow.service
  commontime_management
  connectivity
  consumer_ir
  content
  country_detector
  cover
  cpuinfo
  dbinfo
  device_policy
  deviceidle
  devicestoragemonitor
  diskstats
  display
  dreams
  drm.drmManager
  dropbox
  ethernet
  fido_authenticator
  fingerprint
  gfxinfo
  graphicsstats
  haptics
  huawei.audioalgoservice
  huawei.camera.cfgsvr
  huawei.imax.gaze.service
  hwAlarmService
  hwAntiTheftService
  hwConnectivityExService
  hwGeneralService
  hwPfwService
  hwUsbExService
  hwext_device_service
  hwfm_service
  hwsysresmanager
  ihwvsim
  imms
  ims
  ims_config
  ims_ut
  input
  input_method
  input_method_secure
  interaction
  intercept
  ioinfo
  iphonesubinfo
  isms
  isms_interception
  isub
  jank
  jankshield
  jobscheduler
  launcherapps
  location
  lock_settings
  media.audio_flinger
  media.audio_policy
  media.camera
  media.camera.proxy
  media.log
  media.player
  media.radio
  media.resource_manager
  media.sound_trigger_hw
  media_projection
  media_router
  media_session
  meminfo
  midi
  mount
  multi_task
  netpolicy
  netstats
  network_management
  network_score
  nfc
  nonhardaccelpkgs
  notification
  package
  perfhub
  permission
  pgservice
  phone
  phone_apdu
  phone_huawei
  post.camera
  power
  powerprofile
  print
  processinfo
  procstats
  restrictions
  rttmanager
  samplingprofiler
  scheduling_policy
  search
  sensorservice
  serial
  servicediscovery
  simphonebook
  smartcardservice
  statusbar
  system.hsmcore
  telecom
  telephony.registry
  textservices
  trust
  tui
  tv_controller_manager_service
  uimode
  updatelock
  usagestats
  usb
  user
  vibrator
  voiceinteraction
  vr_display
  wallpaper
  webviewupdate
  wifi
  wifip2p
  wifiscanner
  window

D:\迅雷下载\adb>

**Comment by liudongmiao** [comment]
真的没有 appwidget 服务...

**Comment by adrinvor** [comment]
那咋整，是不是这个所谓华为至未来的智能系统把服务名字改名了，哪个像啊？有没有变通方法？magic电池容量不大，太需要黑域了。麻烦分析一下呗

**Comment by liudongmiao** [comment]
等着下次发布吧

**Comment by adrinvor** [comment]
多谢！！！

**Comment by adrinvor** [comment]
多谢，去酷安下载了测试版好使了。
D:\迅雷下载\adb>adb devices
List of devices attached
adb server version (31) doesn't match this client (39); killing...
* daemon started successfully *
S3V0217324002182        device


D:\迅雷下载\adb>adb devices
List of devices attached
S3V0217324002182        device


D:\迅雷下载\adb>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server...started, pid: 24808
checking for stable....success

if you find any issues, please report bug to https://github.com/brevent/Brevent/
issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

D:\迅雷下载\adb>

**Comment by adrinvor** [comment]
必须五星，googleplay和酷安都五星！
