### ISSUE TITLE
一直显示：“电池未优化，不建议黑域”

### ISSUE THREAD

**Issue by catdog** [brevent/Brevent#101]
系统:
EMUI 5.0/Android 7.0

无论开启或者关闭
某应用的“忽略电池优化”选项，在黑域中都显示
“电池未优化，不建议黑域”

**Comment by liudongmiao** [comment]
自己去你的系统查看 电池优化 白名单，黑域不解决这类问题。只是不建议黑域，它不能待机，仅此而已。
