### ISSUE TITLE
黑域root模式下会有异常复位现象

### ISSUE THREAD

**Issue by inwind007** [brevent/Brevent#102]
zuk z1,用的的RR5.8.3 安卓7.1.2的rom,发现会随机复位，目前改用非root模式，暂时还没发现复位现象，希望能尽快解决，如果需要我提供什么数据，请告诉我如何操作，我是个新手，谢谢。

**Comment by liudongmiao** [comment]
随机这种事，不提供任何技术支持。
如果你能每次复现，再说。
