### ISSUE TITLE
安卓O间歇性关闭黑域服务

### ISSUE THREAD

**Issue by sunnoy** [brevent/Brevent#102]
在没有重启的情况下

**Comment by kcgp007** [comment]
nexus 6p 升级8.0系统也出现这种问题

**Comment by liudongmiao** [comment]
认真阅读商店详情，不要关闭调试模式，不要切换 usb 模式。

**Comment by kcgp007** [comment]
不是这中低级错误啦，升级之前还开启过，当时都没问题的。

[Android O]
Android O 下，如果关闭调试模式或者切换 USB 模式，黑域就会失效。如果拔线后，调试模式就被关闭，请尝试其它的 USB 连接选项，或者执行 adb tcpip 5555 开启网络调试后再拔线。请注意：调试模式有风险，不要随意授权。

感觉应该是这种问题，但是开启网络调试之后

D:\Android\sdk\platform-tools>adb connect 192.168.13.224:5555
already connected to 192.168.13.224:5555

D:\Android\sdk\platform-tools>adb devices
List of devices attached
192.168.13.224:5555     device

D:\Android\sdk\platform-tools>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
error: no devices found

可是执行logcat命令之类的时候却又可以，希望可以指导一下

**Comment by vvb2060** [comment]
@AuJ-King  开启网络adb后，直接打开黑域就行。另外，既然是远程连接，你为什么还要加 -d

**Comment by kcgp007** [comment]
啊啊啊～是这样吗。。。-d 只是复制过来的，重新操作了一下，用网络调试已经可以了，谢谢解答

**Comment by liudongmiao** [comment]
@AuJ-King 我又认真的检查了代码，-d 只会出现在连接了 usb 的情况下...

**Comment by kcgp007** [comment]
@liudongmiao 我可能是复制到了商店页面的命令，才有 -d 的，抱歉，可能没表述清楚
