### ISSUE TITLE
红米运行brevent，报permissions denied

### ISSUE THREAD

**Issue by jieaobuqun** [brevent/Brevent#1022]
红米K50至尊版，运行：adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
报：permissions denied，怎么处理？
OS版本：Xiaomi Hyper OS 1.0.10.0

**Comment by vvb2060** [comment]
执行弹窗提示的命令，或者使用网页 [brevent.sh](https://brevent.sh/)

**Comment by jieaobuqun** [comment]
> 执行弹窗提示的命令，或者使用网页 [brevent.sh](https://brevent.sh/)

谢谢，解决了。发现还有无线调试很方便，不需要连接PC了
