### ISSUE TITLE
和黑域关系比较小，但因为谷歌不到，所以希望解答一下

### ISSUE THREAD

**Issue by BlessWz** [brevent/Brevent#103]
1、fcm是不是不需要任何后台
2、是的话，为什么miui加入黑名单后就无法fcm？
3、但是加入白名单、不翻墙，可以fcm，这么说需要后台常驻或者后台缓存？
4、但是后台列表、缓存列表并没有应用，这是怎么回事？同样是看似没有运行，为什么加入白名单后就可以fcm，miui到底杀掉了什么？
5、黑域一个应用后，它是会和miui一样杀了fcm，还是保留了fcm？（手上这台设备无法启动黑域，所以无法试验）
求解答啊啊啊啊啊，困扰很久T_T

**Comment by liudongmiao** [comment]
1. 不需要。确切的说，需要 GMS 可用，且应用支持 FCM（微信不支持）。
2. 不知道
3. 不需要。确切的说，需要系统安装 GMS，以及你这个应用处于非停止状态。简单点，黑域内开启了允许同步。
4. FCM 需要处于非停止状态。
5. 不开启允许同步的话，不会保留。

当然回答完了以后，才发现你没用黑域。此问题关闭，不回答非黑域用户的使用问题。
