### ISSUE TITLE
private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface(     new ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package")));  public static void grantRuntimePermission(String packageName, String permissionName, int userId) {     try {         PACKAGE_MANAGER.grantRuntimePermission(packageName, permissionName, userId);     } catch (RemoteException tr) {         throw new RuntimeException(tr.getMessage(), tr);     } }

### ISSUE THREAD

**Issue by Rizki12345678900** [brevent/Brevent#1040]
private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface(
    new ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package")));

public static void grantRuntimePermission(String packageName, String permissionName, int userId) {
    try {
        PACKAGE_MANAGER.grantRuntimePermission(packageName, permissionName, userId);
    } catch (RemoteException tr) {
        throw new RuntimeException(tr.getMessage(), tr);
    }
}

**Comment by syafiqstore55** [comment]
private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface(
    new ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package")));

public static void grantRuntimePermission(String packageName, String permissionName, int userId) {
    try {
        PACKAGE_MANAGER.grantRuntimePermission(packageName, permissionName, userId);
    } catch (RemoteException tr) {
        throw new RuntimeException(tr.getMessage(), tr);
    }
}

**Comment by Nmontanye1** [comment]
I have no idea what I'm doing. I wanted to boost my crappy wifi and now I am learning (poorly). What all this means.  I do not speak code.  Where can I learn, for dummies edition

**Comment by lankhang757-lgtm** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Comment by mnghsrchrd-lang** [comment]
https://github.com/brevent/Brevent/issues/1040

**Comment by goneyuvaraj1984-netizen** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Comment by cutien0943-hub** [comment]
> private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface( new ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package")));
> 
> public static void grantRuntimePermission(String packageName, String permissionName, int userId) { try { PACKAGE_MANAGER.grantRuntimePermission(packageName, permissionName, userId); } catch (RemoteException tr) { throw new RuntimeException(tr.getMessage(), tr); }tff

**Comment by cutien0943-hub** [comment]
Fff
