### ISSUE TITLE
魅族手机 黒域2.1.7版本之后不能开启

### ISSUE THREAD

**Issue by LayneHe** [brevent/Brevent#105]
魅族 pro6s
FLyme版本：6.7.9.5Beta (Android 7.1.1)
黑域版本从2.1.7之后就不能正常通过ADB开启
日志内容：sh: /data/data/me.piebridge.brevent/brevent.sh: Permission denied

**Comment by vvb2060** [comment]
关于魅族自动返回向导，不会生成指令文件的问题，请在 #95 进行讨论。
临时可以通过执行`adb shell  /data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so`来开启服务（不同手机路径可能不同，自己对照修改下）

**Comment by liudongmiao** [comment]
请确认以下事件：

1. 2.1.7 可以工作

2. 请邮件我，我会给你一个测试版
