### ISSUE TITLE
pdf有几句话有歧义，还是再问问

### ISSUE THREAD

**Issue by BlessWz** [brevent/Brevent#105]
这次有点长，辛苦大大了
1、为什么微信明明加入了黑域却杀不掉，只有黑域加强行停止操作才会永久被杀光，这算bug？还是故意这样做的？（显示是电池未优化应用）
2、电池未优化应用是什么意思？例如qq，微信也是
3、我试了一下，关闭待机，后台超时1分钟，后台模式，然后眼睁睁看见闹钟图标时间3分钟了应用还没被关掉，“黑域方法”里不是说好的超时了就强行停止了吗？这是什么情况Σ(ﾟдﾟlll)
4、打开黑域，一直等到某个app计时到2分钟吧，划掉黑域，随便过多久，打开黑域，发现重新计时了，也就是说，判断后台超时的计时，只在黑域在总览里的时候有效，从总览划掉成为非可视后台后就不计时了(ﾟДﾟ≡ﾟДﾟ)?what？那后台超时不就是个摆设吗？不是的话怎么解释这个现象
5、为什么“一个缓存进程”黑域符号是一个圈，这是什么情况，含义是什么？pdf没说
6、“服务进程”和“缓存进程”有什么区别？一个会耗电，一个不耗电？缓存进程是不是类似墓碑机制？记忆后便于恢复？
7、那“1个服务，2个进程”又是几个意思啊？1服务加1缓存？
8、举例，微信不黑域，从总览划掉，去黑域查看，有时间计数；outlook不黑域，从总览划掉，照理说也应该有后台时间计数，但却没有，为什么？（两个都是一个服务进程）
9、一个黑域了且没有同步的应用，从总览里划掉后（彻底杀掉后台）能否fcm？经测试，不能。接上一个issue，你不是说fcm不需要后台吗？那为什么还不能？请给一个合理的解释啊啊啊啊啊啊😭
10、但是，与fcm不同，彻底杀死一个app后能收到mipush(　ﾟ皿ﾟ)！什么情况？但是只能收到一些公共通知，例如：斗鱼直播了、微博一些公共热点，但都收不到私信，打开app才有私信消息，这时候彻底关闭app，私信消息会fc，但是公共消息还在……难道说mipush和fcm不一样？但不都是开发者到谷歌或小米，然后它们推送到手机吗，只要miuisdk和gcm service在就好了呀……还是说调起通知的机制不一样，fcm需要后台？不过你说不需要后台……你之前说过你用的不是miui，如果你也不知道的话就算了
伪12、开了允许同步和黑域的应用，从总览里划掉，过一两分钟，显示没有运行，但是，这个没有运行和不开同步的没有运行不同，是收得到fcm的，那么，问问题
12、是怎么做到彻底关闭了app又保留了fcm的呢，与以前的阻止运行和现在不开同步的黑域相比，好像是新机制？是看似没有运行，实际保留了一点东西对吧？能通俗地解释一下么？（如果你觉得你说了我也听不懂的话那就算了……)
13、允许同步的没有运行会比没有同步的没有运行耗电吗？
14、我猜不会，那么，为什么不把同步集成进黑域里面啊(´△｀)，黑域的同时又自带推送消息，这不是很好吗？（反正又不多耗电）为什么一定要两个割裂开来，先黑域保证不会后台常驻来端内推送是肯定的，但是我想要fcm的话，得再一个一个的去设置（关键是还没有批量设置），麻烦不说，重点是难道以后我装一个支持fcm的app就得去黑域里打开同步一下吗？呵呵，那我干脆放弃fcm算了（╯－＿－）╯╧╧      柳大开发的时候是怎么想的呢？
15（建议）、为什么有的应用因为无障碍，桌面app等原因无法黑域，例如“全局复制”、“nova launcher”，希望解除这个限制，以前阻止运行不是没有这个限制吗？
16（建议）、做阻止运行的时候有“强行停止app”，为啥黑域反而没了呀，建议也加上，原因是：一个app已在总览里划掉，但仍在后台运行，这时候我把它加入了黑域列表，但它依然在运行，想让这个黑域操作当即起效的办法是再去打开这个app，从总览里划掉。（阻止运行的时候貌似刷新一下列表就会让操作起效，但黑域刷新列表好像没用，所以只能用这个办法）但这样很麻烦，加入一键强行停止的话会好很多
17、一天前真正的问题(╥ω╥`)  ……我的三星平板刷了AEX，7.1.2，supersu2.79，可以adb开启黑域，无法root开启。上次你说日志不清晰，那么日志该用什么app截呢？怎么截呢，？上次用的log viewer，一打开app日志疯狂产生，完全不知道该给哪一段，就找了有brevent的一小段，貌似不行，谷歌上没有关于怎么截日志给开发者的文章啊，所以请说明一下，感谢柳大

**Comment by vvb2060** [comment]
issues是缺陷跟踪，避免提与黑域无关的issue。
黑域行为与预期不符，一个情况一个issue，同时注意测试版是否已解决问题。
读更新记录和历史issues会解决你大部分疑问，比如允许同步：#54

提取黑域日志`adb logcat -d -s BreventServer BreventLoader`

>

**Comment by liudongmiao** [comment]
这次有点长，辛苦大大了
1、为什么微信明明加入了黑域却杀不掉，只有黑域加强行停止操作才会永久被杀光，这算bug？还是故意这样做的？（显示是电池未优化应用）
参照说明

2、电池未优化应用是什么意思？例如qq，微信也是
字面意思

3、我试了一下，关闭待机，后台超时1分钟，后台模式，然后眼睁睁看见闹钟图标时间3分钟了应用还没被关掉，“黑域方法”里不是说好的超时了就强行停止了吗？这是什么情况Σ(ﾟдﾟlll)
等下次执行。此外依赖事件。

4、打开黑域，一直等到某个app计时到2分钟吧，划掉黑域，随便过多久，打开黑域，发现重新计时了，也就是说，判断后台超时的计时，只在黑域在总览里的时候有效，从总览划掉成为非可视后台后就不计时了(ﾟДﾟ≡ﾟДﾟ)?what？那后台超时不就是个摆设吗？不是的话怎么解释这个现象
是指黑域还是其它应用？
黑域的话，你又打开了，所以重新计算。
其它应用，偶然会有这种情况，非正常返回所致，强行停止它们，强行停止启动器。

5、为什么“一个缓存进程”黑域符号是一个圈，这是什么情况，含义是什么？pdf没说
非服务进程是安全的，不建议处理。如果持续没有服务，建议直接不要黑域。

6、“服务进程”和“缓存进程”有什么区别？一个会耗电，一个不耗电？缓存进程是不是类似墓碑机制？记忆后便于恢复？
涉及 Android 底层知识，阻止运行那边有我翻译的文档。

7、那“1个服务，2个进程”又是几个意思啊？1服务加1缓存？
Android 是多进程。

8、举例，微信不黑域，从总览划掉，去黑域查看，有时间计数；outlook不黑域，从总览划掉，照理说也应该有后台时间计数，但却没有，为什么？（两个都是一个服务进程）
所见非所得，黑域需要时间统计系统状态。理论都不会有。

9、一个黑域了且没有同步的应用，从总览里划掉后（彻底杀掉后台）能否fcm？经测试，不能。接上一个issue，你不是说fcm不需要后台吗？那为什么还不能？请给一个合理的解释啊啊啊啊啊啊😭
国内 ROM 应该不能，因为还会强行停止，把应用置为停止状态。
停止状态不能接收 FCM 消息。允许同步后，黑域检测到被外部应用强行停止以后，取消停止状态。

10、但是，与fcm不同，彻底杀死一个app后能收到mipush(　ﾟ皿ﾟ)！什么情况？但是只能收到一些公共通知，例如：斗鱼直播了、微博一些公共热点，但都收不到私信，打开app才有私信消息，这时候彻底关闭app，私信消息会fc，但是公共消息还在……难道说mipush和fcm不一样？但不都是开发者到谷歌或小米，然后它们推送到手机吗，只要miuisdk和gcm service在就好了呀……还是说调起通知的机制不一样，fcm需要后台？不过你说不需要后台……你之前说过你用的不是miui，如果你也不知道的话就算了

不知道。本地测过魅族，它是自己的推送服务推送的消息，虽然显示应用图标，但应用并没有唤醒。然后点击消息，跳到应用。本地黑域“推送服务”即可。miui 估计和这个类似。
一般来说，如果没有允许同步，有消息来时，只要有服务，就会强行停止。
如果没有服务，通知会保留（非激进模式仅强行停止服务进程）。接下来，可能优化。


伪12、开了允许同步和黑域的应用，从总览里划掉，过一两分钟，显示没有运行，但是，这个没有运行和不开同步的没有运行不同，是收得到fcm的，那么，问问题

我优化了它，参见 FCM 要求。

12、是怎么做到彻底关闭了app又保留了fcm的呢，与以前的阻止运行和现在不开同步的黑域相比，好像是新机制？是看似没有运行，实际保留了一点东西对吧？能通俗地解释一下么？（如果你觉得你说了我也听不懂的话那就算了……)

我优化了它，参见 FCM 要求。
大致的原理，可以阅读这个：http://www.jianshu.com/p/efdc9e6c2935

13、允许同步的没有运行会比没有同步的没有运行耗电吗？
都没有运行，你说呢...

14、我猜不会，那么，为什么不把同步集成进黑域里面啊(´△｀)，黑域的同时又自带推送消息，这不是很好吗？（反正又不多耗电）为什么一定要两个割裂开来，先黑域保证不会后台常驻来端内推送是肯定的，但是我想要fcm的话，得再一个一个的去设置（关键是还没有批量设置），麻烦不说，重点是难道以后我装一个支持fcm的app就得去黑域里打开同步一下吗？呵呵，那我干脆放弃fcm算了（╯－＿－）╯╧╧ 柳大开发的时候是怎么想的呢？

这个功能叫允许同步。
系统账号里有太多流氓，同时，也有太多应用声称支持 FCM，却只是用来发广告。
至于不提供批量，因为界面上已经有两个按钮了，再来两个依赖的按钮，界面丑。
我个人认为，这个操作要慎重，所以加大处理复杂度。


15（建议）、为什么有的应用因为无障碍，桌面app等原因无法黑域，例如“全局复制”、“nova launcher”，希望解除这个限制，以前阻止运行不是没有这个限制吗？
你会经常用到了它，强行停止它们再启动，除了浪费电，还能干啥？

16（建议）、做阻止运行的时候有“强行停止app”，为啥黑域反而没了呀，建议也加上，原因是：一个app已在总览里划掉，但仍在后台运行，这时候我把它加入了黑域列表，但它依然在运行，想让这个黑域操作当即起效的办法是再去打开这个app，从总览里划掉。（阻止运行的时候貌似刷新一下列表就会让操作起效，但黑域刷新列表好像没用，所以只能用这个办法）但这样很麻烦，加入一键强行停止的话会好很多

我做的版本一直没有。因为给你了按钮，还要考虑界面怎么刷新的问题。
所以，给了详情，你点进详情去强行停止吧。
你这个不生效，等下次黑域时机。回到桌面 3 秒，打开应用 30 秒，以及其它触发情况。
如果你一直切换，你猜我为了节省你的电，是会每次都黑域，还是一直不黑域等你最后那次结束？

17、一天前真正的问题(╥ω╥`) ……我的三星平板刷了AEX，7.1.2，supersu2.79，可以adb开启黑域，无法root开启。上次你说日志不清晰，那么日志该用什么app截呢？怎么截呢，？上次用的log viewer，一打开app日志疯狂产生，完全不知道该给哪一段，就找了有brevent的一小段，貌似不行，谷歌上没有关于怎么截日志给开发者的文章啊，所以请说明一下，感谢柳大

你每次启动黑域时，黑域都有清晰的提示，告诉你怎么提取日志。
同时，在应用商店详情，底部也是日志提取方法，你不看，怪我？
你不看，反而来这里不断的问，除了浪费你我时间，还能干啥？

以上，请按每字 0.1 元付费。

最新测试版，支持提取日志。但，仅对于成功使用的用户。
而不成功的用户，首次启动时，就已经有异常提示了。

**Comment by BlessWz** [comment]
1、启动黑域的时候没有日志提示 ，只有用adb开启方法2、我没有怪你，是你自己在yy 3、我问的根本就不是日志问题好吧，逗我呢，是你自己很多东西pdf没说清楚，打这些，想这些，我也费了很长时间，我只是想诚恳地问些问题罢了，我弄了这么久，你就这种态度，我真是无奈了，酷安就三条指令，什么都不说就放在那，想让小白直接看懂我也是呵呵了，我什么时候不断问日志的事了，就最后提到了一下，我好好地提问，你觉得不对就指出来，心平气和的不就行了嘛，这都能闹脾气，你小孩子吗？
4、之前就在pc端adb输入了酷安最后的一条服务日志，（黑域运行完后）然后就出来了这三条，所以这让我怎么上传？我看别人的代码都很长，觉得这样应该不对，才找了别服务日志的日志软件，找了半天bre相关代码，这是C:\Users\Administrator\Desktop\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
07-16 16:47:28.345 11849 11849 E BreventLoader: worker 11852 exited with status 255
07-16 16:49:23.112 12251 12251 E BreventLoader: worker 12259 exited with status 255
07-16 16:54:13.920 12461 12461 E BreventLoader: worker 12466 exited with status 255

**Comment by liudongmiao** [comment]
1. 你用 adb 开启，不论成功或失败，都会有提示告诉你提取日志。

2. 不是我 yy，就是字面意思，系统给的。如果不是你自己设的，就是系统默认的。

3. pdf 从来就没想要把问题全部说清楚。你咋不说，怎么没有英文版呢？

4. 如果只有这些，是你自己系统日志问题，不显示 Debug, Warning, Info 级别日志。

**Comment by liudongmiao** [comment]
社区问问题，请尽量简单，没人有这耐心。真有问题，就带日志，不带日志，不回答问题。
