### ISSUE TITLE
开启错误

### ISSUE THREAD

**Issue by wagaaa** [brevent/Brevent#106]
oneplus3:/ $ sh /data/data/me.piebridge.brevent/brevent.sh
rm: /data/local/tmp/brevent: Permission denied
WARNING: /data/local/tmp is not writalbe
ERROR: cannot be run as u0_a137(10137).
1|oneplus3:/ $ su
oneplus3:/ # sh /data/data/me.piebridge.brevent/brevent.sh
WARNING: run as root is experimental!!!
checking...brevent_server started, pid: 30810
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below--- crash start ---
>>> logcat -b crash -t '07-17 08:31:53.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-17 08:31:53.000' -d -s BreventLoader BreventServer
07-17 08:31:54.187 30799 30799 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-17 08:31:54.553 30810 30810 D BreventServer: get service: package
07-17 08:31:54.562 30810 30810 I BreventServer: starting Brevent Server 1.3.407-17 08:31:54.569 30810 30810 D BreventServer: get service: package
07-17 08:31:54.571 30810 30810 I BreventServer: brevent user: 0, uid: 0
07-17 08:31:54.572 30810 30810 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-17 08:31:54.585 30810 30810 I BreventServer: loading brevent list
07-17 08:31:54.585 30810 30810 I BreventServer: loading brevent conf
07-17 08:31:54.588 30810 30810 D BreventServer: get service: appwidget
07-17 08:31:54.596 30810 30810 D BreventServer: get service: usagestats
07-17 08:31:55.483 30810 30821 I BreventServer: Brevent Event, now: 1500251515
07-17 08:31:55.484 30810 30810 D BreventServer: check and brevent
07-17 08:31:55.486 30810 30810 D BreventServer: get service: notification
07-17 08:31:55.493 30810 30821 I BreventServer: system_server: 1164, now: 1500251515
07-17 08:31:55.636 30810 30810 D BreventServer: get service: activity
07-17 08:31:55.668 30810 30810 D BreventServer: get service: alarm
07-17 08:31:55.669 30810 30810 D BreventServer: get service: wallpaper
07-17 08:31:55.700 30810 30810 D BreventServer: get service: batterystats
07-17 08:31:55.808 30810 30810 D BreventServer: check again in 3600s
07-17 08:31:55.809 30810 30810 D BreventServer: check and brevent, took 324ms07-17 08:31:55.811 30810 30810 I BreventServer: charging: false
07-17 08:31:55.811 30810 30810 I BreventServer: support standby: true
07-17 08:31:55.811 30810 30810 I BreventServer: support stopped: true
07-17 08:31:55.817 30810 30810 E BreventServer: Can't be run as root, please open Brevent
07-17 08:31:55.839 30799 30799 E BreventLoader: worker 30810 exited with status 1
07-17 08:31:55.839 30799 30799 D BreventLoader: signal arrived, update: 0
07-17 08:31:55.841 30795 30795 D BreventLoader: worker 30799 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above
1|oneplus3:/ #

**Comment by vvb2060** [comment]
>07-17 08:31:55.817 30810 30810 E BreventServer: Can't be run as root, please open Brevent

按照向导中的方法进行root开启
