### ISSUE TITLE
一直处于正在获取进程状态，请稍后……

### ISSUE THREAD

**Issue by longsir123** [brevent/Brevent#107]
跳转到了请启动黑域服务
向导  复制指令

之前已经开启了黑域，并且成功了运行使用。一段时间后就会出现这样问题。手机并没有重启

**Comment by vvb2060** [comment]
需要日志……
```
adb logcat -d -s BreventServer BreventLoader
```

**Comment by longsir123** [comment]
E:\Oneplus>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
found old brevent_server, pid: 2234, killing
checking...brevent_server started, pid: 13189
checking for stable...........ok

if you find any issues, please report bug to https://github.com/brevent/Brevent/
issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

E:\Oneplus>adb logcat -d -s BreventServer BreventLoader
--------- beginning of crash
--------- beginning of system
--------- beginning of main
07-17 14:23:33.185  2234  2234 D BreventServer: update current to net.oneplus.la
uncher
07-17 14:23:36.190  2234  2234 D BreventServer: check and brevent
07-17 14:23:36.296  2234  2234 D BreventServer: check again in 3600s
07-17 14:23:36.296  2234  2234 D BreventServer: check and brevent, took 103ms
07-17 14:23:52.034  2234  2234 D BreventServer: check and brevent
07-17 14:23:52.177  2234  2234 D BreventServer: check again in 3600s
07-17 14:23:52.177  2234  2234 D BreventServer: check and brevent, took 139ms
07-17 14:25:03.603  2234  2234 D BreventServer: update current to me.piebridge.b
revent
07-17 14:25:11.740  2234  2234 D BreventServer: update current to com.android.sy
stemui
07-17 14:25:12.860  2234  2234 D BreventServer: check and brevent
07-17 14:25:13.011  2234  2234 D BreventServer: check again in 3600s
07-17 14:25:13.011  2234  2234 D BreventServer: check and brevent, took 148ms
07-17 14:25:14.726  2234  2234 D BreventServer: update current to me.piebridge.b
revent
07-17 14:25:26.045  2234  2234 D BreventServer: check and brevent
07-17 14:25:26.196  2234  2234 D BreventServer: Force stop com.oneplus.market(no
Recent)
07-17 14:25:26.197  2234  2234 D BreventServer: check again in 3600s
07-17 14:25:26.197  2234  2234 D BreventServer: check and brevent, took 148ms
07-17 14:40:01.660  2234  2234 D BreventServer: update current to com.android.sy
stemui
07-17 14:40:02.403  2234  2234 D BreventServer: update current to net.oneplus.la
uncher
07-17 14:40:05.403  2234  2234 D BreventServer: check and brevent
07-17 14:40:05.507  2234  2234 D BreventServer: Force stop com.oneplus.market(no
Recent)
07-17 14:40:05.508  2234  2234 D BreventServer: check again in 3600s
07-17 14:40:05.508  2234  2234 D BreventServer: check and brevent, took 104ms
07-17 14:40:18.813  2223  2223 E BreventLoader: worker 2234 exited on signal 15
07-17 14:40:18.813  2223  2223 D BreventLoader: signal arrived, update: 0
07-17 14:40:19.250 13178 13178 D BreventLoader: loader path: /data/app/me.piebri
dge.brevent-1/base.apk
07-17 14:40:19.625 13189 13189 D BreventServer: get service: package
07-17 14:40:19.627 13189 13189 I BreventServer: starting Brevent Server 1.3.4
07-17 14:40:19.631 13189 13189 D BreventServer: get service: package
07-17 14:40:19.633 13189 13189 I BreventServer: brevent user: 0, uid: 2000
07-17 14:40:19.634 13189 13189 I BreventServer: brevent data directory: /data/us
er_de/0/com.android.shell
07-17 14:40:19.643 13189 13189 I BreventServer: loading brevent list
07-17 14:40:19.645 13189 13189 I BreventServer: load /data/user_de/0/com.android
.shell/me.piebridge.brevent.list, size: 38
07-17 14:40:19.654 13189 13189 I BreventServer: loading brevent conf
07-17 14:40:19.656 13189 13189 D BreventServer: get service: appwidget
07-17 14:40:19.663 13189 13189 D BreventServer: get service: usagestats
07-17 14:40:19.895 13189 13200 I BreventServer: Brevent Event, now: 1500273619
07-17 14:40:19.896 13189 13189 D BreventServer: check and brevent
07-17 14:40:19.902 13189 13189 D BreventServer: get service: notification
07-17 14:40:19.919 13189 13200 I BreventServer: system_server: 1430, now: 150027
3619
07-17 14:40:19.938 13189 13189 D BreventServer: get service: activity
07-17 14:40:19.945 13189 13189 D BreventServer: get service: alarm
07-17 14:40:19.948 13189 13189 D BreventServer: get service: wallpaper
07-17 14:40:19.961 13189 13189 D BreventServer: get service: batterystats
07-17 14:40:20.042 13189 13189 D BreventServer: check again in 3600s
07-17 14:40:20.042 13189 13189 D BreventServer: check and brevent, took 140ms
07-17 14:40:20.044 13189 13189 I BreventServer: charging: false
07-17 14:40:20.044 13189 13189 I BreventServer: support standby: true
07-17 14:40:20.044 13189 13189 I BreventServer: support stopped: true
07-17 14:40:20.044 13189 13189 I BreventServer: Brevent Server 1.3.4 started

**Comment by vvb2060** [comment]
这些日志都很正常……
你可以把日志缓冲区调高：开发者选项-日志记录器缓冲区大小，下次出现问题再提取日志
```
adb logcat -b main -d -s BreventLoader BreventServer BreventUI
```

**Comment by longsir123** [comment]
已经把日志记录器缓冲区大小 调成了16M，然后卸载了黑域，清除了它数据和缓存，重启之后，再次安装黑域，指令执行，黑域正常进入，现在不知道是否还会出现一直获取进程的状态。正在测试中。。。

**Comment by liudongmiao** [comment]
下次出现，第一时间获取日志吧。
