### ISSUE TITLE
2.0.1在adb下启动问题，Android 7.1.2和5.1.1均有出现

### ISSUE THREAD

**Issue by Han9402** [brevent/Brevent#108]
设备型号：华为荣耀5X（KIW-UL00）
Android版本：7.1.2
系统版本：lineage-14.1-20170712-nightly-kiwi-signed

报错内容

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-18 07:24:19.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-18 07:24:19.000' -d -s BreventLoader BreventServer
07-18 07:24:20.803  9172  9172 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-18 07:24:21.761  9183  9183 D BreventServer: get service: package
07-18 07:24:21.762  9183  9183 D BreventServer: args: [10]
07-18 07:24:21.762  9183  9183 I BreventServer: signal: 10
07-18 07:24:21.767  9183  9183 I BreventServer: starting Brevent Server 2.0.1
07-18 07:24:21.782  9183  9183 D BreventServer: get service: package
07-18 07:24:21.785  9183  9183 I BreventServer: brevent user: 0, uid: 2000
07-18 07:24:21.787  9183  9183 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-18 07:24:21.822  9183  9183 I BreventServer: loading brevent list
07-18 07:24:21.829  9183  9183 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 92
07-18 07:24:21.832  9183  9183 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:24:21.832  9183  9183 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:24:21.832  9183  9183 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
07-18 07:24:21.832  9183  9183 E BreventServer:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
07-18 07:24:21.832  9183  9183 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
07-18 07:24:21.832  9183  9183 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
07-18 07:24:21.832  9183  9183 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
07-18 07:24:21.832  9183  9183 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
07-18 07:24:21.832  9183  9183 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
07-18 07:24:21.832  9183  9183 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-18 07:24:21.832  9183  9183 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:264)
07-18 07:24:21.853  9172  9172 E BreventLoader: worker 9183 exited with status 1
07-18 07:24:21.853  9172  9172 D BreventLoader: signal arrived, update: 0
07-18 07:24:21.854  9167  9167 D BreventLoader: worker 9172 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by Han9402** [comment]
而且黑域经常不知道被谁杀掉 目前手机上只有黑域和绿色守护 均设置了互不处理

**Comment by Han9402** [comment]
设备型号：华为荣耀3C（H30-L20)
Android版本：5.1.1
系统版本：EMUI 3.1

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-18 07:35:28.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-18 07:35:28.000' -d -s BreventLoader BreventServer
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
I/BreventServer(32627): signal: 10
I/BreventServer(32627): starting Brevent Server 2.0.1
I/BreventServer(32627): brevent user: 0, uid: 2000
I/BreventServer(32627): brevent data directory: /data/data/com.android.shell
I/BreventServer(32627): loading brevent list
I/BreventServer(32627): load /data/data/com.android.shell/me.piebridge.brevent.list, size: 63
E/BreventServer(32627): Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
E/BreventServer(32627): java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
E/BreventServer(32627):         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
E/BreventServer(32627):         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
E/BreventServer(32627):         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
E/BreventServer(32627):         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
E/BreventServer(32627):         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
E/BreventServer(32627):         at java.lang.reflect.Method.invoke(Native Method)
E/BreventServer(32627):         at java.lang.reflect.Method.invoke(Method.java:372)
E/BreventServer(32627):         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
E/BreventServer(32627):         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/BreventServer(32627):         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
E/BreventLoader(32612): worker 32627 exited with status 1
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by Han9402** [comment]
应用下载来源：http://coolapk.com/apk/me.piebridge.brevent

**Comment by Han9402** [comment]
2.0.2已更新，问题已解决，但输完adb命令后，直接回退到上个应用界面，望修复

**Comment by liudongmiao** [comment]
@Han9402 这是正常的。
首次执行时，会给黑域授予日志权限（READ_LOGS），仅一次。

有了这个，在黑域内可以直接读取日志，并以邮件方式发送。
