### ISSUE TITLE
8.0下使用root启动失败

### ISSUE THREAD

**Issue by docps4** [brevent/Brevent#109]
--- crash start ---
[command] logcat -b crash -t '09-22 10:33:52.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-22 10:33:52.000' -d -s BreventLoader BreventServer
09-22 10:33:53.407 23751 23751 D BreventLoader: line: package:/data/app/me.piebridge.brevent-4RGGE2sKuL7L_d9Fo6eUdA==/base.apk
09-22 10:33:53.433 23751 23751 D BreventLoader: loader path: /data/app/me.piebridge.brevent-4RGGE2sKuL7L_d9Fo6eUdA==/base.apk
09-22 10:33:53.434 23770 23770 D BreventLoader: start: 1506047632
09-22 10:33:54.505 23770 23770 I BreventServer: starting Brevent Server 2.1.10
09-22 10:33:54.543 23770 23770 I BreventServer: brevent user: 0, uid: 0
09-22 10:33:54.545 23770 23770 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
09-22 10:33:54.628 23770 23770 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 3
09-22 10:33:55.219 23770 23790 I BreventServer: Brevent Event, now: 1506047635
09-22 10:33:55.237 23770 23790 I BreventServer: system_server: 807, now: 1506047635
09-22 10:33:55.436 23770 23770 W BreventServer: no tracks
09-22 10:33:55.818 23770 23770 I BreventServer: notification_cancel_all events: 1
09-22 10:33:55.821 23770 23770 I BreventServer: charging: false
09-22 10:33:55.821 23770 23770 I BreventServer: support standby: true
09-22 10:33:55.822 23770 23770 I BreventServer: support stopped: true
09-22 10:33:55.823 23770 23770 I BreventServer: support upgrade: true
09-22 10:33:55.839 23770 23770 E BreventServer: ROOT is unsupported for Android O
09-22 10:33:55.863 23751 23751 E BreventLoader: worker 23770 exited with status 1
09-22 10:33:55.863 23751 23751 D BreventLoader: signal arrived, update: 0
09-22 10:33:55.865 23746 23746 D BreventLoader: worker 23751 exited with status 0
--- brevent end ---

**Comment by vvb2060** [comment]
目前暂不支持在Android O上通过ROOT启动服务，请使用电脑或网络adb。

**Comment by liudongmiao** [comment]
降到 2.1.9e，确认支付开启允许  ROOT 启动再升上来；或者 adb 方式启动，确认支付开启允许 ROOT 启动再使用。
