### ISSUE TITLE
2.0.1在安卓5.1上无法启动

### ISSUE THREAD

**Issue by jiangming1399** [brevent/Brevent#109]
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xda0
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0x1
WARNING: run as root is experimental!!!
checking for server..started, pid: 9090
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-18 07:30:50.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-18 07:30:50.000' -d -s BreventLoader BreventServer
D/BreventLoader( 9076): loader path: /data/app/me.piebridge.brevent-2/base.apk
D/BreventServer( 9090): get service: package
D/BreventServer( 9090): args: [10]
I/BreventServer( 9090): signal: 10
I/BreventServer( 9090): starting Brevent Server 2.0.1
D/BreventServer( 9090): get service: package
I/BreventServer( 9090): brevent user: 0, uid: 0
I/BreventServer( 9090): brevent data directory: /data/data/com.android.shell
I/BreventServer( 9090): loading brevent list
I/BreventServer( 9090): load /data/data/com.android.shell/me.piebridge.brevent.list, size: 24
E/BreventServer( 9090): Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
E/BreventServer( 9090): java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
E/BreventServer( 9090):         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
E/BreventServer( 9090):         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
E/BreventServer( 9090):         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
E/BreventServer( 9090):         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
E/BreventServer( 9090):         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
E/BreventServer( 9090):         at java.lang.reflect.Method.invoke(Native Method)
E/BreventServer( 9090):         at java.lang.reflect.Method.invoke(Method.java:372)
E/BreventServer( 9090):         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
E/BreventServer( 9090):         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/BreventServer( 9090):         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:250)
E/BreventLoader( 9076): worker 9090 exited with status 1
D/BreventLoader( 9076): signal arrived, update: 0
D/BreventLoader( 9072): worker 9076 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by Han9402** [comment]
2.0.2版本正常运行

**Comment by liudongmiao** [comment]
已发布 2.0.2
