### ISSUE TITLE
九游 app 居然黑域无效

### ISSUE THREAD

**Issue by imoldchen** [brevent/Brevent#110]
九游的app应该是针对黑域做了反禁止功能，只要运行九游的游戏，例如崩坏3，九游就会自动不被黑域了，下次重启，九游就不在黑域列表而且常驻后台一个服务进程。它就是用来领九游的游戏礼包而已，官方非要把它做成一个服务，还收集本机游戏由它来运行，挺恶心的。

**Comment by vvb2060** [comment]
应用如果没有root权限，不能修改黑域清单。黑域会对无障碍、桌面应用、输入法等自动取消黑域，但这只发生在打开黑域应用时，并且有提示。
请说明九游是何时被取消黑域的，打开九游时？重启手机后？还是打开黑域，底部出现“已取消”提示后。

**Comment by liudongmiao** [comment]
@imoldchen 以你的表现，大约是闹钟。目前黑域自动反禁止闹钟与壁纸。
具体的话，你可以带上日志看看。
