### ISSUE TITLE
三星c7安装2.0.1后，重新adb后报错

### ISSUE THREAD

**Issue by a1121611810** [brevent/Brevent#110]
checking for server...cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-18 07:41:16.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-18 07:41:16.000' -d -s BreventLoader BreventServer
07-18 07:40:19.896  9544  9544 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-18 07:40:20.496  9555  9555 D BreventServer: get service: package
07-18 07:40:20.496  9555  9555 D BreventServer: args: [10]
07-18 07:40:20.496  9555  9555 I BreventServer: signal: 10
07-18 07:40:20.516  9555  9555 I BreventServer: starting Brevent Server 2.0.1
07-18 07:40:20.526  9555  9555 D BreventServer: get service: package
07-18 07:40:20.526  9555  9555 I BreventServer: brevent user: 0, uid: 2000
07-18 07:40:20.526  9555  9555 I BreventServer: brevent data directory: /data/user/0/com.android.shell
07-18 07:40:20.606  9555  9555 I BreventServer: loading brevent list
07-18 07:40:20.606  9555  9555 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 66
07-18 07:40:20.616  9555  9555 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:40:20.616  9555  9555 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:40:20.616  9555  9555 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
07-18 07:40:20.616  9555  9555 E BreventServer:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
07-18 07:40:20.616  9555  9555 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
07-18 07:40:20.616  9555  9555 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
07-18 07:40:20.616  9555  9555 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
07-18 07:40:20.616  9555  9555 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
07-18 07:40:20.616  9555  9555 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
07-18 07:40:20.616  9555  9555 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-18 07:40:20.616  9555  9555 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)
07-18 07:40:20.626  9544  9544 E BreventLoader: worker 9555 exited with status 1
07-18 07:40:20.626  9544  9544 D BreventLoader: signal arrived, update: 0
07-18 07:40:20.626  9536  9536 D BreventLoader: worker 9544 exited with status 0
07-18 07:40:27.346  9619  9619 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-18 07:40:27.936  9658  9658 D BreventServer: get service: package
07-18 07:40:27.936  9658  9658 D BreventServer: args: [10]
07-18 07:40:27.936  9658  9658 I BreventServer: signal: 10
07-18 07:40:27.956  9658  9658 I BreventServer: starting Brevent Server 2.0.1
07-18 07:40:27.966  9658  9658 D BreventServer: get service: package
07-18 07:40:27.966  9658  9658 I BreventServer: brevent user: 0, uid: 2000
07-18 07:40:27.966  9658  9658 I BreventServer: brevent data directory: /data/user/0/com.android.shell
07-18 07:40:28.056  9658  9658 I BreventServer: loading brevent list
07-18 07:40:28.056  9658  9658 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 66
07-18 07:40:28.066  9658  9658 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:40:28.066  9658  9658 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:40:28.066  9658  9658 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
07-18 07:40:28.066  9658  9658 E BreventServer:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
07-18 07:40:28.066  9658  9658 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
07-18 07:40:28.066  9658  9658 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
07-18 07:40:28.066  9658  9658 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
07-18 07:40:28.066  9658  9658 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
07-18 07:40:28.066  9658  9658 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
07-18 07:40:28.066  9658  9658 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-18 07:40:28.066  9658  9658 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)
07-18 07:40:28.076  9619  9619 E BreventLoader: worker 9658 exited with status 1
07-18 07:40:28.076  9619  9619 D BreventLoader: signal arrived, update: 0
07-18 07:40:28.076  9597  9597 D BreventLoader: worker 9619 exited with status 0
07-18 07:41:16.886  9843  9843 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-18 07:41:17.546  9853  9853 D BreventServer: get service: package
07-18 07:41:17.546  9853  9853 D BreventServer: args: [10]
07-18 07:41:17.546  9853  9853 I BreventServer: signal: 10
07-18 07:41:17.566  9853  9853 I BreventServer: starting Brevent Server 2.0.1
07-18 07:41:17.576  9853  9853 D BreventServer: get service: package
07-18 07:41:17.576  9853  9853 I BreventServer: brevent user: 0, uid: 2000
07-18 07:41:17.576  9853  9853 I BreventServer: brevent data directory: /data/user/0/com.android.shell
07-18 07:41:17.666  9853  9853 I BreventServer: loading brevent list
07-18 07:41:17.666  9853  9853 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 66
07-18 07:41:17.666  9853  9853 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:41:17.666  9853  9853 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 07:41:17.666  9853  9853 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
07-18 07:41:17.666  9853  9853 E BreventServer:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
07-18 07:41:17.666  9853  9853 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
07-18 07:41:17.666  9853  9853 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
07-18 07:41:17.666  9853  9853 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
07-18 07:41:17.666  9853  9853 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
07-18 07:41:17.666  9853  9853 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
07-18 07:41:17.666  9853  9853 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-18 07:41:17.666  9853  9853 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)
07-18 07:41:17.676  9843  9843 E BreventLoader: worker 9853 exited with status 1
07-18 07:41:17.676  9843  9843 D BreventLoader: signal arrived, update: 0
07-18 07:41:17.676  9838  9838 D BreventLoader: worker 9843 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
已发布 2.0.2
