### ISSUE TITLE
更新至2.0.1後無法啟動黑域服務

### ISSUE THREAD

**Issue by sykh2011** [brevent/Brevent#111]
附上Log
![default](https://user-images.githubusercontent.com/14211360/28296498-3e2d89ca-6b9b-11e7-9ad7-4e4c12418a96.JPG)

**Comment by zfmy** [comment]
+1


checking for server...cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-18 09:32:17.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-18 09:32:17.000' -d -s BreventLoader BreventServer
07-18 09:32:18.437 20578 20578 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-18 09:32:19.197 20589 20589 D BreventServer: get service: package
07-18 09:32:19.199 20589 20589 D BreventServer: args: [10]
07-18 09:32:19.199 20589 20589 I BreventServer: signal: 10
07-18 09:32:19.203 20589 20589 I BreventServer: starting Brevent Server 2.0.1
07-18 09:32:19.211 20589 20589 D BreventServer: get service: package
07-18 09:32:19.212 20589 20589 I BreventServer: brevent user: 0, uid: 2000
07-18 09:32:19.214 20589 20589 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-18 09:32:19.230 20589 20589 I BreventServer: loading brevent list
07-18 09:32:19.233 20589 20589 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 46
07-18 09:32:19.234 20589 20589 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 09:32:19.234 20589 20589 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 09:32:19.234 20589 20589 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-18 09:32:19.234 20589 20589 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
07-18 09:32:19.253 20578 20578 E BreventLoader: worker 20589 exited with status 1
07-18 09:32:19.253 20578 20578 D BreventLoader: signal arrived, update: 0
07-18 09:32:19.255 20573 20573 D BreventLoader: worker 20578 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by sykh2011** [comment]
更新2.0.2正常
