### ISSUE TITLE
"高德地图"黑域无效

### ISSUE THREAD

**Issue by HustCoderHu** [brevent/Brevent#111]
残留 ChannelService 和 QS 两个服务
跟手机型号还有OS有关系吗？本人mi5，LineageOS官方版

**Comment by liudongmiao** [comment]
自查有没有其它应用，如天气等依赖它吧。

**Comment by HustCoderHu** [comment]
依赖是会把高德唤醒的意思吗？没有天气，手机上就装几个微信TIM支付宝之类的关键app。
不知道咋地，黑域就有效了。。。。。这什么情况

**Comment by liudongmiao** [comment]
就是某些应用会调用地图定位。如果黑域检查到这种依赖，就不会强行停止它。
