### ISSUE TITLE
2.0.2列表刷新的bug

### ISSUE THREAD

**Issue by catwithrabbit** [brevent/Brevent#112]
更新了2.0.2以后，黑域列表不自动刷新了怎么回事_(:3」∠)_ 必须完全退出重开才会有新的后台软件出现.....

**Comment by catwithrabbit** [comment]
还有个问题，原来可以正常识别返回键退出的app现在都不行了_(:3」∠)_ 全都得手动黑域..... 选了那个“识别非正常返回“的设置也没用QAQ

**Comment by liudongmiao** [comment]
不同的问题，不要放在一个会话里，不好追踪。

标题所示问题，已经修复，待发新版：https://github.com/brevent/Brevent/commit/5b4dc79a1899f046e367377e1651ec9cc6e3eabb
