### ISSUE TITLE
Check for stable 时出现Timeout

### ISSUE THREAD

**Issue by guoyonganceo** [brevent/Brevent#113]
![Screenshot_20170718-215942.png](https://i.loli.net/2017/07/18/596e14fe23813.png)
详情+日志已加入截图

**Comment by guoyonganceo** [comment]
补上：
版本为2.0.3，系统版本为：7.1.2

**Comment by liudongmiao** [comment]
timeout 很正常。

目前，只有当黑域在前台，才会认为正常；如果不在前台，将会认为无法检测。

后续会支持网络 ADB。

**Comment by guoyonganceo** [comment]
好的
