### ISSUE TITLE
网易云音乐播放中被强行停止

### ISSUE THREAD

**Issue by devlkx** [brevent/Brevent#114]
设备：Oneplus X Android 6.0
问题：优化音乐类应用开启，但网易云音乐播放中按home键离开应用后三四秒后被停止运行，但按多任务键离开应用会保留

**Comment by devlkx** [comment]
版本是2.1.10 play版

**Comment by liudongmiao** [comment]
日志呢？

**Comment by devlkx** [comment]
邮件已发，请查收

**Comment by liudongmiao** [comment]
某种原因无法识别音乐，不处理。
