### ISSUE TITLE
黑域服务已经启动，但是没有事件日志。请稍后重试，或重启手机。

### ISSUE THREAD

**Issue by beidouchangxi** [brevent/Brevent#115]
![default](https://user-images.githubusercontent.com/5969658/28323134-89d0a9a6-6c0a-11e7-8009-221725b21d9f.png)

如上图，似乎没抓取到有价值的日志。

手机是 Nexus6，LineageOS 7.1.2

**Comment by beidouchangxi** [comment]
使用Powershell跑了一遍似乎多了一点输入日志。。。希望作者可以参考

PS D:\设备相关\adb> .\adb shell
7[r[999;999H[6n8shamu:/ $
shamu:/ $
shamu:/ $ su
7[r[999;999H[6n8shamu:/ #
shamu:/ # sh /data/data/me.piebridge.brevent/brevent.sh
WARNING: run as root is experimental!!!
found old brevent_server, pid: 7193, killing
checking for server...started, pid: 7458
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-18 22:58:14.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-18 22:58:14.000' -d -s BreventLoader BreventServer
07-18 22:58:16.261  7458  7458 D BreventServer: get service: package
07-18 22:58:16.262  7458  7458 D BreventServer: args: [10]
07-18 22:58:16.262  7458  7458 I BreventServer: signal: 10
07-18 22:58:16.269  7458  7458 I BreventServer: starting Brevent Server 2.0.3
07-18 22:58:16.284  7458  7458 D BreventServer: get service: package
07-18 22:58:16.286  7458  7458 I BreventServer: brevent user: 0, uid: 0
07-18 22:58:16.288  7458  7458 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-18 22:58:16.369  7458  7458 I BreventServer: loading brevent list
07-18 22:58:16.369  7458  7458 I BreventServer: loading brevent conf
07-18 22:58:16.374  7458  7458 D BreventServer: get service: appwidget
07-18 22:58:16.384  7458  7458 D BreventServer: get service: usagestats
07-18 22:58:16.512  7458  7458 D BreventServer: notification_cancel_all, tag: 2752, event: 4
07-18 22:58:16.518  7458  7458 D BreventServer: notification_panel_revealed, tag: 27500, event: 6
07-18 22:58:16.518  7458  7458 D BreventServer: notification_panel_hidden, tag: 27501, event: 7
07-18 22:58:16.519  7458  7458 D BreventServer: am_new_intent, tag: 30003, event: 8
07-18 22:58:16.520  7458  7458 D BreventServer: am_restart_activity, tag: 30006, event: 10
07-18 22:58:16.521  7458  7458 D BreventServer: am_resume_activity, tag: 30007, event: 2
07-18 22:58:16.522  7458  7458 D BreventServer: am_pause_activity, tag: 30013, event: 9
07-18 22:58:16.523  7458  7458 D BreventServer: am_proc_start, tag: 30014, event: 1
07-18 22:58:16.526  7458  7458 D BreventServer: am_switch_user, tag: 30041, event: 3
07-18 22:58:16.535  7458  7458 D BreventServer: screen_toggled, tag: 70000, event: 5
07-18 22:58:16.543  7458  7469 I BreventServer: Brevent Event, now: 1500389896
07-18 22:58:16.543  7458  7458 D BreventServer: check and brevent
07-18 22:58:16.544  7458  7458 D BreventServer: get service: notification
07-18 22:58:16.561  7458  7469 I BreventServer: system_server: 995, now: 1500389896
07-18 22:58:16.717  7458  7458 D BreventServer: get service: activity
07-18 22:58:16.725  7458  7458 D BreventServer: get service: alarm
07-18 22:58:16.727  7458  7458 D BreventServer: get service: wallpaper
07-18 22:58:16.729  7458  7458 D BreventServer: widgets: {com.google.android.googlequicksearchbox, com.cyanogenmod.lockc
lock, com.netease.cloudmusic}
07-18 22:58:16.729  7458  7458 D BreventServer: recent: {com.speedsoftware.rootexplorer=1167, com.android.vending=1213,
com.tencent.mm=120, com.shanbay.words=4}
07-18 22:58:16.870  7458  7458 D BreventServer: org.cyanogenmod.yahooweatherprovider depended by {org.cyanogenmod.weathe
rservice}
07-18 22:58:16.871  7458  7458 D BreventServer: com.android.providers.settings depended by {com.android.providers.media,
 com.teslacoilsw.launcher, com.android.providers.downloads, com.android.vending, com.tencent.mm, me.piebridge.brevent, c
om.cyanogenmod.lockclock, com.android.cellbroadcastreceiver, com.google.android.gms, com.google.android.gsf, com.google.
android.inputmethod.pinyin, com.android.systemui}
07-18 22:58:16.871  7458  7458 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify, com.teslacoi
lsw.launcher, com.android.vending}
07-18 22:58:16.871  7458  7458 D BreventServer: org.cyanogenmod.cmsettings depended by {com.android.systemui, org.cyanog
enmod.weatherservice}
07-18 22:58:16.871  7458  7458 D BreventServer: com.android.bluetooth depended by {com.android.systemui}
07-18 22:58:16.871  7458  7458 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
07-18 22:58:16.871  7458  7458 D BreventServer: unsafe: {com.teslacoilsw.launcher, com.android.systemui}
07-18 22:58:16.871  7458  7458 D BreventServer: notifications: {com.github.shadowsocks=[98]}
07-18 22:58:16.872  7458  7458 D BreventServer: check again in 3600s
07-18 22:58:16.872  7458  7458 D BreventServer: check and brevent, took 329ms
07-18 22:58:16.874  7458  7458 D BreventServer: get service: batterystats
07-18 22:58:16.875  7458  7458 I BreventServer: charging: true
07-18 22:58:16.875  7458  7458 I BreventServer: support standby: true
07-18 22:58:16.875  7458  7458 I BreventServer: support stopped: true
07-18 22:58:16.879  7458  7458 W BreventServer: has no BreventActivity
07-18 22:58:16.879  7458  7458 E BreventServer: Can't be run as root, please open Brevent
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above
1|shamu:/ #

**Comment by liudongmiao** [comment]
> 07-18 22:58:16.879 7458 7458 E BreventServer: Can't be run as root, please open Brevent

**Comment by beidouchangxi** [comment]
截图里那次不是root跑的，没输出任何东西，只有root跑才有日志出来。
