### ISSUE TITLE
2.2无法root启动，ADB_*全是null

### ISSUE THREAD

**Issue by cv0cv0** [brevent/Brevent#115]

**Comment by vvb2060** [comment]
正因为全是null，所以不能ROOT启动。需要你添加自己的调试密钥

**Comment by liudongmiao** [comment]
都能自己编译了，你自己还不能改下代码，直接使用之前的直接启动么。

**Comment by gameclamp** [comment]
研究了半天，四个参数中的三个好像分别是公钥、模、私钥的指数，但是那个拼接在20位随机token前面的是什么？没搞懂ADB协议是怎么认证的。

**Comment by liudongmiao** [comment]
反正你可以反编译黑域的嘛...

目前也已经 fallback 了，自己编译的版本，没有网络调试，支持直接 root。
