### ISSUE TITLE
魅族手机 魅蓝E更新新系统 黑域无法启动

### ISSUE THREAD

**Issue by 1141087505** [brevent/Brevent#117]
如题 （第一次发帖 如有错误 请指正）
9月26号 下午更新的flyme 7.0系统          其他还好 就黑域没用 
输入日志：09-26 20:08:24.183   839   839 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9 in tid 839 (init_thh)
黑域服务日志不知道啥情况按照命令调不出来

![123](https://user-images.githubusercontent.com/32299460/30860785-ef963cf2-a2fa-11e7-90c5-c5ec4b0216b2.PNG)

**Comment by vvb2060** [comment]
#95
请邮件作者进行联调

**Comment by liudongmiao** [comment]
电脑安装 teamviewer，邮件发我 id 与密码。

**Comment by 1141087505** [comment]
mailto:brevent@piebridge.me 这是你邮件是吧

**Comment by 1141087505** [comment]
mailto:brevent@piebridge.me  这是你邮箱是吧 @liudongmiao 
装了1.2版本好了 但装了高等级的版本又不行
