### ISSUE TITLE
软件打开不正常

### ISSUE THREAD

**Issue by bloodkilory** [brevent/Brevent#117]
有时可以正常使用，但有的时候。。。使用ps -ef可以看到黑域服务是正在运行，但打开软件就显示正在获取进程状态。。。过一会就显示黑域服务没有响应。机器三星s8，已经root。

**Comment by liudongmiao** [comment]
你看下是否有其它应用干扰黑域使用网络。

**Comment by bloodkilory** [comment]
然而并没有，我捐赠了3美刀啊，这种使用体验。。。

**Comment by bloodkilory** [comment]
补充说明一下：之前没有root的时候，使用adb模式，并没有出现过问题。后来刷了极光的rom，除了智能管理器以外，还安装了appops和强制打盹，appops给满了权限，强制打盹也没有开亮屏打盹。有时会突然打不开黑域，但过一段时间就又好了，总之感觉莫名其妙

**Comment by liudongmiao** [comment]
你也说了，没 root 前，没有问题…
装了其他应用，就出现了这个问题…但过一段时间就好…

这么说吧，黑域服务，要一直工作，但不幸的是，这个黑域服务系统看不见，能统计电量，不一定能不被 doze （可能能，可能不能，不清楚）。而黑域，也依赖网络…

就你提供的信息来看，我更多认为是兼容性问题。如果不能稳定重现，很难定位并修复。我下个版本，在启动黑域服务界面时，加入日志选项，但也需要至少成功启动过一次。

这和你捐了多少并没有关系。如果需要退款，发送邮件附上订单号即可。
