### ISSUE TITLE
一加3T在开机启动黑域和黑域新应用的时候会弹Toast：“成功黑域一加漫游”。但是在黑域里都找不到一加漫游这个应用。

### ISSUE THREAD

**Issue by iVeego** [brevent/Brevent#12]
手机型号：一加 3T ；
操作系统：OxygenOS 4.1.3 base on Android 7.1.1 .
请问如何可以帮助您定位到问题。

**Comment by liudongmiao** [comment]
最好的方式，电脑上安装 teamviewer，邮件我帐号密码，我登录上去。

此外，你可以注意下这个日志：
> add package ...

有一种情况，确实无法见到。如果这个是用户应用，但是是与通讯相关的应用。

**Comment by iVeego** [comment]
@liudongmiao 已经邮件给您了，需要连接的话，麻烦柳大提前告知下，谢谢。

**Comment by liudongmiao** [comment]
已发测试版，应该已经彻底修复这个问题。
