### ISSUE TITLE
 I want to ask questions ...

### ISSUE THREAD

**Issue by 1836807765** [brevent/Brevent#122]
Compile successfully...but ...Run error ...
Error message
------------------------------------------------------------
Information:Gradle tasks [:brevent:assembleDebug]
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
D:\Android\AppData\Local\Android\sdk\ndk-bundle\sysroot\usr\include\stdio.h
Error:(1, 1) error: unknown type name 'b'
Error:(1, 2) error: expected identifier or '('
Error:(1, 7) error: source file is not valid UTF-8
Error:(1, 44) error: source file is not valid UTF-8
Error:(1, 45) error: source file is not valid UTF-8
Error:(1, 46) error: source file is not valid UTF-8
Error:(1, 47) error: source file is not valid UTF-8
Error:(1, 49) error: source file is not valid UTF-8
Error:(1, 50) error: source file is not valid UTF-8
Error:(1, 52) error: expected identifier or '('
Error:(1, 53) error: source file is not valid UTF-8
Error:(1, 54) error: source file is not valid UTF-8
Error:(1, 57) error: source file is not valid UTF-8
Error:(1, 61) error: source file is not valid UTF-8
Error:(1, 62) error: source file is not valid UTF-8
Error:(1, 65) error: source file is not valid UTF-8
Error:(1, 66) error: source file is not valid UTF-8
Error:(1, 69) error: source file is not valid UTF-8
Error:(1, 73) error: source file is not valid UTF-8
Error:<U+001F><FB>q<U+0014><U+0006><E2>^<CC><U+001A><U+001B><U+0013><C2>
Error:Execution failed for task ':brevent:buildBootstrap'.
> Process 'command 'D:\Android\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2
------------------------------------------------------------

**Comment by liudongmiao** [comment]
Sorry, but i can do nothing.

I mainly develop on Mac OS X, and compiled it on Windows 7, with latest Android Studio, and Gradle.
