### ISSUE TITLE
停止状态不支持怎么解决？

### ISSUE THREAD

**Issue by wocala** [brevent/Brevent#122]
Nexus5 Android 6.0.1 未root
版本2.2
显示停止状态：不支持
停止状态什么意思？
不支持怎么解决？
谢谢

**Comment by liudongmiao** [comment]
https://developer.android.google.cn/about/versions/android-3.1.html#launchcontrols

不支持就不支持呗，找你的魔改 ROM 去。

**Comment by wocala** [comment]
所以对于原生系统来说，这个不支持是正常的？

**Comment by liudongmiao** [comment]
原生系统都支持的。

**Comment by wocala** [comment]
嗯，重新安装后显示支持了。谢谢
