### ISSUE TITLE
非激进模式下王者荣耀助手禁不掉啊，王者荣耀也是，非得我强制停止。

### ISSUE THREAD

**Issue by qtiuto** [brevent/Brevent#124]
不止一个进程啊，比如王者荣耀助手，除了待机的embryo进程，还有包名：game进程和包名：QALSERVICE（腾讯随心播的，斗鱼也有这个进程）进程。这些都没有停止啊，我7.1的氢OS，手机是root模式运行黑域的，得出的比较结果是直接读/proc目录得出的结果，不清楚你的进程是哪里读的，am的getRunningProcesses?应该不是getRunningServices.
![screenshot_20170722-205854](https://user-images.githubusercontent.com/9564242/28491303-6e53b870-6f21-11e7-9889-fc63c9abbcb5.png)
![screenshot_20170722-205916](https://user-images.githubusercontent.com/9564242/28491308-87daf060-6f21-11e7-9882-9ce5d8f66e9a.png)
![screenshot_20170722-205925](https://user-images.githubusercontent.com/9564242/28491311-939811e4-6f21-11e7-888e-08d32edad691.png)
![screenshot_20170722-205944](https://user-images.githubusercontent.com/9564242/28491317-a08464ca-6f21-11e7-99cf-0c74b9174280.png)
![screenshot_20170722-205952](https://user-images.githubusercontent.com/9564242/28491323-b43852ec-6f21-11e7-9b2c-bc2c80e4e5e5.png)

**Comment by kimyeonghoo** [comment]
有root可以配合绿色守护切断唤醒和结束进程

**Comment by liudongmiao** [comment]
不来图，不来日志，怎么看嘛。

1. 黑域使用一系列的手段来判断你是否使用应用
2. 黑域使用一系列的手段来判断是否强行停止应用

但是，你没有任何截图，没有任何日志。

**Comment by qtiuto** [comment]
截图更新了，如上

**Comment by liudongmiao** [comment]
建议直接给 dumpsys activity processes 结果。
黑域底层使用 `getRunningAppProcesses` 来获取进程数据，系统自带设置也是使用这个 API。在部分系统上，会使用 `getServices` 来获取服务信息。

在之前，主要是用户经常黑域系统应用反而更费电，所以非激进模式下不再强行停止没有服务的应用。
接下来，我会考虑改进机制，区分系统应用与用户应用。

对于你的情况，你可以直接从最近列表划掉什么 rongyao

黑域不可能，也不会去兼容所有应用，只使用单纯的规则。

**Comment by liudongmiao** [comment]
值得说明下，某些应用，会 fork 一些看起来不受系统控制的进程。
在阻止运行时代，花了大量时间来判断。
黑域里，不再判断，直接强行停止了事，因为发现强行停止系统也会回收这些用户 fork 出来的进程。

如果你的系统实现不友好，无法在强行停止之后进程失效，请报告问题。

**Comment by liudongmiao** [comment]
也就是说，当前认为 rongyao 是安全的，但有可能不是安全的。之前判断是基于服务，现在优化成基于调度，大于 `PROCESS_STATE_RECEIVER`，这个在不同的 Android 版本中，值不同，所以并没有 final，会取系统实际值，以下为代码片段。

```java
    /**
     * @hide Process is in the background running a receiver.   Note that from the
     * perspective of oom_adj receivers run at a higher foreground level, but for our
     * prioritization here that is not necessary and putting them below services means
     * many fewer changes in some process states as they receive broadcasts.
     */
    public static int PROCESS_STATE_RECEIVER = 11;

    /**
     * @hide Process is in the background but hosts the home activity.
     */
    public static int PROCESS_STATE_HOME = 12;

    /**
     * @hide Process is in the background but hosts the last shown activity.
     */
    public static int PROCESS_STATE_LAST_ACTIVITY = 13;

    /**
     * @hide Process is being cached for later use and contains activities.
     */
    public static int PROCESS_STATE_CACHED_ACTIVITY = 14;

    /**
     * @hide Process is being cached for later use and is a client of another cached
     * process that contains activities.
     */
    public static int PROCESS_STATE_CACHED_ACTIVITY_CLIENT = 15;

    /**
     * @hide Process is being cached for later use and is empty.
     */
    public static int PROCESS_STATE_CACHED_EMPTY = 16;
```

更多请见源码：https://github.com/android/platform_frameworks_base/blob/master/core/java/android/app/ActivityManager.java#L381

**Comment by liudongmiao** [comment]
你可以开启激进模式，或者使用测试版看看新的安全应用认定。

**Comment by liudongmiao** [comment]
问题已经解释。如有疑问，请重开。
