### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [brevent/Brevent#125]
Please add the app to the F-Droid.

**Comment by liudongmiao** [comment]
Actually, Brevent is not free, you can see the license: https://github.com/brevent/Brevent/#license

And if you build yourself, it has another name as Nrevent, which means Not Brevent, and use a logo like block from Android. 

https://github.com/brevent/Brevent/blob/master/brevent/src/main/res/mipmap-xxxhdpi/ic_nrevent.png

**Comment by liudongmiao** [comment]
For Brevent, payment are required for experimental features. And Chinese users can use other version, only ROOT experimental feature is required to pay. (ROOT means start automatically when boot completes.)

For Nrevent, it has no support from myself. It's free to use all the features.
