### ISSUE TITLE
when I start it with root....

### ISSUE THREAD

**Issue by kimyeonghoo** [brevent/Brevent#125]
WARNING: run as root is experimental!!!
checking for server.fail
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-22 18:00:46.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-22 18:00:46.000' -d -s BreventLoader BreventServer
--- brevent end ---

**Comment by liudongmiao** [comment]
there is no logcat or no log on your devices. please fix it first.
