### ISSUE TITLE
更新a、b后进黑域，很大程度会卡在获取进程、查看日志状态，然后就跳出黑域没有响应，之前版本没有这问题。

### ISSUE THREAD

**Issue by wt670280793** [brevent/Brevent#126]
WARNING: run as root is experimental!!!
found old brevent_server, pid: 21231, killing
checking for server..started, pid: 21364
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-22 21:00:11.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-22 21:00:11.000' -d -s BreventLoader BreventServer
07-22 21:00:11.226 21186 21186 E BreventLoader: worker 21231 exited on signal 15
07-22 21:00:11.226 21186 21186 D BreventLoader: signal arrived, update: 0
07-22 21:00:11.752 21343 21343 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
07-22 21:00:12.278 21364 21364 D BreventServer: get service: package
07-22 21:00:12.278 21364 21364 D BreventServer: args: [10]
07-22 21:00:12.278 21364 21364 I BreventServer: signal: 10
07-22 21:00:12.280 21364 21364 I BreventServer: starting Brevent Server 2.0.4b
07-22 21:00:12.287 21364 21364 D BreventServer: get service: package
07-22 21:00:12.289 21364 21364 I BreventServer: brevent user: 0, uid: 0
07-22 21:00:12.289 21364 21364 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-22 21:00:12.330 21343 21343 E BreventLoader: worker 21364 exited on signal 15
07-22 21:00:12.331 21343 21343 D BreventLoader: signal arrived, update: 0
07-22 21:00:12.331 21338 21338 D BreventLoader: worker 21343 exited with status 0
--- brevent end ---

**Comment by liudongmiao** [comment]
> worker 21231 exited on signal 15

其它应用杀了这个进程...自查吧。
