### ISSUE TITLE
没有事件日志，checking for stable...........timeout

### ISSUE THREAD

**Issue by beidouchangxi** [brevent/Brevent#127]
黑域版本 v2.0.4a，手机Nexus6，Android 7.1.2
按照操作引导进入黑域界面，然后执行adb命令，显示checking for stable...........timeout
执行logcat命令无任何日志输出。
![baidushurufa_2017-7-22_21-11-51](https://user-images.githubusercontent.com/5969658/28491361-632dcc82-6f22-11e7-97c5-6d8936d9309a.png)

**Comment by beidouchangxi** [comment]
app端会先显示：正在等待时间日志，请查看然后关闭通知以触发事件......
然后显示：黑域服务已经启动，但是没有事件日志。请稍后重试，或者重启手机。

重启几次后尝试问题没有改变，使用root权限执行也没有变化。

**Comment by liudongmiao** [comment]
没有事件日志的话，黑域无法使用，请不要关闭日志，调大日志之类。
（某些国产 ROM 会改动日志级别，但黑域依赖日志。）

所以，黑域没有检测到日志，认为不成功；
不成功的话，启动的时候就会显示超时（不可能一直等下去...）。
