### ISSUE TITLE
一加3 root启动黑域失败

### ISSUE THREAD

**Issue by studioprintf** [brevent/Brevent#129]
WARNING: run as root is experimental!!!
checking for server..fail
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-23 14:27:08.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-23 14:27:08.000' -d -s BreventLoader BreventServer
07-23 14:27:09.441  9874  9874 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-23 14:27:09.885  9893  9893 D BreventServer: get service: package
07-23 14:27:09.885  9893  9893 D BreventServer: args: [10]
07-23 14:27:09.886  9893  9893 I BreventServer: signal: 10
07-23 14:27:09.893  9893  9893 I BreventServer: starting Brevent Server 2.0.4b
07-23 14:27:09.901  9893  9893 D BreventServer: get service: package
07-23 14:27:09.903  9893  9893 I BreventServer: brevent user: 0, uid: 0
07-23 14:27:09.904  9893  9893 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-23 14:27:09.916  9893  9893 I BreventServer: loading brevent list
07-23 14:27:09.916  9893  9893 I BreventServer: loading brevent conf
07-23 14:27:09.918  9893  9893 D BreventServer: get service: appwidget
07-23 14:27:09.918  9893  9893 E BreventServer: Cannot dump appwidget(remote dead)
07-23 14:27:09.937  9874  9874 E BreventLoader: worker 9893 exited with status 1
07-23 14:27:09.937  9874  9874 D BreventLoader: signal arrived, update: 0
07-23 14:27:09.939  9870  9870 D BreventLoader: worker 9874 exited with status 0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
>  Cannot dump appwidget(remote dead)

请禁用 selinux，或者参考 #32
