### ISSUE TITLE
锤子M1L更新2.2.1无法启动，日志如下

### ISSUE THREAD

**Issue by LYTPride** [brevent/Brevent#130]
--- crash start ---
[command] logcat -b crash -t '10-01 21:48:00.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '10-01 21:48:00.000' -d -s BreventLoader BreventServer
10-01 21:48:00.987 32305 32305 D BreventLoader: line: package:/data/app/me.piebridge.brevent-1/base.apk
10-01 21:48:01.001 32305 32305 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
10-01 21:48:01.002 32315 32315 D BreventLoader: start: 1506865680
10-01 21:48:01.401 32315 32315 I BreventServer: starting Brevent Server 2.2.1
10-01 21:48:01.462 32315 32315 I BreventServer: brevent user: 0, uid: 2000
10-01 21:48:01.463 32315 32315 I BreventServer: brevent data directory: /data/user/0/com.android.shell
10-01 21:48:01.485 32315 32315 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 74
10-01 21:48:01.491 32315 32315 W BreventServer: Can't setStopped for com.fenqile.fenqile(ignore)
10-01 21:48:01.491 32315 32315 W BreventServer: java.lang.SecurityException: Permission Denial: attempt to change active state from pid=32315, uid=2000, package uid=10212
10-01 21:48:01.491 32315 32315 W BreventServer:         at android.os.Parcel.readException(Parcel.java:1620)
10-01 21:48:01.491 32315 32315 W BreventServer:         at android.os.Parcel.readException(Parcel.java:1573)
10-01 21:48:01.491 32315 32315 W BreventServer:         at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4454)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.g.a(HideApi.java:235)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.c.a(BreventServerImpl.java:2209)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.c.b(BreventServerImpl.java:1322)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.c.a(BreventServerImpl.java:1276)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.c.d(BreventServerImpl.java:468)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.c.<init>(BreventServerImpl.java:306)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.c.a(BreventServerImpl.java:2255)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:36)
10-01 21:48:01.491 32315 32315 W BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
10-01 21:48:01.491 32315 32315 W BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:144)
10-01 21:48:01.491 32315 32315 W BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-01 21:48:01.491 32315 32315 W BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
10-01 21:48:01.492 32315 32315 E BreventServer: Could not access overlay. Is the system running?
10-01 21:48:01.516 32305 32305 E BreventLoader: worker 32315 exited with status 1
10-01 21:48:01.516 32305 32305 D BreventLoader: signal arrived, update: 0
10-01 21:48:01.516 32300 32300 D BreventLoader: worker 32305 exited with status 0
--- brevent end ---

**Comment by liushuai0929** [comment]
更新新版

**Comment by liushuai0929** [comment]
话说锤子还需要黑域么？

**Comment by liudongmiao** [comment]
2.2.2 已经修复，你来晚了...锤子的话，老老实实等我在锤子商店更新吧。

**Comment by LYTPride** [comment]
已经更新PLAY版2.2.2，问题解决
