### ISSUE TITLE
应用宝黑域不掉啊

### ISSUE THREAD

**Issue by zyb1777** [brevent/Brevent#130]
还是会无故自启 腾讯真流氓

**Comment by vvb2060** [comment]
关闭，提供日志与具体操作过程后再打开该issue

**Comment by liudongmiao** [comment]
我见到一个日志，qq 需要应用宝....这种，没法处理。
好像是 qq 内有一个软件管家，需要直接对接应用宝吧。
如果恰好在那个页面，然后强行停止了应用宝，QQ 也被强行停止了，画面太美不敢想像。
