### ISSUE TITLE
命令以后出现以下错误

### ISSUE THREAD

**Issue by WystanW** [brevent/Brevent#131]
adb server version (32) doesn't match this client (39); killing...
error: unknown host service
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (10048)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

**Comment by liudongmiao** [comment]
与黑域无关
