### ISSUE TITLE
三星S6 root模式开启失败

### ISSUE THREAD

**Issue by MuenYu** [brevent/Brevent#131]
WARNING: run as root is experimental!!!
checking for server.fail
please report bug to https://github.com/brevent/Brevent/issues 

 with log below
--- crash start ---
>>> logcat -b crash -t '07-23 18:08:42.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-23 18:08:42.000' -d -s BreventLoader BreventServer
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues 

 with log above

**Comment by liudongmiao** [comment]
没有任何日志，请想办法让 logcat 正常。
