### ISSUE TITLE
华为荣耀9 emui5.1正常开启后没有事件日志，无法进入黑域App

### ISSUE THREAD

**Issue by joel-zhu** [brevent/Brevent#135]
C:\Users\admin\Desktop\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
10-07 18:47:31.883  5105  5105 I BreventServer: starting Brevent Server 2.2.3
10-07 18:47:31.961  5105  5105 I BreventServer: brevent user: 0, uid: 2000
10-07 18:47:31.962  5105  5105 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
10-07 18:47:32.016  5105  5105 I BreventServer: no service overlay
10-07 18:47:32.029  5105  5105 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 63
10-07 18:47:33.205  5105  5140 I BreventServer: Brevent Event, now: 1507373253
10-07 18:47:33.216  5105  5140 I BreventServer: system_server: 1335, now: 1507373253
10-07 18:47:33.757  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {com.google.android.googlequicksearchbox, in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:47:33.813  5105  5105 I BreventServer: notification_cancel_all events: 17
10-07 18:47:33.815  5105  5105 I BreventServer: charging: true
10-07 18:47:33.815  5105  5105 I BreventServer: support standby: true
10-07 18:47:33.816  5105  5105 I BreventServer: support stopped: true
10-07 18:47:33.816  5105  5105 I BreventServer: support upgrade: true
10-07 18:47:33.821  5105  5105 I BreventServer: granted permission
10-07 18:47:34.294  5105  5105 I BreventServer: Brevent Server 2.2.3 started
10-07 18:47:34.295  5105  5105 I BreventServer: received first event
10-07 18:47:37.639  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {com.google.android.googlequicksearchbox, in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:47:44.412  5105  5164 I BreventServer: make brevent whitelist, args: [whitelist, -me.piebridge.brevent]
10-07 18:47:44.501  5105  5164 W BreventServer: no tracks
10-07 18:47:44.511  5105  5164 W BreventServer: sent 10 to 5093
10-07 18:48:32.827  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:49:33.232  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:49:38.478  5105  5164 W BreventServer: no tracks
10-07 18:49:46.505  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {org.telegram.messenger, in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:49:46.508  5105  5105 W BreventServer: has no BreventActivity
10-07 18:50:16.517  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:50:31.042  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:51:02.474  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 19:11:09.647 13442 13442 I BreventServer: received first event

**Comment by CVN-77** [comment]
1.* # * # 2846579 # * # *
2. 后台设置
3. LOG设置
4. 随意选中一个
