### ISSUE TITLE
支付宝是免疫的吗？

### ISSUE THREAD

**Issue by wulinfo** [brevent/Brevent#137]
如题，黑不掉呀

**Comment by naloder** [comment]
不是，第二 你没有日志

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Meizu M3s 发送_

**Comment by vvb2060** [comment]
关闭，提供日志与具体操作过程后再打开该issue

**Comment by wulinfo** [comment]
请查收日志文件，发件人：wulinfo@gmail.com
