### ISSUE TITLE
黑域选项里没有待机选项，如何能开启

### ISSUE THREAD

**Issue by zzzdtz** [brevent/Brevent#138]
安卓7.0没有待机选项，是否是rom关闭了待机，所以黑域不显示，如果需要开启待机，要怎么开启，假如已root

**Comment by vvb2060** [comment]
安装 Google Play 服务，或一个包名为com.google.android.gms的应用。

具体原因参考[电源管理
](https://source.android.com/devices/tech/power/mgmt?hl=zh-cn#doze-reqs)
（部分ROM无需安装GMS，默认打开doze 和 app standby）

**Comment by zzzdtz** [comment]
如果已安装GMS，app stanby还是么有呢。。。

**Comment by vvb2060** [comment]
重启后还是没有可能是这个功能被厂商删掉了。

**Comment by zzzdtz** [comment]
重启过了，看来是删掉了。。。

**Comment by zzzdtz** [comment]
我看cm之类的，我还以为可以通过修改system下的文件，手动开启呢。

**Comment by liudongmiao** [comment]
你大约可以改 framework-res.apk 下的配置文件，然后重新打包。
有一定风险，不建议使用。

反正吧，待机也基本没啥用，就是待机了，断网了而已。

**Comment by cv0cv0** [comment]
@liudongmiao 要是cpu也不再消耗就好了，内存不够了优先回收这部分软件占用的内存，包括服务。

**Comment by liudongmiao** [comment]
@cv0cv0 待机只是不能访问网络而已，真的是有看官方文档？

https://developer.android.google.cn/training/monitoring-device-state/doze-standby.html?hl=en

要看中文的话，就把 en 改成 zh。

**Comment by zzzdtz** [comment]
@liudongmiao  但是如果不开启待机，微信 或者其他GCM 应用直接被杀死的话，GCM可以重新启动微信之类的GCM应用吗
