### ISSUE TITLE
反馈一个无法镇压“网易公开课”推送的问题

### ISSUE THREAD

**Issue by digiw** [brevent/Brevent#138]
柳大，按黑域说明里获取日志的方式开启服务调试日志后，分别执行“崩溃日志"和”黑域“服务日志”，
只能获得如下信息：
G:\adb tools>adb -d logcat -d -b crash
10-11 09:19:42.807  5707  5750 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x41 in tid 5750 (Binder_2)
10-11 10:25:17.826 17601 17610 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f7632e270 in tid 17610 (Binder_2)
10-11 10:41:45.211 18870 18887 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7fa86429d0 in tid 18887 (Binder_2)
10-11 16:26:10.071 27021 27028 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f9d381dfc in tid 27028 (Binder_1)
10-11 23:28:56.136  7704  7744 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x41 in tid 7744 (Binder_2)

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader
---------------------------------------------------------------------------------
系统是安卓6.0.1，黑域为最新版本，上述第二条指令执行后，没有结果在cmd窗口里输出。
已经黑域掉“网易公开课”这个app了，并且起先用绿守休眠它也没用，仍然会定时有推送信息输出到下拉消息通知栏里。

另外顺便想反馈一下，因为点击root按钮来启动黑域，即使已经成功获取线程进入黑域，但下拉消息框里仍然显示一条“正在启动黑域服务”的信息，无法划掉。除非此时覆盖安装一次黑域，此通知才会消失。

**Comment by liudongmiao** [comment]
黑域的日志，都可以直接通过 菜单 下的日志获取。

目前主要日志都放到了 /sdcard 下某目录，并额外保存 3 天。

**Comment by liudongmiao** [comment]
黑域从来没有说过绝对禁止某个应用被唤醒，只是说，不会让它一直运行。

什么时候处理一个应用，规则说得很清楚。至于被服务唤醒，不会处理。

难道说，同样的手段，能唤醒支付宝支持，不能唤醒 X 弹个广告？
