### ISSUE TITLE
启动黑域时 checking for stable...........timeout

### ISSUE THREAD

**Issue by luck-apple** [brevent/Brevent#139]
启动时有异常，但是进入app后是可以正常用的（Google Pixel 8.0.0）：
found old brevent_server, pid: 4992, killing
checking for server..started, pid: 7121
checking for stable...........timeout

$ adb logcat -b main -d -s BreventLoader BreventServer：
10-12 10:09:30.681  3160  3230 I BreventServer: make brevent whitelist, args: [whitelist, -me.piebridge.brevent]
10-12 10:09:30.739  3160  3230 W BreventServer: no tracks
10-12 10:09:30.783  3117  3117 D BreventLoader: received signal: 10, ppid: 1
10-12 10:09:30.784  3160  3230 W BreventServer: sent 10 to 3117
10-12 10:09:36.064  3117  3117 E BreventLoader: worker 3160 exited on signal 15
10-12 10:09:36.064  3117  3117 D BreventLoader: signal arrived, update: 0
10-12 10:09:36.402  4978  4978 D BreventLoader: line: package:/data/app/me.piebridge.brevent-hgXM391XMFgnEiTY9ZrmXA==/base.apk
10-12 10:09:36.416  4978  4978 D BreventLoader: loader path: /data/app/me.piebridge.brevent-hgXM391XMFgnEiTY9ZrmXA==/base.apk
10-12 10:09:36.417  4992  4992 D BreventLoader: start: 1507774176
10-12 10:09:37.045  4992  4992 I BreventServer: starting Brevent Server 2.2.4
10-12 10:09:37.073  4992  4992 I BreventServer: brevent user: 0, uid: 2000
10-12 10:09:37.075  4992  4992 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
10-12 10:09:37.111  4992  4992 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 48
10-12 10:09:37.168  4992  5004 I BreventServer: Brevent Event, now: 1507774177
10-12 10:09:37.180  4992  5004 I BreventServer: system_server: 913, now: 1507774177
10-12 10:09:37.286  4992  4992 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:09:37.352  4992  4992 I BreventServer: notification_cancel_all events: 11
10-12 10:09:37.355  4992  4992 I BreventServer: charging: false
10-12 10:09:37.356  4992  4992 I BreventServer: support standby: true
10-12 10:09:37.357  4992  4992 I BreventServer: support stopped: true
10-12 10:09:37.359  4992  4992 I BreventServer: support upgrade: true
10-12 10:09:37.371  4992  4992 I BreventServer: Brevent Server 2.2.4 started
10-12 10:09:37.371  4992  4992 I BreventServer: received first event
10-12 10:09:53.540  4992  5011 I BreventServer: make brevent whitelist, args: [whitelist, -me.piebridge.brevent]
10-12 10:09:53.556  4992  5011 W BreventServer: no tracks
10-12 10:09:53.585  4978  4978 D BreventLoader: received signal: 10, ppid: 1
10-12 10:09:53.585  4992  5011 W BreventServer: sent 10 to 4978
10-12 10:10:06.806  4992  4992 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:10:14.384  4992  4992 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:10:17.377  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:10:17.391  4992  5011 W BreventServer: no tracks
10-12 10:10:20.374  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:10:20.395  4992  5011 W BreventServer: no tracks
10-12 10:10:31.765  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:10:31.958  4992  5011 W BreventServer: no tracks
10-12 10:10:35.974  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:10:35.994  4992  5011 W BreventServer: no tracks
10-12 10:10:39.574  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:10:39.590  4992  5011 W BreventServer: no tracks
10-12 10:11:06.362  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:11:06.379  4992  5011 W BreventServer: no tracks
10-12 10:11:10.928  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:11:10.945  4992  5011 W BreventServer: no tracks
10-12 10:11:34.065  4992  5011 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:11:34.080  4992  5011 W BreventServer: no tracks
10-12 10:11:36.686  4978  4978 E BreventLoader: worker 4992 exited on signal 15
10-12 10:11:36.686  4978  4978 D BreventLoader: signal arrived, update: 0
10-12 10:11:37.072  7110  7110 D BreventLoader: line: package:/data/app/me.piebridge.brevent-hgXM391XMFgnEiTY9ZrmXA==/base.apk
10-12 10:11:37.089  7110  7110 D BreventLoader: loader path: /data/app/me.piebridge.brevent-hgXM391XMFgnEiTY9ZrmXA==/base.apk
10-12 10:11:37.090  7121  7121 D BreventLoader: start: 1507774296
10-12 10:11:37.801  7121  7121 I BreventServer: starting Brevent Server 2.2.4
10-12 10:11:37.832  7121  7121 I BreventServer: brevent user: 0, uid: 2000
10-12 10:11:37.836  7121  7121 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
10-12 10:11:37.879  7121  7121 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 48
10-12 10:11:37.990  7121  7133 I BreventServer: Brevent Event, now: 1507774297
10-12 10:11:38.001  7121  7133 I BreventServer: system_server: 913, now: 1507774298
10-12 10:11:38.085  7121  7121 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:11:38.141  7121  7121 I BreventServer: notification_cancel_all events: 18
10-12 10:11:38.145  7121  7121 I BreventServer: charging: false
10-12 10:11:38.146  7121  7121 I BreventServer: support standby: true
10-12 10:11:38.147  7121  7121 I BreventServer: support stopped: true
10-12 10:11:38.148  7121  7121 I BreventServer: support upgrade: true
10-12 10:11:38.171  7121  7121 I BreventServer: Brevent Server 2.2.4 started
10-12 10:11:49.364  7121  7121 I BreventServer: received first event
10-12 10:12:08.668  7121  7121 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}
10-12 10:12:30.012  7121  7121 I BreventServer: won't block com.android.vending, depended by {com.google.android.gms}

**Comment by vvb2060** [comment]
正常，启动服务时没有打开黑域应用就是这样。
