### ISSUE TITLE
ROOT 模式启动失败

### ISSUE THREAD

**Issue by hx1997** [brevent/Brevent#139]
日志如下
--- crash start ---
>>> logcat -b crash -t '07-26 14:05:03.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-26 14:05:03.000' -d -s BreventLoader BreventServer
07-26 14:05:04.026  5763  5763 E BreventLoader: worker 5770 exited with status 255
--- brevent end ---

**Comment by liudongmiao** [comment]
日志太少，请使用最新测试版：https://piebridge.me/br/next/
