### ISSUE TITLE
This case...

### ISSUE THREAD

**Issue by DanngZ** [brevent/Brevent#14]
![qq 20170527202128](https://cloud.githubusercontent.com/assets/28999963/26521406/761c294e-431a-11e7-84a6-bf97e6b31e8e.jpg)

**Comment by DanngZ** [comment]
So I've comen here......

**Comment by liudongmiao** [comment]
Please follow instructions. If you have root, read guide - permission learn how to open it. 

In your case, you run it as terminal, which has no permission.
