### ISSUE TITLE
Extra space in front of "special" packages in popup menu

### ISSUE THREAD

**Issue by EraserKing** [brevent/Brevent#14]
As you can see there's an additional space in the popup menu...
I checked your strings.xml and found you put the space there on purpose. I guess you'd like to format the string to replace "%s", but I don't know why it's not replaced by another string (I don't know much about Java).

![2017-08-10 18 07 43](https://user-images.githubusercontent.com/1160403/29166133-cae96500-7df7-11e7-93c2-15906f083a3a.png)

Version 2.1.1 (Play), Normal mode

**Comment by liudongmiao** [comment]
Will fix in next version.

Thanks for feedback, please email me, I will give you a contributor promotion.

**Comment by EraserKing** [comment]
My account is eraserking@gmail.com
Thanks.
