### ISSUE TITLE
网易云音乐非正常结束

### ISSUE THREAD

**Issue by zjns** [brevent/Brevent#140]
网易云音乐在开启云音乐锁屏播放音乐时锁屏再开屏解锁，会有两个步骤，第一步，解云音乐锁屏，第二步，解系统锁屏，当执行完第一步时，几秒后云音乐就被结束。怀疑是黑域进行了错误的判断。
系统：lineage 7.1.2

**Comment by liudongmiao** [comment]
音乐类，请主动开允许同步。

**Comment by liudongmiao** [comment]
允许同步，保证系统可以多种方式唤醒它。不黑域，只是不黑域。
