### ISSUE TITLE
Found a License Issue

### ISSUE THREAD

**Issue by cubesky** [brevent/Brevent#143]
~delete it~

**Comment by liudongmiao** [comment]
~delete it~

**Comment by RedL0tus** [comment]
~delete it~

**Comment by cubesky** [comment]
~delete it~

**Comment by liudongmiao** [comment]
~delete it~

**Comment by cubesky** [comment]
~delete it~

**Comment by liudongmiao** [comment]
~delete it~

**Comment by RedL0tus** [comment]
@liudongmiao 
Seems you've misunderstood what @cubesky said.

看起來你誤解了他的意思。
我們還是用中文說吧。

首先你的代碼是使用 WTFPL 協議發佈的，圖標等等是別的協議，這本身沒問題。

問題在於你的附加條件，也就是你說的修改代碼後必須改名字和包名。
WTFPL 不允許在它之上添加其它限制條款，除非你更改協議的名字。

@cubesky 的前一條評論的意思是說包名和程序名是寫在了代碼裏面的，也算是代碼的一部分（當然如果你有辦法讓源碼裏完全不含包名和程序名就沒有這個問題了），所以你添加的附加條款是違反了 WTFPL 的要求的。

而且他在一開始就給了你解決方法：把 WTFPL 的內容複製出來改個名字，再加上你的附加條款即可。

你既然選擇了 WTFPL，就請爲你的選擇負責。即使是魔改後用同樣的包名和程序名發佈也是在 WTFPL 的允許範圍內的，別人就這樣發佈你也無權要求別人下架；如果不想這樣，請在下一個版本 re-license 到別的協議，或者乾脆下個版本就別開源了，對誰來說都省事。

**Comment by liudongmiao** [comment]
随你便啊。黑域由两个部分组成，开源的黑域 及 不开源的黑域服务。你 TM 想怎么处理开源的黑域都成，只是不开源的黑域服务限定了以下情况：

- 签名必须是本人签名，或者 testkey 的签名。
- 如果是 testkey 签名，包名不得叫 me.piebridge.brevent，名称不得含有 Brevent / 黑域 等近似值。

所以，你可以想怎么就怎么，但是，不开源的黑域服务的限制在这里。而且，即使你叫 Brevent 或者 黑域，你 TM 还想去其它商店发布么。

F**K!@

**Comment by liudongmiao** [comment]
请认真睁大你们的眼睛！

```
According WTFPL, you're free to modify codes.
```

```
根据 WTFPL 协议，您可自由修改黑域代码。
```

其它的限定，只是针对 不开源 的黑域服务说的。我也可以不说，你能用，就破解去呗。
