### ISSUE TITLE
找不到 brevent.sh

### ISSUE THREAD

**Issue by Wiilz** [brevent/Brevent#143]
Phone : Smartisan YQ601
OS : Smartisan OS 3.6.8 (Android 5.1.1)
brevent version : 2.0.4b
之前一直可以正常使用黑域，在这次手机重启后，第一次用adb命令，一直提示让我生成新的brevent.sh。之后手动将黑域卸载掉，重新安装app后，就一直是这种情况  "No such file or directory"，找不到 brevent.sh 了 。

![brevent.sh](http://osnxazri2.bkt.clouddn.com/2017-07-27_225506.jpg)

**Comment by CVN-77** [comment]
服了

**Comment by Wiilz** [comment]
哪里打错了？
“adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh”

**Comment by vvb2060** [comment]
@Wiilz 麻烦你认真对比下应用显示的和你输入的。

**Comment by Wiilz** [comment]
@vvb2060 你好，我确实逐字对照了，就是图中红框上面那行是输入的命令，没有发现问题。而且，cmd里的命令是直接从app复制的。

**Comment by vvb2060** [comment]
@Wiilz 你可以把截图发上来让大家看看，应用上写的是
`adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh`
还是
`adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh`
一个新版一个旧版，你自称使用2.0.4b，应该是新版命令。

**Comment by Wiilz** [comment]
@vvb2060  原来是 2.0.4b 换命令了，这个确实是我的失误，因为之前用着很正常，我用的命令是之前版本激活后，为了方便直接存到电脑记事本里的，更到2.0.4b后没有注意到app内命令变化的提示。上面你们只说命令错了，我还对比“adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh”看了好几遍没有错误，很是纳闷。 现在知道原因了明天开机试一下，十分感谢帮助，为大家添麻烦了，再次表示歉意。
