### ISSUE TITLE
升级到2.0.5（2.0.5a）后出现黑域无法连接本地网络

### ISSUE THREAD

**Issue by JeromeShaw** [brevent/Brevent#145]
机型一加3，系统氢OS公测17版（170714），使用magisksu并有黑域自启magisk模块，已root模式运行，原来可用，在升级到2.0.5以后黑域出现“正在检查黑域服务，请稍候”，检查完毕后显示“黑域无法访问本地网络，请调整防火墙或网络设置”

**Comment by JeromeShaw** [comment]
如果需要日志，需要稍晚时间补上

**Comment by liudongmiao** [comment]
现在黑域确实会做这个检测。请自查是否有网络限制，doze 等。

**Comment by JeromeShaw** [comment]
没有任何网络限制，如果和doze有关的话我看看把黑域加入白名单能不能解决，另外重启可以解决这个问题

**Comment by liudongmiao** [comment]
我个人不建议使用任何强制 doze 的应用。极易出问题。
