### ISSUE TITLE
brevent server cannot start

### ISSUE THREAD

**Issue by FoobarRogers** [brevent/Brevent#145]
10-20 23:42:55.369 D/BreventUI(5007): received: android.intent.action.BOOT_COMPLETED
10-20 23:42:55.390 D/BreventUI(5007): action: android.intent.action.BOOT_COMPLETED, allowRoot: true
10-20 23:42:55.391 D/BreventUI(5007): has su: /sbin/su
10-20 23:42:55.391 D/BreventUI(5007): will startService
10-20 23:42:55.402 D/BreventUI(5007): show notification
10-20 23:42:55.424 V/BreventUI(5007): cannot connect to localhost:59526
10-20 23:42:55.425 D/BreventUI(5007): startBrevent, action: android.intent.action.BOOT_COMPLETED
10-20 23:42:55.433 D/BreventUI(5007): service.adb.tcp.port: 5555
10-20 23:42:55.433 D/BreventUI(5007): adb port: 5555
10-20 23:43:11.470 D/BreventUI(5007): (Cannot start Brevent in 15 seconds)
10-20 23:43:11.470 D/BreventUI(5007): hide notification
10-20 23:43:11.485 V/BreventUI(5007): cannot connect to localhost:59526
10-20 23:43:24.317 D/BreventUI(5007): send, command: CNXN, length: 14
10-20 23:43:24.318 D/BreventUI(5007): recv, head: [65, 85, 84, 72, 1, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 48, 9, 0, 0, -66, -86, -85, -73]
10-20 23:43:24.319 D/BreventUI(5007): recv, command: AUTH, arg0: 1, arg1: 0
10-20 23:43:24.319 D/BreventUI(5007): recv, data: [4, 121, 112, 20, -47, 107, 102, 121, 10, 32, -1, -96, 21, -113, -109, -111, -11, -36, 39, -117]
10-20 23:43:24.326 D/BreventUI(5007): send, command: AUTH, length: 256
10-20 23:43:24.331 D/BreventUI(5007): recv, head: [67, 78, 88, 78, 0, 0, 0, 1, 0, 16, 0, 0, 120, 0, 0, 0, -13, 43, 0, 0, -68, -79, -89, -79]
10-20 23:43:24.331 D/BreventUI(5007): recv, command: CNXN, arg0: 16777216, arg1: 4096
10-20 23:43:24.332 D/BreventUI(5007): recv: data: device::ro.product.name=lineage_oneplus3;ro.product.model=ONEPLUS A3000;ro.product.device=OnePlus3;features=cmd,shell_v2
10-20 23:43:24.332 D/BreventUI(5007): send, command: OPEN, length: 52
10-20 23:43:24.343 D/BreventUI(5007): recv, head: [79, 75, 65, 89, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -80, -76, -66, -90]
10-20 23:43:24.343 D/BreventUI(5007): recv, command: OKAY, arg0: 1, arg1: 1
10-20 23:43:24.450 D/BreventUI(5007): recv, head: [87, 82, 84, 69, 1, 0, 0, 0, 1, 0, 0, 0, 21, 0, 0, 0, -74, 7, 0, 0, -88, -83, -85, -70]
10-20 23:43:24.450 D/BreventUI(5007): recv, command: WRTE, arg0: 1, arg1: 1
10-20 23:43:24.450 D/BreventUI(5007): recv: data: checking for server..
10-20 23:43:35.769 D/BreventUI(5007): recv, head: [87, 82, 84, 69, 1, 0, 0, 0, 1, 0, 0, 0, -2, 0, 0, 0, -63, 87, 0, 0, -88, -83, -85, -70]
10-20 23:43:35.769 D/BreventUI(5007): recv, command: WRTE, arg0: 1, arg1: 1
10-20 23:43:35.769 D/BreventUI(5007): recv: data: started, pid: 5695
10-20 23:43:35.769 D/BreventUI(5007): checking for stable...........timeout
10-20 23:43:35.769 D/BreventUI(5007): 
10-20 23:43:35.769 D/BreventUI(5007): if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
10-20 23:43:35.769 D/BreventUI(5007): for crash log: logcat -b crash -d
10-20 23:43:35.769 D/BreventUI(5007): for brevent log: logcat -b main -d -s BreventLoader BreventServer
10-20 23:43:35.770 D/BreventUI(5007): recv, head: [67, 76, 83, 69, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -68, -77, -84, -70]
10-20 23:43:35.770 D/BreventUI(5007): recv, command: CLSE, arg0: 1, arg1: 1
10-20 23:43:35.770 D/BreventUI(5007): send, command: CLSE, length: 0

**Comment by liudongmiao** [comment]
From the log, it's ok.
