### ISSUE TITLE
android 8.0上自适应图标问题

### ISSUE THREAD

**Issue by antinomypa** [brevent/Brevent#146]
最新的黑域采用了api 26，会有自适应图标，但黑域的图标由于是原来的圆形，在8.0的pixel launcher切换成其他形状图标后会自动套一个白框，略影响美观，建议作者闲暇时能优化一下，感谢作者，辛苦您了。

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by liudongmiao** [comment]
底色我没想好....或者有推荐的颜色么？

**Comment by antinomypa** [comment]
个人觉得现在图标上的黑色应该挺好的

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by liudongmiao** [comment]
看看测试版图标怎么样：https://piebridge.me/br/next/

我本地只有模拟器，看不到效果。
