### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by cv0cv0** [brevent/Brevent#147]
Error:Could not resolve all files for configuration ':brevent:releaseCompileClasspath'.
> Failed to transform file 'classes.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\Code\Android\Brevent\hidden-api\build\intermediates\bundles\default\classes.jar does not exist.

**Comment by liudongmiao** [comment]
这明显与黑域无关嘛...

**Comment by liudongmiao** [comment]
此外，自己下载最新的 gradle。

**Comment by cv0cv0** [comment]
好像是因为找不到project.ext.hiddenApi = files(project(':hidden-api').file('build/intermediates/bundles/default/classes.jar'))
把/*if (project.gradle.startParameter.taskRequests?.empty) {
    // for ide
    dependencies {
        compile project(':hidden-api')
    }
} else {
    // for gradle
    dependencies {
        provided rootProject.hiddenApi
    }
}*/
改为
    dependencies {
        compile project(':hidden-api')
    }
就可以了。

但是装上运行不了。
以debug包运行提示无法使用root启动黑域服务，以release包启动点击进入黑域报 java.lang.UnsupportedOperationException错。
