### ISSUE TITLE
安卓O dp4 root模式失败

### ISSUE THREAD

**Issue by Project-Fi** [brevent/Brevent#149]
WARNING: run as root is experimental!!!
checking for server.fail
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-29 18:40:04.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-29 18:40:04.000' -d -s BreventLoader BreventServer
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
信息量太少，先禁用 selinux 看看。不行就电脑上安装 teamviewer，发邮件我远程调试。

**Comment by liudongmiao** [comment]
已经有朋友协助联调，将于下个版本修复。
