### ISSUE TITLE
未重启，突然需要重新adb

### ISSUE THREAD

**Issue by heganyuliang** [brevent/Brevent#15]
正常使用中，想打开黑域界面时卡在正在获取进程状态很久，然后弹出adb页面。日志如下：

> 05-27 21:47:48.677 16238 16238 D BreventServer: update current to com.android.systemui
05-27 21:47:50.179 16238 16238 D BreventServer: update current to com.click369.dozex
05-27 21:47:51.558 16238 16238 D BreventServer: update current to com.teslacoilsw.launcher
05-27 21:47:54.560 16238 16238 D BreventServer: check and brevent
05-27 21:47:54.994 16238 16238 D BreventServer: Force stop com.tencent.tim(previous running)
05-27 21:47:54.999 16238 16238 D BreventServer: check again in 1124s
05-27 21:47:54.999 16238 16238 D BreventServer: check and brevent, took 436ms
05-27 21:47:55.792 16238 16238 D BreventServer: update current to me.piebridge.brevent
05-27 21:47:55.844 16238 16238 D BreventServer: check and brevent
05-27 21:47:56.034 16238 16238 D BreventServer: check again in 1123s
05-27 21:47:56.034 16238 16238 D BreventServer: check and brevent, took 190ms
05-27 21:47:56.055 16238 16238 D BreventServer: handled status
05-27 21:47:56.055 16238 16238 D BreventServer: checking feelgood
05-27 21:47:56.059 16238 16283 D BreventServer: received feelgood
05-27 21:47:57.876 16238 16238 D BreventServer: update current to com.teslacoilsw.launcher
05-27 21:48:00.877 16238 16238 D BreventServer: check and brevent
05-27 21:48:01.136 16238 16238 D BreventServer: check again in 1117s
05-27 21:48:01.137 16238 16238 D BreventServer: check and brevent, took 259ms
05-27 21:48:02.795 16238 16238 D BreventServer: update current to io.github.javiewer
05-27 21:48:09.401 16238 16238 D BreventServer: update current to com.teslacoilsw.launcher
05-27 21:48:09.402 16238 16238 D BreventServer: abnormal back: io.github.javiewer
05-27 21:48:13.204 16238 16238 D BreventServer: check and brevent
05-27 21:48:13.653 16238 16238 D BreventServer: check again in 3596s
05-27 21:48:13.654 16238 16238 D BreventServer: check and brevent, took 447ms
05-27 21:48:16.601 16238 16238 D BreventServer: update current to com.coolapk.market
05-27 21:48:17.111 16238 16238 D BreventServer: update current to com.google.android.packageinstaller
05-27 21:48:17.319 16238 16238 D BreventServer: update current to com.coolapk.market
05-27 21:49:16.602 16238 16238 D BreventServer: check and brevent
05-27 21:49:16.892 16238 16238 D BreventServer: check again in 3533s
05-27 21:49:16.892 16238 16238 D BreventServer: check and brevent, took 284ms
05-27 21:50:26.396 16238 16238 D BreventServer: update current to com.teslacoilsw.launcher
05-27 21:50:26.397 16238 16238 D BreventServer: abnormal back: com.coolapk.market
05-27 21:50:27.576 16238 16238 D BreventServer: update current to com.android.systemui
05-27 21:50:28.526 16238 16238 D BreventServer: update current to io.github.javiewer
05-27 21:50:29.398 16238 16238 D BreventServer: check and brevent
05-27 21:50:29.858 16238 16238 D BreventServer: Force stop com.coolapk.market(previous running)
05-27 21:50:29.860 16238 16238 D BreventServer: check again in 3599s
05-27 21:50:29.860 16238 16238 D BreventServer: check and brevent, took 459ms
05-27 21:50:32.954 16238 16238 D BreventServer: update current to com.teslacoilsw.launcher
05-27 21:50:32.954 16238 16238 D BreventServer: abnormal back: io.github.javiewer
05-27 21:50:34.127 16238 16238 D BreventServer: update current to com.android.systemui
05-27 21:50:35.169 16238 16238 D BreventServer: update current to me.piebridge.brevent
05-27 21:50:35.955 16238 16238 D BreventServer: check and brevent
05-27 21:50:36.307 16238 16238 D BreventServer: Force stop io.github.javiewer(previous running)
05-27 21:50:36.309 16238 16238 D BreventServer: check again in 3600s
05-27 21:50:36.309 16238 16238 D BreventServer: check and brevent, took 353ms
05-27 21:51:09.259 16238 16238 D BreventServer: update current to com.android.systemui
05-27 21:51:10.229 16238 16238 D BreventServer: update current to com.click369.dozex
05-27 21:51:11.243 16238 16238 D BreventServer: update current to com.teslacoilsw.launcher
05-27 21:51:12.174 16238 16238 D BreventServer: update current to me.piebridge.brevent
05-27 21:51:14.245 16238 16238 D BreventServer: check and brevent
05-27 21:51:14.574 16238 16238 D BreventServer: check again in 3600s
05-27 21:51:14.574 16238 16238 D BreventServer: check and brevent, took 327ms
05-27 21:51:17.293 16238 16238 D BreventServer: update current to com.android.systemui
05-27 21:51:18.553 16238 16238 D BreventServer: update current to com.teslacoilsw.launcher
05-27 21:51:19.852 16238 16238 D BreventServer: update current to me.piebridge.brevent
05-27 21:51:21.555 16238 16238 D BreventServer: check and brevent
05-27 21:51:21.964 16238 16238 D BreventServer: check again in 3600s
05-27 21:51:21.964 16238 16238 D BreventServer: check and brevent, took 407ms
05-27 21:53:38.021 16215 16215 E BreventLoader: worker 16238 exited on signal 15
05-27 21:53:38.021 16215 16215 D BreventLoader: signal arrived, update: 0
05-27 21:53:38.384 27909 27909 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
05-27 21:53:38.759 27921 27921 I BreventServer: Brevent Server 1.1.11 started
05-27 21:53:38.768 27921 27921 I BreventServer: brevent user: 0, uid: 2000
05-27 21:53:38.770 27921 27921 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
05-27 21:53:38.800 27921 27921 I BreventServer: android providers: {com.android.providers.calendar, com.android.providers.media, com.android.providers.downloads, com.android.providers.downloads.ui, com.android.providers.partnerbookmarks, com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.providers.contacts}
05-27 21:53:38.800 27921 27921 I BreventServer: loading brevent list
05-27 21:53:38.803 27921 27921 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 72
05-27 21:53:38.808 27921 27921 D BreventServer: Force stop so.ofo.labofo(load brevent)
05-27 21:53:38.817 27921 27921 D BreventServer: Force stop app.errang.com.poems(load brevent)
05-27 21:53:38.825 27921 27921 D BreventServer: Force stop org.telegram.messenger(load brevent)
05-27 21:53:38.834 27921 27921 D BreventServer: Force stop com.oneplus.soundrecorder(load brevent)
05-27 21:53:38.840 27921 27921 D BreventServer: Force stop com.sankuai.meituan(load brevent)
05-27 21:53:38.843 27921 27921 D BreventServer: Force stop com.colure.app.privacygallery(load brevent)
05-27 21:53:38.854 27921 27921 D BreventServer: Force stop cn.wq.myandroidtoolspro(load brevent)
05-27 21:53:38.858 27921 27921 D BreventServer: Force stop com.clover.imuseum(load brevent)
05-27 21:53:38.863 27921 27921 D BreventServer: Force stop com.lerist.go_hosts(load brevent)
05-27 21:53:38.870 27921 27921 D BreventServer: Force stop com.zjwh.android_wh_physicalfitness(load brevent)
05-27 21:53:38.873 27921 27921 D BreventServer: Force stop com.journey.app(load brevent)
05-27 21:53:38.886 27921 27921 D BreventServer: Force stop com.noctuasoftware.stellarium(load brevent)
05-27 21:53:38.893 27921 27921 D BreventServer: Force stop com.themezilla.pixelui(load brevent)
05-27 21:53:38.898 27921 27921 D BreventServer: Force stop com.microsoft.office.officelens(load brevent)
05-27 21:53:38.901 27921 27921 D BreventServer: Force stop com.kabouzeid.gramophone(load brevent)
05-27 21:53:38.914 27921 27921 D BreventServer: Force stop com.mxtech.ffmpeg.v7_neon(load brevent)
05-27 21:53:38.919 27921 27921 D BreventServer: Force stop com.hupu.football(load brevent)
05-27 21:53:38.928 27921 27921 D BreventServer: Force stop com.xunlei.downloadprovider(load brevent)
05-27 21:53:38.931 27921 27921 D BreventServer: Force stop com.iwantavnow(load brevent)
05-27 21:53:38.939 27921 27921 D BreventServer: Force stop com.lesshint.android.bypassgeo(load brevent)
05-27 21:53:38.950 27921 27921 D BreventServer: Force stop cc.forestapp(load brevent)
05-27 21:53:38.953 27921 27921 D BreventServer: Force stop com.icbc(load brevent)
05-27 21:53:38.960 27921 27921 D BreventServer: Force stop com.microsoft.office.onenote(load brevent)
05-27 21:53:38.970 27921 27921 D BreventServer: Force stop me.phh.superuser(load brevent)
05-27 21:53:38.974 27921 27921 D BreventServer: Force stop kh.android.dir(load brevent)
05-27 21:53:38.977 27921 27921 D BreventServer: Force stop com.apkpure.aegon(load brevent)
05-27 21:53:38.988 27921 27921 D BreventServer: Force stop net.ia.iawriter(load brevent)
05-27 21:53:38.995 27921 27921 D BreventServer: Force stop com.dianping.movieheaven(load brevent)
05-27 21:53:39.002 27921 27921 D BreventServer: Force stop com.shanbay.words(load brevent)
05-27 21:53:39.008 27921 27921 D BreventServer: Force stop com.microsoft.office.officehub(load brevent)
05-27 21:53:39.017 27921 27921 D BreventServer: Force stop com.dv.adm.pay(load brevent)
05-27 21:53:39.026 27921 27921 D BreventServer: Force stop com.tencent.tim(load brevent)
05-27 21:53:39.031 27921 27921 D BreventServer: Force stop com.merriamwebster.premium(load brevent)
05-27 21:53:39.038 27921 27921 D BreventServer: Force stop com.mxtech.videoplayer.ad(load brevent)
05-27 21:53:39.047 27921 27921 D BreventServer: Force stop com.ruby.timetable(load brevent)
05-27 21:53:39.059 27921 27921 D BreventServer: Force stop zhao.apkcrack(load brevent)
05-27 21:53:39.066 27921 27921 D BreventServer: Force stop com.airvisual(load brevent)
05-27 21:53:39.072 27921 27921 D BreventServer: Force stop com.teslacoilsw.launcher.prime(load brevent)
05-27 21:53:39.085 27921 27921 D BreventServer: Force stop com.downloading.main.baiduyundownload(load brevent)
05-27 21:53:39.090 27921 27921 D BreventServer: Force stop com.microsoft.translator(load brevent)
05-27 21:53:39.095 27921 27921 D BreventServer: Force stop com.xda.feed.oneplus3(load brevent)
05-27 21:53:39.103 27921 27921 D BreventServer: Force stop com.thearclabs.polycon(load brevent)
05-27 21:53:39.110 27921 27921 D BreventServer: Force stop uk.co.economist(load brevent)
05-27 21:53:39.117 27921 27921 D BreventServer: Force stop com.topjohnwu.magisk(load brevent)
05-27 21:53:39.120 27921 27921 D BreventServer: Force stop com.android.vending.billing.InAppBillingService.LOCK(load brevent)
05-27 21:53:39.127 27921 27921 D BreventServer: Force stop com.qianyan.eudic(load brevent)
05-27 21:53:39.131 27921 27921 D BreventServer: Force stop com.coolapk.market(load brevent)
05-27 21:53:39.141 27921 27921 D BreventServer: Force stop io.github.javiewer(load brevent)
05-27 21:53:39.144 27921 27921 D BreventServer: Force stop com.muzik(load brevent)
05-27 21:53:39.153 27921 27921 D BreventServer: Force stop com.runar.issdetector.pro(load brevent)
05-27 21:53:39.161 27921 27921 D BreventServer: Force stop eu.thedarken.sdm(load brevent)
05-27 21:53:39.166 27921 27921 D BreventServer: Force stop com.caij.emore(load brevent)
05-27 21:53:39.175 27921 27921 D BreventServer: Force stop com.autonavi.minimap(load brevent)
05-27 21:53:39.180 27921 27921 D BreventServer: Force stop com.Nebugu.SoccerPyhsics2D(load brevent)
05-27 21:53:39.187 27921 27921 D BreventServer: Force stop pl.solidexplorer2(load brevent)
05-27 21:53:39.191 27921 27921 D BreventServer: Force stop com.noodlecake.altosadventure(load brevent)
05-27 21:53:39.195 27921 27921 D BreventServer: Force stop com.mrcigi.aktprofiles(load brevent)
05-27 21:53:39.209 27921 27921 D BreventServer: Force stop com.google.android.keep(load brevent)
05-27 21:53:39.217 27921 27921 D BreventServer: Force stop com.alensw.PicFolder(load brevent)
05-27 21:53:39.223 27921 27921 D BreventServer: Force stop com.ideashower.readitlater.pro(load brevent)
05-27 21:53:39.234 27921 27921 D BreventServer: Force stop mega.privacy.android.app(load brevent)
05-27 21:53:39.238 27921 27921 D BreventServer: Force stop net.oneplus.music(load brevent)
05-27 21:53:39.244 27921 27921 D BreventServer: Force stop melandru.lonicera(load brevent)
05-27 21:53:39.253 27921 27921 D BreventServer: Force stop com.taobao.taobao(load brevent)
05-27 21:53:39.257 27921 27921 D BreventServer: Force stop com.pleasure.trace_wechat(load brevent)
05-27 21:53:39.260 27921 27921 D BreventServer: Force stop com.google.android.play.games(load brevent)
05-27 21:53:39.268 27921 27921 D BreventServer: Force stop com.xio.cardnews(load brevent)
05-27 21:53:39.274 27921 27921 D BreventServer: Force stop com.netease.cloudmusic(load brevent)
05-27 21:53:39.283 27921 27921 D BreventServer: Force stop tv.danmaku.bili(load brevent)
05-27 21:53:39.288 27921 27921 D BreventServer: Force stop com.netease.yanxuan(load brevent)
05-27 21:53:39.294 27921 27921 D BreventServer: Force stop party.danyang.nationalgeographic(load brevent)
05-27 21:53:39.299 27921 27921 D BreventServer: Force stop com.edward.iconpack.pelmix(load brevent)
05-27 21:53:39.300 27921 27921 I BreventServer: loading brevent conf
05-27 21:53:39.882 27921 27921 D BreventServer: check and brevent
05-27 21:53:40.150 27921 27921 D BreventServer: check again in 3600s
05-27 21:53:40.150 27921 27921 D BreventServer: check and brevent, took 267ms
05-27 21:53:41.128 27921 27921 D BreventServer: handled status
05-27 21:53:41.128 27921 27921 D BreventServer: sent first status

**Comment by liudongmiao** [comment]
> 05-27 21:53:38.021 16215 16215 E BreventLoader: worker 16238 exited on signal 15

被其他应用 Kill 了，这种情况，我在想要不要处理…

此外，看看最新测试版是否有解决你的问题。

**Comment by heganyuliang** [comment]
按理说不会啊，设置没有变过，之前也没出现过。我用测试版试一下吧。

**Comment by Bob021** [comment]
把/sdcard/Android/data/me.piebridge.brevent/files文件夹删除掉，重新ADB启动黑域，启动后不要关闭USB调试。试试看。
