### ISSUE TITLE
2.1.2自编译版报下面的错误

### ISSUE THREAD

**Issue by cv0cv0** [brevent/Brevent#15]
OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/06151600:user/release-keys
SELinux: false

WARNING: run as root is experimental!!!
checking for server..started, pid: 26654
checking for stable....quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> /system/bin/logcat -b crash -t '08-11 08:10:35.000' -d
08-11 08:10:38.839 26654 26679 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-2
08-11 08:10:38.839 26654 26679 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(JJZ)V in class Lme/piebridge/brevent/protocol/BreventDisableRoot; or its super classes (declaration of 'me.piebridge.brevent.protocol.BreventDisableRoot' appears in /data/app/me.piebridge.brevent-1/base.apk)
08-11 08:10:38.839 26654 26679 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:497)
08-11 08:10:38.839 26654 26679 E AndroidRuntime: 	at me.piebridge.brevent.server.b.a(BreventSocket.java:71)
08-11 08:10:38.839 26654 26679 E AndroidRuntime: 	at me.piebridge.brevent.server.b.run(BreventSocket.java:39)
08-11 08:10:38.839 26654 26679 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '08-11 08:10:35.000' -d -s BreventLoader BreventServer
08-11 08:10:36.145 26635 26635 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
08-11 08:10:36.583 26654 26654 D BreventServer: get service: package
08-11 08:10:36.584 26654 26654 D BreventServer: args: [10]
08-11 08:10:36.584 26654 26654 I BreventServer: signal: 10
08-11 08:10:36.599 26654 26654 I BreventServer: starting Brevent Server 2.1.2
08-11 08:10:36.606 26654 26654 D BreventServer: get service: package
08-11 08:10:36.607 26654 26654 I BreventServer: brevent user: 0, uid: 0
08-11 08:10:36.608 26654 26654 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-11 08:10:36.626 26654 26654 I BreventServer: loading brevent list
08-11 08:10:36.630 26654 26654 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 84
08-11 08:10:36.646 26654 26654 I BreventServer: loading brevent conf
08-11 08:10:36.648 26654 26654 D BreventServer: get service: appwidget
08-11 08:10:36.657 26654 26654 D BreventServer: get service: usagestats
08-11 08:10:37.293 26654 26667 I BreventServer: Brevent Event, now: 1502410237
08-11 08:10:37.294 26654 26654 D BreventServer: check and brevent
08-11 08:10:37.295 26654 26654 D BreventServer: get service: notification
08-11 08:10:37.303 26654 26667 I BreventServer: system_server: 1284, now: 1502410237
08-11 08:10:37.397 26654 26654 D BreventServer: get service: activity
08-11 08:10:37.436 26654 26654 D BreventServer: get service: alarm
08-11 08:10:37.437 26654 26654 D BreventServer: get service: wallpaper
08-11 08:10:37.528 26654 26654 D BreventServer: get service: deviceidle
08-11 08:10:37.538 26654 26654 D BreventServer: check again in 34s
08-11 08:10:37.538 26654 26654 D BreventServer: check and brevent, took 244ms
08-11 08:10:37.540 26654 26654 D BreventServer: get service: batterystats
08-11 08:10:37.546 26654 26654 I BreventServer: charging: false
08-11 08:10:37.546 26654 26654 I BreventServer: support standby: true
08-11 08:10:37.546 26654 26654 I BreventServer: support stopped: true
08-11 08:10:37.546 26654 26654 I BreventServer: Brevent Server 2.1.2 started
08-11 08:10:37.549 26654 26654 D BreventServer: get service: appops
08-11 08:10:37.549 26654 26654 D BreventServer: set appops, package: me.piebridge.brevent, package uid: 10861, code: 43, mode: 0
08-11 08:10:37.549 26654 26654 I BreventServer: checking port
08-11 08:10:37.559 26654 26654 I BreventServer: checked port
08-11 08:10:37.765 26654 26679 W BreventServer: no first brevent event
08-11 08:10:37.838 26654 26654 I BreventServer: received first event
08-11 08:10:38.875 26635 26635 E BreventLoader: worker 26654 exited on signal 9
08-11 08:10:38.875 26635 26635 D BreventLoader: signal arrived, update: 0
08-11 08:10:38.876 26631 26631 D BreventLoader: worker 26635 exited with status 0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
你下了太新的代码...而且，2.1.2 的 tag 我没有上传，你知道是哪个 commit 么?
你差不多要切到这个 commit: https://github.com/brevent/Brevent/commit/b4829a012e635cffeba0f2bbdffd1e8d447a3384

**Comment by cv0cv0** [comment]
好的，谢谢。
