### ISSUE TITLE
建议增强自动验证支付宝转账记录

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#150]
目前支付宝在与某个人的“往来记录”里查询，确实只能显示近1年的，但通过在个人总账里查询，将时间跨度调好，照样能找出与之1年前或更久的记录，点进去也一样能看到详情（账单详情）。

建议1年前的根据账单详情验证，账单详情有具体的订单号，这个做不了假，小金额的可通过分开点详情进去来累计。

**Comment by CVN-77** [comment]
在账单详情里，有对方头像，可以点进去进入转账界面，作为确认身份（也就是作者）的辅助验证。

**Comment by liudongmiao** [comment]
我从来不推荐使用什么往来记录，而是使用“账单详情”。
在我本地看，可以展示一年以前的数据，没有任何问题。

而且，一年后会怎么样，谁知道呢？

**Comment by CVN-77** [comment]
我说的往来记录其实和黑域用于累计金额的转账记录是一样的，界面完全一样，“往来记录”是在账单详情里的描述，“转账记录”就是转账输入金额界面的右上角，点进去是同一个界面。在支付宝选择某个账户再进去查询“转账记录”，确实有些是查不到1年前的记录。
不过确定就是使用“账单详情”来验证的话，那就没问题了，账单详情可以通过定位时间来查询。

**Comment by CVN-77** [comment]
这是最新版2.0.7弹窗描述语，看来我没记错，怪不得之前有疑惑：


“允许 ROOT 启动”需要支付 3 美元或 15 人民币（推荐支付宝）。

如您已经支付，请打开“支付宝”（需要临时禁用 Xposed），点开“转账记录”（不是“账单详情”），将会自动识别（如果账单过期，将无法自动识别）。

如果无法自动识别，或者其它方式支付，请发送邮件（需要安装邮件客户端），附上支付订单截图。



点开“转账记录”（不是“账单详情”），当时以为只看转账记录累计总额而不看账单详情。

**Comment by liudongmiao** [comment]
这是自动模式，随便本地怎么玩。只要不清空数据，都在。
至于故意清空数据，然后找茬的，就像对我要求永不清理后台设置的人说的那样：

请告诉我永久是多久，到了那天再说。

以及，咋不说，到了 2038 年，好多 32 位设备都运行不了呢？

**Comment by CVN-77** [comment]
支付宝转账记录是保存近期，近12个月的记录是可能有，但再往前的就不确定了，支付宝官方客服是说手机客户端保存近12个月的转账记录没问题，再往前就推荐用电脑版定位时间查询，我也试过查询转账记录完全为空的账号，用时间查询找到与之2015年的记录。相信因为这个“转账记录”来问的是多数，毕竟描述是这样（后来描述加了无法自动识别）。

我觉得现在部分人有疑问很正常，担心1年后用不了也很正常，1年毕竟短，而且肯定有很多想着付费=授权，他们没有捐赠这个概念，1年后如果因为找不到记录用不了他们肯定接受不了，play没人质疑时间，就因为知道play的特性，很多人想支付宝也像play那样，这些其实没什么，给他们指出能查到账单详情也好。故意清空数据这个我不猜测别人会不会这么做，账单就是凭据，一般是没账单不处理，就像play账号丢失了找不回来了那也没辙，这些非正常情况其实都不用想。

最后我还是希望能在技术上加强支付宝的自动验证，毕竟账单能通过时间查出来，不一定在转账记录。

**Comment by CVN-77** [comment]
其实加强自动识别有好处，功能完善更加方便，到时也不用一个个人工认证，对双方都好，不过如果做不了那也算了，我从来都是在功能方面的提议，不考虑评论区的口舌之争。
