### ISSUE TITLE
请求改进

### ISSUE THREAD

**Issue by AronLL** [brevent/Brevent#151]
既然没有黑域诸如无障碍应用（如lastpass）、天气时钟（pure天气）、设备管理器（airdroid）这些的可能和必要性，为什么不新增一个选项，将这些从正在运行中排除出去了~

希望能得到改进，但是这确实不是非常必要的功能，毕竟它与黑域本身的功能无关。

（另外，希望作者不要囿于酷安的撕逼了~毕竟不是人民币，没可能所有人都爱你O(∩_∩)O哈哈~）

**Comment by vvb2060** [comment]
黑域应用还有一个任务管理器的身份，而不仅仅是用来展示一个黑域列表。

**Comment by liudongmiao** [comment]
这个想法...太诡异。

让人看到有一个应用在运行，但是黑域里找不到，问题更麻烦。
