### ISSUE TITLE
Why？要崩溃了。

### ISSUE THREAD

**Issue by cv0cv0** [brevent/Brevent#152]
OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/06151600:user/release-keys
SELinux: true

WARNING: run as root is experimental!!!
checking for server..started, pid: 13389
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-30 18:47:47.000' -d
07-30 18:47:48.435 13389 13389 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
07-30 18:47:48.435 13389 13389 E AndroidRuntime: java.lang.reflect.InvocationTargetException
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2265)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:264)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/f/i;
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at me.piebridge.brevent.server.e.a(HideApi.java:368)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at me.piebridge.brevent.server.e.d(HideApi.java:358)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1082)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.j(BreventServer.java:732)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:2065)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2171)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	... 4 more
07-30 18:47:48.435 13389 13389 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.f.i" on path: DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/data/app/me.piebridge.brevent-1/lib/arm64, /system/lib64, /vendor/lib64]]
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-30 18:47:48.435 13389 13389 E AndroidRuntime: 	... 10 more
07-30 18:47:48.437 13389 13389 E AndroidRuntime: Error reporting crash
07-30 18:47:48.437 13389 13389 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-30 18:47:48.437 13389 13389 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-30 18:47:48.437 13389 13389 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
07-30 18:47:48.437 13389 13389 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5163)
07-30 18:47:48.437 13389 13389 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
07-30 18:47:48.437 13389 13389 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-30 18:47:48.437 13389 13389 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-30 18:47:47.000' -d -s BreventLoader BreventServer
07-30 18:47:47.449 13370 13370 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-30 18:47:47.810 13389 13389 D BreventServer: get service: package
07-30 18:47:47.811 13389 13389 D BreventServer: args: [10]
07-30 18:47:47.811 13389 13389 I BreventServer: signal: 10
07-30 18:47:47.831 13389 13389 I BreventServer: starting Brevent Server 2.0.7a
07-30 18:47:47.839 13389 13389 D BreventServer: get service: package
07-30 18:47:47.839 13389 13389 W BreventServer: version unmatched, running: 2.0.7a, installed: brevent
07-30 18:47:47.840 13389 13389 I BreventServer: brevent user: 0, uid: 0
07-30 18:47:47.841 13389 13389 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-30 18:47:47.854 13389 13389 I BreventServer: loading brevent list
07-30 18:47:47.854 13389 13389 I BreventServer: loading brevent conf
07-30 18:47:47.855 13389 13389 D BreventServer: get service: appwidget
07-30 18:47:47.860 13389 13389 D BreventServer: get service: usagestats
07-30 18:47:48.356 13389 13401 I BreventServer: Brevent Event, now: 1501411668
07-30 18:47:48.357 13389 13389 D BreventServer: check and brevent
07-30 18:47:48.358 13389 13389 D BreventServer: get service: notification
07-30 18:47:48.367 13389 13401 I BreventServer: system_server: 1583, now: 1501411668
07-30 18:47:48.453 13370 13370 E BreventLoader: worker 13389 exited on signal 9
07-30 18:47:48.453 13370 13370 D BreventLoader: signal arrived, update: 0
07-30 18:47:48.454 13366 13366 D BreventLoader: worker 13370 exited with status 0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
确实是一个问题，需要你打包 brevent 项目也使用最新版本的 gradle 及优化。

**Comment by liudongmiao** [comment]
@cv0cv0 你可以单独发邮件给我，我给你看看到底是什么问题。
