### ISSUE TITLE
adb上输入代码后最后一行显示“out of time"

### ISSUE THREAD

**Issue by fenglipop29** [brevent/Brevent#154]
电脑上用adb输入代码，前面显示都正常，最后一行显示”checking for stable ...... out of time"
然后黑域在手机上能正常使用。但是这行代码对吗？
手机是nexus 6p 安卓7.1.2

**Comment by liudongmiao** [comment]
你确定是 out of time，不是 timeout 么？

timeout 只是表明，在检测过程中，黑域服务没有收到来自黑域的请求。

**Comment by fenglipop29** [comment]
哦哦，对的，timeout 那应该没什么问题吧？

**Comment by liudongmiao** [comment]
强行停止黑域，重新进入，查看是否正常。正常的话，没有问题；不正常的话，看提示。
