### ISSUE TITLE
ERROR: please open Brevent to make a new brevent.sh

### ISSUE THREAD

**Issue by zjacai** [brevent/Brevent#156]
按照流程走，出现这个：ERROR: please open Brevent to make a new brevent.sh
斐讯小龙c1330，阿里云OS，未root，系统版本5.1.1

**Comment by vvb2060** [comment]
打开黑域应用，按照提示在电脑上输入命令并执行

**Comment by zjacai** [comment]
按照教程流程走的，手机端打开了，但就是提示这个，手机重启过也是这样，重装apk也不行，
就第4步成功不了，，，

**Comment by vvb2060** [comment]
你输入的命令是？

zjacai <notifications@github.com> 于 2017年10月27日周五 上午10:47写道：

**Comment by zjacai** [comment]
1、adb devices
List of devices attached
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
C1330   device

2、adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
ERROR: please open Brevent to make a new brevent.sh

**Comment by vvb2060** [comment]
`adb shell cat /data/data/me.piebridge.brevent/brevent.sh`
`adb shell ls -l /data/local/tmp`
`adb shell dumpsys package me.piebridge.brevent`
分别执行以上三条命令，结果都发上来看看？

**Comment by vvb2060** [comment]
好了，原因找到了。等待下一个版本

**Comment by liudongmiao** [comment]
感谢汇报，请前往测试。 https://piebridge.me/br/

**Comment by zjacai** [comment]
新版本的运行结果：
checking for server....fail
[command] pm path me.piebridge.brevent
package:/system/priv-app/Shell/Shell.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '10-27 21:16:11.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '10-27 21:16:11.000' -d -s BreventLoader BreventServer
10-27 21:16:13.465 22040 22040 D BreventLoader: line: package:/system/priv-app/Shell/Shell.apk
10-27 21:16:13.491 22040 22040 D BreventLoader: loader path: /system/priv-app/Shell/Shell.apk
10-27 21:16:13.493 22040 22040 E BreventLoader: can't find loader: /system/priv-app/Shell/Shell.apk
10-27 21:16:13.494 22035 22035 E BreventLoader: worker 22040 exited with status 255
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by zjacai** [comment]
这是dumpsys的结果：
Activity Resolver Table:

  Non-Data Actions:

      android.intent.action.MAIN:

        54d2dc0 me.piebridge.brevent/.ui.BreventActivity



Receiver Resolver Table:

  Non-Data Actions:

      me.piebridge.brevent.intent.action.ALIPAY:

        84d2af9 me.piebridge.brevent/.ui.BreventServerReceiver

      me.piebridge.brevent.intent.action.ADD_PACKAGE:

        84d2af9 me.piebridge.brevent/.ui.BreventServerReceiver

      android.intent.action.LOCKED_BOOT_COMPLETED:

        1895a3e me.piebridge.brevent/.ui.BreventReceiver

      android.intent.action.BOOT_COMPLETED:

        1895a3e me.piebridge.brevent/.ui.BreventReceiver

      me.piebridge.brevent.intent.action.ALIPAY2:

        84d2af9 me.piebridge.brevent/.ui.BreventServerReceiver

      me.piebridge.brevent.intent.action.HOME_TID:

        84d2af9 me.piebridge.brevent/.ui.BreventServerReceiver



Permissions:

  Permission [me.piebridge.brevent.permission.MANAGER] (6975154):

    sourcePackage=me.piebridge.brevent

    uid=10129 gids=null type=0 prot=signature

    perm=Permission{aee809f me.piebridge.brevent.permission.MANAGER}

    packageSetting=PackageSetting{e00f9f2 me.piebridge.brevent/10129}



Registered ContentProviders:

  me.piebridge.brevent/android.support.v4.content.FileProvider:

    Provider{cb765ec me.piebridge.brevent/android.support.v4.content.FileProvider}



ContentProvider Authorities:

  [me.piebridge.brevent.fileprovider]:

    Provider{cb765ec me.piebridge.brevent/android.support.v4.content.FileProvider}

      applicationInfo=ApplicationInfo{bac7db5 me.piebridge.brevent}



Key Set Manager:

  [me.piebridge.brevent]

      Signing KeySets: 94



Packages:

  Package [me.piebridge.brevent] (e00f9f2):

    userId=10129

    pkg=Package{5bcdc4a me.piebridge.brevent}

    codePath=/data/app/me.piebridge.brevent-2

    resourcePath=/data/app/me.piebridge.brevent-2

    legacyNativeLibraryDir=/data/app/me.piebridge.brevent-2/lib

    primaryCpuAbi=armeabi

    secondaryCpuAbi=null

    versionCode=119 targetSdk=27

    versionName=2.3.2

    splits=[base]

    applicationInfo=ApplicationInfo{bac7db5 me.piebridge.brevent}

    flags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]

    pkgFlagsEx=[ ]

    dataDir=/data/user/0/me.piebridge.brevent

    supportsScreens=[small, medium, large, xlarge, resizeable, anyDensity]

    timeStamp=2017-10-27 21:15:24

    firstInstallTime=2017-10-26 11:24:47

    lastUpdateTime=2017-10-27 21:15:29

    signatures=PackageSignatures{820c33e [7c487bb]}

    installPermissionsFixed=true installStatus=1

    pkgFlags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]

    declared permissions:

      me.piebridge.brevent.permission.MANAGER: prot=signature, INSTALLED

    requested permissions:

      android.permission.INTERNET

      com.android.vending.BILLING

      android.permission.RECEIVE_BOOT_COMPLETED

      me.piebridge.brevent.permission.MANAGER

      android.permission.READ_LOGS

      android.permission.EXPAND_STATUS_BAR

      android.permission.PACKAGE_USAGE_STATS

      android.permission.DUMP

      android.permission.GET_APP_OPS_STATS

    install permissions:

      android.permission.RECEIVE_BOOT_COMPLETED: granted=true

      android.permission.EXPAND_STATUS_BAR: granted=true

      android.permission.INTERNET: granted=true

      me.piebridge.brevent.permission.MANAGER: granted=true

    User 0:  installed=true hidden=false stopped=false notLaunched=false enabled=0

      gids=[3003]

      runtime permissions:

**Comment by liudongmiao** [comment]
pm path me.piebridge.brevent 返回 Shell.apk，就不再支持了...
