### ISSUE TITLE
不支持“停止状态”

### ISSUE THREAD

**Issue by zsakvo** [brevent/Brevent#158]
您好，系统是LineageOS13，装有Google服务框架，使用root启动黑域。但是停止状态一直显示“不支持” 请问是什么原因可能引起的呢？（在之前2.2.4以及之前一直都是正常的  后来2.2.6开始就突然不支持了）
![646499c648260604e8f4dd036d6a0305](https://user-images.githubusercontent.com/25399519/32111222-854bdcea-baff-11e7-9041-e71171da52e4.png)

**Comment by liudongmiao** [comment]
不支持就是不支持，表明权限不够之类。

**Comment by liudongmiao** [comment]
对于这一切，黑域都有完整日志。
