### ISSUE TITLE
请问在哪里下载APK呢

### ISSUE THREAD

**Issue by xhsmyxzx** [brevent/Brevent#159]
你好，请问除了Google Play在哪里下载APK呢

**Comment by liyufan** [comment]
https://piebridge.me/br/

**Comment by xhsmyxzx** [comment]
谢谢

**Comment by vvb2060** [comment]
其它版：国内ROM厂商的商店，目前有[魅族商店](http://app.meizu.com/apps/public/detail?package_name=me.piebridge.brevent)和锤子商店
(同)play版：[非官方网站](https://piebridge.me/br/) （包含所有历史版本）、[play商店](https://play.google.com/store/apps/details?id=me.piebridge.brevent)、[应用宝](https://a.app.qq.com/o/simple.jsp?pkgname=me.piebridge.brevent)
~或许GitHub也可以发布？~

**Comment by liyufan** [comment]
在GitHub发布了，那些自己编译肯定会很困惑。。

**Comment by liudongmiao** [comment]
Github 一向访问起来很慢，有时会访问不动。
