### ISSUE TITLE
duplicate notification on Android O.

### ISSUE THREAD

**Issue by flowfire** [brevent/Brevent#161]
when I enable "allow sync" option for fcm supported apps, they push duplicate notifications to my device.
enviroment:
nexus5x
Android O DP4

**Comment by flowfire** [comment]
用我蹩脚的英文提了 issue 才发现大家都是提中文 issue 的……
我还是用中文描述一下吧。
在 android o dp4 版本上
为支持 FCM 的应用程序启用  允许同步  选项后
每次收到消息都会收到两条相同的推送
内容相同但是格式不一样
一条是彩色应用程序名，右边还有和 icon
一条是黑白应用程序名

**Comment by liudongmiao** [comment]
这个，就和黑域无关了....你直接不黑域看看吧。

黑域不改变应行行为。
