### ISSUE TITLE
优化音乐应用不识别Retro Music

### ISSUE THREAD

**Issue by zsakvo** [brevent/Brevent#161]
2.3.4play版，Retro Music正播放音乐且有常驻通知，黑域不识别其播放状态，仍然正常结束之。
![3115155e763c06f0cd45186db142e6a6](https://user-images.githubusercontent.com/25399519/32363487-96a713b4-c0aa-11e7-8622-388a2e4e7a05.jpg)

**Comment by vvb2060** [comment]
Nexus 6P Android8.1测试正常。
播放时连接电脑或使用终端，执行`dumpsys media.audio_flinger`以及` dumpsys activity processes`，将结果发上来。

**Comment by zsakvo** [comment]
dumpsys activity processes：

[dumpsys activity processes.log](https://github.com/brevent/Brevent/files/1440703/dumpsys.activity.processes.log)

dumpsys media.audio_flinger：

[dumpsys media.audio_flinger.log](https://github.com/brevent/Brevent/files/1440704/dumpsys.media.audio_flinger.log)

**Comment by liudongmiao** [comment]
点发送日志吧，最新版会有相关的 debug 信息了。

**Comment by liudongmiao** [comment]
```
    Name Active Client Type      Fmt Chn mask Session fCount S F SRate  L dB  R dB    Server Main buf  Aux Buf Flags UndFrmCnt
       1     no   4623    0 00000001 00000001      68   1924 I 0 48000   -10   -10  00000000 0xf4c0d000 0x0 0x000         0 
       0    yes   3016    3 00000001 00000003     408  22050 A 3 44100     0     0  003C631E 0xf4c0d000 0x0 0x000         0 
```

根据音频日志，3016 在播放音乐。
但是，进程里，找不到 3016 这个记录...
你可以 ps 找下这个进程是啥。

**Comment by liudongmiao** [comment]
实验性功能真的很实验性，不要有太多期望。

**Comment by zsakvo** [comment]
只是遇到了问题单纯的提一下，并没有什么别的意思（包括期望），不要误会

**Comment by zsakvo** [comment]
ps也看不到
![jietu20171103-183042 2x](https://user-images.githubusercontent.com/25399519/32369697-1cf589d6-c0c5-11e7-8a9a-69f3fdec0cf0.jpg)

**Comment by vvb2060** [comment]
@zsakvo 想知道是 只有Retro Music(这次)不能识别，还是 这个功能从来没有生效？

**Comment by zsakvo** [comment]
@vvb2060  网易云正常  别的没试过

**Comment by aviraxp** [comment]
你输错了 3016 不是 3106

**Comment by zsakvo** [comment]
额  抱歉……应该是这样
![jietu20171103-191514 2x](https://user-images.githubusercontent.com/25399519/32371357-7d911d68-c0cb-11e7-80a0-cde3b6a852cf.jpg)

**Comment by liudongmiao** [comment]
特意去下了 https://play.google.com/store/apps/details?id=code.name.monkey.retromusic
在 8.0 与 8.1 上均能识别。所以，可能属于 ROM 差异。
