### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Jermainsa** [brevent/Brevent#162]
两台手机一部安卓6.0的成功了，然后7.0的出现这样的情况请问什么原因

E:\platform-tools>adb -d shell sh /data/data/me.piebridge.brevent/brevent.so
sh: /data/data/me.piebridge.brevent/brevent.so: Permission denied

**Comment by liudongmiao** [comment]
指令输入错误....参照屏幕提示。

**Comment by Jermainsa** [comment]
不是很懂请大神指路

**Comment by Ecareyu** [comment]
同问，我这边也是，求指导

**Comment by Ecareyu** [comment]
去酷安更新到最新版本就好了
