### ISSUE TITLE
Cannot turn off network debug when boot completed

### ISSUE THREAD

**Issue by liudongmiao** [brevent/Brevent#163]

**Comment by liudongmiao** [comment]
@vvb2060 你是没有使用 2.3.4 么。
理论上你使用的话，肯定能发现这个问题吧...

**Comment by vvb2060** [comment]
网络adb常开，我以为是“网络adb”应用开机自启的效果……

Liu DongMiao <notifications@github.com> 于 2017年11月7日周二 上午8:05写道：

**Comment by liudongmiao** [comment]
这个已经修了…

因为上个版本，为了解决某些不正常 su 导致通知一直不变…所以启动成功后，直接强行停止黑域。

强行停止以后，当然没法关闭网络调试（不会关闭非黑域开启的调试），执行 8.0
下为 adb 优化的脚本了。

**Comment by liudongmiao** [comment]
虽然已经发 beta 版，但可能不会在应用商店升级，用户会很奇怪，只为 root 用户优化了…而绝大部分用户，不 root。
