### ISSUE TITLE
希望可以增加一个隐藏部分用户应用的隐藏选项

### ISSUE THREAD

**Issue by Kotori-0912** [brevent/Brevent#164]
应为使用了OMS主题的系统编译安装了很多主题的APK，然后黑域获取用户应用列表的时候也把OMS主编译的题包括进内，有时候找应用不太方便，希望大大可以增加一个选择允许隐藏掉非必要的用户应用（类似于OMS主题的安装包）
![_20170802120155](https://user-images.githubusercontent.com/25550007/28857251-8548ac78-777a-11e7-91b1-e68afe984383.png)

**Comment by vvb2060** [comment]
没有入口的用户应用，一并隐藏了？用户应用里一般是激活器，输入法，插件应用，还有这个叠加层……

**Comment by liudongmiao** [comment]
它都没有运行，你要翻到后面去干啥啊...

我猜，你需要的是搜索功能....

**Comment by Kotori-0912** [comment]
@liudongmiao 默认是没有运行，但是一打开他就在最上面QAQ，感觉看起来很乱.......

**Comment by liudongmiao** [comment]
那我没有办法..你可以让开发者给它来个名字，把它放到最后去...

我也会考虑加个算法，如果名字和包名一样，放最后去。

但绝对不会不显示。

**Comment by liudongmiao** [comment]
你要的选项，大概是，隐藏名字和包名一样的的应用。

即使有，属于强迫症选项，要求支付的。

但你是第一个想到的，如果做了，肯定会给你特别贡献勋章。

**Comment by Kotori-0912** [comment]
@liudongmiao 这个的确是我强迫症问题QAQ，有时候进去取消掉部分用户软件感觉很难找，我也知道这个属于强迫症问题，所以我一开始也已经想过需要捐赠，关于上次Play商店双Google账户问题无法验证的问题我自己找到了答案，只要在设备设定已经捐赠的Google账户为主账户，后面无论添加多少个Google账户也不会改变

**Comment by liudongmiao** [comment]
但我也不一定会做。。。会先排个序，这种应用放最末尾去，眼不见心净。

**Comment by liudongmiao** [comment]
@Kotori-0912 已经发布最新测试版: https://piebridge.me/br/next/

没有选项，但是把这种名字以包名开头的，放到最末尾去了。

暂无计划做选项，即使不开启“显示所有应用”。

**Comment by Kotori-0912** [comment]
@liudongmiao 刚刚安装好了测试版，感觉这也样子也挺好的把叠加层的应用放在最后面看来也是一个不错的选择
