### ISSUE TITLE
黑域失效问题

### ISSUE THREAD

**Issue by imaxumin** [brevent/Brevent#164]
黑域用一阵时间会失效，要重新连接电脑才行，没有重启手机。机型nexus 6p Android 8.0

**Comment by liudongmiao** [comment]
- 商店描述
> [Android O]
> Android O 下，如果关闭调试模式或者更改 USB 选项，黑域就会失效。如果拔线后，调试模式就被关闭，请尝试其它的 USB 选项，或者执行 adb tcpip 5555 开启网络调试后再拔线。请注意：调试模式有风险，不要随意授权。正常情况下，使用“仅充电”选项就好。

- 改动日志
> Android O 用户请不要关闭“USB 调试”，不要更改 USB 选项。

- 向导
> “调试模式”权限很高，Android O 以下设备重启就失效；在 Android O 及以上则更严格，关闭“USB 调试”或更改 USB 选项就失效。

- 设置
> 不要停用“USB 调试”，不要更改 USB 选项

请问，我要怎么写，你才能看到？
哦，这是具体原因：https://www.jianshu.com/p/14e6705ffc28

当然，如果你使用 Root 启动，黑域特别优化了这件事。
