### ISSUE TITLE
求问哪里有上传安卓apk？

### ISSUE THREAD

**Issue by 627850449** [brevent/Brevent#165]
谷歌市场貌似下架了，而且国区的还不能下载。求一个稳定的更新网址。

**Comment by liudongmiao** [comment]
1. 应用宝，可升级不可搜: https://a.app.qq.com/o/simple.jsp?pkgname=me.piebridge.brevent
2. 锤子商店
3. 魅族商店
4. 酷安: https://coolapk.com/apk/me.piebridge.brevent
5. Play 商店：https://play.google.com/store/apps/details?id=me.piebridge.brevent

终级站点：https://piebridge.me/br/
