### ISSUE TITLE
新功能：建议卸载 或 不允许后台运行

### ISSUE THREAD

**Issue by liudongmiao** [brevent/Brevent#165]
主要点，分析过去一段时间，如每天的日志。提取以下点：

- 应用主动打开
- 应用被强行停止

如果超过一个阀值，则给出方案：
- 建议卸载
- 不允许后台运行 （Android 7+）
- 停用 （需要配合其它应用）

@vvb2060 @aviraxp

**Comment by liudongmiao** [comment]
当然，这个重要性，还不如提供唤醒与强行停止日志。

以及，如果判断一个应用是不是恶意应用，真的要引入机器学习了。

这应该是一个 logistic regression...呃，又有一周作业没完成，逃（。。。

**Comment by liudongmiao** [comment]
功能冻结，暂不处理。

**Comment by GithubApkUser** [comment]
柳大好想法！
