### ISSUE TITLE
奥利奥无法开启黑域

### ISSUE THREAD

**Issue by Hanvayne** [brevent/Brevent#168]
Xiaomi/aicp_sagit/sagit:8.0.0/OPR6.170623.012/3d35474072:userdebug/test-keys

/data/data/me.piebridge.brevent/brevent.sh[30]: cp: not found
WARNING: /data/local/tmp is not writable
checking for server..fail
[command] pm path me.piebridge.brevent
sh: pm: not found
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '11-08 14:50:25.000' -d
sh: logcat: not found
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '11-08 14:50:25.000' -d -s BreventLoader BreventServer
sh: logcat: not found
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

无论是Root还是adb都是这样显示的。。

**Comment by vvb2060** [comment]
不是黑域的问题，去找系统编译者。可以给他看这份日志，表明该ROM中，重要系统命令不可用。
