### ISSUE TITLE
建议咨询

### ISSUE THREAD

**Issue by QAQQIAOY** [brevent/Brevent#169]
免root 模式开启能否像冰箱那样做成设备管理员模式，附上冰箱设置链接
https://github.com/heruoxin/Ice-Box-Docs/blob/master/Device%20Owner%20%EF%BC%88%E5%85%8D%20root%EF%BC%89%E6%A8%A1%E5%BC%8F%E8%AE%BE%E7%BD%AE.md

**Comment by vvb2060** [comment]
不可能，权限不足。黑域需要完整的ADB调试（shell）权限。
另外，黑域专为无root用户开发，没有免root模式，只有实验性的root模式。

**Comment by liudongmiao** [comment]
@QAQQIAOY 你也说了那是设备管理员啊...

即使是设备管理员，依旧无法：
- 强行停止应用
- 待机
- 实验性的应用权限


而且，设备管理员需要：
- 删除已有账号
- （可能）只能有一个激活的设备管理员

你可能能同意“删除已有帐号”；而只能有一个激活的设备管理员，我估计你要骂人。
