### ISSUE TITLE
[Suggestion] 增加备份/还原功能

### ISSUE THREAD

**Issue by wbsdty331** [brevent/Brevent#169]
对于加入黑域的应用列表进行备份，重装黑域后即可直接通过备份文件还原

还原的时候如果某些在备份文件里面的 App 没有安装，则自动跳过，完成后对用户提示

**Comment by vvb2060** [comment]
如果在服务没有运行时卸载黑域，列表不会清空。
然后我不懂这应用还需要经常卸载重装吗？备份有何意义……

**Comment by liudongmiao** [comment]
不会做这样的功能，也没什么可以备份的。
