### ISSUE TITLE
brevent dumpsys dead

### ISSUE THREAD

**Issue by plutochang** [brevent/Brevent#17]
HTC U11
Android: 7.11
軟體號碼: 1.03.709.4

黑域版本: 2.1.1

請參考，謝謝。

htc/ocndugl_00709/htc_ocndugl:7.1.1/NMF26X/923215.4:user/release-keys
SELinux: true

WARNING: run as root is experimental!!!
checking for server..fail
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
>>> /system/bin/logcat -b crash -t '08-11 15:11:26.000' -d
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '08-11 15:11:26.000' -d -s BreventLoader BreventServer
08-11 15:11:26.653 26251 26251 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
08-11 15:11:27.058 26270 26270 D BreventServer: get service: package
08-11 15:11:27.059 26270 26270 D BreventServer: args: [10]
08-11 15:11:27.059 26270 26270 I BreventServer: signal: 10
08-11 15:11:27.061 26270 26270 I BreventServer: starting Brevent Server 2.1.1
08-11 15:11:27.068 26270 26270 D BreventServer: get service: package
08-11 15:11:27.070 26270 26270 I BreventServer: brevent user: 0, uid: 0
08-11 15:11:27.071 26270 26270 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-11 15:11:27.089 26270 26270 I BreventServer: loading brevent list
08-11 15:11:27.093 26270 26270 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 117
08-11 15:11:27.120 26270 26270 I BreventServer: loading brevent conf
08-11 15:11:27.124 26270 26270 D BreventServer: get service: appwidget
08-11 15:11:27.125 26270 26270 E BreventServer: Cannot dump appwidget(brevent dumpsys dead)
08-11 15:11:27.142 26251 26251 E BreventLoader: worker 26270 exited with status 1
08-11 15:11:27.142 26251 26251 D BreventLoader: signal arrived, update: 0
08-11 15:11:27.143 26247 26247 D BreventLoader: worker 26251 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by vvb2060** [comment]
你应该看到了“無法執行 dumpsys，請禁用 SELinux，然后再試”的提示才对。
可以用root权限执行 `setenforce 0` 命令来禁用SELinux，重启后失效。

我早已向问题 SU 提交了 PR，但对方未予理会 https://github.com/topjohnwu/magiskpolicy/pull/3
作为变通，你可以将这个修补脚本放到Magisk开机自动执行目录下：/magisk/.core/post-fs-data.d/
文件名随意，内容为：
```
#!/system/bin/sh

magiskpolicy --live "allow system_server su fifo_file write"
magiskpolicy --live "allow audioserver su fd use"
magiskpolicy --live "allow audioserver su fifo_file write"
```
注意：这个修补脚本仅仅是让黑域能够运行，MagiskSU的dumpsys命令依旧没有完全修复。

**Comment by EraserKing** [comment]
This workaround seems still not working (Brevent server cannot start).
I ran into timeout (when run as root) after this is applied (originally it's the problem described in the topic).
Same on Nexus 6P / 8.0.0 and Nexus 4 / 7.1.2.

**Comment by joel-zhu** [comment]
C:\Users\admin\Desktop\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
10-07 18:47:31.883  5105  5105 I BreventServer: starting Brevent Server 2.2.3
10-07 18:47:31.961  5105  5105 I BreventServer: brevent user: 0, uid: 2000
10-07 18:47:31.962  5105  5105 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
10-07 18:47:32.016  5105  5105 I BreventServer: no service overlay
10-07 18:47:32.029  5105  5105 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 63
10-07 18:47:33.205  5105  5140 I BreventServer: Brevent Event, now: 1507373253
10-07 18:47:33.216  5105  5140 I BreventServer: system_server: 1335, now: 1507373253
10-07 18:47:33.757  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {com.google.android.googlequicksearchbox, in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:47:33.813  5105  5105 I BreventServer: notification_cancel_all events: 17
10-07 18:47:33.815  5105  5105 I BreventServer: charging: true
10-07 18:47:33.815  5105  5105 I BreventServer: support standby: true
10-07 18:47:33.816  5105  5105 I BreventServer: support stopped: true
10-07 18:47:33.816  5105  5105 I BreventServer: support upgrade: true
10-07 18:47:33.821  5105  5105 I BreventServer: granted permission
10-07 18:47:34.294  5105  5105 I BreventServer: Brevent Server 2.2.3 started
10-07 18:47:34.295  5105  5105 I BreventServer: received first event
10-07 18:47:37.639  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {com.google.android.googlequicksearchbox, in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:47:44.412  5105  5164 I BreventServer: make brevent whitelist, args: [whitelist, -me.piebridge.brevent]
10-07 18:47:44.501  5105  5164 W BreventServer: no tracks
10-07 18:47:44.511  5105  5164 W BreventServer: sent 10 to 5093
10-07 18:48:32.827  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:49:33.232  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:49:38.478  5105  5164 W BreventServer: no tracks
10-07 18:49:46.505  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {org.telegram.messenger, in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:49:46.508  5105  5105 W BreventServer: has no BreventActivity
10-07 18:50:16.517  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:50:31.042  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 18:51:02.474  5105  5105 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, is.shortcut}
10-07 19:11:09.647 13442 13442 I BreventServer: received first event

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/magiskpolicy/commit/d7a6127273407a32bccf75e70fa7bbe84c14e4f8#diff-18e802b298cd88b01205762067b89fb6R89
Magisk已修复dumpsys命令

**Comment by liudongmiao** [comment]
黑域早就不使用“直接 Root”了...
