### ISSUE TITLE
如何查看自我诊断日志

### ISSUE THREAD

**Issue by StrollStars** [brevent/Brevent#171]
最近发现黑域才用ROOT方式开机启动，有时候会无法正常运行，因而开启了“自我诊断”功能，该功能“必要时收集日志”，请问我该如何查看该日志并粘贴上来？

**Comment by liudongmiao** [comment]
发送日志时，会自动携带。

**Comment by StrollStars** [comment]
请问下发送功能在哪里？看了下菜单只有一个反馈，点击浏览器打开这个项目的页面。

**Comment by liudongmiao** [comment]
如果你在菜单中看不到“日志”，就说明你系统没有给黑域日志权限（android.permission.READ_LOGS）。

**Comment by StrollStars** [comment]
查看了下系统设置，给予了ROOT权限，当然这个关系不大。
应用权限中黑域没有任何权限，记得没有提醒黑域申请权限，请问这是怎么回事？
系统：CM13  黑域版本：Google Play最新版

**Comment by vvb2060** [comment]
如果没有安装邮件应用，不会显示日志选项。

**Comment by StrollStars** [comment]
感谢 @vvb2060 提醒，确实禁用了邮件应用，但是启用邮件应用后，重启系统，还是找不到“日志”菜单项。

**Comment by liudongmiao** [comment]
找一个支持的邮箱，如 QQ邮箱，GMail，Inbox 等。
