### ISSUE TITLE
提示timeout，虽然还是可以开启，但是感觉不爽啊

### ISSUE THREAD

**Issue by U0Axuan** [brevent/Brevent#172]
提示如下：
checking for server...started, pid: 30073
checking for stable...........timeout

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by liudongmiao** [comment]
你是不是执行的时候，没有打开黑域？

**Comment by U0Axuan** [comment]
好像是的，下回开黑域试试(*/ω╲*)

**Comment by U0Axuan** [comment]
好像是的，下回开黑域试试(/ω╲)
