### ISSUE TITLE
Permanent notification for Brevent?

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#173]
Hi.
Android may unload Brevent on wish. As I know many applications show constant notifcation to prevent that. Is there any chance Brevent will implement this too?

**Comment by liudongmiao** [comment]
I don't know what do you mean.

Brevent works even it's force-stopped, as the actual working Brevent Server is not part of Android System (AMS).

**Comment by ghost** [comment]
@liudongmiao Strange. If Brevent app is not running it doesn't work for me. I.e. brevented apps in Android task manager never get killed. And I seen Android killed Brevent app after few days of use.

**Comment by ghost** [comment]
Oh, you're right. Looks like things just don't work 100% reliable on the rom I use
