### ISSUE TITLE
黑域首页好像有广告，我这是下到了盗版还是miui的问题啊

### ISSUE THREAD

**Issue by wozuida521** [brevent/Brevent#174]

**Comment by vvb2060** [comment]
图呢？具体情况？
关于盗版，在 https://piebridge.me/br/ 下载apk进行覆盖安装，能够安装就没问题。

**Comment by wozuida521** [comment]
![screenshot_2017-11-17-13-19-56-655_me piebridge brevent](https://user-images.githubusercontent.com/24818755/32934682-96229adc-cba7-11e7-9882-abb5be4df3c6.png)

**Comment by wozuida521** [comment]
应该是miui的问题

**Comment by liudongmiao** [comment]
黑域没有任何广告，也没有启动页。
请给个完整的视频，以及日志，好定位问题。

**Comment by vvb2060** [comment]
从图上看应该是MIUI为黑域加的开屏广告。
https://dev.mi.com/doc/page_id=8466/index.html
这是小米商店那个与黑域相同包名的应用的开发者注册的广告

**Comment by wozuida521** [comment]
我不懂的怎么提取日志哎，有什么方法可以取消这个广告啊，刚刚从谷歌商店重新下了一个，还是有广告，这miui有毒

**Comment by liudongmiao** [comment]
@wozuida521 目前黑域已在小米商店下架，请后续继续关注是否有广告。
