### ISSUE TITLE
我是黑莓keyone用户，关于激活方式

### ISSUE THREAD

**Issue by ffxk** [brevent/Brevent#177]
现在我已经正常使用黑域，并也愿意支付微不足道的绵薄力量。

黑莓keyone也是无法root的，从以前的手机，以前的阻止运行，到现在的黑莓，现在的黑域，我都是跟随作者，在黑莓上使用黑域的时间里，有几次出差没办法的情况下重启了手机就无法使用黑域了。

我不懂软件技术，就想问问作者，黑域是否可以开发一种其他的激活方式做到很方便的激活，或激活一次管永久。  是安卓api上不支持，还是用户安全上考虑。
           感谢作者开发的软件。

**Comment by vvb2060** [comment]
这是Android自身的安全限制，并且随着Android的版本升级而越加严格。
对于外出等情况，假定有使用充电宝和数据线，可以参考[这个项目](https://github.com/vvb2060/BreventLauncher)，它通过硬件来启动黑域服务。

**Comment by ffxk** [comment]
感谢，我了解下

**Comment by liudongmiao** [comment]
@vvb2060 哈哈，你肯定没注意到 brevent 下面还多了个项目..

@ffxk 请阅读这个：https://www.jianshu.com/p/9fee93554974

**Comment by vvb2060** [comment]
@liudongmiao  完全没有注意……看来我那个也没存在必要了。
[飞智黑域厅](https://github.com/brevent/MotionElf)

**Comment by ffxk** [comment]
@liudongmiao 通过搜索已经阅读了，并下单了硬件。等硬件到了在测试，激活流程

**Comment by liudongmiao** [comment]
@vvb2060 你的还是有必要的。
我的版本，由于使用 testkey 签名，比你的大几十还是几百字节好像...

**Comment by ffxk** [comment]
看来大神们也有在为激活方式寻各种解决方案，BreventLauncher 与 MotionElf 是同样功能吧， @liudongmiao 激活黑域后可以不删除伪造飞智吧。

**Comment by liudongmiao** [comment]
不要删除那个 apk，否则每次激活都要安装。
同时，打开一次自动隐藏，眼不见心为烦。

黑域也不会在列表中隐藏这个应用。
