### ISSUE TITLE
安卓8.0一拔线就失效

### ISSUE THREAD

**Issue by androgyneutrois** [brevent/Brevent#178]
索尼XZ1 compact.
手机未重启，**# **没有修改usb调试**及配置**。
连接电脑adb指令成功后，一旦拔掉数据线，下次打开黑域仍提示需要adb.

**Comment by androgyneutrois** [comment]
试了下，adb时# **usb连接必须是默认**弹出的“为此设备充电”，且之后每次连电脑都不能改。
这样就不再需要重新adb。

**Comment by liudongmiao** [comment]
#164 我只有一个疑问，到底要怎样写，才能明白？
直接 android o 上弹出一个提示框？

**Comment by androgyneutrois** [comment]
请仔细体会上边加黑字体的区别

**Comment by vvb2060** [comment]
@androgyneutrois  直接说明了，拔线之前，`adb shell getprop sys.usb.state`的结果必须是adb。

**Comment by liudongmiao** [comment]
@androgyneutrois 既然你能体会，那么为何不拔线后看下日志，然后搜索 usb 或者 adb 字样？

你真的认为你不更改 usb 配置，系统就不更改么？
你真的认真阅读过 #164 中我的回复，及原理么？

**Comment by androgyneutrois** [comment]
@liudongmiao 是的，我完全理解并且感谢你的详尽分享。

然而我所指出的，不过是个语文问题：
黑域说明里说“请勿切换USB模式”，这句话可以理解为“**使用默认的USB模式**”，也可能被理解为“配置黑域前和配置黑域后，保持USB模式不变”。
二者的区别在于，系统默认USB模式是“**充电**”，而（我个人）惯用模式是“**文件传输**”。那么，我在配置黑域前后都勾选“文件传输”，是否也符合黑域说明里所说“不切换 USB 模式”？
奥利奥重启，一连上电脑，USB模式被**自动**切换成默认的“充电”，这个过程里，根据您所描述的原理，adbd就已经被清理了吧？即便再手动切回“文件传输”也于事无补。

综上，建议文档说明直接指出“保持系统默认的USB模式”，而不是“请勿切换USB模式”。

**Comment by liudongmiao** [comment]
- ...如果关闭调试模式或者更改 USB 选项，黑域就失效...
这句描述可能的情况，一般人不会动。

- ...如果拔线后，调试模式就被关闭，请尝试其它的 USB 选项...
这句描述动了的情况，明确给出提示，尝试其它选项。

- ...正常情况下，使用“仅充电”选项就好...
这句告诉你，哪种模式一般不会有问题。

不认真阅读提示，你爱怎么理解就怎么理解。

**Comment by androgyneutrois** [comment]
我觉得我已经说清楚了。你喜欢就好

**Comment by kobe01116** [comment]
androgyneutrois
您好　能否加您微信或ｑｑ，我跟你一样的情形　想请教您！
我ｑｑ: ~删除个人信息~
