### ISSUE TITLE
关于黑域更新建议

### ISSUE THREAD

**Issue by SoDebug** [brevent/Brevent#18]
1.更新日志描述问题
原更新日志

v2.1
- 支持简单搜索
- 支持排序，优化名称排序
- 优化 ROOT 启动，不再需要 7 次显示 ROOT
- 在日志中添加电池相关信息
- 黑域在前台时，退出强制 doze
magisksu 用户，如果出现 dumpsys 错误，请参考此页面：
https://github.com/topjohnwu/magiskpolicy/pull/3

1.其中的"退出强制doze"建议改为"强制退出doze"
当时看了半天愣是没看出是啥意思，相信也有其他感同身受者！
2.建议去除或者改善"退出强制doze"这个功能！
有时候黑域本身就处于doze的白名单中，黑域服务不会受到干扰，不需要强制整个系统退出doze模式！尤其是通过电脑ADB命令激活doze的用户，离开电脑后，一进入黑域前台。doze就被强制退出，需要重新用电脑doze.
3.黑域设置中部分用语
（1）位置:设置/高级功能/检查通知/底部描述
原描述:只有当您的机器解锁或查看通知卡顿时，才需要关闭"检查通知"
建议把"机器"改为"设备"，"解锁"改为"解除锁屏"（避免与"oem解锁混淆"）
（2）位置:设置/黑域清单/自动更新
建议把"自动更新"改为"自动刷新列表"，

**Comment by liudongmiao** [comment]
1-2. 不会改。
强制 doze 只会有副作用，所以，一定要退出。
就是退出“强制 doze”，exit "force doze"，没毛病。
根据谷歌规范，亮屏不应该启用 doze，除了测试。

3.1 允许通知将会去除

3.2 确实含有自动更新的意思...
如黑域服务升级，真的会自动更新...虽然你关闭这个选项，还是会自动更新...
但如果这个选项不可改，就是无法自动更新了。

**Comment by SoDebug** [comment]
哦，好吧

**Comment by liudongmiao** [comment]
感谢建议。

自动更新可能需要更新描述，但“自动刷新列表”更为不妥。
