### ISSUE TITLE
1.1.11adb以后不断刷新黑域服务没有相应

### ISSUE THREAD

**Issue by ftdPhoenix** [brevent/Brevent#18]
更新1.1.11以后重启手机再次adb时候发现出问题了

PS E:\手机相关\platform-tools-latest-windows\platform-tools> .\adb -d shell sh /sdcard/Android/data/me.piebridge.brevent
/brevent.sh
found old brevent_server, pid: 13326, killing
checking.....brevent_server started, pid: 30953
checking for stable...........ok

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
PS E:\手机相关\platform-tools-latest-windows\platform-tools>  .\adb -d logcat -d -b crash
05-28 21:16:44.380  3631  3631 F libc    : "/data/user/0/com.baidu.tieba/files/libprocmox_v1_4.so": error: only position independent executables (PIE) are supported.
05-28 21:16:44.380  3631  3631 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3631 (libprocmox_v1_4)
05-28 21:16:44.450  3637  3637 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 21:16:44.450  3637  3637 F DEBUG   : UUID: 328a42b7-1b16-4eab-ae73-414ea1d27544
05-28 21:16:44.450  3637  3637 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:7.0/39.2.A.0.417/1528746196:user/release-keys'
05-28 21:16:44.450  3637  3637 F DEBUG   : Revision: '0'
05-28 21:16:44.450  3637  3637 F DEBUG   : ABI: 'arm'
05-28 21:16:44.450  3637  3637 F DEBUG   : pid: 3631, tid: 3631, name: libprocmox_v1_4  >>> /data/user/0/com.baidu.tieba/files/libprocmox_v1_4.so <<<
05-28 21:16:44.450  3637  3637 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-28 21:16:44.450  3637  3637 F DEBUG   :     r0 00000000  r1 00000e2f  r2 00000006  r3 00000008
05-28 21:16:44.450  3637  3637 F DEBUG   :     r4 ea94658c  r5 00000006  r6 ea946534  r7 0000010c
05-28 21:16:44.450  3637  3637 F DEBUG   :     r8 ea8da010  r9 00000000  sl 00000000  fp ffb40674
05-28 21:16:44.450  3637  3637 F DEBUG   :     ip 00000000  sp ffb3f3d0  lr ea926caf  pc ea92773c  cpsr 200f0010
05-28 21:16:44.459  3637  3637 F DEBUG   :
05-28 21:16:44.459  3637  3637 F DEBUG   : backtrace:
05-28 21:16:44.460  3637  3637 F DEBUG   :     #00 pc 0004573c  /system/bin/linker (__dl_tgkill+12)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #01 pc 00044cab  /system/bin/linker (__dl_pthread_kill+34)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #02 pc 0003d00f  /system/bin/linker (__dl_raise+10)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #03 pc 0003ba9b  /system/bin/linker (__dl___libc_android_abort+34)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #04 pc 0003aa00  /system/bin/linker (__dl_abort+4)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #05 pc 0003caeb  /system/bin/linker (__dl___libc_fatal+22)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #06 pc 00009433  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2250)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #07 pc 00008ad3  /system/bin/linker (__dl___linker_init+358)
05-28 21:16:44.461  3637  3637 F DEBUG   :     #08 pc 000027d0  /system/bin/linker (_start+4)
05-28 21:18:13.941  7575  7575 F libc    : "/data/user/0/com.kingpoint.gmcchh/files/com.cmcc.aoe.keepalive": error: only position independent executables (PIE) are supported.
05-28 21:18:13.941  7575  7575 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7575 (com.cmcc.aoe.ke)
05-28 21:18:14.104  7578  7578 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 21:18:14.104  7578  7578 F DEBUG   : UUID: 0095725e-618a-40ea-9420-7bec1e3170dc
05-28 21:18:14.104  7578  7578 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:7.0/39.2.A.0.417/1528746196:user/release-keys'
05-28 21:18:14.104  7578  7578 F DEBUG   : Revision: '0'
05-28 21:18:14.104  7578  7578 F DEBUG   : ABI: 'arm'
05-28 21:18:14.105  7578  7578 F DEBUG   : pid: 7575, tid: 7575, name: com.cmcc.aoe.ke  >>> /data/user/0/com.kingpoint.gmcchh/files/com.cmcc.aoe.keepalive <<<
05-28 21:18:14.105  7578  7578 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-28 21:18:14.105  7578  7578 F DEBUG   :     r0 00000000  r1 00001d97  r2 00000006  r3 00000008
05-28 21:18:14.105  7578  7578 F DEBUG   :     r4 ee9cb58c  r5 00000006  r6 ee9cb534  r7 0000010c
05-28 21:18:14.105  7578  7578 F DEBUG   :     r8 ee95f010  r9 00000000  sl 00000000  fp fff02eb4
05-28 21:18:14.105  7578  7578 F DEBUG   :     ip 00000000  sp fff01c10  lr ee9abcaf  pc ee9ac73c  cpsr 200f0010
05-28 21:18:14.124  7578  7578 F DEBUG   :
05-28 21:18:14.124  7578  7578 F DEBUG   : backtrace:
05-28 21:18:14.126  7578  7578 F DEBUG   :     #00 pc 0004573c  /system/bin/linker (__dl_tgkill+12)
05-28 21:18:14.126  7578  7578 F DEBUG   :     #01 pc 00044cab  /system/bin/linker (__dl_pthread_kill+34)
05-28 21:18:14.126  7578  7578 F DEBUG   :     #02 pc 0003d00f  /system/bin/linker (__dl_raise+10)
05-28 21:18:14.127  7578  7578 F DEBUG   :     #03 pc 0003ba9b  /system/bin/linker (__dl___libc_android_abort+34)
05-28 21:18:14.127  7578  7578 F DEBUG   :     #04 pc 0003aa00  /system/bin/linker (__dl_abort+4)
05-28 21:18:14.127  7578  7578 F DEBUG   :     #05 pc 0003caeb  /system/bin/linker (__dl___libc_fatal+22)
05-28 21:18:14.127  7578  7578 F DEBUG   :     #06 pc 00009433  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2250)
05-28 21:18:14.127  7578  7578 F DEBUG   :     #07 pc 00008ad3  /system/bin/linker (__dl___linker_init+358)
05-28 21:18:14.127  7578  7578 F DEBUG   :     #08 pc 000027d0  /system/bin/linker (_start+4)
05-28 21:18:25.827  8058  8059 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xded0910c in tid 8059 (Thread-3)
05-28 21:18:26.104  8068  8068 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 21:18:26.104  8068  8068 F DEBUG   : UUID: 335c3995-3dfe-45f7-97c0-d7d4c0e90065
05-28 21:18:26.104  8068  8068 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:7.0/39.2.A.0.417/1528746196:user/release-keys'
05-28 21:18:26.105  8068  8068 F DEBUG   : Revision: '0'
05-28 21:18:26.105  8068  8068 F DEBUG   : ABI: 'arm'
05-28 21:18:26.105  8068  8068 F DEBUG   : pid: 8058, tid: 8059, name: Thread-3  >>> com.netease.edu.ucmooc:cosine <<<
05-28 21:18:26.105  8068  8068 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xded0910c
05-28 21:18:26.105  8068  8068 F DEBUG   :     r0 ded0910c  r1 00000000  r2 00000004  r3 ded0910c
05-28 21:18:26.105  8068  8068 F DEBUG   :     r4 ded0910c  r5 00000004  r6 00003a47  r7 deef9ee8
05-28 21:18:26.105  8068  8068 F DEBUG   :     r8 deef9f28  r9 da275e00  sl 00000000  fp deef9eb4
05-28 21:18:26.105  8068  8068 F DEBUG   :     ip 80000000  sp deef9de0  lr e4cdcbf5  pc e67c4cc4  cpsr 80070010
05-28 21:18:26.112  8068  8068 F DEBUG   :
05-28 21:18:26.112  8068  8068 F DEBUG   : backtrace:
05-28 21:18:26.112  8068  8068 F DEBUG   :     #00 pc 00017cc4  /system/lib/libc.so (memset+196)
05-28 21:18:26.112  8068  8068 F DEBUG   :     #01 pc 00003bf1  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z16zeroProcessStatev+136)
05-28 21:18:26.112  8068  8068 F DEBUG   :     #02 pc 00002f11  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z15daemonj_preparePKPKcP7_JNIEnv+8)
05-28 21:18:26.112  8068  8068 F DEBUG   :     #03 pc 00002be3  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (Java_com_netease_cosine_core_Cosine_nativeWorker+16)
05-28 21:18:26.112  8068  8068 F DEBUG   :     #04 pc 00824579  /data/app/com.netease.edu.ucmooc-1/oat/arm/base.odex (offset 0x794000)
05-28 21:19:35.295 10856 10857 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdf08610c in tid 10857 (Thread-3)
05-28 21:19:35.561 10864 10864 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 21:19:35.561 10864 10864 F DEBUG   : UUID: 086e782e-6c30-4581-b257-a0c4a20f5892
05-28 21:19:35.561 10864 10864 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:7.0/39.2.A.0.417/1528746196:user/release-keys'
05-28 21:19:35.561 10864 10864 F DEBUG   : Revision: '0'
05-28 21:19:35.561 10864 10864 F DEBUG   : ABI: 'arm'
05-28 21:19:35.565 10864 10864 F DEBUG   : pid: 10856, tid: 10857, name: Thread-3  >>> com.netease.edu.ucmooc:cosine <<<
05-28 21:19:35.565 10864 10864 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdf08610c
05-28 21:19:35.565 10864 10864 F DEBUG   :     r0 df08610c  r1 00000000  r2 00000004  r3 df08610c
05-28 21:19:35.565 10864 10864 F DEBUG   :     r4 df08610c  r5 00000004  r6 00003a47  r7 dee79ee8
05-28 21:19:35.566 10864 10864 F DEBUG   :     r8 dee79f28  r9 da275e00  sl 00000000  fp dee79eb4
05-28 21:19:35.566 10864 10864 F DEBUG   :     ip 80000000  sp dee79de0  lr e4cdcbf5  pc e67c4cc4  cpsr 80070010
05-28 21:19:35.571 10864 10864 F DEBUG   :
05-28 21:19:35.571 10864 10864 F DEBUG   : backtrace:
05-28 21:19:35.571 10864 10864 F DEBUG   :     #00 pc 00017cc4  /system/lib/libc.so (memset+196)
05-28 21:19:35.571 10864 10864 F DEBUG   :     #01 pc 00003bf1  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z16zeroProcessStatev+136)
05-28 21:19:35.571 10864 10864 F DEBUG   :     #02 pc 00002f11  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z15daemonj_preparePKPKcP7_JNIEnv+8)
05-28 21:19:35.571 10864 10864 F DEBUG   :     #03 pc 00002be3  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (Java_com_netease_cosine_core_Cosine_nativeWorker+16)
05-28 21:19:35.571 10864 10864 F DEBUG   :     #04 pc 00824579  /data/app/com.netease.edu.ucmooc-1/oat/arm/base.odex (offset 0x794000)
05-28 21:21:01.583 14953 14954 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xded4c10c in tid 14954 (Thread-3)
05-28 21:21:01.899 14958 14958 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 21:21:01.899 14958 14958 F DEBUG   : UUID: b0e06d45-93b1-41fb-9c26-7ee58346d282
05-28 21:21:01.899 14958 14958 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:7.0/39.2.A.0.417/1528746196:user/release-keys'
05-28 21:21:01.899 14958 14958 F DEBUG   : Revision: '0'
05-28 21:21:01.899 14958 14958 F DEBUG   : ABI: 'arm'
05-28 21:21:01.899 14958 14958 F DEBUG   : pid: 14953, tid: 14954, name: Thread-3  >>> com.netease.edu.ucmooc:cosine <<<
05-28 21:21:01.899 14958 14958 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xded4c10c
05-28 21:21:01.900 14958 14958 F DEBUG   :     r0 ded4c10c  r1 00000000  r2 00000004  r3 ded4c10c
05-28 21:21:01.900 14958 14958 F DEBUG   :     r4 ded4c10c  r5 00000004  r6 00003a47  r7 deef9ee8
05-28 21:21:01.900 14958 14958 F DEBUG   :     r8 deef9f28  r9 d8d04e00  sl 00000000  fp deef9eb4
05-28 21:21:01.900 14958 14958 F DEBUG   :     ip 80000000  sp deef9de0  lr e4cdcbf5  pc e67c4cc4  cpsr 80070010
05-28 21:21:01.918 14958 14958 F DEBUG   :
05-28 21:21:01.918 14958 14958 F DEBUG   : backtrace:
05-28 21:21:01.918 14958 14958 F DEBUG   :     #00 pc 00017cc4  /system/lib/libc.so (memset+196)
05-28 21:21:01.918 14958 14958 F DEBUG   :     #01 pc 00003bf1  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z16zeroProcessStatev+136)
05-28 21:21:01.918 14958 14958 F DEBUG   :     #02 pc 00002f11  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z15daemonj_preparePKPKcP7_JNIEnv+8)
05-28 21:21:01.918 14958 14958 F DEBUG   :     #03 pc 00002be3  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (Java_com_netease_cosine_core_Cosine_nativeWorker+16)
05-28 21:21:01.918 14958 14958 F DEBUG   :     #04 pc 00824579  /data/app/com.netease.edu.ucmooc-1/oat/arm/base.odex (offset 0x794000)
05-28 21:22:51.773 18559 18560 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xded6610c in tid 18560 (Thread-3)
05-28 21:22:52.022 18578 18578 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 21:22:52.022 18578 18578 F DEBUG   : UUID: 2f3eb5dd-825c-4a1f-9aa2-14451e1e5f84
05-28 21:22:52.022 18578 18578 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:7.0/39.2.A.0.417/1528746196:user/release-keys'
05-28 21:22:52.023 18578 18578 F DEBUG   : Revision: '0'
05-28 21:22:52.023 18578 18578 F DEBUG   : ABI: 'arm'
05-28 21:22:52.023 18578 18578 F DEBUG   : pid: 18559, tid: 18560, name: Thread-3  >>> com.netease.edu.ucmooc:cosine <<<
05-28 21:22:52.023 18578 18578 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xded6610c
05-28 21:22:52.023 18578 18578 F DEBUG   :     r0 ded6610c  r1 00000000  r2 00000004  r3 ded6610c
05-28 21:22:52.023 18578 18578 F DEBUG   :     r4 ded6610c  r5 00000004  r6 00003a47  r7 deef9ee8
05-28 21:22:52.023 18578 18578 F DEBUG   :     r8 deef9f28  r9 d8d04e00  sl 00000000  fp deef9eb4
05-28 21:22:52.023 18578 18578 F DEBUG   :     ip 80000000  sp deef9de0  lr e4cdcbf5  pc e67c4cc4  cpsr 80070010
05-28 21:22:52.026 18578 18578 F DEBUG   :
05-28 21:22:52.026 18578 18578 F DEBUG   : backtrace:
05-28 21:22:52.026 18578 18578 F DEBUG   :     #00 pc 00017cc4  /system/lib/libc.so (memset+196)
05-28 21:22:52.027 18578 18578 F DEBUG   :     #01 pc 00003bf1  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z16zeroProcessStatev+136)
05-28 21:22:52.027 18578 18578 F DEBUG   :     #02 pc 00002f11  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z15daemonj_preparePKPKcP7_JNIEnv+8)
05-28 21:22:52.027 18578 18578 F DEBUG   :     #03 pc 00002be3  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (Java_com_netease_cosine_core_Cosine_nativeWorker+16)
05-28 21:22:52.027 18578 18578 F DEBUG   :     #04 pc 00824579  /data/app/com.netease.edu.ucmooc-1/oat/arm/base.odex (offset 0x794000)
05-28 21:29:02.811 25069 25070 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe4caa10c in tid 25070 (Thread-3)
05-28 21:29:03.199 25089 25089 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 21:29:03.199 25089 25089 F DEBUG   : UUID: 4e99319e-562c-4cb8-a9e9-d9bdb4ab657e
05-28 21:29:03.199 25089 25089 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:7.0/39.2.A.0.417/1528746196:user/release-keys'
05-28 21:29:03.199 25089 25089 F DEBUG   : Revision: '0'
05-28 21:29:03.199 25089 25089 F DEBUG   : ABI: 'arm'
05-28 21:29:03.199 25089 25089 F DEBUG   : pid: 25069, tid: 25070, name: Thread-3  >>> com.netease.edu.ucmooc:cosine <<<
05-28 21:29:03.199 25089 25089 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe4caa10c
05-28 21:29:03.200 25089 25089 F DEBUG   :     r0 e4caa10c  r1 00000000  r2 00000004  r3 e4caa10c
05-28 21:29:03.200 25089 25089 F DEBUG   :     r4 e4caa10c  r5 00000004  r6 00003a47  r7 deef9ee8
05-28 21:29:03.200 25089 25089 F DEBUG   :     r8 deef9f28  r9 da275e00  sl 00000000  fp deef9eb4
05-28 21:29:03.200 25089 25089 F DEBUG   :     ip 80000000  sp deef9de0  lr e4cdcbf5  pc e67c4cc4  cpsr 80070010
05-28 21:29:03.215 25089 25089 F DEBUG   :
05-28 21:29:03.215 25089 25089 F DEBUG   : backtrace:
05-28 21:29:03.215 25089 25089 F DEBUG   :     #00 pc 00017cc4  /system/lib/libc.so (memset+196)
05-28 21:29:03.215 25089 25089 F DEBUG   :     #01 pc 00003bf1  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z16zeroProcessStatev+136)
05-28 21:29:03.215 25089 25089 F DEBUG   :     #02 pc 00002f11  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (_Z15daemonj_preparePKPKcP7_JNIEnv+8)
05-28 21:29:03.215 25089 25089 F DEBUG   :     #03 pc 00002be3  /data/app/com.netease.edu.ucmooc-1/lib/arm/libcosine.so (Java_com_netease_cosine_core_Cosine_nativeWorker+16)
05-28 21:29:03.215 25089 25089 F DEBUG   :     #04 pc 00824579  /data/app/com.netease.edu.ucmooc-1/oat/arm/base.odex (offset 0x794000)

**Comment by liudongmiao** [comment]
先看看最新测试版吧：https://piebridge.me/br/next/

**Comment by ftdPhoenix** [comment]
OK了 重装测试版以后 一次adb就成功了，多谢
