### ISSUE TITLE
改进与建议

### ISSUE THREAD

**Issue by Lyon1994** [brevent/Brevent#180]
1，我想问这软件是你们开发的么？创意十足，我也是Android开发者，没想起来拿这个adb来做这种事，666

2，改进：对于开发者而言，在使用黑域的时候无法正常进行调试，会有干扰，能否开一个adb代理服务，端口改成6666，让开发者使用adb wifi进行调试软件？

**Comment by vvb2060** [comment]
黑域只在root启动时操作网络adb，后续不依赖网络adb。请具体描述如何干扰？

**Comment by Lyon1994** [comment]
在使用usb模式调试的时候黑域经常性的被关闭，无法正常监控其他应用，

**Comment by vvb2060** [comment]
#164
