### ISSUE TITLE
Publish APK on Github

### ISSUE THREAD

**Issue by IzzySoft** [brevent/Brevent#181]
It would be great if you could [attach the `.apk` to the `releases/` here at Github](https://help.github.com/articles/creating-releases/), for those folks working without Playstore. Could you do that? Thanks in advance!

**Comment by liudongmiao** [comment]
https://piebridge.me/br/

**Comment by IzzySoft** [comment]
I know. But I can't fetch it automatically there as e.g. the file name changes. I was thinking about adopting it into [my F-Droid repo](https://apt.izzysoft.de/fdroid). Would mean added publicity (not that you'd need that) and automatic updates via the F-Droid client. My updater can deal with Github releases – but it's not "intelligent" enough to deal with "random structures". If there would be a *fixed file name*, that would work (as your server's response contains the `Last Modified` timestamp). Any chance for either?

**Comment by liudongmiao** [comment]
You can just download it from Play Store.

GitHub release is unavailable in China.

**Comment by liudongmiao** [comment]
As there are some network provider would cache the apk with the same name.
So, I never use the same name if apk is changed.

**Comment by IzzySoft** [comment]
> You can just download it from Play Store.

That'd violate their TOS if I did that automatically.

> So, I never use the same name if apk is changed.

That's as it's setup here with several projects (with an URL like `…/latest.apk`). Which could simply be a redirect or symlink to the real one, and have a minimal "cache time"/Expiry set (e.g. 12h; [see here](https://veerasundar.com/blog/2014/09/setting-expires-header-for-assets-nginx/) for how to set up expiry per file with NGinx which you're running AFAIK).

IIRC, having your app in my repo would benefit your Chinese users another way, too, as AFAIK access to Playstore is quite limited there as well – or am I wrong with that assumption? But however: If you don't want that, I'll of course respect your decision. Was just an offer from my end :wink:

**Comment by liudongmiao** [comment]
Then you can use https://piebridge.me/br/latest.apk, and for ipv6: https://v.piebridge.me/br/latest.apk. It will be 302 to real link.

There are many backup for chinese users, and some of them can use experiment features without payment (donation).
Now, all the apks are the same with Play Store.

**Comment by IzzySoft** [comment]
Thanks a lot, @liudongmiao – that looks good! Wasn't sure about the redirect, but indeed I get the LastMod of the real APK. So I've set it up with my repo, and you're welcome to point interested users [here](https://apt.izzysoft.de/fdroid/index/apk/me.piebridge.brevent). And you can be sure it's your unmodified APK that lands there :wink:

Thanks again!

**Comment by IzzySoft** [comment]
@liudongmiao looks like the certificate is expired today. Are you going to renew it?

~~~
d.jianyu.io uses an invalid security certificate. The certificate expired on July 16, 2018, 12:24 PM. The current time is July 16, 2018, 10:49 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE
~~~

**Comment by liudongmiao** [comment]
just update.

**Comment by IzzySoft** [comment]
Thanks!
