### ISSUE TITLE
在sony的安卓8.0上会隔一段时间黒域后台adb启动的服务被kill？？

### ISSUE THREAD

**Issue by pashifika** [brevent/Brevent#182]
rt
手机是sony XZp 系统8.0，原来7.1的时候USB启动一次就不用管了。现在几乎每天要联一次USB重启黒域的后台

**Comment by vvb2060** [comment]
#164

**Comment by MedievalSteel** [comment]
我很奇怪，为什么出现这个问题的基本都是 Sony？#164 中所有的 mentioned 都是 Sony。
