### ISSUE TITLE
黑域启动后，王者荣耀wifi变得很卡，关闭黑域后恢复正常

### ISSUE THREAD

**Issue by StephenGiant** [brevent/Brevent#185]
手机 是 索尼xzp，系统8.0

**Comment by liudongmiao** [comment]
如果你认为和黑域相关，并且你坚持没有黑域不该黑域的应用，那就不要使用黑域吧。

**Comment by StephenGiant** [comment]
我重复实验过了啊 黑域启动后，登陆都不行，重启手机黑域失效后就正常

**Comment by liudongmiao** [comment]
那就卸载黑域

**Comment by StephenGiant** [comment]
黑域这么良心的应用，而且我也有捐献，为什么要卸载？我只想找到原因啊

**Comment by liudongmiao** [comment]
黑域从来不会这样。也从未接到类似反馈。
而你坚持认为与黑域有关。所以，为了你的应用，建议直接卸载黑域。
