### ISSUE TITLE
Android O 无法启动黑域

### ISSUE THREAD

**Issue by Acker921** [brevent/Brevent#186]
checking for server.fail
[command] pm path me.piebridge.brevent
sh: pm: not found
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '12-06 22:39:44.000' -d
sh: logcat: not found
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '12-06 22:39:44.000' -d -s BreventLoader BreventServer
sh: logcat: not found
--- brevent end ---
```
刚开始用 root 成功了，后来尝试用 adb 后失败了
再次使用 root 后应用列表为空

**Comment by liudongmiao** [comment]
找你的 Rom 提供商，或者 Root 提供商。
黑域不解决没有基础指令问题。
