### ISSUE TITLE
checking for server..fail

### ISSUE THREAD

**Issue by Bobo22331** [brevent/Brevent#187]
--- crash start ---
[command] logcat -b crash -t '12-10 13:01:26.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '12-10 13:01:26.000' -d -s BreventLoader BreventServer
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
12-10 13:01:27.678  5207  5207 E BreventLoader: can't get path
12-10 13:01:27.678  5202  5202 E BreventLoader: worker 5207 exited with status 255
--- brevent end ---

**Comment by liudongmiao** [comment]
Contact your Rom provider.

And it seems you use an old version.
The latest version is 2.4.1.
