### ISSUE TITLE
夏普SHV33 安卓7.0 超时问题

### ISSUE THREAD

**Issue by JuneCN** [brevent/Brevent#188]
D:\adb>adb logcat -b main -d -s BreventLoader BreventServer
12-13 23:01:04.558 18538 18538 D BreventLoader: line: package:/data/app/me.piebridge.brevent-1/base.apk
12-13 23:01:04.584 18538 18538 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
12-13 23:01:04.585 18553 18553 D BreventLoader: start: 1513177263
12-13 23:01:05.698 18553 18553 I BreventServer: args: [10, me.piebridge.brevent, 1513177263]
12-13 23:01:05.813 18553 18553 I BreventServer: server log name: server.20171213.2301.18553.txt
12-13 23:01:05.815 18553 18553 I BreventServer: starting Brevent Server 2.4.1
12-13 23:01:05.887 18553 18553 I BreventServer: brevent user: 0, uid: 2000
12-13 23:01:05.891 18553 18553 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
12-13 23:01:05.933 18553 18553 I BreventServer: no service overlay
12-13 23:01:05.944 18553 18553 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 24
12-13 23:01:06.189 18553 18566 I BreventServer: system_server: 1829, now: 1513177266
12-13 23:01:06.997 18553 18553 I BreventServer: notification_cancel_all events: 8
12-13 23:01:07.004 18553 18553 I BreventServer: granted permission
12-13 23:01:07.036 18553 18553 I BreventServer: charging: true
12-13 23:01:07.037 18553 18553 I BreventServer: support standby: true
12-13 23:01:07.037 18553 18553 I BreventServer: support stopped: true
12-13 23:01:07.037 18553 18553 I BreventServer: support upgrade: true
12-13 23:01:07.038 18553 18553 I BreventServer: support appops: true
12-13 23:01:07.038 18553 18553 I BreventServer: Brevent Server 2.4.1 started
12-13 23:01:07.049 18553 18553 I BreventServer: received first event

**Comment by JuneCN** [comment]
~删除无关日志~

**Comment by liudongmiao** [comment]
到 23.01.07，黑域就成功开启。

如果你界面上见不到，说明你系统限制了黑域访问本地网络。
或者你在双开，多用户等非正常场景下使用。

**Comment by JuneCN** [comment]
未多开，非多用户，系统是否有限制未知，请问有什么方法能判断一下吗？ 卸载重装之后又能打开了

2017-12-14 9:43 GMT+08:00 Liu DongMiao <notifications@github.com>:

**Comment by liudongmiao** [comment]
我也不知道。黑域从来不保证与其它应用兼容性。
