### ISSUE TITLE
关于黑域界面描述问题

### ISSUE THREAD

**Issue by SoDebug** [brevent/Brevent#19]
位置:向导/ADB
原文:1. 解压 platform-tools-latest-<平台>.zip
这儿应该是想表达的意思是:1. 解压 platform-tools-latest.zip？

**Comment by vvb2060** [comment]
没有这个文件……
你没下载过吗？比如win版就是platform-tools-latest-windows.zip

**Comment by SoDebug** [comment]
platform-tools-latest-<平台>.zip
那你能把"<平台>"改成"<Windows平台>"吗，我感觉我有点强迫症，，，😭😭

**Comment by vvb2060** [comment]
你没打开过那个网页吗？
三大平台：
SDK Platform-Tools for Windows
SDK Platform-Tools for Mac
SDK Platform-Tools for Linux

**Comment by SoDebug** [comment]
可是就"<平台>"很怪，，，这样"<**平台>"怎么样

**Comment by liudongmiao** [comment]
`<平台>` 与 `<**平台>` 并无本质区别。
业内的话，也一般使用 `<xxx>` 代替某个东西。
