### ISSUE TITLE
Root模式启动失败，ADB也不行

### ISSUE THREAD

**Issue by Vstory** [brevent/Brevent#19]
1.
在外置SD卡目录（/storage/sdcard1/Android/data/me.piebridge.brevent/brevent.sh）运行brevent.sh ,成功启动黑域后的提示：
WARNING: run as root is experimental!!!
checking...WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xa7c
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0x1
brevent_server started, pid: 12790
checking for stable...........ok

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

成功启动黑域服务。

2.
运行在内置存储(/storage/emulated/legacy/Android/data/me.piebridge.brevent/brevent.sh)的brevent.sh ，提示：ERROR: cannot be run as non-shell.

3.
ADB启动不了，报错：
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools> .\adb -d shell sh /sdcard/Android/data/me.piebridge.b
revent/brevent.sh
ERROR: cannot be run as non-shell.
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools>

**Comment by Vstory** [comment]
ADB启动不了，报错：
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools> .\adb -d shell sh /sdcard/Android/data/me.piebridge.b
revent/brevent.sh
ERROR: cannot be run as non-shell.
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools>

**Comment by Vstory** [comment]
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools> .\adb devices
List of devices attached
1b321c057d52    device

PS D:\Software\ADB\platform-tools-latest-windows\platform-tools> .\adb -d shell sh /sdcard/Android/data/me.piebridge.bre
vent/brevent.sh
ERROR: cannot be run as non-shell.
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools> .\adb -d shell sh /sdcard/Android/data/me.piebridge.bre
vent/brevent.sh
ERROR: cannot be run as non-shell.
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools>

**Comment by Vstory** [comment]
在外置SD卡目录运行brevent.sh ,成功启动黑域后的提示：
WARNING: run as root is experimental!!!
checking...WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xa7c
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0x1
brevent_server started, pid: 12790
checking for stable...........ok

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by Vstory** [comment]
运行在内置存储(/storage/emulated/legacy/Android/data/me.piebridge.brevent/brevent.sh)的brevent.sh ，提示：ERROR: cannot be run as non-shell.

**Comment by Vstory** [comment]
内置存储prevent.sh
#!/system/bin/sh

path=/data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so
abi64=false

# path, abi64 should have been defined
if [ -z $path -o -z $abi64 ]; then
    echo "please specify path and abi64" >&2
    exit 1
fi

package=me.piebridge.brevent
brevent=/data/local/tmp/brevent

name=`id -un`
if [ x"$name" = x"root" ]; then
    :
elif [ x"$name" != x"shell" ]; then
    echo "ERROR: cannot be run as non-shell." >&2
    exit 1
fi

rm -rf $brevent
cp $path $brevent
if [ -f $brevent ]; then
    chmod 0755 $brevent
else
    echo "WARNING: /data/local/tmp is not writalbe" >&2
fi

if [ x"$abi64" == x"false" -a -x /system/bin/app_process64 ]; then
    rm -rf /data/local/tmp/app_process
    ln -s /system/bin/app_process32 /data/local/tmp/app_process
    export PATH=/data/local/tmp:$PATH
fi
if [ -x $brevent ]; then
    exec $brevent
elif [ -x $path ]; then
    exec $path
else
    echo "cannot execute brevent" >&2
    exit 1
fi

**Comment by Vstory** [comment]
外置存储brevent.sh
#!/system/bin/sh

path=/data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so
abi64=false

# path, abi64 should have been defined
if [ -z $path -o -z $abi64 ]; then
    echo "please specify path and abi64" >&2
    exit 1
fi

package=me.piebridge.brevent
brevent=/data/local/tmp/brevent
rm -rf $brevent
cp $path $brevent
if [ ! -f $brevent ]; then
    echo "/data/local/tmp is not writalbe" >&2
    exit 1
fi
chmod 0755 $brevent
if [ x"$abi64" == x"false" -a -x /system/bin/app_process64 ]; then
    rm -rf /data/local/tmp/app_process
    ln -s /system/bin/app_process32 /data/local/tmp/app_process
    export PATH=/data/local/tmp:$PATH
fi
if [ -x $brevent ]; then
    exec $brevent
elif [ -x $path ]; then
    exec $path
else
    echo "cannot execute brevent" >&2
    exit 1
fi

**Comment by liudongmiao** [comment]
你机器很古怪。约个事件，电脑上安装 teamviewer，邮件我 id 和 密码，我登陆上去看看。

**Comment by liudongmiao** [comment]
刚发布 1.1.11+10，请再看看。

我本地在 5.0 / 6.0 模拟器 (ROOT)，7.1 真机 + ROOT 测试通过。

**Comment by chinen95** [comment]
7.1.1下root模式用不了+1 只能adb实在太麻烦了

**Comment by Vstory** [comment]
@liudongmiao 1.1.11 +10 可以了Root模式正常自启。
adb 模式启动后，也正常。
adb 运行的提示如下：
`PS D:\Software\ADB\platform-tools-latest-windows\platform-tools> .\adb -d shell sh /sdcard/Android/data/me.piebridge.bre
vent/brevent.sh
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xaa0
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0x1
checking....brevent_server started, pid: 10841
checking for stable...........ok

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
PS D:\Software\ADB\platform-tools-latest-windows\platform-tools>`

**Comment by Vstory** [comment]
@chinen95 我是安卓5.1.1

**Comment by liudongmiao** [comment]
@Vstory 正常了就不用看了～

@chinen95 你的问题，单开 issue 吧。
对于 root 相关的，目前我只接受远程调试。
