### ISSUE TITLE
请问 爱心 闹钟 圆圈 等图标分别代表什么？

### ISSUE THREAD

**Issue by qwIvan** [brevent/Brevent#192]
网上没有查到相关资料介绍

**Comment by vvb2060** [comment]
心型是喜欢，不建议黑域，一般系统默认或某种规则。
闹钟代表即将黑域，带时间的后台超时后处理，不带时间的下次处理，不会处理被其他应用依赖的应用。
圆圈代表没有服务，目前是安全的，建议可以适当取消黑域。
圆圈加杠表明正常黑域。
此外，还有睡觉的，待机中。

这些图标左边带有云朵，支持 FCM 且允许同步。
双箭头，表示允许同步。

以上所有，都代表应用在黑域列表里。

**Comment by qwIvan** [comment]
@vvb2060 关于心形还是不太懂，基于什么规则认为不建议黑域？

**Comment by vvb2060** [comment]
电话、短信、gms、电池优化豁免应用。显示心形后，会出现括号提示原因。

**Comment by imknown** [comment]
看 `drawable` 文件名, 猜用途:
https://github.com/brevent/Brevent/tree/master/brevent/src/main/res/drawable

---

https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/BreventActivity.java#L824-L851

https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/AppsItemAdapter.java#L140-L167

https://github.com/brevent/Brevent/blob/91d0dead3cbc527c0e1023640092c716254e9609/brevent/src/main/java/me/piebridge/brevent/ui/OpsItemAdapter.java#L224-L226
