### ISSUE TITLE
是否愿意提供一个入口来手动黑域app？

### ISSUE THREAD

**Issue by qwIvan** [brevent/Brevent#193]
打算自己写shell脚本或者用tasker来实现控制。
我是指手动standby和force stop，而不是定时处理。

**Comment by vvb2060** [comment]
如果你指的是添加应用进入黑域清单，可以通过写`/data/user_de/0/com.android.shell/me.piebridge.brevent.list`实现。包名后有`=true`表示允许同步。
Android7以下路径为`/data/data/com.android.shell/me.piebridge.brevent.list`

**Comment by liudongmiao** [comment]
黑域全自动。我不明白，你有什么样的需要，需要手动这样处理？

**Comment by qwIvan** [comment]
我觉得，你无法设定一套规则，然后对所以需求都适用。因此认为应该开放操作入口，允许用户自己调用。
例如我想周期性地（每小时一次地）打开一个app，接收通知，一分钟后把它黑域掉。

**Comment by vvb2060** [comment]
鉴于你有高度个性化的需求，黑域可能无法满足，建议：
待机一个应用：`am set-inactive <packageName> true`
强行停止一个应用：`am force-stop <packageName>`
配合shell或tasker使用即可

**Comment by liudongmiao** [comment]
就你的规则来说，你只需要周期性打开就好。
剩下的，黑域会自行处理。比如有通知就保留，没通知就黑域掉之类。

**Comment by liudongmiao** [comment]
如果你要做类似的事，可以寻求  tasker 。
但是他无法绕过权限，也就仅此而已。
当然，黑域 api 权限非常之高，目前没有任何打算开许这些 api。

**Comment by qwIvan** [comment]
@vvb2060 单纯使用 am force-stop 能够有效阻止应用被唤醒吗？
@liudongmiao 黑域的规则过于简单，无法针对不同应用设置不同的待机时间或停止时间

**Comment by vvb2060** [comment]
@qwIvan 应用被强行停止后处于停止状态，无法被系统广播唤醒，也无法收到 FCM 消息。黑域的允许同步会取消停止状态。
