### ISSUE TITLE
编译出现问题

### ISSUE THREAD

**Issue by Zxilly** [brevent/Brevent#196]
编译时brevent.c中有问题，提示Error:error: use of undeclared identifier 'EPERM'，是否误删除了#define EPERM

**Comment by Zxilly** [comment]
谢谢

**Comment by liudongmiao** [comment]
你确定使用了最新代码？

**Comment by liudongmiao** [comment]
https://github.com/brevent/Brevent/commit/8a39b764598e288167624ac4f145131d1a528354

**Comment by Zxilly** [comment]
编译之前已经git fetch
原始代码使用git clone 获取

**Comment by vvb2060** [comment]
使用`git pull`来抓取然后合并远程分支到当前分支。
再去看看git文档吧……
