### ISSUE TITLE
手机不能通过电脑连接，求助

### ISSUE THREAD

**Issue by walklinewang** [brevent/Brevent#197]
adb devices好不到设备，尝试了用temux调用sh脚本，结果是没权限，当然手机肯定没root，同一个脚本为什么在其他手机上可以调用，而我这里提示创建tmp文件夹没有权限呢？不是说不用root的吗？

**Comment by liudongmiao** [comment]
黑域不处理无法连接电脑问题，请自行解决。

你也可以使用无电脑方案：https://www.jianshu.com/p/9fee93554974
