### ISSUE TITLE
黑屏，看不到应用，

### ISSUE THREAD

**Issue by Rain33** [brevent/Brevent#198]
打开黑域，看不到应用列表，卸载后再安装也没得用。求解

**Comment by liudongmiao** [comment]
#190 查看具体原因。

最新 beta 版解决了这个问题。

**Comment by Rain33** [comment]
没看到beta版呀，我昨天更新后就出现这个问题了，之前一直好好的。（从谷歌商店下载的）

2017年12月24日 17:35，"Liu DongMiao" <notifications@github.com>写道：

**Comment by liudongmiao** [comment]
play 商店自己加入 beta 版渠道。
非 play：https://piebridge.me/br/beta/

而且，即使黑域解决了这个问题，其他类似应用怎么办？
