### ISSUE TITLE
三星S7 安卓7.0版本安装失败

### ISSUE THREAD

**Issue by alvin634** [brevent/Brevent#2]
黑域安装的是google play的版本
ADB也是从官方推荐的页面下载：
https://developer.android.google.cn/studio/releases/platform-tools.html 

按照google play简介页面的方法安装输入下面的命令不成功：
adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh

也试过之前的命令：
adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
这条命令的执行结果是no such directory or file

google找不到解决方法，才不得以在这里麻烦作者。

电脑端的截图如下：
(截图的时候重新操作一次，由于有点仓促，最后的h没有复制进去，但是出错的信息是一样的)
<img width="960" alt="default" src="https://user-images.githubusercontent.com/30725647/28969420-1f915a68-7957-11e7-9b6f-af797592689f.png">

手机已经开启USB调试，USB连接为MTP模式，安卓版本为7.0，手机为三星S7国行未root。

**Comment by vvb2060** [comment]
把向导认真看完，然后按照弹窗提示输入命令。别那么急……

**Comment by alvin634** [comment]
多谢大神的神速回复。按照手机上的命令逐字输入后发现一次成功。原来命令有变，懒得输入，看了开头和结尾的几个字符一样就复制，反而浪费时间。解决了，谢谢！！

Best regards,
Alvin Chen
 
发件人： vvb2060
发送时间： 2017-08-04 21:24
收件人： brevent/Brevent
抄送： alvin634; Author
主题： Re: [brevent/Brevent] 三星S7 安卓7.0版本安装失败 (#2)
把向导认真看完，然后按照弹窗提示输入命令。别那么急……
―

**Comment by vvb2060** [comment]
emmmm，那啥，是得把向导看完。命令是对的………

**Comment by puXiaoyi** [comment]
我也是从google play上下载的最新版本，执行`adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh`，提示`no such directory or file`； 执行`adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh`，提示`Permission denied`，楼主怎么解决的啊？
