### ISSUE TITLE
海贝音乐播放音乐时按返回键退出后被杀掉

### ISSUE THREAD

**Issue by RolandVyens** [brevent/Brevent#20]
开着识别非正常返回，内存绝对够用，系统是lineage OS14.1@Android7.1.2，英伟达sheild内核

**Comment by vvb2060** [comment]
没有允许同步的话，返回的确是退出的意思啊，黑域会帮你杀掉它。正确的方法应该是按主页/总览把它放到后台。
当然，也可以对它允许同步。设置后有通知/前台服务就不杀。

**Comment by liudongmiao** [comment]
@leiersai 下一个版本，你可以开启“优化音乐类应用”。
