### ISSUE TITLE
gradle编译问题

### ISSUE THREAD

**Issue by Zxilly** [brevent/Brevent#200]
`17:05:44.599 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Failed to capture snapshot of output files for task ':brevent:copyReleaseApk' property 'destinationDir' during up-to-date check.
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to create MD5 hash for file content.
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:05:44.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
17:05:44.609 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
17:05:44.610 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 45s
17:05:44.610 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 192 actionable tasks: 8 executed, 184 up-to-date`
支付宝捐赠后始终无法验证，想编译社区版自用

**Comment by Zxilly** [comment]
`Running dex as a separate process.

To run dex in process, the Gradle daemon needs a larger heap.
It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html

:brevent:transformClassesWithShrinkResForRelease
Removed unused resources: Binary resource data reduced from 380KB to 369KB: Removed 3%
:appcompat-dummy:compileReleaseNdk NO-SOURCE
:appcompat-dummy:mergeReleaseJniLibFolders
:appcompat-dummy:transformNativeLibsWithMergeJniLibsForRelease
:appcompat-dummy:transformNativeLibsWithStripDebugSymbolForRelease
:appcompat-dummy:transformNativeLibsWithIntermediateJniLibsForRelease
:brevent:mergeReleaseJniLibFolders
:brevent-protocol:compileReleaseNdk NO-SOURCE
:brevent-protocol:mergeReleaseJniLibFolders
:brevent-protocol:transformNativeLibsWithMergeJniLibsForRelease
:brevent-protocol:transformNativeLibsWithStripDebugSymbolForRelease
:brevent-protocol:transformNativeLibsWithIntermediateJniLibsForRelease
:brevent-ui:compileReleaseNdk NO-SOURCE
:brevent-ui:mergeReleaseJniLibFolders
:brevent-ui:transformNativeLibsWithMergeJniLibsForRelease
:brevent-ui:transformNativeLibsWithStripDebugSymbolForRelease
:brevent-ui:transformNativeLibsWithIntermediateJniLibsForRelease
:donation-dummy:compileReleaseNdk NO-SOURCE
:donation-dummy:mergeReleaseJniLibFolders
:donation-dummy:transformNativeLibsWithMergeJniLibsForRelease
:donation-dummy:transformNativeLibsWithStripDebugSymbolForRelease
:donation-dummy:transformNativeLibsWithIntermediateJniLibsForRelease
:log-reader:generateJsonModelRelease
:log-reader:externalNativeBuildRelease
Build reader x86
[x86] SharedLibrary  : liblog.so
[x86] SharedLibrary  : libreader.so
Build log x86
make: `C:/msys64/home/Welcome/Brevent-new/Brevent/log-reader/build/intermediates/ndkBuild/release/obj/local/x86/liblog.so' is up to date.
Build log arm64-v8a
[arm64-v8a] SharedLibrary  : liblog.so
Build reader arm64-v8a
[arm64-v8a] SharedLibrary  : libreader.so
Build log x86_64
[x86_64] SharedLibrary  : liblog.so
Build reader x86_64
[x86_64] SharedLibrary  : libreader.so
Build log armeabi
[armeabi] SharedLibrary  : liblog.so
Build reader armeabi
[armeabi] SharedLibrary  : libreader.so
:log-reader:deleteLogStub
:log-reader:mergeReleaseJniLibFolders
:log-reader:transformNativeLibsWithMergeJniLibsForRelease
:log-reader:transformNativeLibsWithStripDebugSymbolForRelease
:log-reader:transformNativeLibsWithIntermediateJniLibsForRelease
:stats-dummy:compileReleaseNdk NO-SOURCE
:stats-dummy:mergeReleaseJniLibFolders
:stats-dummy:transformNativeLibsWithMergeJniLibsForRelease
:stats-dummy:transformNativeLibsWithStripDebugSymbolForRelease
:stats-dummy:transformNativeLibsWithIntermediateJniLibsForRelease
:brevent:transformNativeLibsWithMergeJniLibsForRelease
:brevent:transformNativeLibsWithStripDebugSymbolForRelease
:brevent:packageRelease
:brevent:assembleRelease
:brevent:copyReleaseApk FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of output files for task ':brevent:copyReleaseApk' property 'destinationDir' during up-to-date check.
> Failed to create MD5 hash for file content.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 32s
192 actionable tasks: 185 executed, 7 up-to-date
`

**Comment by liudongmiao** [comment]
自查 gradle 版本吧。Android Studio 3 需要 4.1，我没有测试其它版本，理论上 4.1+ 都可以。

**Comment by Zxilly** [comment]
emmm..
您使用了gradle-wrapper，gradle的版本应该是由您的的配置文件决定的

**Comment by liudongmiao** [comment]
再认真看看，我可没提供 gradle wrapper ...
黑域源码里，没有指定任何 gradle 版本
所以，这个由你本地的 gradle 指定

**Comment by Zxilly** [comment]
emmm...非常感谢

**Comment by Zxilly** [comment]
也许是Android Studio自动指定的

**Comment by Zxilly** [comment]
指定gradle 4.4后报错，也许应该使用gradle 4.1?

    Error:警告:

     [options] 未与 -source 1.7 一起设置引导类路径
    1 个警告
    警告: [options] 未与 -source 1.7 一起设置引导类路径
    1 个警告
    警告: [options] 未与 -source 1.7 一起设置引导类路径
    1 个警告
    警告: [options] 未与 -source 1.7 一起设置引导类路径
    1 个警告
    注: C:\Users\Welcome\Desktop\Brevent-2.4.4a\brevent-ui\src\main\java\me\piebridge\brevent\ui\LocaleUtils.java使用或覆盖了已过时的 API。
    注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
    注: C:\Users\Welcome\Desktop\Brevent-2.4.4a\brevent\src\main\java\me\piebridge\brevent\ui\BreventApplication.java使用或覆盖了已过时的 API。
    注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
    注: 某些输入文件使用了未经检查或不安全的操作。
    注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
    Note: there were 11 duplicate class definitions.
          (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
    FAILURE: Build failed with an exception.

    * What went wrong:
    Failed to capture snapshot of output files for task ':brevent:copyReleaseApk' property 'destinationDir'     during up-to-date check.
    > Failed to create MD5 hash for file content.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 14m 6s
