### ISSUE TITLE
adb报错误

### ISSUE THREAD

**Issue by Franticbaby** [brevent/Brevent#201]
C:\platform-tools>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server..fail
[command] pm path me.piebridge.brevent
sh: pm: not found
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '12-30 16:13:19.000' -d
sh: logcat: not found
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '12-30 16:13:19.000' -d -s BreventLoader BreventServer
sh: logcat: not found
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
建议带上日志，联系你的 Rom 提供商。

**Comment by Zxilly** [comment]
没有busybox，缺少pm命令，尝试刷入busybox
