### ISSUE TITLE
Look forward to developing a function likes appops

### ISSUE THREAD

**Issue by ZyuHung** [brevent/Brevent#203]
The function that the permissions are under control, but I hope that the permissions can be changed via a specific template.

**Comment by ZyuHung** [comment]
The function that the permissions are under control exists, but I hope that the permissions can be changed via a specific template automatically.

**Comment by liudongmiao** [comment]
appops in Brevent is very experimental, and I'm waiting for data like actual usage.

You can look forward to appops directly.

**Comment by liudongmiao** [comment]
add template in 2.9.8, you can join play beta, or download here: https://piebridge.me/br/beta/

please note, appops in brevent requires 3 brefoil.
however, if you pay 3 brefoil, you can use disable too.
