### ISSUE TITLE
Nrevent Design Bug

### ISSUE THREAD

**Issue by Zxilly** [brevent/Brevent#204]
Nrevent使用的是Brevent的brevent-server，但编译时所产生的版本号和原版release的不一致，adb操作时提示Version Not Match

    WARNING: linker: /data/local/tmp/brevent: unsupported flags DT_FLAGS_1=0x8000001
    found old brevent_server, pid: 5476, killing
    checking for server...fail
    [command] pm path me.piebridge.nrevent
    package:/data/app/me.piebridge.nrevent-1/base.apk
    --- crash start ---
    [command] logcat -b crash -t '01-02 18:41:38.000' -d
    --- crash end ---
    --- brevent start ---
    [command] logcat -b main -t '01-02 18:41:38.000' -d -s BreventLoader BreventServer
    01-02 18:41:39.005  5460  5460 E BreventLoader: worker 5476 exited on signal 15
    01-02 18:41:39.005  5460  5460 D BreventLoader: signal arrived, update: 0
    01-02 18:41:39.779  9818  9818 D BreventLoader: line: package:/data/app/me.piebridge.nrevent-1/base.apk
    01-02 18:41:39.806  9818  9818 D BreventLoader: loader path: /data/app/me.piebridge.nrevent-1/base.apk
    01-02 18:41:39.807  9829  9829 D BreventLoader: start: 1514889698
    01-02 18:41:40.618  9829  9829 I BreventServer: args: [10, me.piebridge.nrevent, 1514889698]
    01-02 18:41:40.626  9829  9829 W BreventServer: Can't find logger
    01-02 18:41:40.626  9829  9829 W BreventServer: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
    01-02 18:41:40.626  9829  9829 W BreventServer:         at me.piebridge.brevent.server.i.g(ServerLog.java:122)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at me.piebridge.brevent.server.i.d(ServerLog.java:102)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:32)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:139)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:264)
    01-02 18:41:40.626  9829  9829 W BreventServer: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.slf4j.LoggerFactory" on path: DexPathList[[zip file "/data/app/me.piebridge.nrevent-1/base.apk"],nativeLibraryDirectories=[/data/app/me.piebridge.nrevent-1/lib/arm64, /system/lib64, /vendor/lib64]]
    01-02 18:41:40.626  9829  9829 W BreventServer:         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    01-02 18:41:40.626  9829  9829 W BreventServer:         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    01-02 18:41:40.626  9829  9829 W BreventServer:         ... 7 more
    01-02 18:41:40.626  9829  9829 I BreventServer: starting Brevent Server 2.4.4a
    01-02 18:41:40.668  9829  9829 E BreventServer: version unmatched
    01-02 18:41:40.688  9818  9818 E BreventLoader: worker 9829 exited with status 1
    01-02 18:41:40.688  9818  9818 D BreventLoader: signal arrived, update: 0
    01-02 18:41:40.690  9813  9813 D BreventLoader: worker 9818 exited with status 0
    --- brevent end ---

**Comment by liudongmiao** [comment]
请自觉保证打包的版本与实际版本一致。
