### ISSUE TITLE
4个问题

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#205]
1. 被停用的应用刷新时没有消失。关了再打开才消失。
2. 阿里YunOS推广告，黑域把推广告的应用隐藏了，找不到。
3. 可信代理的判断有问题，明明看设置是灰的都不能点进去，也没有锁屏密码。黑域却认为Google服务是可信代理。
4. 对无障碍，输入法的判断太晚。看见被杀之后才想起去黑域取消掉。还有，开了通知使用权跟开了无障碍差不多，为什么只有无障碍不许黑域?

**Comment by liudongmiao** [comment]
1. 刷新主要是状态，而不是列表。

2. 自己去设置里开启显示所有应用。默认不显示无法打开的应用。
如果显示所有也没有，那说明这些应用用户 id 在 10000 以下，属于特殊用户。
黑域永远不会显示用户 id 在 10000 以下的用户，如设置 (2000)，通讯类应用等。

3. 使用系统  API...

4. 判断太晚...你配置了以后，立即进入黑域看看？
通知权限，暂无计划，你可以直接  PR。

**Comment by ksvmra17238** [comment]
1.但是，卸载应用却能马上消失。不然我也不会提
2.id在10000以下。YunOS专门把id设置到10000以下推送广告，作用只有推送广告，其中一个包名直接是com.yunos.ad。我只是想定时停止清除广告，都不想唤醒马上停止之类。居然不行…………
3.这时系统会不会唤醒可信代理？如果不会有没有类似api检查状态？比如可信代理未打开或没有锁屏
4.新安装应用后黑域会提示黑域了xxx，能不能改成通知？有按钮取消黑域它。不想打开无障碍后还要打开黑域让它“**自动**”被取消黑域。PR是什么？

**Comment by zxy1001** [comment]
1.刷新按钮的作用是重新检测当前列表的运行状态，而不是重新加载应用列表，每次进入的时候的读条才是重新加载应用列表。
2.你可以使用冰箱，把广告服务冻结。
3.Google似乎是默认启用可信代理，无法打开，是因为你的系统有问题。云os阉割了很多东西。
4.如果你想要一个作者还没有计划开发的新功能，你可以自己写代码去实现这个功能，然后向作者请求pull,即pull request,由作者考虑是否合并。

2018年1月4日 12:36，"ksvmra17238" <notifications@github.com>写道：

1.但是，卸载应用却能马上消失。不然我也不会提
2.id在10000以下。YunOS专门把id设置到10000以下推送广告，作用只有推送广告，其中一个包名直接是com.yunos.ad
。我只是想定时停止清除广告，都不想唤醒马上停止之类。居然不行…………
3.这时系统会不会唤醒可信代理？如果不会有没有类似api检查状态？比如可信代理未打开或没有锁屏
4.新安装应用后黑域会提示黑域了xxx，能不能改成通知？有按钮取消黑域它。不想打开无障碍后还要打开黑域让它“*自动*”被取消黑域。PR是什么？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brevent/Brevent/issues/205#issuecomment-355197179>, or mute
the thread

**Comment by ksvmra17238** [comment]
```
$ ls -l  /data/data/com.android.shell/ |grep list
-rw------- shell    shell        3094 2017-11-09 20:31 me.piebridge.brevent.list
echo com.yunos.ad>>/data/data/com.android.shell/me.piebridge.brevent.list 
/system/bin/sh: can't create /data/data/com.android.shell/me.piebridge.brevent.list: Operation not permitted
```
想直接加入黑域清单，为什么没有权限？这个目录下还有非常大量的奇怪文件，截取一部分展示，这是什么？
```
/data/data/com.android.shell $ ls
dumpsys-1000027297notification
dumpsys-1014639802notification
dumpsys-1017551801notification
dumpsys-1019815243notification
dumpsys-1033863821notification
dumpsys-1033889836notification
dumpsys-1045824231notification
dumpsys-1046425609notification
dumpsys-1055281571notification
dumpsys-1057954246notification
dumpsys-1063464462notification
dumpsys-106552509notification
dumpsys-1069354443notification
dumpsys-1071262320notification
dumpsys-1083642141notification
```

**Comment by zxy1001** [comment]
您大概需要了解一下黑域的运行原理。。。

2018年1月4日 12:55，"ksvmra17238" <notifications@github.com>写道：

**Comment by ksvmra17238** [comment]
@zxy1001  YunOS的系统，shell没有MANAGE_USERS权限。也没有Google套件。

**Comment by zxy1001** [comment]
他提到黑域把Google认作可信代理，应该是自己刷了谷歌套件，毕竟YunOS说白了就是死不承认的套壳安卓

2018年1月4日 13:20，"ksvmra17238" <notifications@github.com>写道：

**Comment by ksvmra17238** [comment]
@zxy1001 我有三个手机，其中一个刷了Lineage OS和OpenGapps。设置DPM需要shell有MANAGE_USERS权限，谢谢。

**Comment by zxy1001** [comment]
我没说你错啊大哥

2018年1月4日 13:30，"ksvmra17238" <notifications@github.com>写道：

**Comment by liudongmiao** [comment]
@ksvmra17238 

1. 卸载与停用其实还是不同的，停用与启用不是一个常见的操作，不会处理。

2. 你应该使用了一个古老的版本。早期会有 dumpXXX 文件，现在已经没有了。

**Comment by liudongmiao** [comment]
@ksvmra17238 如果你使用的是最新的版本（不要问我是哪个版本号），那就是你找错了位置。

**Comment by ksvmra17238** [comment]
嗯，看文件时间很早，没有清理所以留下来了。不过为什么不能写入list？我设置为777都无法写入
```
$ ls -l /data/data/com.android.shell/|grep list
-rw------- shell    shell        3117 2018-01-04 13:13 me.piebridge.brevent.list
$ chmod 777 /data/data/com.android.shell/me.piebridge.brevent.list  
$ ls -l /data/data/com.android.shell/|grep list
-rwxrwxrwx shell    shell        3117 2018-01-04 13:13 me.piebridge.brevent.list
$ echo com.yunos.ad>>/data/data/com.android.shell/me.piebridge.brevent.list 
/system/bin/sh: can't create /data/data/com.android.shell/me.piebridge.brevent.list: Operation not permitted
```

**Comment by liudongmiao** [comment]
不知道。

另外，即使你把包名写进去了，黑域也不会认的，硬限制就是不处理 10000 以下的应用。
本意是不能让用户作死，黑域一些通讯类应用。至于你机器特例，我建议直接停用。

**Comment by ksvmra17238** [comment]
要是能停用早就停用了。试过任何方法都不行，就盼着黑域结果黑域不处理。仅UI判断不行？
另外，刚刚取消黑域一个应用，list文件时间马上刷新，证明能写入，只是adb shell不能。

**Comment by liudongmiao** [comment]
@ksvmra17238 对于你的第一个问题，可以回答你一下。

黑域根据列表数据判断是否要更新，然后再过滤停用应用。
当卸载或安装应用时，列表数据即时更新。
当停用或启用应用时，列表数据还在，不会触发更新操作，所以只有下次进入时才会更新。
停用或启用应用以后，再安装或者卸载一个应用，你再看看是不是刷新了。

不过在 568f77c7cbba3915a0761e53b22b2cd5e46a9d5a 之后，列表数据是从黑域服务获取，倒是可以优化下。

**Comment by liudongmiao** [comment]
就目前来说，黑域底线是不触碰 uid 在 10000 以下应用。
虽然有些通讯类的应用，我也想要干掉，如每次开机以后，运营商通讯的通知...

**Comment by liudongmiao** [comment]
至于 无障碍 与 输入法 的判断，由于某种原因故意放在黑域端，而不是黑域服务端。

黑域服务端除了极其危险的类型外，不应该过多干扰黑域清单。
输入法方面，如果放到黑域服务，运行 65535 次以后，还会导致系统直接重启。

唯一的例外，是闹钟。如果你设置了闹钟，不需要进入黑域，会立即取消黑域。
因为我可不想之前黑域了闹钟应用，忘了取消黑域；然后设定一个闹钟，再也不响...

**Comment by liudongmiao** [comment]
@ksvmra17238 我目前没有任何计划展示小于 10000 的应用。
你可以付费发起开发。

**Comment by liudongmiao** [comment]
@ksvmra17238 你那个阿里云广告应用，uid 是多少？

**Comment by ksvmra17238** [comment]
三个推广告的应用：`com.yunos.ad`、`com.yunos.baseservice.cmns_client`、`com.yunos.lifecard`。
https://user-images.githubusercontent.com/35072438/34553071-769c5b6a-f160-11e7-8afa-4604b1d6148f.png

`com.yunos.ad`和`com.yunos.lifecard`能被黑域，黑域后广告没了。只剩`com.yunos.baseservice.cmns_client`
https://user-images.githubusercontent.com/35072438/34553085-8945b91e-f160-11e7-9454-f48275389386.jpg
刚刚看了uid，emmmmm
```
  Package [com.yunos.baseservice.cmns_client] (c0ef1ee):
    userId=1000
    sharedUser=SharedUserSetting{f497989 android.uid.system/1000}
    pkg=Package{1239d14 com.yunos.baseservice.cmns_client}
```

**Comment by liudongmiao** [comment]
1000 的肯定不会展示，极其危险。
1000 包括系统设置，系统内容提供器...

**Comment by liudongmiao** [comment]
第一个问题最新 beta 已经支持。
其它的要么不是问题，要么不会支持。
