### ISSUE TITLE
请问如何修改应用清理后台后服务的行为

### ISSUE THREAD

**Issue by HaotingLiu** [brevent/Brevent#209]
大神您好，
根据我的使用理解，目前的黑域版本，如果将后台的tag给划掉（就是传统的清理后台方式）无论如何选择黑域方式，应用的所有服务都会立刻被关闭，即使设置的黑域选项是仅待机应用，不彻底关闭。
现在我想将相关的功能实现改成：如果黑域选项是只待机，不关闭应用时，清理后台应用的情况下会将应用的服务进行待机而不是直接关闭。麻烦大神能不能指导下相关代码大致在哪个位置。

跪谢。

**Comment by liudongmiao** [comment]
黑域不会提供这样功能。

如果你真能明白从后台划掉这种行为，就该理解。
当你划掉以后，Android 会回收所有资源，服务就重新启动进程（唯一例外是前台服务），绝大部分国产 Rom 也会直接不允许启动。

所以，你的要求黑域不可能实现。

此外，你可能不理解待机含义，黑域向导中提及，只是不能访问网络及任务而已。

如果划掉时，没有服务，什么也不会发生，进程全没。如果有服务，且为 aosp，即使待机，也没什么意义，会继续耗费你资源。

此问题不再回复。

**Comment by HaotingLiu** [comment]
感谢您的回复，
我想说明下情况以给您提供参考，也希望您能理解为什么我会提出这个需求。

首先我说明下我的手机配置。我的手机是oos 5.0的一加5，身在国外，所以国内app使用很少，谷歌服务使用很多。

在我反复实验后发现，在oos 5.0中（也包括过去版本的oos），如果在黑域策略中选择只待机，不退出应用。那么会出现以下情况：
应用如果没有选择被黑域，则被划掉后大部分会留下一个服务进程或者一个安全的缓存进程；如果被黑域则不会。针对同一应用的测试也是这个结果。而如果一个应用留下进程则会保证所有的notification均可用。没有的话则notification均无效。
如果应用被standby，因为fcm的作用，所有notification同样均有效。
所以这就造成了一个问题：

如果我选择一个应用被黑域，那么划掉之后所有notification均无效，但不划掉情况下所有notification均有效。
如果我选择一个应用不被黑域，无论是否划掉，notification均有效。

此外我将standby时间设为1分钟，所以对于省电来说有一定效果。

以上就是为什么我会产生类似需求。

目前我觉得问题的关键在于：

1. 针对不同系统可能黑域的表现并不相同。
2. 在oos下，为什么会出现被黑域应用在关闭后不会再次启动后台服务，而不被黑域的应用关闭后却会启动。
3. 后台服务standby与不standby在能耗上是否有区别（目前针对这一条我的测试是有一些区别）

早上也读了一下源码，但因为我的专长并不是移动开发（安卓4.4以来第一次读应用源码）还有点懵逼，我再继续研究下，如果有什么发现会实时回复在这。

谢谢大神

ps：顺便说下我现在针对这种情况的暂时应对措施：
我现在让尽可能多的需要notification的应用处于后台，然后对他们全部实行黑域，实行一分钟后standby但永不关闭策略，并且对他们加锁（oos特性）确保他们不被划掉。因为一加的内存很大所以这个策略才可行，所以也并不奢望官方版提供这个功能，就是想自己做做。。。。。

**Comment by liudongmiao** [comment]
你要通知，阅读描述，向导，都有提到允许同步。

**Comment by liudongmiao** [comment]
我建议你认真阅读黑域商店描述，向导，中文图文 PDF （ https://piebridge.me/br/ 内找 pdf 链接 ），绝大部分都有答案，而不是自己随便想。
