### ISSUE TITLE
立即黑域强行停止后台应用

### ISSUE THREAD

**Issue by chinen95** [brevent/Brevent#21]
终于又发生了 操作是这样的 过程中没有按过一次返回键 从QQ按方框切换到微信 再用方框切回QQ QQ已经被强制关闭 连续发生了两次 看了下内存占用 1.1G可用(减去缓存进程 700M可用) 不存在低内存被系统杀的可能性

05-29 11:44:38.769 20337 20337 D BreventServer: check and brevent
05-29 11:44:39.036 20337 20337 D BreventServer: check again in 3600s
05-29 11:44:39.036 20337 20337 D BreventServer: check and brevent, took 264ms
05-29 11:46:48.708 20337 20337 D BreventServer: check and brevent
05-29 11:46:48.970 20337 20337 D BreventServer: check again in 3600s
05-29 11:46:48.970 20337 20337 D BreventServer: check and brevent, took 260ms
05-29 11:47:05.476 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:47:06.192 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:47:09.316 20337 20337 D BreventServer: check and brevent
05-29 11:47:09.599 20337 20337 D BreventServer: check again in 3600s
05-29 11:47:09.599 20337 20337 D BreventServer: check and brevent, took 283ms
05-29 11:48:03.339 20337 20337 D BreventServer: check and brevent
05-29 11:48:03.592 20337 20337 D BreventServer: check again in 3600s
05-29 11:48:03.592 20337 20337 D BreventServer: check and brevent, took 253ms
05-29 11:48:22.270 20337 20337 D BreventServer: check and brevent
05-29 11:48:22.516 20337 20337 D BreventServer: check again in 3600s
05-29 11:48:22.516 20337 20337 D BreventServer: check and brevent, took 245ms
05-29 11:49:06.154 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:06.422 20337 20337 D BreventServer: Force stop com.tencent.mobileqq(brevent request)
05-29 11:49:06.674 20337 20337 D BreventServer: update current to com.android.chrome
05-29 11:49:07.383 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:08.685 20337 20337 D BreventServer: update current to com.tencent.mm
05-29 11:49:11.003 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:11.529 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:49:14.420 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:49:19.080 20337 20337 D BreventServer: update current to rikka.notificationforqq
05-29 11:49:19.268 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:49:21.263 20337 20337 D BreventServer: check and brevent
05-29 11:49:21.613 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:21.613 20337 20337 D BreventServer: check and brevent, took 350ms
05-29 11:49:31.495 20337 20337 D BreventServer: check and brevent
05-29 11:49:31.737 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:31.737 20337 20337 D BreventServer: check and brevent, took 242ms
05-29 11:49:40.539 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:40.837 20337 20337 D BreventServer: Force stop com.tencent.mobileqq(brevent request)
05-29 11:49:41.042 20337 20337 D BreventServer: update current to com.tencent.mm
05-29 11:49:42.003 20337 20337 D BreventServer: check and brevent
05-29 11:49:42.289 20337 20337 D BreventServer: Force stop com.tencent.mobileqq(previous running)
05-29 11:49:42.290 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:42.290 20337 20337 D BreventServer: check and brevent, took 286ms
05-29 11:49:42.290 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:42.802 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:49:46.037 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:49:47.885 20337 20337 D BreventServer: update current to com.android.settings
05-29 11:49:56.413 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:56.595 20337 20337 D BreventServer: check and brevent
05-29 11:49:56.883 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:56.883 20337 20337 D BreventServer: check and brevent, took 287ms
05-29 11:49:57.571 20337 20337 D BreventServer: update current to com.android.settings
05-29 11:50:01.503 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:50:02.619 20337 20337 D BreventServer: update current to rikka.notificationforqq
05-29 11:50:02.623 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:50:04.504 20337 20337 D BreventServer: check and brevent
05-29 11:50:04.746 20337 20337 D BreventServer: check again in 3600s
05-29 11:50:04.746 20337 20337 D BreventServer: check and brevent, took 240ms
05-29 11:50:30.702 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:50:33.705 20337 20337 D BreventServer: check and brevent
05-29 11:50:33.988 20337 20337 D BreventServer: check again in 3600s
05-29 11:50:33.988 20337 20337 D BreventServer: check and brevent, took 281ms
05-29 11:50:37.046 20337 20337 D BreventServer: update current to com.termux
05-29 11:50:41.437 20337 20337 D BreventServer: Force stop eu.chainfire.supersu(brevent request)
05-29 11:50:53.693 20337 20337 D BreventServer: check and brevent
05-29 11:50:54.048 20337 20337 D BreventServer: check again in 3600s
05-29 11:50:54.048 20337 20337 D BreventServer: check and brevent, took 354ms

**Comment by liudongmiao** [comment]
> Force stop com.tencent.mobileqq(brevent request)
你自己看看你是否设置了立即黑域。

**Comment by liudongmiao** [comment]
你自己在页面搜索 com.tencent.mobileqq

更多的，就需要调试日志了。

**Comment by chinen95** [comment]
设置了 这个设置会无视计时？ 但是大部分时候是正常的 偶尔会出这种问题

**Comment by liudongmiao** [comment]
我说的是，你需要更多调试日志。
你不给调试日志，我咋知道你机器上的原因呢？

有了调试日志，你自己也可以直接针对性搜索：com.tencent.mobileqq

**Comment by liudongmiao** [comment]
举个极端的例子。

如果你打 QQ 打开放后台，如果其它程序试图唤醒它开启新的进程，要不要处理？

不开启立即黑域的话，下次认真判断状态；如果开启了立即黑域，直接强行停止。

因为如果还要去判断它当前的状态，还得调用一系统的 API。
而你开启了这个本不建议开启的功能，就直接图省事，强行停止了事。

**Comment by liudongmiao** [comment]
这个功能，我懒得去优化。如果要优化的化，继续唤醒时看是否在后台运行。
但是，如果在后台运行，但是待机中，要不要处理呢？

还有，其实分屏下也有这样的问题。

当然，如果应用当前正在使用，或者接下来会打开，都不会处理。
以及，桌面小部件，支付宝/微信/Play 商店，“允许同步”都不受此影响。

看这感觉，这个功能应该归为“实验性功能”。

**Comment by chinen95** [comment]
出了这问题之后 我多试了了几次 每次都会发生 不管切出去时间有多短 不可能每次都要其他应用尝试唤醒吧 后台中的TX家APP只有微信一个

**Comment by liudongmiao** [comment]
我给你个包，你测试下吧。

当未达到后台应用超时时，允许唤醒。

**Comment by liudongmiao** [comment]
去测试吧。但是，依旧不保证。

毕竟，“立即黑域”真的是强迫症专享的。
