### ISSUE TITLE
自动更新关闭后，卸载应用依然会更新清单

### ISSUE THREAD

**Issue by cheetah747** [brevent/Brevent#210]
1、列表能按已黑域应用排序吗，把已黑域的排在前面。现在这样看着乱七八糟的，我要检查我哪些应用被黑域了还要遍历整个应用列表看一遍，烦死了！
2、我的应用卸载了再重新装，还要再去黑域里添加一遍，真TM麻烦。你看人家冰箱，添加一遍以后怎么卸载重装都始终在列表里。

**Comment by vvb2060** [comment]
1. 对大多数人，用户应用中已黑域应用比未黑域多得多。而且，有搜索功能和四种排序方式。
2. 黑域的自动更新功能，支持卸载自动移出黑域清单、新安装自动添加进清单。我不知道为什么卸载移出生效，安装添加无效，不过你可以关闭此功能，黑域清单就不会自动改变了。

**Comment by cheetah747** [comment]
1、（其实这个需求也无大碍啦）
2、自动更新一直都是关闭状态，因为我不希望以后每个新安装的应用都自动被黑域掉，是否黑域由我自己决定自己进去添加。但关闭自动更新功能后，一旦卸载，重新安装，这个应用就又恢复未黑域状态了，又要重新添加一遍。

**Comment by liudongmiao** [comment]
卸载一个之前在黑域清单应用，（过了很久，久到你都忘了），重新安装，没有开自动更新选项，被自动黑域了，这才反体验吧？

为了效率，黑域清单内容会被放进内存，不存在的应用会直接忽略。

**Comment by cheetah747** [comment]
不不，你看冰箱的处理，你只要把一个应用加入冻结列表，那么就算卸载再装也还在列表里。。按你说的就算卸载过了好久好久又装回来，那那个应用也应该仍然是被黑域的对象。一般一个应用一朝作恶，也基本不用指望有生之年能从良了。（不过也许每个人需求不同吧，我觉得对我来说这样体验更好）

**Comment by cheetah747** [comment]
冰箱主要是免root模式我总是失败，root模式的话手机的root经常不定期抽风失效，必须重启才能恢复root，急用应用还得等重启后才能解冻，很尴尬。所以才来试试黑域。核心功能两家都很棒。但抛开核心功能，我觉得无论从UI设计还是交互逻辑，都是冰箱更优秀的。（个人拙见

**Comment by vvb2060** [comment]
我一直以为，关闭自动更新后，黑域清单就不会改变了。说明也是“应用安装或**卸载**之后，更新黑域清单”。没想到卸载移出是强制的。
而且就算按现在这种模式，不存在的应用直接忽略。但没有更新清单，还是会出现重新安装被自动黑域。
我觉得关闭自动更新就是想保持现在的清单，不被自动修改。比如使用应用挂载器类似(pm hide xxx)，需要关闭自动更新。

**Comment by liudongmiao** [comment]
至于 UI，能看就不错了…如果你看了之前阻止运行，你会直接想骂人。

我 UI 并不见长（其实后台也如此），UI 是为核心逻辑服务。也正因为此，阻止运行也好，黑域也好，你不打开都成，甚至把黑域冻结，卸载是特意做的无残留。

**Comment by liudongmiao** [comment]
@vvb2060 其实，你的理解也是对的。
如果黑域启动以后，从来不动黑域清单，黑域清单不会更新：
- 开启自动更新
- 手动更新黑域清单，包括允许同步
- 更改系统闹钟，因为闹钟会自动移除，我可不想设了闹钟以后不想
- 更改桌布应用，因为桌面应用自动移除，我可不想设了桌布以后不生效

**Comment by liudongmiao** [comment]
@vvb2060 pm hide 没试，但 pm disable 不触发卸载。
@cheetah747 这与这个开关，更新的是硬盘记录。即使关闭自动更新，内存中的那份，应该随着卸载就移除了。和其他应用超强自信不同，黑域总认为黑域可能带来副作用，所以一旦卸载不会操作。

@cheetah747 此外，我觉得只是冰箱没法做到像黑域一样可以无条件自动更新黑域清单吧，不论模式，不论是否冻结黑域本身。

我本人并不认同冰箱体验，所以不建议拿到一起讨论。

**Comment by vvb2060** [comment]
pm hide触发卸载，pm unhide 触发安装。
