### ISSUE TITLE
黑域影响GooglePlay更新app

### ISSUE THREAD

**Issue by laoyang945** [brevent/Brevent#215]
Asus X00ID 7.1.1
黒域打开的情况下，GooglePlay更新app基本就停在「正在下载」的步骤，要很长很长的时间才会开始下载。如果把黒域关掉的话，google play「正在下载」后很快就开始下载，看到下载进度
不知道是哪个地方需要进一步的设置，谢谢

**Comment by liudongmiao** [comment]
> 谨慎黑域系统应用、框架应用及常用应用，谨慎开启激进模式。

每次都认真写着这句话。

如果你不正确使用，有可能；就我而言，从来没有发生过。

**Comment by laoyang945** [comment]
今天又测试了一下，在wifi情况下才会影响，不过确实是可能是和机型有关，之前我的三星就没有出现这个问题。
我也没有黒域系统应用和框架，激进模式也是关闭的，提这个issue只是说可能有点问题，你有空就研究，没空就算了

**Comment by liudongmiao** [comment]
你再看看，Wifi 是不是和某些应用相关，比如某些需要登录才能使用的，或者说登录用户速度有差别的。

**Comment by laoyang945** [comment]
确认了是华硕机器的问题

**Comment by risyomei** [comment]
我这边也有发生诶。。
