### ISSUE TITLE
三星s7e 从锁屏到解锁 这个过程 卡的实在是受不了了

### ISSUE THREAD

**Issue by flamercao** [brevent/Brevent#22]
从买了这个手机开始 一直就是黑域的忠实用户 但是 最近几个版本 不知道怎么了 手机关闭屏幕 到点亮 到解锁 要花很长时间 有电话打进来 等我按下接听键 也要很久 而且解锁过程 还是一卡一卡的 真的郁闷死了 手机重启后 一切正常了 解锁超快  然后 一连接电脑输入命令之后 又不行了 这到底是什么原因呢 黑域设置中 我已经关闭了检查通知选项了

**Comment by flamercao** [comment]
另外 我装的APP数量 挺多的 大概有200个吧 不知道和应用数量有没有关系  不过 我基本装的都是一些国际版等没有那么流氓的应用

**Comment by flamercao** [comment]
说的简单点 就是手机黑屏时 按下home键或者电源键 需要几秒 到十几秒的时间 屏幕才会亮 然后解锁过程 会出现卡顿 像幻灯片一样 解锁进去后 就一点都不卡了 没有开省电模式 如果手机重启后 不输入命令 就算用一天 解锁也是秒开的 一输入命令 激活黑域后 就开始卡解锁了

**Comment by liudongmiao** [comment]
不要黑域系统应用，框架应用。

没日志，我也不知道发生了什么。

**Comment by flamercao** [comment]
日志 怎么给你看呢？

**Comment by flamercao** [comment]
我就黑域了几个自带应用 但是这几个自带应用 显示在框架和系统应用里面 其他的系统和框架应用 我也没有黑域

**Comment by liudongmiao** [comment]
日志参照商店详情底部。

**Comment by flamercao** [comment]
经过一天测试 1.2版本 极大的改善了这种锁屏的点亮延迟和卡顿 虽然还能感觉到 但是已经能够忍受

**Comment by flamercao** [comment]
帖子关的太快了吧 哈哈

**Comment by liudongmiao** [comment]
我等你日志好发新版，一直没等到…

**Comment by flamercao** [comment]
日志 我发给你看下  1.2版本 有很大改善  但是依旧有解锁和点亮延迟 
[debug.txt](https://github.com/brevent/Brevent/files/1050130/debug.txt)
[crash.txt](https://github.com/brevent/Brevent/files/1050131/crash.txt)
