### ISSUE TITLE
启动黒域后无法开启热点

### ISSUE THREAD

**Issue by JamesTungCY** [brevent/Brevent#220]
版本安卓7.0 Nexus 6P 启动黒域时无法打开热点 重启未adb授权黒域时正常 adb后又无法打开 请问如何解决

**Comment by JamesTungCY** [comment]
准确来说是开启only force stop no stand by 模式时

**Comment by vvb2060** [comment]
> 谨慎黑域系统应用、框架应用及常用应用，谨慎开启激进模式。

我的Nexus 6P在7.0，7.1，8.0时没遇到这个问题，目前8.1测试也没有问题。

**Comment by JamesTungCY** [comment]
调回standby后forcestop模式 已解决
