### ISSUE TITLE
TIM这个妖孽的“返回”是假的。

### ISSUE THREAD

**Issue by weigaow** [brevent/Brevent#228]
虽然开启了识别非正常返回，但是[TIM](http://office.qq.com/)（V2.1.0.1742）这个妖孽还是无法降住，柳大看有办法吗？

**Comment by liudongmiao** [comment]
有部分用户反馈，这个有不可取消通知。
目前黑域对于不可取消通知，只要在后台，不会处理它。

你可以直接从最近列表划掉。

**Comment by weigaow** [comment]
OK，通知类型改为“降噪通知”（H2OS）就可以用了。
