### ISSUE TITLE
小游使用官网motionelf.apk手机重启后无法激活黑域

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#229]
小游（19￥）到手有一周了，一直没时间试。今天用mate8 emui5 android7.0试了一下，发现黑域已被激活的情况下，安装正版motionelf.apk，用小游能重新激活黑域（蓝灯常亮），但手机重启后就没法激活了，小游蓝灯一直在闪。试了很多次，只要手机重启，就没法重新激活，蓝灯狂闪，只有连电脑激活后紧接着再用小游才可以。反而是用那个非授权需要自己保存命令的app怎么都可以激活。这种情况有些奇怪啊。

看日志好像是一直连不上
01-23 19:17:34.494  5306  5306 I BreventUI: received: android.hardware.usb.action.USB_STATE
01-23 19:17:34.638  5306  5306 I BreventUI: received: android.hardware.usb.action.USB_STATE
01-23 19:17:56.398  5306  5366 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 19:17:56.399  5306  5364 I BreventUI: service.adb.tcp.port: 
01-23 19:17:56.402  5306  5364 I BreventUI: request status
01-23 19:17:56.403  5306  5366 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 19:17:57.403  5306  5364 I BreventUI: retry request status
01-23 19:17:57.406  5306  5366 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 19:17:58.407  5306  5364 I BreventUI: retry request status
01-23 19:17:58.416  5306  5366 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 19:17:59.418  5306  5364 I BreventUI: retry request status
01-23 19:17:59.421  5306  5366 W BreventUI: Can't brevent(Connection refused) to localhost

**Comment by CVN-77** [comment]
![screenshot_20180123-195730](https://user-images.githubusercontent.com/26182187/35274447-0d7546f8-0077-11e8-9cb2-a71ba6b67dda.png)

调试选择仅充电允许usb调试

**Comment by CVN-77** [comment]
这是已用非授权app激活服务但无法进入黑域后，卸载非授权app安装官方motionelf.apk，用小游重新激活的日志。这时候黑域服务已经激活，用motionelf.apk可以直接重新激活，但手机重启后还是无法激活

01-23 20:05:06.551  5531  5531 I BreventUI: received: android.hardware.usb.action.USB_STATE
01-23 20:05:07.430  5531  5597 I BreventUI: request status
01-23 20:05:07.506  5531  5531 I BreventUI: received: android.hardware.usb.action.USB_STATE
01-23 20:05:11.901  5531  5531 I BreventUI: received: android.hardware.usb.action.USB_STATE
01-23 20:05:11.932  5531  5531 I BreventUI: received: android.hardware.usb.action.USB_STATE
01-23 20:05:13.021  5531  5597 I BreventUI: request status
01-23 20:05:13.237  5531  5597 W BreventUI: Can't brevent(null) to localhost/::1:59526
01-23 20:05:13.237  5531  5597 W BreventUI: java.io.EOFException
01-23 20:05:13.237  5531  5597 W BreventUI: 	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
01-23 20:05:13.237  5531  5597 W BreventUI: 	at me.piebridge.brevent.protocol.BreventProtocol.readFrom(BreventProtocol.java:103)
01-23 20:05:13.237  5531  5597 W BreventUI: 	at me.piebridge.brevent.ui.d.a(AppsActivityHandler.java:352)
01-23 20:05:13.237  5531  5597 W BreventUI: 	at me.piebridge.brevent.ui.d.a(AppsActivityHandler.java:310)
01-23 20:05:13.237  5531  5597 W BreventUI: 	at me.piebridge.brevent.ui.d.handleMessage(AppsActivityHandler.java:123)
01-23 20:05:13.237  5531  5597 W BreventUI: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-23 20:05:13.237  5531  5597 W BreventUI: 	at android.os.Looper.loop(Looper.java:156)
01-23 20:05:13.237  5531  5597 W BreventUI: 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-23 20:05:13.238 19830 19830 E BreventLoader: worker 19841 exited on signal 15
01-23 20:05:14.153  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:14.153  5531  5597 I BreventUI: service.adb.tcp.port: 
01-23 20:05:14.156  5531  5597 I BreventUI: request status
01-23 20:05:14.157  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:14.163  6139  6139 I BreventServer: args: [10, me.piebridge.brevent, 1516709113]
01-23 20:05:14.329  6139  6139 I BreventServer: server log name: server.20180123.2005.6139.txt
01-23 20:05:14.338  6139  6139 I BreventServer: starting Brevent Server 2.6.1
01-23 20:05:14.417  6139  6139 I BreventServer: brevent user: 0, uid: 2000
01-23 20:05:14.425  6139  6139 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
01-23 20:05:14.468  6139  6139 I BreventServer: no service overlay
01-23 20:05:14.478  6139  6139 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 1
01-23 20:05:14.605  6139  6157 I BreventServer: system_server: 1338, now: 1516709114
01-23 20:05:15.158  5531  5597 I BreventUI: retry request status
01-23 20:05:15.160  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:15.205  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:15.205  5531  5597 I BreventUI: service.adb.tcp.port: 
01-23 20:05:15.206  5531  5597 I BreventUI: request status
01-23 20:05:15.207  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:16.162  5531  5597 I BreventUI: retry request status
01-23 20:05:16.164  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:16.208  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:16.209  5531  5597 I BreventUI: service.adb.tcp.port: 
01-23 20:05:16.211  5531  5597 I BreventUI: request status
01-23 20:05:16.213  5531  5599 W BreventUI: Can't brevent(Connection refused) to localhost/::1:59526
01-23 20:05:16.834  6139  6139 I BreventServer: notification_cancel_all events: 5
01-23 20:05:16.890  6139  6139 I BreventServer: charging: false
01-23 20:05:16.890  6139  6139 I BreventServer: support standby: true
01-23 20:05:16.891  6139  6139 I BreventServer: support stopped: true
01-23 20:05:16.891  6139  6139 I BreventServer: support upgrade: true
01-23 20:05:16.892  6139  6139 I BreventServer: support appops: true
01-23 20:05:16.892  6139  6139 I BreventServer: Brevent Server 2.6.1 started
01-23 20:05:16.902  5531  5531 I BreventUI: received: me.piebridge.brevent.intent.action.BREVENT
01-23 20:05:16.910  6139  6139 I BreventServer: received first event
01-23 20:05:16.926  6139  6177 W BreventServer: sent 10 to 6117
01-23 20:05:17.166  5531  5597 I BreventUI: retry request status
01-23 20:05:18.680  5531  5597 I BreventUI: request status
01-23 20:05:20.097  5531  5597 I BreventUI: received response
01-23 20:05:20.102  5531  5597 I BreventUI: daemon: 0, server: 0
01-23 20:05:25.756  5531  6404 I BreventUI: request status
01-23 20:05:27.328  5531  6404 I BreventUI: received response

**Comment by liudongmiao** [comment]
motionelf.apk 需要打开一次，才会释放相应文件。

**Comment by CVN-77** [comment]
我安装完立刻就打开了，打开后启动黑域，桌面图标隐藏，但重启手机后连小游还是蓝灯一直闪，没有激活成功

**Comment by liudongmiao** [comment]
说明你手机可能有毒，隐藏以后，有副作用。

**Comment by CVN-77** [comment]
…这个有解决办法不，我现在重启手机后用小游激活只能先卸载motionelf.apk安装非授权apk激活服务，然后卸载非授权apk安装回motionelf.apk，再用小游激活一次才能打开，绕了一圈…

**Comment by liudongmiao** [comment]
别急，我这两天就会测试单独激活器；motionelf 将不再维护。

**Comment by liudongmiao** [comment]
测试版发你邮箱了。

这个应该属于 ROM 原因，每次重启恢复目录权限。早先 小游 没做好兼容处理，近期版本应该没问题。也就是，不能隐藏了。

**Comment by CVN-77** [comment]
OK了，新版本重启后按步骤先打开黑域再插小游即可激活服务，目前这小硬件的体验还不错的，到时飞智黑域版出了会继续支持！

**Comment by CVN-77** [comment]
感觉重启后要是能不用打开黑域直接启动服务就更好不过了，有些懒…vvfgaa那个cmd工具可以能够无指令文件启动服务。我之前也试过把一个brevent.sh  push进了/data/local/tmp里面，每次adb激活时就用这个激活，不用打开黑域界面。不知道小游硬件/飞智黑域厅可不可以再优化以避开权限的问题，不过不行也无妨，以后黑域支持手敲指令，我就用sh /data/local/tmp/brevent.sh了

**Comment by liudongmiao** [comment]
是你系统原因啊...

飞智小黑当然支持。已经测试以下情况：

1. 没有安装黑域，跳转落地页，可以下载安装。

2. 只要安装了应用，就可以激活，不必打开应用。
你手里的版本，应该比较低，不支持没有权限时自动打开。

黑域支持手敲指令，你黑域都没激活呢，怎么执行指令...

**Comment by CVN-77** [comment]
自动打开应用的版本还有不…我用的是邮件里的motionelf-donated.apk和2.6.1+1。重启后需要手动打开黑域界面才能激活成功，蓝灯常亮。如果重启后直接插小游，不会自动打开黑域（没有限制黑域及motionelf-donated.apk），蓝灯一直在闪（如果这时候拔线打开黑域仍提示激活），需要连着小游同时手动打开黑域，才能完成激活。

其他命令这个，我原以为是通过motionelf-donated.apk额外支持修改/增加启动命令，插小游时立刻响应，就像酷安那个一样（试过不打开黑域时同样无法通过sh /data/data/me.piebridge.brevent/brevent.sh激活成功，但能直接激活 sh /data/local/tmp XXX，还有某ops）。之前不太清楚这些命令是由黑域完成还是motionelf-donated.apk完成…是不是motionelf-donated.apk只能单独激活黑域服务，其他adb的命令需要等黑域启动后完成？

这样也没问题，我的需求就是重启后不用人工手动打开黑域界面，这个界面可以在插小游后自己打开，蓝灯常亮先确保把黑域激活，再自动完成其他的命令。但由于我这里无法自动打开黑域，我才想着要不就更改motionelf-donated.apk的命令，让它执行本地文件，能够插小游直接完成激活，不用手动打开黑域这一步…

**Comment by liudongmiao** [comment]
是这样子的，小游硬件激活有这步： dd if=XX of=XX
这步，有可能是 no such file，有可能是 permission denied
已知某个版本以后，可以处理这两种异常；但你手里的版本，没有处理 permission denied。
绝大部分 Rom 重启后不会重设目录权限，你手里 Rom 没有。

等新版小游，或者小黑。这两个都可以解决。

至于支持其它应用，或者说执行指令，是黑域提供的功能，不是假冒游戏厅。
2.6.2 将去除一切限制，连 test 签名都不必，随便玩，反正与黑域无关。

**Comment by CVN-77** [comment]
就是说我手里的小游版本低了，不会处理这种情况？这个只能等硬件更新，用新版本小游硬件，或者小黑硬件？我原以为能通过motionelf-donated.apk更新解决，没想到是硬件问题…不过搞清楚了就行，用低版本硬件+motionelf-donated.apk无非就是多点一次，也能接受。

其他指令由黑域完成，能够理解，这也属于黑域开发的功能点，通过黑域界面管理，不用额外一个app，也方便更新维护。就是要先确保黑域服务启动。这个功能还是很期待的。

看来很多问题还是得从硬件上解决。飞智小黑，相比原硬件提升点还有哪些？希望更强大更方便
