### ISSUE TITLE
黑域 2.6.1: 黑域服务权限不足，部分功能暂不可用。请检查“开发者选项”中与“USB调试”相关的设置

### ISSUE THREAD

**Issue by Myfreedom614** [brevent/Brevent#230]
| Brevent Version | Phone Model | Phone OS Version |
| - | - | - |
|黑域 2.6.1 | XiaoMi MIX2 | MIUI 9.2 稳定版  **9.2.5.0**|

每次打开黑域提示：

**黑域服务权限不足，部分功能暂不可用。请检查“开发者选项”中与“USB调试”相关的设置**

**确认已经开启USB调试**，是从黑域上个版本开始出现此问题的

![screenshot_2018-01-25-10-19-16-798_me piebridge brevent](https://user-images.githubusercontent.com/2476467/35367825-63b5473a-01bb-11e8-8db6-4968a24c53ac.png)

@liudongmiao

**Comment by liudongmiao** [comment]
以前也没有权限，只是我没有为 miui 适配，所以没有提示。

你可以点确定，然后直接去设置中找与“USB 调试”，“权限”相关的选项...

**Comment by Myfreedom614** [comment]
@liudongmiao  貌似得开启 USB调试（安全设置） 允许通过USB调试修改权限或模拟点击
