### ISSUE TITLE
failed to start the server via adb shell , on lineage os 14 & oneplus2 

### ISSUE THREAD

**Issue by Z-Y00** [brevent/Brevent#232]
As you can see , I could only start it by root.
the version is 2.4.4a, downloaded from play store
![image](https://user-images.githubusercontent.com/23717414/35467724-17e4e81a-030a-11e8-90c3-c6801307bb53.png)

**Comment by Z-Y00** [comment]
![image](https://user-images.githubusercontent.com/23717414/35467770-c3e06f68-030a-11e8-9606-0235d030d648.png)

**Comment by liudongmiao** [comment]
Please follow instruction of Brevent.

And the command is "sh /data/data...", not direc /data/data..
