### ISSUE TITLE
没有权限访问黑域服务

### ISSUE THREAD

**Issue by youyim** [brevent/Brevent#233]
没有权限访问黑域服务。Android 7.1.1 Nubia Z11
[log.txt](https://github.com/brevent/Brevent/files/1669981/log.txt)
![screenshot_2018-01-27-18-15-13](https://user-images.githubusercontent.com/19865880/35471027-d979a73e-038e-11e8-9355-7da155cc9650.png)
![qq 20180127181558](https://user-images.githubusercontent.com/19865880/35471029-dcc2fd8c-038e-11e8-9dae-a18c05eecaa0.png)

**Comment by liudongmiao** [comment]
要求黑域在前台，但是，你的机器上，明显不是。
01-27 18:13:16.254  9200  9224 W BreventServer: has no .ui.Brevent


请使用黑域内建日志功能，或者手动带上黑域日志。

**Comment by liudongmiao** [comment]
你也可以打开黑域时，直接电脑上执行 dumpsys activity me.piebridge.brevent

**Comment by youyim** [comment]
黑域一直处于前台，用adb输完命令就如上图所示。
[2.log](https://github.com/brevent/Brevent/files/1670723/2.log)

**Comment by vvb2060** [comment]
@youyim123 2.log使用的命令错了。
电脑输完启动命令，手机打开黑域显示“没有权限访问黑域服务…”时，电脑继续输入命令`adb -d shell dumpsys activity me.piebridge.brevent` ，把结果发上来

**Comment by liudongmiao** [comment]
如果你系统太慢，如检查黑域是否在前台超时，有可能会这样。
你先看看 2.6.4 这个版本，进行了部分优化。

**Comment by youyim** [comment]
我没有在酷安找到2.6.4版本。
这个是adb -d shell dumpsys activity me.piebridge.brevent输出结果
![qq 20180129102645](https://user-images.githubusercontent.com/19865880/35491032-fb175368-04de-11e8-9168-2b361c1fa512.png)

**Comment by liudongmiao** [comment]
https://piebridge.me/br/beta/ 这个版本

**Comment by liudongmiao** [comment]
你这个输出结果很奇怪，非常奇怪。正常的话，会有这个的状态信息。

**Comment by youyim** [comment]
2.6.4和之前的一样
![qq 20180129205137](https://user-images.githubusercontent.com/19865880/35511359-7e11092e-0536-11e8-8a81-61644f943f48.png)

**Comment by liudongmiao** [comment]
那基本没有办法支持你的机器。
黑域通过这个来判断是否处理前台。

**Comment by liudongmiao** [comment]
看下 2.6.5: https://piebridge.me/br/beta/

**Comment by youyim** [comment]
2.6.5可以正常使用了

**Comment by liudongmiao** [comment]
烦请黑域里发送一下日志，并描述一下情况吧，要不然我也不知道是你。

**Comment by youyim** [comment]
我没在黑域内找到如何发送日志给你。唯一的一个反馈功能是跳转到黑域github的issues

**Comment by liudongmiao** [comment]
装邮箱应用。
