### ISSUE TITLE
啟動失敗

### ISSUE THREAD

**Issue by eason-li** [brevent/Brevent#237]
C:\Users\yiche\Downloads\platform-tools-latest-windows\platform-tools>adb devices
List of devices attached
G7AZCY0054234JK device

C:\Users\yiche\Downloads\platform-tools-latest-windows\platform-tools>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server..fail
[command] pm path me.piebridge.brevent
sh: pm: not found
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '01-30 09:39:39.000' -d
sh: logcat: not found
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-30 09:39:39.000' -d -s BreventLoader BreventServer
sh: logcat: not found
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

手機是ZE520KL OS是oreo

**Comment by liudongmiao** [comment]
没有 pm / logcat 等指令，其实我也没有什么好的办法...
