### ISSUE TITLE
由黑域设置进支付宝查询时会遇到的问题

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#24]
识别成功后的toast一直弹窗：

正常时，转账记录（→账单详情→往来记录）→转账输金额→黑域主界面，共五个界面，只要先在转账记录弹出toast后，按顺序进入其他四个界面都会弹。但是有时会遇到toast持续弹窗的时间特别长，远超弹5次的时间，而且现象也是那种拼命的弹，不是渐出后再显示。

复现方式：进入转账记录看到弹toast后，快速点进账单详情再快速点进往来记录，再快速返回账单详情再返回转账记录，期间动作要快，不等toast消失就快速切换页面，然后停在转账记录不返回，此时toast就一直弹，一直弹后再返回，toast就要等一段长时间后才消失。

**Comment by CVN-77** [comment]
黑域服务重启：

反复尝试过程中，在转账记录遇到一直弹toast后，此时再快速前进后退切换页面，容易遇到“黑域服务正常启动，请稍候再试”的toast，但通知栏没有提示(已开启检查)，返回也是正常的回到设置，不是重进那样刷新，似乎是瞬间掉服务又连上。

**Comment by CVN-77** [comment]
08-16 01:36:59.933  5769  5769 I BreventServer: Brevent Server 2.1.2-30-gc5c3fdc started
08-16 01:36:59.936  5769  5769 D BreventServer: get service: appops
08-16 01:36:59.938  5769  5769 D BreventServer: set appops, package: me.piebridge.brevent, package uid: 10205, code: 43, mode: 0
08-16 01:36:59.938  5769  5769 I BreventServer: checking port
08-16 01:36:59.949  5769  5769 I BreventServer: checked port
08-16 01:37:02.157  5769  5769 I BreventServer: received first event
08-16 01:37:02.187  5769  5769 D BreventServer: update current to com.eg.android.AlipayGphone
08-16 01:37:02.187  5769  5769 D BreventServer: previous: null, packageName: com.eg.android.AlipayGphone
08-16 01:37:08.883  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:10.550  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:11.983  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:13.567  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:15.080  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:15.355  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:15.763  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:16.242  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:17.222  5769  5769 D BreventServer: get service: deviceidle
08-16 01:37:17.227  5769  5769 I BreventServer: make brevent tempwhitelist
08-16 01:37:17.227  5769  5769 D BreventServer: update current to me.piebridge.brevent
08-16 01:37:17.227  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: me.piebridge.brevent
08-16 01:37:18.801  5769  5769 D BreventServer: update current to com.eg.android.AlipayGphone
08-16 01:37:18.801  5769  5769 D BreventServer: previous: me.piebridge.brevent, packageName: com.eg.android.AlipayGphone
08-16 01:37:18.803  5769  5769 D BreventServer: classname: com.alipay.mobile.quinox.LauncherActivity.alias
08-16 01:37:19.021  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:19.021  5769  5769 D BreventServer: classname: com.alipay.mobile.quinox.LauncherActivity
08-16 01:37:19.272  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:19.272  5769  5769 D BreventServer: classname: com.alipay.mobile.scan.as.router.CodeRouteActivity
08-16 01:37:19.678  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:19.678  5769  5769 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFQueryReceiveInfoActivity_
08-16 01:37:20.051  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:20.051  5769  5769 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFToAccountConfirmActivity_
08-16 01:37:21.021  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:21.021  5769  5769 D BreventServer: classname: com.alipay.mobile.bill.list.ui.ObjectSetActivity_
08-16 01:37:22.027  5769  5769 D BreventServer: doRefreshAccessibility
08-16 01:37:22.067  5769  5769 D BreventServer: name: 黑域(*)
08-16 01:37:22.071  5769  5769 D BreventServer: account: pr***@piebridge.me
08-16 01:37:22.074  5769  5769 I BreventServer: bill:   月   支出:           收入:
08-16 01:37:22.477  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:22.478  5769  5769 D BreventServer: classname: com.alipay.mobile.nebulacore.ui.H5Activity
08-16 01:37:23.116  5769  5769 D BreventServer: doRefreshAccessibility
08-16 01:37:24.385  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:24.385  5769  5769 D BreventServer: classname: com.alipay.mobile.bill.list.ui.ObjectSetActivity_
08-16 01:37:25.557  5769  5769 D BreventServer: doRefreshAccessibility
08-16 01:37:25.569  5769  5769 D BreventServer: name: 黑域(*)
08-16 01:37:25.572  5769  5769 D BreventServer: account: pr***@piebridge.me
08-16 01:37:25.574  5769  5769 I BreventServer: bill:   月   支出:          收入:
08-16 01:37:25.779  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:25.779  5769  5769 D BreventServer: classname: com.alipay.mobile.nebulacore.ui.H5Activity
08-16 01:37:26.415  5769  5769 D BreventServer: doRefreshAccessibility
08-16 01:37:27.389  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:27.389  5769  5769 D BreventServer: classname: com.alipay.mobile.bill.list.ui.ObjectSetActivity_
08-16 01:37:28.265  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:28.265  5769  5769 D BreventServer: classname: com.alipay.mobile.nebulacore.ui.H5Activity
08-16 01:37:28.604  5769  5769 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:28.604  5769  5769 D BreventServer: classname: com.alipay.mobile.bill.list.ui.ObjectSetActivity_
08-16 01:37:28.609  5769  5769 W BreventServer: Can't startAccessibility
08-16 01:37:28.609  5769  5769 W BreventServer: Can't cancelAccessibility
08-16 01:37:28.903  9355  9355 D BreventLoader: worker 5769 exited with status 0
08-16 01:37:28.903  9355  9355 D BreventLoader: signal arrived, update: 1
08-16 01:37:29.322  9355  9355 D BreventLoader: line: package:/data/app/me.piebridge.brevent-2/base.apk
08-16 01:37:29.322  9355  9355 D BreventLoader: 
08-16 01:37:29.344  9355  9355 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
08-16 01:37:29.713  6313  6313 D BreventServer: get service: package
08-16 01:37:29.713  6313  6313 D BreventServer: args: [10]
08-16 01:37:29.713  6313  6313 I BreventServer: signal: 10
08-16 01:37:29.725  6313  6313 I BreventServer: starting Brevent Server 2.1.2-30-gc5c3fdc
08-16 01:37:29.731  6313  6313 D BreventServer: get service: package
08-16 01:37:29.732  6313  6313 I BreventServer: brevent user: 0, uid: 2000
08-16 01:37:29.733  6313  6313 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-16 01:37:29.753  6313  6313 I BreventServer: loading brevent list
08-16 01:37:29.757  6313  6313 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 73
08-16 01:37:29.769  6313  6313 I BreventServer: loading brevent conf
08-16 01:37:29.773  6313  6313 D BreventServer: get service: appwidget
08-16 01:37:29.778  6313  6313 D BreventServer: get service: usagestats
08-16 01:37:29.920  6313  6328 I BreventServer: Brevent Event, now: 1502818649
08-16 01:37:29.920  6313  6313 D BreventServer: check and brevent
08-16 01:37:29.921  6313  6313 D BreventServer: get service: notification
08-16 01:37:29.944  6313  6328 I BreventServer: system_server: 1628, now: 1502818649
08-16 01:37:30.706  6313  6313 D BreventServer: get service: activity
08-16 01:37:30.745  6313  6313 D BreventServer: get service: alarm
08-16 01:37:30.749  6313  6313 D BreventServer: get service: wallpaper
08-16 01:37:30.909  6313  6313 W BreventServer: com.litesuits.control has foreground service, but without notification
08-16 01:37:30.913  6313  6313 D BreventServer: get service: deviceidle
08-16 01:37:30.921  6313  6313 D BreventServer: check again in 822s
08-16 01:37:30.921  6313  6313 D BreventServer: check and brevent, took 1000ms
08-16 01:37:30.994  6313  6313 I BreventServer: notification_cancel_all events: 0
08-16 01:37:31.000  6313  6313 D BreventServer: Force stop com.android.shell(notification_cancel_all)
08-16 01:37:31.050  6313  6313 I BreventServer: notification_cancel_all events: 1
08-16 01:37:31.051  6313  6313 D BreventServer: get service: batterystats
08-16 01:37:31.051  6313  6313 I BreventServer: charging: false
08-16 01:37:31.052  6313  6313 I BreventServer: support standby: true
08-16 01:37:31.052  6313  6313 I BreventServer: support stopped: true
08-16 01:37:31.052  6313  6313 I BreventServer: support upgrade: true
08-16 01:37:31.052  6313  6313 I BreventServer: Brevent Server 2.1.2-30-gc5c3fdc started
08-16 01:37:31.053  6313  6313 D BreventServer: get service: appops
08-16 01:37:31.054  6313  6313 D BreventServer: set appops, package: me.piebridge.brevent, package uid: 10205, code: 43, mode: 0
08-16 01:37:31.054  6313  6313 I BreventServer: checking port
08-16 01:37:31.058  6313  6313 I BreventServer: checked port
08-16 01:37:31.058  6313  6313 I BreventServer: received first event
08-16 01:37:34.124  6313  6313 D BreventServer: update current to com.eg.android.AlipayGphone
08-16 01:37:34.124  6313  6313 D BreventServer: previous: null, packageName: com.eg.android.AlipayGphone
08-16 01:37:41.110  6313  6313 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:42.192  6313  6313 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 01:37:46.081  6313  6313 D BreventServer: get service: deviceidle
08-16 01:37:46.084  6313  6313 I BreventServer: make brevent tempwhitelist
08-16 01:37:46.084  6313  6313 D BreventServer: update current to me.piebridge.brevent
08-16 01:37:46.084  6313  6313 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: me.piebridge.brevent
08-16 01:37:48.121  6313  6313 D BreventServer: update current to com.android.settings
08-16 01:37:48.143  6313  6313 D BreventServer: previous: com.android.settings, packageName: com.android.settings
08-16 01:37:50.973  6313  6313 D BreventServer: get service: deviceidle
08-16 01:37:50.980  6313  6313 I BreventServer: make brevent tempwhitelist
08-16 01:37:50.980  6313  6313 D BreventServer: update current to me.piebridge.brevent
08-16 01:37:50.980  6313  6313 D BreventServer: previous: com.android.settings, packageName: me.piebridge.brevent
08-16 01:37:51.831  6313  6313 D BreventServer: get service: deviceidle
08-16 01:37:51.834  6313  6313 I BreventServer: make brevent tempwhitelist
08-16 01:37:51.834  6313  6313 D BreventServer: previous: me.piebridge.brevent, packageName: me.piebridge.brevent
08-16 01:37:51.836 21042 21042 D BreventUI: onActivityResult
08-16 01:37:51.844 21042 21108 V BreventUI: connected to localhost: 59526
08-16 01:37:51.844 21042  5261 D BreventUI: request status
08-16 01:37:51.847 21042 21108 V BreventUI: connected to localhost: 59526
08-16 01:37:51.962  6313  6334 D BreventServer: get service: deviceidle
08-16 01:37:51.968  6313  6334 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-16 01:37:52.030  6313  6334 D BreventServer: get service: lock_settings
08-16 01:37:52.032  9355  9355 D BreventLoader: received signal: 10, ppid: 1
08-16 01:37:52.032  6313  6334 W BreventServer: sent 10 to 9355
08-16 01:37:52.039 21042  5261 D BreventUI: days: 0, living: 0
08-16 01:37:52.177 21042  5261 D BreventUI: setAlarm
08-16 01:37:54.991 21042  5261 D BreventUI: logcat for system.txt
08-16 01:37:55.252 21042  5261 D BreventUI: logcat for events.txt
08-16 01:37:55.341 21042  5261 D BreventUI: logcat for brevent.txt

**Comment by CVN-77** [comment]
除了这个，有时正常的由黑域设置进入支付宝时，如果有个额外的第三方安全应用的程序锁，解锁后再切到转账界面，就没有toast，似乎没识别，需要返回设置再重新来一次，没有程序锁直接进就识别了。

这里是不是“仅查看从黑域设置打开支付宝后的转账记录页面”做的限定，就是包括中途有其他应用界面切出来都不行？如果是这样能理解。

**Comment by CVN-77** [comment]
除了这个，有时正常的由黑域设置进入支付宝时，如果有个额外的第三方安全应用的程序锁，解锁后再切到转账界面，就没有toast，似乎没识别，需要返回设置再重新来一次，没有程序锁直接进就识别了。这里是不是“仅查看从黑域设置打开支付宝后的转账记录页面”做的限定，就是包括中途有其他应用界面切出来都不行？如果是这样能理解。

但有时在没有其他应用界面干扰的情况下，由黑域设置进入支付宝转账记录时不知为何也没有toast，需要紧接着再来一次才行。以下是日志，45分后第一次从设置进入支付宝，全程没有其他界面干扰，但没有识别，返回设置再进入支付宝，就识别了，进行了两次。
08-16 02:45:00.798 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:00.799 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:00.799 24655 24655 D BreventServer: update current to me.piebridge.brevent
08-16 02:45:00.799 24655 24655 D BreventServer: previous: com.sonymobile.home, packageName: me.piebridge.brevent
08-16 02:45:00.824 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:00.825 15906 29970 D BreventUI: request status
08-16 02:45:00.827 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:00.864 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:00.865 24655 24673 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-16 02:45:00.884 15906 29970 D BreventUI: received response
08-16 02:45:01.220 15906 29970 D BreventUI: setAlarm
08-16 02:45:01.221 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:01.233 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:01.234 24655 24673 I BreventServer: make brevent tempwhitelist
08-16 02:45:03.439 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:03.442 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:03.442 24655 24655 D BreventServer: previous: me.piebridge.brevent, packageName: me.piebridge.brevent
08-16 02:45:04.430 24655 24655 D BreventServer: update current to com.eg.android.AlipayGphone
08-16 02:45:04.450 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:05.407 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:05.942 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:06.527 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:10.701 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:11.731 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:16.191 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:17.313 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:18.807 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:18.824 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:18.824 24655 24655 D BreventServer: update current to me.piebridge.brevent
08-16 02:45:18.824 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: me.piebridge.brevent
08-16 02:45:19.158 24655 24655 D BreventServer: check and brevent
08-16 02:45:20.013 24655 24655 W BreventServer: com.litesuits.control has foreground service, but without notification
08-16 02:45:20.024 24655 24655 D BreventServer: Force stop com.taobao.taobao(service)
08-16 02:45:20.029 24655 24655 D BreventServer: check again in 1276s
08-16 02:45:20.029 24655 24655 D BreventServer: check and brevent, took 870ms
08-16 02:45:23.130 24655 24655 D BreventServer: check and brevent
08-16 02:45:24.120 24655 24655 W BreventServer: com.litesuits.control has foreground service, but without notification
08-16 02:45:24.126 24655 24655 D BreventServer: check again in 1272s
08-16 02:45:24.126 24655 24655 D BreventServer: check and brevent, took 993ms
08-16 02:45:24.127 24655 24655 D BreventServer: update current to com.eg.android.AlipayGphone
08-16 02:45:24.127 24655 24655 D BreventServer: previous: me.piebridge.brevent, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.128 24655 24655 D BreventServer: classname: com.alipay.mobile.quinox.LauncherActivity.alias
08-16 02:45:24.130 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.130 24655 24655 D BreventServer: classname: com.alipay.mobile.quinox.LauncherActivity
08-16 02:45:24.131 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.131 24655 24655 D BreventServer: classname: com.alipay.mobile.scan.as.router.CodeRouteActivity
08-16 02:45:24.414 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.414 24655 24655 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFQueryReceiveInfoActivity_
08-16 02:45:24.806 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.806 24655 24655 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFToAccountConfirmActivity_
08-16 02:45:31.917 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:31.917 24655 24655 D BreventServer: classname: com.alipay.mobile.bill.list.ui.ObjectSetActivity_
08-16 02:45:33.002 24655 24655 D BreventServer: doRefreshAccessibility
08-16 02:45:33.067 24655 24655 D BreventServer: name: 黑域(*栋淼)
08-16 02:45:33.078 24655 24655 D BreventServer: account: pr***@piebridge.me
08-16 02:45:33.088 24655 24655 I BreventServer: bill: 。月   支出:                收入:
08-16 02:45:33.993 24655 24655 D BreventServer: doRefreshAccessibility
08-16 02:45:34.030 24655 24655 D BreventServer: name: 黑域(*)
08-16 02:45:34.035 24655 24655 D BreventServer: account: pr***@piebridge.me
08-16 02:45:34.039 24655 24655 I BreventServer: bill:   月   支出:            收入:   
08-16 02:45:34.476 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:34.476 24655 24655 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFToAccountConfirmActivity_
08-16 02:45:34.980 24655 24655 D BreventServer: doRefreshAccessibility
08-16 02:45:35.276 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:35.276 24655 24655 D BreventServer: classname: com.eg.android.AlipayGphone.AlipayLogin
08-16 02:45:37.962 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:37.965 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:37.965 24655 24655 D BreventServer: update current to me.piebridge.brevent
08-16 02:45:37.965 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: me.piebridge.brevent
08-16 02:45:40.066 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:40.067 15906 15906 D BreventUI: onActivityResult
08-16 02:45:40.071 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:40.071 24655 24655 D BreventServer: previous: me.piebridge.brevent, packageName: me.piebridge.brevent
08-16 02:45:40.080 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:40.081 15906 29970 D BreventUI: request status
08-16 02:45:40.089 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:40.148 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:40.152 24655 24673 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-16 02:45:40.422 15906 29970 D BreventUI: setAlarm
08-16 02:45:40.432 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:40.545 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:40.547 24655 24673 I BreventServer: make brevent tempwhitelist
08-16 02:45:43.567 15906 29970 D BreventUI: logcat for system.txt
08-16 02:45:43.783 15906 29970 D BreventUI: logcat for events.txt
08-16 02:45:43.872 15906 29970 D BreventUI: logcat for brevent.txt

**Comment by CVN-77** [comment]
有时查询没反应需要再来一次：

有时正常的由黑域设置进入支付宝时，如果有个额外的第三方安全应用的程序锁，解锁后再切到转账界面，就没有toast，似乎没识别，需要返回设置再重新来一次，没有程序锁直接进就识别了。这里是不是“仅查看从黑域设置打开支付宝后的转账记录页面”做的限定，就是包括中途有其他应用界面切出来都不行？如果是这样能理解。

但有时在没有其他应用界面干扰的情况下，由黑域设置进入支付宝转账记录时不知为何也没有toast，需要紧接着再来一次才行。以下是日志，45分后第一次从设置进入支付宝，全程没有其他界面干扰，但没有识别，返回设置再进入支付宝，就识别了，进行了两次查询。


08-16 02:45:00.798 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:00.799 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:00.799 24655 24655 D BreventServer: update current to me.piebridge.brevent
08-16 02:45:00.799 24655 24655 D BreventServer: previous: com.sonymobile.home, packageName: me.piebridge.brevent
08-16 02:45:00.824 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:00.825 15906 29970 D BreventUI: request status
08-16 02:45:00.827 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:00.864 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:00.865 24655 24673 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-16 02:45:00.884 15906 29970 D BreventUI: received response
08-16 02:45:01.220 15906 29970 D BreventUI: setAlarm
08-16 02:45:01.221 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:01.233 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:01.234 24655 24673 I BreventServer: make brevent tempwhitelist
08-16 02:45:03.439 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:03.442 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:03.442 24655 24655 D BreventServer: previous: me.piebridge.brevent, packageName: me.piebridge.brevent
08-16 02:45:04.430 24655 24655 D BreventServer: update current to com.eg.android.AlipayGphone
08-16 02:45:04.450 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:05.407 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:05.942 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:06.527 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:10.701 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:11.731 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:16.191 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:17.313 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:18.807 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:18.824 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:18.824 24655 24655 D BreventServer: update current to me.piebridge.brevent
08-16 02:45:18.824 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: me.piebridge.brevent
08-16 02:45:19.158 24655 24655 D BreventServer: check and brevent
08-16 02:45:20.013 24655 24655 W BreventServer: com.litesuits.control has foreground service, but without notification
08-16 02:45:20.024 24655 24655 D BreventServer: Force stop com.taobao.taobao(service)
08-16 02:45:20.029 24655 24655 D BreventServer: check again in 1276s
08-16 02:45:20.029 24655 24655 D BreventServer: check and brevent, took 870ms
08-16 02:45:23.130 24655 24655 D BreventServer: check and brevent
08-16 02:45:24.120 24655 24655 W BreventServer: com.litesuits.control has foreground service, but without notification
08-16 02:45:24.126 24655 24655 D BreventServer: check again in 1272s
08-16 02:45:24.126 24655 24655 D BreventServer: check and brevent, took 993ms
08-16 02:45:24.127 24655 24655 D BreventServer: update current to com.eg.android.AlipayGphone
08-16 02:45:24.127 24655 24655 D BreventServer: previous: me.piebridge.brevent, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.128 24655 24655 D BreventServer: classname: com.alipay.mobile.quinox.LauncherActivity.alias
08-16 02:45:24.130 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.130 24655 24655 D BreventServer: classname: com.alipay.mobile.quinox.LauncherActivity
08-16 02:45:24.131 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.131 24655 24655 D BreventServer: classname: com.alipay.mobile.scan.as.router.CodeRouteActivity
08-16 02:45:24.414 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.414 24655 24655 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFQueryReceiveInfoActivity_
08-16 02:45:24.806 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:24.806 24655 24655 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFToAccountConfirmActivity_
08-16 02:45:31.917 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:31.917 24655 24655 D BreventServer: classname: com.alipay.mobile.bill.list.ui.ObjectSetActivity_
08-16 02:45:33.002 24655 24655 D BreventServer: doRefreshAccessibility
08-16 02:45:33.067 24655 24655 D BreventServer: name: 黑域()
08-16 02:45:33.078 24655 24655 D BreventServer: account: pr**@piebridge.me
08-16 02:45:33.088 24655 24655 I BreventServer: bill:   月 支出: 收入:
08-16 02:45:33.993 24655 24655 D BreventServer: doRefreshAccessibility
08-16 02:45:34.030 24655 24655 D BreventServer: name: 黑域()
08-16 02:45:34.035 24655 24655 D BreventServer: account: pr**@piebridge.me
08-16 02:45:34.039 24655 24655 I BreventServer: bill: 月 支出: 收入:
08-16 02:45:34.476 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:34.476 24655 24655 D BreventServer: classname: com.alipay.mobile.transferapp.ui.TFToAccountConfirmActivity_
08-16 02:45:34.980 24655 24655 D BreventServer: doRefreshAccessibility
08-16 02:45:35.276 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: com.eg.android.AlipayGphone
08-16 02:45:35.276 24655 24655 D BreventServer: classname: com.eg.android.AlipayGphone.AlipayLogin
08-16 02:45:37.962 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:37.965 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:37.965 24655 24655 D BreventServer: update current to me.piebridge.brevent
08-16 02:45:37.965 24655 24655 D BreventServer: previous: com.eg.android.AlipayGphone, packageName: me.piebridge.brevent
08-16 02:45:40.066 24655 24655 D BreventServer: get service: deviceidle
08-16 02:45:40.067 15906 15906 D BreventUI: onActivityResult
08-16 02:45:40.071 24655 24655 I BreventServer: make brevent tempwhitelist
08-16 02:45:40.071 24655 24655 D BreventServer: previous: me.piebridge.brevent, packageName: me.piebridge.brevent
08-16 02:45:40.080 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:40.081 15906 29970 D BreventUI: request status
08-16 02:45:40.089 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:40.148 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:40.152 24655 24673 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-16 02:45:40.422 15906 29970 D BreventUI: setAlarm
08-16 02:45:40.432 15906 15943 V BreventUI: connected to localhost: 59526
08-16 02:45:40.545 24655 24673 D BreventServer: get service: deviceidle
08-16 02:45:40.547 24655 24673 I BreventServer: make brevent tempwhitelist
08-16 02:45:43.567 15906 29970 D BreventUI: logcat for system.txt
08-16 02:45:43.783 15906 29970 D BreventUI: logcat for events.txt
08-16 02:45:43.872 15906 29970 D BreventUI: logcat for brevent.txt

**Comment by liudongmiao** [comment]
1. 故意多弹

2. 不可用时，自动重启
```
08-16 01:37:28.609 5769 5769 W BreventServer: Can't startAccessibility
08-16 01:37:28.609 5769 5769 W BreventServer: Can't cancelAccessibility
08-16 01:37:28.903 9355 9355 D BreventLoader: worker 5769 exited with status 0
```

3. 这个东西，与功能无关，目标只有一个，识别...
能识别了，不用管体验...

**Comment by CVN-77** [comment]
关于第一个，是转账记录→账单详情→查看往来记录→返回账单详情→返回转账记录后，toast就一直弹。有时转账记录→账单详情→返回转账记录后，toast也长期霸屏。

知道是在多个界面都弹一次toast进行确认，只是感觉在多个界面已经看到toast了，返回到转账记录界面toast应该也是正常的弹一次就行，不必一直弹，我刚才又试了一下2.1.3还是这样，现在打字时toast还在……

**Comment by liudongmiao** [comment]
转账记录之后，就可以退回了嘛...因为可能有人会翻页，记录会变更，所以会多次提示，每次又是 3 秒。

后续会优化这里，但我真的没觉得有人会从这里点进去，比起不能识别来说，有个 toast 更好点。
