### ISSUE TITLE
使用root模式 重启几次后服务无法正常启动

### ISSUE THREAD

**Issue by jerry001100** [brevent/Brevent#240]
samsung/SC-05G/SC-05G:7.0/NRD90M/SC05GOMU1CQL2:user/release-keys

WARNING: linker: /data/local/tmp/brevent: unsupported flags DT_FLAGS_1=0x8000001
WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '01-31 15:14:14.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-31 15:14:14.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above
WARNING: linker: /data/local/tmp/brevent: unsupported flags DT_FLAGS_1=0x8000001
WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '01-31 15:14:15.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-31 15:14:15.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by jerry001100** [comment]
报错之后 开机黑域服务无法启动 root模式启用报错 用adb命令可以正常启动黑域服务

**Comment by liudongmiao** [comment]
自己清空数据吧…你 root 有毒，不执行指令。

**Comment by jerry001100** [comment]
用的magisk里带的supersu。xposed,solid explorer的root权限都正常
