### ISSUE TITLE
cant open after reboot

### ISSUE THREAD

**Issue by blood1995** [brevent/Brevent#242]
im using root heres the log

samsung/j2ltedtvdx/j2ltedtv:5.1.1/LMY47X/J200BTUBU2APK2:user/release-keys

WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xadc
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0x1
WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '02-04 06:51:55.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '02-04 06:51:55.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xadc
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0x1
WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '02-04 06:51:55.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '02-04 06:51:55.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
Clear data, it will return to root-adb mode.

**Comment by blood1995** [comment]
after i click to root mode its just blank not showing anything even logs

**Comment by liudongmiao** [comment]
You can turn on network adb via other Apps (as you have Root), then launch Brevent.

Brevent is not mainly for Root, and without logs, I cannot do anything.
