### ISSUE TITLE
最新motionelf.apk

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#243]
~删除日志~
最新版本 motionelf，不需要与黑域相结合。

**Comment by CVN-77** [comment]
状况和以前一样，重启后连接小游蓝灯闪烁，没有自动打开黑域，手动打开后激活成功

**Comment by liudongmiao** [comment]
1. 需要卸载原先版本

2. 安装以后，确保 motionelf 显示的 target sdk 为 23

**Comment by liudongmiao** [comment]
3. 整个过程不必打开黑域

**Comment by CVN-77** [comment]
原先版本不卸载没法安装新版的，我把隔壁的假冒飞智小游助手也删了。
目标sdk是23

**Comment by liudongmiao** [comment]
卸载，重新安装。

同时电脑上执行这个看看。

> adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server of=/data/local/tmp/motionelf_server

此外，你也可以卸载这个，安装隔壁的版本，不打开，直接执行这个看看输出异同。

**Comment by liudongmiao** [comment]
指令有误，已修改。

**Comment by CVN-77** [comment]
我重新卸载黑域重新安装试试

刚好身边没有电脑，尴尬…指令结果得等等…

**Comment by liudongmiao** [comment]
改成了 sdk 22，请再试。理论上 23 引入运行时权限，默认不给权限是 23 引入的。

**Comment by liudongmiao** [comment]
我刚在模拟器上试了，确实应该是 sdk 22 的版本。请重新下载。

**Comment by liudongmiao** [comment]
我看了下源码，是 android 7.X 引入的。

https://github.com/LineageOS/android_frameworks_native/blob/cm-14.1/cmds/installd/commands.cpp#L170

所以需要 target 24 以下。

**Comment by liudongmiao** [comment]
又更新了一版，版号号 0.3

**Comment by CVN-77** [comment]
刚到家，马上调试，上一个已经有成功情况，但成功率不高，有时可以有时不行

**Comment by CVN-77** [comment]
刚试了0.3，安装后插小游第一次没成功，和0.2.5（target sdk 22）遇到相同情况：确认usb调试后，自动打开黑域请启动画面，但服务没激活成功，画面长期定在请启动画面，此时蓝灯由疯狂闪烁变为慢闪，大概接近一秒一下

**Comment by CVN-77** [comment]
拔线后，第二次插小游激活成功，自动打开黑域，自动激活服务，蓝灯常亮

**Comment by CVN-77** [comment]
手机再一次重启，执行结果如下

C:\ADB>adb devices
List of devices attached
balabalabala        device


C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
dd: /data/data/com.game.motionelf/files/motionelf_server: Permission denied

C:\ADB>


而且这次重启后连接小游没反应了。。。

**Comment by CVN-77** [comment]
这时隔壁版本的执行指令情况（安装完后编辑脚本为 sh /data/local/tmp/brevent.sh，但没连接小游激活，编辑完后直接重启手机连电脑输出）
C:\ADB>adb devices
List of devices attached
blankblankblank        device


C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
1+1 records in
1+1 records out
613 bytes transferred in 0.003 secs (204333 bytes/sec)

C:\ADB>

ps：我的/data/local/tmp/目录下很早就放了一个brevent.sh

**Comment by liudongmiao** [comment]
根据源码 sdk 23 以下就可以。稍后我各个 target 都放下。

**Comment by CVN-77** [comment]
0.3其实几乎成功了，重启手机插小游确认调试后，看到有飞智黑域厅弹出，接着黑域被打开。但不知为何，画面就定在了请启动服务界面，小游蓝灯由快闪变成慢闪，但还是一直闪，服务也没激活成功，感觉就差一点，不知道哪里出了问题

**Comment by CVN-77** [comment]
这个蓝灯快闪变慢闪很奇怪

**Comment by CVN-77** [comment]
现在0.3版本执行adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server of=/data/local/tmp/motionelf_server又有结果了
C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
2+1 records in
2+1 records out
1202 bytes transferred in 0.001 secs (1202000 bytes/sec)

但奇怪的是，现在插小游又没反应了，确认后没动静（黑域还没激活）

**Comment by liudongmiao** [comment]
根据  sdk 23, 22, 21
1. 卸载现在
2. 安装新版 
3. 执行 adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server 
期望，提示 "No such file or directory"
如果任何一个不提示 "No such file or directory"，即为失败。

提示这个以后，就可以给小游供电，插手机了。
现在成功以后才会打开黑域。

**Comment by CVN-77** [comment]
motionelf sdk 23版
卸载旧版安装新版后执行命令，提示 "No such file or directory"
（1）第一次插小游，蓝灯快闪变慢闪，飞智黑域厅一闪而过，没打开黑域，没有激活成功
（2）拔线重插，，无反应。此后反复拔线重插，确认调试后均无反应
手机重启后，情况同（2），怎么拔线重插确认调试后都无反应

motionelf sdk 22版
卸载旧版安装新版后执行命令，提示 "No such file or directory"
（1）第一次插小游，蓝灯快闪变慢闪，飞智黑域厅一闪而过，没打开黑域，没有激活成功
（2）拔线重插，激活成功。
手机重启确认调试后，有时同（1）（2），有时无反应（遇到无反应后怎么拔插都是无反应），有时飞智黑域厅一闪而过没打开黑域，蓝灯常亮，但拔线后打开黑域没激活。。
重启后各种情况都有


motionelf sdk 21版
卸载旧版安装新版后执行命令，提示 "No such file or directory"
（1）第一次插小游，蓝灯快闪变慢闪，飞智黑域厅一闪而过，没打开黑域，没有激活成功
（2）拔线重插，无反应。此后反复拔线重插，确认调试后均无反应
手机重启后，情况同（2），怎么拔线重插确认调试后都无反应

**Comment by CVN-77** [comment]
好像我这target sdk22的版本成功率相对其他两个高些，但成功率还是不大，重启后还是遇到各种情况没激活成功，而且找不到稳定重现的方法。唯一稳定重现的就是第一次插小游，蓝灯快闪变慢闪，这个情况3个版本都遇上了

**Comment by liudongmiao** [comment]
只要提示这个就是正常的，其他未知，我本地多个测试机都正常。现在版本，就是假冒版本一闪而过，激活成功再打开黑域。

**Comment by liudongmiao** [comment]
我弄了个最终版，打开以后，不会一闪而过（相当于流氓...）。

灯的变化：

1. 红灯快闪，蓝灯不亮：没有接接手机
2. 红灯常亮，蓝灯不亮：已经连接手机，没有开启调试
3. 红灯常亮，蓝灯快闪：没有确认密钥
4. 红灯常亮，蓝灯慢闪：正在执行脚本
5. 红灯常亮，蓝灯常亮：执行脚本完成
到于蓝灯常亮，但黑域没有激活成功，可能是指令问题？

首次激活，文件没有释放，可能会出现第 4 种情况。
在我本地，pixel 上之前版本由于生成文件太慢，小游 dd 时文件还没有，就出现第 4 种情况。
目前判断 黑域 脚本是否存在，存在就直接使用。

你先看看，如果第 4 种情况频繁出现，就告诉我好了。

**Comment by CVN-77** [comment]
0.4版本，连接后确实没有一闪而过，首次激活出现第4种情况，应该是生成文件慢。

但再次重启后就出现无反应，此后反复重启拔线重插，确认调试后均无反应，蓝灯快闪。USB线也换了好几条都这样，难道是重启后无法执行脚本...

**Comment by liudongmiao** [comment]
重启后，你可以电脑上运行这个看看。

> adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server of=/data/local/tmp/motionelf_server

看看提示。

**Comment by liudongmiao** [comment]
其实这个文件生成非常快，大约  0.5 秒不到。

**Comment by liudongmiao** [comment]
不过吧，确实有一个小小的可以优化的地方。

**Comment by liudongmiao** [comment]
你再找看看，有一个 repack 的版本，我反编译后改的。

**Comment by CVN-77** [comment]
0.4版本
首次安装激活，蓝灯慢闪后，
C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
2+1 records in
2+1 records out
1279 bytes transferred in 0.001 secs (1279000 bytes/sec)

重启后（连接小游前）运行结果为
C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
dd: /data/data/com.game.motionelf/files/motionelf_server: Permission denied

**Comment by CVN-77** [comment]
0.4 repack 版本
首次安装激活时也是蓝灯慢闪，然后连电脑执行结果也是
2+1 records in
2+1 records out

重启后连接小游前运行结果也是
dd: /data/data/com.game.motionelf/files/motionelf_server: Permission denied

插小游后，蓝灯慢闪，重新拔插，蓝灯瞬间常亮，过2到3秒黑域自动打开进入列表，激活成功。

第一次插小游蓝灯慢闪后，第二次插小游前，连电脑执行结果
C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
2+1 records in
2+1 records out
1279 bytes transferred in 0.001 secs (1279000 bytes/sec)

更新：蓝灯常亮后，得过1到6秒才会自动打开黑域，有时很快有时慢

**Comment by CVN-77** [comment]
重启了几次，0.4 repack 版本的情况基本都稳定重现（需插两次小游）：
（1）重启后第一次插小游蓝灯慢闪
（2）重新拔插蓝灯常亮，激活成功

**Comment by CVN-77** [comment]
用0.4 repack版又重启了一次，遇到一个新问题（请启动画面疯狂闪烁）：
这次重启插小游蓝灯瞬间常亮，但黑域长时间没有自动打开。拔线后，手动打开黑域，请启动画面疯狂闪烁，home到后台后，有时过一会会自动弹出黑域（还是请启动画面疯狂闪烁），划掉卡片强行停止再打开，还是请启动画面疯狂闪烁

再次插小游才重新激活成功，黑域自动打开进入列表。

**Comment by CVN-77** [comment]
0.4 repack 版本 重启后插小游蓝灯瞬间常亮，但黑域长时间没有自动打开。

这种情况在插小游前的执行结果为（重启后直接连电脑执行）：
C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
0+1 records in
0+1 records out
168 bytes transferred in 0.001 secs (168000 bytes/sec)

第一次插小游蓝灯慢闪后，第二次插小游前，连电脑执行结果
C:\ADB>adb -d shell dd if=/data/data/com.game.motionelf/files/motionelf_server o
f=/data/local/tmp/motionelf_server
2+1 records in
2+1 records out
1279 bytes transferred in 0.001 secs (1279000 bytes/sec)

第二次都插都能激活成功，自动打开黑域。

**Comment by CVN-77** [comment]
这个请启动画面闪烁应该是飞智黑域厅在不断尝试激活黑域，不知道在哪里卡住了。
刚又重启了一次，这次重启后连接电脑执行结果也是0+1 records in out，没有连接小游，手动打开黑域，请启动画面闪烁。（但也由于手动打开了黑域，第一次插小游直接就激活成功自动打开列表）

**Comment by liudongmiao** [comment]
发了个 0.5，请重新看看。

除首次需要重新插拔以外，如果其它场景无法激活，请帮忙电脑上执行这个指令，然后给出结果，谢谢。

 > adb shell stat /data/data/com.game.motionelf/files/motionelf_server /data/data/com.game.motionelf/files /data/data/com.game.motionelf

**Comment by liudongmiao** [comment]
0.5 起，放弃任何尝试，直接把以下内容，写入 motionelf_server:

```bash
#!/system/bin/sh

path=/data/data/me.piebridge.brevent/brevent.sh
comp=me.piebridge.brevent/.ui.BreventActivity

if [ ! -r $path ]; then
    am start -n $comp
    sleep 3
fi

sh $path

if [ $? -eq 0 ]; then
    am start -n $comp
fi
```

**Comment by CVN-77** [comment]
0.5版本除首次需要插两次激活外，其他场景基本能实现主功能了。

在安装0.5版本首次插小游需要插两次才激活服务后，手机直接重启、激活后清除黑域应用数据、清除数据后重启，卸载黑域重新安装，这几种分别试过，都能做到只需插一次小游就激活

不过这个版本还是有请启动画面疯狂闪烁的情况，特别是重新安装黑域后的激活每次都闪，重启后闪的次数少些但还是闪。就是插小游确认调试后，黑域自动打开，在请启动界面闪烁好几次（多的时候有10几次）才进入列表。闪的频率有时快有时慢，我看到请启动疯狂闪的时候都不敢拔线，等它自己进入列表后才放心。

这个黑域服务激活成功的时间点不确定是蓝灯常亮后就已完成，还是以进入列表为准。感觉是蓝灯常亮的话应该是已激活完成。但这个每次情况又不完全一样，有时请启动疯狂闪的时候蓝灯也在狂闪，有时一插小游蓝灯很快就常亮了，但请启动画面仍在疯狂闪几次。

**Comment by CVN-77** [comment]
刚又试了一下，插小游确认调试后，蓝灯变常亮，这时不管自动打开正在狂闪的黑域，直接拔线，黑域请启动画面闪了几秒，也进入列表了。

**Comment by liudongmiao** [comment]
黑域启动闪是因为做了兼容性支持，beta 版将会去掉。
常亮就可以拔线了，表明在执行最后一个脚本，不出意外就会成功。

你还可以清空 假冒飞智游戏厅 与 黑域数据，什么也不要打开，看看情况。
理论上的话，需要两次插拔硬件（含首次生成 小游 文件），不需要直接打开黑域就可以激活。

**Comment by CVN-77** [comment]
试了一次清空飞智黑域厅 与 黑域数据，什么也不要打开，情况确实如你所述。

第一次插小游确认调试后都是蓝灯慢闪 。在第一次插小游前，执行结果为
C:\ADB\platform-tools>adb shell stat /data/data/com.game.motionelf/files/motione
lf_server /data/data/com.game.motionelf/files /data/data/com.game.motionelf
stat: '/data/data/com.game.motionelf/files/motionelf_server': No such file or di
rectory
stat: '/data/data/com.game.motionelf/files': No such file or directory
  File: `/data/data/com.game.motionelf'
  Size: 4096     Blocks: 8       IO Blocks: 4096        directory
Device: fd05h/64773d     Inode: 6127846  Links: 2
Access: (751/drwxr-x--x)        Uid: (10999/ u0_a999)   Gid: (10999/ u0_a999)
Access: 2018-02-06 17:25:20.309999887
Modify: 2018-02-06 17:27:13.299999870
Change: 2018-02-06 17:27:13.299999870

文件还没有生成，好像如果这样的话第一次插小游蓝灯就会慢闪

第一次插小游后，第二次插小游前，执行结果为
C:\ADB\platform-tools>adb shell stat /data/data/com.game.motionelf/files/motione
lf_server /data/data/com.game.motionelf/files /data/data/com.game.motionelf
  File: `/data/data/com.game.motionelf/files/motionelf_server'
  Size: 232      Blocks: 8       IO Blocks: 4096        regular file
Device: fd05h/64773d     Inode: 6373401  Links: 1
Access: (644/-rw-r--r--)        Uid: (10999/ u0_a999)   Gid: (10999/ u0_a999)
Access: 2018-02-06 17:32:06.479999825
Modify: 2018-02-06 17:32:06.479999825
Change: 2018-02-06 17:32:06.479999825
  File: `/data/data/com.game.motionelf/files'
  Size: 4096     Blocks: 8       IO Blocks: 4096        directory
Device: fd05h/64773d     Inode: 6373400  Links: 2
Access: (771/drwxrwx--x)        Uid: (10999/ u0_a999)   Gid: (10999/ u0_a999)
Access: 2018-02-06 17:32:06.479999825
Modify: 2018-02-06 17:32:06.479999825
Change: 2018-02-06 17:32:06.479999825
  File: `/data/data/com.game.motionelf'
  Size: 4096     Blocks: 8       IO Blocks: 4096        directory
Device: fd05h/64773d     Inode: 6127846  Links: 4
Access: (751/drwxr-x--x)        Uid: (10999/ u0_a999)   Gid: (10999/ u0_a999)
Access: 2018-02-06 17:25:20.309999887
Modify: 2018-02-06 17:32:06.479999825
Change: 2018-02-06 17:32:06.479999825

文件生成后就只需插一次了

**Comment by liudongmiao** [comment]
隔壁版本，因为你打开应用，生成了文件，所以看起来只需要插入一回。

**Comment by liudongmiao** [comment]
看看最新 beta 版 2.6.8，应该不会再闪来闪去了。

**Comment by CVN-77** [comment]
2.6.8版本情况好许多了。插上小游确认调试后，蓝灯常亮，自动打开黑域请启动画面，闪一下然后画面定住，过了几秒钟后就进入列表。
这个请启动画面最多再闪一次，就是先闪一下定住，再闪一下定住，然后就进入列表。

**Comment by liudongmiao** [comment]
你可以这样，重启，黑域会出现“黑域没有启动”提示（请 系统 中允许黑域自启）。
这时，插入非定制版小游，常亮后会进入黑域；
定制版小游，激活成功后，通知会去掉，不会进入黑域。

**Comment by CVN-77** [comment]
这个通知条我知道的，重启后都有通知条，我在系统对黑域设置了 允许自启，锁屏后不清理，后台卡片加锁。（这几个也是自我诊断需要的，允许后台运行）

现在重启后插小游蓝灯很快常亮（这时也可以即刻拔线了），黑域自动打开，就是这个请启动画面定格的时间有时有点长，要五六秒才刷进去，有时又不慢，三秒左右就刷进去，不知道是不是和手机重启后插小游的时间，或者手机运行速度有关…因为有时刚重启，我在手机还有点小卡，一些自启应用还没出现时，马上就插小游）

还有蓝灯常亮是不是仅代表执行完了激活命令，之后请启动定格是不是在检查黑域服务的情况，确认彻底激活成功之后才进去？好像以前连电脑激活输完命令回车后，也得等一小会才出结果。
