### ISSUE TITLE
最新beta版无法选择应用进入黑域列表

### ISSUE THREAD

**Issue by naloder** [brevent/Brevent#244]
(如题)

**Comment by liudongmiao** [comment]
点击图标即可。

很多人可能喜欢打开上下文菜单来选择应用。
但是，我一直推荐的是，点击图标。
当我想要加入更多选项的时候，发现这个选择其实不好。
因为点击图标更快，点击图标，点菜单还可以反选。

**Comment by naloder** [comment]
soga，看来是更好的选择了╮(╯▽╰)╭
