### ISSUE TITLE
Samsung Galaxy S4

### ISSUE THREAD

**Issue by xiaojimo** [brevent/Brevent#246]
Verizon/jfltevzw/jfltevzw:5.0.1/LRX22C/I545VRSGPL1:user/release-keys

WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '02-06 15:23:36.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '02-06 15:23:36.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above
WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '02-06 15:23:36.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '02-06 15:23:36.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
黑域目前尝试 Root 开启 adb 启动，失败后尝试直接 Root 启动。
但是你的 Root 开启 adb 后，adb 连接以后，还是 Root，请与 Root 提供商联系。

另外，你的 Rom 限制，无法使用 popen / system / execvp 指令，请报告给你的 Root 提供商。
末了，还是想说，黑域并不需要 Root；同时，Root 也并不拥有所有权限，特别在黑域这里。
