### ISSUE TITLE
设置中新加入的功能的滑钮没有动画

### ISSUE THREAD

**Issue by sjdhome** [brevent/Brevent#247]
像“自动更新”这种点击之后会有滑钮滑动的动画，而新加入的如“应用权限”这种点击之后则没有动画。希望能修改。

**Comment by liudongmiao** [comment]
完全不懂…录个视频看看？
这两个~~空间~~控件几乎完全一样。

**Comment by sjdhome** [comment]
![-2018-02-07-11-02-19](https://user-images.githubusercontent.com/11871061/35896372-cdab27b4-0bf6-11e8-9f12-924aaa9272e6.gif)

**Comment by liudongmiao** [comment]
你的图片看起来确实有一点点差别，但我本地没有。

这样吧，你直接使用 自我诊断 与 应用权限 对比吧，这两个挨得近。
除了 建议支付 与 需要支付 控件，其它的开关，都使用同一个控件。
建议支付 与 需要支付 控件，基于其它开关使用的控件，只是动态调整了提示语而已。

**Comment by sjdhome** [comment]
的确有差别
![-2018-02-07-12-55-20](https://user-images.githubusercontent.com/11871061/35899288-7ca4fd76-0c06-11e8-935a-f567ca40c27d.gif)

**Comment by sjdhome** [comment]
附一张关于手机截图
![screenshot_20180207-125828](https://user-images.githubusercontent.com/11871061/35899327-b410f396-0c06-11e8-9390-63b35fca0c29.png)

**Comment by liudongmiao** [comment]
我回去看下 lineage os 测试机。
但我只能看看，如果能重现，就修复；如果不能，就只能这样了。

**Comment by liudongmiao** [comment]
感谢报告，已经确认，将在下个版本中修复。

**Comment by sjdhome** [comment]
谢谢大佬

**Comment by liudongmiao** [comment]
已发布 beta 版，请前住下载测试。

**Comment by sjdhome** [comment]
已经完美修复

**Comment by liudongmiao** [comment]
请发个邮件获取特别贡献优惠。

其实看起来完美，但实现并不完美，甚至比较 ugly。
