### ISSUE TITLE
Google Play的beta2.7

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#249]
~~删除与未公开文档相关的操作~~

**Comment by liudongmiao** [comment]
1. 仅仅是支付确认，没有提及支付
根据 play 规则，不可以支付，但是，没有说不能确认支付。

2. play 版没有任何公开文档提及这点

此外，可以参照这条：

> 开发者如果要在通过 Google Play 下载的其他类别的应用内出售商品，则必须采用 Google Play 应用内购买结算收费，但以下情况除外：
>    - 收费内容涉及可在应用本身以外的环境中使用的数字内容（例如可在其他音乐播放器上播放的歌曲）。

提供的支付宝帐号，不仅适用于黑域应用，还适用于我本人名下所有应用。

如果你认为违反 play 开发者政策，请向 play 举报。
https://play.google.com/intl/zh-CN/about/monetization-ads/

**Comment by GithubApkUser** [comment]
了解了

**Comment by liudongmiao** [comment]
另外，我也正在就这个问题，直接咨询 Google。

**Comment by liudongmiao** [comment]
Google ~~没有明确回复，只是提到~~回复不支持 先安装其它版本，再在 play 商店升级，这种行为属于 未定义。
为安全起见，正式版本将去除这项隐藏功能。
