### ISSUE TITLE
这里好像有个bug

### ISSUE THREAD

**Issue by quan901** [brevent/Brevent#25]
![_20170816103251](https://user-images.githubusercontent.com/16775637/29345243-f856a670-826f-11e7-8553-16fe00100bf9.png)
![image](https://user-images.githubusercontent.com/16775637/29345246-020f9190-8270-11e7-929f-7e3ea8172506.png)

**Comment by vvb2060** [comment]
用最新版看看提示吧

**Comment by quan901** [comment]
这是2.1.2社区版，应该是最新版了吧

**Comment by vvb2060** [comment]
不对旧版提供支持，不对社区版提供支持。

**Comment by liyufan** [comment]
我突然想起来，这个地方的英文提示语我没更新。。。

**Comment by liudongmiao** [comment]
没有事件日志，这个问题很难解决。

看看最新版的提示，也只是更新了下描述。总的来说，你要解决这个问题。

当然，有可能是 suhide 的问题，目前已经解决了。可能是其它问题，描述已经更新。

**Comment by liudongmiao** [comment]
@quan901 
描述性的话语：https://github.com/brevent/Brevent/blob/master/brevent/src/main/res/values-zh-rCN/strings.xml#L191

suhide 相关的已经修复：https://github.com/brevent/Brevent/commit/cb590a5c2ebb12032226932454e9c21f30b7d59e

使用一个旧版提问题，确实不妥。
