### ISSUE TITLE
黑域1.2版本（非play版本）每次进入都需要重新获取程序信息

### ISSUE THREAD

**Issue by gjhwssg** [brevent/Brevent#25]
步骤如下：
①打开 黑域（已用adb命令开启，root模式现象相同） 显示 【获取程序信息】进度如下图
![image](https://cloud.githubusercontent.com/assets/4454357/26617140/fea039b6-4605-11e7-8582-dd61acb7f56c.png)
②载入完成后，按【home】键回到主页，再次打开黑域，正常进入，无【获取程序信息】进度。
③按【back】键退出黑域，再次打开黑域，再次显示 【获取程序信息】进度。
④重复③步骤，依然如此。

此现象发生时全新安装1.2版本黑域软件，未进行任何设置的更改，**未把黑域app 自身加入黑域列表**
之前1.1.10版本无此问题（除了首次安装启动，需要【获取程序信息】，之后都是瞬间完成）

系统信息如下：
![image](https://cloud.githubusercontent.com/assets/4454357/26617294/f2deb8cc-4606-11e7-84a5-b265ebd00457.png)

log如下：

> PS D:\Flashtool\x10flasher_lib> ./adb -d logcat -d -b main -s BreventServer BreventLoader
05-31 13:04:20.983 15716 15716 D BreventServer: handle event am_proc_start(1)
05-31 13:04:25.866 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:04:34.185 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:04:52.919 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:05:14.647 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:05:14.647 15716 15716 D BreventServer: pause activity, tid: 8367, packageName: pl.solidexplorer2
05-31 13:05:14.674 15716 15716 D BreventServer: handle event am_restart_activity(10)
05-31 13:05:14.674 15716 15716 D BreventServer: resume activity, tid: 8372, packageName: pl.solidexplorer2, launcher: com.teslacoilsw.launcher
05-31 13:05:18.704 15716 15716 D BreventServer: handle message: check(6)
05-31 13:05:18.704 15716 15716 D BreventServer: check and brevent
05-31 13:05:19.343 15716 15716 D BreventServer: widgets: {com.google.android.calendar, com.sonymobile.xperiaweather, com.sonyericsson.music, com.google.android.keep}
05-31 13:05:19.343 15716 15716 D BreventServer: running: {com.android.vending=1082, pl.solidexplorer2=1219}
05-31 13:05:19.343 15716 15716 D BreventServer: recent: {com.android.vending=3462, com.tencent.mm=1233, me.piebridge.brevent=3534, com.android.chrome=2216, com.coolapk.market=1369, pl.solidexplorer2=3600, com.fastaccess.github=1686}
05-31 13:05:19.447 15716 15716 D BreventServer: com.google.android.webview depended by {com.android.vending}
05-31 13:05:19.447 15716 15716 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify, com.sonymobile.lifelog, com.android.vending, com.google.android.apps.maps, com.sonymobile.email, com.codium.hydrocoach.pro}
05-31 13:05:19.447 15716 15716 D BreventServer: top: {pl.solidexplorer2}
05-31 13:05:19.447 15716 15716 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
05-31 13:05:19.447 15716 15716 D BreventServer: current: pl.solidexplorer2
05-31 13:05:19.447 15716 15716 D BreventServer: notifications: {com.github.shadowsocks=[98], com.sonymobile.lifelog=[114]}
05-31 13:05:19.448 15716 15716 D BreventServer: check again in 3600s
05-31 13:05:19.448 15716 15716 D BreventServer: check and brevent, took 743ms
05-31 13:05:19.448 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:05:19.448 15716 15716 D BreventServer: pause activity, tid: 7763, packageName: pl.solidexplorer2
05-31 13:05:19.448 15716 15716 D BreventServer: handle event am_resume_activity(2)
05-31 13:05:19.448 15716 15716 D BreventServer: resume activity, tid: 8362, packageName: pl.solidexplorer2, launcher: com.teslacoilsw.launcher
05-31 13:05:32.289 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:05:53.661 15716 15716 D BreventServer: handle event am_new_intent(8)
05-31 13:05:53.666 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:05:53.666 15716 15716 D BreventServer: pause activity, tid: 8095, packageName: pl.solidexplorer2
05-31 13:05:53.709 15716 15716 D BreventServer: handle event am_resume_activity(2)
05-31 13:05:53.709 15716 15716 D BreventServer: resume activity, tid: 8095, packageName: com.android.systemui, launcher: com.teslacoilsw.launcher
05-31 13:05:53.709 15716 15716 D BreventServer: update current to com.android.systemui
05-31 13:05:55.023 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:05:55.023 15716 15716 D BreventServer: pause activity, tid: 7763, packageName: com.android.systemui
05-31 13:05:55.075 15716 15716 D BreventServer: handle event am_resume_activity(2)
05-31 13:05:55.075 15716 15716 D BreventServer: resume activity, tid: 8372, packageName: com.android.vending, launcher: com.teslacoilsw.launcher
05-31 13:05:55.075 15716 15716 D BreventServer: update current to com.android.vending
05-31 13:06:07.630 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:06:43.962 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:06:53.721 15716 15716 D BreventServer: handle message: check(6)
05-31 13:06:53.721 15716 15716 D BreventServer: check and brevent
05-31 13:06:54.430 15716 15716 D BreventServer: widgets: {com.google.android.calendar, com.sonymobile.xperiaweather, com.sonyericsson.music, com.google.android.keep}
05-31 13:06:54.430 15716 15716 D BreventServer: running: {com.android.vending=1255, pl.solidexplorer2=1254}
05-31 13:06:54.431 15716 15716 D BreventServer: recent: {com.android.vending=3541, com.tencent.mm=1138, me.piebridge.brevent=3439, com.android.chrome=2121, com.coolapk.market=1274, pl.solidexplorer2=3539, com.fastaccess.github=1591}
05-31 13:06:54.525 15716 15716 D BreventServer: com.google.android.webview depended by {com.android.vending}
05-31 13:06:54.525 15716 15716 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify, com.sonymobile.lifelog, com.android.vending, com.google.android.apps.maps, com.sonymobile.email, com.codium.hydrocoach.pro}
05-31 13:06:54.526 15716 15716 D BreventServer: top: {com.android.vending}
05-31 13:06:54.526 15716 15716 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
05-31 13:06:54.526 15716 15716 D BreventServer: current: com.android.vending
05-31 13:06:54.526 15716 15716 D BreventServer: notifications: {com.github.shadowsocks=[98], com.sonymobile.lifelog=[114]}
05-31 13:06:54.528 15716 15716 D BreventServer: check again in 3600s
05-31 13:06:54.528 15716 15716 D BreventServer: check and brevent, took 805ms
05-31 13:06:55.528 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:06:55.530 15716 15716 D BreventServer: pause activity, tid: 4055, packageName: com.android.vending
05-31 13:06:55.640 15716 15716 D BreventServer: handle event screen_toggled(5)
05-31 13:06:57.643 15716 15716 D BreventServer: handle message: check(6)
05-31 13:06:57.643 15716 15716 D BreventServer: check and brevent
05-31 13:06:58.999 15716 15716 D BreventServer: widgets: {com.google.android.calendar, com.sonymobile.xperiaweather, com.sonyericsson.music, com.google.android.keep}
05-31 13:06:58.999 15716 15716 D BreventServer: running: {com.android.vending=1315, pl.solidexplorer2=1253}
05-31 13:06:58.999 15716 15716 D BreventServer: recent: {com.android.vending=3597, com.tencent.mm=1134, me.piebridge.brevent=3435, com.android.chrome=2117, com.coolapk.market=1270, pl.solidexplorer2=3535, com.fastaccess.github=1587}
05-31 13:06:59.101 15716 15716 D BreventServer: com.google.android.webview depended by {com.android.vending}
05-31 13:06:59.101 15716 15716 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify, com.sonymobile.lifelog, com.android.vending, com.google.android.apps.maps, com.sonymobile.email, com.codium.hydrocoach.pro}
05-31 13:06:59.102 15716 15716 D BreventServer: top: {com.android.vending}
05-31 13:06:59.102 15716 15716 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
05-31 13:06:59.102 15716 15716 D BreventServer: current: com.android.vending
05-31 13:06:59.102 15716 15716 D BreventServer: notifications: {com.github.shadowsocks=[98], com.sonymobile.lifelog=[114]}
05-31 13:06:59.104 15716 15716 D BreventServer: check again in 3600s
05-31 13:06:59.104 15716 15716 D BreventServer: check and brevent, took 1461ms
05-31 13:06:59.104 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:07:04.048 15716 15716 D BreventServer: handle event screen_toggled(5)
05-31 13:07:07.079 15716 15716 D BreventServer: handle event am_resume_activity(2)
05-31 13:07:07.079 15716 15716 D BreventServer: resume activity, tid: 8358, packageName: com.android.vending, launcher: com.teslacoilsw.launcher
05-31 13:07:16.801 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:07:26.049 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:07:26.050 15716 15716 D BreventServer: pause activity, tid: 8362, packageName: com.android.vending
05-31 13:07:26.117 15716 15716 D BreventServer: handle event am_restart_activity(10)
05-31 13:07:26.117 15716 15716 D BreventServer: resume activity, tid: 8096, packageName: me.piebridge.brevent, launcher: com.teslacoilsw.launcher
05-31 13:07:26.117 15716 15716 D BreventServer: update current to me.piebridge.brevent
05-31 13:07:26.220 15716 15890 D BreventServer: request: version: 49, action: request
05-31 13:07:26.281 15716 15890 D BreventServer: checking feelgood
05-31 13:07:26.282 15716 15889 D BreventServer: received feelgood
05-31 13:07:26.376 15716 15890 D BreventServer: request: version: 49, action: configuration
05-31 13:07:33.477 15716 15716 D BreventServer: handle event am_proc_start(1)
05-31 13:07:33.528 15716 15716 D BreventServer: handle event am_proc_start(1)
05-31 13:07:45.820 15716 15716 D BreventServer: handle event am_proc_start(1)
05-31 13:07:48.824 15716 15716 D BreventServer: handle message: check(6)
05-31 13:07:48.824 15716 15716 D BreventServer: check and brevent
05-31 13:07:49.490 15716 15716 D BreventServer: widgets: {com.google.android.calendar, com.sonymobile.xperiaweather, com.sonyericsson.music, com.google.android.keep}
05-31 13:07:49.490 15716 15716 D BreventServer: running: {com.android.vending=1346, me.piebridge.brevent=1346, pl.solidexplorer2=1254}
05-31 13:07:49.490 15716 15716 D BreventServer: recent: {com.android.vending=3577, com.tencent.mm=1083, me.piebridge.brevent=3577, com.android.chrome=2066, com.coolapk.market=1219, pl.solidexplorer2=3484, com.fastaccess.github=1536}
05-31 13:07:49.511 15716 15716 D BreventServer: inactive for com.mobike.mobikeapp: 0, timeout: 60
05-31 13:07:49.581 15716 15716 D BreventServer: com.google.android.webview depended by {com.android.vending}
05-31 13:07:49.581 15716 15716 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify, com.sonymobile.lifelog, com.android.vending, com.sonymobile.email, com.codium.hydrocoach.pro}
05-31 13:07:49.581 15716 15716 D BreventServer: service: {com.mobike.mobikeapp}
05-31 13:07:49.581 15716 15716 D BreventServer: blocking: {com.mobike.mobikeapp}
05-31 13:07:49.581 15716 15716 D BreventServer: top: {me.piebridge.brevent}
05-31 13:07:49.581 15716 15716 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
05-31 13:07:49.581 15716 15716 D BreventServer: current: me.piebridge.brevent
05-31 13:07:49.581 15716 15716 D BreventServer: final blocking: {com.mobike.mobikeapp}
05-31 13:07:49.581 15716 15716 D BreventServer: notifications: {com.github.shadowsocks=[98], com.coderchoy.netspeed=[2], com.sonymobile.lifelog=[114], com.android.systemui=[16]}
05-31 13:07:49.581 15716 15716 D BreventServer: noRecent: {com.mobike.mobikeapp}
05-31 13:07:49.582 15716 15716 D BreventServer: full power list: {com.android.providers.downloads, com.tencent.mm, com.google.android.gms, com.google.android.wearable.app}
05-31 13:07:49.596 15716 15716 D BreventServer: Force stop com.mobike.mobikeapp(service)
05-31 13:07:49.601 15716 15716 D BreventServer: check again in 3600s
05-31 13:07:49.601 15716 15716 D BreventServer: check and brevent, took 776ms
05-31 13:07:49.615 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:07:53.716 15716 15716 D BreventServer: handle message: check changed(7)
05-31 13:07:54.598 15716 15716 D BreventServer: handle message: remove killed(11)
05-31 13:07:59.968 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:08:02.935 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:08:02.936 15716 15716 D BreventServer: pause activity, tid: 8096, packageName: me.piebridge.brevent
05-31 13:08:03.013 15716 15716 D BreventServer: handle event am_resume_activity(2)
05-31 13:08:03.013 15716 15716 D BreventServer: resume activity, tid: 7697, packageName: com.android.vending, launcher: com.teslacoilsw.launcher
05-31 13:08:03.013 15716 15716 D BreventServer: update current to com.android.vending
05-31 13:08:26.118 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:08:38.823 15716 15716 D BreventServer: handle event am_proc_start(1)
05-31 13:08:45.988 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:08:52.250 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:09:03.025 15716 15716 D BreventServer: handle message: check(6)
05-31 13:09:03.026 15716 15716 D BreventServer: check and brevent
05-31 13:09:03.782 15716 15716 D BreventServer: widgets: {com.google.android.calendar, com.sonymobile.xperiaweather, com.sonyericsson.music, com.google.android.keep}
05-31 13:09:03.783 15716 15716 D BreventServer: running: {com.android.vending=1383, pl.solidexplorer2=1253}
05-31 13:09:03.783 15716 15716 D BreventServer: recent: {com.android.vending=3539, com.tencent.mm=1009, me.piebridge.brevent=3539, com.android.chrome=1992, com.coolapk.market=1145, pl.solidexplorer2=3410, com.fastaccess.github=1462}
05-31 13:09:03.904 15716 15716 D BreventServer: com.google.android.webview depended by {com.android.vending}
05-31 13:09:03.904 15716 15716 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify, com.sonymobile.lifelog, com.android.vending, com.sonymobile.email, com.codium.hydrocoach.pro}
05-31 13:09:03.904 15716 15716 D BreventServer: top: {com.android.vending}
05-31 13:09:03.904 15716 15716 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
05-31 13:09:03.904 15716 15716 D BreventServer: current: com.android.vending
05-31 13:09:03.904 15716 15716 D BreventServer: notifications: {com.github.shadowsocks=[98], com.sonymobile.lifelog=[114], com.android.systemui=[16]}
05-31 13:09:03.995 15716 15716 D BreventServer: Force stop com.mobike.mobikeapp(previous running)
05-31 13:09:03.996 15716 15716 D BreventServer: check again in 3600s
05-31 13:09:03.996 15716 15716 D BreventServer: check and brevent, took 968ms
05-31 13:09:03.996 15716 15716 D BreventServer: handle event am_pause_activity(9)
05-31 13:09:03.996 15716 15716 D BreventServer: pause activity, tid: 4055, packageName: com.android.vending
05-31 13:09:03.996 15716 15716 D BreventServer: handle event screen_toggled(5)
05-31 13:09:04.015 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:09:04.333 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:09:05.998 15716 15716 D BreventServer: handle message: check(6)
05-31 13:09:05.998 15716 15716 D BreventServer: check and brevent
05-31 13:09:07.367 15716 15716 D BreventServer: widgets: {com.google.android.calendar, com.sonymobile.xperiaweather, com.sonyericsson.music, com.google.android.keep}
05-31 13:09:07.367 15716 15716 D BreventServer: running: {com.android.vending=1444, pl.solidexplorer2=1254}
05-31 13:09:07.367 15716 15716 D BreventServer: recent: {com.android.vending=3596, com.tencent.mm=1005, me.piebridge.brevent=3535, com.android.chrome=1988, com.coolapk.market=1141, pl.solidexplorer2=3406, com.fastaccess.github=1458}
05-31 13:09:07.450 15716 15716 D BreventServer: com.google.android.webview depended by {com.android.vending}
05-31 13:09:07.450 15716 15716 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify, com.sonymobile.lifelog, com.android.vending, com.sonymobile.email, com.codium.hydrocoach.pro}
05-31 13:09:07.450 15716 15716 D BreventServer: top: {com.android.vending}
05-31 13:09:07.450 15716 15716 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
05-31 13:09:07.450 15716 15716 D BreventServer: current: com.android.vending
05-31 13:09:07.450 15716 15716 D BreventServer: notifications: {com.github.shadowsocks=[98], com.sonymobile.lifelog=[114], com.android.systemui=[16]}
05-31 13:09:07.452 15716 15716 D BreventServer: check again in 3600s
05-31 13:09:07.453 15716 15716 D BreventServer: check and brevent, took 1454ms
05-31 13:09:08.113 15716 15716 D BreventServer: handle message: check changed(7)
05-31 13:09:08.998 15716 15716 D BreventServer: handle message: remove killed(11)
05-31 13:09:59.087 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:10:03.189 15716 15716 D BreventServer: handle message: check changed(7)
05-31 13:10:19.488 15716 15716 D BreventServer: handle event screen_toggled(5)
05-31 13:10:21.949 15716 15716 D BreventServer: handle event am_resume_activity(2)
05-31 13:10:21.949 15716 15716 D BreventServer: resume activity, tid: 4093, packageName: com.android.vending, launcher: com.teslacoilsw.launcher
05-31 13:10:28.148 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:10:50.012 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:11:03.633 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:11:17.239 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:11:43.109 15716 15716 D BreventServer: handle event notification_cancel_all(4)
05-31 13:12:21.468 15716 15716 D BreventServer: handle event am_proc_start(1)
05-31 13:12:28.754 15716 15716 D BreventServer: handle event notification_cancel_all(4)

**Comment by liudongmiao** [comment]
最新测试版应该修复了这个问题：https://piebridge.me/br/next/

主要是您的机器上，调用系统 api 时，返回黑域和框架签名一样。然后没有缓存。

**Comment by gjhwssg** [comment]
最新测试版可以解决这个问题，非常感谢~
