### ISSUE TITLE
No aggressive mode since 2.7

### ISSUE THREAD

**Issue by 1357209470** [brevent/Brevent#250]

**Comment by liudongmiao** [comment]
Aggressive mode contains two parts:
1. brevent more early.
It would break some apps, and I don't think brevent early have any actual benefits.

2. force-stop safe cached processes.
As it's safe, it's unnecessary.
If you just hate to see that Brevent shows it as running.
However, as it's name, it's safe.

激进模式包含两部分内容：
1. 更早黑域
但是，这会导致某些应用不可用，我个人不认为这样有任何实际好处。

2. 强行停止安全进程
都说了是安全了，完全没有必要。
如果你只是心里不爽，那我也没办法。
你不能因为你心里不爽，而要求我加上，让不需要的人不爽。

**Comment by 1357209470** [comment]
强迫症啊，看着难受，激进在使用上也没发现什么问题。还是希望大大您不要放弃激进模式啊～

**Comment by liudongmiao** [comment]
你不知道，为了解决你的强迫症，多少人得被强迫看这个选项，以及我本人被强迫维护这个选项？

**Comment by N0CANN0BB** [comment]
没人？

**Comment by vvb2060** [comment]
@SanmiaoF you can 👍 this issue, if over 100👍, aggresive mode will back.

**Comment by vongolaD1** [comment]
👍

**Comment by ghost** [comment]
hope to bring back the aggresive mode

**Comment by bhliupengfei** [comment]
我确定有些流氓因此管不住了

**Comment by liudongmiao** [comment]
在我多款设备，包括 pixel 上，没有什么问题。

**Comment by liudongmiao** [comment]
close it, as no body care in one month.
