### ISSUE TITLE
Brevent

### ISSUE THREAD

**Issue by nunomat** [brevent/Brevent#257]
There is something wrong with this version with the "ignore". Before i had all my apps brevent and allow sync and they delivered, but now after some time they stop and Stay stoped.

One question: Whats apps should i allow on battery otimization?

I've send it to you a few days ago a log file by email. (nunomatosphotography)

Thanks

**Comment by liudongmiao** [comment]
- allow sync apps can be "Stopped"
- Brevent is not releated to "battery optimization"
- logs without description will just be ignored
