### ISSUE TITLE
显示checking for stable.......timeout，一定几率不能正常使用，并且会经常自动重启

### ISSUE THREAD

**Issue by Endios24** [brevent/Brevent#258]
我看了其它的帖子的方法都没用，偶尔会显示success

**Comment by liudongmiao** [comment]
timeout 表示黑域已经成功，但是由于某种原因，黑域服务无法及时收到黑域请求。
一般属于本地网络原因等。

经常重启的话，请关闭检查通知，多出现在 三星 与 一加 机型。
