### ISSUE TITLE
已经再谷歌商店付款，但是

### ISSUE THREAD

**Issue by Johnduan02** [brevent/Brevent#259]
已经付款，信用卡都显示扣款成功，为何软件还是显示没有付款

**Comment by liudongmiao** [comment]
Play 支付使用 Google Play 标准 API，我本人没有什么好的办法。以下是一些可能的办法：
Play 支付的，请自备梯子到购买区，不要使用任何工具阻止黑域唤醒 Play 商店。
必要时，开启“显示支付”，或者卸载黑域，登录网页版 Play 商店下载到指定设备。

如果多次尝试还是无法识别，请直接退款。
24 小时内，可在 Play 商店中自主退款；超过 24 小时，黑域内点反馈，说明退款，带上订单号（非图片）。

**Comment by xiaobailong24** [comment]
请问多个设备，同一play账号需要多次购买吗？

**Comment by liudongmiao** [comment]
黑阈所有支付方式，只要确认以后，都不限设备。

**Comment by xiaobailong24** [comment]
好的，感谢。今天可以了，昨天还让我付款
