### ISSUE TITLE
收不到fcm

### ISSUE THREAD

**Issue by njzhenghao** [brevent/Brevent#26]
不知道怎么回事，一直用的play板，然后换成其他版也一样

问题:
比如inbox和Twitter等支持fcm的app，无法收到推送消息，必须打开app才会有消息，以前都有消息，现在不知哪个版本开始没有了，收邮件很麻烦

手机状态:
nexus 5x官方7。1。2root
所有系统应用和框架应用都没有黑域
黑域，ss，inbox，Twitter等需要fcm的软件都开了不进行电池优化，并且测试过，开不开黑域都无法接受消息，ss24小时挂着

求大佬指导

**Comment by liudongmiao** [comment]
那就不知道了…在我本地，最近 play console 有些不正常，消息有推送不到情况。由于网络环境、应用实现等问题，并不能确保一定可以。

这个问题无解。

你可以测试下，黑域内显示没有运行时，那几个应用是否还可以强行停止。

**Comment by njzhenghao** [comment]
好得，谢了

**Comment by njzhenghao** [comment]
不过我又测试了一下，卸载黑域之后，推送又正常了

**Comment by liudongmiao** [comment]
如果即使没有黑域某个应用，但是发现某个重要功能无法使用，请直接卸载即可。

虽然，黑域从不处理不在黑域清单应用。
