### ISSUE TITLE
魅族 S6 无法开启黑域服务

### ISSUE THREAD

**Issue by Bianca33** [brevent/Brevent#263]
[BreventLog.txt](https://github.com/brevent/Brevent/files/1751203/BreventLog.txt)
![tim 20180223173914](https://user-images.githubusercontent.com/36760735/36588633-ac5b3a7a-18c3-11e8-892e-c44e8c2265d9.png)

**Comment by liudongmiao** [comment]
这个问题看起来比较棘手，请发邮件给我，需要远程调试。

**Comment by liudongmiao** [comment]
邮箱：brevent@piebridge.me

**Comment by Bianca33** [comment]
已发邮件

**Comment by liudongmiao** [comment]
alpha 绕过式支持这款设备，也就直接关闭事件日志获取。
