### ISSUE TITLE
第三方Pixel Android8.1 启动后频繁弹出Google停止运行

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#264]
频繁启动失败！偶尔打开黑域，弹出启动黑域，我是以root方式启动的黑域，而且启动后把Google勾上，会经常Google停止运行，有一次崩溃记录

**Comment by ghost** [comment]
最严重导致pixel launcher被杀，不得不重启

**Comment by vvb2060** [comment]
启动黑域失败请提供弹窗显示的日志。如果黑域有意外行为也请点按日志按钮提供日志。
没有日志，无法处理。

**Comment by liudongmiao** [comment]
1. 最新 alpha 版：https://piebridge.me/br/alpha/

2. 没有日志，无法处理。如果是常态，早修了；如果非常态，你这么一说，我也不知道啊...

3. 第三方 Rom，Root 等的支持，优先级最低。黑域主要为非 Root 用户服务，我本人也不使用 Root。
