### ISSUE TITLE
关于Android6停用

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#265]
黑域基于简单极致的kiss原则，提倡免root也能使用，但是如果没root，Android6就用不了停用了，纠结！

能不能在没有root的Android6上用pm uninstall -k来停用，用pm install来启用，用appops来恢复权限，数据也不会丢失！效果和pm hide差不多，速度可能有些慢，但还是可以用滴！这样就不用装冰箱了！可不可行嘞？

**Comment by vvb2060** [comment]
卸载和安装是有广播的，会造成无法评估的影响。而且不少国产ROM会对命令安装进行拦截和提示。

**Comment by liudongmiao** [comment]
建议你了解一下，什么是 Play 商店所定义的恶意行为：https://play.google.com/intl/zh-CN_ALL/about/privacy-security-deception/malicious-behavior/

> 未经用户事先同意在设备上安装其他应用的应用。 

虽然你可能说，用户同意；但不论如何，它确实是真实的卸载与安装，只是可能保留了数据。
黑域为了简单极致，不会提供此种操作；这是也最近去掉 框架应用 识别的原因之一。

**Comment by liudongmiao** [comment]
讲真，Android 6 发布于 2015 年，你该升级了。
接下来，黑域会逐步移除不再支持的系统。
所有不再支持的系统，最后一个版本会去除所有支付提示及反馈渠道。

**Comment by GithubApkUser** [comment]
柳大，这个行为需要界定！冰箱使用的pm hide和pm unhide 实际上也属于卸载和安装啊，也是有广播的，它能在play商店上架，会不会说明没有问题啊

**Comment by liudongmiao** [comment]
有所为，有所不为，这是我的理念。
要不，你先去举报一下，比如 Play 版支持其它支付问题？
要不，你先去举报一下，各种应用不遵守的问题？
别人可以不遵守，不代表自己也要不遵守。

**Comment by liudongmiao** [comment]
@GithubApkUser 你看看 pm hide / pm unhide 是否可以？
可以的话，我考虑放开。

但是，5.X 绝对不会放开，因为运行时权限 6.X 才引入。

**Comment by vvb2060** [comment]
@liudongmiao  没有模拟器，翻了下代码，好像是因为冰箱是设备管理员才能用的
https://android.googlesource.com/platform/frameworks/base/+/android-cts-6.0_r26/core/java/android/content/pm/PackageUserState.java#31
更正：
https://android.googlesource.com/platform/frameworks/base/+/android-cts-6.0_r26/services/core/java/com/android/server/pm/PackageManagerService.java#9611
Android6时，shell有MANAGE_USERS权限，可以使用pm hide

**Comment by liudongmiao** [comment]
设备管理员 API，调用 pm hide / unhide 时是 system 身份，相当于中间来了一层转换。
但是，和 冰箱 作者交流以后，不应该提供。
一旦用户在低版本 hide 以后，升级到 7.X 及以上，是没有办法 unhide 的。
（虽然也存在升级 7.X 以后，用户 Root 失效，但这不是黑域支持场景。）
