### ISSUE TITLE
Google play 捐赠有bug

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#268]
柳大我想给黑域捐赠，但只能捐1二向箔，太少了，没有捐2二向箔3二向箔的选项，有问题！我想一次性捐2二向箔或3二向箔，强烈建议增加选项！

**Comment by liudongmiao** [comment]
你可以黑域多一点应用，开启建议支付的选项，达到建议支付数量；
否则，支付过的话，只补差价，新用户则会直接 3 二向箔。
