### ISSUE TITLE
黑域状态全部支持但是就是不会自动黑新安装应用

### ISSUE THREAD

**Issue by xu451271** [brevent/Brevent#269]
现在用的是lineage os `15.1的系统[](url)`
[logs-v2.9.3-20180305.1418.zip](https://github.com/brevent/Brevent/files/1779705/logs-v2.9.3-20180305.1418.zip)

**Comment by vvb2060** [comment]
确保 右上角菜单-设置-自动更新 为打开状态，安装一个新应用，等待20秒。没有弹出通知则点按右上角菜单-日志，将压缩包发上来。

**Comment by xu451271** [comment]
我把日志传上去了。。帮忙看下是啥情况

**Comment by vvb2060** [comment]
>BreventServer: support upgrade: false

你的自动更新应该是灰色的？其实共计六个支持状态，自动更新没有在下面又显示一遍而已。

**Comment by xu451271** [comment]
![Uploading Screenshot_黑域_20180305-163139.png…]()

**Comment by liudongmiao** [comment]
1. 检测结果：support upgrade: false

2. 目前没有任何相关日志 notification_cancel_all

3. 你可以这样测试

adb logcat -b events

然后安装应用，查看这个日志中是否有出现包名；如果没有，则不支持。
