### ISSUE TITLE
对于支付提示的一些建议

### ISSUE THREAD

**Issue by iwzh** [brevent/Brevent#27]
手机状态：
第一次安装新版黑域
手机有root权限

遇到问题：
前台没有提示支付启动root功能。
无法通过支付，自动root启动。
这种情况下，只能通过电脑adb命令打开黑域，而通过电脑adb打开黑域的话，无法显示root功能，也就没有了支付选项。

第一次打开软件，如果没有启动黑域，且有root权限，无法直接支付宝转账，自动启动。必须电脑输入指令开启之后，才能进入软件。

**Comment by liudongmiao** [comment]
把线拔掉以后，就会提示 root 启动了。
