### ISSUE TITLE
耗电严重

### ISSUE THREAD

**Issue by AsasinCree** [brevent/Brevent#271]
虽然手机耗电没有包含brevent，但是系统是第一个，不知道是不是这个导致的

**Comment by liudongmiao** [comment]
因为其它应用耗电少了，系统排名第一。
如果你认为耗电真实增多，黑域执行指令自带 电量诊断，会在 存储卡根目录 生成电量文件。
你可以打包反馈。

注意：电量文件包含同步等账号信息，本人认为属于隐私，不要公开传播。
你也可以发出来之前，全部打码处理。

**Comment by liudongmiao** [comment]
没有进一步反馈，关闭。
