### ISSUE TITLE
黑域会导致手机重启吗？

### ISSUE THREAD

**Issue by mathieu001** [brevent/Brevent#272]
华为荣耀7未root，Android版本5.0.2，安装了最新版本的黑域（2.8.6）发现：
每天上午到公司后通过adb运行启动黑域服务
快到下班时间的时候，手机就会自动重启
几乎是必现的。
未安装黑域时没有这个现象。
请问有人碰到过类似的情况吗？应该怎么处理？

**Comment by jr21066** [comment]
第一帖就贡献在这了

我遇到的情况是这样，我由miui开发版刷到内测版，第一次未清数据，在熄屏后会重启，第二次全清刷机后就正常了，两次均为root模式
楼主可以参考下。

**Comment by liudongmiao** [comment]
某些机器下，如果开启检查通知，会这样。
