### ISSUE TITLE
索尼L36, 发热严重, 并时不时自动重启

### ISSUE THREAD

**Issue by AJay0712** [brevent/Brevent#277]
以下为abd 进程记录

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\A-Jay>adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached

C:\Users\A-Jay>adb devices
List of devices attached
CB5A1PJ97A device

C:\Users\A-Jay>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0
xb34
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0
x1
WARNING: brevent on Android 5.X - 6.0 is experimental!!!
checking for server.......fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-2/base.apk
please report bug to http://t.cn/RSqrb70 with log below
```
--- crash start ---
[command] logcat -b crash -t &#039;03-12 10:35:51.000&#039; -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t &#039;03-12 10:35:51.000&#039; -d -s BreventLoader BreventServ
er
D/BreventLoader(28203): line: package:/data/app/me.piebridge.brevent-2/base.apk
D/BreventLoader(28203): loader path: /data/app/me.piebridge.brevent-2/base.apk
D/BreventLoader(28307): start: 1520822151
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
你可以查看到底哪些在运行，或者使用执行指令中的获取电量数据，然后把 /sdcard/ 目录下的 batterystats.txt 使用反馈发出来。
