### ISSUE TITLE
测试版应用操作建议

### ISSUE THREAD

**Issue by frathy** [brevent/Brevent#278]
单击模版能弹出状态选择，长按读取相应权限使用软件。这样能方便些，偶尔点进去能循环几圈，退出去要按好多次返回。
点开模版界面全选之后全选应该变成取消选项吧，虽然有反选。。。

**Comment by liudongmiao** [comment]
1. 目前主界面也是 点按图标及长按 选择，点按其它区域 打开 菜单。
现在与主界面保持一致。你也可以体验下 Inbox。
至于长按进入，是 bug，已经在 2.9.9 中修复，一会就发布。

2. 一直都没有取消。不论主界面还是在哪。
如果说有的话，选择以后，出现了数据，左边那个就可以取消。
