### ISSUE TITLE
QQ 系应用（包括 Tim ）无法待机

### ISSUE THREAD

**Issue by siwei-lu** [brevent/Brevent#279]
我把 Tim 转成了 FCM 推送,，但是没办法待机，很烦。垃圾毒瘤。

**Comment by siwei-lu** [comment]
实测钉钉也不行，猜测是 JobService 的问题。希望能出个干掉 JobService 的功能

**Comment by vvb2060** [comment]
请使用 黑域→右上角菜单→(反馈)→日志  功能，将日志压缩包作为附件上传。

**Comment by liudongmiao** [comment]
如果你知道 Job 是什么，就知道为什么黑域不会处理了。
黑域不会破坏其它应用完整性，最多只会强行停止它，以及需要付费才能开启的 应用操作。
但本质上，应用操作 应用自身也可以绕过，影响并没有那么大。

**Comment by siwei-lu** [comment]
@liudongmiao 应用操作目前看起来跟 App Ops 差不多，暂时没发现比较高级的用法。

我稍微了解一点安卓开发，知道很多 App 都是拿 Job 来做保活的。虽然我很认同您对于不破坏其它应用完整性的坚持，但是明知道它流氓，但是却拿它没办法的感觉极其难受。

以优酷为例，我如果黑域了它，那么超时之后它就被强行停止（我的设置是只待机！），体验极差。我如果把它放出来，它又会作妖。

所以我想，能否加一个强制休眠的选项，在用户知情的情况下，休眠一些强行保活的流氓 App 。

以上。

**Comment by liudongmiao** [comment]
我的底线，应用再流氓，是你安装的，你可以卸载，可以停用，可以强行停止，不能破坏它的完整性。
黑域面向群体是普通用户，不能让普通用户因为黑域提供的某种操作，导致应用崩溃。
不喜欢或不认同，就卸载其它应用或者黑域。

如果你设置的是只待机，黑域不会强行停止它。除非触发了别的规则。
黑域所有的强行停止，包括设置 appops 与 待机，都有完整的日志，你可以自行查看。
非黑域导致的，黑域不背这个锅。
