### ISSUE TITLE
有时误杀有界面的进程

### ISSUE THREAD

**Issue by asdfeeshy** [brevent/Brevent#28]
例如，把微博加入黑域，某些调用微博登录的应用就会无法完成调用登录。Facebook加入黑域却没有这个问题。

**Comment by liudongmiao** [comment]
如果没有开启立即黑域，取决于是否 3 秒内打开界面。

如果开启了黑域，已知问题。

**Comment by asdfeeshy** [comment]
开启了黑域，但是没有开启立即黑域。

**Comment by liudongmiao** [comment]
那就带日志吧…这个要 verbose 级别日志。

**Comment by liudongmiao** [comment]
此外，你可以把微博放一个桌面小部件。或者开允许同步（但会有好多推送的）。

**Comment by asdfeeshy** [comment]
呐…怎样获取verbose级别的日志…晚上复现一下试试

Liu DongMiao <notifications@github.com>于2017年5月31日周三 17:10写道：

**Comment by asdfeeshy** [comment]
并不需要它推送😂……装微博和Facebook只是为了登录其他应用…这两个App现在垃圾消息都太多了😂

feeshy <asdfeeshy@gmail.com>于2017年5月31日周三 17:11写道：

**Comment by vvb2060** [comment]
@asdfeeshy 
日志的命令为：setprop log.tag.BreventServer VERBOSE
另外如果只需要登录的话可以用写轮眼把它弄残废只留一个登录授权

**Comment by asdfeeshy** [comment]
不知怎么回事又恢复正常了，尝试很多次都没法复现…😂…不管怎样先关掉这个issue吧……
（感觉如果在App内直接保留最近几分钟的log会方便不少，希望后续版本可以考虑支持下😗）

vvb2060 <notifications@github.com>于2017年5月31日周三 17:21写道：

**Comment by liudongmiao** [comment]
暂时关闭，有需要再开。
