### ISSUE TITLE
Would like to pay some 二向箔

### ISSUE THREAD

**Issue by Iphigen1a** [brevent/Brevent#280]
Please send me sth to pay
my phone is nexus 6 it has google play

**Comment by liudongmiao** [comment]
check show donation, then tap play store's icon.

**Comment by Iphigen1a** [comment]
显示的是：
错误
目前还无法在您所在的国家/地区购买Google Play中的内容。很抱歉，您将无法完成购买交易。
可以用支付宝吗？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by liudongmiao** [comment]
https://www.jianshu.com/p/4aa39accd52c
