### ISSUE TITLE
没有进行过核心破解，所有应用还是被识别成了框架应用

### ISSUE THREAD

**Issue by roujiamojun** [brevent/Brevent#283]
手机是小米6，系统是俄版MIUI最新开发版。我没有进行过类似核心破解的操作，软件也不能降级安装或者无视签名安装。但是黑域还是把所有应用识别成了框架应用
![screenshot_2018-03-22-08-48-40-834_me piebridge brevent](https://user-images.githubusercontent.com/7042988/37745359-564b93f4-2daf-11e8-9176-d3a76f0eeb4d.png)
![screenshot_2018-03-22-08-48-17-837_com miui packageinstaller](https://user-images.githubusercontent.com/7042988/37745304-1498e2b8-2daf-11e8-890b-7fa439ca6816.png)
[logs-v3.0.6-20180322.0836.zip](https://github.com/brevent/Brevent/files/1835685/logs-v3.0.6-20180322.0836.zip)

**Comment by liudongmiao** [comment]
框架应用，与降级安装，无视签名不同。

如果为官方正式版，再提；否则不受理。
