### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by TinkMingKing** [brevent/Brevent#290]
1.正在运行程序列表，让黑域进程默认置顶会比较舒服，因为退出后不会有超时计时，就去看黑域前台时间来了解黑域程序的速度。
2.超时程序关闭后仍然计时，刷新才会更新列表，退出后的程序也是关闭后不会更新列表，要手动刷新，能不能像补丁版那样动态地更新程序列表？这样更加方便用户了解黑域的程序性能，使用起来也比较舒服。
3.有的程序黑域速度快，有的慢，这个是什么机制？能不能在说明中添加更加详细的说明？
4.返回键退出后的应用图标能不能不使用闹钟？这样会让人以为是在计时，而事实上只是在3~60s间不确定的时间点结束程序，像补丁版那样的一个反色图标也许不错。

**Comment by liudongmiao** [comment]
1. 不会处理...
2. 不会处理...
3. 具体参照向导关于黑域时机
4. 不会处理，闹钟表示等待黑域
