### ISSUE TITLE
反馈一个不太好的情况

### ISSUE THREAD

**Issue by naloder** [brevent/Brevent#291]
![](https://i.imgur.com/r05jVQY.jpg)
在Mobilism站出现黑域破解。。这种情况需不需要处理。

**Comment by vvb2060** [comment]
没有破解才不正常吧？我倒是对它写着需要root很在意…

**Comment by liudongmiao** [comment]
这是一个攻与防的游戏。
在 3.1.0 里，我稍稍加大了破解的难度。
看可以多久被破解。
