### ISSUE TITLE
為什麼會這樣?

### ISSUE THREAD

**Issue by appleblue3324** [brevent/Brevent#292]
C:\Users\user\Downloads\platform-tools-latest-windows(1)\platform-tools>adb -d s
hell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server..fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '04-01 14:36:31.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '04-01 14:36:31.000' -d -s BreventLoader BreventServ
er
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

C:\Users\user\Downloads\platform-tools-latest-windows(1)\platform-tools>

**Comment by vvb2060** [comment]
您的设备无法执行系统命令，请联系厂商。
