### ISSUE TITLE
黑域使用一段时间后会断流

### ISSUE THREAD

**Issue by StephenGiant** [brevent/Brevent#294]
soc是835 手机是索尼xzp 系统8.0 这个问题困扰了好久 不开黑域又会卡 
希望你们能看看是什么原因 是手机的原因还是跟rom的适配问题
重启黑域失效后网络恢复正常

**Comment by liudongmiao** [comment]
自查应用吧。

待机以后，就是无法访问网络。

不行，就卸载黑阈吧。
