### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by Leetiantian0913** [brevent/Brevent#297]
黑阈最新版，使用应用操作时，qq,淘宝，闲鱼的精准位置不能忽略

**Comment by vvb2060** [comment]
具体描述情况，操作过程及结果。并且使用黑阈菜单-反馈-日志，将日志上传。

**Comment by Leetiantian0913** [comment]
录像

2018年4月4日星期三，vvb2060 <notifications@github.com> 写道：

**Comment by liudongmiao** [comment]
应用操作，调用的是系统  api，我本人不处理相关问题。
而且，系统里，根本没有 精准位置 一说，你要么全部允许位置，要么全部拒绝，生效的只是一个。
