### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by TinkMingKing** [brevent/Brevent#299]
现在，本人是补丁版与普通版共同使用，原因有下，补丁版方式激进，结束快，用于对付那些使用频率低的软件，而普通版结束速度较慢，但是更加智能，且能待机，用于那些频率中等的软件，频率高的软件大部分不处理。

在评论区逛，感觉许多用户还是偏向激进模式，既然这样，能否给黑域清单内的应用添加激进选项，便于满足部分用户需求，这样自主设置，更加合理，就我个人(以及像我这样的用户)而言，也省去使用两个应用的烦恼 。

望考虑

**Comment by liudongmiao** [comment]
XX 不能运行，怎么办？
激进模式的反馈，谁来负责，是你还是我？
