### ISSUE TITLE
google play版本黑域反馈

### ISSUE THREAD

**Issue by tgr989** [brevent/Brevent#3]
liu大，你加入了google的那个不能退出什么计划，导致一个问题，就是黑域对 "google设置" 产生了依赖，只要 "google设置" 不运行，打开黑域就会转圈圈刷不出列表，甚至会提示服务没有启动的界面，但实际上黑域在正常运行，把 "google设置" 服务启动，一切正常。

**Comment by liudongmiao** [comment]
怎么可能...我那个只是由 google 签名而已。
不懂什么是 google 设置...

**Comment by aviraxp** [comment]
你自己的锅。。。看看有谁阻止了 Google Play 服务启动吧。

**Comment by tgr989** [comment]
@liudongmiao 您可以测试一下，只存在在新版（1.1.8和1.1.10），“Google设置”就是“Google Play 服务” ，黑域里不是显示叫“Google设置”嘛，哈哈。
我黑箱试了好几天，只是猜测是跟“Google Play 服务” 有关，猜想：既然Google签了名，或许也会有验证过程吧。
之前您说google play版本跟国内版有不同的那个帖子我找不到了，我也在里面有回复，本想在那个帖子回复的，好像被删除了。

**Comment by tgr989** [comment]
@aviraxp 不是锅不锅的问题，开始杀进程我有意调的，现在我手机上已经调好了，试了一天没出现问题才来反馈的。Google Play 服务在原生上不怎么耗电，但是在被大量修改的国产安卓上耗电还是比较大的，至少我用的魅族是这样。

**Comment by vvb2060** [comment]
把play安装包放到无GApps的手机上，能正常使用，实验性功能当然还是黑的。
你需要提交日志。

**Comment by tgr989** [comment]
@vvb2060 可能是我个人问题，也可能是加个判断检测有无gplay，这是个好的code习惯。条件不允许提供日志，我已经决定用官网提供的国内版本了。

**Comment by liudongmiao** [comment]
@tgr989 所谓 Google 签发，只是在 AndroidManifest.xml 里加了一句 metadata 而已。
不给日志，不让调试的话，我什么也做不了，使用非 Play 版本吧。
