### ISSUE TITLE
Run as ROOT not working

### ISSUE THREAD

**Issue by rex993** [brevent/Brevent#3]
enabled experimental run as root and got the following error:

samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQG5:user/release-keys
SELinux: true

hopefully you can get it working so there won't be need to adb every restart. thanks

**Comment by liudongmiao** [comment]
There should be log, if no...Then, please just give up.

**Comment by rex993** [comment]
I was just about to send logs but saw new version in store. So I upgraded to 2.1a as I see 'optimize root, remove 7 times hack' in the changelog.

However, now that the 7x hack is removed, there is no option to enable 'run as root' as more!

**Comment by liudongmiao** [comment]
@rexii2300 if you have su, it will just show "run as root".

**Comment by liudongmiao** [comment]
and i didn't receive the logs. so if you send logs, please give a description about the logs.

**Comment by rex993** [comment]
there is no option of 'run as root' as more. Maybe I have misunderstood this feature. The description implies that I can 'run as root' without root (su). Are you saying that the phone must be rooted for this to work?

**Comment by liudongmiao** [comment]
if you have su, there will be "run as root"; otherwise, this option won't show.
And brevent is for non-root users.

**Comment by rex993** [comment]
Can you please explain a bit more? My understanding is that to have su, the phone must be rooted. How can I have su without root??? For example, installing the app SuperSU does nothing

**Comment by liudongmiao** [comment]
su means root.

and, if you connect your phone with pc, it will never show "run as root".

**Comment by liudongmiao** [comment]
i think, a screenshot maybe better.

**Comment by rex993** [comment]
Sounds like it's a misunderstanding then.

you said brevent is for non-root users, so I thought the experimental 'run as root' mode means I can start brevent without connecting it to the pc (via adb).

So really it means only if I have root, then I can use 'run as root' option.

**Comment by liudongmiao** [comment]
1. brevent don't requires root, and root is experimental

2. brevent remove "7 times to show run as root", and it show only if:
- device doesn't connect to pc
- device have su / root in it's PATH

so, if you cannot see "run as root", then just disconnect with pc, and make sure your install ~pc~ su.

and if you click "run as root", then it doesn't work, there should be logs.

**Comment by rex993** [comment]
ok now it is clear. Previously it sounded like I can run brevent as root without actual root.
