### ISSUE TITLE
6.1更新1.2.1版后无法显示play捐赠

### ISSUE THREAD

**Issue by qingchoulove** [brevent/Brevent#30]
今天下午商店自动更新之后，无法查询之前捐赠，打开显示捐赠后也无play渠道。

**Comment by liudongmiao** [comment]
打开 play 放后台。放后台看看吧。
我是 7.8.16.P-all，没啥问题。

你也可以试试换个 vpn 看看。
如果还不行，邮件我订单号，给你退款。
