### ISSUE TITLE
Magisk 下systemize 模块不能将黑阈转到/system/app或/system-priv/app

### ISSUE THREAD

**Issue by Justsoos** [brevent/Brevent#301]
目测可以后台运行，但前台调不出来了，提示不能放在系统目录下运行云云。

对于已经root的手机来说，重启之后黑阈就要重新 adb shell.... 相当麻烦，目测以 root 方式运行，也需要再点开一次app，再次确认，如果不确认，后台不自动运行？

**Comment by vvb2060** [comment]
黑阈不支持安装为系统应用，这并不会增加**任何**效果，反而可能导致某些奇怪的问题。
黑阈在接收到开机广播时会有通知，接下来如果有 root 权限，会自动开启服务。没有 root 也会提示请启动服务。只要没有看见通知，就证明是第三方干预了黑阈自启，请自行排查。

调整黑阈为系统应用并不能让黑阈服务在重启后保留，或有权限自动启动黑阈服务。很可能你的 ROM 是因为不会干预系统应用的自启，让你以为黑阈转为系统应用会有额外特效。请搜索你使用的 ROM 添加白名单的方法。
