### ISSUE TITLE
总是在后台奔溃，无法维持

### ISSUE THREAD

**Issue by JX-7** [brevent/Brevent#304]
我用的是黑莓priv，然后最近黑域无法维持工作，总是不在工作，还经常自动重启，于是我重新打开电脑去开他的时候，结果就这样……

WARNING: brevent on Android 5.X - 6.0 is experimental!!!
found old brevent_server, pid: 24732, killing
checking for server...started, pid: 25439
checking for stable.......timeout

**Comment by vvb2060** [comment]
更新到最新beta版后再试，版本 3.2.1-beta1。
另外你可能限制了黑阈连接本地网络，检查手机设置。

**Comment by liudongmiao** [comment]
timeout 属于正常，如网络及其它限制等。
