### ISSUE TITLE
后台还是控制不严格

### ISSUE THREAD

**Issue by dr5hx** [brevent/Brevent#305]
王者荣耀依旧在后台运行，即使把卡片划掉

**Comment by vvb2060** [comment]
首先，更新黑阈到最新版本： beta版[下载地址](https://jianyu.io/br/beta/)。
如果问题依旧，展开黑阈右上角菜单，选择反馈，点按日志按钮。将压缩包保存并上传。
可用GitHub评论附件功能上传，拖放文件到输入框或点击底部蓝色的 selecting them 文字。

**Comment by liudongmiao** [comment]
不懂你的后台运行。

1. 如果是 无需处理，直接忽视即可

2. 如果还在运行，等待处理时间即可。必要时刻，带日志反馈。
