### ISSUE TITLE
QQ浏览器黑域不掉。

### ISSUE THREAD

**Issue by 1357209470** [brevent/Brevent#306]
QQ浏览器和360手机助手和黑域不掉啊。请您看一看
https://share.weiyun.com/5otgWld

**Comment by 1357209470** [comment]
三星G9250 安卓7.0

**Comment by vvb2060** [comment]
首先，由于没有说明黑阈版本，麻烦更新到最新版本，目前是 3.2.1-beta1，可在[官网](https://jianyu.io/br/beta/)下载。
然后，如果问题依旧，请上传**完整的日志压缩包**，而不是其中的一个文件。可用GitHub评论附件功能上传，拖放文件到输入框或点击底部蓝色的 selecting them 文字。

**Comment by 1357209470** [comment]
黑域已是3.2.1-beta1  手机未root adb开启的黑域。最新的3.2.1-beta2也一样
[logs-v3.2.1-beta1-20180417.2012.zip](https://github.com/brevent/Brevent/files/1919651/logs-v3.2.1-beta1-20180417.2012.zip)

 ![screenshot_20180417-200940](https://user-images.githubusercontent.com/25477049/38869758-529615de-427e-11e8-9a0d-3cc722b2d911.png)
![screenshot_20180417-201641](https://user-images.githubusercontent.com/25477049/38869767-551fd6fa-427e-11e8-83d2-96565d58752a.png)

**Comment by vvb2060** [comment]
```
2018-04-17 20:12:18,399 [main] DEBUG foreground service: {com.limboworks.honorofcup.qihoo, com.tencent.mtt, com.tencent.mobileqq, com.qihoo.appstore}
2018-04-17 20:12:18,399 [main] DEBUG sticky notification: {com.limboworks.honorofcup.qihoo, com.tencent.mtt, com.tencent.mobileqq, com.kugou.android, com.qihoo.appstore}
```
QQ浏览器和360手机助手为前台服务且有通知，不会被黑阈。

**Comment by vvb2060** [comment]
你可以把它们从概览屏幕划掉，这样黑阈会强行停止它们。

**Comment by 1357209470** [comment]
嗯，可以了，重新设置了应用的通知开关就好了 可能是手机系统更新的bug

**Comment by 1357209470** [comment]
所有应用都没显示通知啊，我都是设置禁止显示通知的。现在是要重新设置是否允许显示通知才可以黑域掉，打开又关闭。每次都要重新设置 是否应用显示通知 才可以黑域掉
