### ISSUE TITLE
关于应用权限问题

### ISSUE THREAD

**Issue by crazy2379663** [brevent/Brevent#307]
安卓7.0，三星s7 Active。
今天重启之后，再次通过电脑连接黑域以后，发现部分手机应用的存储等关键权限无法打开，结果部分应用无法正常使用。

**Comment by vvb2060** [comment]
请详细描述情况。应用信息-权限-存储空间，显示为灰色无法打开？还是已经打开但应用实际无法访问存储空间。
对于后者，检查你对该应用的**应用操作**设置，`读取存储空间`与`写入存储空间`。除了为新安装应用套用你设置的模板，黑阈不会自动调整应用操作。

**Comment by liudongmiao** [comment]
1. 黑阈 中的应用操作，已经明确提示“可能导致应用无法正常使用”
2. 应用操作 除非你事先设置，黑阈不会更改
3. 应用操作 整个功能，默认不可见

所以，这个问题，我想直接关闭。
