### ISSUE TITLE
 优化音乐类应用功能失效

### ISSUE THREAD

**Issue by Strimina** [brevent/Brevent#314]
在重启手机后优化音乐类应用功能不能正常使用，必须重新打开开关然后关闭一次才行，望修复。系统MIUI,9最新开发版8.4.19

**Comment by vvb2060** [comment]
展开黑阈右上角菜单，选择反馈，点按日志按钮。将压缩包保存并上传。
可用GitHub评论附件功能上传，拖放文件到输入框或点击底部蓝色的 selecting them 文字。
没有日志，无法处理。

**Comment by liudongmiao** [comment]
1. 这个功能非常实验性
2. 这个功能依赖通知，且至少要有一次 检查操作，才能知道是不是 音乐播放器。
3. 这个检查操作，可能不会那么及时。
