### ISSUE TITLE
 foregroundServiceNoNotification audio apps

### ISSUE THREAD

**Issue by ansmax** [brevent/Brevent#315]
从3.2.0版本以后  优化音乐类应用功能就已经无效了  不管是网易云音乐还是Q音乐 还是导航  播放状态到时间都会被黑掉 麻烦大大查看一下

**Comment by ansmax** [comment]
刚才确认了一下  3.0.6版本无问题  从3.1.2开始有问题  播放状态进程后的标识不会变成播放符号而是秒表符号

**Comment by vvb2060** [comment]
展开黑阈右上角菜单，选择反馈，点按日志按钮。将压缩包保存并上传。
可用GitHub评论附件功能上传，拖放文件到输入框或点击底部蓝色的 selecting them 文字。
没有日志，无法处理。

**Comment by ansmax** [comment]
[logs-v3.2.0-20180421.1044.zip](https://github.com/brevent/Brevent/files/1934090/logs-v3.2.0-20180421.1044.zip)

**Comment by vvb2060** [comment]
从日志看，你打开过一次QQ音乐，它随后被黑阈停止。期间手机没有任何通知，但QQ音乐启动了前台服务，于是被黑阈停止。手机没有通知，黑阈也不会检查音频。
麻烦补充说明情况。手机是否出现过任何通知？使用的是什么ROM？

**Comment by Saszr** [comment]
开关是开着的，确实失效了，是普遍问题。beta3版没用，beta1版当时用，失效问题也是有的，借楼反馈下，就不新开问题了。

**Comment by vvb2060** [comment]
@Saszr  有条件请提供日志，没有日志的反馈是无作用的。

**Comment by liudongmiao** [comment]
没有 通知 事件，黑阈无法实时检查通知。

目前已经兼容处理，请前往测试：https://jianyu.io/br/alpha/

另外，请给下 rom 型号，执行指令 `getprop ro.build.fingerprint` 即可。

**Comment by liudongmiao** [comment]
duplicate #325
