### ISSUE TITLE
关于不待机的问题

### ISSUE THREAD

**Issue by TinkMingKing** [brevent/Brevent#322]
[server.20180428.1240.31282.txt](https://github.com/brevent/Brevent/files/1957309/server.20180428.1240.31282.txt)
设置的是待机超时5min，后台超时1min,偶尔会发生该情况，被黑域的软件不待机，直接5分钟左右被处理

**Comment by liudongmiao** [comment]
你这个日志中，黑阈强行停止了三个应用，都是 noRecent，也就是你从最近列表划掉了它。
这是符合期望的。

**Comment by TinkMingKing** [comment]
你的意思是说日志里没有异常，我也大致看了一下日志，软件在待机列表中，可是黑域界面中显示一直是在正在运行列表中，这个问题时常出现

~删除感叹号~
~为了社区交流，请不要使用感叹号~

**Comment by liudongmiao** [comment]
你问我为什么强行停止，我说了强行停止原原因。
至于其它的，我不对你 ROM 或应用行为发表任何意见。
如果你认为黑阈处理不当，那就另开，带日志说话。
你也可以看懂日志，自己看就好。
