### ISSUE TITLE
foregroundServiceNoNotification audio apps

### ISSUE THREAD

**Issue by wtjjtds** [brevent/Brevent#325]
RT

**Comment by vvb2060** [comment]
展开黑阈右上角菜单，选择反馈，点按日志按钮。将压缩包保存并上传。
可用GitHub评论附件功能上传，拖放文件到输入框或点击底部蓝色的 selecting them 文字。

**Comment by wtjjtds** [comment]
[logs-v3.2.1p1-20180429.0904.zip](https://github.com/brevent/Brevent/files/1958336/logs-v3.2.1p1-20180429.0904.zip)

**Comment by vvb2060** [comment]
与 #315 情况相同。没有发现任何通知事件，黑阈认为从未接到过通知(但在第一个日志文件里长期有相同的“当前通知”，估计是启动时dump的，一直没变过)。因为没有通知，黑阈不会检查音频。
在此情况下，音乐应用启动了前台服务播放音频，黑阈因为前台服务却无通知，强行停止了它们。

请问，确认通知栏出现过通知？手机用的是什么ROM？

**Comment by liudongmiao** [comment]
duplicate as #315 , close this

与 #315 问题类似，关闭此问题。讨论请前往 #315
