### ISSUE TITLE
无法黑域王者荣耀

### ISSUE THREAD

**Issue by SteveChern** [brevent/Brevent#329]
微博国际版会唤醒王者荣耀，在使用微博国际版时经常出现王者荣耀的通知，进入黑域查看却显示王者荣耀为没有运行

**Comment by liudongmiao** [comment]
没有日志。

且，国内 ROM 经常 通知 显示是这个应用，但实际不是这个应用发出的。
也就是说，应用不需要运行，就能接收通知，流氓吧。

是否运行，以黑阈内展示为准。
必要时，你可以开启“激进模式”。
