### ISSUE TITLE
大神，brevent-server部分的源码不开放吗？

### ISSUE THREAD

**Issue by shilei0619** [brevent/Brevent#330]
“There is no source for `brevent-server`.”看到这句很伤心
另外我按照develop.md里面说的，把classes2.dex从老版本里提取出来重新打包进安装到手机之后，在进入黑域那一步最后显示“无法生成指令文件”

**Comment by liyufan** [comment]
是的，而且新版已经闭源。

**Comment by csc001** [comment]
作者想捞钱了。

**Comment by liudongmiao** [comment]
如果你想研究，阅读 0.8.X 一样可以。但我估计，有兴趣的不用参考黑阈源码，没兴趣的给了源码也没用。

**Comment by Zxilly** [comment]
现在UI部分也不开源了

**Comment by liudongmiao** [comment]
开源也没人见提交补丁啊...
