### ISSUE TITLE
挂了VPN也无法应用内支付

### ISSUE THREAD

**Issue by weiwuzhiqiang** [brevent/Brevent#333]
挂了VPN可以正常登录play更新应用，但是在黑阀内无法打开play的支付，看了作者的指南说是要授权黑阀允许打开play，请问如何授权？在手机设置应用内没有找到相关选项，谢谢各位大佬

**Comment by liudongmiao** [comment]
打开 play 商店，放后台，然后进入黑阈。鉴于国内环境，如果真的不可以使用，就不要使用吧...
