### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by nextzhou** [brevent/Brevent#334]
* daemon not running; starting now at tcp:5037
* daemon started successfully
WARNING: linker: /data/local/tmp/brevent: unsupported flags DT_FLAGS_1=0x8000001
WARNING: brevent on Android 5.X - 6.0 is experimental!!!
checking for server.......fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '05-08 13:40:37.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '05-08 13:40:37.000' -d -s BreventLoader BreventServer
05-08 13:40:45.374  2775  2775 D BreventLoader: line: package:/data/app/me.piebridge.brevent-1/base.apk
05-08 13:40:45.482  2775  2775 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
05-08 13:40:45.636  2838  2838 D BreventLoader: start: 1525758037
05-08 13:40:47.443  2838  2838 I BreventServer: args: [10, me.piebridge.brevent, 1525758037]
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
日志有点太少了。
