### ISSUE TITLE
为什么不直接在黑域中加入支付宝或微信支付

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#335]
黑域作者：
        你好。      
        黑域正式开始收费我不反对，但大陆这么个特殊的网络环境，感觉在生之年谷歌支付也没法接入大陆了，请作者给黑域的大陆用户弄个可以用国内支付渠道的版本。
        谢谢。祝黑域越做越好。

**Comment by vvb2060** [comment]
根据play商店政策，在play商店安装的应用只能使用Google pay。在大陆商店安装将可以使用支付宝，接下来会接入微信支付。
黑阈的大陆用户一直可以使用国内支付渠道。你不是大陆用户(通过play商店安装)，或者你虽然是国内商店安装但停用了支付宝。
