### ISSUE TITLE
怎样在支付宝中验证2017年3月的支付记录？

### ISSUE THREAD

**Issue by eaglehigh7** [brevent/Brevent#336]
在黑阈中调出支付宝后，返回到支付宝主界面-我的-账单-搜索到支付记录，黑阈不能自动识别。是我的方法有问题吗？

**Comment by liudongmiao** [comment]
请参考这个：https://www.jianshu.com/p/4aa39accd52c

如果依旧不能，请重现，黑阈内 菜单 - 反馈 - 日志，并描述问题（邮件太多，不描述对不上）。
