### ISSUE TITLE
关于增加无障碍服务优化的建议

### ISSUE THREAD

**Issue by SoDebug** [brevent/Brevent#34]
@Brevent 能不能对无障碍服务也做相应优化
(1)主要是因为使用一段时间辅助服务就不会用了，但黑域不处理它，他会一直挂在后台，黑域前台点击黑域提示无障碍服务，不联系黑域，其实这时用户已经不用它了。
(2)有时候正在使用无障碍服务，但是黑域又突然停止了该应用
具体处理方法可以看看下方：
1.用户从最近列表划去，立即强行停止！或者待机1分钟后强行停止
2.用户通过"Back"返回(或者在该软件内同一界面多次频繁点击"Back")，强行停止(因为可能是软件卡顿)！
3.用户通过"HOME"返回桌面，不予处理！

**Comment by liudongmiao** [comment]
无障碍 就是要一直启用。

虽然黑域能在检查过程中判断当前是否为无障碍，但是这个 api 只能调用 65535 次，然后就会导致系统软重启。所以，相当于无法在黑域过程中检查是否为无障碍，只能由你自己开启。

如果你要使用无障碍，那么开启它，进入黑域，黑域会不再黑域它；或者直接手动不要黑域。
否则，那就使用它。

不要试图使用黑域解决所有问题。
