### ISSUE TITLE
删掉appcompat-v7后应用UI显示异常

### ISSUE THREAD

**Issue by vvb2060** [brevent/Brevent#34]
非原生ROM多变为了系统默认样式
7.1原生ROM部分异常：状态栏无法进入阅读模式（是这个名字吧？仅有电池和时间）用户应用，系统应用一栏固定不隐藏

**Comment by liudongmiao** [comment]
你得来个图吧。

颜色什么的，懒得指定，直接使用系统默认配置。
（作为对比，至少在我的魅族上看起来很好的，有点小问题。）

此外，去掉了阅读模式，免得有人忘了自己不在用户应用下，把系统应用或框架应用给黑域了。

**Comment by vvb2060** [comment]
原来是故意的，能不能把状态栏部分的阅读模式恢复？这个应该不影响吧

**Comment by liudongmiao** [comment]
可是可以，但是，没啥实际意义了吧。

你可以下载我另一个 app （圣经阅读器），来体验下阅读模式。
但是，还没写完，后来就切到黑域了。现在我估计，可以把重心放到 圣经 App 了。

体验地址：https://v4.piebridge.me/pb/

**Comment by vvb2060** [comment]
强制沉浸的xposed模块有53万下载量，黑域54万。好看就是意义啊🤣
另外现在向导一进去并不能知道共有多少屏，会不会让用户更难以认真看完？

**Comment by liudongmiao** [comment]
不看完，找不到入口吧。

之前我想过，给 3 个，但是，给人一种感觉完全没有入口的感觉。
所以，现在，给了 2.5 个。为了，我还认真 hack 了 TabLayout。
https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/GuideTabLayout.java#L42

也许，应该像其他应用一样，完全不给快速入口，必须一页页翻。

**Comment by liudongmiao** [comment]
@vvb2060 黑域要能有 50 万下载就好了。
目前在 play 上，连 5 万都不到，实际用户，可能只有 2 万多一点点。

酷安上能看到的下载数，没有任何意义。

**Comment by vvb2060** [comment]
没说清楚，主要是一种焦虑的心情。安装完一打开就是大段说明，还望不到底，会不会导致用户快速略过变成了找入口的游戏？

**Comment by liudongmiao** [comment]
一个版本，将改为默认的主题: Theme.DeviceDefault
作为对比，目前是 Theme.Material

之前的版本是 appcompat 默认主题。

在本地看了下，魅族机器上，Theme.DeviceDefault 视觉效果上更统一。


当然，我还是有部分自定义的。
比如设置的小标题部分，强制使用 colorAccent 颜色。

**Comment by vvb2060** [comment]
还是统一的视觉体验好些？去掉兼容包也就不到1MB的大小差异
![](http://ww3.sinaimg.cn/large/006HJ39wgy1fgdrom72rrj30u01dcq5k.jpg)
![](http://ww1.sinaimg.cn/large/006HJ39wgy1fgdron5fldj30u01hcwkf.jpg)
![](http://ww3.sinaimg.cn/large/006HJ39wgy1fgdronbeisj30u01hcadb.jpg)
![](http://ww4.sinaimg.cn/large/006HJ39wgy1fgdroo1ww6j30u01hc0wj.jpg)

**Comment by liudongmiao** [comment]
@vvb2060 我想知道，你这个截图之后，现在新版是什么样子？

**Comment by vvb2060** [comment]
@liudongmiao 这些是在酷安上收集的，从近期上面的截图看来应该没有问题，和原生系统看到的相同。
另外似乎改了DPI导航条显示会不一样
 ![](https://ooo.0o0.ooo/2017/06/23/594d01c9b57c0.png)
