### ISSUE TITLE
支付问题

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#340]
黑域作者：
你好。
我已经安装大陆版本的黑域，并在其中支付，后发现大陆的黑域版本为旧版。请问之后的更新可以保持我的购买记录么？购买之后的版本会与谷歌商店同步么？
谢谢

**Comment by liudongmiao** [comment]
不存在旧版一说，目前都是同步发布的。

版本及支付请参见：https://www.jianshu.com/p/4aa39accd52c
