### ISSUE TITLE
添加新功能-唤醒切断

### ISSUE THREAD

**Issue by bydvoid** [brevent/Brevent#341]
目前仍然有应用被其它应用唤醒，一唤醒一大堆，我不得不停用那些应用。希望能增加个唤醒切断的功能，一劳永逸。

**Comment by vvb2060** [comment]
黑阈不破坏其它应用完整性，不会添加此功能。
目前黑阈智能识别被唤醒但没有打开界面的应用，快速停止。

**Comment by catdog** [comment]
这功能需要root权限吧
