### ISSUE TITLE
动态gms与ssr的问题

### ISSUE THREAD

**Issue by pzcn** [brevent/Brevent#345]
当gms被动态停用  打开ssr  打开依赖gms的应用 
 gms被启用时 ssr就会断开连接。
另外，之前有过一次play更新app失败，点击通知进入play时不会动态启用gms。

**Comment by pzcn** [comment]
试了手动启用停用gms也会导致ssr关闭，目前有没有比较好的解决办法？
（或者是我个例？）

**Comment by liudongmiao** [comment]
1. ss 不需要 gms 也能用
2. 但是如果 ss 打开了 gms，这时强行停止 gms，也会停止 ss
我本人不使用什么  ssr，你也不需要给我结果。

这种问题，我本人真的不愿意回答与测试。
动态 gms 功能，是给那些基本不用 gms 的人使用的。
如果某个你必须的应用，必须接入 gms 才能使用，并且你要一直使用它，那么，不要停用 gms。
