### ISSUE TITLE
换新UI后没法停用操作系统应用了

### ISSUE THREAD

**Issue by catdog** [brevent/Brevent#348]
v3.5.2 play ver.
在操作系统标签下，选择应用（非android进程）后右上角没出现┆操作菜单

**Comment by liudongmiao** [comment]
你需要开启停用功能，且停用“操作系统应用”仅限特别贡献版。
因为，真的太太太危险了: https://jianyu.io/br/price.zh.html

**Comment by catdog** [comment]
我不知道你如何理解issue标题的，为什么你会认为我没有开启 【停用应用】以及【显示操作系统应用】？
另外，你close issue前自己有确认/试过吗？！！

**Comment by vvb2060** [comment]
我刚刚确认了，没有3.5.2版，目前最新版本是3.2.5.1。而这个版本没有问题。
你可以给出截图，GitHub支持直接上传截图。

**Comment by liudongmiao** [comment]
所有 issue，关闭之前肯定都已经确认。

即使开启了 显示操作系统应用，“Android 进程” 及其它重要类别不许停用。

如果您要体验“作死”（请原谅我使用这个词）的感觉，可以复制包名，然后执行指令里输入

```
pm disable-user <包名>
```
