### ISSUE TITLE
充电的时候异常发热，怀疑是不是黑域的问题

### ISSUE THREAD

**Issue by maxiye** [brevent/Brevent#35]
手机是sony xz，感觉以前版本不会发热的，后来好像升级到0.9以后开始的（充电到30%~65%发热明显），猜测是充电期间app自启严重，黑域杀个不停，然后发热。就是可不可以充电的时候暂停黑域服务，充电完成后继续？

**Comment by liudongmiao** [comment]
发个邮件到我邮箱，我单独给你测试包。

**Comment by maxiye** [comment]
你的邮箱是？

**Comment by liudongmiao** [comment]
已经默认去掉该功能。

如果需要启动，手动执行 

```
setprop log.tag.brevent.charging disabled
```
