### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by AronLL** [brevent/Brevent#35]
1.网易云音乐在黑域允许同步的情况下，不知道为什么，一段时间后仍然会被自动关闭。
2.在使用substratum主题的时候，如果应用安装了新主题，这些新主题会被自动黑域。很显然，这些主题应用并不需要被黑域，而我没有针对于此的取消自动黑域的按钮。更重要的是，因为一个主题里面包含大量的叠加层，每安装一个的时候自动黑域一下，有时甚至会导致卡死.....

如果能修复和改进，十分感激！

**Comment by vvb2060** [comment]
第一个，使用最新测试版看看。第二个，早已优化过，或许你开着激进模式？

**Comment by AronLL** [comment]
因为我用的是PLAY版，没有BETA计划，所以先算了~.~既然已经在修复，我就也不急哈哈。谢谢喽~
