### ISSUE TITLE
android o的 root 使用情况下，USB连接断开电脑不定期出现服务关掉的情况

### ISSUE THREAD

**Issue by ynuance** [brevent/Brevent#350]
而且会提醒我安卓8以上不要关闭adb，实际上我就没打开过ADB，一直是使用root。
有时候服务关闭后会弹出提示选择是使用root还是adb，其实我已经授予了root权限，还是让我选。
而且在选择了root之后，有时还会多次弹出选择窗口，点好几次root才行。

[logcat(2).txt](https://github.com/brevent/Brevent/files/2011351/logcat.2.txt)

**Comment by liudongmiao** [comment]
从你的日志来看，最终是 OK 的。
我本人不处理任何与 root 相关的展示慢问题。
目前，黑阈不再为 root 进行任何优化。
在我所有测试机上，表现均正常。
