### ISSUE TITLE
开启黑阈失败

### ISSUE THREAD

**Issue by RolandVyens** [brevent/Brevent#351]
u0_a111@SG305SH:/ $ su root@SG305SH:/ # adb -d shell sh /data/data/me.piebridge.brevent/brevent adb -d shell sh /data/data/me.piebridge.brevent/brevent sh: /data/data/me.piebridge.brevent/brevent: No such file or directory root@SG305SH:/ # adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh WARNING: brevent on Android 5.X - 6.0 is experimental!!! checking for server.......fail [command] pm path me.piebridge.brevent package:/data/app/me.piebridge.brevent-2/base.apk please report bug to https://github.com/brevent/Brevent/issues with log below ``` --- crash start --- [command] logcat -b crash -t '05-17 15:01:34.000' -d --- crash end --- --- brevent start --- [command] logcat -b main -t '05-17 15:01:34.000' -d -s BreventLoader BreventServer 05-17 15:01:34.897 15700 15700 I BreventLoader: pm path me.piebridge.brevent 05-17 15:01:38.617 15700 15700 I BreventLoader: line: package:/data/app/me.piebridge.brevent-2/base.apk 05-17 15:01:38.785 15700 15700 I BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk 05-17 15:01:38.790 15728 15728 I BreventLoader: start: 152654049405-17 15:01:42.275 15728 15728 I BreventServer: args: [10, me.piebridge.brevent, 1526540494] 05-17 15:01:42.829 15728 15728 I BreventServer: server log name: server.20180517.1501.15728.txt 05-17 15:01:42.836 15728 15728 I BreventServer: starting Brevent Server 3.2.5.1 05-17 15:01:43.058 15728 15728 I BreventServer: brevent version: 3.2.5.1 05-17 15:01:43.060 15728 15728 I BreventServer: brevent user: 0, uid: 2000 05-17 15:01:43.214 15728 15728 I BreventServer: core apps: [com.android.providers.telephony, com.blackberry.keyboard, com.blackberry.spf.helper, com.quicinc.cne.CNEService, com.android.mms.service, com.blackberry.cellular.vzwwfcaddressmanager, com.blackberry.cellular.ims.daemon, com.android.defcontainer, android, org.codeaurora.ims, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.frameworks.telresources, com.android.inputdevices, com.blackberry.deviceconfig, com.android.server.telecom, com.qualcomm.qti.rcsbootstraputil, com.android.dialer, com.google.android.packageinstaller, com.android.proxyhandler, com.blackberry.cellular.ims.provider, com.qualcomm.qti.rcsimsbootstraputil, com.android.settings, com.qualcomm.location, com.qualcomm.simcontacts, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.blackberry.internalinputdevice, com.qualcomm.atfwd] 05-17 15:01:43.215 15728 15728 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.defcontainer, android, com.android.providers.settings, com.android.frameworks.telresources, com.android.inputdevices, com.android.server.telecom, com.android.dialer, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui} 05-17 15:01:43.218 15728 15728 I BreventServer: installer: com.google.android.packageinstaller 05-17 15:01:43.218 15728 15728 I BreventServer: brevent data directory: /data/user/0/com.android.shell 05-17 15:01:43.228 15728 15728 I BreventServer: no service overlay 05-17 15:01:43.325 15728 15728 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 49 05-17 15:01:43.426 15728 15728 W BreventServer: Can't setStopped for so.ofo.labofo(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10463) 05-17 15:01:43.428 15728 15728 W BreventServer: Can't setStopped for net.idik.artemis(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10366) 05-17 15:01:43.430 15728 15728 W BreventServer: Can't setStopped for com.niksoftware.snapseed(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10170) 05-17 15:01:43.431 15728 15728 W BreventServer: Can't setStopped for com.benqu.wuta(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10409) 05-17 15:01:43.433 15728 15728 W BreventServer: Can't setStopped for com.zui.recorder(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10360) 05-17 15:01:43.434 15728 15728 W BreventServer: Can't setStopped for com.speedsoftware.rootexplorer(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10440)05-17 15:01:43.436 15728 15728 W BreventServer: Can't setStopped for com.tencent.qqmusic(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10373) 05-17 15:01:43.437 15728 15728 W BreventServer: Can't setStopped for com.tencent.FileManager(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10438) 05-17 15:01:43.438 15728 15728 W BreventServer: Can't setStopped for com.pandecheng.coolapk.sticker(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10405)05-17 15:01:43.440 15728 15728 W BreventServer: Can't setStopped for com.google.android.apps.authenticator2(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10162) 05-17 15:01:43.441 15728 15728 W BreventServer: Can't setStopped for com.ruguoapp.jike(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10247) 05-17 15:01:43.442 15728 15728 W BreventServer: Can't setStopped for com.MobileTicket(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10242) 05-17 15:01:43.444 15728 15728 W BreventServer: Can't setStopped for com.liuyx.myblechat(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10279) 05-17 15:01:43.445 15728 15728 W BreventServer: Can't setStopped for com.lufax.android(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10235) 05-17 15:01:43.446 15728 15728 W BreventServer: Can't setStopped for com.tencent.token(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10282) 05-17 15:01:43.448 15728 15728 W BreventServer: Can't setStopped for com.sunny.www.compass(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10147) 05-17 15:01:43.449 15728 15728 W BreventServer: Can't setStopped for com.oweika.gitartune(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10295) 05-17 15:01:43.450 15728 15728 W BreventServer: Can't setStopped for com.amazon.kindlefc(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10110) 05-17 15:01:43.451 15728 15728 W BreventServer: Can't setStopped for com.kittendev.sticker(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10352) 05-17 15:01:43.452 15728 15728 W BreventServer: Can't setStopped for com.eusoft.eudic(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10307) 05-17 15:01:43.453 15728 15728 W BreventServer: Can't setStopped for com.android.chrome(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10048) 05-17 15:01:43.454 15728 15728 W BreventServer: Can't setStopped for com.google.android.gsf(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10012) 05-17 15:01:43.456 15728 15728 W BreventServer: Can't setStopped for com.google.android.tts(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10063) 05-17 15:01:43.457 15728 15728 W BreventServer: Can't setStopped for com.baidu.tieba(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10434) 05-17 15:01:43.458 15728 15728 W BreventServer: Can't setStopped for com.sun.quickpay(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10332) 05-17 15:01:43.459 15728 15728 W BreventServer: Can't setStopped for ru.zdevs.zarchiver.pro(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10388) 05-17 15:01:43.461 15728 15728 W BreventServer: Can't setStopped for org.videolan.vlc(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10384) 05-17 15:01:43.462 15728 15728 W BreventServer: Can't setStopped for com.google.android.apps.photos(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10078)05-17 15:01:43.464 15728 15728 W BreventServer: Can't setStopped for com.xueqiu.android(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10471) 05-17 15:01:43.465 15728 15728 W BreventServer: Can't setStopped for me.morirain.dev.iconpack.pure(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10465) 05-17 15:01:43.466 15728 15728 W BreventServer: Can't setStopped for com.sunrain.timetablev4(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10328) 05-17 15:01:43.468 15728 15728 W BreventServer: Can't setStopped for com.hippotech.materialislands(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10452) 05-17 15:01:43.469 15728 15728 W BreventServer: Can't setStopped for com.antfortune.wealth(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10148) 05-17 15:01:43.471 15728 15728 W BreventServer: Can't setStopped for com.One.WoodenLetter(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10248) 05-17 15:01:43.472 15728 15728 W BreventServer: Can't setStopped for com.drpe26.MemoryCleaner(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10257) 05-17 15:01:43.474 15728 15728 W BreventServer: Can't setStopped for cn.wps.moffice_eng(Permission Denial: attempt to change stopped state from pid=15728, uid=2000, package uid=10159) --- brevent end --- ``` please report bug to https://github.com/brevent/Brevent/issues with log above root@SG305SH:/ #

**Comment by liudongmiao** [comment]
这个日志也太难看了。

本来好好的有分行的，到你这里，没有任何分行。

请重现，使用黑阈日志，或者直接文本化日志。

**Comment by RolandVyens** [comment]
这堆日志是终端模拟器里的，无法重现，不用修了                                                                                                                                                                        发送自我的 BlackBerry - 最安全的移动设备                                                                                                                                                                           发件人： notifications@github.com发送时间： 2018年5月19日 17:09收件人： Brevent@noreply.github.com回复： reply@reply.github.com抄送： leiersai@sina.com; author@noreply.github.com主题： Re: [brevent/Brevent] 开启黑阈失败 (#351)  Closed #351.
