### ISSUE TITLE
force quitting all not force quitted or specified elements

### ISSUE THREAD

**Issue by fxmbsw7** [brevent/Brevent#352]
as like for loop app list +system nd if force quit button is active app.force_quit a couple of times and then further to next app
and that repeat every one minute
with whitelist

so it quits all like non google vendor services and all the non removeable bullshitts

thered be loop app list; check if not force quitted already, check if not in whitelist, force quit function a couple of times, then further next app element, every specified time like every minute

like named brevent_all +whitelist mode

see any way to code it ?

as brevent is now, it doesnt force quit much and many elements that the force quit function / button would work are disabled

peace /xmb

**Comment by liudongmiao** [comment]
Please use normal English, don't short it.

**Comment by liudongmiao** [comment]
In short, won't implement.

**Comment by fxmbsw7** [comment]
ok sad byee
this english i write samely i speak it

bye
