### ISSUE TITLE
你好我想退款

### ISSUE THREAD

**Issue by oooasis** [brevent/Brevent#355]
换设备后，手机不能root，身旁没有电脑 转账记录删了 但是这里貌似不能上传图片，支付宝17689300207

**Comment by Zxilly** [comment]
# 发邮件吧

**Comment by oooasis** [comment]
邮址发我一个谢谢

**Comment by liudongmiao** [comment]
流程：https://www.jianshu.com/p/87aa6245d814
邮箱：brevent # jianyu.io (# 换成 @)
