### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by Hocuri** [brevent/Brevent#356]
This repository contains only the translations, a license file, a contributors file and a .gitignore file.

Where are the .java files and so on? Like this it is not open source, just using Github for things that are public anyway.

**Comment by skinzor** [comment]
There's another branch, called "master". The default branch is "translation".
See here: https://github.com/brevent/Brevent/tree/master

**Comment by liudongmiao** [comment]
Brevent stop open source after 2.8.6.

1. Some of guys violate license of Brevent, distribute Nrevent with original Brevent  launch icon.

2. It's impossible to split brevent and brevent server after android's d8.
> D8 is the default dx tools since android studio 3.1.
> https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html
