### ISSUE TITLE
无法启动 root 电脑都不行

### ISSUE THREAD

**Issue by srjanese** [brevent/Brevent#358]
--- crash start ---
[command] logcat -b crash -t '05-25 10:41:35.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '05-25 10:41:35.000' -d -s BreventLoader BreventServer
05-25 10:41:35.420  9633  9633 I BreventLoader: sdk: 25
05-25 10:41:35.452  9638  9638 I BreventLoader: pm path me.piebridge.brevent
05-25 10:41:35.460  9638  9638 I BreventLoader: line:
05-25 10:41:35.461  9638  9638 E BreventLoader: can't get path
05-25 10:41:35.461  9633  9633 E BreventLoader: worker 9638 exited with status 255
--- brevent end ---

**Comment by vvb2060** [comment]
Android原生指令无法执行，联系您的手机ROM提供商。
