### ISSUE TITLE
一句话描述黑域实现机制

### ISSUE THREAD

**Issue by shilei0619** [brevent/Brevent#359]
“adb shell启动一个守护进程用以适时停包。”
没毛病吧
至于为什么可以做到参考这篇博客：https://www.jianshu.com/p/3f6006e74821

**Comment by vvb2060** [comment]
这个issue，你是想表达什么呢？
黑阈服务持有权限，黑阈前端与其交互。

**Comment by shilei0619** [comment]
因为没有源码，所以问下作者是不是这个实现原理。
“黑阈服务持有权限，黑阈前端与其交互。”这句话不够具体，或者说不算是技术角度。
之所有能有权限还是adb shell启动的进程uid=shell所以拥有至高权限，才有能力后台直接forcestop.

**Comment by vvb2060** [comment]
https://github.com/brevent/Brevent/commit/f70169786fc26bd3f6341c548f09129e368ef0db
虽然不是最新黑阈服务代码，但如果只是想了解原理的话，这些就足够了。
关于权限，UID=2000的权限并不够，黑阈服务还需要网络以及读取日志等权限。

**Comment by shilei0619** [comment]
嗯，多谢多谢
