### ISSUE TITLE
黑域酷安后会导致酷安断网

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#36]
后台应用超时设置1分钟，待机超时15分钟，安卓6.0。

将酷安加入黑域，无论是否开启立即黑域，无论是否对酷安开启允许同步，只要酷安进入待机后（back退出令酷安待机或home挂到后台待机），先打开其他应用刷个三五分钟，再重新打开酷安，如果之前是back退出，此时酷安就会长时间转圈然后提示“网络连接超时”，首页一片空白，有时再等久些会刷出来，但大多数情况怎么都刷不出来；如果之前是home挂到后台，此时酷安有之前页面，但实际已断网，点击后还是转圈刷不出来。

只要取消黑域酷安，酷安怎样操作都能秒刷。奇怪的是，目前只遇到酷安这一个黑域后前台界面也断网的应用，其他应用都不会这样，待机后重新打开会长时间断网。手头暂时没电脑，日志要迟一点才能提供。

**Comment by CVN-77** [comment]
酷安待机后，重新打开酷安会断网，必须要划掉后台卡片强行停止再打开酷安，才能秒刷。

而取消黑域酷安后，直接打开酷安时还是转圈没网，也要划掉后台卡片强行停止，之后酷安才能恢复正常使用。

**Comment by CVN-77** [comment]
看来是酷安（最新版7.9.1）有bug，取消黑域后，手动在未启用应用里将其调为未启用，后台等个三五分钟，再重新打开酷安，也是长时间转圈提示断网…

**Comment by liudongmiao** [comment]
应用自身兼容性问题。
