### ISSUE TITLE
新版本黑域微信后无法通过FCM获取推送

### ISSUE THREAD

**Issue by millermoment** [brevent/Brevent#362]
上个版本，将微信黑域的同时开启允许同步即可让微信通过FCM获取推送，这个版本通过Google Play更新后便不行了，不知道是什么原因，希望可以得到解决。
机型:SONY XPERIA Z5 Dual 
基本情况:未ROOT 无绿色守护 仅安装黑域。

**Comment by liudongmiao** [comment]
微信应当是不支持 FCM 的，其它 FCM 应用没有问题。

**Comment by millermoment** [comment]
我还以为这个问题要石沉大海了，没想到竟然第二天就能得到回复，nice。多谢解答。

Liu DongMiao <notifications@github.com> 于 2018年5月30日周三 21:53写道：
