### ISSUE TITLE
卡在奇怪的地方

### ISSUE THREAD

**Issue by Tommy0607** [brevent/Brevent#365]
遇到个bug，不知道其他人遇到过没有，就是用adb开启黑阈服务后不知道过了多久（可能几天可能几周吧），我发现很多应用后台没清理掉，便再打开黑阈，发现一直卡在这个对话框，然后用adb再次开启的话提示服务正在运行，问题还是没有解决，只能先修改一下usb模式或者重启一下重新再重新开启服务。这个情况已经出现多次了
日志文件：https://pan.baidu.com/s/1p5_Xq0lYfveJlJOh3DcviQ

**Comment by Tommy0607** [comment]
发不了图，这是图的链接：https://pan.baidu.com/s/1SovXQtC21ySPlJq2IIJM3g

**Comment by liudongmiao** [comment]
抱歉，我不接受其它站点日志及文件，因为真的下载麻烦。
您也可以直接发送邮件至 黑阈 邮箱。

我本人不处理与其它应用兼容性，也不处理系统误杀行为。
