### ISSUE TITLE
黑域一直卡在检查服务状态

### ISSUE THREAD

**Issue by TinkMingKing** [brevent/Brevent#366]
[server.20180602.0154.2159.txt](https://github.com/brevent/Brevent/files/2064627/server.20180602.0154.2159.txt)
问题类似#365，一直是检查服务状态页面，偶尔到获取进程状态，然后可能是失败，又到了提示root启动，然后基本就卡在检查服务状态了，补个日志

**Comment by TinkMingKing** [comment]
几分钟后，系统界面自动重启，网络调试自动打开，服务运行成功

**Comment by liudongmiao** [comment]
原因未知。

如果后续继续出现，我再给可能修复版本。
