### ISSUE TITLE
found brevent_daemon, pid: 11687

### ISSUE THREAD

**Issue by Iphigen1a** [brevent/Brevent#369]
[crash log.txt](https://github.com/brevent/Brevent/files/2065633/crash.log.txt)
* daemon not running; starting now at tcp:5037
* daemon started successfully
checking for server.......fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '06-03 11:57:41.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '06-03 11:57:41.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above
怎么会不够呢，就这么些啊

**Comment by liudongmiao** [comment]
no enough log
