### ISSUE TITLE
支付宝账单识别问题

### ISSUE THREAD

**Issue by Xander-Hou** [brevent/Brevent#372]
一年以上的账单无法识别；
且在已激活设备上尝试会被反激活为体验版。

LG G5 ＆ Micromax A311
7.1.2

订单号20170504200040011100520000352250

**Comment by liudongmiao** [comment]
https://www.jianshu.com/p/4aa39accd52c

**Comment by Xander-Hou** [comment]
？？？就是用这个方法被反激活的

**Comment by liudongmiao** [comment]
参照流程，目前没有实质无法识别的。
如果真无法识别，重现后黑阈 - 反馈，点按日志并描述。
