### ISSUE TITLE
启动后莫名关闭，后台允许启动，各种白名单

### ISSUE THREAD

**Issue by huozhecccc** [brevent/Brevent#374]
启动容易失败，再次打开就行了
Meizu/meizu_M3X/M3X:6.0.1/MMB29U/1517207688:user/release-keys

sh: <stdin>[2]: /data/data/me.piebridge.brevent/brevent.sh: can't execute: Permission denied
WARNING: run as root is experimental!!!
checking for server...started, pid: 26350
checking for stable..success

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by liudongmiao** [comment]
> WARNING: run as root is experimental!!!

您问我，我也不知道呢。我真的没有这种古董机器，手里的 flyme 没有出现过这种问题。
