### ISSUE TITLE
Settings backup

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#375]
Any plans for adding possibility to backup brevented apps settings?

**Comment by vvb2060** [comment]
backup：
```
cp /data/user_de/0/com.android.shell/me.piebridge.brevent.list  /sdcard/Documents/brevent.list
```
restore：
```
cp /sdcard/Documents/brevent.list  /data/user_de/0/com.android.shell/me.piebridge.brevent.list
kill -HUP `pidof brevent_server`
```
use `Exec command` to exec. Backup file in `sdcard/Documents/brevent.list` , only Brevent list.

**Comment by ghost** [comment]
thanks🙂 but this is only list of app.. no other settings like sync,fcm or set agressive

**Comment by vvb2060** [comment]
Of course also include them.

**Comment by liudongmiao** [comment]
There are many files under data directory of `com.android.shell`, you can just backup and restore them.
