### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Haruhikoo** [brevent/Brevent#376]
提供一个按时黑域的功能 比如在夜间自动黑域微信 减少夜间电量消耗也可做免打扰用

**Comment by vvb2060** [comment]
你可能更需要的是定时停用，请求冰箱等应用来实现会更好。
应用被黑阈后，离开应用超时后会待机，不再活跃超时后被强行停止。

**Comment by liudongmiao** [comment]
1. 不建议黑阈即时通讯类应用

2. 你大约需要开启其的夜间免收消息功能
