### ISSUE TITLE
地图应用锁屏导航失效

### ISSUE THREAD

**Issue by zl939144892** [brevent/Brevent#377]
用的高德地图导航，把屏幕关了，过一会就会说gps信号弱，然后打开屏幕会发现android的gps定位通知没了，但会立马又重新弹出来。希望针对导航类应用进行一下优化，谢谢。

**Comment by liudongmiao** [comment]
单纯使用黑阈不会这样，我也一直这样使用，没有什么问题。

黑阈不对 导航 特殊优化，通过其它渠道：
- 如果有不可取消的通知，黑阈不处理
- 如果有前台服务，黑阈不处理
- 如果为前台应用，黑阈不处理

导航时，以上全都符合。

**Comment by zl939144892** [comment]
好的, 我再研究研究吧
