### ISSUE TITLE
关于黑域微信的同时开启允许同步走GCM获取推送的问题

### ISSUE THREAD

**Issue by millermoment** [brevent/Brevent#378]
在当前版本的黑域下，请问那些支持GCM的app是否可以通过黑域该应用的同时开启“允许同步“来达到既能省电又能像APNs一样接受推送？在之前的几个版本中，通过上述的做法后的支持GCM的微信即使将微信从后台界面划去仍然能从GCM获取推送信息，这个版本突然就不行了，求解答，谢谢。

**Comment by liudongmiao** [comment]
微信不支持 FCM，但开启“允许同步”以后，仍有可能通过其它渠道被动运行从而接收消息。
对于支持 FCM 的其它应用，~开始~开启“允许同步”即可接收 FCM 消息。

此问题终结。

**Comment by millermoment** [comment]
了解，多谢了。

Liu DongMiao <notifications@github.com> 于 2018年6月17日周日 20:48写道：

**Comment by millermoment** [comment]
了解 多谢了

Liu DongMiao <notifications@github.com> 于 2018年6月17日周日 20:48写道：
