### ISSUE TITLE
三星s6 edge +有时没有重启手机，黑域会失效

### ISSUE THREAD

**Issue by DoveBoy** [brevent/Brevent#38]
三星手机，6.0官方系统，没有root，能正常开启黑域，但是有时手机没有重启，黑域还是会失效，试过开启黑域后关闭USB调试以及更改用于记录的缓冲区大小仍然无效，注意到切换网络（开关wifi，开关移动数据网络）貌似会很大可能性造成黑域失效，但有时切换网络也没有触发，不知道到底是什么原因造成的，请开发者看看

**Comment by vvb2060** [comment]
把日志缓冲调到最大，发现失效后按play商店底部的方法提取日志看看？重要是后面退出时的日志？

DoveBoy <notifications@github.com>于2017年6月9日周五 下午2:30写道：

**Comment by liudongmiao** [comment]
需要一点点日志嘛...

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。

**Comment by DoveBoy** [comment]
@liudongmiao 测试一个星期发现同时关闭USB调试和更改用于记录的缓冲区大小为16M就不会失效
