### ISSUE TITLE
"允许同步"描述建议换成"接收 GCM 通知"

### ISSUE THREAD

**Issue by XGHeaven** [brevent/Brevent#380]
允许同步的用处就是允许 GCM 接收通知，所以我觉得换成“接收 GCM 通知”的描述会更好一些。
而且允许同步会让人理解成系统的同步，允许唤醒进行同步用户状态，通讯等等内容。
这样会导致很多人不会选择允许同步，之后不开启允许同步的话，就会导致 GCM 异常。

**Comment by vvb2060** [comment]
允许同步就是允许进行系统同步(比如邮箱应用，还有你说的同步通讯录等等)，也允许被唤醒来短时间执行任务(比如FCM推送)。同时，允许同步的应用不会被待机，保证其能联网拉取信息。

如果系统支持FCM推送，允许同步的应用也支持FCM，其标志会由同步转换为云朵(FCM)。这仅仅是显示上的区别：提示你这个应用可以直接接收推送的消息。

**Comment by XGHeaven** [comment]
那有一个问题，如果允许同步，那么会不会导致被比如网络状态变更的事件唤醒之后就起了一些服务，然后就不会被待机不会被强制停止了？

还有就是能不能提供一个选项就是只允许接受 FCM 推送唤醒，不允许其他方式唤醒进行系统的同步。

**Comment by vvb2060** [comment]
允许同步的应用被唤醒以后允许存活 30 秒。
黑阈不改动系统，无法实现仅允许FCM唤醒，这是仅xposed能实现的功能。

**Comment by sxml** [comment]
允许同步不会被待机 停止这问题不止我一个人
