### ISSUE TITLE
Just want to confirm the charges

### ISSUE THREAD

**Issue by kuyeduwu** [brevent/Brevent#381]
I have used brevent for free for a long time, and it really makes my Nexus 6P great again. But in the recent days, every time I wanted to brevent an app, a window will pop up asking me to donate some money. I know brevent is a great app and I would like to donate some money to make it better, but before that, I want to confirm something:
1. Is this approved by the author? I want to confirm this since previously there was an accident that a developer lost his control on a chrome add-in in chrome store, another developer make this add-in non-free and added some bad code. Since brevent has been free for a long time, it feel abnormal to see this pop up.
2. From the wording in the pop up, looks the donation is optional, but I could not brevent an app if I click "Cancel", if it is mandatory, why wouldn't you make it obviously like “to brevent more apps, you need to pay some money".
3. For now, I have brevented around 30 apps and it asks for 3 Brefoil, is the price based on the number of brevented apps? If yes, where could I find the detailed pricing plan? I feel comfortable to pay some money to a great app, even in monthly subscription, but the surprising pop up makes me uncomfortable, and if I paid this time, I actually don't want to be surprised again in the future.

**Comment by liudongmiao** [comment]
1. for price, refer here: https://jianyu.io/br/price.en.html
There are link in app too.

2. normally, you have no chance to update manually:
Brevent add new apps to brevent list automatically
However, if you unbrevent an app, then brevent...

3. there is free way to use for chinese locale.
