### ISSUE TITLE
经常自动退出

### ISSUE THREAD

**Issue by amos19911023** [brevent/Brevent#382]
没有重启，也没有关闭或修改USB调试、选项
Android版本6.0.1

**Comment by vvb2060** [comment]
请提供日志。发现退出后再次启动黑阈服务，点按反馈-日志按钮保存日志，使用GitHub编辑框上传功能上传压缩包。

**Comment by amos19911023** [comment]
[logs-v3.2.7.2-20180623.0016.zip](https://github.com/brevent/Brevent/files/2128406/logs-v3.2.7.2-20180623.0016.zip)

**Comment by liudongmiao** [comment]
很奇怪的异常...请稍后看下 3.3.0-beta5

**Comment by liudongmiao** [comment]
> notification_enqueue, data: {uid=sound completion :content://settings/system/notification_sound}

你系统发送了一个不正常的事件，然后就....这种问题，不应该发生。
