### ISSUE TITLE
英文环境下，点头像旁边的问号，跳转的还是中文帮助

### ISSUE THREAD

**Issue by pzcn** [brevent/Brevent#384]
发现简域官网是有英文版本价格说明的，但是不论是黑阈内设置英文，还是系统设置成英文，点问号还是会跳转到中文版价格说明页面。

**Comment by vvb2060** [comment]
目前黑阈的最新稳定版本为3.2.7.2，你所使用的版本是？

**Comment by PedroZhang** [comment]
3.3.0alpha3 版本的原因吗..

**Comment by vvb2060** [comment]
我这里，stable和alpha版都无法复现…

**Comment by liudongmiao** [comment]
感谢使用支付宝支付。

只要使用支付宝支付过，或当前为中文，就跳转到中文页面。
