### ISSUE TITLE
麻烦退款谢谢

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#385]
收了钱连个认证服务器都不搞，你这服务收的钱比谁都贵。
~删除隐私信息~

**Comment by liudongmiao** [comment]
退款请参照：https://www.jianshu.com/p/87aa6245d814
从截图看，您已超出退款时限。

您可继续按流程申请退款，但会按“恶意退款”对待。

**Comment by Lather0519** [comment]
厉害，自己的垃圾软件没法给我认证，然后还要设置退款时限。明明写着如果一直无法确认购买可以退款，现在就给我来个恶意退款，国产就是国产，厉害厉害

**Comment by ghost** [comment]
@liudongmiao 
我是因为无法认证才申请退款，刚才发现了新的认证方式已经解决了。
①现在的问题是之前可以自动黑域的现在不可以是什么原因？
②在支付宝买了18元，现在想升级到30元，应该如何操作才能正确识别我已付款30元？

![screenshot_2018-06-25-16-25-37-357_com android settings](https://user-images.githubusercontent.com/32637838/41839175-183556f0-7895-11e8-9b4d-c00c5fb717a2.png)

**Comment by liudongmiao** [comment]
1. 自动黑阈 就是看有没有事件日志...这个与设备相关。
必要时，你可以直接 重新启动 黑阈服务看看

2. 直接继续支付就好。
应该会自动填好差额。
