### ISSUE TITLE
关于各种图标代表意义的问题

### ISSUE THREAD

**Issue by millermoment** [brevent/Brevent#387]
比如微博的暂停图标，Facebook的三角箭头图标，某些APP比如掌盟的斜杠加闹钟图标，还有一片云，一颗爱心等等这些都是什么意思呢？建议出一张图形含义对照表，如果可以的话。希望开发者在百忙之中如果看到我的这个问题麻烦解答一下，非常感谢。

**Comment by liudongmiao** [comment]
阅读简单中使用文档链接：https://jianyu.io/br/br.pdf

**Comment by millermoment** [comment]
非常感谢！希望黑域越来越完善，越做越好。

Liu DongMiao <notifications@github.com> 于 2018年6月26日周二 10:19写道：
