### ISSUE TITLE
对音乐软件Retro Music的优化

### ISSUE THREAD

**Issue by IceFucker** [brevent/Brevent#389]
Retro Music在后台运行的时候会被黑域暂停

**Comment by vvb2060** [comment]
黑阈不专门针对某应用进行特殊处理，而是使用统一规则。
Retro Music一个本地音乐播放器，播放时自动暂停…黑阈不至于无聊到做这种事。
建议排查其它情况，怀疑黑阈有问题请使用反馈-日志功能保存并上传日志，直接把压缩包拖动到GitHub输入框即可上传。

**Comment by vvb2060** [comment]
无回应，关闭。
可能是其它应用播放媒体音频，被抢占的缘故。
