### ISSUE TITLE
Android 6.0无法使用root打开

### ISSUE THREAD

**Issue by stp88888** [brevent/Brevent#39]
sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh           <
WARNING: run as root is experimental!!!
checking............cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '06-10 19:15:04.000' -d
06-10 19:15:04.911 10641 10641 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
06-10 19:15:04.911 10641 10641 E AndroidRuntime: java.lang.reflect.InvocationTargetException
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2021)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
06-10 19:15:04.911 10641 10641 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1626)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:3512)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at me.piebridge.brevent.server.e.a(HideApi.java:156)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.f(BreventServer.java:338)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:237)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1909)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        ... 4 more
06-10 19:15:04.911 10641 10641 E AndroidRuntime: Error reporting crash
06-10 19:15:04.911 10641 10641 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4534)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
06-10 19:15:04.911 10641 10641 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-10 19:15:04.000' -d -s BreventLoader BreventServer
06-10 19:15:04.543 10631 10631 D BreventLoader: loader path: /data/app/me.piebridge.brevent-3/base.apk
06-10 19:15:04.866 10641 10641 D BreventServer: get service: package: android.os.BinderProxy@41a3d69
06-10 19:15:04.885 10641 10641 I BreventServer: starting Brevent Server 1.2.3
06-10 19:15:04.891 10641 10641 D BreventServer: get service: package: android.os.BinderProxy@41a3d69
06-10 19:15:04.893 10641 10641 I BreventServer: brevent user: 0, uid: 0
06-10 19:15:04.894 10641 10641 I BreventServer: brevent data directory: /data/user/0/com.android.shell
06-10 19:15:04.917 10631 10631 E BreventLoader: worker 10641 exited on signal 9
06-10 19:15:04.917 10631 10631 D BreventLoader: signal arrived, update: 0
06-10 19:15:04.918 10627 10627 D BreventLoader: worker 10631 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above
1|root@le_zl1:/ #

**Comment by liudongmiao** [comment]
你是否限制了获取安装软件的列表？

执行以下指令看看 pm list packages --user 0

一般来说，不对 root 方式提供任何支持。如果需要，请电脑上安装 teamviewer，约好时间，发送 id 与密码到邮箱。

**Comment by stp88888** [comment]
u0_a72@le_zl1:/ $ pm list packages --user 0
package:com.letv.android.FuseWire
package:com.sorcerer.sorcery.iconpack
package:com.google.android.youtube
package:com.qualcomm.qti.auth.sampleextauthservice
package:com.oasisfeng.greenify
package:com.android.providers.telephony
package:com.letv.android.agent
package:com.google.android.googlequicksearchbox
package:com.letv.android.theme
package:com.android.providers.calendar
package:com.sollyu.xposed.hook.model
package:com.android.providers.media
package:com.softsim.control
package:com.sabik.assistantenabler
package:gavinhua.zhuishushenqicracked
package:com.qti.service.colorservice
package:com.google.android.onetimeinitializer
package:com.eui.sdk.appupgrade
package:com.qualcomm.qti.modemtestmode
package:com.qualcomm.shutdownlistner
package:com.sohu.inputmethod.sogou
package:com.android.wallpapercropper
package:com.teslacoilsw.launcher
package:com.quicinc.cne.CNEService
package:com.letv.android.wallpaper
package:com.youku.phone
package:com.letv.leui.schpwronoff
package:me.gfuil.bmap
package:air.tv.douyu.android
package:com.redteamobile.virtual.softsim
package:com.speedsoftware.rootexplorer
package:org.simalliance.openmobileapi.service
package:com.dolby.daxappUI
package:com.letv.android.wallpaperonline
package:com.letv.android.letvsafe
package:com.android.externalstorage
package:cn.wq.myandroidtoolspro
package:com.lerist.go_hosts
package:com.letv.android.themesettings
package:com.android.mms.service
package:com.ushaqi.zhuishushenqi
package:me.piebridge.forcestopgb
package:com.android.providers.downloads
package:com.qualcomm.qti.auth.sampleauthenticatorservice
package:com.le.android.webview
package:com.zeusis.mmi
package:com.linangran.nowakelock
package:com.qualcomm.qti.telephonyservice
package:com.letv.android.usagestats
package:com.google.android.configupdater
package:com.letv.wihd.sample
package:com.ChillyRoom.DungeonShooter
package:com.android.defcontainer
package:de.robv.android.xposed.installer
package:com.lenovo.fido.uafclient
package:com.android.providers.downloads.ui
package:com.android.vending
package:com.android.pacprocessor
package:in.zhaoj.shadowsocksr
package:com.fkzhang.qqxposed
package:com.tencent.mm
package:com.android.vendors.bridge.softsim
package:com.sankuai.meituan.takeoutnew
package:com.letv.android.freeflow
package:com.android.certinstaller
package:com.android.carrierconfig
package:com.mhook.alipay
package:com.letv.android.euitransfer.appdata
package:com.qti.qualcomm.datastatusnotification
package:android
package:com.android.contacts
package:com.android.camera2
package:com.letv.android.appdataprovider
package:com.qualcomm.wfd.service
package:com.flyersoft.moonreaderp
package:com.qualcomm.qti.GBAHttpAuthentication.auth
package:com.letv.android.telextra
package:me.piebridge.brevent
package:com.tencent.token
package:com.android.mms
package:com.android.nfc
package:com.android.stk
package:com.android.launcher3
package:com.hlinapp.drawcal
package:com.ceco.marshmallow.gravitybox
package:com.baidu.location.fused
package:cn.com.shouji.market
package:com.android.backupconfirm
package:com.letv.android.systemreport
package:com.icbc
package:com.fkzhang.wechatxposed
package:com.letv.android.backup
package:org.codeaurora.ims
package:com.android.statementservice
package:com.letv.android.setupwizard
package:cn.wq.myandroidtoolsxposed
package:com.android.wallpaper.holospiral
package:com.android.calendar
package:com.letv.android.remotedevice
package:com.letv.android.backupclient
package:com.apkpure.aegon
package:com.qualcomm.qti.auth.secureextauthservice
package:org.adaway
package:com.google.android.setupwizard
package:com.qti.primarycardcontroller
package:com.qualcomm.qcrilmsgtunnel
package:com.android.providers.settings
package:bin.xposed.Unblock163MusicClient
package:com.android.sharedstoragebackup
package:com.android.printspooler
package:com.android.dreams.basic
package:com.android.frameworks.telresources
package:com.dv.adm.pay
package:com.android.mp
package:com.android.inputdevices
package:com.jumobile.manager.systemapp
package:com.qualcomm.qti.auth.securesampleauthservice
package:com.qti.dpmserviceapp
package:com.mxtech.videoplayer.ad
package:com.dropbox.android
package:com.kapp.ifont
package:com.qti.xdivert
package:com.twitter.android
package:com.android.musicfx
package:com.android.VRAdmin
package:com.google.android.apps.docs
package:com.letv.gallery3d.syncservice
package:com.letv.bugpostbox
package:com.xesygao.puretie
package:com.google.android.webview
package:com.downloading.main.baiduyundownload
package:com.android.qrd.engineeringmode
package:com.lvr.wizzard
package:com.android.server.telecom
package:com.google.android.syncadapters.contacts
package:com.theme.mumu.flat
package:com.android.keychain
package:mark.via
package:com.android.dialer
package:com.letv.domain
package:com.google.android.gms
package:com.google.android.gsf
package:com.google.android.tts
package:com.android.calllogbackup
package:com.google.android.partnersetup
package:com.tencent.mobileqq
package:com.android.packageinstaller
package:com.svox.pico
package:com.dsi.ant.server
package:com.letv.android.mobileactivation
package:com.android.proxyhandler
package:com.willme.topactivity
package:net.typeblog.webview
package:com.letv.agnes
package:com.google.android.feedback
package:com.letv.android.supermanager
package:com.google.android.apps.photos
package:com.letv.android.powercontroller
package:com.android.vending.billing.InAppBillingService.LOCK
package:com.google.android.syncadapters.calendar
package:com.android.managedprovisioning
package:com.mediatek.calendarimporter
package:com.letv.wihd
package:com.zhihu.android
package:com.irtest.letv
package:com.google.android.gsf.login
package:com.android.smspush
package:com.letv.android.accountinfo
package:com.coolapk.market
package:com.letv.wallet
package:com.android.wallpaper.livepicker
package:com.romide.terminal
package:com.zeusis.factorytest
package:com.android.apps.tag
package:me.iacn.bilineat
package:com.letv.roaming
package:com.letv.leui.widget.leclipboardapp
package:com.dolby
package:com.haxor
package:com.ghostflying.locationreportenabler
package:com.baidu.map.location
package:com.letv.factorymode
package:com.letv.android.filemanager
package:com.letv.android.StateInfo
package:com.google.android.apps.translate
package:com.google.android.backuptransport
package:com.sutui.stat
package:eu.thedarken.sdm
package:com.android.settings
package:com.qualcomm.qti.ims
package:com.letv.android.ecoProvider
package:com.quicinc.wbcserviceapp
package:com.google.android.apps.inbox
package:com.qualcomm.location
package:com.taobao.idlefish
package:com.le.webview
package:com.letv.android.gallery3d.filtershow.stereo
package:com.qualcomm.qti.tetherservice
package:ztc1997.vibrationtuner
package:pl.idreams.SkyForceReloaded2016
package:com.qualcomm.qti.securemsm.mdtp
package:com.haifer.qingyoureader
package:com.android.wallpaper
package:com.qualcomm.qti.services.secureui
package:com.letv.android.privacydata
package:com.android.vpndialogs
package:eu.chainfire.supersu
package:com.android.phone
package:com.android.shell
package:com.android.providers.userdictionary
package:com.qualcomm.qti.RIDL
package:com.android.location.fused
package:com.android.deskclock
package:com.android.systemui
package:com.android.exchange
package:com.letv.bsp.qccrashhandler
package:com.android.bluetoothmidiservice
package:com.qualcomm.qti.networksetting
package:sina.mobile.tianqitongletv
package:com.qualcomm.fastdormancy
package:com.qualcomm.qti.auth.fidosuiservice
package:com.taobao.taobao
package:com.qualcomm.qti.biometrics.voiceprint.service
package:com.android.bluetooth
package:com.qualcomm.timeservice
package:com.lenovo.fido.asm
package:com.qualcomm.embms
package:com.android.providers.contacts
package:com.netease.cloudmusic
package:tv.danmaku.bili
package:com.android.captiveportallogin
package:com.eg.android.AlipayGphone
package:com.chaozh.iReader
package:cn.wps.moffice_eng
package:com.letv.android.LetvShareProvider
package:com.letv.android.phonecontrol
u0_a72@le_zl1:/ $


另外邮箱是多少呀

**Comment by liudongmiao** [comment]
以 root 身份执行上述结果。

你连接上的是 shell，那么这时直接以  adb 启动黑域也是可以的。

**Comment by stp88888** [comment]
root@le_zl1:/ # pm list packages --user 0
Error: java.lang.NullPointerException: Attempt to get length of null array

**Comment by liudongmiao** [comment]
所以，先找你的 root 提供商，解决原生指令无法使用问题。

如果 root 本身不能执行，那么黑域也是不能执行的。

**Comment by liudongmiao** [comment]
这种情况，你可以禁用 selinux 看看。

**Comment by stp88888** [comment]
selinux是宽容模式，permissive

**Comment by liudongmiao** [comment]
这个问题无法解决，属于 su 实现或类似问题。
请使用 adb 普通权限。

**Comment by liudongmiao** [comment]
@stp88888 看看最新测试版吧。

**Comment by stp88888** [comment]
可以了。
