### ISSUE TITLE
三星s6国行Android6.0系统状态不支持待机吗？

### ISSUE THREAD

**Issue by tenwx** [brevent/Brevent#394]
RT，待机理论上是从6.0开始就引入的，为何s6却不支持呢？
另外显示框架应用是灰色的，下面写着“卧槽，所有应用都是框架应用”，我的手机只是用supersu root了下，难道这样就会有兼容问题么？

**Comment by liudongmiao** [comment]
1. 是否待机，需要 rom 自行适配，黑阈使用系统数据。

2. 自行检阅是否开启 核心破解 之类，黑阈使用系统 api 检查框架应用。
如果黑阈发现自己也是框架应用，就会认为所有应用都是框架应用。
