### ISSUE TITLE
优化微信能否考虑支持双开微信

### ISSUE THREAD

**Issue by eldonly** [brevent/Brevent#396]
例：多开微信，基于Android for Work（如MIUI多开，Island，一加多开）

问题1：黑阈微信会同时黑阈掉多开的微信，这个正常。
问题2：GCM会无法区分应用；
比如微信A和微信B，微信B为被多开应用，收到GCM推送后，都是通过包名打开的微信A。
结果：黑阈微信并开启优化微信并从最近任务列表划掉微信后，微信a可以通过fcm实时收消息，微信b则必须打开微信界面后，才能收到消息。

**Comment by vvb2060** [comment]
问题一：黑阈仅处理主用户应用，不会处理其它用户。
问题二：Google服务能区分多用户。
结果：黑阈的优化微信仅供测试，只是尽可能让微信能接收消息，不是修改微信。不要依赖此功能，微信设计问题不是黑阈能修改的。

**Comment by liudongmiao** [comment]
黑阈不支持工作使用，也不会支持工作模式。

**Comment by liudongmiao** [comment]
另外，黑阈只会处理 主账号 里的应用。

**Comment by cs-usst** [comment]
@eldonly 想问一下您在android for work里面有登录google账号吗？我在android for work里的微信收不到gcm推送

**Comment by eldonly** [comment]
不好意思回复晚了。android for work里面我没有登录google账号。
我已经放弃FCM接收微信了，感觉还是微信本身的长连接更加稳定和可靠。

At 2019-10-14 19:03:15, "cs-usst" <notifications@github.com> wrote:


@eldonly 想问一下您在android for work里面有登录google账号吗？我在android for work里的微信收不到gcm推送
