### ISSUE TITLE
关于开启“优化音乐类应用”失效

### ISSUE THREAD

**Issue by komazhy** [brevent/Brevent#397]
1.黑阈最新版，已经支付18元，点击设置的微信图标，显示需支付12元，这个是什么意思？
2.动态GMS和优化微信是灰色状态，是否说明还需继续支付？
3.开启优化音乐类应用后，喜马拉雅FM在锁屏后会暂停运行。

**Comment by liudongmiao** [comment]
1. 黑阈可以一直付费..你付过以后，会默认关闭“显示支付”

2. 这两个功能标明实验性，实验性阶段需要 5 二向箔，以免误付
https://jianyu.io/br/price.zh.html

3. 我不认为 优化音乐 会暂停其它应用。
如果您认为有，就不要开启，也不要黑阈这个应用。
