### ISSUE TITLE
搜索框问题

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#399]
搜索框有内容时，快速三击搜索结果的应用名称会导致返回

**Comment by vvb2060** [comment]
测试结果：快速点按三次 应用图标 会退出搜索。

**Comment by liudongmiao** [comment]
暂时不处理了。这个过程是这样子的。

1. 搜索

2. 刷新结果。
当快速处理时，在异步刷新结果的时候，发现当前不在搜索，于是刷新全局结果，就是退出搜索了。
