### ISSUE TITLE
柳大帮我看看吧，为什么微信走GCM唤醒很难。

### ISSUE THREAD

**Issue by wt670280793** [brevent/Brevent#4]
_好想知道，为嘛微信走GCM，在426可以看到消息过来，并且广播了微信，但就是拉不起来微信呢？或者要等半天不即时，又或者收到几个消息后才拉得动微信通知。琢磨了半天就是搞不明白，明明GCM有消息并且给微信广播了，但就是慢或者没有反应。 
![screenshot_20170523-173843](https://cloud.githubusercontent.com/assets/26296311/26362380/53012804-4010-11e7-95be-5f4f4f32a3c5.png)
![screenshot_20170523-232457](https://cloud.githubusercontent.com/assets/26296311/26362384/5371ef94-4010-11e7-841d-bf801386e6c9.png)
![screenshot_20170523-232506](https://cloud.githubusercontent.com/assets/26296311/26362382/530a0ae6-4010-11e7-8131-86c225fbc9a4.png)
![screenshot_20170523-232516](https://cloud.githubusercontent.com/assets/26296311/26362381/5307ae36-4010-11e7-967f-0599c3d1f19b.png)
![screenshot_20170523-232642](https://cloud.githubusercontent.com/assets/26296311/26362383/530df264-4010-11e7-86af-f17cc228934e.png)

**Comment by liudongmiao** [comment]
微信不是标准 FCM，所以没有意义。

如果你实在要在黑域内测试，就黑域它，允许同步，把它放后台，不要从最近列表划掉它。
等到它待机。

否则，没有任何意义。之前文章：www.jianshu.com/p/efdc9e6c2935

对于微信的 FCM，能用就用，不能用就不要用。否则，就是浪费你我的时间。
