### ISSUE TITLE
某些情况下支付宝无法自动停止

### ISSUE THREAD

**Issue by dfliaoyue** [brevent/Brevent#40]
似乎在充电情况下使用完支付宝后，有可能会出现每次打开黑域时支付宝运行时间会自动重置。拔掉充电线后，支付宝可以进入standby模式，但经常出现一直不停止运行的情况。
此外，在暂时不确定的情形下，支付宝会保持在前台，可能也和充电时使用有关。比如现在有支付宝的服务运行了6小时，似乎是从拔出电源线开始计时，充电时使用过支付宝。另一服务运行了3小时多，那个时间点应该是开始插上了电源线，但没有开过支付宝。

**Comment by liudongmiao** [comment]
不正常 back 也会这样。

请暂时强行停止这些应用，然后强行停止启动器。

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
