### ISSUE TITLE
黑域 2.1.3a-24-ga6bc490(Android zh_CN_#Hans-7.0)

### ISSUE THREAD

**Issue by songwenjie123** [brevent/Brevent#40]
HONOR/KNT-UL10/HWKNT:7.0/HUAWEIKNT-UL10/C00B385:user/release-keys
作者您好，在使用黑域兼绿色守护的过程中，通知栏跳出百度地图与斗鱼直播的消息提示，打开黑域并未显示两个软件在工作

**Comment by songwenjie123** [comment]
打开绿色守护，显示斗鱼直播，掌上英雄联盟，QQ游戏三个软件正在工作。通知栏上消息并未自动消失。发送邮件的前几分钟又出现了上述情况，让人非常困扰

**Comment by songwenjie123** [comment]
作者的邮箱是多少，我发送日志吧

**Comment by liudongmiao** [comment]
黑域内点日志，你需要安装一个邮件客户端。

**Comment by liudongmiao** [comment]
另外，请不要以其它应用显示的“正在工作”为准。
如果你在黑域报告问题，请使用黑域内的状态，或者使用系统下列状态为准：

- `ps`
- `dumpsys activity processes`
- 设备中正在运行的服务，或者缓存进程

**Comment by liudongmiao** [comment]
此外，通知的话，请给 `dumpsys notification` 结果。
这个输出很多，你自己看 NotificationRecord 的吧。
