### ISSUE TITLE
拔掉数据线后，立马无法使用？

### ISSUE THREAD

**Issue by JZLeung** [brevent/Brevent#400]
在电脑终端执行了 shell 脚本。
![](https://ws2.sinaimg.cn/large/006tNc79gy1ftank054e4j30vw0ckadj.jpg)

然后拔掉数据线，就立马弹出这个框，不拔数据线没有问题。
![](https://ws2.sinaimg.cn/large/006tNc79gy1ftanjm58w6j30u01rcwgf.jpg)

机型： Nokia x6
root： 未 root
android版本： 8.1
内核版本： 4.4.87

**Comment by JZLeung** [comment]
已经将黑阈允许自动唤醒和锁屏保留。

![image](https://user-images.githubusercontent.com/7995232/42732305-b959a1fa-8851-11e8-958a-69a1d33f3c79.png)

**Comment by vvb2060** [comment]
Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。 
如果依旧无效，执行` adb tcpip 3035  `后再拔线。

**Comment by drinmo** [comment]
> Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。
> 如果依旧无效，执行`adb tcpip 3035 `后再拔线。

一加6T，系统9.0，黑阈专业版
问题与上述一样，锁屏后重新开屏显示 服务失效 。

解决操作：
USB 选项 设置成：默认（无任何操作）；
USB 调试 打√后，打死不碰；
在电脑**拔线**前最后执行：.\adb tcpip 3035

现在已经过了五分钟，反复锁屏开屏，问题暂时解决。

**Comment by Prurite** [comment]
遇到同样问题
而且我是执行 adb tcpip 3035 后立马无法使用……
华为麦芒7

**Comment by liudongmiao** [comment]
请不要开启网络调试。

华为请在开发者选项中开启“仅充电模式下允许 ADB 调试”。


https://support.qq.com/products/41738/faqs/39058
