### ISSUE TITLE
关于手机黑域后无法显示黑域主页面

### ISSUE THREAD

**Issue by crazy2379663** [brevent/Brevent#402]
手机型号:三星G925P   软件型号:安卓7.0
黑域版本:3.3.2
问题:黑域后当再次进入黑域时一直显示需要黑域，可消息提示却显示黑域正常运行，且在adb中发现已经开启。手机开发模式并没有设置后台强制停止，且黑域一直处于运行状态。

**Comment by vvb2060** [comment]
检查是否限制了黑阈访问本地网络

**Comment by crazy2379663** [comment]
并没有限制。

**Comment by liudongmiao** [comment]
没法理解你说的事情。请使用黑阈界面提示的用语。
