### ISSUE TITLE
关于新版本黑域看法

### ISSUE THREAD

**Issue by crazy2379663** [brevent/Brevent#403]
首先对于黑域的强大功能表示满意。其次，对于后期新版本黑域对手机软件的分类表示有些不解，尤其是对本机内部系统软件无法进行黑域和停止服务。
    总体使用来看，表示希望后期版本能像3.0.2版本的简易操作看齐，本人对于耗电这方面略有些在意。希望谅解。

**Comment by vvb2060** [comment]
保持设置默认，不要开启高级功能，不懂的黑阈功能也不用开启。

**Comment by eddielau0** [comment]
有个问题 急急急 ，为什么我连上电脑开启黑域以后 ，只要一拔掉数据线就会显示未启动服务 - LG v30 （以往都能正常开启的） 忘恢复一下  不胜感激 orz

**Comment by vvb2060** [comment]
@WalterMittyC Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。
如果依旧无效，执行`adb tcpip 3035`后再拔线。

**Comment by eddielau0** [comment]
@vvb2060 执行那行代码起效了  真的非常感谢 ：)

**Comment by liudongmiao** [comment]
你说的是 操作系统应用 吧，这是后来新增的。
对于部分应用，确实不提供 黑阈 或 停止。
前者，是因为强行停止，又会启动，只会更费电；
后者，属于底层服务，黑阈不提供作死行为。
如果要作死，可以直接卸载，或者使用黑阈的执行指令，如 `pm disable-user <包名>`
