### ISSUE TITLE
can't pay "" payment is not available

### ISSUE THREAD

**Issue by wizardt** [brevent/Brevent#404]
It says " Payment is not available"

**Comment by liudongmiao** [comment]
Please make sure Play store is available.

**Comment by wizardt** [comment]
国产手机没有store，有支付宝

**Comment by liudongmiao** [comment]
https://www.jianshu.com/p/4aa39accd52c

目前支持两种方式：

1. 微信
仅限中文环境，以及非 play 商店分发版本

2. play 商店
