### ISSUE TITLE
3.3.5.3版本更新后，google play无限闪退

### ISSUE THREAD

**Issue by libra7012** [brevent/Brevent#406]
更新最新版后打开google play过一会儿闪退，之后打开立刻闪退，退回到3.3.4版无问题。

**Comment by vvb2060** [comment]
你应该黑阈了一些不该黑阈的应用。
现在取消了“内容提供器”型依赖检查，并且会提示哪些应用不可打开是否取消黑阈。

**Comment by liudongmiao** [comment]
3.3.5.X 取消了“内容提供器”型依赖检查。
你可以进入黑阈，看是否提示“已经黑阈不可取消应用”之类。

另外，你也可以复现，黑阈 - 反馈 - 日志，并详细说明问题。

取消这个依赖，是因为发现好多例使用“内容提供器”来作为依赖，以逃避黑阈检查的恶意应用。
