### ISSUE TITLE
优化音乐类应用部分失效

### ISSUE THREAD

**Issue by zvx4** [brevent/Brevent#408]
网易云音乐，黑阈最新版,sony xperia xz F8332。
以前网易云在后台横划关闭，只要下拉栏播放条还在就能继续播放，现在后台不关能在黑阈里看到有个标志不会黑阈，而关闭就会直接进程消失音乐停止。
反馈可能写得不标准还请见谅。

**Comment by vvb2060** [comment]
重复此现象后，在黑阈应用内，点按反馈-日志，将压缩包保存并上传，拖放文件到GitHub编辑框内即可上传。

**Comment by zvx4** [comment]
Sony/F8332/F8332:8.0.0/41.3.A.2.157/1629700793:user/release-keys
[logs-v3.3.8.1-20180808.2201.zip](https://github.com/brevent/Brevent/files/2270528/logs-v3.3.8.1-20180808.2201.zip)

**Comment by liudongmiao** [comment]
使用最新版本，再测试。
