### ISSUE TITLE
打开黑域以后手机提示 网络连接超时 稍后再试

### ISSUE THREAD

**Issue by klbbsue** [brevent/Brevent#409]
打开黑域以后手机提示 网络连接超时 稍后再试

**Comment by klbbsue** [comment]
具体是哪个应用出现问题我也无法判断

**Comment by liudongmiao** [comment]
待机以后，是正常现象。

**Comment by klbbsue** [comment]
更新后会提示我建议取消黑域 请问怎么操作

Liu DongMiao <notifications@github.com> 于 2018年8月10日周五 下午9:04写道：

**Comment by liudongmiao** [comment]
很多人不明白推荐取消黑阈的初衷。

1. 短时间内不断强行停止，要么是流氓，要么是真的需要。

2. 对于流氓，建议卸载或停用（再不济，可以开启激进）；对于常用，建议取消黑阈。允许同步应用也可能不断启动多次，但不会统计在内。

补充说明：

1> 主动打开应用后，计数清零
2> 默认不会提示允许同步，或者激进应用
3> 15 次以后每 3 次提示，30 次以后归零
4> 频率 4 分钟提示 取消，2 分钟且开启停用提示 停用；仅提示，不操作。

3. 发现误报怎么办。收起高贵的评论，黑阈内反馈，带上日志。

4. 不想看通知怎么办。有通知类别，自己关闭；也有全局开关，自己看改动日志。
