### ISSUE TITLE
XX  应用时间自动归零

### ISSUE THREAD

**Issue by Hidarihitomi** [brevent/Brevent#41]
以下为日志
08-21 22:03:28.063 21004 21004 D BreventServer: check again in 3600s
08-21 22:03:28.063 21004 21004 D BreventServer: check and brevent, took 262ms
08-21 22:03:53.270 21004 21004 D BreventServer: check and brevent
08-21 22:03:53.531 21004 21004 I BreventServer: won't block com.github.shadowsocks, depended by {com.android.systemui}
08-21 22:03:53.533 21004 21004 D BreventServer: audio: {}
08-21 22:03:53.533 21004 21004 D BreventServer: audioPaused: {}
08-21 22:03:53.534 21004 21004 D BreventServer: standby moe.reimu.weiboxposed
08-21 22:03:53.534 21004 21004 D BreventServer: standby com.android.documentsui
08-21 22:03:53.535 21004 21004 D BreventServer: standby com.android.mtp
08-21 22:03:53.536 21004 21004 D BreventServer: standby com.android.printspooler
08-21 22:03:53.537 21004 21004 D BreventServer: standby com.android.cellbroadcastreceiver
08-21 22:03:53.538 21004 21004 D BreventServer: standby com.google.android.gsf
08-21 22:03:53.539 21004 21004 D BreventServer: standby com.google.android.partnersetup
08-21 22:03:53.540 21004 21004 D BreventServer: standby com.svox.pico
08-21 22:03:53.542 21004 21004 D BreventServer: standby com.google.android.GoogleCamera
08-21 22:03:53.542 21004 21004 D BreventServer: check again in 3600s
08-21 22:03:53.542 21004 21004 D BreventServer: check and brevent, took 271ms
08-21 22:03:59.322 21004 21004 D BreventServer: check and brevent
08-21 22:03:59.609 21004 21004 D BreventServer: audio: {}
08-21 22:03:59.609 21004 21004 D BreventServer: audioPaused: {}
08-21 22:03:59.609 21004 21004 D BreventServer: standby com.github.shadowsocks
08-21 22:03:59.610 21004 21004 D BreventServer: standby moe.reimu.weiboxposed
08-21 22:03:59.611 21004 21004 D BreventServer: standby com.android.documentsui
08-21 22:03:59.611 21004 21004 D BreventServer: standby com.android.mtp
08-21 22:03:59.612 21004 21004 D BreventServer: standby com.android.printspooler
08-21 22:03:59.612 21004 21004 D BreventServer: standby com.android.cellbroadcastreceiver
08-21 22:03:59.613 21004 21004 D BreventServer: standby com.google.android.gsf
08-21 22:03:59.613 21004 21004 D BreventServer: standby com.google.android.partnersetup
08-21 22:03:59.614 21004 21004 D BreventServer: standby com.svox.pico
08-21 22:03:59.614 21004 21004 D BreventServer: standby com.google.android.GoogleCamera
08-21 22:03:59.615 21004 21004 D BreventServer: check again in 3600s
08-21 22:03:59.615 21004 21004 D BreventServer: check and brevent, took 291ms
08-21 22:04:02.629 21004 21004 D BreventServer: update current to com.teslacoilsw.launcher
08-21 22:04:02.630 21004 21004 D BreventServer: previous: com.tencent.mobileqq, packageName: com.teslacoilsw.launcher
08-21 22:04:05.234 21004 21004 D BreventServer: update current to yarolegovich.materialterminal
08-21 22:04:05.630 21004 21004 D BreventServer: check and brevent
08-21 22:04:05.829 21004 21004 D BreventServer: audio: {}
08-21 22:04:05.829 21004 21004 D BreventServer: audioPaused: {}
08-21 22:04:05.829 21004 21004 D BreventServer: standby com.github.shadowsocks
08-21 22:04:05.830 21004 21004 D BreventServer: standby moe.reimu.weiboxposed
08-21 22:04:05.830 21004 21004 D BreventServer: standby com.android.documentsui
08-21 22:04:05.831 21004 21004 D BreventServer: standby com.android.mtp
08-21 22:04:05.831 21004 21004 D BreventServer: standby com.android.printspooler
08-21 22:04:05.832 21004 21004 D BreventServer: standby com.android.cellbroadcastreceiver
08-21 22:04:05.833 21004 21004 D BreventServer: standby com.google.android.gsf
08-21 22:04:05.833 21004 21004 D BreventServer: standby com.google.android.partnersetup
08-21 22:04:05.833 21004 21004 D BreventServer: standby com.svox.pico
08-21 22:04:05.834 21004 21004 D BreventServer: standby com.google.android.GoogleCamera
08-21 22:04:05.834 21004 21004 D BreventServer: check again in 3600s
08-21 22:04:05.834 21004 21004 D BreventServer: check and brevent, took 203ms

**Comment by liudongmiao** [comment]
你自己看看，在这里有找到 bi 么？

**Comment by Hidarihitomi** [comment]
知道找不到啊，酷安有发gif图，确实存在

**Comment by liudongmiao** [comment]
非正常返回所致，强行停止它，然后强行停止启动器。
