### ISSUE TITLE
自动激进

### ISSUE THREAD

**Issue by WhatJava** [brevent/Brevent#412]
开启自动激进后，一直提醒我，是否取消自动激进，能不能关闭？

**Comment by liudongmiao** [comment]
黑阈不会提示你自动激进，顶多提示建议取消黑阈。

很多人不明白推荐取消黑阈的初衷。

1. 短时间内不断强行停止，要么是流氓，要么是真的需要。

2. 对于流氓，建议卸载或停用（再不济，可以开启激进）；对于常用，建议取消黑阈。允许同步应用也可能不断启动多次，但不会统计在内。

补充说明：

1> 主动打开应用后，计数清零
2> 默认不会提示允许同步，或者激进应用
3> 15 次以后每 3 次提示，30 次以后归零
4> 频率 4 分钟提示 取消，2 分钟且开启停用提示 停用；仅提示，不操作。

3. 发现误报怎么办。收起高贵的评论，黑阈内反馈，带上日志。

4. 不想看通知怎么办。有通知类别，自己关闭；也有全局开关，自己看改动日志。
