### ISSUE TITLE
APK Link broken

### ISSUE THREAD

**Issue by IzzySoft** [brevent/Brevent#413]
Since about 2 days, https://piebridge.me/br/latest.apk no longer works but leads to a 404:

    Location: https://jianyu.io/br/latest.apk [following]
    Location: https://d.jianyu.io/br/br-v3.3.8.1.play.apk [following]
    Remote file does not exist -- broken link!!!

Could that please be fixed? Just make it `br-v3.3.9.1.play.apk` :wink:

**Comment by liudongmiao** [comment]
Sorry, forget to deploy to firebase.

~~Please use this link instead: https://d.jianyu.io/br/latest.apk~~

jianyu.io -> firebase hosting
d.jianyu.io -> actual download link, on vps

piebridge.me and v*.piebridge.me is deprecated.

**Comment by liudongmiao** [comment]
Still cannot fixed..

cannot deploy to firebase hosting..
and, https://d.jianyu.io/br/latest.apk won't be a 302, will just download.

**Comment by IzzySoft** [comment]
It's slow, but seems to work. Just let me know when I shall use a different link. Until then I'd say "works for me". Thanks!

**Comment by liudongmiao** [comment]
Cannot make jianyu.io / piebridge.me work.

So, please note, https://jianyu.io/br/latest.apk won't be a 302, it will just response as 200.
which means, you should send if-match with etag, last-modified.

**Comment by IzzySoft** [comment]
That should be fine. I don't need a 302 – all I need is an URL that gives me a last-modified tag in the header. Currently I'm using https://d.jianyu.io/br/latest.apk which seems to work – if 2018-08-08 is the currently latest version.
