### ISSUE TITLE
zteA2017

### ISSUE THREAD

**Issue by ATcong** [brevent/Brevent#415]
--- crash start ---
[command] logcat -b crash -t '08-14 13:40:18.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-14 13:40:18.000' -d -s BreventLoader BreventServer
08-14 13:40:18.205 15203 15203 I BreventLoader: sdk: 26
08-14 13:40:18.248 15208 15208 I BreventLoader: pm path me.piebridge.brevent
08-14 13:40:18.772 15208 15208 I BreventLoader: line: package:/data/app/me.piebridge.brevent-u5sp-7d752lAvFzRzoMcTg==/base.apk
08-14 13:40:18.797 15208 15208 I BreventLoader: loader path: /data/app/me.piebridge.brevent-u5sp-7d752lAvFzRzoMcTg==/base.apk
08-14 13:40:18.799 15230 15230 I BreventLoader: start: 1534225218
08-14 13:40:19.334 15230 15230 I BreventServer: args: [10, me.piebridge.brevent, 1534225218]
08-14 13:40:19.398 15230 15230 I BreventServer: server log name: server.20180814.1340.15230.txt
08-14 13:40:19.399 15230 15230 I BreventServer: starting Brevent Server 3.3.9.1
08-14 13:40:19.437 15230 15230 I BreventServer: brevent version: 3.3.9.1
08-14 13:40:19.457 15230 15230 I BreventServer: brevent user: 0, uid: 2000
08-14 13:40:19.562 15230 15230 I BreventServer: core apps: [com.qualcomm.qti.perfdump, com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.quicinc.cne.CNEService, com.qualcomm.svi, com.qualcomm.qti.uceShimService, com.android.mms.service, com.qualcomm.qti.telephonyservice, com.mifavor.callsetting, com.android.defcontainer, com.qualcomm.cabl, com.zte.cn.doubleapp, com.wapi.wapicertmanage, android, com.zte.screeneffect, org.codeaurora.ims, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.inputdevices, com.telephony.service, com.android.server.telecom, com.android.dialer, com.qualcomm.qti.qtisystemservice, com.android.packageinstaller, com.android.proxyhandler, com.android.inputmethod.latin, com.android.modem.service, com.zte.ztelockscreen, com.zte.karaokesettings, com.android.settings, zte.com.cn.alarmclock, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, zpub.res]
08-14 13:40:19.563 15230 15230 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.defcontainer, android, com.android.providers.settings, com.android.inputdevices, com.android.server.telecom, com.android.dialer, com.android.packageinstaller, com.android.proxyhandler, com.android.inputmethod.latin, com.android.modem.service, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui}
08-14 13:40:19.567 15230 15230 I BreventServer: installer: com.android.packageinstaller
08-14 13:40:19.568 15230 15230 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-14 13:40:19.639 15208 15208 E BreventLoader: worker 15230 exited with status 3
08-14 13:40:19.639 15208 15208 I BreventLoader: signal arrived, update: 0
08-14 13:40:19.640 15203 15203 I BreventLoader: worker 15208 exited with status 0
--- brevent end ---

**Comment by liudongmiao** [comment]
don't crak brevent. in short, uninstall, then install again.

For chinese, download from here: https://jianyu.io/br/mirror.qq
For other, download from play store.
