### ISSUE TITLE
microg+黑阈

### ISSUE THREAD

**Issue by sxml** [brevent/Brevent#417]
![screenshot_2018-08-15-15-00-06-214_com google android gms](https://user-images.githubusercontent.com/4932232/44153101-da3df65a-a0d9-11e8-8260-01f255c2ba6f.png)
microg代替谷歌 比谷歌pico省电
3.3.2+microg不用签名欺骗 不用梯 微信可以推送。之后版本都不成功？？？
3.3.9.1+microg需要签名欺骗才可以，
microg显示秒收信息，为什么到黑阈拉起需要3分钟左右？

**Comment by liudongmiao** [comment]
黑阈向来反对假冒签名的应用，也从不保证微信这种根本不支持 FCM 的应用是否能及时收到消息。
