### ISSUE TITLE
ofo共享单车被唤醒时直接打开界面

### ISSUE THREAD

**Issue by vvb2060** [brevent/Brevent#42]
针对这种情况，黑域会特别处理吗？比如加入严格模式：对加入的应用仅允许常规途径启动？

**Comment by liudongmiao** [comment]
不会处理。界面的话，基本用户能感知。

后续的话，会尝试看打开的这个界面大小。

不过意义不大，要用户无感知，打开了这个界面，要放到后台。如果它真的这样来绕过…本质上也没什么用，反正不久后，他也将被黑域，只是时间更长些…

此外，好歹你得来点日志吧 …

**Comment by vvb2060** [comment]
难得一点了还在。
我也认为不需要，毕竟打开一个activity太明显了，一划掉就死，又不是偷偷启动一个服务。
就是很烦，恼了可以直接拿写轮眼、冰箱对付。

日志……不是说不会专门优化一个应用吗？像这种宏观策略上的没啥必要吧？

Liu DongMiao <notifications@github.com>于2017年6月13日周二 上午1:31写道：

**Comment by liudongmiao** [comment]
半夜娃要吃奶....顺便处理。
