### ISSUE TITLE
微信登录后显示支付的开关问题

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#421]
已支付大于3或者5二向箔，解锁了专业版/特殊贡献版的用户，使用头像或者设置里右上角的微信登录，建议登录后自动关闭显示支付开关，就像play版那样。

**Comment by liudongmiao** [comment]
设置里的，应该是已经处理了，不过检查了下代码，继续优化了下；头像那里，已经加上支持。

https://jianyu.io/br/alpha/
