### ISSUE TITLE
用了黑狱ssr就不能用了，无法连接，重启关掉黑狱就可以了

### ISSUE THREAD

**Issue by adraim** [brevent/Brevent#426]
两个不能并存

**Comment by vvb2060** [comment]
请提供日志

**Comment by liudongmiao** [comment]
请给予尊重，明显叫黑阈。

**Comment by adraim** [comment]
把SSR改成全局就可以用了，= =！我怀疑是安卓系统的问题，三星NOTE9最近版本要全局SSR才能用，小米MIX2随便用，前提都是开了黑阈

**Comment by adraim** [comment]
日志文件
[logs-v3.4.1.1-20180903.2224.zip](https://github.com/brevent/Brevent/files/2345878/logs-v3.4.1.1-20180903.2224.zip)
