### ISSUE TITLE
关于应用在桌面有微件的问题

### ISSUE THREAD

**Issue by az-123-none** [brevent/Brevent#428]
确实不黑阈解决了微件更新的问题，但是能否给每个有微件的应用自定义一个选项开关，因为有的我并不需要它更新；有需要的可以自定义一个或多个更新时间，打开几秒就再次黑阈掉。比如某课表程序，后台时常3个服务运行，但我只需要一天更新一次课表就好。

**Comment by liudongmiao** [comment]
最新 beta 版，可以自行设置属性 （setprop）。
没有任何计划做进界面，更加不会给每个微件定义是否更新。

**Comment by liudongmiao** [comment]
下个版本起，有“强迫症选项”，可通过属性，或者界面控制功能。
界面控制仅限特别贡献版。
