### ISSUE TITLE
vivo手机安装失败

### ISSUE THREAD

**Issue by lalalajinsi** [brevent/Brevent#43]
D:\程 序\shuame\4.2.1.221>adb -d shell sh /sdcard/Android/data/me.piebridge.brev
ent/brevent.sh
checking...brevent_server started, pid: 21825
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '06-13 20:56:35.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-13 20:56:35.000' -d -s BreventLoader BreventServer
D/BreventLoader(21807): loader path: /mnt/asec/me.piebridge.brevent-1/base.apk
E/BreventLoader(21807): worker 21825 exited on signal 6
D/BreventLoader(21807): signal arrived, update: 0
D/BreventLoader(21802): worker 21807 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issu
es with log above

**Comment by liudongmiao** [comment]
不要放到外置存储上。

一个不到 500K 的软件，有必要放外置存储么…

**Comment by liudongmiao** [comment]
而且，你的 ROM 太魔性。黑域都指定了只能安装在内部存储。。。

**Comment by lalalajinsi** [comment]
恩恩，已经解决啦
