### ISSUE TITLE
关于优化音乐类应用

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#43]
现在这个功能对于真的音乐应用已经非常厉害了，只是有些会用到音频的其他应用，似乎仍有提升空间，有些疑问前来咨询。

起点读书这个app在朗读时，它的语音插件app讯飞语记 会被识别为播放，但起点读书没被识别，还是闹钟，导致起点读书在后台朗读过程中会被待机，之后会被强杀。
朗读暂停时（在起点读书朗读时在起点图书界面里点一下就暂停，再点一下就继续，关闭的话要点退出朗读），讯飞语记不会被识别暂停，显示闹钟。

酷安推荐的快读免费小说app在播放暂停时的识别情况也是类似，不同的是快读免费小说在朗读时有通知，似乎不会被待机再强杀，而起点读书没有通知导致被处理。

而IT之家这个app也有语音朗读，在分屏界面，一端it之家，一端黑域，it之家在朗读时，黑域里能识别播放，it之家暂停朗读时（点它的音乐符号有暂停）的，黑域里变回闹钟，没识别暂停。

**Comment by liudongmiao** [comment]
A 应用调用 B 应用发声，那么显示 B 应用为播放，这是正常的。相反，显示 A 反而不妥。
虽然技术上，可能采取某种手段，让 A 与 B 一起，但是，被恶意使用怎么办。

而至于暂停图标，必须要实际状态是未播放，且有通知。如果没有通知，认为你无法继续播放。
接下来，可能会优化成有通知或者有界面，都可以显示暂停，也就是加入一个有界面的判断。

黑域的这些功能，都属于实验性，确确实实使用一些变通的手段，来试图达到这样的效果。
不一定稳定，但应该能解决绝大部分问题；实验性功能无法解决所有问题。

而音乐类，主要要解决的也是音乐类，不是音频类。

**Comment by CVN-77** [comment]
@liudongmiao 我终于发现怎么复现telegram莫名暂停了。有些其他应用比如it之家可能也是这些原因，出现了消息通知推送，虽然没播放过，但会被误识别。

有时候打开telegram，明明好像啥音频输出都没有，没有播放语音等，但打开黑域一看，额，显示暂停…后来我发现应该是黑域判断状态结合通知有些问题，打开telegram时，如果通知栏冒出一片telegram的消息通知（其实有消息推送时确实有滴的一下通知声，但这和语音消息的音频输出应该不同），这时虽然没有语音信息，但打开黑域查看，tg被识别暂停了，后台日志也显示，在没有被audio记录的情况下，tg被audiopaused记录了。把消息通知全部划掉，再打开黑域查看，tg就变回闹钟或圆圈。再打开tg，如果通知栏又推送消息，黑域里tg又被识别暂停。

**Comment by CVN-77** [comment]
08-22 14:34:25.568 13710 13710 D BreventServer: check and brevent 08-22 14:34:26.628 13710 13710 D BreventServer: audioPaused: {fm.xiami.main} 08-22 14:34:26.630 13710 13710 D BreventServer: check again in 385s 08-22 14:34:26.630 13710 13710 D BreventServer: check and brevent, took 1061ms 08-22 14:34:26.856 13710 13710 D BreventServer: update current to org.telegram.messenger 08-22 14:34:26.856 13710 13710 D BreventServer: previous: com.android.systemui, packageName: org.telegram.messenger 08-22 14:35:03.639 13710 13710 D BreventServer: update current to com.huawei.android.launcher 08-22 14:35:03.639 13710 13710 D BreventServer: return home via non-Home: org.telegram.messenger 08-22 14:35:03.639 13710 13710 D BreventServer: previous: org.telegram.messenger, packageName: com.huawei.android.launcher 08-22 14:35:05.306 13710 13710 D BreventServer: update current to me.piebridge.brevent 08-22 14:35:05.306 13710 13710 D BreventServer: previous: com.huawei.android.launcher, packageName: me.piebridge.brevent 08-22 14:35:05.369 13851 13888 V BreventUI: connected to localhost: 59526 08-22 14:35:05.369 13851 18603 D BreventUI: request status 08-22 14:35:05.376 13851 13888 V BreventUI: connected to localhost: 59526 08-22 14:35:05.421 13710 13822 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent] 08-22 14:35:06.298 13851 18603 D BreventUI: received response 08-22 14:35:06.629 13851 18603 D BreventUI: setAlarm 08-22 14:35:06.640 13710 13710 D BreventServer: check and brevent 08-22 14:35:06.642 13851 13888 V BreventUI: connected to localhost: 59526 08-22 14:35:07.589 13710 13710 D BreventServer: audioPaused: {org.telegram.messenger, fm.xiami.main} 08-22 14:35:07.597 13710 13710 D BreventServer: check again in 344s 08-22 14:35:07.597 13710 13710 D BreventServer: check and brevent, took 956ms 08-22 14:35:09.965 13710 13710 D BreventServer: update current to com.huawei.android.launcher 08-22 14:35:09.965 13710 13710 D BreventServer: previous: me.piebridge.brevent, packageName: com.huawei.android.launcher 08-22 14:35:23.175 13710 13710 D BreventServer: check and brevent 08-22 14:35:23.210 13851 13888 V BreventUI: connected to localhost: 59526 08-22 14:35:23.211 13851 18685 D BreventUI: request status 08-22 14:35:23.219 13851 13888 V BreventUI: connected to localhost: 59526 08-22 14:35:23.331 13710 13822 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent] 08-22 14:35:24.142 13710 13710 D BreventServer: audioPaused: {org.telegram.messenger, fm.xiami.main} 08-22 14:35:24.147 13710 13710 D BreventServer: check again in 327s 08-22 14:35:24.147 13710 13710 D BreventServer: check and brevent, took 963ms 08-22 14:35:24.898 13710 13710 D BreventServer: update current to me.piebridge.brevent 08-22 14:35:24.898 13710 13710 D BreventServer: previous: com.huawei.android.launcher, packageName: me.piebridge.brevent 08-22 14:35:24.912 13851 18685 D BreventUI: received response 08-22 14:35:25.267 13851 18685 D BreventUI: setAlarm 08-22 14:35:25.277 13851 13888 V BreventUI: connected to localhost: 59526 08-22 14:35:27.401 13851 18685 D BreventUI: logcat for system.txt 08-22 14:35:27.561 13851 18685 D BreventUI: logcat for events.txt 08-22 14:35:27.663 13851 18685 D BreventUI: logcat for brevent.txt

**Comment by CVN-77** [comment]
黑域是2.1.4版本，有这个问题。我觉得在判断上可能要加个在顺序上的逻辑（audio ，audiopaused）。

**Comment by CVN-77** [comment]
补充一下，清空通知并强行停止tg，先打开tg，在里边随意一个群聊里看到新消息来的时候，要听到滴的一声，然后home到后台后，等通知栏再出现新消息通知，然后去黑域查看，tg就被识别为暂停（没滴的一下，或者没出现通知似乎不会被误识别）。这样操作基本能复现。

**Comment by liudongmiao** [comment]
只要放过声音，就会有记录；只要有记录，且没发声，就认为是暂停。
但是，这个暂停还必须有通知。实验性功能，无法做到非常好。

**Comment by CVN-77** [comment]
额…怪不得，我猜用tg聊天的可能要崩溃，每发一次消息就记录一次声音，回头出现通知，就变暂停…

**Comment by CVN-77** [comment]
我又试了一下，发现tg接收到消息的滴的一声是属于手机音量里“铃声和通知音量”，把tg的音效暂时关闭后，黑域就不会误识别暂停，而tg语音消息播放的声音是属于音量控制里的“媒体音量”，两个有所不同，虽然发声后都会被目前黑域记录，但结合大部分应用，似乎音乐类应用实际被用户所用的多为媒体音量，黑域可否从这方面入手进行进一步优化？

**Comment by liudongmiao** [comment]
将仅识别音乐，也就是 STREAM_MUSIC (3)。
