### ISSUE TITLE
Android TV上界面显示不全

### ISSUE THREAD

**Issue by fengmlo** [brevent/Brevent#430]
在Android TV上界面显示不全，无法打开侧滑菜单，无法黑域应用

**Comment by benwwchen** [comment]
同样情况。按左上角面包菜单按钮无反应，选择应用后右上角没有按钮

**Comment by liudongmiao** [comment]
真不建议 android tv 使用，我也没有任何计划适配。

**Comment by fengmlo** [comment]
可惜，Android TV上只有黑域能在不root的情况下管控应用

**Comment by liudongmiao** [comment]
都不知道要怎么适配...

**Comment by benwwchen** [comment]
其他app的原生UI一般都没什么问题的…可以先试试调好UI看能不能直接用？或许只是UI布局的问题而不是功能代码需要适配…

**Comment by liudongmiao** [comment]
https://developer.android.google.cn/training/tv/start/start

看了下，基本上是要认真适配的。

而且，黑阈也没有添加相应启动入口，电视机上应该找不到应用的。

**Comment by fengmlo** [comment]
目前可以通过应用列表进入，也能启动黑域服务，被强制关闭的应用也没法在后台自启，所以推测核心功能应该是ok的，目前主要问题是长按应用后右上角没有按钮，点击汉堡菜单按钮也没有反应

**Comment by liudongmiao** [comment]
是的，Android TV 需要单独适配。问题是，如果没有适配，电视上应该见不到入口才对。

**Comment by fengmlo** [comment]
是的，桌面没有入口，但是可以从设置里应用列表进入

**Comment by liudongmiao** [comment]
没有计划支持电视，手表等。也不建议这些类似设备使用黑阈。
