### ISSUE TITLE
关于支付确认的问题

### ISSUE THREAD

**Issue by StrollStars** [brevent/Brevent#432]
尊敬的开发者，您好。
今天看到了Google Play更新，谈到了支付确认问题，我更新之后特意进去看了一下设置，显示的是“特别贡献版”，然而却找不到ROOT启动的选项（到目前为止使用都没有问题），然后开启“显示支付”，点击“如已支付，请先确认”，提示需要支付1二向箔，我就支付了，但是再次点击进去后还是出现了这样的画面。
我应该是黑域/黑阈的早期用户，第一次支付好像是2美元，后来随着功能增加，而依次增加到3美元、5美元，如今已经累计支付了6美元。
我想请教下，我现在还需要继续支付吗？我的ROOT启动还能继续使用吧，哪里可以看到ROOT启动的设置？
最后感谢您的开发。
PS：为什么“应用操作”中的项目比其他有些应用要少？

**Comment by liudongmiao** [comment]
1. 不需要，多余的那 1 刀，属于重复支付
请参照退款流程退款：https://www.jianshu.com/p/4aa39accd52c

2. root 相关功能，全部自动。
2.1）开机自启，已经支付 并且有 root 会自动
2.2) root 启动，已经支付 并且有 root 会展现（需要不连接电脑）
以上两个，3 天试用期内自动展示及自动启动

**Comment by liudongmiao** [comment]
黑阈的应用操作，就是纯应用操作，只读系统的 appops，仅展示系统可用的 op。

**Comment by StrollStars** [comment]
感谢回复。
重复支付就支持作者了，能正常使用就好。
期待新功能。
