### ISSUE TITLE
可否添加已停用应用的桌面快捷方式？

### ISSUE THREAD

**Issue by ExtremelyCold** [brevent/Brevent#434]
停用的应用在使用时经常会选用临时启用这一功能，但每次临时启用都要打开黑阈，不是很方便，所以，可否将已停用的应用以快捷方式的形式添加到桌面？

**Comment by vvb2060** [comment]
在未停用时使用“添加临时应用”即可。

**Comment by ExtremelyCold** [comment]
抱歉，我没有这个选项，我只有
https://wx1.sinaimg.cn/large/b426c831ly1fv6yxu3by7j21401z40z6.jpg
这些

**Comment by liudongmiao** [comment]
最新正式版 3.4.5.2 有这个功能。
