### ISSUE TITLE
临时启动选项不见了

### ISSUE THREAD

**Issue by vivzer** [brevent/Brevent#435]
Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V10.0.1.0.OCACNFH:user/release-keys

重装系统恢复黑阈后，开启时常死机，重开后临时启动的选项没了，卸载重装也无法恢复，请问是怎么回事？

**Comment by vivzer** [comment]
总是操作着操作着就莫名的死机，MIUI10

**Comment by liudongmiao** [comment]
对于第 1 个问题，请确保是最新版本，至少 3.4.5.2 及以上。
临时启动 需要应用可以打开，不支持其它应用停用。
你可以使用 3.4.5.2 中的创建临时应用快捷方式。
黑阈下载地址：https://br.jianyu.io

对于第 2 个问题，你说了和没说一样。
