### ISSUE TITLE
在flyme6上自动停止运行

### ISSUE THREAD

**Issue by yeduzhouzi** [brevent/Brevent#436]
黑阈最新版，已购买，运行于魅蓝m3，flyme6系统，系统内部自带开启root选项。开启root功能后授予黑阈root权限并且在app内部直接启动黑阈服务。随后经过一段不定的时间再次打开黑阈检查，即发现黑阈已经停止运行，或者已经失去root权限，需要重新授予。

**Comment by liudongmiao** [comment]
m3 的 flyme6 应该是基于 android 6 吧。
Android 6 里，由于权限问题，直接使用 root 而不是网络 adb。
而这很容易导致进程被 flyme 清理，如 #79

这个问题无解。

你可以尝试网络调试。
但是，网络调试的话，在 android 5.X - 6.0 中，无法使用停用功能。

自己取舍吧。

黑阈不需要 root 也不为 root 用户特别优化。

**Comment by vvb2060** [comment]
其实还可以更换为SuperSU
