### ISSUE TITLE
开过root各种权限，半天后还会要求root权限

### ISSUE THREAD

**Issue by weicomeqq** [brevent/Brevent#44]

**Comment by liudongmiao** [comment]
想办法弄点日志吧。

从另外一点来说，root 属于实验性功能，不提供任何支持。知道为啥不？

1. 张口不能用的，只是一句不能用，而不能用的可性性太多。谁知道 root 之后，干了啥。

2. 没有日志，无法处理。有日志，肯定已经处理。
