### ISSUE TITLE
索尼xperiaXZ总是启动不了

### ISSUE THREAD

**Issue by DISTanceSSS** [brevent/Brevent#442]
PS D:\platform-tools> .\adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server.......fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-teQSDgXtAcXBu_n4vi79JQ==/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '09-21 14:28:39.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-21 14:28:39.000' -d -s BreventLoader BreventServer
09-21 14:28:39.394 31405 31405 I BreventLoader: pm path me.piebridge.brevent
09-21 14:28:45.992 31405 31405 I BreventLoader: line: package:/data/app/me.piebridge.brevent-teQSDgXtAcXBu_n4vi79JQ==/base.apk
09-21 14:28:46.256 31405 31405 I BreventLoader: loader path: /data/app/me.piebridge.brevent-teQSDgXtAcXBu_n4vi79JQ==/base.apk
09-21 14:28:46.293 31662 31662 I BreventLoader: start: 1537511319
09-21 14:28:49.920 31662 31662 I BreventServer: args: [10, me.piebridge.brevent, 1537511319]
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
这个看起来，都无法加载 class loader。
请问 Android 版本多少？

**Comment by DISTanceSSS** [comment]
>           这个看起来, 都无法加载类装载机。请问 Android 版本多少？

8.0.0，很抱歉这么晚回复你，前天成功了，今天笔记本放在宿舍，没带回家，结果手机自己重启了，卡得连输入个解锁图案都不行。。刚刚我又试着启动，还是跳出这一段，但是却成功了

**Comment by liudongmiao** [comment]
可能只是太慢...一般来说，3 秒内会成功。
黑或有超时检测，像这个已经 6 秒以上，还没有执行到下一步，黑阈认为失败了。

虽然实际上没有失败。

**Comment by DISTanceSSS** [comment]
谢谢解答
