### ISSUE TITLE
Google play services to shut down when again when no longer needed

### ISSUE THREAD

**Issue by Dheie** [brevent/Brevent#443]
Hi
The shortcuts are a huge step forward. Thank you. 
Any chance Google play services might now be made to be disabled just like all the other apps as soon as its gms dependencies are off?

I can see that this is not happening even once keep or other app is brevented.

**Comment by liudongmiao** [comment]
You can check the dependencies icon of Google Play Service.

Normally, when all gapps are brevented, gms would be disabled.
There are two types of gapps:
- specify by launch-gms shortcut, any apps declare `com.google.android.gms.version`
- hardcoded play store, and packages like `com.google.android.*` (excluding launcher)

**Comment by Dheie** [comment]
How do you check dependencies icon?

What I did was disabled gapps, created gms shortcuts for them, disabled Google play services. Then, started keep using the gms shortcut, turned keep off by sweeping it off recent menu. At this stage google play services showed the three points connected symbol and showed to still be occupied by three processes. I wonder if there is a way to tell what they are.

**Comment by liudongmiao** [comment]
Check icon for Google play Service.

![_20180922_234331](https://user-images.githubusercontent.com/473522/45918975-5c38ec00-bec1-11e8-9625-3c73d0dfe38c.JPG)

You can just feedback with logs.

**Comment by Dheie** [comment]
Okay, just done it.

**Comment by liudongmiao** [comment]
I have replied you for the detail dependency.
