### ISSUE TITLE
其他例外退款

### ISSUE THREAD

**Issue by ChiyongWu** [brevent/Brevent#444]
本人于 2017 年 8 月 20 日和2017年10月12日先后两次在黑阈内共计支付 19.5 元，不符合黑阈退款政策 https://www.jianshu.com/p/87aa6245d814，要求开发者例外退款。

~~删除隐私信息~~

支付宝转账记录：
流水号~~删除流水号~~     金额16
流水号~~删除流水号~~       金额3.5

**Comment by liudongmiao** [comment]
删除隐私信息，并退款。

**Comment by liudongmiao** [comment]
#77
