### ISSUE TITLE
允许同步机制

### ISSUE THREAD

**Issue by sxml** [brevent/Brevent#446]
ROM魔改？小米官方开发版啊

“允许同步被服务启动后，允许运行 30 秒以接收通知，过后没通知就停止。”

没错弹出通知不去点阅 30秒会停止 
你通知信息不去打开看吗 
你点阅后 按还回/主页可以超时停止 最新版划掉列表可以停止？你别告诉我也一直在黑域清单里运行！！！！

**Comment by sxml** [comment]
登陆不了 提示去很新
最新版我使用有问题 再安装旧版本既然不能登陆

**Comment by liudongmiao** [comment]
本贴不讨论“允许同步”的设计思想，只说“允许同步”的工作表现。

> “允许同步”应用不会被待机；有通知或在后台运行时，不会被强行停止。

关于后台运行，黑阈有展示时间的，为后台运行。一般操作表现：

1. 按 返回：绝大部分应用不会在后台，具体以实际展示为准。

   - 如果不在后台，（不会待机），待机超时后，然后强行停止。
   - 如果在后台，不会强行停止。

2. 按 主页：直接放在后台，不会强行停止。

3. 最近列表划掉：不会在后台，不久后强行停止。

如果你对于“允许同步”的工作表现有疑问，带上截图与日志，说明包名。

**Comment by liudongmiao** [comment]
黑阈不对旧版提供任何支持。

旧版支付时没有提示，为了避免重复支付；另外，旧版不支持新型兑换码：所以一起限制。
如果可以登录，却无法支付与兑换，还不如不能登录。

**Comment by liudongmiao** [comment]
#447
