### ISSUE TITLE
允许同步 - 微信

### ISSUE THREAD

**Issue by sxml** [brevent/Brevent#447]
@liudongmiao 请问你黑阈怎么设置
微信接收推送 能唤醒拉起 使用完 返回退出不后台运行或待机

**Comment by liudongmiao** [comment]
不可能。

> “允许同步”应用不会被待机；有通知或在后台运行时，不会被强行停止。

1. 要能接收推送，需要设置“允许同步”。

2. 微信使用完，按 返回 以后，**不会退出**，而是**放到后台**，这是微信自己选择。
微信按 返回 使用 Android 常规 API 放到后台，黑阈**几乎**没有方式检测。

所以，如果对微信设置了允许同步，打开微信以后，除非从最近列表划掉，否则黑阈不会强行停止。

**Comment by sxml** [comment]
你微信是一直是运行的？ 除非手动划掉。
你微信不设置自启动 能不能拉起来？设自启 划掉能停止吗

**Comment by liudongmiao** [comment]
打开以后，除非划掉，一直运行；划掉以后，会停止。
你的版本也是这样，之前给你分析过日志。

而没有运行时，收到消息以后可以拉起来，不论是否支持 FCM，不支持 FCM 时需要其它情况触发。
你的版本也是这样，之前也给你分析过日志。

就我使用场景，晚上睡觉前划掉微信，白天打开一次。
也就是白天可以收到消息，晚上没有消息不会运行（微信设置了夜间免打扰）。

**Comment by liudongmiao** [comment]
至于自启动，我不是魔改的 miui 之类，没有这个选项。
是否设置，我本人不回答。
