### ISSUE TITLE
能不能上下文 增加超时/活跃选项

### ISSUE THREAD

**Issue by sxml** [brevent/Brevent#448]
超时和活跃设置是全局 能不能上下文添加 真对性选择 我开同步这些就失效 
用强制打盹 K键代替 黒域返回键 才能待机或停止

**Comment by liudongmiao** [comment]
不能。。黑阈不会把配置文件弄得很复杂。

**Comment by sxml** [comment]
大佬请给我3.3.2版 谢谢 付费微信登陆不上 需要里面付费功能 不喜欢新版
