### ISSUE TITLE
我在电脑输入命令后没有成功开启黑域，出现的是以下的代码，我也不懂代码，希望您能看看这个怎么解决

### ISSUE THREAD

**Issue by Ykhaaaa** [brevent/Brevent#45]
D:\adb>adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
checking............cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '06-18 11:04:39.000' -d
06-18 11:04:39.004   907   907 F DEBUG   :
06-18 11:04:39.004   907   907 F DEBUG   : Tombstone written to: /data/tombstone
s/tombstone_09
06-18 11:04:41.080 12036 12036 F libc    : Fatal signal 6 (SIGABRT), code -6 in
tid 12036 (main)
06-18 11:04:41.183   907   907 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
06-18 11:04:41.184   907   907 F DEBUG   : UUID: 3ffade8d-ce63-4685-97de-e3032ec
407d7
06-18 11:04:41.184   907   907 F DEBUG   : Build fingerprint: 'Sony/F8332/F8332:
6.0.1/39.0.A.1.213/2541384116:user/release-keys'
06-18 11:04:41.184   907   907 F DEBUG   : Revision: '0'
06-18 11:04:41.184   907   907 F DEBUG   : ABI: 'arm64'
06-18 11:04:41.184   907   907 F DEBUG   : pid: 12036, tid: 12036, name: main  >
>> brevent_server <<<
06-18 11:04:41.184   907   907 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL
), fault addr --------
06-18 11:04:41.196   907   907 F DEBUG   : Abort message: 'art/runtime/thread.cc
:1336] No pending exception expected: java.lang.ClassNotFoundException: Didn't f
ind class "me.piebridge.brevent.server.BreventServer" on path: DexPathList[[],na
tiveLibraryDirectories=[/vendor/lib64, /system/lib64]]'
06-18 11:04:41.196   907   907 F DEBUG   :     x0   0000000000000000  x1   00000
00000002f04  x2   0000000000000006  x3   0000000000000000
06-18 11:04:41.196   907   907 F DEBUG   :     x4   0000000000000000  x5   00000
00000000001  x6   0000000000000000  x7   0000000000000000
06-18 11:04:41.196   907   907 F DEBUG   :     x8   0000000000000083  x9   00000
0000000d640  x10  00000000001d4f08  x11  00000000001d5048
06-18 11:04:41.196   907   907 F DEBUG   :     x12  0000000000000000  x13  00000
07f78a3c000  x14  0000000000000000  x15  0000000000000000
06-18 11:04:41.197   907   907 F DEBUG   :     x16  0000007f78a2e568  x17  00000
07f789c050c  x18  0000007f78a3ff50  x19  0000007f78e4a0a8
06-18 11:04:41.197   907   907 F DEBUG   :     x20  0000007f78e49fe8  x21  00000
00000000000  x22  0000000000000006  x23  0000007f7533a000
06-18 11:04:41.197   907   907 F DEBUG   :     x24  0000007f7534d640  x25  00000
07f7583ba00  x26  0000007f75345a40  x27  0000007f7525c000
06-18 11:04:41.197   907   907 F DEBUG   :     x28  0000007f7534d500  x29  00000
07fe9753900  x30  0000007f789bdca8
06-18 11:04:41.197   907   907 F DEBUG   :     sp   0000007fe9753900  pc   00000
07f789c0514  pstate 0000000020000000
06-18 11:04:41.215   907   907 F DEBUG   :
06-18 11:04:41.215   907   907 F DEBUG   : backtrace:
06-18 11:04:41.215   907   907 F DEBUG   :     #00 pc 0000000000069514  /system/
lib64/libc.so (tgkill+8)
06-18 11:04:41.215   907   907 F DEBUG   :     #01 pc 0000000000066ca4  /system/
lib64/libc.so (pthread_kill+68)
06-18 11:04:41.215   907   907 F DEBUG   :     #02 pc 0000000000023b78  /system/
lib64/libc.so (raise+28)
06-18 11:04:41.215   907   907 F DEBUG   :     #03 pc 000000000001e318  /system/
lib64/libc.so (abort+60)
06-18 11:04:41.215   907   907 F DEBUG   :     #04 pc 0000000000433b24  /system/
lib64/libart.so (_ZN3art7Runtime5AbortEv+324)
06-18 11:04:41.215   907   907 F DEBUG   :     #05 pc 00000000001361e4  /system/
lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
06-18 11:04:41.215   907   907 F DEBUG   :     #06 pc 0000000000130c88  /system/
lib64/libart.so (_ZN3art7BarrierD2Ev+296)
06-18 11:04:41.215   907   907 F DEBUG   :     #07 pc 0000000000468838  /system/
lib64/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_tr
aitsIcEEEE+212)
06-18 11:04:41.215   907   907 F DEBUG   :     #08 pc 0000000000433c0c  /system/
lib64/libart.so (_ZN3art7Runtime5AbortEv+556)
06-18 11:04:41.216   907   907 F DEBUG   :     #09 pc 00000000001361e4  /system/
lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
06-18 11:04:41.216   907   907 F DEBUG   :     #10 pc 00000000004594cc  /system/
lib64/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv.part.181+504)
06-18 11:04:41.216   907   907 F DEBUG   :     #11 pc 0000000000190bf8  /system/
lib64/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mi
rror11ClassLoaderEEE+48)
06-18 11:04:41.216   907   907 F DEBUG   :     #12 pc 00000000003680ec  /system/
lib64/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+1172)
06-18 11:04:41.216   907   907 F DEBUG   :     #13 pc 000000000009010c  /system/
lib64/libandroid_runtime.so (_ZN7android30register_android_util_SeempLogEP7_JNIE
nv+36)
06-18 11:04:41.216   907   907 F DEBUG   :     #14 pc 0000000000090eac  /system/
lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime8startRegEP7_JNIEnv+84)
06-18 11:04:41.216   907   907 F DEBUG   :     #15 pc 0000000000092a24  /system/
lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorIN
S_7String8EEEb+336)
06-18 11:04:41.216   907   907 F DEBUG   :     #16 pc 0000000000001e78  /system/
bin/app_process64
06-18 11:04:41.216   907   907 F DEBUG   :     #17 pc 000000000001be98  /system/
lib64/libc.so (__libc_init+100)
06-18 11:04:41.216   907   907 F DEBUG   :     #18 pc 0000000000002250  /system/
bin/app_process64
06-18 11:04:41.355   907   907 F DEBUG   :
06-18 11:04:41.355   907   907 F DEBUG   : Tombstone written to: /data/tombstone
s/tombstone_00
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-18 11:04:39.000' -d -s BreventLoader BreventServer
06-18 11:04:39.302 11900 11900 E BreventLoader: worker 11925 exited on signal 6
06-18 11:04:39.302 11900 11900 D BreventLoader: signal arrived, update: 0
06-18 11:04:39.305 11894 11894 D BreventLoader: worker 11900 exited with status
0
06-18 11:04:40.490 11999 11999 D BreventLoader: loader path: /mnt/asec/me.piebri
dge.brevent-1/base.apk
06-18 11:04:41.627 11999 11999 E BreventLoader: worker 12036 exited on signal 6
06-18 11:04:41.627 11999 11999 D BreventLoader: signal arrived, update: 0
06-18 11:04:41.628 11994 11994 D BreventLoader: worker 11999 exited with status
0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issu
es with log above

**Comment by vvb2060** [comment]
参考 #43

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Huawei Nexus 6P 发送_

**Comment by vvb2060** [comment]
参考 #43

**Comment by Ykhaaaa** [comment]
十分感谢，已经搞定了，我也不知道为什么默认安装在SD卡了。
