### ISSUE TITLE
更新最新版黑域描述问题

### ISSUE THREAD

**Issue by SoDebug** [brevent/Brevent#45]
1)原文：“允许 ROOT 启动”需要支付 3 美元或 16 人民币（推荐支付宝）。

如您已经支付，请打开“支付宝”（需要临时禁用 Xposed），点开“转账记录”（不是“账单详情”），将会自动识别（如果账单过期，将无法自动识别）。

如果无法自动识别，或者其它方式支付，请发送邮件（需要安装邮件客户端），附上支付订单截图。

邮件一般 24 小时内回复，请尽量自动确认。
(2)问题：建议把“16人民币”改为“16元人民币”
或者使用通用方式“16RMB”
否则一些爱搞破坏的人说是16万人民币(虽然没这么离谱，还是建议改一下)

**Comment by liudongmiao** [comment]
感谢建议，将使用这个：

> “允许 ROOT 启动”需要支付 3 美元或人民币 16 元...

**Comment by SoDebug** [comment]
感谢采纳
