### ISSUE TITLE
抽屉菜单可否不展示微信图标？

### ISSUE THREAD

**Issue by StrollStars** [brevent/Brevent#450]
今日更新到了最新版，发现ROOT已无法启动，通过重新安装成功ROOT启动后，发现微信服务已经自动启动了，而且黑阈设置图标变成了微信图标。经查阅这是和微信绑定了（我没有点微信登录）。
现在想请教以下几个问题：
①我在微信中是否能看到黑阈的相关信息？
②我是否可以完全断开黑阈、Google Play与微信的关联？

非常不喜欢黑阈新版本的变化，而且我每次更新都会看新变化的内容（针对所有APP），其中并未指出会自动关联微信以及更多相关信息。

另外建议：
①关联之前能够给予提示让用户可以有所选择？
②即使有了心形图标，是否可以保留圆圈加杠图标？
③微信黑阈提示无法待机，我设置了黑阈后是如何处理的？

**Comment by vvb2060** [comment]
没有绑定，绑定后显示的是你的微信头像，这是提示可以绑定。
处理方法按照设置-黑阈方法处理。由于你或系统的设置无法待机微信，将跳过待机环节。

**Comment by StrollStars** [comment]
@vvb2060 感谢那么快回复，对问题进行了下更新。
那是否可以完全不出现微信图标？
跳过待机环节是直接强行停止的意思？
通过电池优化设置实现了待机，发现[说明文件](https://jianyu.io/br/br.pdf)很好，可是隐藏太深，可否放在项目的说明文件中？

**Comment by liudongmiao** [comment]
1. 当你系统没有安装微信，或者微信停用时，不会出现微信图标。
你微信登录以后，会使用你微信头像。

2. 跳过待机，就是单纯的跳过的意思。

   黑阈管理应用的生命周期：
   - 正在使用: 黑阈不处理
   - 放到后台: （Back / Home / 最近列表都会影响）
     - 后台超时，待机。如果不支持待机，或者黑阈方法里不包含待机，不进行。
     - 待机超时，强行停止。如果黑阈方法里不包含强行停止，不进行。

3. 各个商店的介绍里，都有提及文档。如：
   - [Play 商店](https://play.google.com/store/apps/details?id=me.piebridge.brevent&hl=zh)
   - [应用宝](http://sj.qq.com/myapp/detail.htm?apkName=me.piebridge.brevent)

**Comment by StrollStars** [comment]
@liudongmiao 感谢回复，可否像“显示支付”那样提供个“显示微信”的选项，毕竟停用微信不太方便。
感谢解答，“图文文档”后的“文档内容可能过时”文字可否改为文档更新时间？这样也方便用户跟着更新。

**Comment by liudongmiao** [comment]
这个“微信”图标，乃至这个抽屉菜单，都是临时的，为了它再来一个控制...不会处理。
文档里有更新时间，后续将确保文档最新。
