### ISSUE TITLE
It cannot work on Google Pixel -- Android Pie System in the latest update (26 Sep 2018).

### ISSUE THREAD

**Issue by WillieYang** [brevent/Brevent#452]
Every time after I enable the brevent using PC (by type commands using ADB tool), it works for  two or three minutes, however, after that, it would reveal the primary interface of brevent, and asking me to enable brevent by PC (which has already been done).

**Comment by liudongmiao** [comment]
i still don't receive the latest update. will check when i update.

**Comment by liudongmiao** [comment]
There is no security update for pixel, and don't turn off adb in anyway.

You can turn ~~off~~ on network adb:

```
adb tcpip 3035
```

**Comment by liudongmiao** [comment]
Just receive Oct update, and it works well.

**Comment by WillieYang** [comment]
Hi,

I don't know why, but after I run the command: adb tcpip 3035, it works.

Anyway, thank you very much indeed.

Willie
