### ISSUE TITLE
Option to remove notifications

### ISSUE THREAD

**Issue by rafi3403** [brevent/Brevent#453]
Dear developers,
Kindly please give An option to remove the notifications that shows to unbrevent some apps. They are reasonable,but I have brevented those on purpose. And i don't need them to be running in the background. also kindly please remove the pop-up dialogue box while launching the app telling us to unbrevent some apps that cannot be opened. I hope this would be a noticeable issue that you might have to solve this. Thank you.

**Comment by liudongmiao** [comment]
1. (for android o+) there are notifications channel, you can control them.

2. it shouldn't show them again if they are unchanged, for paid users.
and if have paid, and show them again and again, then don't disable apps by other tools, or don't brevent them.

**Comment by rafi3403** [comment]
Ok thanks
