### ISSUE TITLE
请教下这个软件能阻止唤醒还是只是将恶意唤醒后的app杀死？

### ISSUE THREAD

**Issue by tiger20081015** [brevent/Brevent#456]
如果是将恶意唤醒后的app杀死，理论上来说还是有可能在短时间内出现卡顿吧？不知道我理解的对不对？

**Comment by liudongmiao** [comment]
1. 经过黑阈处理之后，android 内部机制可以最大限度不启动该应用
额外的更大限度，包括 应用操作 的 后台运行（Android 7 引入，8 公开），索尼的 auto_start

2. 对于极少部分启动，黑阈会在启动后不久强行停止
这部分基本属于友好启动，如分享，支付，依赖等；另一个意义上讲，打开界面也是。

3. 如果你需要完全不被启动，包括界面，友好交互等，可以使用 停用快捷 方式
使用停用快捷方式（或者临时启用）打开的应用，在使用完之后，黑阈会直接停用，完全无法启动
