### ISSUE TITLE
breventing newly installed app(s)

### ISSUE THREAD

**Issue by zputnyq** [brevent/Brevent#457]
Hallo I'm new user of brevent.
Recently I use brevent v3 5.1.4 with root mode (magisk v17.1) on Xperia m4 6.0.1 stock.
When I install a new app, brevent notification always appear & when I remove the notification (without pressing unbrevent), brevent will directly brevent that newly installed app.
Would you mind removing this behaviour since v.3.5.1.2 seems not like that & if it is a new feature, probably you could give an option to remove the notification / behaviour.
Thanks, I really appreciate it

**Comment by liudongmiao** [comment]
```
setprop log.tag.brevent.update.disabled true
```

Then launch Brevent.

If you have paid 5 Brefoil, tap "System status" in Settings of Brevent 7 times to show ocd features.

**Comment by vvb2060** [comment]
From the **first** version, Brevent will auto brevent new apps.
