### ISSUE TITLE
更新最新版黑域描述问题(2)

### ISSUE THREAD

**Issue by SoDebug** [brevent/Brevent#46]
1.位置：设置/实验性功能/识别非正常“返回”
2.原文：有些应用按“返回”时放到后台而不退出
Play 版需要累计支付 2 美元，其它版请随意
3.修改建议：将“退出”改为“强行停止” ，因为实际上，用户已经“退出”该程序主界面，只是不想停止该程序！

**Comment by vvb2060** [comment]
据此，我认为识别非正常返回描述需要更新，因为有人根本不知道这是干什么的

**Comment by SoDebug** [comment]
是的，的确这样

**Comment by liudongmiao** [comment]
> 应用使用非“主页”方式回到桌面时，立即黑域

这样可以么？

**Comment by SoDebug** [comment]
也可以，意思差不多

**Comment by liudongmiao** [comment]
> 应用使用非“主页”方式（如“返回”）回到桌面时，立即黑域

加入括号内容，非主页方式，主要发生在按返回时。

**Comment by SoDebug** [comment]
是的，这样意思较为明确
