### ISSUE TITLE
BREVENT STOPPED WORKING AUTOMATICALLY

### ISSUE THREAD

**Issue by VSR007VSR** [brevent/Brevent#462]
After followed brevent  Execute steps stopped in 5 min
Again i need to execute same pc command 
i never disable usb debugging or reboot

Mobile model: REDMI 6A-OREO

C:\Program Files\Minimal ADB and Fastboot>adb -d shell sh /data/data/me.piebridg
e.brevent/brevent.sh
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
checking for server.......fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-_ADDd5zcbdEWd-2F8bD-oA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '10-16 18:43:55.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '10-16 18:43:55.000' -d -s BreventLoader BreventServ
er
10-16 18:43:55.702  3841  3841 I BreventLoader: sdk: 27
10-16 18:43:55.913  3875  3875 I BreventLoader: pm path me.piebridge.brevent
10-16 18:44:01.579  3875  3875 I BreventLoader: line: package:/data/app/me.piebr
idge.brevent-_ADDd5zcbdEWd-2F8bD-oA==/base.apk
10-16 18:44:01.620  3875  3875 I BreventLoader: loader path: /data/app/me.piebri
dge.brevent-_ADDd5zcbdEWd-2F8bD-oA==/base.apk
10-16 18:44:01.623  4066  4066 I BreventLoader: start: 1539695635
10-16 18:44:02.850  4066  4066 I BreventServer: args: [10, me.piebridge.brevent,
 1539695635]
10-16 18:44:03.104  4066  4066 I BreventServer: server log name: server.20181016
.1844.4066.txt
10-16 18:44:03.107  4066  4066 I BreventServer: remove file: /storage/emulated/0
/Android/data/me.piebridge.brevent/server.20181015.1602.15101.txt
10-16 18:44:03.109  4066  4066 I BreventServer: starting Brevent Server 3.5.1.4
10-16 18:44:03.447  4066  4066 I BreventServer: brevent version: 3.5.1.4
10-16 18:44:03.912  4066  4066 I BreventServer: brevent user: 0, uid: 2000
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

C:\Program Files\Minimal ADB and Fastboot>
[server.20181015.1610.18467.txt](https://github.com/brevent/Brevent/files/2483429/server.20181015.1610.18467.txt)
[server.20181015.2106.29187.txt](https://github.com/brevent/Brevent/files/2483430/server.20181015.2106.29187.txt)
[server.20181015.2145.9830.txt](https://github.com/brevent/Brevent/files/2483431/server.20181015.2145.9830.txt)
[server.20181016.0647.8067.txt](https://github.com/brevent/Brevent/files/2483432/server.20181016.0647.8067.txt)
[server.20181016.0648.9112.txt](https://github.com/brevent/Brevent/files/2483433/server.20181016.0648.9112.txt)
[server.20181016.1844.4066.txt](https://github.com/brevent/Brevent/files/2483434/server.20181016.1844.4066.txt)

**Comment by liudongmiao** [comment]
use command 

```
adb tcpip 3035
```

to turn on network debug, then launch Brevent.

**NEVER** try to make multi `brevent_daemon` / `brevent_server`.
