### ISSUE TITLE
激活了，还是会变成非激活状态。

### ISSUE THREAD

**Issue by wakeup0215** [brevent/Brevent#464]
麻烦作者了解下，回下教程

**Comment by vvb2060** [comment]
https://dl.jianyu-studio.com/br/br.pdf
异常退出请说明情况并且带上日志。

**Comment by liudongmiao** [comment]
Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。

如果默认选项或“仅充电”还是不行，请使用指令“adb tcpip 3035”开启网络调试。网络调试有风险，不要轻易授权。
