### ISSUE TITLE
增加“自动黑阈”开关

### ISSUE THREAD

**Issue by chikehe** [brevent/Brevent#466]
与冰箱类管理软件共存时，每次打开冰冻的app黑阈都会自动黑阈，希望增加功能开关

**Comment by vvb2060** [comment]
特别贡献版点按 7 次系统状态可显示或关闭强迫症选项。当前强迫症选项共有 4 个，非特别贡献版可通过执行指令开启
1. 建议取消黑阈: setprop log.tag.brevent.forcestop.check default 或 true 或 false
2. 关闭自动更新: setprop log.tag.brevent.update.disabled true
3. 黑阈微件: setprop log.tag.brevent.widget.disabled true
4. 忽略安全: setprop log.tag.brevent.safe.disabled true

**Comment by chikehe** [comment]
执行setprop log.tag.brevent.forcestop.check false

返回
[shproc] Process[pid=15340, hasExited=false]
[shproc] Process[pid=15340, hasExited=true, exitcode=0]

没效果？

**Comment by liudongmiao** [comment]
这个指令，本身就是没有返回值的。
