### ISSUE TITLE
停止运行

### ISSUE THREAD

**Issue by doudou5451** [brevent/Brevent#467]
在essential phone上会停止运行，系统版本安卓9  034

**Comment by vvb2060** [comment]
Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。

如果默认选项或“仅充电”还是不行，请使用指令“adb tcpip 3035”开启网络调试。网络调试有风险，不要轻易授权。
