### ISSUE TITLE
麻烦优化一下对“正在播放的应用”的识别

### ISSUE THREAD

**Issue by syh911231** [brevent/Brevent#468]
APP：红警OL
最近发现它异常耗电，一宿能达到17%
已经黑域了也设置了激进，但它被识别成了正在播放的应用，黑域根本不管它
难道这又是新毒瘤？明明跟播放没关系啊
希望能优化一下识别方法或者把这应用拉黑，谢谢~

**Comment by vvb2060** [comment]
划掉它的通知

**Comment by syh911231** [comment]
> 划掉它的通知

它的通知我已经关闭啦

**Comment by liudongmiao** [comment]
正在播放，只有当检测到播放，才会去检测。

目前这个功能，不会进一步优化。
黑阈对比过国内主流音乐播放器，才最终选择目前这个方案。
这是一个可以运行在所有版本上的隐藏 API，虽然后续有公司 API 可以获取，但并不稳定。

如果觉得有 Bug，可以关闭这个功能。
