### ISSUE TITLE
每次重启都失去root功能

### ISSUE THREAD

**Issue by Aquarian-Age** [brevent/Brevent#469]
重启之后 无法开启服务 必须卸载重新安装才能使用 不知道哪里问题
HTC 刷的第三方ROM8.0版本

**Comment by liudongmiao** [comment]
root 仅能 3 天内无限制使用，否则需要付费。
但黑阈不想为 root 优化，也不会提示支付。

另外，黑阈不想为 root 优化，也基本不受理 root 相关问题。
