### ISSUE TITLE
更新最新版黑域描述问题(3)

### ISSUE THREAD

**Issue by SoDebug** [brevent/Brevent#47]
(1)位置：设置/高级功能/自我诊断
(2)原文：每 15 分钟检查黑域服务，必要时收集日志
只有偶然不正常停止时，才需要开启。开启之后，将把黑域加入电池优化白名单
(3)修改建议：将“开启之后，将把黑域加入电池优化白名单”改为“开启之后，自动将把黑域加入电池优化白名单”。避免用户不理解是需要用户自行把“黑域”加入电池优化白名单还是“黑域自动把自己加入电池优化白名单”！

**Comment by vvb2060** [comment]
需要用户自己操作的部分会特别说明的，我认为“将把”完全可以清楚表达

**Comment by SoDebug** [comment]
我认为会有部分用户会摸不着头脑，你不能仅仅靠自己去认为，还有用户能完全理解，这是开发者应该能明白的，毕竟，最终使用的群体是用户，不是开发者

**Comment by CVN-77** [comment]
我觉得要这么说，也是“将自动把…”比“自动将把…”通顺

**Comment by SoDebug** [comment]
这两个的意思似乎一样吧，，

**Comment by vvb2060** [comment]
用户打开这个开关后，返回黑域主页面会看见黑域已经电池未优化了。所以这个讨论意义不大

**Comment by SoDebug** [comment]
，，不是，那个我想说的是“将自动把黑域加入.....”
我只是打错了，，，

**Comment by SoDebug** [comment]
我只是尽可能的把软件想要表达的意思说清楚，避免用户操作时的理解错误，且更新描述也是顺便的事。

**Comment by liudongmiao** [comment]
感谢建议，采纳。

**Comment by liudongmiao** [comment]
@SoDebug 请黑域内点反馈，告诉我你的身份，好赠送您特别贡献优惠。
