### ISSUE TITLE
执行脚本路径下找不到相应文件。

### ISSUE THREAD

**Issue by liukeyu** [brevent/Brevent#47]
执行
 .\adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
报
sh: /sdcard/Android/data/me.piebridge.brevent/brevent.sh: No such file or directory
手机是nexus 6p
系统是7.1.2

**Comment by zhengfc** [comment]
我也是这个问题，电脑随便输入cd /shcard也没有该目录文件

**Comment by liudongmiao** [comment]
只有在黑域的“请启动黑域服务”的提示界面，才会创建这个文件。

**Comment by zhengfc** [comment]
可以了，写错了，是```sdcard```；我写错```shcard```； @liudongmiao

**Comment by liukeyu** [comment]
明白了，因为首页标签页只有欢迎、权限、安全这三个标签页。没有想到向左滑动还有更多标签。
也算提个建议 ，希望"进入黑域"能放在显眼的位置，或者提示向左滑动，情况跟我一样的人应该还蛮多的

**Comment by vvb2060** [comment]
@liukeyu 现在这样是故意的，逼人看完。但是你不知道后面还有是怎么进去的呢？

**Comment by liukeyu** [comment]
@vvb2060 我是直接阅读的https://piebridge.me/br/上面的PDF文档。还纳闷怎么文档中是5个标签页，我的只有3个。然后就没有管，直接执行adb 命令了

**Comment by liudongmiao** [comment]
@liukeyu 

黑域说明书的第一句话就是：

> 首次打开时，见到的是向导页面。这里有一些基本的介绍，到了使用页面，就可以开启黑域之旅。

以下，在图下面，就是这句话：

> 左右滑动或者点击页签切换不同页面，进入“使用”之后，点击“进入黑域”。

**Comment by liukeyu** [comment]
嗯，没看仔细
