### ISSUE TITLE
黑域为什么总是未启动服务

### ISSUE THREAD

**Issue by 1141087505** [brevent/Brevent#470]
安卓8.1  有的时候打开几个应用就显示未启动 得连电脑输命令 有的时候打开一个应用就这样  usb调试和开发者模式没动过  一天下来 得连电脑好几次   
连电脑 选择媒体设备mtp模式 电脑能认出手机的那个模式不管用 线一断开就没用了 用的充电模式 输入的命令

**Comment by liudongmiao** [comment]
Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。

此外，部分系统（如魅族）会有“安全支付”之类的选项，开启之后可能会不时停用调试模式。

如果默认选项或“仅充电”还是不行，请使用指令“adb tcpip 3035”开启网络调试。网络调试有风险，不要轻易授权。

**Comment by 1141087505** [comment]
> Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。
> 
> 此外，部分系统（如魅族）会有“安全支付”之类的选项，开启之后可能会不时停用调试模式。
> 
> 如果默认选项或“仅充电”还是不行，请使用指令“adb tcpip 3035”开启网络调试。网络调试有风险，不要轻易授权。
关闭了安全支付 目前黑域好了  应该没事了
 我是用的充电模式 输入的命令  黑域也可以正常用 可是就是随便开个app 然后就不行了   安全支付我这部手机 只有开支付宝的时候有 而且我支付宝也不是经常开 大多数时候就开了个微信 B站 京东 之类的常用APP 然后就没用了   一天下来要连接电脑好多次 
需不需要上传日志文件

**Comment by 1141087505** [comment]
> > Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。如果拔线后黑阈就失效，请尝试其它 USB 选项。正常情况下，使用默认选项或“仅充电”就好。
> > 此外，部分系统（如魅族）会有“安全支付”之类的选项，开启之后可能会不时停用调试模式。
> > 如果默认选项或“仅充电”还是不行，请使用指令“adb tcpip 3035”开启网络调试。网络调试有风险，不要轻易授权。
> 
> 我是用的充电模式 输入的命令 黑域也可以正常用 可是就是随便开个app 然后就不行了 安全支付我这部手机 只有开支付宝的时候有 而且我支付宝也不是经常开 大多数时候就开了个微信 B站 京东 之类的常用APP 然后就没用了 一天下来要连接电脑好多次
