### ISSUE TITLE
你好，关于Android9.0黑阈自动关闭的问题

### ISSUE THREAD

**Issue by xhsmyxzx** [brevent/Brevent#474]
升级了Android9.0。安装黑阈后，链接adb打开黑阈,然后拔掉USB后黑阈正常。但是关闭手机屏幕后再打开屏幕，这时候黑阈服务会停止。也就是说，正常启动黑阈后，拔掉USB线,只要不关手机屏幕，黑阈就运行正常，关了手机屏幕后黑阈会退出。请问这个怎么解决

**Comment by xhsmyxzx** [comment]
升级Android 9.0后
启动黑阈正常
拔掉USB线黑阈正常
锁屏后再解锁，黑阈服务已停止

**Comment by xhsmyxzx** [comment]
索尼XZ1手机

**Comment by xhsmyxzx** [comment]
[logs-v3.5.3-20181116.1950.zip](https://github.com/brevent/Brevent/files/2589312/logs-v3.5.3-20181116.1950.zip)

**Comment by jdidbidbdidb** [comment]
发件人: "支付者"<zzw2583644273@163.com>
发送时间: 2018年11月14日(星期三) 中午12:29
收件人: "refund@jianyu.io"<refund@jianyu.i

**Comment by liudongmiao** [comment]
adb tcpip 3035 吧
