### ISSUE TITLE
微信支付确认

### ISSUE THREAD

**Issue by eletic23** [brevent/Brevent#475]
请问微信账号登录的作用是什么？我之前登录支付过，刷机后重新登录需要重新支付的，希望得到回复。
主要是我的微信不知道为什么最近支付不了，不然支付几次都没问题，希望解决一下

**Comment by liudongmiao** [comment]
微信登录以后，会直接返回绑定的支付信息。
如果确实没有，找到单号，发邮件至 brevent # jianyu.io
