### ISSUE TITLE
一加6 安卓9.0 待机:不支持

### ISSUE THREAD

**Issue by bottledcute** [brevent/Brevent#479]
卸载重装第一次激活使用是全部支持的。但是重启手机后再次使用待机就变成不支持。

**Comment by bottledcute** [comment]
[logs-v3.5.4.1-20181122.1903.zip](https://github.com/brevent/Brevent/files/2607868/logs-v3.5.4.1-20181122.1903.zip)

**Comment by bottledcute** [comment]
已发现问题所在，是因为我关闭了智能电池管理，希望开发者您能添加下说明，告诉其他使用者有这种情况，防止大家走弯路~ 谢谢
![screenshot_20181122-204508](https://user-images.githubusercontent.com/42441811/48904115-5ac37a00-ee98-11e8-87ef-b7abbd12dfd9.jpg)
![screenshot_20181122-204514](https://user-images.githubusercontent.com/42441811/48904117-5b5c1080-ee98-11e8-8ecd-4096725afcf2.jpg)
![screenshot_20181122-204518](https://user-images.githubusercontent.com/42441811/48904118-5b5c1080-ee98-11e8-99f6-24a7be1939a5.jpg)

**Comment by liudongmiao** [comment]
这个没法说明吧。真的都是系统可设置的。
我早就知道这个，另外还有几个隐藏属性。

当然，我非常自豪的说，黑阈提示不能，就是真的不能。

**Comment by bottledcute** [comment]
> 这个没法说明吧。真的都是系统可设置的。
> 我早就知道这个，另外还有几个隐藏属性。
> 
> 当然，我非常自豪的说，黑阈提示不能，就是真的不能。

隐藏属性是什么？能否和我讲解下 谢谢~

**Comment by haotingliu1990** [comment]
所以就是说如果系统是安卓p，在关闭了智能电源管理的模式下无法使应用待机？
