### ISSUE TITLE
使用adb开启时报错，再次运行命令后以root模式开始

### ISSUE THREAD

**Issue by heganyuliang** [brevent/Brevent#48]
正常使用adb命令启动服务时显示如下日志：

>  --- brevent start ---
logcat -b main -t '06-18 23:14:24.000' -d -s BreventLoader BreventServer
06-18 23:14:25.245  5250  5250 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
06-18 23:14:25.601  5262  5262 D BreventServer: get service: package: android.os.BinderProxy@8cd9085
06-18 23:14:25.606  5262  5262 I BreventServer: starting Brevent Server 1.2.5a
06-18 23:14:25.612  5262  5262 D BreventServer: get service: package: android.os.BinderProxy@8cd9085
06-18 23:14:25.614  5262  5262 I BreventServer: brevent user: 0, uid: 0
06-18 23:14:25.616  5262  5262 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
06-18 23:14:25.637  5262  5262 I BreventServer: android providers: {com.android.providers.calendar, com.android.providers.media, com.android.providers.downloads, com.android.providers.downloads.ui, com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.providers.contacts}
06-18 23:14:25.637  5262  5262 I BreventServer: loading brevent list
06-18 23:14:25.641  5262  5262 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 77
06-18 23:14:25.645  5262  5262 D BreventServer: Force stop com.nosixfive.verto(load brevent)
06-18 23:14:25.651  5262  5262 D BreventServer: Force stop so.ofo.labofo(load brevent)
06-18 23:14:25.659  5262  5262 D BreventServer: Force stop app.errang.com.poems(load brevent)
06-18 23:14:25.662  5262  5262 D BreventServer: Force stop com.wandoujia(load brevent)
06-18 23:14:25.665  5262  5262 D BreventServer: Force stop com.mxtech.videoplayer.pro(load brevent)
06-18 23:14:25.675  5262  5262 D BreventServer: Force stop com.niksoftware.snapseed(load brevent)
06-18 23:14:25.683  5262  5262 D BreventServer: Force stop com.colure.app.privacygallery(load brevent)
06-18 23:14:25.691  5262  5262 D BreventServer: Force stop bos.consoar.imagestitch(load brevent)
06-18 23:14:25.699  5262  5262 D BreventServer: Force stop cn.wq.myandroidtoolspro(load brevent)
06-18 23:14:25.702  5262  5262 D BreventServer: Force stop com.clover.imuseum(load brevent)
06-18 23:14:25.713  5262  5262 D BreventServer: Force stop com.zjwh.android_wh_physicalfitness(load brevent)
06-18 23:14:25.719  5262  5262 D BreventServer: Force stop com.noctuasoftware.stellarium(load brevent)
06-18 23:14:25.723  5262  5262 D BreventServer: Force stop com.themezilla.pixelui(load brevent)
06-18 23:14:25.737  5262  5262 D BreventServer: Force stop com.keramidas.TitaniumBackup(load brevent)
06-18 23:14:25.742  5262  5262 D BreventServer: Force stop com.microsoft.office.officelens(load brevent)
06-18 23:14:25.752  5262  5262 D BreventServer: Force stop eu.thedarken.sdm.unlocker(load brevent)
06-18 23:14:25.757  5262  5262 D BreventServer: Force stop com.microsoft.office.excel(load brevent)
06-18 23:14:25.772  5262  5262 D BreventServer: Force stop com.hupu.football(load brevent)
06-18 23:14:25.776  5262  5262 D BreventServer: Force stop com.iwantavnow(load brevent)
06-18 23:14:25.778  5262  5262 D BreventServer: Force stop com.lesshint.android.bypassgeo(load brevent)
06-18 23:14:25.785  5262  5262 D BreventServer: Force stop cc.forestapp(load brevent)
06-18 23:14:25.790  5262  5262 D BreventServer: Force stop com.tratao.xcurrency(load brevent)
06-18 23:14:25.795  5262  5262 D BreventServer: Force stop com.microsoft.office.onenote(load brevent)
06-18 23:14:25.799  5262  5262 D BreventServer: Force stop me.phh.superuser(load brevent)
06-18 23:14:25.803  5262  5262 D BreventServer: Force stop kh.android.dir(load brevent)
06-18 23:14:25.806  5262  5262 D BreventServer: Force stop com.apkpure.aegon(load brevent)
06-18 23:14:25.816  5262  5262 D BreventServer: Force stop org.adaway(load brevent)
06-18 23:14:25.818  5262  5262 D BreventServer: Force stop net.ia.iawriter(load brevent)
06-18 23:14:25.821  5262  5262 D BreventServer: Force stop com.dianping.movieheaven(load brevent)
06-18 23:14:25.829  5262  5262 D BreventServer: Force stop com.shanbay.words(load brevent)
06-18 23:14:25.831  5262  5262 D BreventServer: Force stop com.dv.adm.pay(load brevent)
06-18 23:14:25.834  5262  5262 D BreventServer: Force stop com.merriamwebster.premium(load brevent)
06-18 23:14:25.837  5262  5262 D BreventServer: Force stop com.ruby.timetable(load brevent)
06-18 23:14:25.840  5262  5262 D BreventServer: Force stop zhao.apkcrack(load brevent)
06-18 23:14:25.857  5262  5262 D BreventServer: Force stop com.grarak.kerneladiutor(load brevent)
06-18 23:14:25.864  5262  5262 D BreventServer: Force stop com.airvisual(load brevent)
06-18 23:14:25.868  5262  5262 D BreventServer: Force stop com.microsoft.office.word(load brevent)
06-18 23:14:25.884  5262  5262 D BreventServer: Force stop com.teslacoilsw.launcher.prime(load brevent)
06-18 23:14:25.889  5262  5262 D BreventServer: Force stop com.downloading.main.baiduyundownload(load brevent)
06-18 23:14:25.894  5262  5262 D BreventServer: Force stop com.microsoft.office.powerpoint(load brevent)
06-18 23:14:25.897  5262  5262 D BreventServer: Force stop com.microsoft.translator(load brevent)
06-18 23:14:25.901  5262  5262 D BreventServer: Force stop rikka.smscodehelper(load brevent)
06-18 23:14:25.906  5262  5262 D BreventServer: Force stop com.tencent.mobileqq(load brevent)
06-18 23:14:25.912  5262  5262 D BreventServer: Force stop uk.co.economist(load brevent)
06-18 23:14:25.918  5262  5262 D BreventServer: Force stop info.papdt.blackblub(load brevent)
06-18 23:14:25.925  5262  5262 D BreventServer: Force stop com.android.vending.billing.InAppBillingService.LOCK(load brevent)
06-18 23:14:25.930  5262  5262 D BreventServer: Force stop com.qianyan.eudic(load brevent)
06-18 23:14:25.935  5262  5262 D BreventServer: Force stop com.catchingnow.icebox(load brevent)
06-18 23:14:25.938  5262  5262 D BreventServer: Force stop com.coolapk.market(load brevent)
06-18 23:14:25.946  5262  5262 D BreventServer: Force stop io.github.javiewer(load brevent)
06-18 23:14:25.951  5262  5262 D BreventServer: Force stop com.muzik(load brevent)
06-18 23:14:25.953  5262  5262 D BreventServer: Force stop com.adobe.reader(load brevent)
06-18 23:14:25.956  5262  5262 D BreventServer: Force stop eu.thedarken.sdm(load brevent)
06-18 23:14:25.963  5262  5262 D BreventServer: Force stop small.word(load brevent)
06-18 23:14:25.969  5262  5262 D BreventServer: Force stop com.caij.emore(load brevent)
06-18 23:14:25.975  5262  5262 D BreventServer: Force stop com.autonavi.minimap(load brevent)
06-18 23:14:25.980  5262  5262 D BreventServer: Force stop com.Nebugu.SoccerPyhsics2D(load brevent)
06-18 23:14:25.983  5262  5262 D BreventServer: Force stop pl.solidexplorer2(load brevent)
06-18 23:14:25.987  5262  5262 D BreventServer: Force stop com.noodlecake.altosadventure(load brevent)
06-18 23:14:26.000  5262  5262 D BreventServer: Force stop com.mrcigi.aktprofiles(load brevent)
06-18 23:14:26.005  5262  5262 D BreventServer: Force stop com.google.android.keep(load brevent)
06-18 23:14:26.009  5262  5262 D BreventServer: Force stop com.alensw.PicFolder(load brevent)
06-18 23:14:26.021  5262  5262 D BreventServer: Force stop com.ideashower.readitlater.pro(load brevent)
06-18 23:14:26.027  5262  5262 D BreventServer: Force stop mega.privacy.android.app(load brevent)
06-18 23:14:26.037  5262  5262 D BreventServer: Force stop com.neuralprisma(load brevent)
06-18 23:14:26.041  5262  5262 D BreventServer: Force stop melandru.lonicera(load brevent)
06-18 23:14:26.046  5262  5262 D BreventServer: Force stop com.pleasure.trace_wechat(load brevent)
06-18 23:14:26.049  5262  5262 D BreventServer: Force stop com.google.android.play.games(load brevent)
06-18 23:14:26.054  5262  5262 D BreventServer: Force stop com.netease.cloudmusic(load brevent)
06-18 23:14:26.065  5262  5262 D BreventServer: Force stop tv.danmaku.bili(load brevent)
06-18 23:14:26.072  5262  5262 D BreventServer: Force stop com.netease.yanxuan(load brevent)
06-18 23:14:26.076  5262  5262 D BreventServer: Force stop party.danyang.nationalgeographic(load brevent)
06-18 23:14:26.080  5262  5262 D BreventServer: Force stop com.edward.iconpack.pelmix(load brevent)
06-18 23:14:26.081  5262  5262 I BreventServer: loading brevent conf
06-18 23:14:26.089  5262  5262 D BreventServer: get service: appwidget: android.os.BinderProxy@d6d3eda
06-18 23:14:26.095  5262  5262 D BreventServer: get service: activity: android.os.BinderProxy@7465f0b
06-18 23:14:26.098  5262  5262 W BreventServer: has no BreventActivity
06-18 23:14:26.098  5262  5262 E BreventServer: Can't be run as root, please open Brevent
06-18 23:14:26.126  5250  5250 E BreventLoader: worker 5262 exited with status 1
06-18 23:14:26.126  5250  5250 D BreventLoader: signal arrived, update: 0
06-18 23:14:26.127  5245  5245 D BreventLoader: worker 5250 exited with status 0
--- brevent end ---

再次运行命令黑域就以root模式运行了

**Comment by vvb2060** [comment]
```
06-18 23:14:26.098 5262 5262 E BreventServer: Can't be run as root, please open Brevent
```
你的ROM默认让adb shell取得root权限，这个报错是未开启“允许root运行”导致的，开启时黑域不在屏幕最上层就会直接退出。
第二次成功了应该是因为打开了黑域应用。

**Comment by liudongmiao** [comment]
@vvb2060 给你加了写权限，你看看有没有权限关闭 issue 等。

@heganyuliang 请不要使用非官方方式启动黑域。比如 ROOT，已经提供了界面内的点击。

顺便说一句，由于酷安上我不会验证手机号，所以不会在酷安上说话。但是，可以去微博吐槽@黑域APP 。
