### ISSUE TITLE
以root方式无法开启Brevent问题

### ISSUE THREAD

**Issue by Ostryopsis** [brevent/Brevent#48]
@liudongmiao 
samsung/trlteduoszh/trltechnzh:6.0.1/MMB29M/N9100ZHU1DQG1:user/release-keys
SELinux: true

WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '08-22 18:13:39.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-22 18:13:39.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

0_a209@trltechnzh:/ $ su
root@trltechnzh:/ # ash
/ # pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
/ # logcat -b crash -t '08-22 18:13:39.000' -d
Unable to open log device 'crash'
/ # logcat -b main -t '08-22 18:13:39.000' -d -s BreventLoader BreventServer
08-22 18:07:35.085 21818 21818 D BreventLoader: line:
08-22 18:07:35.085 21818 21818 E BreventLoader: can't get path
08-22 18:07:35.095 21804 21804 E BreventLoader: worker 21818 exited with status 
08-22 18:12:17.795 22348 22348 D BreventLoader: line:
08-22 18:12:17.795 22348 22348 E BreventLoader: can't get path
08-22 18:12:17.805 22329 22329 E BreventLoader: worker 22348 exited with status 255
08-22 18:13:39.515 22836 22836 D BreventLoader: line:
08-22 18:13:39.515 22836 22836 E BreventLoader: can't get path
08-22 18:13:39.515 22795 22795 E BreventLoader: worker 22836 exited with status 255
/ #

**Comment by liudongmiao** [comment]
你应该能看到提示...请换个 su 吧...
