### ISSUE TITLE
关于黑阈识别区域禁止国内用户Play支付的问题

### ISSUE THREAD

**Issue by bottledcute** [brevent/Brevent#480]
能说明下为何禁止国内通过Play支付？恶意退款太多？有啥办法能用Play支付？

**Comment by vvb2060** [comment]
因为很多人选择了play商店支付后不能始终保证外网通畅，丢失支付状态，故作此限制。
可拔掉 SIM 卡，或者通过执行指令功能，设置属性 `setprop debug.me.piebridge.brevent.play true `来绕过检查。

**Comment by liudongmiao** [comment]
由于代码错误，brevent.play 之间没有 .，正确指令应为

```
setprop setprop debug.me.piebridge.breventplay true
```

**Comment by liudongmiao** [comment]
自 3.6.8 起，恢复 brevent.play 中间的 .，后续版本指令为：

```
setprop debug.me.piebridge.brevent.play true
```
