### ISSUE TITLE
循环启动和停止通知侦听器的问题

### ISSUE THREAD

**Issue by Tao93** [brevent/Brevent#482]
问题描述：
应用的进程可能循环 (被系统) 启动和 (被黑阈) 停止，永不停止。

复现步骤：
1. 新安装一个声明通知侦听的应用
2. 在黑阈中标记要黑它 (这一步常常在新安装应用时默认就会黑)
3. 在系统设置中授予此应用 Notification Access 权限。

问题原因：
系统会自动启动获得 Notification Access 权限的应用，但是此应用的进程会马上被黑阈杀掉，然后系统再次启动应用，黑阈再次杀掉应用，如此往复。

尽管在黑阈中无法再次限制已获得 Notification Access 权限的应用，但是应用可能先被标记要被黑 (这一步常常是默认进行的)，然后再获得 Notification Access 权限，黑阈没有考虑到这一点。

**Comment by vvb2060** [comment]
其实考虑到了的，比如闹钟应用就是服务端也有判断，自动取消黑阈。其它不怎么重要的仅UI判断。
关于通知侦听器，它不像无障碍功能，强行停止后系统会自动取消权限。有通知侦听器服务的应用被强行停止后它可以利用(滥用?)此权限复活。造成了这个问题。
在打开黑阈应用后，应该会有提示，建议取消黑阈它。

对于如此特殊的通知访问权，可能需要改变当前策略……

**Comment by Tao93** [comment]
@vvb2060 
可是黑阈并没有提示「建议取消黑阈」，而是继续在不停地杀应用，而应用不停的启动。

**Comment by liudongmiao** [comment]
> 尽管在黑阈中无法再次限制已获得 Notification Access 权限的应用

进入黑阈应该会提示你“重要应用”。如果你不进入，确实看不到。
目前在后台判断的有：输入法，下一个闹钟，壁纸，vpn 等，不包含 通知权限。
很多检查，黑阈服务 会相当麻烦（毕竟使用私有 API），所以这个工作交给管理界面。

> 建议取消黑阈

这个功能，默认设置是仅对系统应用。你可自行设置为“全部”。
入口在 黑阈 - 设置 - 7 次系统状态。

要使用黑阈，达到不省电甚至费电的效果，也有好多办法。
比如你这种“通知侦听器”，再比如设置“允许同步”，黑阈 GMS，黑阈经常被其它应用依赖的应用。
但是，没法一一而足，黑阈只尽力提示，不能保证所有。

**Comment by liudongmiao** [comment]
还有一点，通知侦听器 属于一个高级功能，不像 输入法、闹钟、壁纸、VPN 这么常见。

**Comment by Tao93** [comment]
@liudongmiao  小米运动和 Fitbit 应用等，如果需要让手环类设备能显示通知，对应的应用就需要 notification access 权限。黑阈在杀应用前检查一下应用中是否有 [NotificationListenerService](https://developer.android.com/reference/android/service/notification/NotificationListenerService) 不可以吗？

**Comment by liudongmiao** [comment]
没有计划，你可以不黑阈此类应用。

另外，你可以试试允许同步，这个允许存活 30 秒。
然后，如果有通知，不会处理。

**Comment by liudongmiao** [comment]
此外，再次确认，技术上非常有难度。

1. 获取它基本只有通过 provider 调用，也就是 settings 这个命令
    但是，这个命令，至少在 android 7 以前，如果调用次数到 6 万多次，就会出问题；黑阈直接访问服务，调用非常快。你使用 settings 命令 (java 版本) ，一次也要近 300ms 秒左右。

2. 当有 shell command 的时候，已经到了 android 8 ...
   而黑阈基本不针对不同平台优化。

3. 添加进通知服务，是你非常主观的行为，可以人为控制。
    且这个不像 输入法、闹钟、壁纸、VPN 那么常见，且这些的调用，基本不对系统造成影响。

4. 早先输入法也是使用 settings 读取，后来去掉；再后来发现可以通过 input_method 服务来获取。
   但是，通知获取，如果读取通知服务的话，在部分机型上会非常慢，甚至会导致系统重启。
   当前，通知是黑阈服务获取 1 次以后，后续解析通知事件。
 （虽然在 5.0 上有一点点兼容性问题，但是 5.0 - 6.0 黑阈属于实验性支持。）
