### ISSUE TITLE
播放状态检测

### ISSUE THREAD

**Issue by ssuii** [brevent/Brevent#486]
有定时停止播放音乐的习惯（睡觉之类的），能否检测到播放状态停止后一段时间内强行停止？

**Comment by zbqwla73264** [comment]
如果应用定时停止播放会取消通知，那么这是默认行为。如果不取消通知，无法分辨此情况与暂停播放。

**Comment by vvb2060** [comment]
如果应用定时停止播放会取消通知，那么这是默认行为。如果不取消通知，无法分辨此情况与暂停播放。

**Comment by liudongmiao** [comment]
如果没有其它的操作的话，可能有点难。

黑阈最近版本，仅依赖事件日志。
一般来说，播放与暂停本身不会触发这个检查。

但是其它的操作会触发：
- 手动操作黑阈清单内应用
- 黑阈清单内应用被恶意运行
- 或者黑阈清单内应用，到达处理时机（黑阈设置里的时间）

有了这个机制以后，如果黑阈清单内应用没有任何动作，黑阈不会开启检查，因为检查本身也需要一小点资源。
