### ISSUE TITLE
应用待机失效

### ISSUE THREAD

**Issue by ssuii** [brevent/Brevent#487]
设置里显示支持应用待机，但现在测试后发现应用一直无法待机（应用右侧小图标也显示：超时后待机），执行指令里重启服务后偶尔能待机

**Comment by vvb2060** [comment]
黑阈-反馈-日志，保存日志压缩包后拖动到GitHub评论框上传。

**Comment by liudongmiao** [comment]
黑阈只尽力调用 API，但是是否真正待机，则不保证。
如果你设置很小的时间，小到系统待机最小阈值，则极有可能不会待机。

日志里，黑阈都会说，是否有调用 API。

此外，黑阈的状态支持，基本上仅启动黑阈时检查。
如果你动态调整，则有可能会发生变化，而黑阈不知道。
比如 Android 9 下的待机，和好多个属性啊设置啊相关。
