### ISSUE TITLE
关于ROOT启动与adb启动

### ISSUE THREAD

**Issue by FulLiunian** [brevent/Brevent#49]
在手机root过 以及黑域被授权过root启动后 再去用电脑 adb方案启动会默认为root方案启动 不会用adb方案启动

adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh

![qq 20170822232425](https://user-images.githubusercontent.com/29416280/29573362-612f7444-8791-11e7-91f7-61960586fe99.png)

**Comment by liudongmiao** [comment]
去问你的 root 提供方。
