### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by fanyuanhang** [brevent/Brevent#498]
你好，我想请问如果我退出黑域，或者在任务栏中把黑域划掉，它还会不会一直在后台工作？还是说我必须让黑域一直呆在任务栏不划掉他？
还有黑域界面有一个无需处理的程序缓存进程列表，这些需不需要也给他黑域了呢？还是说不管他就行

**Comment by vvb2060** [comment]
会工作的，可以划掉。
如果这些应用一直是这种状态，也就不需要黑阈它们。
