### ISSUE TITLE
Brevent going wrong on NEXUS 6p

### ISSUE THREAD

**Issue by ZHLinn** [brevent/Brevent#499]
--- crash start ---
[command] logcat -b crash -t '02-04 19:41:10.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '02-04 19:41:10.000' -d -s BreventLoader BreventServer
02-04 19:41:19.539 17356 17356 D BreventLoader: line: package:/data/app/me.piebridge.brevent-2NU5v4rPNFg2-Mbq6wQwbA==/base.apk
02-04 19:41:20.463 17356 17356 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2NU5v4rPNFg2-Mbq6wQwbA==/base.apk
02-04 19:41:20.464 17521 17521 D BreventLoader: start: 1549280470
--- brevent end ---
```

**Comment by liudongmiao** [comment]
it should be more logs.

may it's caused by your device is too slow.
