### ISSUE TITLE
黒域新用户疑问

### ISSUE THREAD

**Issue by ddknight** [brevent/Brevent#5]
首先不是很理解黒域的意义,虽然有人解释说这个概念来自三体,然而我们没有读过三体,所以还请解读解读,
1.这个软件的意义在于什么,我听很多安卓的用户说,他们的手机都喜欢装黒域,因为可以防止互相启动的问题,比如手机启动了支付宝,会启动淘宝,会启动其他的很多软件,这个问题可以通过黒域去进行管理.黒域还有更多可以扩展的功能么?
2.我觉得可以在软件的README.MD中加入更多的软件介绍.这样可以让不了解这个软件的人了解的更多一点.

PS.对之前在版本控制的issues中写疑问表示抱歉.

**Comment by liudongmiao** [comment]
各个商店的介绍看了么？play 的，国内应用宝/魅族/锤子/酷安。
