### ISSUE TITLE
The Icon of the Latest Version Is Not Displaying Properly

### ISSUE THREAD

**Issue by 7nights** [brevent/Brevent#50]
![image](https://user-images.githubusercontent.com/3193621/29595100-f16cfdc8-87e7-11e7-9fca-54858ea7ceda.png)

As you can see at the bottom, Brevent's icon seems to be cropped... A little bit annoying for those people with OCD 😀😀😀

**Comment by liudongmiao** [comment]
It's generated by android studio preview 3...
Maybe I should generate again to avoid this?

You can see the change here: https://github.com/brevent/Brevent/commit/8ac5b6f2219a407ec74b26b5431555cce0bec3d6

**Comment by 7nights** [comment]
I just checked those icons changed since 8ac5b6f but everything looks fine in Chrome... Does Pixel launcher use Adaptive Icons feature to display app icons? Is there any chance that it's a bug of Android itself?
