### ISSUE TITLE
MIUI10  magiskroot

### ISSUE THREAD

**Issue by Leetiantian0913** [brevent/Brevent#501]
老哥，过年好！我是MIUI10.magisk root不能启动，总是正在获取进程，请稍候，也就没有办法抓取日志，支个招，我抓取日志

**Comment by liudongmiao** [comment]
我本人无法提供任何协助。

有 root，你总可以获取日志。

logcat -s BreventUI BreventServer

不要使用任何方式限制 黑阈 访问本地网络。
