### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 473576805** [brevent/Brevent#505]
--- brevent start ---
[command] logcat -b main -t '02-17 17:41:30.000' -d -s BreventLoader BreventServer
02-17 17:41:30.662 12104 12104 I BreventLoader: sdk: 28
02-17 17:41:30.682 12109 12109 I BreventLoader: pm path me.piebridge.brevent
02-17 17:41:30.719 12109 12109 I BreventLoader: line: package:/data/app/me.piebridge.brevent-K9AkB_qZphA5ubyaLqRX5Q==/base.apk
02-17 17:41:30.721 12109 12109 I BreventLoader: loader path: /data/app/me.piebridge.brevent-K9AkB_qZphA5ubyaLqRX5Q==/base.apk
02-17 17:41:30.722 12113 12113 I BreventLoader: start: 1550396490
02-17 17:41:31.036 12113 12113 I BreventServer: args: [10, me.piebridge.brevent, 1550396490]
02-17 17:41:31.067 12113 12113 I BreventServer: server log name: server.20190217.1741.12113.txt
02-17 17:41:31.067 12113 12113 I BreventServer: starting Brevent Server 3.6.3
02-17 17:41:31.081 12113 12113 I BreventServer: brevent version: 3.6.3
02-17 17:41:31.091 12113 12113 E BreventServer: version unmatched
02-17 17:41:31.100 12109 12109 E BreventLoader: worker 12113 exited with status 3
02-17 17:41:31.100 12109 12109 I BreventLoader: signal arrived, update: 0
02-17 17:41:31.103 12104 12104 I BreventLoader: worker 12109 exited with status 0
--- brevent end ---

**Comment by liudongmiao** [comment]
触发了黑阈可信环境检查，请尝试最新 beta 版 3.6.3.1: https://jianyu.io/br/beta/
