### ISSUE TITLE
淘宝，支付宝，京东应用按返回键退出不会被马上黑域

### ISSUE THREAD

**Issue by cybergeek2077** [brevent/Brevent#510]
所有应用都是play最新版，工作模式root，手机pixel3，需要日志吗

**Comment by vvb2060** [comment]
想要立即被黑阈，请从概览屏幕中划掉，否则需要等待超时。

**Comment by cybergeek2077** [comment]
> 想要立即被黑阈，请从概览屏幕中划掉，否则需要等待超时。

那为什么哔哩哔哩这样的应用 按返回键退出会被马上黑域

**Comment by vvb2060** [comment]
#511 bilibili被识别为不在最近任务列表中，所以立即被停止。

**Comment by liudongmiao** [comment]
返回不强行停止是预设行为。
