### ISSUE TITLE
登录微信无法支付

### ISSUE THREAD

**Issue by wanlu** [brevent/Brevent#513]
有没有别的方便一点的支付方式啊？一直找不到支付入口。。。点play说我中国区不能play支付，登录微信之后也没出现什么支付选项。。。就这么小几十块的支付折腾死我了。。。

**Comment by liudongmiao** [comment]
如果能登录微信，但是见不到微信图标，说明是从 Play 商店安装的。根据 Play 商店政策，Play 商店分发的版本，不能有其他支付方式。

Play 并不向中国用户开放，加之不断有中国用户反馈无法识别问题，所以直接取消了。

现在的话，您有两个办法：

1. 从国内下载，或者单纯重新安装一下，就可以见到微信支付了。https://br.jianyu.io

2. 拔掉 sim 卡，继续使用 Play 支付。黑阈使用 Sim 卡判断是否为中国用户。

**Comment by wanlu** [comment]
还是拔掉sim卡好用。。。终于支付成功了。。。app很好用，付款支持一下，继续加油！

**Comment by liudongmiao** [comment]
https://github.com/brevent/Brevent/issues/480
