### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HMLDXHZ** [brevent/Brevent#515]
--- crash start ---
>>> /system/bin/logcat -b crash -t '02-23 20:38:39.000' -d
F/libc    (29244): Fatal signal 6 (SIGABRT), code -6 in tid 29244 (main)
I/DEBUG   (  262): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  262): Build fingerprint: 'LANDI/APOS_A8/APOS_A8:5.1.1/LMY47V/builder01172121:user/test-keys'
I/DEBUG   (  262): Revision: '0'
I/DEBUG   (  262): ABI: 'arm'
I/DEBUG   (  262): pid: 29244, tid: 29244, name: main  >>> brevent_server <<<
I/DEBUG   (  262): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
I/DEBUG   (  262): Abort message: 'art/runtime/thread.cc:1143] No pending exception expected: java.lang.ClassNotFoundException: Didn't find class "me.piebridge.brevent.server.BreventServer" on path: DexPathList[[zip file "/mnt/asec/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /lib, /usr/lib, /home/EPT_Middleware/lib]]'
I/DEBUG   (  262):     r0 00000000  r1 0000723c  r2 00000006  r3 00000000
I/DEBUG   (  262):     r4 b6f7de38  r5 00000006  r6 00000002  r7 0000010c
I/DEBUG   (  262):     r8 00000000  r9 b7d33138  sl b7d3e0f8  fp 00000001
I/DEBUG   (  262):     ip 0000723c  sp be856400  lr b6e0bac9  pc b6e31ba0  cpsr 60070010
I/DEBUG   (  262):
I/DEBUG   (  262): backtrace:
I/DEBUG   (  262):     #00 pc 00039ba0  /system/lib/libc.so (tgkill+12)
I/DEBUG   (  262):     #01 pc 00013ac5  /system/lib/libc.so (pthread_kill+52)
I/DEBUG   (  262):     #02 pc 000146db  /system/lib/libc.so (raise+10)
I/DEBUG   (  262):     #03 pc 00010e7d  /system/lib/libc.so (__libc_android_abort+36)
I/DEBUG   (  262):     #04 pc 0000f534  /system/lib/libc.so (abort+4)
I/DEBUG   (  262):     #05 pc 00215c29  /system/lib/libart.so (art::Runtime::Abort()+160)
I/DEBUG   (  262):     #06 pc 000a6285  /system/lib/libart.so (art::LogMessage::~LogMessage()+1312)
I/DEBUG   (  262):     #07 pc 00223487  /system/lib/libart.so (art::Thread::AssertNoPendingException() const+354)
I/DEBUG   (  262):     #08 pc 000d669b  /system/lib/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+14)
I/DEBUG   (  262):     #09 pc 001cbca5  /system/lib/libart.so (art::JNI::FindClass(_JNIEnv*, char const*)+788)
I/DEBUG   (  262):     #10 pc 00001f2d  /system/lib/libnativehelper.so (jniRegisterNativeMethods+20)
I/DEBUG   (  262):     #11 pc 0005bd7d  /system/lib/libandroid_runtime.so
I/DEBUG   (  262):     #12 pc 0005cea5  /system/lib/libandroid_runtime.so (android::AndroidRuntime::startReg(_JNIEnv*)+28)
I/DEBUG   (  262):     #13 pc 0005cfed  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+288)
I/DEBUG   (  262):     #14 pc 0000167b  /system/bin/app_process32
I/DEBUG   (  262):     #15 pc 0000f3f1  /system/lib/libc.so (__libc_init+44)
I/DEBUG   (  262):     #16 pc 000017b4  /system/bin/app_process32
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '02-23 20:38:39.000' -d -s BreventLoader BreventServer
D/BreventLoader(29218): loader path: /mnt/asec/me.piebridge.brevent-1/base.apk
E/BreventLoader(29218): worker 29244 exited on signal 6
D/BreventLoader(29218): signal arrived, update: 0
D/BreventLoader(29213): worker 29218 exited with status 0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
don't install brevent to /mnt/asec/.

in short, don't try to install brevent to external sdcard.
