### ISSUE TITLE
auto brevent option is missing

### ISSUE THREAD

**Issue by rex993** [brevent/Brevent#516]
Updated Note8 to Android Pie and had to reinstall my apps. Reinstalled Brevent and noticed that I do not have the option to disable auto Brevent anymore. It use to be the first option in the list.

![screenshot_20190224-224257_brevent](https://user-images.githubusercontent.com/6278392/53298694-25a73900-3886-11e9-972a-a470d35c88cc.jpg)

**Comment by liudongmiao** [comment]
default is on.

tap "support status" 7 times to show the options.
