### ISSUE TITLE
关于黑域“应用操作”的建议

### ISSUE THREAD

**Issue by 20171213** [brevent/Brevent#518]
请求“应用操作”增添搜索按钮和排除系统应用的功能

**Comment by Vstory** [comment]
目前应用操作的每个权限进去，都会分开显示系统应用和用户应用。

**Comment by liudongmiao** [comment]
1. 搜索...没有任何计划，如果有场景，可能会考虑。

目前的排序，基本上可以替代。

2. 对于应用的，建议外层搜索或其他方式找到应用后，然后直接进入其 应用操作。

总的来说，我并不擅长界面，功能在这里，将就着用吧。
