### ISSUE TITLE
黑域 2.1.5a启动超时

### ISSUE THREAD

**Issue by AdrianStone0405** [brevent/Brevent#52]
黑域版本：2.1.5a & 2.1.4
设备型号：华为荣耀5X（KIW-UL00）
Android版本：7.1.2
LineageOS版本：14.1-20170816-nightly-kiwi

出现问题：
无法启动，和在wifi调试下，会导致系统自动重启，而黑域一直无法启动。

启动报告：
found old brevent_server, pid: 9392, killing
checking for server....started, pid: 11934
checking for stable...........timeout

 崩溃日志：
08-23 11:30:39.578  2375  2375 E AndroidRuntime: FATAL EXCEPTION: main
08-23 11:30:39.578  2375  2375 E AndroidRuntime: Process: android.process.media, PID: 2375
08-23 11:30:39.578  2375  2375 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 6210, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:438)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at com.android.providers.media.MediaProvider$ScannerClient.onMediaScannerConnected(MediaProvider.java:3907)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.media.MediaScannerConnection.onServiceConnected(MediaScannerConnection.java:256)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-23 11:30:39.578  2375  2375 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-23 11:50:48.060 11377 11377 E AndroidRuntime: FATAL EXCEPTION: main
08-23 11:50:48.060 11377 11377 E AndroidRuntime: Process: com.v2ray.actinium:tile, PID: 11377
08-23 11:50:48.060 11377 11377 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service com.v2ray.actinium.service.ActiniumTileService@2529905 with Intent { cmp=com.v2ray.actinium/.service.ActiniumTileService (has extras) }: java.lang.RuntimeException: Unable to reach IQSService
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.app.ActivityThread.handleBindService(ActivityThread.java:3257)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.app.ActivityThread.-wrap3(ActivityThread.java)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-23 11:50:48.060 11377 11377 E AndroidRuntime: Caused by: java.lang.RuntimeException: Unable to reach IQSService
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.service.quicksettings.TileService.onBind(TileService.java:329)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.app.ActivityThread.handleBindService(ActivityThread.java:3243)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        ... 8 more
08-23 11:50:48.060 11377 11377 E AndroidRuntime: Caused by: android.os.DeadObjectException
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.service.quicksettings.IQSService$Stub$Proxy.getTile(IQSService.java:185)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        at android.service.quicksettings.TileService.onBind(TileService.java:327)
08-23 11:50:48.060 11377 11377 E AndroidRuntime:        ... 9 more

黑域服务日志：
08-23 11:47:12.561  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:47:12.593  9392  9392 D BreventServer: check and brevent
08-23 11:47:12.603  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:47:12.653  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:47:17.606  9392  9392 W BreventServer: dump notification [] timeout
08-23 11:47:17.739  9392  9392 D BreventServer: check again in 3600s
08-23 11:47:17.739  9392  9392 D BreventServer: check and brevent, took 5139ms
08-23 11:47:17.740  9392  9392 D BreventServer: update current to com.teslacoilsw.launcher
08-23 11:47:17.740  9392  9392 D BreventServer: previous: me.piebridge.brevent, packageName: com.teslacoilsw.launcher
08-23 11:47:17.740  9392  9392 D BreventServer: update current to me.piebridge.brevent
08-23 11:47:17.740  9392  9392 D BreventServer: previous: com.teslacoilsw.launcher, packageName: me.piebridge.brevent
08-23 11:47:22.757  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:47:22.789  9392  9392 D BreventServer: check and brevent
08-23 11:47:22.793  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:47:22.854  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:47:27.793  9392  9392 W BreventServer: dump notification [] timeout
08-23 11:47:27.990  9392  9392 D BreventServer: Force stop cn.etouch.ecalendar2(noRecent)
08-23 11:47:28.038  9392  9392 D BreventServer: standby cn.etouch.ecalendar2
08-23 11:47:28.041  9392  9392 D BreventServer: check again in 3600s
08-23 11:47:28.041  9392  9392 D BreventServer: check and brevent, took 5251ms
08-23 11:47:28.041  9392  9392 D BreventServer: cn.etouch.ecalendar2: widgets or system
08-23 11:47:33.066  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:47:33.108  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:47:33.174  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:47:38.196  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:47:38.225  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:47:39.160  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:47:44.187  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:47:44.238  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:47:45.174  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:47:50.190  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:47:50.218  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:47:51.204  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:47:56.225  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:47:56.256  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:47:57.210  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:48:02.231  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:48:02.255  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:48:03.241  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:48:08.261  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:48:08.293  9392  9392 D BreventServer: check and brevent
08-23 11:48:08.301  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:48:09.660  9392  9415 W BreventServer: has no BreventActivity
08-23 11:48:13.306  9392  9392 W BreventServer: dump notification [] timeout
08-23 11:48:13.417  9392  9392 D BreventServer: Force stop cn.etouch.ecalendar2(service)
08-23 11:48:13.419  9392  9392 D BreventServer: standby cn.etouch.ecalendar2
08-23 11:48:13.425  9392  9392 D BreventServer: Force stop com.google.android.apps.plus(noRecent)
08-23 11:48:13.426  9392  9392 D BreventServer: standby com.google.android.apps.plus
08-23 11:48:13.436  9392  9392 D BreventServer: Force stop com.google.android.apps.photos(noRecent)
08-23 11:48:13.438  9392  9392 D BreventServer: standby com.google.android.apps.photos
08-23 11:48:13.442  9392  9392 D BreventServer: standby cn.etouch.ecalendar2
08-23 11:48:13.443  9392  9392 D BreventServer: check again in 3600s
08-23 11:48:13.443  9392  9392 D BreventServer: check and brevent, took 5138ms
08-23 11:48:13.443  9392  9392 D BreventServer: update current to com.android.settings
08-23 11:48:13.443  9392  9392 D BreventServer: previous: me.piebridge.brevent, packageName: com.android.settings
08-23 11:48:37.822  9392  9392 D BreventServer: update current to com.teslacoilsw.launcher
08-23 11:48:37.822  9392  9392 D BreventServer: previous: com.android.settings, packageName: com.teslacoilsw.launcher
08-23 11:48:39.917  9392  9392 D BreventServer: com.google.android.apps.docs.editors.sheets: widgets or system
08-23 11:48:40.391  9392  9392 D BreventServer: update current to me.piebridge.brevent
08-23 11:48:40.391  9392  9392 D BreventServer: previous: com.teslacoilsw.launcher, packageName: me.piebridge.brevent
08-23 11:48:40.612  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:48:45.629  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:48:45.659  9392  9392 D BreventServer: check and brevent
08-23 11:48:45.665  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:48:46.644  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:48:50.668  9392  9392 W BreventServer: dump notification [] timeout
08-23 11:48:50.798  9392  9392 D BreventServer: ignore com.google.android.apps.docs.editors.sheets, wait for the service check
08-23 11:48:50.826  9392  9392 D BreventServer: Force stop com.google.android.apps.plus(noRecent)
08-23 11:48:50.827  9392  9392 D BreventServer: standby com.google.android.apps.plus
08-23 11:48:50.833  9392  9392 D BreventServer: Force stop com.google.android.apps.photos(noRecent)
08-23 11:48:50.834  9392  9392 D BreventServer: standby com.google.android.apps.photos
08-23 11:48:50.835  9392  9392 D BreventServer: check again in 3600s
08-23 11:48:50.835  9392  9392 D BreventServer: check and brevent, took 5168ms
08-23 11:48:55.871  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:48:55.898  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:48:55.947  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:00.959  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:01.010  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:01.952  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:06.973  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:07.015  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:07.957  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:12.975  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:13.025  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:13.975  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:18.990  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:19.025  9392  9392 D BreventServer: check and brevent
08-23 11:49:19.034  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:19.993  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:24.031  9392  9392 W BreventServer: dump notification [] timeout
08-23 11:49:24.203  9392  9392 D BreventServer: Force stop com.google.android.apps.docs.editors.sheets(service)
08-23 11:49:24.207  9392  9392 D BreventServer: standby com.google.android.apps.docs.editors.sheets
08-23 11:49:24.217  9392  9392 D BreventServer: standby com.google.android.apps.plus
08-23 11:49:24.225  9392  9392 D BreventServer: standby com.google.android.apps.photos
08-23 11:49:24.225  9392  9392 D BreventServer: check again in 3600s
08-23 11:49:24.225  9392  9392 D BreventServer: check and brevent, took 5199ms
08-23 11:49:29.249  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:29.283  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:29.327  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:34.344  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:34.383  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:35.325  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:40.358  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:40.392  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:41.348  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:46.365  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:46.390  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:47.367  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:52.389  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:52.422  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:53.376  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:49:58.393  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:49:58.435  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:49:59.408  9392  9415 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:50:04.426  9392  9415 W BreventServer: dump notification [] timeout
08-23 11:50:04.449  9392  9392 D BreventServer: update current to com.android.settings
08-23 11:50:04.452  9392  9415 W BreventServer: cannot handle: Broken pipe
08-23 11:50:37.526  9392  9392 D BreventServer: com.google.android.dialer: priority
08-23 11:50:37.894  9392  9392 D BreventServer: check and brevent
08-23 11:50:42.896  9392  9392 W BreventServer: dump notification [] timeout
08-23 11:50:43.153  9392  9392 D BreventServer: Force stop com.google.android.apps.docs.editors.sheets(noRecent)
08-23 11:50:43.155  9392  9392 D BreventServer: standby com.google.android.apps.docs.editors.sheets
08-23 11:50:43.155  9392  9392 D BreventServer: ignore com.google.android.dialer, wait for the service check
08-23 11:50:43.164  9392  9392 D BreventServer: Force stop com.google.android.apps.plus(noRecent)
08-23 11:50:43.168  9392  9392 D BreventServer: standby com.google.android.apps.plus
08-23 11:50:43.194  9392  9392 D BreventServer: Force stop com.google.android.apps.photos(noRecent)
08-23 11:50:43.195  9392  9392 D BreventServer: standby com.google.android.apps.photos
08-23 11:50:43.205  9392  9392 D BreventServer: Force stop com.google.android.apps.inbox(noRecent)
08-23 11:50:43.208  9392  9392 D BreventServer: standby com.google.android.apps.inbox
08-23 11:50:43.209  9392  9392 D BreventServer: check again in 3600s
08-23 11:50:43.209  9392  9392 D BreventServer: check and brevent, took 5314ms
08-23 11:50:43.210  9392  9392 D BreventServer: com.google.android.apps.docs.editors.sheets: widgets or system
08-23 11:50:53.289  9392  9392 D BreventServer: update current to com.google.android.dialer
08-23 11:50:53.289  9392  9392 D BreventServer: previous: com.android.settings, packageName: com.google.android.dialer
08-23 11:51:02.221  9392  9392 D BreventServer: check and brevent
08-23 11:51:07.223  9392  9392 W BreventServer: dump notification [] timeout
08-23 11:51:07.367  9392  9392 I BreventServer: won't block com.github.shadowsocks, depended by {com.android.systemui}
08-23 11:51:07.376  9392  9392 D BreventServer: Force stop com.google.android.apps.docs.editors.sheets(service)
08-23 11:51:07.383  9392  9392 D BreventServer: standby com.google.android.apps.docs.editors.sheets
08-23 11:51:07.387  9392  9392 D BreventServer: Force stop com.google.android.apps.inbox(service)
08-23 11:51:07.388  9392  9392 D BreventServer: standby com.google.android.apps.inbox
08-23 11:51:07.392  9392  9392 D BreventServer: Force stop com.v2ray.actinium(service)
08-23 11:51:07.393  9392  9392 D BreventServer: standby com.v2ray.actinium
08-23 11:51:07.394  9392  9392 D BreventServer: standby com.google.android.apps.docs.editors.sheets
08-23 11:51:07.397  9392  9392 D BreventServer: standby com.google.android.apps.plus
08-23 11:51:07.400  9392  9392 D BreventServer: standby com.google.android.apps.photos
08-23 11:51:07.405  9392  9392 D BreventServer: standby com.google.android.apps.inbox
08-23 11:51:07.405  9392  9392 D BreventServer: check again in 47s
08-23 11:51:07.405  9392  9392 D BreventServer: check and brevent, took 5183ms
08-23 11:51:13.053  9392  9392 D BreventServer: update current to com.android.settings
08-23 11:51:13.053  9392  9392 D BreventServer: previous: com.google.android.dialer, packageName: com.android.settings
08-23 11:51:22.191  9392  9392 D BreventServer: com.google.android.apps.docs.editors.sheets: widgets or system
08-23 11:51:37.851  9369  9369 E BreventLoader: worker 9392 exited on signal 15
08-23 11:51:37.851  9369  9369 D BreventLoader: signal arrived, update: 0
08-23 11:51:39.826 11920 11920 D BreventLoader: line: package:/data/app/me.piebridge.brevent-1/base.apk
08-23 11:51:39.826 11920 11920 D BreventLoader:
08-23 11:51:39.853 11920 11920 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
08-23 11:51:40.786 11934 11934 D BreventServer: get service: package
08-23 11:51:40.787 11934 11934 D BreventServer: args: [10]
08-23 11:51:40.787 11934 11934 I BreventServer: signal: 10
08-23 11:51:40.854 11934 11934 I BreventServer: starting Brevent Server 2.1.5a
08-23 11:51:40.970 11934 11934 D BreventServer: version: 0
08-23 11:51:41.028 11934 11934 D BreventServer: get service: package
08-23 11:51:41.057 11934 11934 I BreventServer: brevent user: 0, uid: 2000
08-23 11:51:41.076 11934 11934 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-23 11:51:41.187 11934 11934 I BreventServer: loading brevent list
08-23 11:51:41.212 11934 11934 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 103
08-23 11:51:41.300 11934 11934 I BreventServer: loading brevent conf
08-23 11:51:41.364 11934 11934 D BreventServer: get service: appwidget
08-23 11:51:41.379 11934 11934 I BreventServer: checking standby, sdk: 25
08-23 11:51:41.381 11934 11934 D BreventServer: get service: usagestats
08-23 11:51:42.337 11934 11934 D BreventServer: line: mAppIdleEnabled=true mAppIdleTempParoled=false mCharging=true mLastAppIdleParoledTime=0
08-23 11:51:42.383 11934 11934 D BreventServer: check and brevent
08-23 11:51:42.384 11934 11951 I BreventServer: Brevent Event, now: 1503460302
08-23 11:51:42.385 11934 11934 D BreventServer: get service: notification
08-23 11:51:42.458 11934 11951 I BreventServer: system_server: 958, now: 1503460302
08-23 11:51:47.386 11934 11934 W BreventServer: dump notification [] timeout
08-23 11:51:47.405 11934 11934 D BreventServer: get service: activity
08-23 11:51:47.425 11934 11934 D BreventServer: get service: alarm
08-23 11:51:47.442 11934 11934 D BreventServer: get service: wallpaper
08-23 11:51:47.498 11934 11934 D BreventServer: get service: media.audio_flinger
08-23 11:51:47.655 11934 11934 D BreventServer: get service: deviceidle
08-23 11:51:47.683 11934 11934 D BreventServer: Force stop com.github.shadowsocks(noRecent)
08-23 11:51:47.686 11934 11934 D BreventServer: standby com.github.shadowsocks
08-23 11:51:47.693 11934 11934 D BreventServer: Force stop com.google.android.apps.docs.editors.sheets(noRecent)
08-23 11:51:47.694 11934 11934 D BreventServer: standby com.google.android.apps.docs.editors.sheets
08-23 11:51:47.713 11934 11934 D BreventServer: Force stop com.google.android.dialer(priority service)
08-23 11:51:47.730 11934 11934 D BreventServer: Force stop com.google.android.apps.plus(noRecent)
08-23 11:51:47.731 11934 11934 D BreventServer: standby com.google.android.apps.plus
08-23 11:51:47.740 11934 11934 D BreventServer: Force stop com.google.android.apps.photos(noRecent)
08-23 11:51:47.741 11934 11934 D BreventServer: standby com.google.android.apps.photos
08-23 11:51:47.742 11934 11934 D BreventServer: check again in 3600s
08-23 11:51:47.743 11934 11934 D BreventServer: check and brevent, took 5359ms
08-23 11:51:47.771 11934 11934 I BreventServer: notification_cancel_all events: 14
08-23 11:51:47.771 11934 11934 D BreventServer: get service: batterystats
08-23 11:51:47.816 11934 11934 I BreventServer: charging: false
08-23 11:51:47.816 11934 11934 I BreventServer: support standby: true
08-23 11:51:47.816 11934 11934 I BreventServer: support stopped: true
08-23 11:51:47.816 11934 11934 I BreventServer: support upgrade: true
08-23 11:51:47.997 11934 11934 I BreventServer: Brevent Server 2.1.5a started
08-23 11:51:47.998 11934 11934 D BreventServer: get service: appops
08-23 11:51:48.002 11934 11934 D BreventServer: set appops, package: me.piebridge.brevent, package uid: 10049, code: 43, mode: 0
08-23 11:51:48.002 11934 11934 I BreventServer: checking port
08-23 11:51:48.011 11934 11934 I BreventServer: checked port
08-23 11:51:51.598 11934 11934 I BreventServer: received first event
08-23 11:51:59.798 11934 11934 D BreventServer: update current to com.teslacoilsw.launcher
08-23 11:51:59.798 11934 11934 D BreventServer: previous: null, packageName: com.teslacoilsw.launcher
08-23 11:52:02.799 11934 11934 D BreventServer: check and brevent
08-23 11:52:05.442 11934 11962 D BreventServer: get service: deviceidle
08-23 11:52:05.448 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:07.803 11934 11934 W BreventServer: dump notification [] timeout
08-23 11:52:08.004 11934 11934 D BreventServer: standby com.github.shadowsocks
08-23 11:52:08.010 11934 11934 D BreventServer: standby com.google.android.apps.docs.editors.sheets
08-23 11:52:08.014 11934 11934 D BreventServer: Force stop com.google.android.dialer(previous running)
08-23 11:52:08.017 11934 11934 D BreventServer: standby com.google.android.apps.plus
08-23 11:52:08.022 11934 11934 D BreventServer: standby com.google.android.apps.photos
08-23 11:52:08.022 11934 11934 D BreventServer: check again in 3600s
08-23 11:52:08.022 11934 11934 D BreventServer: check and brevent, took 5220ms
08-23 11:52:08.023 11934 11934 D BreventServer: update current to me.piebridge.brevent
08-23 11:52:13.043 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:13.093 11934 11962 D BreventServer: get service: lock_settings
08-23 11:52:13.112 11934 11962 W BreventServer: sent 10 to 11920
08-23 11:52:13.112 11920 11920 D BreventLoader: received signal: 10, ppid: 1
08-23 11:52:13.131 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:13.212 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:18.229 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:18.270 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:19.177 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:24.220 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:24.266 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:25.195 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:30.215 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:30.250 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:31.215 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:36.229 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:36.282 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:37.608 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:42.629 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:42.962 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:43.258 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:48.276 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:48.309 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:49.272 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:52:54.465 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:52:54.738 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:52:55.795 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]
08-23 11:53:00.855 11934 11962 W BreventServer: dump notification [] timeout
08-23 11:53:01.166 11934 11962 W BreventServer: cannot handle: Broken pipe
08-23 11:53:01.780 11934 11962 I BreventServer: make brevent whitelist, args: [whitelist, +me.piebridge.brevent]

截图：
![default](https://user-images.githubusercontent.com/11817602/29598301-a3835888-87fa-11e7-9052-678559dc2fb5.png)
![1](https://user-images.githubusercontent.com/11817602/29598304-a3a60ca2-87fa-11e7-9200-fccf0a86e410.png)
![2](https://user-images.githubusercontent.com/11817602/29598303-a39bcdb4-87fa-11e7-8d8c-858bdbcaf844.png)
![3](https://user-images.githubusercontent.com/11817602/29598302-a394cde8-87fa-11e7-99f9-43df88bbc27a.png)
![4](https://user-images.githubusercontent.com/11817602/29598305-a3a8e3be-87fa-11e7-9832-ca50c4859b92.png)
![5](https://user-images.githubusercontent.com/11817602/29598306-a3aadbf6-87fa-11e7-8901-49d11a798980.png)
![default](https://user-images.githubusercontent.com/11817602/29598307-a3b0601c-87fa-11e7-8a14-2157bc10fe83.png)

**Comment by AdrianStone0405** [comment]
2.1.4上也出现该问题，但偶尔开启成功，2.1.5a下完全无法启动了，更新来源：google play

**Comment by AdrianStone0405** [comment]
重新下载安装后，勉强可以开起来，但反应很慢，而且adb启动时第二行依旧报timeout

**Comment by AdrianStone0405** [comment]
因为要玩游戏 关闭了USB调试模式 现在又起不来了

**Comment by liudongmiao** [comment]
>  08-23 11:53:00.855 11934 11962 W BreventServer: dump notification [] timeout

黑域不会去兼容你的机器。你可使用 2.1.3 之前版本，如 2.1.2，然后关闭检查通知。

**Comment by AdrianStone0405** [comment]
@liudongmiao 了解。求问，哪可以获取老版本的应用呢？您的个人站点吗？我记得酷安和google play是无法找寻老版本应用应用的。

**Comment by AdrianStone0405** [comment]
已在apkpure上找寻，谢谢。

**Comment by Han9402** [comment]
奇怪 apkpure上的均报错 INSTALL_FAILED_VERSION_DOWNGRADE

**Comment by vvb2060** [comment]
你现在是在降级安装，先卸载高版本的……

**Comment by AdrianStone0405** [comment]
@vvb2060 发现了 因为手机直接开了个访客账户 所以初步卸载只卸载了本地账户 没卸载那个未启动账户 已经成功安装4.1.5

**Comment by AdrianStone0405** [comment]
2.1.5 sorry

**Comment by AdrianStone0405** [comment]
我还是听柳大的话吧 唉
