### ISSUE TITLE
why discontinue 5.x versions?

### ISSUE THREAD

**Issue by Dhionata** [brevent/Brevent#520]
I use the application on my E700m and this one is in version 5.1.1, so discontinue it there? Do you have any practical needs?

**Comment by liudongmiao** [comment]
There is no support for 5.X - 6.X, as google don't offer any security update for them.

And, I have no devices running on 5.X - 6.X.

**Comment by Dhionata** [comment]
I did not understand what relationship Google updates for these versions of Android with the app, if it exists. I, as I said, have 5.1.1 device and the application works well, at least before the support of this version in the last beta, I hope you think well and can keep supporting these versions of Android, or that at least someone does, I love the application And I think that's it ..

**Comment by liudongmiao** [comment]
please feedback only for stable, or try latest beta.
