### ISSUE TITLE
黑域建议

### ISSUE THREAD

**Issue by xiaoyou250** [brevent/Brevent#521]
能加快获取应用信息吗？magisk root授权好慢。以及希望增加游戏模式

**Comment by liudongmiao** [comment]
1. 获取应用信息，一般来说很快，首次进入会缓存一些东西，会慢一些。

2. root 与黑阈无关。

3. 请问游戏模式是啥？想要什么样的功能？

之前想了下，大约是以下几种：

- 进入全屏以后，强行停止其他所有应用
- 不展示中低优先级通知，甚至直接进入勿扰模式
