### ISSUE TITLE
发现一个关于返回键关闭应用的问题

### ISSUE THREAD

**Issue by lcckis** [brevent/Brevent#524]
如果按返回键关闭应用回到桌面是可以正常待机的，但是如果用其它应用打开的应用，按返回键关闭了当前应用后，直接返回另一个应用（比如在黑阈中应用商店中直接打开某个应用，关闭的时候按返回键后，返回黑阈或者是商店），关闭的应用是不会进入待机状态而是回一直保持运行状态。  希望能修复？

**Comment by liudongmiao** [comment]
如果不是细节控，建议直接忽视这个问题。

非正常返回，有三个变种：
1. 直接打开桌面，完全不顾 Android 生命周期
最新测试版引入其他日志，可以识别。

2. 直接打开启动器，完全不顾 Android 生命周期
最新测试版引入其他日志，可以识别。

前两个基本类似，如微博，京东（早期，目前没测试）。
黑阈虽然会调用待机，但是系统对于待机有最小时间限定，不一定能处理。
手势应用的加入，可能会产生如 1 或 2 的效果。

3. 自己移到后台
属于 Android 官方标准 API，兼顾 Android 生命周期。
类似应用如 微信，Chrome 等。
虽然可以识别，但黑阈不打算处理。
