### ISSUE TITLE
最新版3.6.5.10发现的bug

### ISSUE THREAD

**Issue by DoveBoy** [brevent/Brevent#525]
最新版发现一个bug，如果给app设置激进模式，每次打开这个app会闪退一下，再次打开才行，如果取消额外设置就没有这个问题了，之前的版本没有这个bug，希望能修复一下

**Comment by liudongmiao** [comment]
激进模式，基本不会处理。也不建议使用。

后期可能直接移除这个功能，改用 停用。

**Comment by liudongmiao** [comment]
我本地，高德地图，大众点评 等都无此问题。

不建议使用这个功能，可以采用 临时启用 快捷方式代替。

**Comment by DoveBoy** [comment]
酷安，京东，一加商店，ssrr问题突出

**Comment by liudongmiao** [comment]
不对旧版提供支持，最新 beta 3.6.8.X 应该有所改善。

目前还有一个没有解决，就是

如果打开 A 应用时，A 应用强行打开 B, C, D 等一系统激进式应用，同时 A 对 B, C, D 等形成强依赖。
