### ISSUE TITLE
黑域划卡非正常工作

### ISSUE THREAD

**Issue by MisakaSakura** [brevent/Brevent#528]
最近更新的几个版本，当应用达到后台应用超时后，从概览屏幕划掉卡片，应用仍然驻留后台，且貌似是按照不再活跃时间被黑域，出现问题应用崩坏3，闲鱼（play版），其他暂时没有相关活动。 GitHub不会发日志，稍后发邮件吧。

**Comment by Jack-ban** [comment]
你好，我也有问题提交。但是日志毕竟太隐私了。能告诉我作者的邮箱吗？

**Comment by MisakaSakura** [comment]
@Jack-ban 黑域里“反馈”有邮箱选项

**Comment by liudongmiao** [comment]
检查过一个用户的日志，这里摘抄如下。

如果你在 非桌面 划掉应用，并且从来不回到桌面。
黑阈暂时不处理这个应用。

这个是为了优化另外一个场景，从应用，打开另外一个应用分享，然后回到上一个应用，和你划掉并无本质区别。
在分享的场景中，这个应用留到下一次检查比较好。

在极端使用场景可能出现不黑阈（但长期肯定是会被处理的），与尽量正常使用相比之下，黑阈选择后者。

**Comment by MisakaSakura** [comment]
@liudongmiao 下一次检查的应用，是指分享到的应用还是原应用？

**Comment by liudongmiao** [comment]
https://jianyv.com/br/alpha/ 可以看下这个版本。

黑阈会不时检查，这次在应用结束之后，加入一次检查。
同时，保证其至少有 30 秒的时间。

打开最近列表划掉任何一个应用，则不会有这个等待时间。

**Comment by MisakaSakura** [comment]
@liudongmiao 好的

**Comment by liudongmiao** [comment]
已发 beta 版。

**Comment by liudongmiao** [comment]
已更新 beta 版。

修复在 sony android 9 上最近列表问题。
主要是 android 9 以后，可以指定最近列表应用。
sony 上配置的与实际的不一样，换了个方式获取最近列表应用。

**Comment by liudongmiao** [comment]
@MisakaSakura 测试了么，怎么样？

**Comment by MisakaSakura** [comment]
@liudongmiao 抱歉不常上GitHub看到晚了，已经测试，现在完美触发划卡停止了，谢谢

**Comment by liudongmiao** [comment]
好的，谢谢。请发送邮件至 brevent@jianyu.io，赠送特别贡献兑换码，请说明是要 play 的还是微信的。
