### ISSUE TITLE
手机淘宝无法待机

### ISSUE THREAD

**Issue by rjyu** [brevent/Brevent#53]
黑域是1.2.7 play版，手机淘宝6.8.0.5 play版，手机是小米5，lineageOS 14.1-20170620

**Comment by rjyu** [comment]
每次打开黑域，淘宝的计时就从0开始，即使等到超时时间，也不会待机。

**Comment by vvb2060** [comment]
每次计时归零是非正常 back 所致。强行停止它，然后强行停止启动器。此外，不再使用的应用可以直接从最近任务列表划掉。
