### ISSUE TITLE
开机时会自动黑阈在外置储存卡的应用

### ISSUE THREAD

**Issue by cEvolve05** [brevent/Brevent#533]
**Android 9 , LineageOS 16**

在开机时会自动黑阈所有移动到外置储存卡的应用

**Comment by liudongmiao** [comment]
如果触发安装事件，有可能。但此问题不处理：
> android 很早就不再支持安装到外部存储，我本人也没办法测试

你可以自行解决：
1. 想办法不要让黑阈启动过早
2. 必要时关闭自动黑阈

当然，有一个可以绕过的办法。
对于安装到外置存储上的应用，不启用自动黑阈功能。

**Comment by cEvolve05** [comment]
谢谢你，我发现软重启也可以解决这个问题

**Comment by kunanaxp** [comment]
自动黑阈功能在哪？我是酷安下载并且已支付版本，没有找到这个选项

**Comment by liudongmiao** [comment]
3.6.10.1 之后，支持 “卸载但保留数据” 应用。

外置存储卡上的应用，在外置存储卡挂载之前，将会被当成 “卸载但保留数据”，请升级并测试兼容性。

此外，如果数据（模拟的 SD 卡）在外置存储卡上，将不支持直接启动，等待正常的开机广播。
