### ISSUE TITLE
asked to tap "adb" since network adb was enbaled

### ISSUE THREAD

**Issue by linzhichu** [brevent/Brevent#535]
turned on adb over tcp ip as in #452 . but now when I open brevent, there was a prompt asking me to tap "ADB". It reads as following:
```
Network ADB is turned on, please tap "ADB" to start brevent server
```

brevent 3.6.8.4 on Pixel

**Comment by liudongmiao** [comment]
Since Android 8.0+, Brevent Server would be terminated if usb mode is changed.

And when network debug is turned on, start network debug would <s>dismiss</s> hide any potential issues, and users cannot know it was terminated.

So, since Brevent 3.6.6, don't auto start with network adb.
