### ISSUE TITLE
黑阈服务开启失败

### ISSUE THREAD

**Issue by veganav** [brevent/Brevent#536]
rm: /data/local/tmp/app_process: Permission denied

ln: /data/local/tmp/app_process: File exists

WARNING: brevent on Android 5.X - 6.0 is deprecated!!!

checking for server...started, pid: 23314

checking for stable...quited

[command] pm path me.piebridge.brevent

package:/data/app/me.piebridge.brevent-1/base.apk

please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```

--- crash start ---

[command] logcat -b crash -t '04-13 00:13:33.000' -d

--- crash end ---

--- brevent start ---

[command] logcat -b main -t '04-13 00:13:33.000' -d -s BreventLoader BreventServer

I/BreventLoader(23269): pm path me.piebridge.brevent

I/BreventLoader(23269): line: package:/data/app/me.piebridge.brevent-1/base.apk

I/BreventLoader(23269): loader path: /data/app/me.piebridge.brevent-1/base.apk

I/BreventLoader(23314): start: 1555085613

I/BreventServer(23314): args: [10, me.piebridge.brevent, 1555085613]

I/BreventServer(23314): server log name: server.20190413.0013.23314.txt

I/BreventServer(23314): starting Brevent Server 3.6.8.4

I/BreventServer(23314): brevent version: 3.6.8.4

E/BreventLoader(23269): worker 23314 exited on signal 9

I/BreventLoader(23269): signal arrived, update: 0

I/BreventLoader(23262): worker 23269 exited with status 0

--- brevent end ---

```

</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

黑阈服务开启失败，请将日志与具体情况发至 https://github.com/brevent/Brevent/issues 来解决问题。

**Comment by veganav** [comment]
谁能帮助我？

**Comment by veganav** [comment]
正在初始化
rm: /data/local/tmp/app_process: Permission denied

ln: /data/local/tmp/app_process: File exists

WARNING: brevent on Android 5.X - 6.0 is deprecated!!!

checking for server..started, pid: 25795

checking for stable..quited



[command] pm path me.piebridge.brevent

package:/data/app/me.piebridge.brevent-1/base.apk

please report bug to https://github.com/brevent/Brevent/issues/new with logs below



<details><summary>Click to show logs</summary>



```

--- crash start ---

[command] logcat -b crash -t '04-13 09:46:24.000' -d

--- crash end ---

--- brevent start ---


[command] logcat -b main -t '04-13 09:46:24.000' -d -s BreventLoader BreventServer

I/BreventLoader(25777): pm path me.piebridge.brevent

I/BreventLoader(25777): line: package:/data/app/me.piebridge.brevent-1/base.apk

I/BreventLoader(25777): loader path: /data/app/me.piebridge.brevent-1/base.apk

I/BreventLoader(25795): start: 1555119984

I/BreventServer(25795): args: [10, me.piebridge.brevent, 1555119984]

I/BreventServer(25795): server log name: server.20190413.0946.25795.txt

I/BreventServer(25795): starting Brevent Server 3.6.8.4

I/BreventServer(25795): brevent version: 3.6.8.4

E/BreventLoader(25777): worker 25795 exited on signal 9

I/BreventLoader(25777): signal arrived, update: 0

I/BreventLoader(25771): worker 25777 exited with status 0

--- brevent end ---

```

</details><br/>



please report bug to https://github.com/brevent/Brevent/issues/new with logs above


执行完成,退出码:0

**Comment by liudongmiao** [comment]
你可能曾经以 root 方式运行过。以及，没有详细日志。

对于 5.0 - 6.0 设备，黑阈会逐步不支持。
一是很多功能无法支持，二是我自己也没有相应设备测试。

**Comment by veganav** [comment]
详细日志点击Click to show logs查看
