### ISSUE TITLE
动态gms功能异常

### ISSUE THREAD

**Issue by eric24lu** [brevent/Brevent#537]
自从3.6.6版本开始，启用动态gms，Google服务被停用后一段时间，再打开Google系的应用会无法正常拉起gms服务，导致例如Gmail，Digital Wellbeing等应用不能正常启动。
机型一加5T，系统版本安卓9。

**Comment by liudongmiao** [comment]
这个功能，建议直接使用 GMS 快捷方式。
使用 GMS 快捷方式之后，会保证会在打开应用之前启用 GMS。
但即使这样，也会存在时间差，应用不一定能支持。

**Comment by eric24lu** [comment]
可是旧版本例如3.6.4.2就没有这个问题，请问是为什么呢？

**Comment by liudongmiao** [comment]
在之前，启用 gms 一共有三个时机：

1. GMS 快捷方式
2. 启动 activity 进程
3. 显示当前 activity
4. 通知渠道，也就是提示“需要启用 gms”之类的通知

后来，放弃了 3。
就目前而言，推荐的方式依旧只有 1。
2 发生在进入 activity 之前，3 则发生在进入 activity 之后，再启用意义不大。
当然，也许有一定的意义，但我本人依旧觉得意义不大。
后续还会加入一个 START 的日志，在此之前启用。
但就目前而言，依旧建议的只是 1.

**Comment by liudongmiao** [comment]
https://jianyv.com/br/alpha/ 你可以试下这个版本。
针对主动打开的 gapps 应用，一共在 3 个位置加入了。
1. 首次启动 activity 进程
2. 每次进入 activity 界面
3. 启动 activity 进程之前

**Comment by eric24lu** [comment]
感谢！

**Comment by liudongmiao** [comment]
最新的 3.6.9.X 已经单独为 play 商店优化。
当发现展示 需要登录 时，会强行停止 play 商店，然后重新打开。

**Comment by eric24lu** [comment]
已更新，感谢作者的优化！
