### ISSUE TITLE
微件应用黑阈问题

### ISSUE THREAD

**Issue by WTF112211** [brevent/Brevent#538]
添加了微件的应用，比如网易云音乐，当我主动停止播放音乐，并从通知，多任务页面关掉时，能不能把它黑阈掉，不想让它在运行

**Comment by WTF112211** [comment]
并不是希望所有微件应用一直后台运行

**Comment by liudongmiao** [comment]
系统本来就会定期更新 微件，所以默认不处理微件。

点按 7 次支持状态，按需开启强迫症选项。

**Comment by WTF112211** [comment]
已开启强迫症选项，感谢
