### ISSUE TITLE
有没有一个典型的配置方式

### ISSUE THREAD

**Issue by rjyu** [brevent/Brevent#54]
曾经用惯iphone，没习惯清最近任务，现在用安卓也能理解最大化利用运存是提高应用响应的方式，那在安卓下结合黑域，是否已经能做到类似iphone那样使后台应用保持冻结状态，但也不会影响消息推送，不用清最近任务？有没有一种典型的配置方案供新手参考？谢谢～

**Comment by vvb2060** [comment]
当应用被待机后会断网，没有网络，基本不活跃，可以认为是冻结状态。
完全支持FCM的应用，只要开了允许同步，即使没有后台，也能接收消息。

你的要求不是配置黑域能解决的，而是看应用是否完全支持FCM。当选择一个应用后出现了FCM标识，允许同步后显示的是云朵图案即表示它能按你所期待的那样运作。

黑域的向导和设置里的说明已经展示了黑域的工作方式，你可以根据自己的需要调整设置，黑域会依据你离开应用的方式作出不同的处理。

**Comment by rjyu** [comment]
那没有FCM的应用，同步是什么意思呢？如果开了同步，待机后是不是也没有用了？

**Comment by liudongmiao** [comment]
同步方式有多种，包括但不限于以下方式：
- 基于 GMS 的 FCM
- 帐号同步
- 桌面小部件
- 其它善意或恶意的唤醒
  （说明下，有些系统，如魅族推送，状态栏你长按看到的是应用，但实际通知是“推送服务”）

说明一下，除了 FCM 里自带消息，不需要网络，待机能接收消息以外；其它类型的，待机状态均无法获得数据。也就是说，如果邮件基于帐号同步（基本上就是这样），但处于待机状态下（如有通知后，你打开会进入待机），是无法在待机状态下收到新信息的。

如果你非常依赖这个应用，则不建议黑域它；或者黑域以后，允许同步（并且考虑电池未优化）。允许同步的应用，只要在后台，都不会被强行停止。否则，不断启与停，只会更费电。

**Comment by liudongmiao** [comment]
但是，黑域有优化，待机之后，强行停止时，会取消待机状态。

如果某些系统，不支持设置停止状态，第三方应用无法支持 FCM 等基于广播的唤醒；如果被强行停止，则会取消待机状态，方便下次唤醒时可以访问网络，同时，保证至少运行 30 秒以接收信息。

允许同步需要单独设置，主要是因为黑域没法改动系统，只能允许全部广播（Xposed 或补丁版可以做到只允许 FCM 广播）。而一旦开启全部广播，系统会在多种状态下发送来触发唤醒。

**Comment by liudongmiao** [comment]
发现说了这么多，都没有回复 @rjyu 原始问题。对于新手，建议的配置方式如下：

0. 不要黑域系统应用，框架应用
1. 不要黑域你常用的应用，特别是 IM 应用；常用但并不依赖的，可以开启允许同步
2. 三星系统不要黑域三星 S 助手（没有人协助到底是什么原因，我一向反对针对某些应用优化）

虽然说不针对，但实际有针对以下应用优化：
- 黑域。废话，不优化都无法找到入口；以及卸载时，退出黑域。
- GMS。1.2.7 加入，不许黑域 GMS。
- 支付宝、微信、PayPal。这些有硬编码检查，判断是否支持捐赠。
   （接下来，会进一步判断签名。）
- 从黑域内点开支付宝，到转账页面时，会统计转账记录。后期可能对实验性功能收费。

**Comment by rjyu** [comment]
感谢@liudongmiao 解释得这么详细，回头再慢慢细读。我想这条issue会有很多新手受益，赞！

**Comment by liudongmiao** [comment]
@rjyu 为了给小白一个不崩溃手机的机会，下个版本起，可以直接黑域所有应用。
当然，非常重要的，直接标记成了重要（感叹号）；不建议黑域的，标记成心形（目前有电池未优化及 GMS）。
