### ISSUE TITLE
申请退款

### ISSUE THREAD

**Issue by lawlvxing** [brevent/Brevent#54]
柳大您好，我是一个坚定的正版和您的支持者，在所谓的社区版和酷域充斥评论时，我直接选择了正版。
但是在我购买的第二天您推出了返现活动，作为您的官方活动，我参与应该也不算是贪图小便宜吧。
所以在这里我请求退款，在28日再次购买。或者是，等到O系统推出时我会再次购买。谢谢您！

~个人信息~

**Comment by vvb2060** [comment]
请使用黑域应用内的反馈功能，在邮件中说明并添加支付截图。
#51 不要多开

**Comment by lawlvxing** [comment]
怎么发邮件啊？
