### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by qq171161636** [brevent/Brevent#547]
这是错误日志，用adb启动的，权限也给了。
checking for server..fail
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> /system/bin/logcat -b crash -t '04-22 17:32:42.000' -d
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '04-22 17:32:42.000' -d -s BreventLoader Bre
ntServer
04-22 17:32:42.680 13019 13019 D BreventLoader: loader path: /data/app/me.pieb
dge.brevent-uOtr9YjhSglQpB46GJl8UA==/base.apk
04-22 17:32:43.056 13023 13023 W BreventServer: Can't find ActivityManager.Sta
Id.FREEFORM_WORKSPACE_STACK_ID
04-22 17:32:43.058 13023 13023 D BreventServer: get service: package
04-22 17:32:43.059 13023 13023 D BreventServer: args: [10]
04-22 17:32:43.059 13023 13023 I BreventServer: signal: 10
04-22 17:32:43.067 13023 13023 I BreventServer: starting Brevent Server 2.1.2
04-22 17:32:43.068 13023 13023 W BreventServer: Can't find ActivityManager.REC
T_IGNORE_HOME_STACK_TASKS nor ActivityManager.RECENT_IGNORE_HOME_AND_RECENTS_S
CK_TASKS
04-22 17:32:43.068 13023 13023 W BreventServer: Can't find ActivityManager.REC
T_INCLUDE_PROFILES
04-22 17:32:43.068 13023 13023 W BreventServer: Can't find ActivityManager.REC
T_INGORE_DOCKED_STACK_TOP_TASK
04-22 17:32:43.068 13023 13023 W BreventServer: Can't find ActivityManager.REC
T_INGORE_PINNED_STACK_TASKS
04-22 17:32:43.070 13023 13023 W BreventServer: Can't find ActivityManager.Sta
Id.FREEFORM_WORKSPACE_STACK_ID
04-22 17:32:43.071 13023 13023 D BreventServer: get service: package
04-22 17:32:43.071 13023 13023 W BreventServer: version unmatched, running: 2.
2, installed: brevent
04-22 17:32:43.072 13023 13023 I BreventServer: brevent user: 0, uid: 2000
04-22 17:32:43.073 13023 13023 I BreventServer: brevent data directory: /data/
er_de/0/com.android.shell
04-22 17:32:43.086 13023 13023 I BreventServer: loading brevent list
04-22 17:32:43.086 13023 13023 I BreventServer: loading brevent conf
04-22 17:32:43.089 13023 13023 D BreventServer: get service: appwidget
04-22 17:32:43.093 13023 13023 D BreventServer: get service: usagestats
04-22 17:32:43.301 13023 13034 I BreventServer: Brevent Event, now: 1555925563
04-22 17:32:43.301 13023 13023 D BreventServer: check and brevent
04-22 17:32:43.302 13023 13023 D BreventServer: get service: notification
04-22 17:32:43.332 13023 13034 I BreventServer: system_server: 927, now: 15559
563
04-22 17:32:43.377 13023 13023 D BreventServer: get service: activity
04-22 17:32:43.385 13023 13023 D BreventServer: get service: alarm
04-22 17:32:43.387 13023 13023 D BreventServer: get service: wallpaper
04-22 17:32:43.392 13023 13023 E BreventServer: Can't get running app processe
04-22 17:32:43.392 13023 13023 E BreventServer: java.lang.NullPointerException
Attempt to read from field 'android.content.pm.ApplicationInfo com.android.ser
r.am.ProcessRecord.info' on a null object reference
04-22 17:32:43.392 13023 13023 E BreventServer:         at android.os.Parcel.c
ateException(Parcel.java:1956)
04-22 17:32:43.392 13023 13023 E BreventServer:         at android.os.Parcel.r
dException(Parcel.java:1918)
04-22 17:32:43.392 13023 13023 E BreventServer:         at android.os.Parcel.r
dException(Parcel.java:1868)
04-22 17:32:43.392 13023 13023 E BreventServer:         at android.app.IActivi
Manager$Stub$Proxy.getRunningAppProcesses(IActivityManager.java:5315)
04-22 17:32:43.392 13023 13023 E BreventServer:         at me.piebridge.breven
server.e.b(HideApi.java:112)
04-22 17:32:43.392 13023 13023 E BreventServer:         at me.piebridge.breven
server.BreventServer.a(BreventServer.java:1993)
04-22 17:32:43.392 13023 13023 E BreventServer:         at me.piebridge.breven
server.BreventServer.j(BreventServer.java:789)
04-22 17:32:43.392 13023 13023 E BreventServer:         at me.piebridge.breven
server.BreventServer.h(BreventServer.java:2101)
04-22 17:32:43.392 13023 13023 E BreventServer:         at me.piebridge.breven
server.BreventServer.a(BreventServer.java:2218)
04-22 17:32:43.392 13023 13023 E BreventServer:         at java.lang.reflect.M
hod.invoke(Native Method)
04-22 17:32:43.392 13023 13023 E BreventServer:         at me.piebridge.breven
server.BreventServer.main(BreventServer.java:2316)
04-22 17:32:43.392 13023 13023 E BreventServer:         at com.android.interna
os.RuntimeInit.nativeFinishInit(Native Method)
04-22 17:32:43.392 13023 13023 E BreventServer:         at com.android.interna
os.RuntimeInit.main(RuntimeInit.java:384)
04-22 17:32:43.392 13023 13023 E BreventServer: Caused by: android.os.RemoteEx
ption: Remote stack trace:
04-22 17:32:43.392 13023 13023 E BreventServer:         at com.android.server.
.ActivityManagerService.getRunningAppProcesses(ActivityManagerService.java:178
)
04-22 17:32:43.392 13023 13023 E BreventServer:         at android.app.IActivi
Manager$Stub.onTransact(IActivityManager.java:1011)
04-22 17:32:43.392 13023 13023 E BreventServer:         at com.android.server.
.ActivityManagerService.onTransact(ActivityManagerService.java:3820)
04-22 17:32:43.392 13023 13023 E BreventServer:         at android.os.Binder.e
cTransact(Binder.java:752)
04-22 17:32:43.392 13023 13023 E BreventServer:
04-22 17:32:43.403 13019 13019 E BreventLoader: worker 13023 exited with statu
1
04-22 17:32:43.403 13019 13019 D BreventLoader: signal arrived, update: 0
04-22 17:32:43.404 13014 13014 D BreventLoader: worker 13019 exited with statu
0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by vvb2060** [comment]
更新应用
