### ISSUE TITLE
ROOT 模式无法获取应用列表

### ISSUE THREAD

**Issue by bcx123** [brevent/Brevent#55]
$ su
$ sh "/storage/emulated/0/Android/data/me.piebridge.brevent/brevent.sh"
WARNING: run as root is experimental!!!
checking............cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '06-23 06:22:26.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-23 06:22:26.000' -d -s BreventLoader BreventServer
06-23 06:22:26.845 20688 20688 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
06-23 06:22:27.193 20705 20705 D BreventServer: get service: package
06-23 06:22:27.219 20705 20705 I BreventServer: starting Brevent Server 1.2.7
06-23 06:22:27.225 20705 20705 D BreventServer: get service: package
06-23 06:22:27.227 20705 20705 I BreventServer: brevent user: 0, uid: 0
06-23 06:22:27.228 20705 20705 I BreventServer: brevent data directory: /data/user/0/com.android.shell
06-23 06:22:27.251 20705 20705 E BreventServer: Can't getInstalledPackages
06-23 06:22:27.276 20688 20688 E BreventLoader: worker 20705 exited with status 1
06-23 06:22:27.276 20688 20688 D BreventLoader: signal arrived, update: 0
06-23 06:22:27.277 20681 20681 D BreventLoader: worker 20688 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by vvb2060** [comment]
不能获取安装软件的列表

如果SU后执行以下指令 `pm list packages --user 0` 不能返回应用列表，找你的 root 提供商，解决原生指令无法使用问题。

PS：可以尝试关闭SELinux：`setenforce 0` 。如果依然不行那是SU的实现有问题，不能靠关闭SELinux解决。

**Comment by liudongmiao** [comment]
#39 一样的问题，目前从已有信息来看，出现在乐视手机上。

可以约个周末的时候，联调下。这个是获取系统全部的安装应用列表，你看下手机里是否有这样的开关，禁止获取安装列表之类。

虽然，对于 root 的系统来说，也许有其它方式获取系统安装的应用列表，你可以尝试使用（root 情况下）:

```
dumpsys package packages
```

如果能返回信息，我可能考虑做个兼容；如果不行，基本就不会进一步处理了。

**Comment by vvb2060** [comment]
@liudongmiao 一个样本，酷派手机 http://www.coolapk.com/feed/3532842 
看来`dumpsys package packages`可用

**Comment by liudongmiao** [comment]
@vvb2060 你是开发者么？

要不，我把 brevent-server 权限也给你吧。
以防哪天，我累了，弃坑....

**Comment by liudongmiao** [comment]
@vvb2060 此外，好像我机器上，还有之前的黑域补丁版源码。
但我自己都不知道是不是当时最新的。

目前看来，你有意入这个坑。
说实话吧，目前新版黑域接入补丁版，加两到三个功能，还是很容易的，只是我不用:
- 开机自启
- 事先阻断。事先阻断，除了效果外，还能更好的处理 内容提供器 这种事后强行停止会导致崩溃的情况
- 脏方法处理微信也成

并且，新版黑域天然支持自我升级，主要是状态都直接从系统获取，不像之前的阻止运行，状态全都记在自己进程空间，所以无法热更新。

**Comment by bcx123** [comment]
runtime permissions:
        android.permission.READ_SMS: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.READ_CALENDAR: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.ACCESS_FINE_LOCATION: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.READ_EXTERNAL_STORAGE: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.ACCESS_COARSE_LOCATION: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.READ_PHONE_STATE: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.SEND_SMS: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.CALL_PHONE: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.CAMERA: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.WRITE_CALENDAR: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.GET_ACCOUNTS: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.WRITE_EXTERNAL_STORAGE: granted=true, flags=[ GRANTED_BY_DEFAULT ]
        android.permission.RECORD_AUDIO: granted=true, flags=[ GRANTED_BY_DEFAULT ]
  Package [com.android.providers.downloads.ui] (b8a3c40):
    userId=10006
    sharedUser=SharedUserSetting{dd25d2d android.media/10006}
    pkg=Package{7d51225 com.android.providers.downloads.ui}
    codePath=/system/app/DownloadProviderUi
    resourcePath=/system/app/DownloadProviderUi
    legacyNativeLibraryDir=/system/app/DownloadProviderUi/lib
    primaryCpuAbi=null
    secondaryCpuAbi=null
    versionCode=23 targetSdk=23
    versionName=6.0.1
    splits=[base]
    applicationInfo=ApplicationInfo{ede2ffa com.android.providers.downloads.ui}
    flags=[ SYSTEM HAS_CODE ALLOW_CLEAR_USER_DATA ALLOW_BACKUP ]
    pkgFlagsEx=[ ]
    dataDir=/data/user/0/com.android.providers.downloads.ui
    supportsScreens=[small, medium, large, xlarge, resizeable, anyDensity]
    timeStamp=2017-05-09 19:42:22
    firstInstallTime=2017-03-11 11:07:27
    lastUpdateTime=2017-05-09 19:42:22
    signatures=PackageSignatures{c94c9ab [b4c72ae]}
    installPermissionsFixed=true installStatus=1
    pkgFlags=[ SYSTEM HAS_CODE ALLOW_CLEAR_USER_DATA ALLOW_BACKUP ]


大佬。你那个代码我输入了有回复（返回代码总共41万字符发不出去，所以我就截了开头一小部分）

**Comment by vvb2060** [comment]
@liudongmiao 定位是客服😅对此感兴趣。以后可能会吧，现在不是开发者。

**Comment by liudongmiao** [comment]
@bcx123 我更换了 API 获取应用列表，你看下这个版本：https://piebridge.me/br/next/

另外，adb 模式正常么？对于 root，我原则上不提供任何支持，要支持的话，请电话上安装 teamviewer，然后发给我 id 与密码。

**Comment by bcx123** [comment]
adb电脑上是正常的。手机的话没法用。你发的这个版本，返回信息如下

u0_a188@le_x2:/ $ su
dcard/Android/data/me.piebridge.brevent/brevent.sh             <
WARNING: run as root is experimental!!!
checking...brevent_server started, pid: 4786
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '06-24 08:08:09.000' -d
06-24 08:08:10.991  4786  4786 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
06-24 08:08:10.991  4786  4786 E AndroidRuntime: java.lang.reflect.InvocationTargetException
06-24 08:08:10.991  4786  4786 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-24 08:08:10.991  4786  4786 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2013)06-24 08:08:10.991  4786  4786 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-24 08:08:10.991  4786  4786 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
06-24 08:08:10.991  4786  4786 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getWallpaperInfo(I)Landroid/app/WallpaperInfo; in class Landroid/app/IWallpaperManager; or its super classes (declaration of 'android.app.IWallpaperManager' appears in /system/framework/framework.jar)
06-24 08:08:10.991  4786  4786 E AndroidRuntime:        at me.piebridge.brevent.server.e.h(HideApi.java:804)
06-24 08:08:10.991  4786  4786 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.g(BreventServer.java:648)
06-24 08:08:10.991  4786  4786 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1934)
06-24 08:08:10.991  4786  4786 E AndroidRuntime:        ... 4 more
06-24 08:08:10.992  4786  4786 E AndroidRuntime: Error reporting crash
06-24 08:08:10.992  4786  4786 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-24 08:08:10.992  4786  4786 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
06-24 08:08:10.992  4786  4786 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
06-24 08:08:10.992  4786  4786 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4534)
06-24 08:08:10.992  4786  4786 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
06-24 08:08:10.992  4786  4786 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
06-24 08:08:10.992  4786  4786 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-24 08:08:09.000' -d -s BreventLoader BreventServer
06-24 08:08:10.134  4776  4776 D BreventLoader: loader path: /data/app/me.piebridge.brevent-3/base.apk
06-24 08:08:10.469  4786  4786 D BreventServer: get service: package
06-24 08:08:10.497  4786  4786 I BreventServer: starting Brevent Server 1.2.7-6-gaebea7a
06-24 08:08:10.514  4786  4786 D BreventServer: get service: package
06-24 08:08:10.517  4786  4786 I BreventServer: brevent user: 0, uid: 0
06-24 08:08:10.518  4786  4786 I BreventServer: brevent data directory: /data/user/0/com.android.shell
06-24 08:08:10.543  4786  4786 I BreventServer: loading brevent list
06-24 08:08:10.547  4786  4786 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 39
06-24 08:08:10.748  4786  4786 I BreventServer: loading brevent conf
06-24 08:08:10.753  4786  4786 D BreventServer: get service: appwidget
06-24 08:08:10.758  4786  4786 D BreventServer: get service: usagestats
06-24 08:08:10.919  4786  4786 D BreventServer: get service: batterystats
06-24 08:08:10.920  4786  4786 I BreventServer: charging: false
06-24 08:08:10.920  4786  4786 D BreventServer: check and brevent06-24 08:08:10.921  4786  4786 D BreventServer: get service: notification
06-24 08:08:10.965  4786  4786 D BreventServer: get service: activity
06-24 08:08:10.987  4786  4786 D BreventServer: get service: alarm
06-24 08:08:10.988  4786  4786 D BreventServer: get service: wallpaper
06-24 08:08:11.005  4776  4776 E BreventLoader: worker 4786 exited on signal 9
06-24 08:08:11.005  4776  4776 D BreventLoader: signal arrived, update: 0
06-24 08:08:11.006  4772  4772 D BreventLoader: worker 4776 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above
1|root@le_x2:/ #

**Comment by bcx123** [comment]
id 541992943
密 123456.

**Comment by bcx123** [comment]
额。忘记说了。晚上八点以后我肯定在

**Comment by liudongmiao** [comment]
@bcx123 再试试最新版。

**Comment by liudongmiao** [comment]
@bcx123 id 与 密码发在这非常危险....

**Comment by liudongmiao** [comment]
@bcx123 出现这个异常，表明已经通过了应用列表那步，不出意外就成功了。
这个异常，是新增的获取壁纸 API，我没有做好兼容性。

**Comment by liudongmiao** [comment]
据 #39 中反馈，已经修复。

**Comment by bcx123** [comment]
已解决，谢了大佬
