### ISSUE TITLE
黑阈例外退款声明

### ISSUE THREAD

**Issue by zhongqiang99** [brevent/Brevent#550]
本人于 2019 年 2 月 6 日在黑阈内支付 34 元，不符合黑阈退款政策 https://www.jianshu.com/p/87aa6245d814 ，要求开发者例外退款。

**Comment by zhongqiang99** [comment]
> 本人于 2019 年 2 月 6 日在黑阈内支付 34 元，不符合黑阈退款政策 https://www.jianshu.com/p/87aa6245d814 ，要求开发者例外退款。

**Comment by liudongmiao** [comment]
已退
