### ISSUE TITLE
permissions denied

### ISSUE THREAD

**Issue by houch80** [brevent/Brevent#56]
C:\platform-tools>adb devices
List of devices attached
0715f7f2cf4e1202        device

C:\platform-tools>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
sh: /data/data/me.piebridge.brevent/brevent.sh: Permission denied

C:\platform-tools>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
sh: /data/data/me.piebridge.brevent/brevent.sh: Permission denied

**Comment by KunsLand** [comment]
Use USB to __'Transfer files'__ instead of __'Charge the device'__.

**Comment by vvb2060** [comment]
When you  see "Please start Brevent server", you can execute the command, don't early.

**Comment by puXiaoyi** [comment]
the same problem。。。how can i do ?

**Comment by ribilynn** [comment]
Same problem with macOS and Pixel 2 (Android 8.0.0,  not root). 
Having 'Transfer files' turned on is also useless.

**Comment by hairuo** [comment]
Update: 新版在打开Brevent的Guide->Welcome->Permissions->Security->Enjoy下面有个Launch Brevent，运行以后就可以adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh而不用担心Permission denied了。

**Comment by victoryeeuk** [comment]
no I don't have a pc
