### ISSUE TITLE
。。。

### ISSUE THREAD

**Issue by nekoinker** [brevent/Brevent#561]
--- crash start ---
[command] logcat -b crash -t '05-14 08:15:41.000' -d
05-14 08:15:42.033  8757  8757 E AndroidRuntime: FATAL EXCEPTION: main
05-14 08:15:42.033  8757  8757 E AndroidRuntime: PID: 8757
05-14 08:15:42.033  8757  8757 E AndroidRuntime: java.lang.reflect.InvocationTargetException
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2476)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
05-14 08:15:42.033  8757  8757 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No static method collectCertificates(Landroid/content/pm/PackageParser$Package;I)V in class Landroid/content/pm/PackageParser; or its super classes (declaration of 'android.content.pm.PackageParser' appears in /system/framework/framework.jar)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at me.piebridge.brevent.protocol.BreventProtocol.getSignatures(BreventProtocol.java:235)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at me.piebridge.brevent.protocol.BreventProtocol.getFingerprint(BreventProtocol.java:223)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.q(BreventServer.java:2480)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2374)
05-14 08:15:42.033  8757  8757 E AndroidRuntime:        ... 4 more
05-14 08:15:42.036  8757  8757 E AndroidRuntime: Error reporting crash
05-14 08:15:42.036  8757  8757 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:1131)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:125)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:253)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:124)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4135)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4132)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:4128)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:217)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
05-14 08:15:42.036  8757  8757 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '05-14 08:15:41.000' -d -s BreventLoader BreventServer
05-14 08:15:41.494  8753  8753 D BreventLoader: line: package:/data/app/me.piebridge.brevent-hv6fTLEU4p7jiCR97JHj4A==/base.apk
05-14 08:15:41.494  8753  8753 D BreventLoader:
05-14 08:15:41.499  8753  8753 D BreventLoader: loader path: /data/app/me.piebridge.brevent-hv6fTLEU4p7jiCR97JHj4A==/base.apk
05-14 08:15:41.983  8757  8757 W BreventServer: Can't find ActivityManager.StackId.FREEFORM_WORKSPACE_STACK_ID
05-14 08:15:42.006  8757  8757 D BreventServer: get service: package
05-14 08:15:42.008  8757  8757 D BreventServer: args: [10]
05-14 08:15:42.008  8757  8757 I BreventServer: signal: 10
05-14 08:15:42.078  8753  8753 E BreventLoader: worker 8757 exited on signal 9
05-14 08:15:42.078  8753  8753 D BreventLoader: signal arrived, update: 0
05-14 08:15:42.079  8749  8749 D BreventLoader: worker 8753 exited with status 0
--- brevent end ---

**Comment by nekoinker** [comment]
我系统框架里缺了安装黑阈所必须的方法？

**Comment by liudongmiao** [comment]
你为何要使用一个古老的版本呢？
