### ISSUE TITLE
没有支付时，开机后无法自启动服务

### ISSUE THREAD

**Issue by MoGuangYu** [brevent/Brevent#564]
需要自己进去一遍，再允许root一次，以前不会这样的，请问这是怎么回事

**Comment by vvb2060** [comment]
如果无法开机自启，请自查任何系统限制。

**Comment by MoGuangYu** [comment]
> 如果无法开机自启，请自查任何系统限制。

没有任何限制，也没对应用进行电池优化还是这样，Android P
![Screenshot_20190523-162855](https://user-images.githubusercontent.com/49760068/58238224-7214ee80-7d79-11e9-8a48-55202c5a2c56.png)
 pie

**Comment by vvb2060** [comment]
黑阈-反馈-日志，将压缩包拖拽到GitHub输入框中上传

**Comment by MoGuangYu** [comment]
> 黑阈 - 反馈 - 日志，将压缩包拖拽到GitHub的输入框中上传

ok
[logs-v3.6.10.7-20190523.1653.zip](https://github.com/brevent/Brevent/files/3211176/logs-v3.6.10.7-20190523.1653.zip)

**Comment by vvb2060** [comment]
黑阈应用没有接到任何开机广播

**Comment by MoGuangYu** [comment]
> 黑阈应用没有接到任何开机广播

那怎么回事，以前都会自启动服务

**Comment by liudongmiao** [comment]
https://www.jianshu.com/p/50dfccd675e2 自己对照吧。

**Comment by MoGuangYu** [comment]
> https://www.jianshu.com/p/50dfccd675e2自己对照吧。

并没有什么卵用，就是以前的版本就没事，

**Comment by vvb2060** [comment]
> 05-23 16:28:16.982  1259  1289 I ActivityManager: Start proc 2846:me.piebridge.brevent/u0a113 for broadcast me.piebridge.brevent/.ui.BreventReceiver

进程被启动但实际上没有工作，events缺少这个时间段的日志，无法确认实际情况

**Comment by MoGuangYu** [comment]
> > 05-23 16:28:16.982 1259 1289 I ActivityManager：启动proc 2846：me.piebridge.brevent / u0a113播放me.piebridge.brevent / .ui.BreventReceiver
> 
> 进程被启动但实际上没有工作，事件缺少这个时间段的日志，无法确认实际情况

请求解决方法，

**Comment by liudongmiao** [comment]
1. 你所发的日志，只有你启动后的日志，没有启动前的。

2. 你又不发日志，又不说实际情况，比如开机之后，到底有没有见到任何通知。

3. 黑阈不需要 root，我本人也没有 root 机器，使用 root 的人，都能使用。

这样吧，带订单号，发到 refund@jianyu.io， 附上这个 issue ，申请退款吧。

**Comment by vvb2060** [comment]
截图就是这个时间点的图，看样子是有通知的。
应该在 重启 出现通知后马上打开应用，收集日志。

**Comment by MoGuangYu** [comment]
> 1. 你所发的日志，只有你启动后的日志，没有启动前的。
> 2. 你又不发日志，又不说实际情况，比如开机之后，到底有没有见到任何通知。
> 3. 黑阈不需要root，我本人也没有root机器，使用root的人，都能使用。
> 
> 这样吧，带订单号，发到[refund@jianyu.io](mailto:refund@jianyu.io)，附上这个问题，申请退款吧。

我所发的日志是app里面抓的，启动前怎么抓？
--实际情况？ 开机就马上自启动了黑阀，就是截图里面的通知

**Comment by MoGuangYu** [comment]
> 截图就是这个时间点的图，看样子是有通知的。
> 应该在重启出现通知后马上打开应用，收集日志。

重启出现通知后马上进去抓日志吗？

**Comment by liudongmiao** [comment]
https://jianyu.io/br/alpha/ 这个 alpha，会把黑阈部分日志，写到文件，再提取应该会有。

自己对照那个你认为没有什么用的 https://www.jianshu.com/p/50dfccd675e2
认真看最后一句话。

**Comment by liudongmiao** [comment]
整个过程，其实你应该关心，到底有没有见到 “正在启动黑阈服务” 这个。

**Comment by MoGuangYu** [comment]
> 整个过程，其实你应该关心，到底有没有见到“正在启动黑阈服务”这个。

没有，一开机锁屏那里就直接显示了上面截图里面状态栏的那个通知

**Comment by MoGuangYu** [comment]
[logs-v3.6.10.8-2-gc42195cb-20190523.2242.zip](https://github.com/brevent/Brevent/files/3212750/logs-v3.6.10.8-2-gc42195cb-20190523.2242.zip)

**Comment by liudongmiao** [comment]
你检查你的 root 工具吧...

```
2019-05-23 22:39:05,823 [Brevent] INFO request status
2019-05-23 22:39:05,879 [main] INFO service.adb.tcp.port:
2019-05-23 22:39:05,904 [Brevent] INFO request status
2019-05-23 22:39:11,026 [Brevent] INFO retry request status
2019-05-23 22:39:11,034 [main] INFO service.adb.tcp.port:
2019-05-23 22:39:12,148 [main] INFO received: android.intent.action.BOOT_COMPLETED
2019-05-23 22:39:12,155 [main] INFO will startForegroundService
2019-05-23 22:39:12,161 [IntentService[JianyuIntentService]] INFO show notification
2019-05-23 22:39:12,176 [IntentService[JianyuIntentService]] INFO hide notification
2019-05-23 22:39:14,518 [main] INFO will startService
2019-05-23 22:39:14,530 [IntentService[JianyuIntentService]] INFO show notification
2019-05-23 22:39:14,533 [IntentService[JianyuIntentService]] INFO startBreventServer for action me.piebridge.brevent.intent.action.RUN_AS_ROOT
2019-05-23 22:39:14,537 [IntentService[JianyuIntentService]] INFO startBreventSync, action: me.piebridge.brevent.intent.action.RUN_AS_ROOT
2019-05-23 22:39:14,540 [IntentService[JianyuIntentService]] INFO service.adb.tcp.port:
2019-05-23 22:39:15,545 [IntentService[JianyuIntentService]] INFO service.adb.tcp.port: 3035
```

在直接启动过程中，没有成功开通 网络调试端口。
目前这个版本，没有记录 其它日志 。

**Comment by liudongmiao** [comment]
呃，好像我看错了。。黑阈没有到执行 su 这个过程。
但是，不知道到底是没有 su，还是没有支付。

https://jianyu.io/br/alpha/ 重新安装这个 alpha 吧。
会告诉你是哪种具体的原因。

**Comment by liudongmiao** [comment]
比如我这边

第一次，开机直接启动，外置存储不可用，不启动。
```
BreventUI: ignore start brevent on unavailable external storage
```

第二次，开机启动，没有 su，不启动。
```
BreventUI: no su, ignore startBreventServer
```

**Comment by MoGuangYu** [comment]
> 你检查你的 root 工具吧...
> 
> ```
> 2019-05-23 22:39:05,823 [Brevent] INFO request status
> 2019-05-23 22:39:05,879 [main] INFO service.adb.tcp.port:
> 2019-05-23 22:39:05,904 [Brevent] INFO request status
> 2019-05-23 22:39:11,026 [Brevent] INFO retry request status
> 2019-05-23 22:39:11,034 [main] INFO service.adb.tcp.port:
> 2019-05-23 22:39:12,148 [main] INFO received: android.intent.action.BOOT_COMPLETED
> 2019-05-23 22:39:12,155 [main] INFO will startForegroundService
> 2019-05-23 22:39:12,161 [IntentService[JianyuIntentService]] INFO show notification
> 2019-05-23 22:39:12,176 [IntentService[JianyuIntentService]] INFO hide notification
> 2019-05-23 22:39:14,518 [main] INFO will startService
> 2019-05-23 22:39:14,530 [IntentService[JianyuIntentService]] INFO show notification
> 2019-05-23 22:39:14,533 [IntentService[JianyuIntentService]] INFO startBreventServer for action me.piebridge.brevent.intent.action.RUN_AS_ROOT
> 2019-05-23 22:39:14,537 [IntentService[JianyuIntentService]] INFO startBreventSync, action: me.piebridge.brevent.intent.action.RUN_AS_ROOT
> 2019-05-23 22:39:14,540 [IntentService[JianyuIntentService]] INFO service.adb.tcp.port:
> 2019-05-23 22:39:15,545 [IntentService[JianyuIntentService]] INFO service.adb.tcp.port: 3035
> ```
> 
> 在直接启动过程中，没有成功开通 网络调试端口。
> 目前这个版本，没有记录 其它日志 。

重启 开机，我这边先打开magisk 

magisk日志

!
![Screenshot_20190523-233918](https://user-images.githubusercontent.com/49760068/58266320-0439e880-7db4-11e9-9ba9-dc8b61e57fa2.png)
[Screenshot_20190523-233501](https://user-images.githubusercontent.com/49760068/58266151-adccaa00-7db3-11e9-96fc-d99884694152.png)

**Comment by MoGuangYu** [comment]
> > 你检查你的 root 工具吧...
> > ```
> > 2019-05-23 22:39:05,823 [Brevent] INFO request status
> > 2019-05-23 22:39:05,879 [main] INFO service.adb.tcp.port:
> > 2019-05-23 22:39:05,904 [Brevent] INFO request status
> > 2019-05-23 22:39:11,026 [Brevent] INFO retry request status
> > 2019-05-23 22:39:11,034 [main] INFO service.adb.tcp.port:
> > 2019-05-23 22:39:12,148 [main] INFO received: android.intent.action.BOOT_COMPLETED
> > 2019-05-23 22:39:12,155 [main] INFO will startForegroundService
> > 2019-05-23 22:39:12,161 [IntentService[JianyuIntentService]] INFO show notification
> > 2019-05-23 22:39:12,176 [IntentService[JianyuIntentService]] INFO hide notification
> > 2019-05-23 22:39:14,518 [main] INFO will startService
> > 2019-05-23 22:39:14,530 [IntentService[JianyuIntentService]] INFO show notification
> > 2019-05-23 22:39:14,533 [IntentService[JianyuIntentService]] INFO startBreventServer for action me.piebridge.brevent.intent.action.RUN_AS_ROOT
> > 2019-05-23 22:39:14,537 [IntentService[JianyuIntentService]] INFO startBreventSync, action: me.piebridge.brevent.intent.action.RUN_AS_ROOT
> > 2019-05-23 22:39:14,540 [IntentService[JianyuIntentService]] INFO service.adb.tcp.port:
> > 2019-05-23 22:39:15,545 [IntentService[JianyuIntentService]] INFO service.adb.tcp.port: 3035
> > ```
> > 
> > 
> > 在直接启动过程中，没有成功开通 网络调试端口。
> > 目前这个版本，没有记录 其它日志 。
> 
> 重启 开机，我这边先打开magisk
> 
> magisk日志
> 
> !
> ![Screenshot_20190523-233918](https://user-images.githubusercontent.com/49760068/58266320-0439e880-7db4-11e9-9ba9-dc8b61e57fa2.png)
> [Screenshot_20190523-233501](https://user-images.githubusercontent.com/49760068/58266151-adccaa00-7db3-11e9-96fc-d99884694152.png)


![Screenshot_20190523-233501](https://user-images.githubusercontent.com/49760068/58266480-4bc07480-7db4-11e9-9c0e-41d28cc96d88.png)

**Comment by MoGuangYu** [comment]
> 比如我这边
> 
> 第一次，开机直接启动，外置存储不可用，不启动。
> 
> ```
> BreventUI: ignore start brevent on unavailable external storage
> ```
> 
> 第二次，开机启动，没有 su，不启动。
> 
> ```
> BreventUI: no su, ignore startBreventServer
> ```

[logs-v3.6.10.8-4-g3250f508-20190523.2342.zip](https://github.com/brevent/Brevent/files/3213029/logs-v3.6.10.8-4-g3250f508-20190523.2342.zip)
启动app抓日志

**Comment by MoGuangYu** [comment]
![Screenshot_20190523-234342](https://user-images.githubusercontent.com/49760068/58266626-a3f77680-7db4-11e9-8b96-c01031cead31.png)

**Comment by liudongmiao** [comment]
目前显示你没有支付。

```
no payment, ignore startBreventServer
```

**Comment by liudongmiao** [comment]
<s>新用户三天内，可以开机自启；后面的话，不再可以。</s> 某个版本起，root 自启需要付费。
同时，为了照顾某些人的感受，也不会在通知栏里提示需要支付。

**Comment by MoGuangYu** [comment]
> 目前显示你没有支付。
> 
> ```
> no payment, ignore startBreventServer
> ```

我丢，不早说，我就说嘛，以前都还是可以的。

**Comment by MoGuangYu** [comment]
> 新用户三天内，可以开机自启；后面的话，不再可以。 某个版本起，root 自启需要付费。
> 同时，为了照顾某些人的感受，也不会在通知栏里提示需要支付。

好的

**Comment by vvb2060** [comment]
原来应用内root启动按钮可用 与 可以开机自动启动服务状态不同步么……

**Comment by MoGuangYu** [comment]
> 原来应用内root启动按钮可用 与 可以开机自动启动服务状态不同步么……

嗯，需要点root启动使用

**Comment by liudongmiao** [comment]
应用内 root 启动按钮，相当于有试用期。
并且，每次启动之后，都有明确提示：
> 黑阈不需要也不提倡 Root，并且需要支付。
