### ISSUE TITLE
黑域环境异常 可能无法正常工作

### ISSUE THREAD

**Issue by peanut996** [brevent/Brevent#565]

**Comment by peanut996** [comment]
https://drive.google.com/file/d/1xGajfcQyU3MOhRN-tFfDhv1ZcAWzEQOE/view?usp=drivesdk

**Comment by liudongmiao** [comment]
目前来看，黑阈没有误报过。

如果你真是原版系统，没有 root，没有改动，就黑阈内反馈 - 日志。
