### ISSUE TITLE
解锁前启动可能导致Magisk ANR

### ISSUE THREAD

**Issue by aviraxp** [brevent/Brevent#567]
magisk在接收BOOT_COMPLETED广播时超时，不确定应该向谁反映这个问题

**Comment by vvb2060** [comment]
我的建议是，目前不要使用重写后的Magisk Manager…

**Comment by liudongmiao** [comment]
所以，是想不要开机直接启动么...
那开机启动呢...

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/commit/1d54c5144ed6aa126eb002005c5cba01d6a31199
我遇到的ANR问题已由此提交修复。不知道你说的是不是同一个问题。

**Comment by aviraxp** [comment]
topjohnwu说他那边没办法修

**Comment by liudongmiao** [comment]
所以，想怎么处理？黑阈不要支持 直接启动 ？

**Comment by liudongmiao** [comment]
已发 3.7.0.6 beta 版。

你可以单独停用任一个组件。

1. 停用直接启动

```bash
pm disable me.piebridge.brevent/.ui.BreventDirectBootReceiver
```

2. 停用开机自启

```bash
pm disable me.piebridge.brevent/.ui.BreventBootReceiver
```
