### ISSUE TITLE
开机自启动会卡

### ISSUE THREAD

**Issue by MoGuangYu** [brevent/Brevent#568]
开机启动的时候，需要在锁屏界面等一些时间再开锁进去桌面没有什么事，马上开锁的话会卡，卡桌面，中途magisk也会卡无响应，之后状态栏会提示黑阀服务启动正常，我试过换magisk版本，所有原生rom pie都会这样，这是怎么回事呢？

**Comment by liudongmiao** [comment]
参见 #567 ?

如果你系统自带的 su 不支持直接启动，请不要让黑阈自启。

在直接启动过程，应用无法访问 context 存储。
黑阈已经优化，相关数据全部使用数据存储。

但是，黑阈目前没有设置可以给你设置是否支持 直接启动。

**Comment by MoGuangYu** [comment]
> 参见 #567 ?
> 
> 如果你系统自带的 su 不支持直接启动，请不要让黑阈自启。
> 
> 在直接启动过程，应用无法访问 context 存储。
> 黑阈已经优化，相关数据全部使用数据存储。
> 
> 但是，黑阈目前没有设置可以给你设置是否支持 直接启动。

那就这样吧

**Comment by liudongmiao** [comment]
已发 3.7.0.6 beta 版。

你可以单独停用任一个组件。

1. 停用直接启动

```bash
pm disable me.piebridge.brevent/.ui.BreventDirectBootReceiver
```

2. 停用开机自启

```bash
pm disable me.piebridge.brevent/.ui.BreventBootReceiver
```
