### ISSUE TITLE
环境异常

### ISSUE THREAD

**Issue by Int-0X7FFFFFFF** [brevent/Brevent#569]
#黑域环境异常#  
老版本中未提示  
ROM Pixel Experience  
设备信息  
品牌:Xiaomi

型号:Mi 5X

基板:MSM8953

驱动:tiffany

标识:xiaomi/tiffany/tiffany:8.1.0/OPM1.171019.019/V10.2.3.0.ODBCNXM:user/release-keys

时间:1558455038000

标签:release-keys

用户名:ethan

版本号:PQ3A.190505.002

安卓版本:9

API级别:28

制造商:Xiaomi

主机地址:ubuntu

版本类型:user

开发代号:REL

指令集名称:arm64-v8a

无线固件版本号:unknown

**Comment by vvb2060** [comment]
如果是官方原版系统，并且未做任何修改，请黑阈内“反馈“ - “日志“，带上日志报告问题。

**Comment by liudongmiao** [comment]
一般是使用类 Xposed 插件注入黑阈进程所致。

如果没有此行为，炳请黑阈内反馈，日志，并描述问题。

如果有此行为，且黑阈看起来正常，可支付至 5 二向箔去掉部分安全提示。
