### ISSUE TITLE
Can't execute command, please switch to another SU

### ISSUE THREAD

**Issue by adroidnote4** [brevent/Brevent#57]
Can't execute command, please switch to another SU.

Root method: Magisk SU, latest v13.6
ROM: stock ROM, Galaxy Note 4, N910F

samsung/trltexx/trlte:6.0.1/MMB29M/N910FXXS1DQFA:user/release-keys
SELinux: true

WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '08-24 20:40:31.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-24 20:40:31.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
system 时不返回数据...所以，没办法。
