### ISSUE TITLE
希望支持读取 persist.adb.tcp.port 来检测网络 ADB 是否启用

### ISSUE THREAD

**Issue by silverzhaojr** [brevent/Brevent#570]
目前黑阈似乎只会检测 `service.adb.tcp.port` 来判断网络 ADB 是否启用，希望在上述检测没通过的时候可以再检测下 `persist.adb.tcp.port`，该设置项在设备重启后也会保持。参见[源代码](https://android.googlesource.com/platform/system/core/+/master/adb/daemon/main.cpp#248)。

**Comment by liudongmiao** [comment]
普通用户并无权限写 persist.adb.tcp.port，且支持网络调试的 rom，都会写 service.adb.tcp.port.

如果你能给出任何一个 rom，开启了网络调试，但是 service.adb.tcp.port 属性为空，请告知。

**Comment by silverzhaojr** [comment]
确实，我是 root 之后写入那个属性的，为的是方便每次重启后可以自动开启网络调试。不知道黑阈是否可以支持这个属性？

**Comment by liudongmiao** [comment]
你还不如问他们，能不能启动网络调试前，更新 service.adb.tcp.port 属性呢。

黑阈不会特意去支持不安全的 设备 使用方式。
包括但不限于这种 自动开启网络调试 的方式。

**Comment by silverzhaojr** [comment]
这个属性是我自己作为个人用户在 root 后写入的，和 rom 无关，主要是 `service.adb.tcp.port` 在重启后会重置。

**Comment by liudongmiao** [comment]
意思其实很简单。
persistent.X 普通没法设置。
能设置的，必然是非官方 ROM，或者提供了 Root。

既然你已经有 Root 了，直接利用黑阈 Root 就好。

否则，adbd 一旦重启，android 8.X 之后，黑阈服务就会被干掉。
黑阈只有在通过 Root 启动时，才会切断 黑阈服务 与 ADBD 关联，保证 adbd 即使关闭，黑阈服务也不会受影响。
