### ISSUE TITLE
在某些时候添加了允许同步的应用会被移除电池优化名单，导致该应用持续额外耗电

### ISSUE THREAD

**Issue by kunanaxp** [brevent/Brevent#575]

**Comment by liudongmiao** [comment]
这是预期行为。

> “黑阈清单”内应用也可以接收通知或执行同步，只要设置为“允许同步”就好。“允许同步”应用不会被待机；有通知或在后台运行时，不会被强行停止。

对于不支持 FCM 消息的应用，只要开启 允许同步，黑阈会把他们加进 电池优化白名单。
因为不支持 FCM 消息，他们即使周期性启动，也没法访问网络。
所以，为了接收消息，他们必须在 电池优化白名单。
