### ISSUE TITLE
部分被加入清单应用还是出现了通知

### ISSUE THREAD

**Issue by jeffreymor** [brevent/Brevent#576]
氢os Android 9.0版本
印象中最近几个版本的才有这样的情况，设置了自动激进还是有推送，出现比较多的是高德地图，腾讯新闻，斗鱼直播这几个

**Comment by liudongmiao** [comment]
一加应该接入了 oppo push，效果类似 小米，华为，魅族 等 push。
他们会无视停止状态，你可以直接控制他们的通知。
