### ISSUE TITLE
退款

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#577]
本人于2018年8月10日在黑阈内支付18元，不符合黑阈退款政策 https://www.jianshu.com/p/87aa6245d814 ，要求开发者例外退款。

**Comment by liudongmiao** [comment]
2019年6月29日支付的，符合退款条件。

所以，应该是信息写错了。

**Comment by ghost** [comment]
---原始邮件---
发件人: "Liu DongMiao"<notifications@github.com>
发送时间: 2019年6月29日(星期六) 中午1:02
收件人: "brevent/Brevent"<Brevent@noreply.github.com>;
抄送: "Verityc"<1723772122@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [brevent/Brevent] 退款 (#577)



2019年6月29日支付的，符合退款条件。
 
所以，应该是信息写错了。

**Comment by liudongmiao** [comment]
#77

**Comment by liudongmiao** [comment]
已退
