### ISSUE TITLE
关于应用操作的建议

### ISSUE THREAD

**Issue by pesh178** [brevent/Brevent#578]
希望在主界面右上角那添加个批量应用操作

**Comment by liudongmiao** [comment]
不懂你的意思。

对于 op，可以选择应用；对于应用，可以选择 op，也可以应用模板。

**Comment by pesh178** [comment]
就是现在应用操作不是只能一个一个设置吗
添加一个多个应用一键使用应用模板的功能

**Comment by liudongmiao** [comment]
这个可以有，下个小版本加入。

**Comment by liudongmiao** [comment]
@188king 看下最新 alpha 版：https://jianyu.io/br/alpha

注意，操作系统应用太过凶险，不提供批量操作，特别贡献用户也不行。

**Comment by liudongmiao** [comment]
已发 beta 版

**Comment by pesh178** [comment]
链接打不开

**Comment by liudongmiao** [comment]
因为已发 beta 版，所以变成了 https://jianyu.io/br/beta/

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
