### ISSUE TITLE
使用黑域后某些应用大概率无法链接网络

### ISSUE THREAD

**Issue by l7ay** [brevent/Brevent#58]
我用的手机是sonyz3c 安卓6.0 。1版本号23.5.A.1.291 手机未root 未解锁 官方固件 
这是服务日志
手机安装的应用都出现过无法连接网络的情况 如果您还需要什么可以再微博里找我 @l7ay
D:\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
06-24 12:51:24.153 25973 25973 D BreventServer: update current to com.tencent.mm

06-24 12:51:24.383 25973 25973 D BreventServer: check and brevent
06-24 12:51:24.629 25973 25973 D BreventServer: check again in 3600s
06-24 12:51:24.629 25973 25973 D BreventServer: check and brevent, took 246ms
06-24 12:51:51.536 25973 25973 D BreventServer: check and brevent
06-24 12:51:51.858 25973 25973 D BreventServer: check again in 3600s
06-24 12:51:51.858 25973 25973 D BreventServer: check and brevent, took 320ms
06-24 12:51:57.976 25973 25973 D BreventServer: check and brevent
06-24 12:51:58.216 25973 25973 D BreventServer: check again in 3600s
06-24 12:51:58.219 25973 25973 D BreventServer: check and brevent, took 242ms
06-24 12:52:00.139 25973 25973 D BreventServer: update current to com.android.se
ttings
06-24 12:52:02.112 25973 25973 D BreventServer: check and brevent
06-24 12:52:02.366 25973 25973 D BreventServer: Force stop com.sankuai.meituan(s
ervice)
06-24 12:52:02.418 25973 25973 D BreventServer: Force stop com.google.android.ap
ps.plus(noRecent)
06-24 12:52:02.499 25973 25973 D BreventServer: Force stop com.zhihu.android(ser
vice)
06-24 12:52:02.500 25973 25973 D BreventServer: check again in 3600s
06-24 12:52:02.500 25973 25973 D BreventServer: check and brevent, took 387ms
06-24 12:52:03.901 25973 25973 D BreventServer: update current to com.tencent.mm

06-24 12:52:31.848 25973 25973 D BreventServer: check and brevent
06-24 12:52:32.151 25973 25973 D BreventServer: Force stop com.google.android.ap
ps.plus(noRecent)
06-24 12:52:32.157 25973 25973 D BreventServer: Force stop com.sankuai.meituan(p
revious running)
06-24 12:52:32.162 25973 25973 D BreventServer: Force stop com.zhihu.android(pre
vious running)
06-24 12:52:32.164 25973 25973 D BreventServer: check again in 3600s
06-24 12:52:32.164 25973 25973 D BreventServer: check and brevent, took 314ms
06-24 12:53:11.661 25973 25973 D BreventServer: check and brevent
06-24 12:53:11.840 25973 25973 D BreventServer: Force stop com.google.android.ap
ps.plus(previous running)
06-24 12:53:11.842 25973 25973 D BreventServer: check again in 3600s
06-24 12:53:11.842 25973 25973 D BreventServer: check and brevent, took 179ms
06-24 12:53:25.161 25973 25973 D BreventServer: update current to com.android.se
ttings
06-24 12:53:28.703 25973 25973 D BreventServer: check and brevent
06-24 12:53:28.883 25973 25973 D BreventServer: check again in 3600s
06-24 12:53:28.883 25973 25973 D BreventServer: check and brevent, took 180ms
06-24 12:53:52.603 25973 25973 D BreventServer: update current to com.tencent.mm

06-24 12:54:02.877 25973 25973 D BreventServer: check and brevent
06-24 12:54:03.120 25973 25973 D BreventServer: Force stop com.sankuai.meituan(s
ervice)
06-24 12:54:03.189 25973 25973 D BreventServer: Force stop com.google.android.ap
ps.plus(noRecent)
06-24 12:54:03.190 25973 25973 D BreventServer: check again in 3600s
06-24 12:54:03.190 25973 25973 D BreventServer: check and brevent, took 310ms
06-24 12:54:27.072 25973 25973 D BreventServer: update current to com.sonyericss
on.home
06-24 12:54:28.388 25973 25973 D BreventServer: update current to com.sina.weibo

06-24 12:54:30.072 25973 25973 D BreventServer: check and brevent
06-24 12:54:30.378 25973 25973 D BreventServer: Force stop com.google.android.ap
ps.plus(noRecent)
06-24 12:54:30.382 25973 25973 D BreventServer: Force stop com.sankuai.meituan(p
revious running)
06-24 12:54:30.384 25973 25973 D BreventServer: check again in 3599s
06-24 12:54:30.384 25973 25973 D BreventServer: check and brevent, took 311ms
06-24 12:54:41.241 25973 25973 D BreventServer: check and brevent
06-24 12:54:41.595 25973 25973 D BreventServer: Force stop com.ruguoapp.jike(ser
vice)
06-24 12:54:41.750 25973 25973 D BreventServer: Force stop me.ele(service)
06-24 12:54:42.109 25973 25973 D BreventServer: Force stop com.netease.mail(serv
ice)
06-24 12:54:42.120 25973 25973 D BreventServer: Force stop com.google.android.ap
ps.plus(previous running)
06-24 12:54:42.121 25973 25973 D BreventServer: check again in 3593s
06-24 12:54:42.121 25973 25973 D BreventServer: check and brevent, took 839ms
06-24 12:55:25.655 25973 25973 D BreventServer: check and brevent
06-24 12:55:25.950 25973 25973 D BreventServer: Force stop me.ele(previous runni
ng)
06-24 12:55:25.952 25973 25973 D BreventServer: Force stop com.netease.mail(prev
ious running)
06-24 12:55:25.953 25973 25973 D BreventServer: check again in 3598s
06-24 12:55:25.953 25973 25973 D BreventServer: check and brevent, took 296ms
06-24 12:58:36.685 25973 25973 D BreventServer: check and brevent
06-24 12:58:36.930 25973 25973 D BreventServer: Force stop com.sankuai.meituan(s
ervice)
06-24 12:58:36.931 25973 25973 D BreventServer: check again in 3407s
06-24 12:58:36.931 25973 25973 D BreventServer: check and brevent, took 244ms
06-24 12:59:11.429 25973 25973 D BreventServer: check and brevent
06-24 12:59:11.670 25973 25973 D BreventServer: Force stop com.sankuai.meituan(s
ervice)
06-24 12:59:11.676 25973 25973 D BreventServer: check again in 3372s
06-24 12:59:11.676 25973 25973 D BreventServer: check and brevent, took 246ms
06-24 13:00:39.716 25973 25973 D BreventServer: check and brevent
06-24 13:00:39.966 25973 25973 D BreventServer: Force stop com.sankuai.meituan(s
ervice)
06-24 13:00:40.050 25973 25973 D BreventServer: Force stop co.uk.mrwebb.wakeonla
n(noRecent)
06-24 13:00:40.186 25973 25973 D BreventServer: Force stop com.zhihu.android(ser
vice)
06-24 13:00:40.190 25973 25973 D BreventServer: check again in 3284s
06-24 13:00:40.190 25973 25973 D BreventServer: check and brevent, took 473ms

D:\platform-tools>

**Comment by l7ay** [comment]
因为我同时使用绿色保护 再我单独使用绿色保护 就没有出现app无法联机网络的情况

**Comment by liudongmiao** [comment]
这个日志看起来很正常。黑域不会待机你正在使用的应用。

你可以看下，不能联网时，是否它处理于待机状态。
但很抱歉，你可能需要自己单独去看未启用的应用。

你也可以报告给其他软件。
但在此之前，我个人不建议你使用不同的软件，处理同一个应用。
否则，谁知道发生了什么呢？比如，你开启 force-doze，加 force-standby 之类。

此外，我个人从不保障与同类软件兼容性。

**Comment by l7ay** [comment]
我试试把其他同类型应用卸载掉 只用黑域试试看
