### ISSUE TITLE
关于卸载的反馈

### ISSUE THREAD

**Issue by seattlemagnet** [brevent/Brevent#581]
在MIUI中，使用黑阈卸载用户应用(但可能该用户应用被MIUI限制卸载)时，黑阈会卡死并丢失从adb获取的权限

**Comment by vvb2060** [comment]
打开黑阈应用-反馈-日志，将压缩包保存，上传到GitHub（浏览器选择桌面模式，点按输入框下面的文字）。

**Comment by seattlemagnet** [comment]
[logs-v3.7.2-20190702.1002.zip](https://github.com/brevent/Brevent/files/3347966/logs-v3.7.2-20190702.1002.zip) 在7月1日尝试过该操作

**Comment by vvb2060** [comment]
请复现问题后及时提取日志…

**Comment by seattlemagnet** [comment]
OK，现在可以复现

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
