### ISSUE TITLE
我是LG手机,刚升级vip,黑域之后待机再用,经常很卡,需要登陆黑域后,重新黑域一次就好了.

### ISSUE THREAD

**Issue by yuantelcom** [brevent/Brevent#583]
我是LG手机,刚升级vip,黑域之后待机再用,经常很卡,需要登陆黑域后,重新刷新黑域一次就好了.经常出现这种情况,请问怎么处理?还是手机哪里要怎么设置?有什么需要注意的?
对了,开发者模式是开启的.
请抽空处理一下,感谢!

**Comment by liudongmiao** [comment]
> 需要登陆黑域后,重新刷新黑域一次就好了

请描述一下这个过程，是指重新 激活黑阈 么？

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
