### ISSUE TITLE
一加3T在最近的更新后拔掉插头后就无法使用

### ISSUE THREAD

**Issue by Soys** [brevent/Brevent#584]
系统氧OS，在进行了190625的更新后…只要运行后拔掉数据线运行状态立马就掉了…这种情况同样发生在魅族16xs上，我把安全支付(手机管家里的)关掉依旧如此。
请问是否是因为谷歌的安全补丁问题？

**Comment by liudongmiao** [comment]
参照常见问题：https://tucao.qq.com/products/41738/faqs/39058

一般就是换个 usb 连接选项。

**Comment by Soys** [comment]
试过了，adb仅MIDI可识别出设备

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
