### ISSUE TITLE
无法在新手机上登录已有微信

### ISSUE THREAD

**Issue by willise** [brevent/Brevent#585]
在原有手机上已支付过, 换了手机后, 在另一台手机上尝试微信登录, 显示报错, 无法认证. 重装后在支付页面显示"payment is unavailable", 支付按钮常亮, 无法切换.

**Comment by liudongmiao** [comment]
1. 请仅使用 正版 微信，黑阈不负责任何 修改版 微信 所导致的任何问题。

2. 登录过程中，黑阈需要访问网络，且仅支持最新版黑阈。

**Comment by willise** [comment]
> 
> 
>     1. 请仅使用 正版 微信，黑阈不负责任何 修改版 微信 所导致的任何问题。
> 
>     2. 登录过程中，黑阈需要访问网络，且仅支持最新版黑阈。

1. 是正版微信, 没有修改过.
2. 授予访问网络权限了.

**Comment by willise** [comment]
将语言切换为中文后, 支付项正常.
