### ISSUE TITLE
启动时经常重新加载软件列表

### ISSUE THREAD

**Issue by hwazai010** [brevent/Brevent#587]
用了一段时间内的黑域，xz2，android9更新了最新的版本，但是有时黑域的捐赠版反映较慢，特别是每次启动都会检测服务、加载软件列表。在使用的过程中，与绿色守护、冰箱等可能存在兼容性问题。

**Comment by liudongmiao** [comment]
请确保使用最新的黑阈，当前是 3.7.4 
https://brevent.jianyu.io/

每次进入，都会有检测服务这个过程，只是非常快，都不会感觉到。

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
