### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by hwj04** [brevent/Brevent#588]
安装黑阈后，手机十分卡顿发热，部分系统应用会提示已停止运行。卸载重启后得到改善，但还是部分系统应用停止运行，怎么回事？刷机(不清除data)能解决吗？

**Comment by liudongmiao** [comment]
1. 黑阈几乎不会影响系统
2. 不正当黑阈，包括黑阈系统应用，以及激进策略，都会导致系统无法正常使用。

黑阈正常时，卸载黑阈，会还原黑阈所有设置。

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
