### ISSUE TITLE
没有关机 也没用关闭usb调试 但是经常需要重新激活

### ISSUE THREAD

**Issue by NoodleTiger** [brevent/Brevent#589]

**Comment by liudongmiao** [comment]
参见常见问题：https://tucao.qq.com/products/41738/faqs/39058

**Comment by NoodleTiger** [comment]
开启网络调试后 过段时间还是会掉

Liu DongMiao <notifications@github.com> 于 2019年7月29日周一 上午7:45写道：

**Comment by liudongmiao** [comment]
目标是不开启网络调试。
自己多试试其它选项。

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
