### ISSUE TITLE
The Weibo intl can not connect the internet.

### ISSUE THREAD

**Issue by MagicLentil** [brevent/Brevent#59]
When I use the heiyu , the Weibo intl can not connect the internet, even though I allow it to sync. Would you please solve it? Thank you!

**Comment by liudongmiao** [comment]
1. force-stop it
2. open it again..

heiyu...it's english name is brevent...

**Comment by MagicLentil** [comment]
Thanks.....
Btw, would you please tell me how to open the GCM of wechat without root in
prevent?

2017年6月24日 20:15，"Liu DongMiao" <notifications@github.com>写道：

**Comment by liudongmiao** [comment]
wechat doesn't support fcm well.

you can just brevent app, then "allow sync". You'll see FCM tip and cloud icon when it may support fcm.

**Comment by MagicLentil** [comment]
Thanks...
See this.......
http://www.jianshu.com/p/efdc9e6c2935
Why I have no GCM option in my prevent(Play Version)?.....

2017年6月29日 20:29，"Liu DongMiao" <notifications@github.com>写道：

**Comment by liudongmiao** [comment]
it's merged into allow sync, and it's enabled by default.

```
v1.0.1
- remove option "Allow FCM", default on
```

**Comment by MagicLentil** [comment]
Thank you!!!!!!!!!!!!!

2017年6月29日 20:35，"Liu DongMiao" <notifications@github.com>写道：
