### ISSUE TITLE
关于黑阈打开后无法运行一些软件

### ISSUE THREAD

**Issue by VstalVVV** [brevent/Brevent#590]
我的手机安卓系统升级到P的时候，买了一个黑阈激活器，然后发现了这个bug。
在我不开（没有激活）黑阈的时候，可以正常运行一类游戏。但是激活了之后就不可以了。这类游戏我发现了两款《ICEY》、《碧蓝航线》。
两个好像都是live2D，希望得到解决。

**Comment by liudongmiao** [comment]
一般是你不正当黑阈系统应用，或者对某些应用开启了 激进策略。
自查吧，特别是 google 家的应用。

**Comment by liudongmiao** [comment]
没有进一步消息，关闭。
