### ISSUE TITLE
黑阈希望能加上常驻通知栏的选项问题

### ISSUE THREAD

**Issue by dengchan0416** [brevent/Brevent#591]
我手机是华为NOTE8 EMUI 8.0 在系统里已经设了黑阈不被系统自动清除,还有开启自启,可是系统运行长时间了还会自动清除APP, 希望能在黑阈软件里,让用户自己选择黑阈是否常驻通知栏,看是否程序运行情况.有没有给系统清除掉,希望能得到回复,谢谢

**Comment by liudongmiao** [comment]
连按 7 次 Home 键，查看黑阈状态。

通知栏没有意义，真正工作的不是黑阈管理界面，是黑阈服务。
