### ISSUE TITLE
Add symbol legend

### ISSUE THREAD

**Issue by ghyatzo** [brevent/Brevent#592]
Hello,
I've used this app for a while now and I must say is incredibly useful. 
Although, I have a hard time understanding sometimes what a specific symbol means. 
And apart from me non understanding I think that a new user of the app would appreciate a clearer explanation on what he is seeing. 
How the app works is explained clearly,  but often you end up with symbols with a meaning that is not really straightforward and nowhere to look for some kind of documentation, or at least not immediately clear where to look. 

Just a little legend in the starting guide section would go a long way helping to understand what is going on with the app. 

Thanks!

**Comment by liudongmiao** [comment]
So, what's `specific symbol`?

**Comment by liudongmiao** [comment]
Actually, you can always tap the icon (symbol?) to see it's meanings.

**Comment by liudongmiao** [comment]
Actually, you can always tap the icon (symbol?) to see it's meanings.

**Comment by ghyatzo** [comment]
Then it's my fault, I'm sorry.
Although adding a tip somewhere where you mention this wouldn't hurt. 

Thank you for your amazing work!!
