### ISSUE TITLE
关于fcm

### ISSUE THREAD

**Issue by Newcomer365** [brevent/Brevent#593]
柳大，可否加个开关以允许可完整fcm推送的应用接受推送的消息。现在的机制一方面需要批量同步后才能知道哪些应用支持fcm，另一方面这些应用需要在后台才能接收fcm的推送。

**Comment by vvb2060** [comment]
搜索框输入 `-f` 可找出所有支持fcm的应用。
完全支持fcm的应用不需要留后台，但应用不能是停止状态或自适应电池受限状态。

**Comment by Newcomer365** [comment]
感谢提醒，理论上电池优化状态下fcm应该也能正常使用（只是会延迟），黑域应用后fcm完全失效，是否有可能增添个开关自动允许fcm应用可使用fcm进行推送（不需要拉起）

**Comment by liudongmiao** [comment]
黑阈内你只需对这些应用开启 允许同步 即可。

如果设备支持 FCM，则黑阈仅更新停止状态；否则，黑阈会尽力保证应用能接收到消息。

**Comment by liudongmiao** [comment]
黑阈内你只需对这些应用开启 允许同步 即可。

如果设备支持 FCM，则黑阈仅更新停止状态；否则，黑阈会尽力保证应用能接收到消息。

**Comment by Newcomer365** [comment]
@liudongmiao 能否给个按钮让支持fcm的应用自动允许同步呀，能自动化的东西没必要手动啊。。。

**Comment by liudongmiao** [comment]
你只需要一次操作，而反感这些通知的人，则需要做更多的事情取消。
而且，黑阈从来不代替用户做选择，所有选择，都由用户主动做出。

比如说个例子，某 恶意应用 使用 FCM 通知 + 推广告，你奈之何？
技术无好坏，重要的是如何使用，以及使用的人用来干什么。

再比如说，利用账号同步的允许同步呢？
Gmail 是不支持 FCM 的哦～

**Comment by liudongmiao** [comment]
你操作很简单，-f 搜索，选择，批量 允许同步 即可。
而自动，带来的后果，更麻烦。

不要总想着你的便利，而要想更多的合理性。

比如，知乎，优酷等都符合 fcm 定义...
你真的需要他们的通知？

**Comment by Newcomer365** [comment]
@liudongmiao    有这个想法，主要是试了下mipush统一推送(非小米手机)，只要push应用不黑域，那么有支持米推的应用通知时push应用可正常推送消息(不管是否黑域)，点击通知可正常进入应用相关界面(不管这些应用是否在黑域名单中)，不点击通知则不会唤醒应用。这种方式既能正常通知，又不会瞎唤醒自启，而对于fcm，一刀切实在太狠了。。。-f 批量允许同步的确很简单，但是对于新应用，每次去手动检查其是否支持gcm实在是太麻烦了。往往是电报 twitter很长时间没推送了，才等反应过来黑域掉了。当然我不是开发者。不知道添加一个安装新应用时如果支持fcm的则自动黑域的功能（或者按钮将选择权给用户）。或者对于正常fcm推送能稍放口子(类似对mipush的处理？)，会不会很难实现，但是相信这个功对海外黑域用户和特殊用户还是很有用的。至于广告，某些应用重要信息（物流，私信）和广告混推，该忍受还是得忍受啊。

**Comment by liudongmiao** [comment]
自己控制啊，那就是 允许同步。
