### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Mubai-Dust** [brevent/Brevent#595]
PS M:\App\platform-tools> .\adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
>>
* daemon not running; starting now at tcp:5037
* daemon started successfully
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '08-15 11:20:40.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-15 11:20:40.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by liudongmiao** [comment]
没什么日志，请确保你设备 开启了 日志功能。

**Comment by Mubai-Dust** [comment]
我该如何开启日志功能呢 没有使用Android Studio

**Comment by Mubai-Dust** [comment]
https://paste.ubuntu.com/p/zHv42N7HPf/
避免太长粘贴到网址了

**Comment by liudongmiao** [comment]
不是说这个日志，而是没有黑阈相关日志。

1. 不要瞎弄 开发者选项 中日志相关内容
2. 仅从黑阈官网下载黑阈 https://brevent.jianyu.io

**Comment by Mubai-Dust** [comment]
用的是miui 没有找到调出日志的方法x

**Comment by liudongmiao** [comment]
官方 rom，你不动它的，是没问题的。
如果非官方，或者你又魔改了，我就不知道了。

**Comment by Mubai-Dust** [comment]
可能跟网络有关嘛 root是可以正常用 但重启后root使用就会消失

**Comment by liudongmiao** [comment]
没有日志，没有后续，关闭。
