### ISSUE TITLE
3.7.4版本root开机启动失败

### ISSUE THREAD

**Issue by adsl95** [brevent/Brevent#596]
app用的play版,
红米note5.
系统miui9.6.4.0.
安卓8.1
root使用magisk 19.3
症状为,开机提示正在启动,一会就启动失败.必须手动点进去黑阈app然后弹出root对话框,点一下root才能启动成功.magisk已经永久授予root权限,其他开机启动的root软件自启都正常.
请问如何解决?
谢谢

**Comment by adsl95** [comment]
补充一句,只要不重启手机或关闭开机,一直用的没问题,就是开机自启一直失败,试了四次结果都是一样的.
app自带的反馈不知道怎么用,点了日志提示打开蓝牙.打开之后显示附近的蓝牙设备.没有下文了

**Comment by adsl95** [comment]
用蓝牙传到另一手机上了,您看看吧.
链接: https://pan.baidu.com/s/1n-9hwB7WO_4TVgu3ty7IBw 提取码: bzfv

**Comment by vvb2060** [comment]
百度网盘不允许游客下载，请直接上传到GitHub。

**Comment by adsl95** [comment]
https://u21137204.ctfile.com/fs/21137204-393305097
您试试这个,github没试过上传附件.
这个网盘不需要登录,点普通下载就行.
谢谢

**Comment by adsl95** [comment]
试一下,能不能附件

**Comment by liudongmiao** [comment]
我估计你可以看看 #567

说实话，不想对 root 提供任何协助。
你说了一大堆，没有任何有用信息。

日志，你直接发邮件描述就好。

**Comment by adsl95** [comment]
已发送至brevent@jianyu.io这个邮箱
这个也属于付费功能.可以的话最好能给解决一下,谢谢.
root用户虽然少但确实的省下很多事,adb和启动器哪个都比root全自动用起来麻烦一点

**Comment by adsl95** [comment]
我这边的话,magisk那边没有任何异常,看magisk授权的日志.授权也是正常的,开机有授权动作.就是黑阈服务启动不来.

**Comment by liudongmiao** [comment]
正常反馈的话，黑阈都会第一时间处理。

已经邮件回复过了。
你提取的日志，要么太慢，要么受干扰，没有任何相关信息，也就是日志被冲刷掉了。

这与付费与否无关，不论是否付费，黑阈都第一时间修复，属于 bug 的赠送特别贡献。

**Comment by liudongmiao** [comment]
没有后续，关闭。
