### ISSUE TITLE
can’t run with root

### ISSUE THREAD

**Issue by Stubborn10086** [brevent/Brevent#60]
u0_a337@max1:/ $ su
root@max1:/ # su -c setenforce 0
getenforce
su -c /data/app/`pm path me.piebridge.brevent|cut -f 4 -d '/'`/lib/*/libbootstrap.sogetenforce
su -c /data/app/`pm path me.piebridge.brevent|cut -f 4 -d '/'`/lib/*/libbootstrap.soroot@max1:/ #
root@max1:/ # su -c setenforce 0
root@max1:/ # getenforce
Permissive
/app/`pm path me.piebridge.brevent|cut -f 4 -d '/'`/lib/*/libbootstrap.so     <
sush: /data/app/me.piebridge.brevent-2/lib/*/libbootstrap.so: not found
127|root@max1:/ # sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
WARNING: run as root is experimental!!!
checking...brevent_server started, pid: 32265
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '06-24 23:09:07.000' -d
06-24 23:09:08.892 32265 32265 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
06-24 23:09:08.892 32265 32265 E AndroidRuntime: java.lang.reflect.InvocationTargetException
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2023)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
06-24 23:09:08.892 32265 32265 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1626)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:3512)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at me.piebridge.brevent.server.e.a(HideApi.java:156)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.f(BreventServer.java:339)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:238)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1911)
06-24 23:09:08.892 32265 32265 E AndroidRuntime:        ... 4 more
06-24 23:09:08.893 32265 32265 E AndroidRuntime: Error reporting crash
06-24 23:09:08.893 32265 32265 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-24 23:09:08.893 32265 32265 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
06-24 23:09:08.893 32265 32265 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
06-24 23:09:08.893 32265 32265 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4534)
06-24 23:09:08.893 32265 32265 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
06-24 23:09:08.893 32265 32265 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
06-24 23:09:08.893 32265 32265 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-24 23:09:07.000' -d -s BreventLoader BreventServer
06-24 23:09:08.230 32255 32255 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
06-24 23:09:08.788 32265 32265 D BreventServer: get service: package: android.os.BinderProxy@42ce945
06-24 23:09:08.836 32265 32265 I BreventServer: starting Brevent Server 1.2.4
06-24 23:09:08.842 32265 32265 D BreventServer: get service: package: android.os.BinderProxy@42ce945
06-24 23:09:08.848 32265 32265 I BreventServer: brevent user: 0, uid: 0
06-24 23:09:08.851 32265 32265 I BreventServer: brevent data directory: /data/user/0/com.android.shell
06-24 23:09:08.923 32255 32255 E BreventLoader: worker 32265 exited on signal 9
06-24 23:09:08.923 32255 32255 D BreventLoader: signal arrived, update: 0
06-24 23:09:08.924 32250 32250 D BreventLoader: worker 32255 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above
1|root@max1:/ #

**Comment by liudongmiao** [comment]
please install the latest 1.3.

#39 #55
