### ISSUE TITLE
开启adb时的弹窗

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#60]
1)如果没先开调试链接USB，开发者选项就变复制指令了，应该等开了调试再变。虽然有提示但考虑有时用户习惯先链接USB，而且有时调试要通过允许，等调试允许后再变更符合实际情况。

2)这里没法回到向导，建议加个向导让用户再看一下adb指令。

**Comment by liudongmiao** [comment]
感谢建议

**Comment by GithubApkUser** [comment]
感谢回复

**Comment by GithubApkUser** [comment]
@liudongmiao 柳大我明白你在#76说的直接退出了，但你也没必要lock啊，我只能在这里回复了。从那个弹窗进入开发者返回黑域直接退出后，能不能让黑域显示在最近任务中，我知道黑域退出后就没了，但起码在这种情况应该让黑域出现在最近任务，这样就能够快速返回黑域，连续两下□也能返回，这样就好用了。

**Comment by liudongmiao** [comment]
明白你的意思了。
