### ISSUE TITLE
黑域使用以后电量掉得特别快

### ISSUE THREAD

**Issue by ssaakkiii** [brevent/Brevent#601]
你好，我是Sony Xperia z2，Android9手机，我使用激活黑域以后，电量掉得比黑域没有启动快，一个很明显的现象是，我用车载充电器充手机，启动黑域以后一直充仍一直掉电，但是关闭开发者调试之后，黑域不工作了，充电电量就在增长了。请优化一下，谢谢！

**Comment by liudongmiao** [comment]
自查是否有以下操作：
1. 黑阈 系统应用/框架应用
2. 对任何一个应用 启用 激进策略

**Comment by liudongmiao** [comment]
你也可以黑阈内 反馈 - 日志，带上日志 并描述，我会分析日志，然后告诉你具体是哪些应用被不断启动及强行停止

**Comment by ssaakkiii** [comment]
哦哦，我激进了十来个应用……和这个有关系吗

**Comment by ssaakkiii** [comment]
我用邮件发送了日志，不知道收到没有

**Comment by liudongmiao** [comment]
没有。发日志邮件，要描述问题，特定问题记得带包名，要不然我会直接忽视。

不建议激进应用，我本人是直接对于激进应用取消，然后使用 停用 及 临时启用 快捷方式。

**Comment by ssaakkiii** [comment]
好的，谢谢
