### ISSUE TITLE
Note 10 Plus无法启用黑域

### ISSUE THREAD

**Issue by NickTheReaI** [brevent/Brevent#604]
之前一直是用的NOTE 8, 一切都很正常.
这几天换成了NOTE 10 PLUS, 插拔USB的时候会失效, 有时候是拔完后5-10分钟内把程序关了再开就会失效.
昨天也出现了较早另外一个Note10用户发的那个adb错误
现在错误的那个没有了
我已经把提示的全部能做的都试了, usb默认调成充电跟其他每一个我都试了, 那个优化音乐的我也关掉了.
我还搜了 有说要下一个ALPHA版本, 我也下了.
但还是没能正常运行.
就想问 是否是Note 10 plus的问题?

**Comment by liudongmiao** [comment]
1. 激活参照  https://brevent.sh （电脑上访问）

2. Android 8 及以上，失效问题参照 https://tucao.qq.com/products/41738/faqs/39058

**Comment by NickTheReaI** [comment]
我知道激活是用电脑上的adb阿 那个失效问题里我每一项我都注意了 并且跟着做了，然而并没有用，还是不行。有几次是拔完线，还正常运行的，期间根本没有动手机，再打开APP就又失效了。

**Comment by liudongmiao** [comment]
这个没有办法，就是多试几个其它的选项。一般来说，默认设置为非数据模式，然后保持不动就好。

从过去检查日志来看，用户每次说这个，都是因为某种原因 usb 模式发生了变化。

**Comment by NickTheReaI** [comment]
我发现问题了，因为是note 10是没有耳机孔的，所以插耳机也是用USB那个口，所以每次插拔耳机也会影响usb。
