### ISSUE TITLE
每次用数据线连接手机和电脑，黑阈服务就会停止，需要重新执行adb

### ISSUE THREAD

**Issue by libra7012** [brevent/Brevent#608]
每次用数据线连接手机和电脑，黑阈服务就会停止，需要重新执行adb，以前不需要的。

**Comment by vvb2060** [comment]
Android 8 起，只要关闭“USB 调试”或更改 USB 选项，黑阈就失效。
部分手机连接时会弹窗，是否允许电脑访问手机数据，这是在切换到MTP模式，请选择拒绝以保持默认的仅充电模式。

**Comment by libra7012** [comment]
明白了，只不过以前连电脑传文件都不会停止服务的，估计是手机更新的锅
