### ISSUE TITLE
ADB命令开启黑域之后，SSR不能用了

### ISSUE THREAD

**Issue by MagiciSource** [brevent/Brevent#61]
一建立连接就会立马断开

**Comment by MagiciSource** [comment]
S7 edge 安卓7.0版本

**Comment by liudongmiao** [comment]
你得来点日志啊...此外，不要黑域这个什么 SSR，如果黑域的话，开启允许同步，同时不要开启立即黑域。

没有日志的反馈，和没有反馈一样，真的。

**Comment by vvb2060** [comment]
已知问题，使用假GMS时出现。
那么既然是假GMS就别黑域GMS了，强行停止GMS时系统杀依赖会把SSR也杀了。

要修复找破娃去问为什么依赖GMS，这边不会也没法处理。

MagiciSource <notifications@github.com>于2017年6月27日周二 下午7:11写道：

**Comment by liudongmiao** [comment]
无日志，关闭。
