### ISSUE TITLE
向导

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#61]
1)Android 系统离开应用可以通过好几种方式，“返回”按钮退出应用回到上层，“主页”按钮或者“总览”（Overview）按钮把应用放到后台。

黑域通过这种方式识别您是否打开或已经退出，阻断黑域清单里的应用在没有使用的时候长期运行。对于被恶意唤醒的应用，一律强行停止。

这里 “黑域通过这种方式识别”的“这种”描述不清晰，不知道是哪一种。应该为“以上”或者“”

**Comment by GithubApkUser** [comment]
或者“这几种”

2)黑域需要您每次开机以后，以调试模式执行一个命令启动黑域服务，让黑域间接持有管理其它应用的权限。
为了方便，黑域有一个实验性的 ROOT 模式，可以直接“使用 ROOT 启动”黑域服务。ROOT 模式与普通模式相比没有更多功能也没有更好效果，在某些设备上 ROOT 模式甚至无法启动黑域服务。

这里表述应该更明确，说明黑域不但能够以Root模式运行，而且开启“使用root启动“后还能够实现开机自启动。

**Comment by GithubApkUser** [comment]
3）向导和设置黑域方法都没说已退出但带服务的应用在锁屏后会很快被处理，不用等待机超时，建议加上这个锁屏清理的描述，这个很经典

**Comment by liudongmiao** [comment]
1. 可改可不改...因为都另起一行了。

2. 可改可不改...因为开机自启需要额外设置，首次见到“使用 ROOT 启动”成功以后，有详细提示。

3. 黑域不会针对锁屏进行任何处理，锁屏只是来一次常规清理，肯定是等待机超时或者后台超时。否则，是其它应用处理。

**Comment by GithubApkUser** [comment]
感谢柳大回复
