### ISSUE TITLE
Brevet In read only mode

### ISSUE THREAD

**Issue by eljejer** [brevent/Brevent#615]
I cannot find out how to prevent prevent from only being able to run in read only mode.
Android Pie (CypherOS) rooted with Magisk.

**Comment by eljejer** [comment]
After app Start message in bottom of screen:
Brevent server is not started.
Brevent is in read-only mode.
I press Start Brevent.
Message: It seems that your device is rooted.
I press "Root" and brevent is granted su rights
Message: Starting Brevent server. Just a moment.
Message: Please start brevent server. Network ADB is turned on. Tap ADB to start brevent server.
I tapp ADB.
Message: Starting brevent server. Just a moment.
Message: Please start brevent server. Network ADB is turned on. Tap ADB to start brevent server.
I tapp ADB.
Message: Starting brevent server. Just a moment.

etc etc. This is a loop...

What can I do?

**Comment by liudongmiao** [comment]
It means Brevent on your device is not stable.

**Comment by eljejer** [comment]
> It means Brevent on your device is not stable.

And do you know of any work around or fix?
