### ISSUE TITLE
不能阻止关联启动

### ISSUE THREAD

**Issue by thotwielder** [brevent/Brevent#616]
pixel 2 xl android 10. 启动彩贝壳时，交警121, 中山医院，太平洋保险，51job等都会自动启动。虽然这些app都被brevent，过一会会自动被清除，但是瞬间自启动时仍然造成系统卡顿。

**Comment by liudongmiao** [comment]
对于这种情况，如果开启了 自动激进，黑阈会标识为 激进。
黑阈没有好的办法，你可以直接停用他们，然后使用临时启用。
不过，到了 Android 10 时代，可以使用内置的 freeze 代替停用，这样桌面上还能看到。

黑域将在下个版本，尝试使用 freeze 处理这种激进模式的应用。
