### ISSUE TITLE
黑阈在安卓q上用处不大

### ISSUE THREAD

**Issue by Diarica** [brevent/Brevent#617]
本人于 2019年  11月 10 日在黑阈内支付 21 元，不符合黑阈退款政策，要求开发者例外退款。（黑阈在安卓q上没什么用，已经不需要了）

**Comment by Diarica** [comment]
> 本人于 2019年 11月 10 日在黑阈内支付 21 元，不符合黑阈退款政策，要求开发者例外退款。（黑阈在安卓q上没什么用，已经不需要了）

4200000453201911104051036321

**Comment by liudongmiao** [comment]
请带上截图，发邮件至 refund # jianyu.io
具体参见 https://www.jianshu.com/p/87aa6245d814 中例外退款政策。

**Comment by liudongmiao** [comment]
该用户 2019-10 已经退过。github 公示后，需要截图发邮件申请。

**Comment by Diarica** [comment]
> 
> 
> 该用户 2019-10 已经退过。github 公示后，需要截图发邮件申请。

谢谢，不需要退款了，已经正确使用黑阈
