### ISSUE TITLE
一加6 Android P上面经常自动退出

### ISSUE THREAD

**Issue by freetum** [brevent/Brevent#618]
在一加6上面经常自动退出，打开之后显示“黑阈 3.8.3 **环境异常，黑阈可能无法正常工作。”。请问是怎么回事？[https://pan.baidu.com/s/1GQOWWkgL8OUGZFVYmJ0rSw](Log)**

**Comment by liudongmiao** [comment]
退出问题参照 https://tucao.qq.com/products/41738/faqs/39058
提示异常，多半是你使用各类 类 xposed 侵入了 黑阈 进程。

**Comment by freetum** [comment]
那个链接信息并没有什么帮助，请问从log看具体是什么原因呢？
