### ISSUE TITLE
Unable to brevent some apps with non-cancelable notification

### ISSUE THREAD

**Issue by perqin** [brevent/Brevent#62]
Some apps present a non-cancelable notification when launched (e.g. this one: [http://www.coolapk.com/apk/cn.soulapp.android](http://www.coolapk.com/apk/cn.soulapp.android)). Brevent fails to standby these apps, that is, they are still running in background after the *Background apps timeout* is reached.

Brevent crash log and Brevent Server log files are attached below.

[crash.txt](https://github.com/brevent/Brevent/files/1107474/crash.txt)
[server.txt](https://github.com/brevent/Brevent/files/1107473/server.txt)

**Comment by liudongmiao** [comment]
> 06-28 11:17:41.931 16846 16846 D BreventServer: inactive for cn.soulapp.android: 72, timeout: 60
> 06-28 11:17:41.975 16846 16846 D BreventServer: final blocking: {cn.soulapp.android}

Please check the brevent mthod, default is "standby, then force-stop".
In your case, the app will be standby, then force-stop.
You can swipe it from recent list, otherwise, it will be force-stop when standby timeout (default 1 hour).

**Comment by liyufan** [comment]
正奇怪你怎么会知道酷安，看了你的profile你是中国人。。。

**Comment by perqin** [comment]
@liudongmiao The brevent  method is set to default option "standby, then force-stop". I launched the *Soul* app and then changed *Background apps timeout* to 1 minute, and *Standby timeout*
 to 15 minutes. However, after 16 minutes, the app is still running. Seems that Brevent failed to force-stop it after the standby timeout.

I checked the server log again and I did find some lines saying *Soul* is blocked. There are some other related logs but I can't figure out their meaning, so I attach the log file here.

[server2.txt](https://github.com/brevent/Brevent/files/1112862/server2.txt)

I decide to try reproducing the issue on my Xiaomi Mi3 W, as I think it may be a ROM- or device-specified issue. More info will be provided later.


@liyufan English is the preferred language in open source world :grin:

**Comment by liudongmiao** [comment]
@perqin It seems that the app has sticky notification.

For non-clearable notification, if it's in background, Brevent won't brevent it.
As for sticky notification, you know it's running, so Brevent won't brevent it.

You can clear it from recent list, then Brevent will brevent it.

It's better to use Chinese, as my English is poor... And there's little English users.
