### ISSUE TITLE
本人于 2019 年 11 月 10 日在黑阈内支付 21 元，不符合黑阈退款政策，要求开发者例外退款。

### ISSUE THREAD

**Issue by Diarica** [brevent/Brevent#621]
微信交易单号：4200000453201911104051036321

已发邮箱

**Comment by liudongmiao** [comment]
请截图发至邮箱。

你之前已经退过款，何必再次退款，浪费大家时间呢。

**Comment by Diarica** [comment]
这次真的不再退款了，看到即将更新的新功能就没有退款的动力了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liu DongMiao"<notifications@github.com&gt;; 
发送时间: 2019年12月4日(星期三) 晚上8:43
收件人: "brevent/Brevent"<Brevent@noreply.github.com&gt;; 
抄送: "混合理论."<3501108459@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [brevent/Brevent] 本人于 2019 年 11 月 10 日在黑阈内支付 21 元，不符合黑阈退款政策，要求开发者例外退款。 (#621)




请截图发至邮箱。
 
你之前已经退过款，何必再次退款，浪费大家时间呢。
