### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#63]
1)日志读取不方便，获取后找不到日志，直接就发送了，有时都不知道发了什么内容，本来想截取一下方便dalao看的，建议获取后能够直接查看
2)黑域里上边的搜索，排序，菜单三个键长按后的样式不一致，有的没反应，有的提示，有的打开，建议能够一致
3)建议排序的四个方式能够提供升降序排列，再点一次就倒过来那种

**Comment by liudongmiao** [comment]
1. 都有文件了，想看的人，自然能看。

2. 系统默认组件，就这样。

3. 不提供。我没有见过有把名字倒过来的看的。这些都典型场景。

以上非核心功能，代码也开源，有人实现了，我就 merge 一下。
否则，没有任何动力去实现。

**Comment by GithubApkUser** [comment]
柳大，我改名字了，我虽然是酷安的但我是挺你的，返现和红包我都不参加的，请问日志在哪里看啊？

**Comment by vvb2060** [comment]
@GithubApkUser /sdcard/Android/data/me.piebridge.brevent/files/logs/

**Comment by GithubApkUser** [comment]
找到了有三个！谢谢！
