### ISSUE TITLE
启动王者荣耀会有跑跑卡丁车推送

### ISSUE THREAD

**Issue by ActDeco** [brevent/Brevent#631]
最近安装了手游版跑跑卡丁车，已经将跑跑卡丁车设置黑域，但是启动王者荣耀的时候，会弹出卡丁车的推送，即使把卡丁车设置为激进也不能阻止。
其它软件没有发现这种情况。

**Comment by liudongmiao** [comment]
部分推送可不启动应用，直接推荐。比如 小米，魅族，华为 等国产手机。
