### ISSUE TITLE
Brevented apps still running and showing notifications.

### ISSUE THREAD

**Issue by k4tipun** [brevent/Brevent#633]
I Brevented Lazada app but still, it still running and show notifications. I even set it on aggressive mode.

![IMG_20200214_143939](https://user-images.githubusercontent.com/25127774/74507621-ec088b80-4f37-11ea-9f20-0736629f1420.jpg)
![IMG_20200214_144005](https://user-images.githubusercontent.com/25127774/74507623-f034a900-4f37-11ea-8d3f-709b1e014d1d.jpg)

**Comment by liudongmiao** [comment]
There are some roms (mainly in china), allow apps to notify without running, and show the icon of the apps instead of notify app.
