### ISSUE TITLE
打开王者荣耀之后一直显示在运行,没有停用到

### ISSUE THREAD

**Issue by dengchan0416** [brevent/Brevent#634]
已经是正常退出游戏了,一直在后台运行着,黑阈也没有停用到,以前是可以的
![7A414EABFA60CED7461011920559C55C](https://user-images.githubusercontent.com/41529838/74697320-56ba0f80-5235-11ea-9528-52a625dd8917.jpg)

**Comment by liudongmiao** [comment]
正常情况下，黑阈不处理 “缓存服务” 应用。
可以连按 7 次 设置 - “系统状态”，关闭 “无需处理” 选项。
