### ISSUE TITLE
三星Android10 一直提示关闭USB调试

### ISSUE THREAD

**Issue by iswenjie** [brevent/Brevent#635]
更新Android10之后，只要一打开购物、支付软件就提示我关闭USB调试，有支付风险。
但是关闭之后黑阈就不能用了，能关闭提示吗，或者在关闭USB调试的情况下，黑阈能用吗？
手机型号：三星 s9+

**Comment by qiaoanqiao** [comment]
向导要仔细看. 关闭了就不能用了

**Comment by angelmengg** [comment]
> 更新Android10之后，只要一打开购物、支付软件就提示我关闭USB调试，有支付风险。
> 但是关闭之后黑阈就不能用了，能关闭提示吗，或者在关闭USB调试的情况下，黑阈能用吗？
> 手机型号：三星 s9+

这个提示能关闭的，具体百度能找到解决办法

**Comment by liudongmiao** [comment]
可能是 安全支付 相关？
