### ISSUE TITLE
最近突然出现大量软件在xx秒内黑阈xx次 建议停用/取消黑阈

### ISSUE THREAD

**Issue by edog025** [brevent/Brevent#637]
包括facebook在内各种国内外软件 不停地出现此通知

**Comment by vvb2060** [comment]
反复启动停止应用会增加耗电，所以当黑阈检测到这种情况时，会建议停用或取消黑阈。
或许应该在通知里说明得更详细一点。

**Comment by edog025** [comment]
> 反复启动停止应用会增加耗电，所以当黑阈检测到这种情况时，会建议停用或取消黑阈。
> 或许应该在通知里说明得更详细一点。

可是把手机里软件都取消黑阈了那根没用黑阈有啥区别。。

**Comment by jeffreymor** [comment]
我也是这种情况，一加7p 氢os Android 10.0，而且是只有Telegram和Instagram最近才出现这种情况，以前都是好好的

**Comment by madokajinan** [comment]
三星s10e也有相同的情况，建议停用黑域...
![Screenshot_20200403-224434_Twitter](https://user-images.githubusercontent.com/63118236/78386837-e0207800-7610-11ea-88f8-b8deeea4bc13.jpg)

**Comment by liudongmiao** [comment]
你要黑阈黑阈，我也没办法。

只要有通知，黑阈就会通知你；而你又黑阈了黑阈，通知你又造成黑阈被启动。

**Comment by liudongmiao** [comment]
此情况，表示事实上：
- 该应用被打开，并且被黑阈强行停止

请：
- 调整策略，不要黑阈或者停用
- 或者关闭此通知，点按 7 次 黑阈 - 设置 - 系统状态，关闭“强行停止检查”

否则：
- 不断的启动与强行停止，只会更加耗电

之前：
- 也有该操作，只是没有通知你而已
