### ISSUE TITLE
请求增加对安卓电视的支持

### ISSUE THREAD

**Issue by tratratratra** [brevent/Brevent#638]
现在国产手机一般都自带后台管理，但是电视硬件性能差、安卓版本低还没有后台管理，经常卡顿。我的索尼电视装上最新版本黑阈后提示黑阈服务已经运行，但标题栏右上角没有任何按钮显示，点左上角菜单按钮也没有反映，安卓电视不支持滑动操作，希望能增加对安卓电视的适配。

**Comment by liudongmiao** [comment]
少装应用吧～

界面适配不是我强项。

**Comment by QAQQIAOY** [comment]
好人才 这么说车子也可以装一个 安卓底层的话

**Comment by liudongmiao** [comment]
没有计划。
