### ISSUE TITLE
设置里的自我诊断

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#64]
每 15 分钟检查黑域服务，必要时收集日志

只有偶然不正常停止时，才需要开启。开启之后，将自动把黑域加入电池优化白名单

请问这里“不正常停止”是指黑域服务本身不正常退出，还是指黑域不正常停止应用？”

**Comment by GithubApkUser** [comment]
2)“必要时收集日志”是指黑域自动采集日志发送，还是要用户手动发送呢？是出问题了就发送，还是每隔15分钟发送？
3)这个电池优化白名单，对某些强制doze/省电模式导致的网络问题有效果吗？

建议描述更改的更清楚
“每隔15分钟检查黑域服务，不正常停止时提示收集日志

只有服务不稳定时才需要开启。开启之后，将自动把黑域加入电池优化白名单”

**Comment by liudongmiao** [comment]
1. 没有任何计划更新。如果你有更好的提示，直接 pr 就好。
一句话，直接更新，大家看效果。

2. 都叫自我诊断了，你觉得呢？

3. 你自己试试不就知道了？
如果你觉得一个应用，能够不经用户手，直接发送日志。

看到酷安用户就头疼，被喷怕了，换个帐号来吧。

**Comment by liudongmiao** [comment]
如果有翻译觉得不好，直接提交更新，不要有疑问。
