### ISSUE TITLE
为什么重启后 fcm同步后的应用电池变成了不优化

### ISSUE THREAD

**Issue by waduhek1997** [brevent/Brevent#640]
如题 黑阈后开启了允许同步（fcm），  重启后， 就变成了电池优化白名单。

**Comment by waduhek1997** [comment]
开机不自启动黑阈服务，就没这个问题

**Comment by waduhek1997** [comment]
开机自启后， 所以同步后过的软件都变成了电池优化白名单

**Comment by liudongmiao** [comment]
允许同步，隐含这个意思。

而且，也就只有你家 ROM 才会初始化 电池优化名单。
