### ISSUE TITLE
found brevent_daemon, pid: 8135

### ISSUE THREAD

**Issue by singsing215** [brevent/Brevent#641]
03-28 17:22:17.557 28864 28872 I BreventServer: remove package com.android.networksettings.overlay.ct
03-28 17:22:17.561 28864 28872 I BreventServer: remove package com.android.phone.overlay.razer.common
03-28 17:22:17.569 28864 28872 I BreventServer: remove package com.razerzone.defaultlauncheroverlay
03-28 17:22:17.582 28864 28872 I BreventServer: remove package com.android.systemui.overlay.razer.common
03-28 17:22:17.587 28864 28872 I BreventServer: remove package com.android.omadm.dmservice.overlay.razer.aura
03-28 17:22:17.595 28864 28872 I BreventServer: remove package com.android.settings.overlay.razer.aura
03-28 17:22:17.603 28864 28872 I BreventServer: remove package com.android.settings.intelligence.overlay.razer.common
03-28 17:22:17.608 28864 28872 I BreventServer: remove package com.android.cellbroadcastreceiver.overlay.common
03-28 17:22:17.618 28864 28872 I BreventServer: remove package android.overlay.razer.aura
03-28 17:22:17.623 28864 28872 I BreventServer: remove package com.android.bluetooth.overlay.common
03-28 17:22:17.642 28864 28864 I BreventServer: check and brevent
03-28 17:22:17.662 28864 28864 W BreventServer: no enqueue event, use dump to check notification
03-28 17:22:18.207 28864 28881 I BreventServer: support upgrade: true
03-28 17:22:18.209 28864 28864 I BreventServer: received first event

**Comment by liudongmiao** [comment]
It just means brevent should be working.
