### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by aviraxp** [brevent/Brevent#643]
![Screenshot_20200331-130608](https://user-images.githubusercontent.com/18079988/77989300-f8626f80-7350-11ea-8c15-785861ef0826.jpg)

**Comment by liudongmiao** [comment]
这个和具体的版本有关...要么就是不适配全面屏。

**Comment by liudongmiao** [comment]
尝试适配了下：https://jianyu.io/br/alpha/

**Comment by aviraxp** [comment]
解决。
