### ISSUE TITLE
新版黑域登录问题

### ISSUE THREAD

**Issue by a37324614** [brevent/Brevent#644]
更新了新版黑域 和微信 显示无法登陆 提示 版本太低或者签名错误  我确定我微信是官方最新版 还有黑域也检查更新过了

**Comment by liudongmiao** [comment]
不要试图使用任何方式 hack 你的系统。

**Comment by a37324614** [comment]
得了吧 更新下微信就好了

**Comment by angelmengg** [comment]
我把微信装在太极框架里边，同样不能登录，因为还想用微x 望解决

**Comment by liudongmiao** [comment]
@angelmengg 黑阈不会支持非正常使用微信的方式
