### ISSUE TITLE
支持FCM的应用设置允许同步后被加入电池优化白名单

### ISSUE THREAD

**Issue by liu33851809** [brevent/Brevent#645]
手机中支持FCM的应用设置允许同步后也全部被加入电池优化白名单，即使手动取消了白名单每次手机重启仍然会会被加回，不知是否是正常情况？

手机是pixel3a原版系统，使用 magisk root。
google/sargo/sargo:10/QQ2A.200305.002/6138846:user/release-keys
黑阈 4.1.8.2(Android zh_CN-10) Google play 版

**Comment by liu33851809** [comment]
[logs-v4.1.8.2-20200407.1035.zip](https://github.com/brevent/Brevent/files/4441751/logs-v4.1.8.2-20200407.1035.zip)

**Comment by liudongmiao** [comment]
允许同步，就是会这样。
