### ISSUE TITLE
小米10 root模式下启动失败

### ISSUE THREAD

**Issue by xiaotianxt** [brevent/Brevent#647]
logs：
[shproc] Process[pid=30707, hasExited=false]
05-01 18:25:43.170 29649 29699 I BreventServer: ignore overlay package: com.android.internal.display.cutout.emulation.corner
05-01 18:25:43.170 29649 29699 I BreventServer: ignore overlay package: com.android.internal.display.cutout.emulation.double
05-01 18:25:43.172 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon.square
05-01 18:25:43.173 29649 29699 I BreventServer: ignore overlay package: com.android.internal.systemui.navbar.gestural_wide_back
05-01 18:25:43.173 29649 29699 I BreventServer: ignore overlay package: com.android.theme.color.cinnamon
05-01 18:25:43.174 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.rounded.systemui
05-01 18:25:43.176 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.rounded.android
05-01 18:25:43.177 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.circular.themepicker
05-01 18:25:43.177 29649 29699 I BreventServer: ignore overlay package: com.android.systemui.icon.overlay
05-01 18:25:43.177 29649 29699 I BreventServer: ignore overlay package: android.qvaoverlay.common
05-01 18:25:43.178 29649 29699 I BreventServer: ignore overlay package: com.android.settings.overlay.miui
05-01 18:25:43.178 29649 29699 I BreventServer: ignore overlay package: android.overlay.common
05-01 18:25:43.179 29649 29699 I BreventServer: ignore overlay package: com.android.internal.display.cutout.emulation.tall
05-01 18:25:43.179 29649 29699 I BreventServer: ignore overlay package: com.android.theme.color.black
05-01 18:25:43.179 29649 29699 I BreventServer: ignore overlay package: com.android.theme.color.green
05-01 18:25:43.179 29649 29699 I BreventServer: ignore overlay package: com.android.theme.color.ocean
05-01 18:25:43.179 29649 29699 I BreventServer: ignore overlay package: com.android.theme.color.space
05-01 18:25:43.179 29649 29699 I BreventServer: ignore overlay package: com.android.internal.systemui.navbar.threebutton
05-01 18:25:43.180 29649 29699 I BreventServer: ignore overlay package: com.android.systemui.notch.overlay
05-01 18:25:43.181 29649 29699 I BreventServer: ignore overlay package: android.miui.overlay
05-01 18:25:43.181 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.rounded.launcher
05-01 18:25:43.182 29649 29699 I BreventServer: ignore overlay package: com.android.internal.systemui.navbar.twobutton
05-01 18:25:43.182 29649 29699 I BreventServer: ignore overlay package: android.overlay.target
05-01 18:25:43.183 29649 29699 I BreventServer: ignore overlay package: com.android.internal.systemui.navbar.gestural_extra_wide_back
05-01 18:25:43.183 29649 29699 I BreventServer: ignore overlay package: com.miui.systemui.devices.overlay
05-01 18:25:43.184 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.filled.settings
05-01 18:25:43.184 29649 29699 I BreventServer: ignore overlay package: com.google.android.overlay.modules.ext.services
05-01 18:25:43.184 29649 29699 I BreventServer: ignore overlay package: com.android.systemui.gesture.line.overlay
05-01 18:25:43.184 29649 29699 I BreventServer: ignore overlay package: com.miui.documentsuioverlay
05-01 18:25:43.185 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.circular.settings
05-01 18:25:43.185 29649 29699 I BreventServer: ignore overlay package: com.android.systemui.overlay.miui
05-01 18:25:43.185 29649 29699 I BreventServer: ignore overlay package: com.google.android.overlay.gmsconfig
05-01 18:25:43.186 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon.teardrop
05-01 18:25:43.186 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.filled.systemui
05-01 18:25:43.186 29649 29699 I BreventServer: ignore non-installed package: com.google.android.packageinstaller
05-01 18:25:43.187 29649 29699 I BreventServer: ignore instant package: com.dropout.ballgamegp0
05-01 18:25:43.187 29649 29699 I BreventServer: ignore overlay package: com.android.phone.overlay.common
05-01 18:25:43.187 29649 29699 I BreventServer: ignore overlay package: com.android.carrierconfig.overlay.common
05-01 18:25:43.187 29649 29699 I BreventServer: ignore overlay package: android.aosp.overlay
05-01 18:25:43.187 29649 29699 I BreventServer: ignore overlay package: com.android.systemui.overlay.common
05-01 18:25:43.187 29649 29699 I BreventServer: ignore overlay package: com.android.server.telecom.overlay.common
05-01 18:25:43.188 29649 29699 I BreventServer: ignore overlay package: com.android.theme.font.notoserifsource
05-01 18:25:43.188 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.filled.android
05-01 18:25:43.188 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.circular.systemui
05-01 18:25:43.190 29649 29699 I BreventServer: ignore overlay package: com.android.systemui.navigation.bar.overlay
05-01 18:25:43.190 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon.squircle
05-01 18:25:43.190 29649 29699 I BreventServer: ignore instant package: com.lamington.spooky
05-01 18:25:43.191 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.filled.launcher
05-01 18:25:43.191 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.circular.launcher
05-01 18:25:43.191 29649 29699 I BreventServer: ignore overlay package: com.miui.systemui.carriers.overlay
05-01 18:25:43.191 29649 29699 I BreventServer: ignore overlay package: com.miui.systemui.overlay.devices.android
05-01 18:25:43.191 29649 29699 I BreventServer: ignore overlay package: com.xiaomi.bluetooth.overlay
05-01 18:25:43.192 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.filled.themepicker
05-01 18:25:43.192 29649 29699 I BreventServer: ignore non-installed package: com.miui.greenguard
05-01 18:25:43.192 29649 29699 I BreventServer: ignore overlay package: com.android.internal.systemui.navbar.gestural
05-01 18:25:43.192 29649 29699 I BreventServer: ignore overlay package: com.android.theme.color.orchid
05-01 18:25:43.192 29649 29699 I BreventServer: ignore overlay package: com.android.theme.color.purple
05-01 18:25:43.194 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon.roundedrect
05-01 18:25:43.194 29649 29699 I BreventServer: ignore overlay package: com.android.internal.systemui.navbar.gestural_narrow_back
05-01 18:25:43.194 29649 29699 I BreventServer: ignore overlay package: com.android.cellbroadcastreceiver.overlay.common
05-01 18:25:43.194 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.rounded.settings
05-01 18:25:43.194 29649 29699 I BreventServer: ignore overlay package: com.android.bluetooth.overlay.common
05-01 18:25:43.194 29649 29699 I BreventServer: ignore overlay package: com.android.theme.icon_pack.circular.android
05-01 18:25:46.377 29738 29738 I BreventLoader: sdk: 29
05-01 18:25:46.980 29747 29747 I BreventServer: args: [10, me.piebridge.brevent, 1588328746, false]
05-01 18:25:47.016 29747 29747 I BreventServer: server log name: server.20200501.1825.29747.txt
05-01 18:25:47.017 29747 29747 I BreventServer: starting Brevent Server 4.1.8.3
05-01 18:25:47.055 29747 29747 I BreventServer: app_suspended_default_message, orig: %1$s目前无法使用。该应用是由%2$s所管理。, now: %1$s目前无法使用。该应用是由黑阈所管理。
05-01 18:25:47.055 29747 29747 I BreventServer: brevent version: 4.1.8.3
05-01 18:25:47.057 29747 29747 I BreventServer: add sigcont handler
05-01 18:25:47.060 29747 29747 I BreventServer: sdk: 29, genuine: 0
05-01 18:25:47.061 29747 29747 I BreventServer: brevent user: 0, uid: 2000
05-01 18:25:47.179 29747 29747 I BreventServer: core apps: {com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.miui.packageinstaller, com.qualcomm.qti.uceShimService, com.android.mms.service, vendor.qti.hardware.cacert.server, com.qualcomm.qti.telephonyservice, com.miui.systemAdSolution, android.qvaoverlay.common, com.android.settings.overlay.miui, android.overlay.common, com.wapi.wapicertmanage, android, android.miui.overlay, com.android.ons, org.codeaurora.ims, com.qualcomm.qti.dynamicddsservice, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.incallui, com.android.inputdevices, com.android.systemui.overlay.miui, com.android.server.telecom, com.android.phone.overlay.common, com.qualcomm.qti.qtisystemservice, android.aosp.overlay, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.proxyhandler, com.xiaomi.misettings, com.zeusis.HydraService, com.google.android.documentsui, com.miui.securityinputmethod, com.android.settings, com.qualcomm.qti.cne, com.modemdebug, com.android.phone, com.android.shell, com.qualcomm.qti.seccamservice, com.android.location.fused, com.android.systemui, com.qualcomm.qti.poweroffalarm, com.android.permissioncontroller}
05-01 18:25:47.179 29747 29747 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.settings.overlay.miui, android, com.android.ons, com.android.providers.settings, com.android.incallui, com.android.inputdevices, com.android.systemui.overlay.miui, com.android.server.telecom, com.android.phone.overlay.common, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.android.permissioncontroller}
05-01 18:25:47.180 29747 29747 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared}
05-01 18:25:47.181 29747 29747 I BreventServer: installer: com.miui.packageinstaller
05-01 18:25:47.188 29747 29747 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
05-01 18:25:47.206 29747 29747 I BreventServer: com.google.firebase.MESSAGING_EVENT: {com.mobisystems.office, com.samsung.android.gearoplugin, com.google.android.youtube, com.safervpn.android, com.catchingnow.clipsync, com.android.vending, com.microsoft.skydrive, com.tencent.mm, com.lastpass.lpandroid, droom.sleepIfUCan, org.thunderdog.challegram, com.adobe.cc, net.pulsesecure.pulsesecure, com.microsoft.office.officehubrow, com.teamviewer.teamviewer.market.mobile, com.valvesoftware.android.steam.community, com.adobe.psmobile, com.taobao.idlefish, com.adobe.lrmobile, com.microsoft.todos}
05-01 18:25:47.209 29747 29747 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {com.github.shadowsocks, com.samsung.android.gearoplugin, com.google.android.youtube, com.safervpn.android, org.swiftapps.swiftbackup, com.google.android.googlequicksearchbox, com.google.android.apps.podcasts, com.smzdm.client.android, com.catchingnow.clipsync, org.zwanoo.android.speedtest, com.android.vending, com.microsoft.skydrive, com.tencent.mm, android, cc.forestapp, me.piebridge.brevent, com.lastpass.lpandroid, com.clipboard.manager, droom.sleepIfUCan, org.thunderdog.challegram, com.adobe.cc, com.androidfung.drminfo, com.nstudio.calc.casio.business, com.adobe.scan.android, com.android.chrome, com.google.android.gms, com.google.android.gsf, com.google.android.apps.walletnfcrel, com.google.android.apps.photos, com.google.android.calendar, net.pulsesecure.pulsesecure, com.microsoft.office.officehubrow, com.teamviewer.teamviewer.market.mobile, com.valvesoftware.android.steam.community, com.adobe.psmobile, pl.solidexplorer2, com.taobao.idlefish, com.app.pornhub, com.adobe.lrmobile, com.microsoft.todos}
05-01 18:25:47.209 29747 29747 I BreventServer: fcm: {com.samsung.android.gearoplugin, com.google.android.youtube, com.safervpn.android, com.catchingnow.clipsync, com.android.vending, com.microsoft.skydrive, com.tencent.mm, com.lastpass.lpandroid, droom.sleepIfUCan, org.thunderdog.challegram, com.adobe.cc, net.pulsesecure.pulsesecure, com.microsoft.office.officehubrow, com.teamviewer.teamviewer.market.mobile, com.valvesoftware.android.steam.community, com.adobe.psmobile, com.taobao.idlefish, com.adobe.lrmobile, com.microsoft.todos}
05-01 18:25:47.221 29747 29747 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 102
05-01 18:25:47.234 29747 29747 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
05-01 18:25:47.234 29747 29747 I BreventServer: disabling: {}
05-01 18:25:47.235 29747 29747 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 9
05-01 18:25:47.235 29747 29747 I BreventServer: ppid: 29742
05-01 18:25:47.235 29747 29747 I BreventServer: checking standby, sdk: 29
05-01 18:25:47.237 29747 29747 I BreventServer: init widgets
05-01 18:25:47.242 29747 29747 I BreventServer: init notifications
05-01 18:25:47.307 29747 29747 I BreventServer: recents package name: com.miui.home
05-01 18:25:47.338 29747 29747 I BreventServer: use com.android.cts.priv.ctsshim to check upgrade and disable
05-01 18:25:47.338 29747 29747 I BreventServer: update com.android.cts.priv.ctsshim to disabled-user, new state: disabled-user
05-01 18:25:47.339 29747 29747 I BreventServer: update com.android.cts.priv.ctsshim to enabled, new state: enabled
05-01 18:25:47.341 29747 29747 I BreventServer: use com.miui.gallery to check suspend
05-01 18:25:47.347 29747 29747 I BreventServer: package com.miui.gallery suspended state: true
05-01 18:25:47.348 29747 29747 I BreventServer: package com.miui.gallery suspended state: false
05-01 18:25:47.349 29747 29747 I BreventServer: uid: 10274
05-01 18:25:47.359 29747 29747 I BreventServer: registerProcessObserver
05-01 18:25:47.362 29747 29811 I BreventServer: system_server: 1741
05-01 18:25:47.362 29747 29811 I BreventServer: system_server: 1741, now: 1588328747
05-01 18:25:47.369 29747 29747 I BreventServer: registerUidObserver
05-01 18:25:47.369 29747 29747 I BreventServer: support standby: true
05-01 18:25:47.369 29747 29747 I BreventServer: support stopped: true
05-01 18:25:47.369 29747 29747 I BreventServer: support upgrade: checking
05-01 18:25:47.369 29747 29747 I BreventServer: support appops: true
05-01 18:25:47.369 29747 29747 I BreventServer: support disable: true
05-01 18:25:47.369 29747 29747 I BreventServer: support suspend: true
05-01 18:25:47.369 29747 29747 I BreventServer: Brevent Server 4.1.8.3 started
05-01 18:25:47.370 29747 29747 I BreventServer: sent 10 to 29742
05-01 18:25:49.402 29747 29811 I BreventServer: support upgrade: true
05-01 18:25:50.395 29747 29747 I BreventServer: brevent disabled packages: {}
05-01 18:25:50.399 29747 29771 I BreventServer: has notification event, use dump to check notification
05-01 18:25:50.407 29747 29747 I BreventServer: received first event
05-01 18:25:50.430 29747 29771 E BreventServer: cannot parse media.audio_flinger
05-01 18:25:50.715 29747 29771 I BreventServer: has notification event, use dump to check notification
05-01 18:25:51.039 29747 29747 I BreventServer: support upgrade: true (native)
05-01 18:25:51.044 29747 29747 I BreventServer: pending check and brevent(notificationEvents)
05-01 18:25:51.588 29747 29747 I BreventServer: check and brevent
05-01 18:26:27.571 29747 29771 I BreventServer: onForegroundActivitiesChanged, pid: 29649, uid: 10274
05-01 18:26:27.643 29747 30512 I BreventServer: sent binder, message: onForegroundActivitiesChanged
05-01 18:26:32.832 29747 29771 I BreventServer: new command: logcat -b main -d -s BreventLoader BreventServer
05-01 18:26:32.844 29747 29771 I BreventServer: command response, total: 0
05-01 18:26:33.247 29747 29769 I BreventServer: command response, total: 45
05-01 18:26:33.651 29747 29769 I BreventServer: command response, total: 0
05-01 18:26:34.057 29747 29769 I BreventServer: command response, total: 15781
05-01 18:26:45.647 29747 29769 I BreventServer: new command: logcat -b main -d -s BreventLoader BreventServer
05-01 18:26:45.663 29747 29769 I BreventServer: command response, total: 0
[shproc] Process[pid=30707, hasExited=true, exitcode=0]
以上来自logcat -b main -d -s BreventLoader BreventServer
[shproc] Process[pid=30938, hasExited=false]
05-01 18:07:42.862  1342  1342 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1342 (init), pid 1342 (init)
05-01 18:07:42.928  1342  1342 F libc    : crash_dump helper failed to exec
[shproc] Process[pid=30938, hasExited=true, exitcode=0]
以上来自logcat -b crash -d

**Comment by liudongmiao** [comment]
日志看起来正常

**Comment by liudongmiao** [comment]
升级最新版，有问题再反馈吧。
