### ISSUE TITLE
三星tabS4只要一息屏就需要重新输入adb指令

### ISSUE THREAD

**Issue by Alexsu26** [brevent/Brevent#648]
输入一次adb命令后，如果一直亮屏就没问题；息屏再打开就会提示服务未启动。应该怎么设置啊？
开发者模式中设置了默认USB配置为MIDI但是每次连接电脑还是会变成传输文件。

**Comment by angelmengg** [comment]
三星s10＋ 系统one ui 2.1,同样情况，望解决

**Comment by liudongmiao** [comment]
没有好办法，关闭 issues。
