### ISSUE TITLE
黑域临时启用快捷方式不可用问题反馈

### ISSUE THREAD

**Issue by szkzn** [brevent/Brevent#649]
如图，正常使用的情况下，添加的临时启用快捷方式突然全部变成没有名字的黑域图标快捷方式，并且无法打开，只能通过黑域进去点击具体应用，临时启用才可以打开。
黑域版本：4.1.8.3
系统：安卓9，EMUI 9.1
无root，无解锁BOOTLOADER，无框架
adb激活的黑域
尝试操作：重启系统，重新激活黑域
图2是没重启系统前的截图，图1是重启系统后的截图
![Screenshot_20200505_104508_com huawei android launcher](https://user-images.githubusercontent.com/30108874/81031313-6f45d780-8ebe-11ea-874a-d9cb03a5e07e.jpg)
![Screenshot_20200505_104255_com huawei android launcher](https://user-images.githubusercontent.com/30108874/81031318-72d95e80-8ebe-11ea-89ea-196ff7d3fa66.jpg)

**Comment by liudongmiao** [comment]
看起来，是 EMUI 兼容性问题，后续没有接到此类报告。
