### ISSUE TITLE
Vivo Nex 3 黑域息屏需重新adb

### ISSUE THREAD

**Issue by wsmmsh** [brevent/Brevent#653]
Vivo nex3（Android版本：10）使用黑域后，adb激活后息屏后仍需重新激活，并且使用VVFGAA激活后仍会出现此种情况，不断提示需重新激活（如图）。

![微信图片_20200612101002](https://user-images.githubusercontent.com/16263676/84457806-2855b980-ac96-11ea-91e2-f5ad4a34e68c.jpg)

**Comment by liudongmiao** [comment]
正常情况，就是找个 不掉线 的模式，也不要开启 网络调试。

https://support.qq.com/products/41738/faqs/39058
