### ISSUE TITLE
Android 11上不可用

### ISSUE THREAD

**Issue by ipcjs** [brevent/Brevent#654]
最新的Android 11 Beta版下，开启服务后依然弹提示开启服务的提示窗，如图：
![image](https://user-images.githubusercontent.com/4396864/84573434-f8600080-add2-11ea-884d-5412acd404c9.png)

![image](https://user-images.githubusercontent.com/4396864/84573418-e41c0380-add2-11ea-8cce-d6ea92efdfd2.png)

**Comment by liudongmiao** [comment]
android 11 beta 下，4.1.9 应该直接崩溃才对...

**Comment by liudongmiao** [comment]
请升级至最新 beta 版  4.1.12
