### ISSUE TITLE
一直通知栏提示建议停用XXX

### ISSUE THREAD

**Issue by onlyJinx** [brevent/Brevent#656]
这个除了使用系统的屏蔽通知还有其他办法吗？
![Screenshot_20200618-185240_CoolApk](https://user-images.githubusercontent.com/21324835/85012560-c6191f00-b195-11ea-869a-57f898231152.jpg)

**Comment by liudongmiao** [comment]
黑阈 - 设置 - 点按 7 次系统状态，关闭“强行停止检查”。
