### ISSUE TITLE
动态GMS功能是如何工作的，我手机里显示的运行时间一直停留在00:07

### ISSUE THREAD

**Issue by KkemChen** [brevent/Brevent#657]
如题，我想知道动态gms功能是如何工作的，怎样知道他什么时候处于动态停用状态。

**Comment by liudongmiao** [comment]
动态 GMS，针对 GMS 单独处理。

打开 GMS 应用时，会启用 GMS；所有 GMS 应用全部不再使用时，会停用 GMS。
默认 GMS 应用为 Play 商店，你可以搜索 `-f`，然后选择应用并标识 GMS 应用。

**Comment by jiang-yuan** [comment]
> 动态 GMS，针对 GMS 单独处理。
> 
> 打开 GMS 应用时，会启用 GMS；所有 GMS 应用全部不再使用时，会停用 GMS。 默认 GMS 应用为 Play 商店，你可以搜索 `-f`，然后选择应用并标识 GMS 应用。

所以这个只是对非常少数的 用户软件 类的google应用(你的意思说只有Play商店)有用,对系统软件 类的google应用没用?
