### ISSUE TITLE
启动黑域服务报错

### ISSUE THREAD

**Issue by evinnnn** [brevent/Brevent#658]
PS D:\download\assets> adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server..started, pid: 1706
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> /system/bin/logcat -b crash -t '07-03 15:49:45.000' -d
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '07-03 15:49:45.000' -d -s BreventLoader BreventServer
07-03 15:49:45.503  1698  1698 D BreventLoader: loader path: /data/app/me.piebridge.brevent-Ijt2YGpbR2HnXnxasU6XpQ==/base.apk
07-03 15:49:46.220  1706  1706 W BreventServer: Can't find ActivityManager.StackId.FREEFORM_WORKSPACE_STACK_ID
07-03 15:49:46.221  1706  1706 D BreventServer: get service: package
07-03 15:49:46.222  1706  1706 D BreventServer: args: [10]
07-03 15:49:46.222  1706  1706 I BreventServer: signal: 10
07-03 15:49:46.243  1706  1706 I BreventServer: starting Brevent Server 2.1.2
07-03 15:49:46.244  1706  1706 W BreventServer: Can't find ActivityManager.RECENT_IGNORE_HOME_STACK_TASKS nor ActivityManager.RECENT_IGNORE_HOME_AND_RECENTS_STACK_TASKS
07-03 15:49:46.244  1706  1706 W BreventServer: Can't find ActivityManager.RECENT_INCLUDE_PROFILES
07-03 15:49:46.244  1706  1706 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
07-03 15:49:46.244  1706  1706 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
07-03 15:49:46.249  1706  1706 W BreventServer: Can't find ActivityManager.StackId.FREEFORM_WORKSPACE_STACK_ID
07-03 15:49:46.250  1706  1706 D BreventServer: get service: package
07-03 15:49:46.250  1706  1706 W BreventServer: version unmatched, running: 2.1.2, installed: brevent
07-03 15:49:46.256  1706  1706 I BreventServer: brevent user: 0, uid: 2000
07-03 15:49:46.258  1706  1706 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-03 15:49:46.278  1706  1706 I BreventServer: loading brevent list
07-03 15:49:46.279  1706  1706 I BreventServer: loading brevent conf
07-03 15:49:46.282  1706  1706 D BreventServer: get service: appwidget
07-03 15:49:46.308  1706  1706 D BreventServer: get service: usagestats
07-03 15:49:46.768  1706  1721 I BreventServer: Brevent Event, now: 1593762586
07-03 15:49:46.769  1706  1706 D BreventServer: check and brevent
07-03 15:49:46.771  1706  1706 D BreventServer: get service: notification
07-03 15:49:46.788  1706  1721 I BreventServer: system_server: 1348, now: 1593762586
07-03 15:49:46.874  1706  1706 D BreventServer: get service: activity
07-03 15:49:46.901  1706  1706 D BreventServer: get service: alarm
07-03 15:49:46.908  1706  1706 D BreventServer: get service: wallpaper
07-03 15:49:46.925  1706  1706 E BreventServer: Can't get running app processes
07-03 15:49:46.925  1706  1706 E BreventServer: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo com.android.server.am.ProcessRecord.info' on a null object reference
07-03 15:49:46.925  1706  1706 E BreventServer:         at android.os.Parcel.createException(Parcel.java:1956)
07-03 15:49:46.925  1706  1706 E BreventServer:         at android.os.Parcel.readException(Parcel.java:1918)
07-03 15:49:46.925  1706  1706 E BreventServer:         at android.os.Parcel.readException(Parcel.java:1868)
07-03 15:49:46.925  1706  1706 E BreventServer:         at android.app.IActivityManager$Stub$Proxy.getRunningAppProcesses(IActivityManager.java:5309)
07-03 15:49:46.925  1706  1706 E BreventServer:         at me.piebridge.brevent.server.e.b(HideApi.java:112)
07-03 15:49:46.925  1706  1706 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1993)
07-03 15:49:46.925  1706  1706 E BreventServer:         at me.piebridge.brevent.server.BreventServer.j(BreventServer.java:789)
07-03 15:49:46.925  1706  1706 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:2101)
07-03 15:49:46.925  1706  1706 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2218)
07-03 15:49:46.925  1706  1706 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
07-03 15:49:46.925  1706  1706 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2316)
07-03 15:49:46.925  1706  1706 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-03 15:49:46.925  1706  1706 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:384)
07-03 15:49:46.925  1706  1706 E BreventServer: Caused by: android.os.RemoteException: Remote stack trace:
07-03 15:49:46.925  1706  1706 E BreventServer:         at com.android.server.am.ActivityManagerService.getRunningAppProcesses(ActivityManagerService.java:17952)
07-03 15:49:46.925  1706  1706 E BreventServer:         at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1011)
07-03 15:49:46.925  1706  1706 E BreventServer:         at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3826)
07-03 15:49:46.925  1706  1706 E BreventServer:         at android.os.Binder.execTransact(Binder.java:752)
07-03 15:49:46.925  1706  1706 E BreventServer:
07-03 15:49:46.958  1698  1698 E BreventLoader: worker 1706 exited with status 1
07-03 15:49:46.959  1698  1698 D BreventLoader: signal arrived, update: 0
07-03 15:49:46.959  1694  1694 D BreventLoader: worker 1698 exited with status 0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by vvb2060** [comment]
不对旧版提供任何支持，请使用最新版。
https://brevent.jianyu.io/

**Comment by evinnnn** [comment]
@vvb2060 黑域需要后台运行吗，我点了返回按钮，查看任务列表黑域就没了
