### ISSUE TITLE
咨询关于动态GMS的问题

### ISSUE THREAD

**Issue by qyd0801** [brevent/Brevent#659]
想咨询动态GMS的使用方法，开启选项后黑域play商店吗

**Comment by liudongmiao** [comment]
动态 GMS，针对 GMS 单独处理。

打开 GMS 应用时，会启用 GMS；所有 GMS 应用全部不再使用时，会停用 GMS。
默认 GMS 应用为 Play 商店，你可以搜索 `-f`，然后选择应用并标识 GMS 应用。
