### ISSUE TITLE
無法使用

### ISSUE THREAD

**Issue by stillsteven** [brevent/Brevent#66]
--- crash start ---
[command] logcat -b crash -t '08-28 16:23:53.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-28 16:23:53.000' -d -s BreventLoader BreventServer
08-28 16:23:54.749 14714 14714 D BreventLoader: line: package:/data/app/me.piebridge.brevent-2/base.apk
08-28 16:23:54.749 14714 14714 D BreventLoader: 
08-28 16:23:54.780 14714 14714 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
08-28 16:23:55.995 14739 14739 D BreventServer: get service: package
08-28 16:23:55.996 14739 14739 D BreventServer: args: [10, me.piebridge.brevent]
08-28 16:23:55.996 14739 14739 I BreventServer: signal: 10
08-28 16:23:56.035 14739 14739 I BreventServer: starting Brevent Server 2.1.6o
08-28 16:23:56.216 14739 14739 D BreventServer: get service: package
08-28 16:23:56.218 14739 14739 I BreventServer: brevent user: 0, uid: 0
08-28 16:23:56.219 14739 14739 I BreventServer: brevent data directory: /data/user/0/com.android.shell
08-28 16:23:56.253 14739 14739 I BreventServer: loading brevent list
08-28 16:23:56.260 14739 14739 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 15
08-28 16:23:56.266 14739 14739 I BreventServer: loading brevent conf
08-28 16:23:56.271 14739 14739 D BreventServer: get service: appwidget
08-28 16:23:56.272 14739 14739 E BreventServer: Cannot dump appwidget(brevent dumpsys dead)
08-28 16:23:56.272 14739 14739 E BreventServer: for more information, refer https://github.com/brevent/Brevent/issues/17
08-28 16:23:56.302 14714 14714 E BreventLoader: worker 14739 exited with status 1
08-28 16:23:56.302 14714 14714 D BreventLoader: signal arrived, update: 0
08-28 16:23:56.303 14700 14700 D BreventLoader: worker 14714 exited with status 0
--- brevent end ---

**Comment by liudongmiao** [comment]
明明有提示，你直接把提示去掉。
明明有给链接，还要自己创建一下。

#17
