### ISSUE TITLE
moto Z国行 7.0 未解锁未root 黑域在后台白名单中会过一段时间丢失配置单然后需要重新配置

### ISSUE THREAD

**Issue by Adiscs** [brevent/Brevent#66]
如题 不是很懂 手机也没有重启或关机
[crash log.txt](https://github.com/brevent/Brevent/files/1108373/crash.log.txt)

**Comment by liudongmiao** [comment]
怀疑都没有正常启动。请尝试最新测试版：https://piebridge.me/br/next/

**Comment by liudongmiao** [comment]
尝试新版之后，还有问题再提吧。
