### ISSUE TITLE
一加8开启失败

### ISSUE THREAD

**Issue by shentaibai** [brevent/Brevent#661]
系统版本10.5.7 
开启的时候显示网络连接失败

**Comment by vvb2060** [comment]
需要更多信息，请上传日志。应用内反馈，然后拖拽压缩包上传到GitHub。

**Comment by shentaibai** [comment]
OnePlus/OnePlus8_CH/OnePlus8:10/QKQ1.191222.002/2006300106:user/release-keys

无法连接，请确认网络及调试端口。
 很抱歉没有找到日志入口，

**Comment by liudongmiao** [comment]
之前看过，就是网络调试真的商品没开。

日志 入口：黑阈 - 反馈 - 日志（需要安装邮件应用）。
