### ISSUE TITLE
Cannot auto unbrevent unlaunchable apps

### ISSUE THREAD

**Issue by MacgyverJohnson** [brevent/Brevent#663]
Dear dev, @liudongmiao 
I would like to thank u for creating such an amazing app for the stock rom users. Hope you and ur family are doing well amongst the pandemic.

Brevent latest beta as of now cannot auto unbrevent unlaunchable apps... Everytime i selected ok on the notification.. nothing happens...this notification pops up every brevent launch.... Clicking cancel does the same thing...
Using samsung a505f android 10 stock rom ...
![Screenshot_20200814-000139_Brevent](https://user-images.githubusercontent.com/17729946/90170602-1beafb80-ddc2-11ea-8a90-7dbce87623b4.jpg)

**Comment by liudongmiao** [comment]
tap "OK".

Or, if you have paid, tap "Cancel" to ignore.
