### ISSUE TITLE
Auto uninstall apps

### ISSUE THREAD

**Issue by MacgyverJohnson** [brevent/Brevent#664]
Brevent is auto uninstalling apps...like last night it uninstalled 3apps of mine...how frustrating...I will lose those data forever....Also brevent was disabled from settings all this time...
![Screenshot_20200814-083937_Brevent](https://user-images.githubusercontent.com/17729946/90208064-b6baf880-de09-11ea-92bc-4597a29c46a0.jpg)

![Screenshot_20200814-083535_Brevent](https://user-images.githubusercontent.com/17729946/90207946-6b084f00-de09-11ea-824b-af9a98bd82de.jpg)

**Comment by liudongmiao** [comment]
Brevent never auto uninstall any apps.
