### ISSUE TITLE
[Enhancement] Please provide a way of purchasing Brefoil for devices without gapps

### ISSUE THREAD

**Issue by astarq** [brevent/Brevent#666]
I don't know if this is actually implemented already. It would be extremely useful for people with phones which do not have Google Play Services, or for those who choose not to use them for their own reasons.

One way to do this would be to include offline codes in updates to the app, which you would then provide to users if they contacted you, and then users could pay using Paypal, Bitcoin, you name it... I'm not sure how that would work but I got the Idea from the peeps at Titanium Backup who do something similar. They're really nice, I'm sure they would be happy to help if you asked.

Or another way would be to release a separate "premium" version of the app, and make it available for purchase on XDA labs. Personally, I like this idea better, as it would mean I could buy it sooner (presumably it wouldn't take as long to release)

This would also benefit the development, since Google wouldn't be able to take a cut :)

Whatever way you choose, I hope you'll consider this soon :)

**Comment by katalyste10** [comment]
good

**Comment by liudongmiao** [comment]
Brevent only support:
- Google Play
- Wechat, a China payment
