### ISSUE TITLE
关于（初始）设置的疑惑

### ISSUE THREAD

**Issue by inlinwei** [brevent/Brevent#67]
根据Brevent的介绍，会：
1. 一定时间后（好像默认是60分钟）自动force stop standby的应用
2. 如果一直按返回或者从程序列表swipe掉的话，会直接force stop掉

那么问题来了，run 完adb命令以后，进入程序的主界面，然后选择需要brevent的app。这个又是干嘛的呢？不是会自动brevent吗？还是说指定要brevent的应用才会执行上面两条操作？

谢谢。

**Comment by vvb2060** [comment]
向导要读完，安全这一屏中写了：不处理未被黑域的应用
也就是说，当你把某些应用黑域后，黑域才会对它们进行操作。

如果你打开了自动更新功能，黑域会自动添加部分新安装应用进黑域清单，并且会有提示。
