### ISSUE TITLE
最新测试版（v1.3a+13）bug

### ISSUE THREAD

**Issue by liyufan** [brevent/Brevent#67]
今天闲来无聊想试试最新测试版。结果如图所示，原来一直正常。
![screenshot_20170629-011212](https://user-images.githubusercontent.com/27893441/27650768-95f8205c-5bfb-11e7-9612-53e6267a3ee4.png)
![screenshot_20170629-011159](https://user-images.githubusercontent.com/27893441/27650776-9ba0e624-5bfb-11e7-9df6-1da77e833443.png)

**Comment by liyufan** [comment]
（虽然重启之后好了）

**Comment by liudongmiao** [comment]
说明之前可能某段时间不工作。黑域依赖事件，现在每次启动时，强制检查事件日志，避免已启动但实际不工作。

**Comment by liyufan** [comment]
更新之后上酷安看了一下，很多人出现了更新之后提示没有事件日志的问题。于是开始寻找重现步骤。
我是root用户，由于之前是更新时提示没有事件日志，怀疑是黑域服务重启后会触发问题。
身边暂时没有电脑，那么重启黑域服务的方法有两种（重启黑域服务之前一切正常）：
1.终端模拟器执行
sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
2.RE管理器以脚本方式执行/data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so
第一种方式，没有出现问题
第二种方式，问题重现，提示没有事件日志，请稍后重试，或重启手机
那么为何以第二种方式启动后，提示没有事件日志呢？为什么重启黑域服务前，有事件日志？事件日志的有无和黑域服务没有多大关系吧~

**Comment by liudongmiao** [comment]
更多请去 #63 讨论。

无论哪种方式，最后都是通过 libbrevent.so 创建守护进程 brevent_daemon，然后启 brevent_server。

在我本地，从来都无法重现，包括以下机器：
- pixel 7.1.2, m5s flyme 6, lineageos
- genymotion 各个版本模拟器
