### ISSUE TITLE
/lib/arm64/libbrevent.so: not found

### ISSUE THREAD

**Issue by x140y40** [brevent/Brevent#672]
手机型号：oppo r15
color os版本：6.0.1
安卓版本：9

USB调试已开启，在PC输入命令adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh，返回
Permission denied

使用一键开启工具，返回日志如下：

/system/bin/sh: /data/app/me.piebridge.brevent-eQ0IEDJbHmcy9RQzTV_0-A==/lib/arm64/libbrevent.so: not found
黑阈服务开启失败，请将日志与具体情况发至 https://github.com/brevent/Brevent/issues 来解决问题。

**Comment by liudongmiao** [comment]
请先打开黑阈，或者访问 https://brevent.sh 使用网页版激活。
