### ISSUE TITLE
「黑阈」似乎已从应用宝上下架（?）

### ISSUE THREAD

**Issue by WitherZuo** [brevent/Brevent#673]
无论如何也无法在应用宝上搜索到「黑阈」应用…  

![Screenshot_20200917160401](https://user-images.githubusercontent.com/25317916/93438304-b1b50180-f8ff-11ea-917a-d49da11bd9d4.png)

**Comment by liudongmiao** [comment]
他家从来都是黑盒...管理后台，和用户前台见到的不一致。

**Comment by liudongmiao** [comment]
请截图与 brevent#jianyu.io，将赠送特别贡献兑换码。

**Comment by WitherZuo** [comment]
> 请截图与 brevent#jianyu.io，将赠送特别贡献兑换码。

啊这……请问要截什么图？
