### ISSUE TITLE
Xperia自带的BatteryCare似乎会导致黑阈的关闭

### ISSUE THREAD

**Issue by DeepBlueBubble** [brevent/Brevent#674]
设备：Xperia 1, Android 10
USB Configuration: File Transferring 
已关闭对黑阈的Battery Optimisation
已经关闭Smart Cleaner 

目前得出的结论：

- 进入 BatteryCare 不会导致自动关闭，反而退出会自动关闭（目前只得出手动退出会导致，自动退出还未测试）

- 倘若设备的 USB Configuration 为 No file transferring下,  _在插拔充电线时_ 会导致黑阈的自动关闭。设定为 File Transferring 则不会（其他未测试）

- 不过有趣的是我在关闭 Battery Care 以及在 File Transferring 的状况下充电时，**锁屏时间一久**也会导致黑阈的自动关闭 :( 

- 又或者仅仅是因为我把黑阈滑出了后台才导致的问题？？如果是这样我就傻逼了我.. 

非常头疼，恳请 developers 能检查一下这个问题，非常感谢！

如果有新情况会继续补充在这里

PS： 在寻找问题解决办法的时候看到某一位开发者似乎很不高兴的怼了有同样问题的人，我理解开发者不停遇到嘴皮子都说烂了的问题，不过有的人，就像我是即使遵循了守则后依旧因为某些因素而出现问题，也会感到很难受

-------------------------------------------------------------------------------------------------

更新：

- **Battery Care可能不是主因**。并且在无论是否连接电脑的情况下，我更改 USB option 都不会导致黑阈的自动关闭...

**Comment by DeepBlueBubble** [comment]
最后请求一下开发者能否把play的价格稍微调低一点，我这里结算的价格是6.5 AUD （大约 30+ RMB）。有点小贵，能否减少到5刀左右的价格呢？感谢。

**Comment by DeepBlueBubble** [comment]
测试了一下 https://txc.qq.com/products/41738/faqs/39058? 中的办法，目前似乎还管用。
倘若有更多情况会跟进

**Comment by liudongmiao** [comment]
手里没有这个设备...只有 xz1 compact...
手晨的设备，默认模式不会掉，一般都是默认模式或者仅充电。

**Comment by liudongmiao** [comment]
可以把日志设得长一些，发现掉线，直接反馈，会提取全部日志。

**Comment by liudongmiao** [comment]
> 最后请求一下开发者能否把play的价格稍微调低一点，我这里结算的价格是6.5 AUD （大约 30+ RMB）。有点小贵，能否减少到5刀左右的价格呢？感谢。

一二向箔是 税后 1 刀。具体参照：https://jianyu.io/br/price.zh.html

你定位到了，会赠送特别贡献兑换码。
