### ISSUE TITLE
提示“暫不支援支付”，從Play商店直接安裝。

### ISSUE THREAD

**Issue by lixingduli** [brevent/Brevent#675]
![Screenshot_黑閾_20201010-222009](https://user-images.githubusercontent.com/32449324/95657594-dd668880-0b47-11eb-8bcc-226803f0d096.png)
不知為何無法調用支付服務，以往Play商店購買軟件，或遊戲充值均可正常付款。

**Comment by liudongmiao** [comment]
参阅 https://github.com/brevent/Brevent/issues/480

如果已经支付过，但是没有自动确认支付，请反馈，并带上日志，记得注明相关信息。

**Comment by lixingduli** [comment]
使用 setprop debug.me.piebridge.brevent.play true 執行指令后
![Screenshot_黑閾_20201018-003057](https://user-images.githubusercontent.com/32449324/96348216-ca206380-10d9-11eb-94ee-4c7bdb92f5af.png)
按鈕顯示 成功支付5二向箔 感謝您對軟件的付出 極大提昇使用體驗
