### ISSUE TITLE
有时候黑阈会弹出这个提示什么情况

### ISSUE THREAD

**Issue by lyunfun** [brevent/Brevent#679]
![Screenshot_2020-11-29-19-35-46-224_me piebridge brevent](https://user-images.githubusercontent.com/29173686/100540768-66fa2300-327a-11eb-9152-62f3a94d5524.jpg)

**Comment by liudongmiao** [comment]
黑阈依赖事件日志，请不要在开发者选项中关闭 日志缓冲区 之类。
