### ISSUE TITLE
不能在手机的shell中执行脚本么

### ISSUE THREAD

**Issue by JayceCao** [brevent/Brevent#68]
只能从adb执行很是不方便啊。

**Comment by vvb2060** [comment]
终端应用权限不足，需要连接电脑获得shell权限。如果手机已经root可以尝试直接启动，相关方法请看向导。

**Comment by JayceCao** [comment]
当我在手机上用root权限运行的时候报这个错

WARNING: run as root is experimental!!!
checking............cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log
below
--- crash start ---
>>> logcat -b crash -t '06-29 14:49:10.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-29 14:49:10.000' -d -s BreventLoader BreventServer
06-29 14:49:10.871 31388 31388 D BreventLoader: loader path:
/data/app/me.piebridge.brevent-2/base.apk
06-29 14:49:11.241 31399 31399 D BreventServer: get service: package
06-29 14:49:11.265 31399 31399 I BreventServer: starting Brevent Server 1.3a
06-29 14:49:11.274 31399 31399 D BreventServer: get service: package
06-29 14:49:11.277 31399 31399 I BreventServer: brevent user: 0, uid: 0
06-29 14:49:11.278 31399 31399 I BreventServer: brevent data directory:
/data/user_de/0/com.android.shell
06-29 14:49:11.289 31399 31399 I BreventServer: loading brevent list
06-29 14:49:11.293 31399 31399 I BreventServer: load
/data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 24
06-29 14:49:11.391 31399 31399 I BreventServer: loading brevent conf
06-29 14:49:11.393 31399 31399 D BreventServer: get service: appwidget
06-29 14:49:11.398 31399 31399 D BreventServer: get service: activity
06-29 14:49:11.402 31399 31399 E BreventServer: Can't be run as root,
please open Brevent
06-29 14:49:11.419 31388 31388 E BreventLoader: worker 31399 exited with
status 1
06-29 14:49:11.420 31388 31388 D BreventLoader: signal arrived, update: 0
06-29 14:49:11.420 31383 31383 D BreventLoader: worker 31388 exited with
status 0
--- brevent end ---
cannot listen port, please report bug to
https://github.com/brevent/Brevent/issues with log above

**Comment by vvb2060** [comment]
手机root启动方法请看向导

**Comment by JayceCao** [comment]
不好意思，这向导在哪里啊...没找到...

**Comment by vvb2060** [comment]
第一次打开黑域会出现向导，要求启动黑域服务的窗口有通向向导的按钮，启动后右上角菜单里也可以找到向导。

JayceCao <notifications@github.com>于2017年6月29日周四 下午3:08写道：

> 不好意思，这向导在哪里啊...没找到...
>

**Comment by liudongmiao** [comment]
@JayceCao 

http://weibo.com/6062946029/F9uOeFS4y?type=comment

一句话，请保证黑域在前台。
在你未开启允许 root 运行之前，不要使用任何第三方方式试图以 root 运行。
