### ISSUE TITLE
Brevent crash, start as root (Magisk 21.1)

### ISSUE THREAD

**Issue by abda11ah** [brevent/Brevent#682]
Here is my log:

Meizu/M6Note/M6Note:7.1.2/N2G47H/6.2.10:user/release-keys

WARNING: run as root is experimental!!!
checking for server......started, pid: 12492
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '12-14 00:32:31.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '12-14 00:32:31.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
</details><br/>

**Comment by liudongmiao** [comment]
no detail log...
