### ISSUE TITLE
索尼电视上UI显示不全

### ISSUE THREAD

**Issue by coolyzp** [brevent/Brevent#684]
没有右上角按钮
如图，附log
![DSC_0032](https://user-images.githubusercontent.com/37400863/102690787-d85a3f80-4242-11eb-9ab5-ca664064b40d.JPG)
[logs-v4.2.1-20201219.2134.zip](https://github.com/brevent/Brevent/files/5719487/logs-v4.2.1-20201219.2134.zip)

**Comment by liudongmiao** [comment]
没有计划。
