### ISSUE TITLE
LG V30刷MIUI11后adb激活黑阈出现以下报错

### ISSUE THREAD

**Issue by zhishixiang** [brevent/Brevent#685]
checking for stable..fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-EfUbirl9tSAB6U6OJ_--vA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '12-27 14:48:27.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '12-27 14:48:27.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by zhishixiang** [comment]
使用root时也会显示未启用，但下拉栏又提示运行正常

**Comment by liudongmiao** [comment]
没有日志。如果正常的话，可能只是提示问题。
最新版加强了检测。
