### ISSUE TITLE
不再活动超时时间能不能增加一个永远的选项？

### ISSUE THREAD

**Issue by limne** [brevent/Brevent#686]
不再活动超时时间能不能增加一个永远的选项？现在最长是6个小时，能不能增加一个无限长的选项，对于大内存的手机来说，可以选择永不终止，只是待机就可以了，谢谢大佬。

**Comment by liudongmiao** [comment]
这个时间，系统能读到的也就只有 6 个小时还是 12 个小时，再多了就读不到了，和没有是一样的。
