### ISSUE TITLE
源码中缺少BreventServer

### ISSUE THREAD

**Issue by biaji** [brevent/Brevent#69]
sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh                                                                                                                
checking....brevent_server started, pid: 2412
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '06-30 14:30:13.000' -d
06-30 14:30:15.096  2412  2412 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 2412 (main)
06-30 14:30:15.201   356   356 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-30 14:30:15.201   356   356 F DEBUG   : CM Version: '13.1.2-ZNH2KAS3P0-bacon'
06-30 14:30:15.201   356   356 F DEBUG   : Build fingerprint: 'oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS3P0:user/release-keys'
06-30 14:30:15.201   356   356 F DEBUG   : Revision: '0'
06-30 14:30:15.201   356   356 F DEBUG   : ABI: 'arm'
06-30 14:30:15.201   356   356 F DEBUG   : pid: 2412, tid: 2412, name: main  >>> brevent_server <<<
06-30 14:30:15.201   356   356 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-30 14:30:15.218   356   356 F DEBUG   : Abort message: 'art/runtime/thread.cc:1336] No pending exception expected: java.lang.ClassNotFoundException: Didn't find class "me.piebridge.brevent.server.BreventServer" on path: DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]'
06-30 14:30:15.218   356   356 F DEBUG   :     r0 00000000  r1 0000096c  r2 00000006  r3 00000000
06-30 14:30:15.218   356   356 F DEBUG   :     r4 b6f2eb88  r5 00000006  r6 b6f2eb38  r7 0000010c
06-30 14:30:15.219   356   356 F DEBUG   :     r8 b4bff820  r9 b4bfde64  sl b4ca44db  fp b4be3720
06-30 14:30:15.219   356   356 F DEBUG   :     ip 00000000  sp be995398  lr b6c744d1  pc b6c76c34  cpsr 20070010
06-30 14:30:15.250   356   356 F DEBUG   : 
06-30 14:30:15.250   356   356 F DEBUG   : backtrace:
06-30 14:30:15.250   356   356 F DEBUG   :     #00 pc 00049c34  /system/lib/libc.so (tgkill+12)
06-30 14:30:15.250   356   356 F DEBUG   :     #01 pc 000474cd  /system/lib/libc.so (pthread_kill+36)
06-30 14:30:15.250   356   356 F DEBUG   :     #02 pc 0001bbe3  /system/lib/libc.so (raise+10)
06-30 14:30:15.250   356   356 F DEBUG   :     #03 pc 0001848d  /system/lib/libc.so (__libc_android_abort+36)
06-30 14:30:15.250   356   356 F DEBUG   :     #04 pc 000164ec  /system/lib/libc.so (abort+4)
06-30 14:30:15.250   356   356 F DEBUG   :     #05 pc 00331875  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228)
06-30 14:30:15.250   356   356 F DEBUG   :     #06 pc 000f44db  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
06-30 14:30:15.250   356   356 F DEBUG   :     #07 pc 000f07b1  /system/lib/libart.so (_ZN3art7BarrierD2Ev+216)
06-30 14:30:15.250   356   356 F DEBUG   :     #08 pc 0035b323  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+162)
06-30 14:30:15.250   356   356 F DEBUG   :     #09 pc 00331939  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+424)
06-30 14:30:15.250   356   356 F DEBUG   :     #10 pc 000f44db  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
06-30 14:30:15.250   356   356 F DEBUG   :     #11 pc 0034ef6b  /system/lib/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv.part.170+378)
06-30 14:30:15.250   356   356 F DEBUG   :     #12 pc 0013698b  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+34)
06-30 14:30:15.250   356   356 F DEBUG   :     #13 pc 0029d3a1  /system/lib/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+812)
06-30 14:30:15.250   356   356 F DEBUG   :     #14 pc 0005f793  /system/lib/libandroid_runtime.so (_ZN7android30register_android_util_SeempLogEP7_JNIEnv+14)
06-30 14:30:15.250   356   356 F DEBUG   :     #15 pc 0005f93d  /system/lib/libandroid_runtime.so
06-30 14:30:15.250   356   356 F DEBUG   :     #16 pc 0005fe1f  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime8startRegEP7_JNIEnv+26)
06-30 14:30:15.250   356   356 F DEBUG   :     #17 pc 0006116b  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+330)
06-30 14:30:15.251   356   356 F DEBUG   :     #18 pc 000018ef  /su/bin/app_process
06-30 14:30:15.251   356   356 F DEBUG   :     #19 pc 00016315  /system/lib/libc.so (__libc_init+52)
06-30 14:30:15.251   356   356 F DEBUG   :     #20 pc 000014d4  /su/bin/app_process
06-30 14:30:15.405   356   356 F DEBUG   : 
06-30 14:30:15.405   356   356 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_04
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '06-30 14:30:13.000' -d -s BreventLoader BreventServer
06-30 14:30:14.196  2399  2399 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
06-30 14:30:15.410  2399  2399 E BreventLoader: worker 2412 exited on signal 6
06-30 14:30:15.410  2399  2399 D BreventLoader: signal arrived, update: 0
06-30 14:30:15.411  2391  2391 D BreventLoader: worker 2399 exited with status 0
--- brevent end ---

**Comment by liyufan** [comment]
BreventServer不开源。

**Comment by biaji** [comment]
看到了。。。 case close

**Comment by liudongmiao** [comment]
@biaji 虽然 brevent-server 不开源，但不影响你改动黑域的其它内容。
这部分已经单独打包，请参考这个文档：https://github.com/brevent/Brevent/blob/master/DEVELOP.md

**Comment by biaji** [comment]
看到了。 不是很方便。还要写个脚本来build。  有些东西也没法debug。我自己改改framework好了。
