### ISSUE TITLE
黑域开启失败

### ISSUE THREAD

**Issue by CCCCCCTV** [brevent/Brevent#691]
[
[BreventLog.txt](https://github.com/brevent/Brevent/files/5880699/BreventLog.txt)
](url)
log如上

**Comment by CCCCCCTV** [comment]
WARNING: linker: /data/local/tmp/brevent: unsupported flags DT_FLAGS_1=0x8000001
checking for server...fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '01-27 22:04:12.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-27 22:04:12.000' -d -s BreventLoader BreventServer
01-27 22:04:13.535  4640  4640 I BreventServer: args: [10, me.piebridge.brevent, 1611756252]
01-27 22:04:13.595  4640  4640 I BreventServer: server log name: server.20210127.2204.4640.txt
01-27 22:04:13.596  4640  4640 I BreventServer: starting Brevent Server 2.7.6
01-27 22:04:13.625  4640  4640 I BreventServer: brevent user: 0, uid: 2000
01-27 22:04:13.627  4640  4640 E BreventServer: Can't find package com.android.shell for 0
01-27 22:04:13.627  4640  4640 E BreventServer: java.lang.NullPointerException: Attempt to read from field 'int android.content.pm.ApplicationInfo.uid' on a null object reference
01-27 22:04:13.627  4640  4640 E BreventServer: 	at me.piebridge.brevent.server.d.f(BreventServerImpl.java:2817)
01-27 22:04:13.627  4640  4640 E BreventServer: 	at me.piebridge.brevent.server.d.<init>(BreventServerImpl.java:390)
01-27 22:04:13.627  4640  4640 E BreventServer: 	at me.piebridge.brevent.server.d.a(BreventServerImpl.java:2902)
01-27 22:04:13.627  4640  4640 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:33)
01-27 22:04:13.627  4640  4640 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
01-27 22:04:13.627  4640  4640 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:138)
01-27 22:04:13.627  4640  4640 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
01-27 22:04:13.627  4640  4640 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
01-27 22:04:13.642  4625  4625 E BreventLoader: worker 4640 exited with status 1
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above
黑阈服务开启失败，请将日志与具体情况发至 https://github.com/brevent/Brevent/issues 来解决问题。

**Comment by vvb2060** [comment]
黑阈不对旧版提供支持，请到 https://brevent.jianyu.io/ 下载新版。
黑阈不支持损坏的系统。

**Comment by CCCCCCTV** [comment]
我这个设备确实删除了部分系统应用
请问下黑阈依赖于什么系统应用或环境？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "vvb2060"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 晚上10:42
收件人: "brevent/Brevent"<Brevent@noreply.github.com&gt;; 
抄送: "凉生"<2091449962@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [brevent/Brevent] 黑域开启失败 (#691)





 
黑阈不对旧版提供支持，请到 https://brevent.jianyu.io/ 下载新版。
 黑阈不支持损坏的系统。

**Comment by CCCCCCTV** [comment]
已解决 感谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "vvb2060"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 晚上10:42
收件人: "brevent/Brevent"<Brevent@noreply.github.com&gt;; 
抄送: "凉生"<2091449962@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [brevent/Brevent] 黑域开启失败 (#691)





 
黑阈不对旧版提供支持，请到 https://brevent.jianyu.io/ 下载新版。
 黑阈不支持损坏的系统。
