### ISSUE TITLE
如何开启实验功能

### ISSUE THREAD

**Issue by DoingDog** [brevent/Brevent#693]
我已购买svip，如何开启实验功能

**Comment by vvb2060** [comment]
设置-实验性，共两个开关，视系统情况显示。没有Google套件不显示动态gms，不支持暂停应用不显示暂停。

**Comment by liudongmiao** [comment]
实验性功能并不稳定，如果不显示的话就是隐藏状态。
建议是关闭～已经支付的话，可以自助退款。
