### ISSUE TITLE
希望增加停止黑阈的功能

### ISSUE THREAD

**Issue by RainThings** [brevent/Brevent#695]
有些情况会出现问题，但不想重启，无法结束黑阈服务进程。希望可以提供这个功能。

**Comment by vvb2060** [comment]
设置-启用黑阈，关闭即可。

**Comment by liudongmiao** [comment]
1. 停止黑阈
vvb2060 已经提及，直接“设置” - 关闭“启用黑阈”即可。

2. 对新装应用停止自动黑阈
设置，点按 7 次系统状态，关闭“自动更新”。
