### ISSUE TITLE
打不開google了，目前無法使用此應用程式

### ISSUE THREAD

**Issue by pekkle-hksar** [brevent/Brevent#696]
每次嘗試打開google app就跳出提示

目前無法使用此應用程式
目前無法使用Google。此應用程式是由「黑阈」管理。

但 黑阈 => 系統应用 沒有選項可以對Google操作，求解！

**Comment by pekkle-hksar** [comment]
好像是因為錯誤把某些google的service黑掉了，請無視

**Comment by liudongmiao** [comment]
这个提示，表明你使用了 停用/暂停 功能。

**Comment by pekkle-hksar** [comment]
我好像是把 google connectivity services 拉黑了，然後就出現這個問題
把service放出來就正常了
