### ISSUE TITLE
如何应用黑阈使系统自动不杀后台

### ISSUE THREAD

**Issue by CCCCCCTV** [brevent/Brevent#697]
如题 刚买的手机 系统杀后台严重 把QQ加了后台自启 允许后台行为和取消黑阈后同样会被杀后台

**Comment by liudongmiao** [comment]
一般来说，黑阈不会处理你没有黑阈的应用。
所以，请尝试以下选项：
- 不要黑阈 QQ
- 不要黑阈 QQ 可能依赖的组件，特别是无法打开的应用或系统应用

不确定的话，可以：
- 黑阈，设置，关闭“启用黑阈”

如果还这样，说明与黑阈无关，请联系手机厂商；如果解决，表明可能是黑阈干的。
重复以后，黑阈 - 反馈 - 日志，邮件发出并在邮件内描述。
