### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by himawari22** [brevent/Brevent#698]
https://del.dog/ywumallena

Xiaomi/cancro/cancro:6.0.1/MMB29M/V8.1.6.0.MXDMIDI:user/release-keys

WARNING: run as root is experimental!!!
checking for server..started, pid: 12754
checking for stable....quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-UEs56E94ooDVoT67UEyJZQ==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '02-24 11:10:32.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '02-24 11:10:32.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by liudongmiao** [comment]
please update to latest version.
