### ISSUE TITLE
版本4.2.2.2，root模式启动，已经启动成功，提示失败，关闭app后再次打开启动成功（本来就是成功的）

### ISSUE THREAD

**Issue by yinzhefuyun** [brevent/Brevent#699]
红米5PLUS miui11 安卓8.1.0，已支付5二向箔

xiaomi/vince/vince:8.1.0/OPM1.171019.019/V11.0.3.0.OEGCNXM:user/release-keys

WARNING: run as root is experimental!!!
checking for server....started, pid: 9366
checking for stable..success（这里提示已经启动成功，弹窗显示失败）

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues/new with logs
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by liudongmiao** [comment]
4.2.3 里优化了一下，但还是可能会这样。

执行成功，但是没有收到回调...

**Comment by yinzhefuyun** [comment]
> 4.2.3 里优化了一下，但还是可能会这样。
> 
> 执行成功，但是没有收到回调...

4.2.4.1重启后使用root，回调成功，没有弹窗显示失败
