### ISSUE TITLE
chromebook不支持

### ISSUE THREAD

**Issue by seanwhy** [brevent/Brevent#7]
我是三星chromebook plus，版本60.0.3112.80beta 32位，安卓版本7.1.1，装了黑域能弹出usb调试连接，选择后报错如下：
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> /system/bin/logcat -b crash -t '08-07 09:14:20.000' -d
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '08-07 09:14:20.000' -d -s BreventLoader BreventServer
08-07 09:14:21.111  4337  4337 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
08-07 09:14:21.655  4347  4347 D BreventServer: get service: package
08-07 09:14:21.655  4347  4347 D BreventServer: args: [10]
08-07 09:14:21.655  4347  4347 I BreventServer: signal: 10
08-07 09:14:21.659  4347  4347 I BreventServer: starting Brevent Server 2.1.1
08-07 09:14:21.666  4347  4347 D BreventServer: get service: package
08-07 09:14:21.667  4347  4347 I BreventServer: brevent user: 0, uid: 2000
08-07 09:14:21.668  4347  4347 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-07 09:14:21.677  4347  4347 I BreventServer: loading brevent list
08-07 09:14:21.677  4347  4347 I BreventServer: loading brevent conf
08-07 09:14:21.679  4347  4347 E BreventServer: Could not access appwidget. Is the system running?
08-07 09:14:21.697  4337  4337 E BreventLoader: worker 4347 exited with status 1
08-07 09:14:21.697  4337  4337 D BreventLoader: signal arrived, update: 0
08-07 09:14:21.697  4332  4332 D BreventLoader: worker 4337 exited with status 0
--- brevent end ---
我知道可能对于chromeos，黑域没做过支持，建议在这方面扩展对于chromebook系列的支持，谢谢！

**Comment by liudongmiao** [comment]
> Could not access appwidget. Is the system running?
那我就没办法了...

你可以执行 `dumpsys appwidget` 看看，输出什么。

**Comment by seanwhy** [comment]
在chrome控制台输入，命令未找到😂

2017年8月7日 09:53，"Liu DongMiao" <notifications@github.com>写道：

**Comment by liudongmiao** [comment]
adb shell 之后，再输入。

**Comment by liudongmiao** [comment]
没有后续反馈，关闭。
