### ISSUE TITLE
重启后设置数据与捐赠信息丢失

### ISSUE THREAD

**Issue by IceEst** [brevent/Brevent#70]
每次重启后都会回到欢迎界面，设置里的选项全部初始化，捐赠信息丢失，要重开支付宝才行。但是黑域哪些应用的数据还在

**Comment by IceEst** [comment]
使用root运行

**Comment by liudongmiao** [comment]
如果出现这种情况，请自查是否有任何其它工具 hack 黑域。

root 情况下，不好处理，所以抱歉。

黑域只在自己的应用目录保存配置文件。
