### ISSUE TITLE
换区导致付费记录失效

### ISSUE THREAD

**Issue by gricn** [brevent/Brevent#700]
18年5月在Google Play购买了 3 Brefoil（当时23HKD），但最近从港区换到美区后，打开brevent一直提示我是免费用户，要用root启动功能需在play商店付费。
请问有什么解决方法吗？

**Comment by liudongmiao** [comment]
黑阈不建议国内用户使用 Play 支付。具体参见 #480 。

正常情况下，打开黑阈即可自动识别支付。
如果没有，检查 Google Play 各项设定。

**Comment by gricn** [comment]
已解决，感谢
