### ISSUE TITLE
黑阈App之后会出现App不能联网的问题

### ISSUE THREAD

**Issue by JayYu998** [brevent/Brevent#703]
黑阈某个App后一段时间就会出现该App不能联网的问题，通过取消黑阈，并且将该应用从系统电池优化名单拉出来停用重开就好了，但只要黑阈并且系统电池优化就会出现这个问题，尝试卸载黑阈后便没有再出现这类问题，无论是否在系统电池优化列表里

**Comment by liudongmiao** [comment]
有两种情况：
- 该应用没有适配 待机
- 黑阈可能不支持 事件

不使用应用时，黑阈会主动 待机 该应用，确保该应用不被启动。

而根据  Android 机制，主动打开时，可以访问网络；黑阈也会取消 待机 该应用。

**Comment by aa889788** [comment]
> 有两种情况：
> 
> * 该应用没有适配 待机
> * 黑阈可能不支持 事件
> 
> 不使用应用时，黑阈会主动 待机 该应用，确保该应用不被启动。
> 
> 而根据 Android 机制，主动打开时，可以访问网络；黑阈也会取消 待机 该应用。

那这种情况的话是只能使用“只强行停止不待机”吗？

**Comment by liudongmiao** [comment]
建议你不用时直接划掉，避免它在后台～新打开的应用，黑阈及系统都会确保它能联网

**Comment by vvb2060** [comment]
另外，AOSP 的 ipfilter 规则重置存在问题，可能会导致已待机的应用退出状态后无法正常恢复网络访问。我们无法处理，也不知道现在Google是否已经修复。
