### ISSUE TITLE
No sufficient permissions

### ISSUE THREAD

**Issue by SV-stark** [brevent/Brevent#704]
Even after giving root access to the app this error shows up. 
![Screenshot_2021-04-11-16-38-14-98_e88630c4e740b41437a1b6dc6436479a](https://user-images.githubusercontent.com/66217841/114302097-2e4e3e00-9ae5-11eb-8416-acc09c6dd4a1.jpg)

**Comment by whynotjinx** [comment]
Same problem here. Have you solved this?

**Comment by liudongmiao** [comment]
Normally, it's related your rom, or settings in Developer Option.

**Comment by Noahsupernosh** [comment]
How do you solve this problem

**Comment by Tuanvirel1** [comment]
Làm sao để fix

**Comment by ananaghale0-ops** [comment]
How to solve
