### ISSUE TITLE
黑域无法持续开启

### ISSUE THREAD

**Issue by ghosiejackson** [brevent/Brevent#705]
我用的xperia 5 ii，近1周出现黑域经常过一段时间自发停止（可能是掉后台），最短不超过半小时甚至几分钟就需要重新开启网络Adb，请问如何解决？

**Comment by vvb2060** [comment]
https://txc.qq.com/products/41738/faqs/39058

如果通过无线调试启动，不要关闭USB调试，否则WiFi关闭后失效。
