### ISSUE TITLE
安卓11切换后台一段时间会提示重新激活无法一直后台运行

### ISSUE THREAD

**Issue by homankit414** [brevent/Brevent#706]
安卓11切换后台一段时间会提示重新激活无法一直后台运行

**Comment by liucan233** [comment]
我也遇到了这个问题，重新打开黑域就需要再授权一次

**Comment by vvb2060** [comment]
https://txc.qq.com/products/41738/faqs/39058

如果通过无线调试启动，不要关闭USB调试，否则WiFi关闭后失效。
