### ISSUE TITLE
美团和WPS被识别为系统应用

### ISSUE THREAD

**Issue by lizhenxin111** [brevent/Brevent#707]
手机型号是华为畅享7plus，TRT-AL00A，android版本是7.0，emui版本是5.1.3，黑阈版本是4.2.4.1

![Screenshot_20210417-191802](https://user-images.githubusercontent.com/25926635/115111291-3c530180-9fb2-11eb-85e2-394fe4f5c62a.png)

**Comment by vvb2060** [comment]
说明在系统看来它们的确是系统应用。如果可以被彻底卸载，那么可能是系统的小动作，对某些应用进行了特殊标记。
