### ISSUE TITLE
无法自动工作

### ISSUE THREAD

**Issue by MisakaSakura** [brevent/Brevent#708]
更新系统之后就显示“没有事件日志，黑域无法正常工作”，系统更新前是没问题的。![Screenshot_20210423-031310_黑阈.png](https://user-images.githubusercontent.com/30547550/115772773-17abbf00-a3e2-11eb-80a2-9f7ae6f1431d.png)![Screenshot_20210423-031455_设置.png](https://user-images.githubusercontent.com/30547550/115772779-1a0e1900-a3e2-11eb-95f0-8f843d46e241.png)

**Comment by vvb2060** [comment]
很明显，你应该向ROM供应商反馈。

**Comment by vvb2060** [comment]
https://github.com/AICP/frameworks_base/commit/34800851c95ddb4c9f5b680225647eb3cbd4da2f
比如这个ROM，居然修改公共API行为，建议检查自己使用的ROM是否包含这个提交。

**Comment by vvb2060** [comment]
果然，Havoc-OS也pick了这个提交，请向ROM维护者反馈。https://github.com/Havoc-OS/android_frameworks_base/commit/6fe1b0f717b7139547e40066de740b10b49c2acf

**Comment by vvb2060** [comment]
你可以请他们pick此提交来还原修改 https://github.com/ProtonAOSP/android_frameworks_base/commit/4ffd638299fe1a3a497762290afa8ceb12516a25

**Comment by lennondotw** [comment]
Legion OS 也有这个问题，我已经提交了 Revert
https://github.com/Project-LegionOS/frameworks_base/pull/19

最近好多 ROM 更新后都导致了 Brevent 失效。我觉得可能有很多 Custom ROM 都 pick 了这个 commit。我遇到的还有 crDriod，也是在某次更新后 Brevent 失效了。
