### ISSUE TITLE
状态提示文本问题

### ISSUE THREAD

**Issue by Vstory** [brevent/Brevent#709]
- 1. 

> 应用已待机，达到“不在活跃超时”或从概览屏幕划掉后被强行停止。

![image](https://user-images.githubusercontent.com/20795557/116440159-c8064100-a882-11eb-9691-2ad71a4055f4.png)

这句话加个`会`字读起来更加通顺。

> 应用已待机，达到“不在活跃超时”或从概览屏幕划掉后会被强行停止。

- 2. 同样的，下图分号前具有相同问题；分号后，读起来就没有这个问题。

![image](https://user-images.githubusercontent.com/20795557/116440793-62ff1b00-a883-11eb-848e-98c07afaf07a.png)

**Comment by liudongmiao** [comment]
以上属于省略了“将”，也就是你提到的“会”字，不处理。
