### ISSUE TITLE
更新版本后电脑ADB打不开，无法root开启

### ISSUE THREAD

**Issue by SYuanLUV** [brevent/Brevent#71]
D:\shuame\4.2.1.221>adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
checking...brevent_server started, pid: 16411
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-01 20:12:50.000' -d
logcat read failure--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-01 20:12:50.000' -d -s BreventLoader BreventServer
logcat read failure--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

无法root开启是之前就有的问题，手机机型是乐MAX2

**Comment by liudongmiao** [comment]
> logcat read failure

黑域依赖日志。请不要关闭日志。

**Comment by SYuanLUV** [comment]
请问要怎么打开日志？ 我之前并没有关闭过啊

**Comment by SYuanLUV** [comment]
求助...百度了好久都不会开启日志，刚刚用adb输入adb logcat也是显示logcat read failure，然后下载了低版本后可以正常使用了
至于一直以来都不能用root开启的问题，我之前查过，用selinux mode change 切成permissive也不能用root开启，终端模拟器也不行
多谢了

**Comment by vvb2060** [comment]
你的root程序破坏了系统，恢复原厂ROM吧，这不是黑域的问题。
https://android.googlesource.com/platform/system/core/+/master/logcat/logcat.cpp#1641

**Comment by SYuanLUV** [comment]
好的谢谢
