### ISSUE TITLE
OxygenOS 10 - OnePlus 7 Pro

### ISSUE THREAD

**Issue by jameskunst** [brevent/Brevent#711]
adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server..started, pid: 21442
checking for stable..reborn, pid: 21518
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-nim7vOfVfR9ZKHIO9dpsmQ==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '05-15 02:24:08.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '05-15 02:24:08.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
</details><br/>

**Comment by vvb2060** [comment]
No valid content in log
