### ISSUE TITLE
play版黑阈要如何退款，退款时显示不符合play退款政策？

### ISSUE THREAD

**Issue by su2353** [brevent/Brevent#712]
play版黑阈要如何退款，退款时显示不符合play退款政策？

**Comment by su2353** [comment]
发邮件也没收到回复

**Comment by vvb2060** [comment]
play要退款只能找Google

**Comment by su2353** [comment]
> play要退款只能找Google

google要我找开发者，且app介绍页面也指明退款只要一个月内发邮件给开发者即可，然而邮件至今仍未得到回复

**Comment by su2353** [comment]
结束：刚查看余额，已退款，只是没收到邮件通知
