### ISSUE TITLE
索尼xperia1ii更新后无法启动黑阈（附图）

### ISSUE THREAD

**Issue by hanaeye** [brevent/Brevent#713]
![DSC_0001~2](https://user-images.githubusercontent.com/85316234/120708976-db927080-c4ee-11eb-8e71-0ff70e289323.JPG)

**Comment by liudongmiao** [comment]
Android 11 后，请使用无线激活：

https://www.coolapk.com/feed/18348062?shareKey=M2M1ZDQyMTFhYzUzNjA0NDcyNjc

此外，自黑阈 4.2.5.2 起，在 Android 11 及以后，不再支持普通网络调试。
