### ISSUE TITLE
默认模式为何切换为了”不休眠，仅强行停止“

### ISSUE THREAD

**Issue by aviraxp** [brevent/Brevent#714]
是 bug 还是 特性 呢？系统是支持 app standby 的。

**Comment by liudongmiao** [comment]
默认的都是 待机+强行停止

**Comment by vvb2060** [comment]
清空数据实测，默认策略是仅强行停止。

**Comment by liudongmiao** [comment]
我再确认下是不是存在什么兼容性：

默认是 default_brevent_method
https://github.com/brevent/Brevent/blob/master/brevent/src/main/res/xml/settings.xml#L15

现在打包的 apk 里，default_brevent_method 是 standby_forcestop

我再确认下～

**Comment by liudongmiao** [comment]
`/data/user_de/0/com.android.shell/me.piebridge.brevent.conf` 这个文件里，brevent_method 这个值是方法，序号就是定义的数组。

**Comment by liudongmiao** [comment]
经检查，之前在收到 黑阈服务 响应时，会检查是否支持黑阈。

而在引入只读模式之后，没有针对 只读 模式特殊处理，认为不支持 待机。

已发 beta 版，请等待 Play 商店推送或者这里：https://jianyu.io/br/beta/
