### ISSUE TITLE
没有事件日志黑阈无法自动工作

### ISSUE THREAD

**Issue by 20171213** [brevent/Brevent#719]
开机可以正常自启，但是一段时间后再打开就会有这个提示
![Screenshot_20210617-141441_黑阈.png](https://user-images.githubusercontent.com/34502902/122341778-6f941b80-cf76-11eb-937f-c15749d27a19.png)
尝试修改开发者选项里的日志缓冲大小，无效
![Screenshot_20210617-141631_设置.png](https://user-images.githubusercontent.com/34502902/122341969-a79b5e80-cf76-11eb-80a7-36ddadb42bb7.png)

**Comment by vvb2060** [comment]
#708
