### ISSUE TITLE
about the Samsung galaxy S6 cant not listen port

### ISSUE THREAD

**Issue by LOST0LOSER** [brevent/Brevent#72]
![3](https://user-images.githubusercontent.com/29311094/27768122-7d4c2968-5f3e-11e7-9705-2afc49b282f7.PNG)
![4](https://user-images.githubusercontent.com/29311094/27768123-7dd89fc4-5f3e-11e7-9fbd-46c9b0192667.PNG)
![crash log 2](https://user-images.githubusercontent.com/29311094/27768124-7de8ba8a-5f3e-11e7-85db-36d308b417d7.PNG)
![crash log](https://user-images.githubusercontent.com/29311094/27768125-7e472444-5f3e-11e7-86c6-75e3f3650056.PNG)
![samsung s6](https://user-images.githubusercontent.com/29311094/27768126-7e48e8f6-5f3e-11e7-9a85-f31621b1b7d0.PNG)

**Comment by liudongmiao** [comment]
眼都要看瞎了。。能来个文字版么？

**Comment by liudongmiao** [comment]
日志偏少，原因未知。请电脑上安装 teamviewer，把 id 与 密码发到 brevent@piebridge.me

**Comment by LOST0LOSER** [comment]
不好意思啊，贪了方便给你带来麻烦

D:\刷机精灵\shuame\4.2.2.222>adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
checking............cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-03 12:27:20.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-03 12:27:20.000' -d -s BreventLoader BreventServer
07-03 12:27:20.481 10157 10157 E BreventLoader: worker 10162 exited with status 255
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

D:\刷机精灵\shuame\4.2.2.222>adb -d logcat -d -b crash
07-03 00:16:30.523  7366  7366 F libc    : "/data/user/0/com.baidu.tieba/files/libprocmox_v1_4.so": error: only position independent executables (PIE) are supported.
07-03 00:16:30.523  7366  7366 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7366 (libprocmox_v1_4)
07-03 00:16:30.583  7368  7368 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-03 00:16:30.583  7368  7368 F DEBUG   : Build fingerprint: 'samsung/dream2qltezc/dream2qltechn:7.0/NRD90M/G9550ZCU1AQDF:user/release-keys'
07-03 00:16:30.583  7368  7368 F DEBUG   : Revision: '10'
07-03 00:16:30.583  7368  7368 F DEBUG   : ABI: 'arm'
07-03 00:16:30.583  7368  7368 F DEBUG   : pid: 7366, tid: 7366, name: libprocmox_v1_4  >>> /data/user/0/com.baidu.tieba/files/libprocmox_v1_4.so <<<
07-03 00:16:30.583  7368  7368 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-03 00:16:30.583  7368  7368 F DEBUG   :     r0 00000000  r1 00001cc6  r2 00000006  r3 00000008
07-03 00:16:30.583  7368  7368 F DEBUG   :     r4 f1c4358c  r5 00000006  r6 f1c43534  r7 0000010c
07-03 00:16:30.583  7368  7368 F DEBUG   :     r8 f1bde000  r9 00000000  sl f1bd2010  fp ffd8cb58
07-03 00:16:30.583  7368  7368 F DEBUG   :     ip 00000000  sp ffd8cad8  lr f1c2340f  pc f1c23e2c  cpsr 600f0010
07-03 00:16:30.587  7368  7368 F DEBUG   :
07-03 00:16:30.587  7368  7368 F DEBUG   : backtrace:
07-03 00:16:30.587  7368  7368 F DEBUG   :     #00 pc 00045e2c  /system/bin/linker (__dl_tgkill+12)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #01 pc 0004540b  /system/bin/linker (__dl_pthread_kill+34)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #02 pc 0003d6ef  /system/bin/linker (__dl_raise+10)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #03 pc 0003c1ab  /system/bin/linker (__dl___libc_android_abort+34)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #04 pc 0003af88  /system/bin/linker (__dl_abort+4)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #05 pc 0003d1f3  /system/bin/linker (__dl___libc_fatal+22)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #06 pc 000093f9  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #07 pc 00008a0b  /system/bin/linker (__dl___linker_init+358)
07-03 00:16:30.587  7368  7368 F DEBUG   :     #08 pc 000027d8  /system/bin/linker (_start+4)
07-03 00:49:18.231 11484 11484 E AndroidRuntime: FATAL EXCEPTION: main
07-03 00:49:18.231 11484 11484 E AndroidRuntime: Process: com.samsung.android.clipboarduiservice, PID: 11484
07-03 00:49:18.231 11484 11484 E AndroidRuntime: java.lang.IllegalArgumentException: Receiver not registered: com.samsung.android.clipboarduiservice.view.ClipboardNormalDialog$1@4693647
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at com.samsung.android.clipboarduiservice.view.ClipboardNormalDialog.onStop(ClipboardNormalDialog.java:855)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.app.Dialog.dismissDialog(Dialog.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.app.Dialog.dismiss(Dialog.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at com.samsung.android.clipboarduiservice.view.ClipboardNormalDialog.dismiss(ClipboardNormalDialog.java:1441)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at com.samsung.android.clipboarduiservice.view.ClipboardNormalDialog$4.handleMessage(ClipboardNormalDialog.java:1301)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.os.Looper.loop(Looper.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
07-03 00:49:18.231 11484 11484 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
07-03 00:53:33.116 13455 13455 F libc    : "/data/data/com.wandoujia.phoenix2/amodel/a": error: only position independent executables (PIE) are supported.
07-03 00:53:33.116 13455 13455 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 13455 (a)
07-03 00:53:33.189 13456 13456 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-03 00:53:33.190 13456 13456 F DEBUG   : Build fingerprint: 'samsung/dream2qltezc/dream2qltechn:7.0/NRD90M/G9550ZCU1AQDF:user/release-keys'
07-03 00:53:33.190 13456 13456 F DEBUG   : Revision: '10'
07-03 00:53:33.190 13456 13456 F DEBUG   : ABI: 'arm'
07-03 00:53:33.190 13456 13456 F DEBUG   : pid: 13455, tid: 13455, name: a  >>> /data/data/com.wandoujia.phoenix2/amodel/a <<<
07-03 00:53:33.190 13456 13456 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-03 00:53:33.190 13456 13456 F DEBUG   :     r0 00000000  r1 0000348f  r2 00000006  r3 00000008
07-03 00:53:33.190 13456 13456 F DEBUG   :     r4 eb8a858c  r5 00000006  r6 eb8a8534  r7 0000010c
07-03 00:53:33.191 13456 13456 F DEBUG   :     r8 eb843000  r9 00000000  sl eb837010  fp ff99d788
07-03 00:53:33.191 13456 13456 F DEBUG   :     ip 00000000  sp ff99d708  lr eb88840f  pc eb888e2c  cpsr 600f0010
07-03 00:53:33.200 13456 13456 F DEBUG   :
07-03 00:53:33.200 13456 13456 F DEBUG   : backtrace:
07-03 00:53:33.201 13456 13456 F DEBUG   :     #00 pc 00045e2c  /system/bin/linker (__dl_tgkill+12)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #01 pc 0004540b  /system/bin/linker (__dl_pthread_kill+34)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #02 pc 0003d6ef  /system/bin/linker (__dl_raise+10)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #03 pc 0003c1ab  /system/bin/linker (__dl___libc_android_abort+34)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #04 pc 0003af88  /system/bin/linker (__dl_abort+4)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #05 pc 0003d1f3  /system/bin/linker (__dl___libc_fatal+22)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #06 pc 000093f9  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #07 pc 00008a0b  /system/bin/linker (__dl___linker_init+358)
07-03 00:53:33.201 13456 13456 F DEBUG   :     #08 pc 000027d8  /system/bin/linker (_start+4)
07-03 12:27:13.025 10037 10037 F libc    : "/data/local/tmp/aapt_android": error: only position independent executables (PIE) are supported.
07-03 12:27:13.025 10037 10037 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 10037 (aapt_android)
07-03 12:27:13.104 10040 10040 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-03 12:27:13.105 10040 10040 F DEBUG   : Build fingerprint: 'samsung/dream2qltezc/dream2qltechn:7.0/NRD90M/G9550ZCU1AQDF:user/release-keys'
07-03 12:27:13.105 10040 10040 F DEBUG   : Revision: '10'
07-03 12:27:13.105 10040 10040 F DEBUG   : ABI: 'arm'
07-03 12:27:13.105 10040 10040 F DEBUG   : pid: 10037, tid: 10037, name: aapt_android  >>> /data/local/tmp/aapt_android <<<
07-03 12:27:13.105 10040 10040 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-03 12:27:13.105 10040 10040 F DEBUG   :     r0 00000000  r1 00002735  r2 00000006  r3 00000008
07-03 12:27:13.105 10040 10040 F DEBUG   :     r4 f446858c  r5 00000006  r6 f4468534  r7 0000010c
07-03 12:27:13.105 10040 10040 F DEBUG   :     r8 f4403000  r9 00000000  sl f43f7010  fp ff99b5d8
07-03 12:27:13.105 10040 10040 F DEBUG   :     ip 00000000  sp ff99b558  lr f444840f  pc f4448e2c  cpsr 600f0010
07-03 12:27:13.121 10040 10040 F DEBUG   :
07-03 12:27:13.121 10040 10040 F DEBUG   : backtrace:
07-03 12:27:13.125 10040 10040 F DEBUG   :     #00 pc 00045e2c  /system/bin/linker (__dl_tgkill+12)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #01 pc 0004540b  /system/bin/linker (__dl_pthread_kill+34)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #02 pc 0003d6ef  /system/bin/linker (__dl_raise+10)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #03 pc 0003c1ab  /system/bin/linker (__dl___libc_android_abort+34)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #04 pc 0003af88  /system/bin/linker (__dl_abort+4)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #05 pc 0003d1f3  /system/bin/linker (__dl___libc_fatal+22)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #06 pc 000093f9  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #07 pc 00008a0b  /system/bin/linker (__dl___linker_init+358)
07-03 12:27:13.125 10040 10040 F DEBUG   :     #08 pc 000027d8  /system/bin/linker (_start+4)

**Comment by liudongmiao** [comment]
上面说了啊，日志信息偏少，估计需要我上去调试....

请电脑上安装 teamviewer，把 id 与 密码发到 brevent@piebridge.me
邮件再约时间。

如果不是特别执着，我建议放弃好了。

**Comment by LOST0LOSER** [comment]
好的，绿色守护应该够用的吧

**Comment by liudongmiao** [comment]
愿意调试就发邮件，不愿意请直接关闭问题。

**Comment by liudongmiao** [comment]
没有后续回馈，关闭问题。
