### ISSUE TITLE
Brevent not allowed in some apps.

### ISSUE THREAD

**Issue by samforo** [brevent/Brevent#72]
I don't understand why it isn't possible to make brevent in applications like: chrome, Google, Google services, chromium, Gmail and Sony theme. I don't want them to be active. Before, I could do Brevent on them.

Google Play services I can understand but the rest aren't system applications.

I hope to hear from you soon, thanks.

**Comment by liudongmiao** [comment]
There are details for these apps. If you brevent them, it will be force-stop then active again.

If you don't use them, just uninstall or disable them.
