### ISSUE TITLE
suspend support

### ISSUE THREAD

**Issue by ghost** [brevent/Brevent#722]
devices is realme 5i
android Q (10) Realme UI 1.0
colorOS v7

latest brevent version is used from playstore

i have serious issues
almost all android devices (included mine) are have suspend support but why brevent say my devices is not supported while my devices supported?

i tried some method:
re enable brevent server
restart brevent (Force-Stop)

**Comment by vvb2060** [comment]
brevent will actually test if the application can be suspended using shell permissions.
