### ISSUE TITLE
建议：已支付后建议Root模式再重启后自动激活

### ISSUE THREAD

**Issue by wangzhenxing4** [brevent/Brevent#725]
手机重启后每次都的手动打开进行Root激活，希望作者能够设置一个实验性功能，开机自动激活“并注明警告。为了防止出现问题导致系统无法正常使用，可以制作一个Magisk模块，虽然这个建议没有多大意义，但是，手动显得好麻烦。

**Comment by vvb2060** [comment]
允许黑阈开机启动即可。
不论支付与否，有无root，只要开机时没有看见黑阈的通知，即证明没有允许黑阈开机启动。
