### ISSUE TITLE
询问：待机机制是什么意思

### ISSUE THREAD

**Issue by wangzhenxing4** [brevent/Brevent#727]
待机机制是什么处理方式，软件切换回后台后会怎么处理？是停止服务，降低CPU和存储占有率吗？

**Comment by wangzhenxing4** [comment]
以及还有，是不是切换到后台后并且进入待机，重新打开应用还是上次界面

**Comment by vvb2060** [comment]
https://developer.android.google.cn/training/monitoring-device-state/doze-standby?hl=zh-cn
