### ISSUE TITLE
希望能在Android 11提供旧版USB调试指令和WEB页面激活入口

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [brevent/Brevent#728]
无线调试离开wifi环境需要重新激活，而我个人只要离开工位wifi就断了，比USB调试麻烦很多，虽然我已经背下了usb激活的指令，但是还是希望能在app里提供一个入口

**Comment by vvb2060** [comment]
请保持USB调试打开。切换或关闭 WIFI 后无线调试自动关闭，两种调试均关闭后黑阈服务失效。

**Comment by MichaelSuen-thePointer** [comment]
> 请保持USB调试打开。切换或关闭 WIFI 后无线调试自动关闭，两种调试均关闭后黑阈服务失效。

啥，我的意思是想要app恢复显示usb指令，现在不显示了，只让我去无线调试

**Comment by vvb2060** [comment]
还有什么需求需要使用USB调试呢

**Comment by MichaelSuen-thePointer** [comment]
> 还有什么需求需要使用USB调试呢

我说了呀我的情况是我只要离开工位上个厕所wifi就断了，就要重新激活

**Comment by MichaelSuen-thePointer** [comment]
> 请保持USB调试打开。切换或关闭 WIFI 后无线调试自动关闭，两种调试均关闭后黑阈服务失效。

哦你的意思是，就算使用无限调试，也要保持usb调试打开？我懂了

**Comment by liudongmiao** [comment]
1. 建议是同时开启“USB 调试”与“无线调试”
2. 统一指令，直接访问 brevent.sh 即可，建议使用网页激活不要记之前指令，之前指令在 Android 12 下无法使用～事实上，目前无线激活实际使用的指令并不是提示的指令...当然，意思差不多。

**Comment by liudongmiao** [comment]
我想想，要不要针对 Android 11 单独再出个提示啊。目前有好几种呢。

1. 支持无线调试（Android 11 且连接 Wifi），展示无线调试提示
2. 网络调试
3. android 12 的网页提示（不支持执行指令）
4. 普通提示

现在相当于在第 1 种时，再区分一下，感觉是没有必要的。
