### ISSUE TITLE
OxygenOS 11.0.2.1 Oneplus 7 Pro 锁屏后需要重新启动服务

### ISSUE THREAD

**Issue by SthMax** [brevent/Brevent#729]
未 Root, 每次锁屏之后都需要手动进 App 里面重新用无线调试端口启动服务
应用版本 Play 版 4.2.8.2
年初更新了 Android 11 之后就一直有这个情况

**Comment by vvb2060** [comment]
可能配置了锁屏后自动断网，并且你没有打开USB调试。
WiFi关闭后无线调试自动关闭，无线调试和USB调试均关闭后服务失效。打开USB调试即可。
