### ISSUE TITLE
希望将临时应用图标改成彩色的

### ISSUE THREAD

**Issue by magic8421** [brevent/Brevent#730]
最近版本加入的临时应用功能非常给力 对于顽固流氓很管用 由于不确定那些app有多流氓我把大部分app都加成临时应用了 很好很省电 但是随之出现一个问题 桌面上的app图标都是灰色的很难识别 也不美观 何不弄成彩色的或者加个选项 这样就完美的提升了使用体验

**Comment by liudongmiao** [comment]
停用功能加入非常久，就是为了与正常快捷方式区分才加的灰色图标。
