### ISSUE TITLE
高德地图和钉钉总是建议取消黑域

### ISSUE THREAD

**Issue by wdnmd-qbsmz** [brevent/Brevent#734]
使用黑域限制了高德地图和钉钉的后台，并且设置为激进模式，黑域总是通知在xxx时间内黑域钉钉/高德地图xxx次，点击取消黑域 。我就是想现在这两个应用的后台运行和自启动，有什么好的设置方法吗？

**Comment by Vstory** [comment]
设置里取消黑阈提示

**Comment by vvb2060** [comment]
连续点按设置-系统状态7次，显示强迫症选项菜单，关闭 强行停止检查。或者关闭对应通知渠道。
