### ISSUE TITLE
隔几天就会掉服务怎么解决

### ISSUE THREAD

**Issue by A1578666284** [brevent/Brevent#736]
隔几天就会掉服务，点adb，会弹出一个窗口，显示
“是否允许USB调试？这台计算机的RSA密钥指纹如下: XXXX”
勾选了始终允许之后点击确定过几天还是要掉，然后再次弹窗

华为设备
USB调试一直开着，修改了wifi adb端口为5555

**Comment by A1578666284** [comment]
![Screenshot_20210912_110316_com.android.systemui_edit_107128942754486.jpg](https://user-images.githubusercontent.com/71799870/132970583-d2365845-6fab-4593-8d6e-94ac727f422d.jpg)

**Comment by vvb2060** [comment]
https://txc.qq.com/products/41738/faqs/39058
