### ISSUE TITLE
Feedback on android 12 not working

### ISSUE THREAD

**Issue by banmg** [brevent/Brevent#739]
[BreventLog.txt](https://github.com/brevent/Brevent/files/7394671/BreventLog.txt)
/system/bin/sh: /data/app/~~GChvYPvdhr2aNyhuogXweA==/me.piebridge.brevent-aBgGMs6x8j_FOFDpePBG7g==/lib/arm64/libbrevent.so: inaccessible or not found

**Comment by vvb2060** [comment]
Android11开始不再支持从外部启动，请遵循应用内说明使用无线调试启动。
