### ISSUE TITLE
希望能适配下小米手表

### ISSUE THREAD

**Issue by XingKong746** [brevent/Brevent#742]
我发现能适配小米手表的dpi但是好像没有禁用按钮无法黑域应用，top只有左边有个更多但是点按之后没有反应

**Comment by XingKong746** [comment]
> 我发现能适配小米手表的dpi但是好像没有禁用按钮无法黑域应用，top只有左边有个更多但是点按之后没有反应

**Comment by liudongmiao** [comment]
没有任何计划，包括电视适配。
