### ISSUE TITLE
there is issues that i can't start up brrvent in miui12.5

### ISSUE THREAD

**Issue by Aditems** [brevent/Brevent#746]
logs below 
[logs-v4.2.10-20211220.0422.zip](https://github.com/brevent/Brevent/files/7741544/logs-v4.2.10-20211220.0422.zip)

**Comment by Aditems** [comment]
还是说这是miui的问题？但是我之前也是MIUI12的时候倒是用的好好的啊，那会儿到现在一直都是Android11

**Comment by liudongmiao** [comment]
请看 alpha 版本：https://jianyu.io/br/alpha/

**Comment by liudongmiao** [comment]
你的 root 有毒啊

```
/system/bin/app_process[2]: can't open symlink: No such file or directory
```

**Comment by Aditems** [comment]
我用的是magisk不应该会这样吧

**Comment by vvb2060** [comment]
/system/bin/app_process 符号链接指向的文件不存在，是不是打开了zygisk？现在的magisk已经处理了，更新。
