### ISSUE TITLE
原可以通过root权限使用的黑阈,希望不要取消。

### ISSUE THREAD

**Issue by Christina-cool** [brevent/Brevent#747]
总是需要重新弄，比较麻烦，希望root权限继续保留吧！

**Comment by vvb2060** [comment]
现在（v4.2.11）也可以

**Comment by Christina-cool** [comment]
很抱歉，我没找到，之前在向导中就可以的，能指导一下吗，或者几个图片也可以，多谢了。

南宫雪珊 ***@***.***> 于 2022年1月2日周日 20:54写道：

**Comment by vvb2060** [comment]
1. 正在使用v4.2.11
2. 已经支付
3. 没有对黑阈隐藏root

**Comment by Christina-cool** [comment]
多谢多谢


南宫雪珊 ***@***.***>于2022年1月3日 周一12:03写道：
