### ISSUE TITLE
使用 pm disable-until-used 禁用的应用没有在黑阈列表中展示

### ISSUE THREAD

**Issue by fei-ke** [brevent/Brevent#748]
三星系统提供了一个深度休眠的功能，使用了 `PackageManager.COMPONENT_ENABLED_STATE_DISABLED_UNTIL_USED`  这个标记对应用进行禁用，通过这个标记禁用的应用没有在黑域列表中展示。

使用以下 root 命令在虚拟机中可以复现
`pm disable-until-used <package>`

版本是：v4.2.11 (2021/12/27)

**Comment by liudongmiao** [comment]
因为这个权限非标准，加上之前测试时，发现黑阈无法启用，所以不支持。

黑阈仅展示可以停用/启用的应用。

**Comment by vvb2060** [comment]
是标准API，但三星的行为不太标准。这个状态一般用于多余的系统内置输入法等。

> This application should be considered, until the point where the user actually wants to use it. This means that it will not normally show up to the user (such as in the launcher), but various parts of the user interface can use [GET_DISABLED_UNTIL_USED_COMPONENTS](https://developer.android.com/reference/android/content/pm/PackageManager#GET_DISABLED_UNTIL_USED_COMPONENTS) to still see it and allow the user to select it (as for example an IME, device admin, etc). Such code, once the user has selected the app, should at that point also make it enabled.

adb shell 无法操作这个状态。
> Shell can only change whole packages between ENABLED and DISABLED_USER states unless it is a test package.

所以与`pm disable`相同，不显示这种状态的app。
