### ISSUE TITLE
breboil of play promotion

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#75]
![png0](https://user-images.githubusercontent.com/31381082/29955662-d90d6a64-8f13-11e7-8e4f-96bcef855b16.png)

![png](https://user-images.githubusercontent.com/31381082/29955678-f8c3de6a-8f13-11e7-86ec-0bd9500edab0.png)

柳大，我发现 图1里 play promotion: 3 usd or low * 0.9, other * 1，但在图2里if (promotion)的条件好像没有写完整，other也是 * 0.9，应该是个bug，会导致大于3usd的兑换码的二向箔被打折扣！

**Comment by liudongmiao** [comment]
commit 日志忘了改，忽略吧。
开始写的是对 3 刀及以下，但想到喷子们会说，怎么区别对待，所以去掉了。
