### ISSUE TITLE
如何 停用工作空间 里面的应用

### ISSUE THREAD

**Issue by gmrsuns** [brevent/Brevent#752]
如题,我的手机有 (work profile工作配置) 里面装了一些应用,打开阈 显示在黑阈上已经卸载里,每个 工作空间里的APP显示:(从未打开),实际情况是,可以正常打开也没有被卸载

**Comment by liudongmiao** [comment]
黑阈不支持工作设备，也不支持工作空间，也不建议在工作设备上使用，更不建议黑阈工作相关应用。
