### ISSUE TITLE
Bug - cannot start brevent server, exit with 1 (noperm)

### ISSUE THREAD

**Issue by DNA-DS** [brevent/Brevent#753]
Cannot start brevent server with error 1, no perm.

**Comment by liudongmiao** [comment]
Please give more details:
1. Brevent version
2. Android version.

**Comment by liudongmiao** [comment]
I have see other reported devices, normally, it's due to root devices with other non brevent way.

**Comment by liudongmiao** [comment]
do it by yourself:

```
rm -rf /data/local/tmp/brevent*
```

**Comment by liudongmiao** [comment]
and make sure `/data/local/tmp` is writable for `shell`.

**Comment by akimxeddi** [comment]
i have no idea how to do it but i have same problem.it say
"brevent server is not started.Brevent is in read only mode"
anyone help please 🥺
