### ISSUE TITLE
Shizuku mode support

### ISSUE THREAD

**Issue by sobaee** [brevent/Brevent#754]
Hello dear developer

I know that Brevent now could use ADB over TCP like Shizuku, but don't you think that activating Shizuku, especially after the restart, is much easier than Brevent;
It is easier and for those who have other Shizuku needed tools like Darq, blocker, etc., to be able to activate all of them in one step by enabling the Shizuku app once, you don't have to activate ADB mode for every needed app separately!

For example, me, after every restart, I always have to activate ADB for Brevent, Shizuku, AM, etc., separately one by one!!

It's better to activate ADB only for Shizuku once, and he will do the rest!

**Comment by vvb2060** [comment]
@RikkaW

**Comment by liudongmiao** [comment]
I don't know whether Shizuku supports exec adb command or not, however, Brevent supports.

As the actual Brevent activate command is very difficult since Android 12. I don't think anyone should input it manually. 

Brevent has an API for other app to input the execute command, other app may use it.

**Comment by vvb2060** [comment]
Activating brevent is as easy as shizuku, and brevent can activate shizuku

**Comment by sobaee** [comment]
> Activating brevent is as easy as shizuku, and brevent can activate shizuku

This is the 1st time I know that Brevent could activate Shizuku 🤔
