### ISSUE TITLE
应用操作没有自启管理选项了吗？

### ISSUE THREAD

**Issue by 20171213** [brevent/Brevent#759]
我记得以前有这个选项的？可以加个搜索框方便找一些选项吗？还有微信支付可以转play支付吗要加钱吗

**Comment by liudongmiao** [comment]
应用操作里面具体的操作，取决于操作系统。如果有就会展示。

微信支付不能转 Play 支付。Play 支付以后，可以绑定到微信。（因为有微信登录，但是没有 Play 登录。）

**Comment by 20171213** [comment]
> 应用操作里面具体的操作，取决于操作系统。如果有就会展示。
> 
> 微信支付不能转 Play 支付。Play 支付以后，可以绑定到微信。（因为有微信登录，但是没有 Play 登录。）

明白了
