### ISSUE TITLE
Snapchat when brevent closes automatically 

### ISSUE THREAD

**Issue by gotmilo** [brevent/Brevent#76]
Latest snapchat forces closes without any warning. I disabled brevent and it works after

**Comment by liudongmiao** [comment]
You should upload some log, and don't brevent system-apps.

**Comment by vvb2060** [comment]
Maybe you opened the Brevent immediately, turn it off and try again.

**Comment by gotmilo** [comment]
![screenshot_20170703-155539](https://user-images.githubusercontent.com/26172012/27806557-4ddc518c-6009-11e7-881a-c71b62920341.jpg)
![screenshot_20170703-155532](https://user-images.githubusercontent.com/26172012/27806559-4f6fc470-6009-11e7-961a-76b18969a9bc.png)

Cant catch log because brevent is very aggressive and will close it instantly. No warning to send log, log comes as a size "0"

**Comment by gotmilo** [comment]
very aggressive killing, never used to be a problem

**Comment by liudongmiao** [comment]
@gotmilo As you use "Brevent immediately", please turn off.

If App A depends App B, and you turn on "Brevent immediately", then whenever App A started, which would start App B, and Brevent would force-stop App B immediately. I have optimized this cases: If App B is system package, or allow sync, or payment apps, or running, or widgets, it won't be force-stop immediately.

You can know what's App B from log, or just turn off "Brevent immediately".

**Comment by liudongmiao** [comment]
@gotmilo As I mentioned, please be careful to turn on "Brevent immediately", "show all apps", "show framework apps". Only to do so if you know what you are doing.

**Comment by liudongmiao** [comment]
closed without more feedback.

**Comment by gotmilo** [comment]
Please reopen.... I disabled the close automatically... and show app.. Started fresh clear data... Brevent is to aggressive with snapchat especially this update..
