### ISSUE TITLE
反馈：请启动黑域服务的bug

### ISSUE THREAD

**Issue by GithubApkUser** [brevent/Brevent#76]
柳大，我发现这个弹窗有两个地方
1)从那个弹窗进入开发者选项后返回就没了，没回到黑域直接回到上一级，又要重新打开黑域，很麻烦，希望能修复

**Comment by GithubApkUser** [comment]
2)因为第一点，所以我连接USB后从其他地方打开USB调试，结果返回黑域后那个第一项调试没变，开发者选项也没变复制指令，要×关掉黑域再打开或者从那个弹窗里的开发者选项进去才变。那个弹窗里的开发者选项又不好用，第一点提到了。希望按钮自己会刷新，根据实际情况识别调试已启用，从其他地方打开的也可以！

**Comment by liudongmiao** [comment]
1. 故意的。为了你的第 2 点，因为你启用了开发者选项，没有任何事件，所以你点开开发者选项，直接退出，方便下次加载。

2. 参考第 1 点，没有任何事件。你不从黑域打开开发者选项，而要从其它地方甚至点 7 次打开，怪我咯？
然后你还说这个直接打开开发者选项不好用...你牛你上呗，这部分就是开源的。

3. usb 有事件，会重新生成确认框。

这是一个小概率事件，真闲。android o 下还无法关闭调试模式，一关闭就全都没了。

**Comment by GithubApkUser** [comment]
柳大，这个第一点不好用我和你明说就明白了！我桌面没有黑域图标，我是从抽屉里打开的！一点开发者选项进去打开USB调试再返回，应该已经有事件了，调试允许都出来了！但黑域闪退了直接回到桌面，而且这个闪退后黑域在最近任务里也不见了！那个最近任务有一个开发者选项但点了没反应，连续两下□也没用，没法快速返回！我又要去抽屉里找黑域！

我没有android o，平时是关闭调试，是为了不想手机连电脑乱弹窗，不是闲！

**Comment by liudongmiao** [comment]
不处理。

系统有通知，不代表普通应用可以收到...

**Comment by liudongmiao** [comment]
此外，你离开其它页面以后，还可能开了 网络调试 呢。
所以，直接退出，是稳妥方案。我本人，不会为了极小的点而优化。

**Comment by liudongmiao** [comment]
@GithubApkUser 看下最新测试版 +12

**Comment by GithubApkUser** [comment]
柳大，现在这个好用！插线就变连接，开关调试跟着变，很快很屌了！
就是有时候会有bug，打开调试退回黑域但按钮还是没变。这个也不是每次都能整出来，但确实搞出来过，有时手机没那么快弹出允许，我一急，手速太快，就先退回到黑域等着，这时开发者偶尔不会变成复制指令，就搞出来了。但我换了部别的机就容易搞出来，从开发者点开调试退回黑域后死活都不会变，之后点开发者进去关了再开再允许，返回黑域还是没变。是不是退回到黑域时它在等着接收什么事件，还是和不同的机还是系统有关，两个机都是N

**Comment by liyufan** [comment]
我也是，一开始USB调试开着，进入黑域按钮是“复制指令”；关闭USB调试，进入黑域按钮是“开发者选项”；
再打开USB调试，发现还是“开发者选项”；重新开关调试也没用。然后用第三方网络ADB开关了一下网络调试，回到黑域才变成“复制指令”

**Comment by liudongmiao** [comment]
没有激活，且自动网络激活失败以后，展示请启动黑域服务。策略如下：

1. 向导，一直展示
    https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/AppsDisabledFragment.java#L66


2. 日志，有权限就展示
https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/AppsDisabledFragment.java#L67

3. 有 root 且没有连接电脑或者开启了允许 root 运行，展示 root: https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/AppsDisabledFragment.java#L70

4. 调试开启（属性`init.svc.adbd` 为 `running`） 且 连接电脑，展示复制指令
https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/AppsDisabledFragment.java#L72

5. 其余，展示开发者选项

**Comment by liudongmiao** [comment]
@GithubApkUser 请黑域内发邮件给我，赠送您特别贡献优惠。

**Comment by GithubApkUser** [comment]
问题已解决，搞明白了！谢谢柳大！
