### ISSUE TITLE
一直把支付宝识别成无障碍应用不处理

### ISSUE THREAD

**Issue by jiang-yuan** [brevent/Brevent#761]
用的google最新beta版,一直把支付宝识别成无障碍应用不处理
支付宝没有在系统设置里面的无障碍选项啊

**Comment by vvb2060** [comment]
使用执行指令功能，输入以下内容
```
settings get secure accessibility_enabled
settings get secure enabled_accessibility_services
```
按发送按钮执行，把输出复制上来

**Comment by jiang-yuan** [comment]
[shproc] Process[pid=24089, hasExited=false]
1
[shproc] Process[pid=24089, hasExited=true, exitcode=0]



[shproc] Process[pid=25179, hasExited=false]
com.eg.android.AlipayGphone/com.alipay.mobile.rome.voicebroadcast.a11y.A11yService:com.ext.star.wars/com.dahuo.sunflower.assistant.services.AS:com.ext.star.wars/com.dahuo.sunflower.assistant.services.ASGestures:com.x8bit.bitwarden/com.x8bit.bitwarden.Accessibility.AccessibilityService:com.yunlian.meditationmode/com.yunlian.meditationmode.service.AccSer
[shproc] Process[pid=25179, hasExited=true, exitcode=0]

**Comment by vvb2060** [comment]
> com.eg.android.AlipayGphone/com.alipay.mobile.rome.voicebroadcast.a11y.A11yService

确实有支付宝的无障碍服务，可能是你没有找到，或者系统把它隐藏了。

**Comment by jiang-yuan** [comment]
有解决办法吗

**Comment by vvb2060** [comment]
咨询手机客服

**Comment by vvb2060** [comment]
```
settings put secure enabled_accessibility_services com.ext.star.wars/com.dahuo.sunflower.assistant.services.AS:com.ext.star.wars/com.dahuo.sunflower.assistant.services.ASGestures:com.x8bit.bitwarden/com.x8bit.bitwarden.Accessibility.AccessibilityService:com.yunlian.meditationmode/com.yunlian.meditationmode.service.AccSer
```

**Comment by jiang-yuan** [comment]
这个看起来就是打开除了支付宝之外的无障碍
有两个问题,1.这个会关闭支付宝的无障碍吗 2.是每次重启我都要执行一次?
