### ISSUE TITLE
黑阈方法里面就剩下"只强行停止，不待机"

### ISSUE THREAD

**Issue by thinkiny** [brevent/Brevent#763]
现在使用的android 12，打开了实验的所有特性，发现黑域方法里面就剩下"只强行停止，不待机"这一个选项，请问是什么问题？

**Comment by vvb2060** [comment]
设备不支持待机功能，可能的原因是没有安装gms

**Comment by thinkiny** [comment]
用的是pixel的手机，应该安装了gms

**Comment by vvb2060** [comment]
系统状态中的待机，是支持还是不支持？

**Comment by thinkiny** [comment]
第一次安装的时候是支持其他方式的，不知道改了点什么，现在不支持了

**Comment by vvb2060** [comment]
打开 自适应电池 开关

**Comment by thinkiny** [comment]
找到了，多谢
