### ISSUE TITLE
Backup settings

### ISSUE THREAD

**Issue by HyperCriSiS** [brevent/Brevent#764]
Hi,
Can you please add the possibility to backup all settings? Also it would be nice if the backup could be triggered by an external program to a certain folder.

Thanks and best regards,
Hyper

**Comment by vvb2060** [comment]
Use `Exec command`, Enter the following and execute
```
mkdir /sdcard/Documents/Brevent
cp /data/user_de/0/com.android.shell/me.piebridge.brevent.* /sdcard/Documents/Brevent
```
