### ISSUE TITLE
在Pixel 3XL USB调试一键启动失败

### ISSUE THREAD

**Issue by zlcllxy** [brevent/Brevent#765]
/system/bin/sh: /data/app/~~VFrVLmbQwaGxYaZA-HFxHg==/me.piebridge.brevent-DGhvCPnbr5Tk2cm53KBz0g==/lib/arm64/libbrevent.so: inaccessible or not found

**Comment by vvb2060** [comment]
Android 11及以后的版本不支持USB调试启动，请按照应用内提示使用无线调试，不再需要电脑。
