### ISSUE TITLE
有什么方法可以使我的设备恢复至安装黑阈之前的状态

### ISSUE THREAD

**Issue by joestarChan** [brevent/Brevent#766]
我前段时间装了黑阈，过后发现qq微信经常收不到信息，于是我把黑阈关掉，后来也是会收不到信息。我把黑阈卸载掉，再重新安装，发现里面应用的配置还是我原本的配置。有什么方法可以使我的设备恢复至安装黑阈之前的状态

**Comment by vvb2060** [comment]
在黑阈服务运行时卸载。

**Comment by vvb2060** [comment]
黑阈会对系统造成持久影响的只有停用、暂停和应用操作功能。
如果没有用过这些功能，重启设备使黑阈服务关闭后，与安装黑阈前没有任何区别。如果出现问题，不是因为黑阈。

**Comment by liudongmiao** [comment]
黑阈服务，以 Shell 账号运行，配置文件放在 Shell 账号里。黑阈应用里，点按黑阈，选择“黑阈服务信息” 也可以看到。如果黑阈服务不在运行状态，你可以“黑阈服务信息”或者使用其它APP，找到 Shell 应用后，清除 Shell 应用的数据。

此外，黑阈会在 /data/local/tmp 下生成两个文件，也仅生成。

**Comment by liudongmiao** [comment]
当前版本，卸载黑阈无法删除“黑阈服务配置文件”。

操作如下：
1. 如果有停用任何应用，黑阈内启用
2. 如果有黑阈任何应用，黑阈内恢复
3. 手动清除黑阈服务配置文件，也就是 Shell 配置。

你所见到的配置文件在，只是因为没有删除。即使如此，卸载黑阈并重启以后，黑阈不会有实际功能。

将在下个版本修复。

**Comment by liudongmiao** [comment]
已发新版：https://jianyu.io/br/beta/

黑阈运行时，卸载黑阈将还原所有改动。

**Comment by liudongmiao** [comment]
@joestarChan 请凭邮件截图，发送至 brevent@jianyu.io 领取特别贡献兑换码。
