### ISSUE TITLE
经常没有事件日志，黑阈不再自动工作

### ISSUE THREAD

**Issue by QAQQIAOY** [brevent/Brevent#768]
经常没有事件日志，黑阈不再自动工作。请重启黑阈服务或联系rom供应商 黑阈4.2.14  安卓12
附上日志「logs-v4....1728.zip」，复制整段内容，打开最新版「夸克APP」即可获取。
无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
/~67373OB8c~:/
链接：https://pan.quark.cn/s/d49cd0644ef4

**Comment by vvb2060** [comment]
联系rom供应商，我们无能为力。 #708

**Comment by WanSL** [comment]
没有事件日志后手动重启黑域就好了能不能设置一个自动重启呢
