### ISSUE TITLE
黑域 4.2.14 Android 13 Beta 3 无法启动服务

### ISSUE THREAD

**Issue by KGB333** [brevent/Brevent#769]
无论使用root模式还是adb模式都无法启动服务，adb模式提示permission denied
感谢辛苦开发者！

日志文件：
https://drive.google.com/file/d/17Ofa4IyJXNIhU4q-d92GIClSW6zNBtzP/view?usp=drivesdk

**Comment by cym422948** [comment]
一样的问题

**Comment by King-Sager2333** [comment]
same situation

**Comment by nok-HuUhfA1ApIsP** [comment]
so do I

**Comment by liudongmiao** [comment]
update to latest beta: https://jianyu.io/br/beta/
