### ISSUE TITLE
[User]：申请退款

### ISSUE THREAD

**Issue by neoFelhz** [brevent/Brevent#77]
本人在 @guozixi 代理商手上购买了 Brevent 三刀 Play 优惠码，兑换于日区。
本人现在申请退款。请将 25 RMB 汇款至下述账户中的任意一个：

~删除私人信息~

汇款成功后请将 单位名称、汇款银行、汇款账户、汇款金额 内容发送到 `neofelhz@gmail.com`

如果需要提供关于本人捐赠的相关证明，请自行联系 @guozixi

**Comment by liudongmiao** [comment]
优惠码请找代理商联系，我本人不替不换。其它退款信息，请黑域内发送邮件。

**Comment by liudongmiao** [comment]
@guozixi 他说的 25 是否属实？
如果属实，3 刀券卖 25，良心何安？

**Comment by ghost** [comment]
@liudongmiao 你好，我当时卖给他18，有截图为证，已经邮件给你。需要我发在这里吗？

**Comment by ghost** [comment]
@liudongmiao 当时我卖18到20不等，没有超过20(当时你给我的价格是14每个)

**Comment by guozixi** [comment]
@liudongmiao 现在我是在手机上回复的消息。如果需要，我今天可以上电脑给你发截图，以证清白

**Comment by liudongmiao** [comment]
那他为什么说 25？我本人不退不换。

**Comment by ghost** [comment]
@liudongmiao 可能是记错了，毕竟过了几个月。

我负责退还除成本价的部分。

Over.

**Comment by neoFelhz** [comment]
@liudongmiao 我要求同时退付购买的两个优惠码，仅要求退款 你的个人所得部分。
@guozixi 的个人所得部分，权当作为对他的捐赠。
截止目前为止，我和又拍云客服经理沟通，他们并未收到任何一笔 25 RMB 的汇款。
现在我重复一遍账户和开户人：


```
~删除私人信息~
```

**Comment by liudongmiao** [comment]
@neoFelhz 优惠码一向是不退不换。如果有需求，请找代理商。
如果你有其它支付，请黑域内反馈，play 的发订单号，其它的带截图，都会给你退款。
不要在公开论坛使用任何私密信息，哪怕不是你个人的。

本 issues 关闭，且锁定。

**Comment by liudongmiao** [comment]
刚对 @guozixi 公布了代理商政策，N 大侠，你的退款，由 @guozixi 负责。
guozixi 与我之间的事情，我不必在这里告诉你。

一句话，谁收了你的钱，找谁退款。
