### ISSUE TITLE
ANR不弹框整个UI卡住

### ISSUE THREAD

**Issue by Ostiepo** [brevent/Brevent#772]
BreventServer: send broadcast timed out
[boot.log](https://github.com/brevent/Brevent/files/8882131/boot.log)

**Comment by vvb2060** [comment]
上传 /data/anr 。另外，可能是会修改系统的插件、模块等导致。

**Comment by liudongmiao** [comment]
在系统没有完全启动时，send broadcast 可能就是会 timed out.
