### ISSUE TITLE
Android 13 Beta 3.1 使用root模式会有一定几率机子完全冻结

### ISSUE THREAD

**Issue by KGB333** [brevent/Brevent#773]
今天Android 13更新了 Beta 3.1，不清楚是不是这个原因造成的，使用root模式过一段时间机子就会卡死，需要电源键硬重启，现在一直使用只读模式就没有问题（黑域版本4.2.16）

**Comment by KGB333** [comment]
![Screenshot_20220611-193416.png](https://user-images.githubusercontent.com/35756327/173186163-411991ec-c19f-4d05-8817-4e5cf93b7493.png)目前不启用黑域的话使用正常

**Comment by vvb2060** [comment]
展开黑阈app侧栏，点按联系，再点按日志，上传日志压缩包或发送邮件

**Comment by KGB333** [comment]
> 展开黑阈app侧栏，点按联系，再点按日志，上传日志压缩包或发送邮件

已发邮件，感谢

**Comment by KGB333** [comment]
我把系统刷回去Beta3就没遇到过了
