### ISSUE TITLE
Exception.

### ISSUE THREAD

**Issue by 1ansam** [brevent/Brevent#774]
[brevent.20220613.0927.9860.txt](https://github.com/brevent/Brevent/files/8887256/brevent.20220613.0927.9860.txt)
[logcat.ui.9860-20220613.0928.txt](https://github.com/brevent/Brevent/files/8887257/logcat.ui.9860-20220613.0928.txt)

Google Pixel 4XL Android 13
TPB3.220513.017

**Comment by vvb2060** [comment]
https://dl.jianyv.com/br/beta/

**Comment by 1ansam** [comment]
@vvb2060 Thanks.
