### ISSUE TITLE
重启手机激活后界面卡死

### ISSUE THREAD

**Issue by hero616** [brevent/Brevent#775]
重启手机激活后连接电脑用adb命令激活应用后一直在一个界面无法退出。界面提示：正在检查黑域服务，请稍候……
[日志文件连接](http://ys-e.ysepan.com/607970658/916152742/i485J3K4L1KQN3VHgMjJ07/logs-v4.2.16-20220616.1553.zip)

**Comment by liudongmiao** [comment]
无法访问日志文件。

一般来说，目前建议使用网页版本的一键激活：https://brevent.sh
