### ISSUE TITLE
Background timeout is always reset to zero on Android 13

### ISSUE THREAD

**Issue by lj0307222** [brevent/Brevent#778]
原生安卓12在黑阈主界面，应用超时一下拉刷新就变为0，后台不划卡一直不会强行停止。

**Comment by vvb2060** [comment]
需要上传日志

**Comment by lj0307222** [comment]
[brevent.20220627.1306.26901.txt](https://github.com/brevent/Brevent/files/8988860/brevent.20220627.1306.26901.txt)
[logcat.crash-20220627.1317.txt](https://github.com/brevent/Brevent/files/8988861/logcat.crash-20220627.1317.txt)
[logcat.events-20220627.1317.txt](https://github.com/brevent/Brevent/files/8988862/logcat.events-20220627.1317.txt)
[logcat.system-20220627.1317.txt](https://github.com/brevent/Brevent/files/8988863/logcat.system-20220627.1317.txt)

**Comment by vvb2060** [comment]
不含有效信息，请启动服务，并在复现问题后发送完整日志压缩包

**Comment by lj0307222** [comment]
[Uploading logs-v4.2.16-20220701.2331.zip…]()

**Comment by lj0307222** [comment]
logs-v4.2.16-20220701.2331.zip

**Comment by lj0307222** [comment]
[logs-v4.2.16-20220701.2331.zip](https://github.com/brevent/Brevent/files/9030016/logs-v4.2.16-20220701.2331.zip)

**Comment by vvb2060** [comment]
你没有启动服务？

**Comment by lj0307222** [comment]
![Screenshot_20220701-233846_黑阈](https://user-images.githubusercontent.com/61595433/176926463-a9d7f124-43b7-44e8-9077-e841b6efac91.png)
shen'm启动了呀

**Comment by gtszx1** [comment]
安卓12.1  重进或刷新app都会导致后台超时计时清零。

**Comment by liudongmiao** [comment]
Please check alpha version 4.2.17-alpha1 or later: https://jianyu.io/br/alpha/

**Comment by gtszx1** [comment]
> 



> 请检查 alpha 版本 4.2.17-alpha1 或更高版本：https://jianyu.io/br/alpha/

这个版本没问题了

**Comment by liudongmiao** [comment]
@gtszx1 请发邮件至 brevent@jianyu.io ，将赠送特别贡献兑换码。

**Comment by liudongmiao** [comment]
@lj0307222 请发邮件至 [brevent@jianyu.io](mailto:brevent@jianyu.io) ，将赠送特别贡献兑换码。
