### ISSUE TITLE
Cannot cache play payment, please try again!

### ISSUE THREAD

**Issue by Angeloxdd** [brevent/Brevent#779]
Hi i have paid 2 times and i become this error.  My phone is rooted with magisk!

**Comment by HawnHan** [comment]
Same as you = =

**Comment by liudongmiao** [comment]
Try again. And make sure Brevent can visit aws.jianyv.com

**Comment by Angeloxdd** [comment]
IT'S WORK AGAIN AND IT RECOGNIZE MY LAST PAYMENT. THANKS!

**Comment by HawnHan** [comment]
> Try again. And make sure Brevent can visit aws.jianyv.com

Strange.Reinstall again it's normal

**Comment by liudongmiao** [comment]
It was an issue of brevent payment server.
