### ISSUE TITLE
无法待机，电池未最佳化

### ISSUE THREAD

**Issue by jackylau2818** [brevent/Brevent#78]
是什么意思？

**Comment by vvb2060** [comment]
我也想问你是什么意思，是想问哪方面？

如果把应用加入了电池优化白名单就会提示这个，被豁免的应用不会被待机，只能被强行停止。
可以在设置-电池-电池优化中找到列表并进行设置。

待机是自Android6.0后引入的一项新功能，应用被待机后将不能联网、执行任务与同步。黑域默认先待机应用，再强行停止，避免应用反复被停止和启动。
如果你接下来长时间都不会再用某个应用，那你可以使用“从最近任务列表划掉”来离开应用，黑域会直接强行停止它。

**Comment by liudongmiao** [comment]
https://developer.android.google.cn/training/monitoring-device-state/doze-standby.html?hl=zh-cn
