### ISSUE TITLE
no events

### ISSUE THREAD

**Issue by legendtang** [brevent/Brevent#78]
```shell
sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
WARNING: run as root is experimental!!!
checking.....brevent_server started, pid: 9465
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-03 10:40:16.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-03 10:40:16.000' -d -s BreventLoader BreventServer
07-03 10:40:17.584  9378  9378 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-03 10:40:18.839  9465  9465 D BreventServer: get service: package
07-03 10:40:18.853  9465  9465 I BreventServer: starting Brevent Server 1.3.2
07-03 10:40:18.881  9465  9465 D BreventServer: get service: package
07-03 10:40:18.883  9465  9465 I BreventServer: brevent user: 0, uid: 0
07-03 10:40:18.886  9465  9465 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-03 10:40:18.925  9465  9465 I BreventServer: loading brevent list
07-03 10:40:18.925  9465  9465 I BreventServer: loading brevent conf
07-03 10:40:18.928  9465  9465 D BreventServer: get service: appwidget
07-03 10:40:18.941  9465  9465 D BreventServer: get service: usagestats
07-03 10:40:19.850  9465  9465 D BreventServer: check and brevent
07-03 10:40:19.851  9465  9465 D BreventServer: get service: notification
07-03 10:40:19.920  9465  9465 D BreventServer: get service: activity
07-03 10:40:19.934  9465  9465 D BreventServer: get service: alarm
07-03 10:40:19.936  9465  9465 D BreventServer: get service: wallpaper
07-03 10:40:19.955  9465  9465 D BreventServer: get service: batterystats
07-03 10:40:20.065  9465  9465 D BreventServer: check again in 3600s
07-03 10:40:20.065  9465  9465 D BreventServer: check and brevent, took 215ms
07-03 10:40:20.106  9465  9465 E BreventServer: no events
07-03 10:40:20.135  9378  9378 E BreventLoader: worker 9465 exited with status 1
07-03 10:40:20.135  9378  9378 D BreventLoader: signal arrived, update: 0
07-03 10:40:20.136  9364  9364 D BreventLoader: worker 9378 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above
```

LOS 14.1 with MagiskSU

**Comment by vvb2060** [comment]
> 07-03 10:40:20.106  9465  9465 E BreventServer: no events


Do not turn off Logger buffer sizes in the Developer options.

**Comment by legendtang** [comment]
@vvb2060 It is not disabled. 256k should be enough?

**Comment by vvb2060** [comment]
Do you run `logcat -b events` with any output?

**Comment by legendtang** [comment]
@vvb2060 Of course, there are some. However no outputs from Brevent.

**Comment by liudongmiao** [comment]
@legendtang 

```
logcat -b events -s am_proc_start
```

**Comment by liudongmiao** [comment]
@legendtang Brevent assumes that there should be some `am_proc_start` in the events.
You can force-stop Brevent (or other app), then launch it, Android will emit a `am_proc_start` event.

**Comment by legendtang** [comment]
@liudongmiao Pretty strange there aren't any from `am_proc_start` with force killing an app but I'm pretty sure logging is enabled. Any thoughts on this?

**Comment by liudongmiao** [comment]
@legendtang Brevent depends following events  to determine when and how to check and brevent:
- `am_proc_start`: Service are started. Brevent will force-stop it later if it doesn't launch any activity.
- `am_restart_activity`: Activity is focused. 
- `am_resume_activity`: Activity is focused, variant 2.

If there is no such events, then Brevent just doesn't work. There are other 7 events to help Brevent work better.

**Comment by liudongmiao** [comment]
@legendtang You can try the latest testing Brevent: https://piebridge.me/br/next/

I have removed the detecting events using history events.

**Comment by legendtang** [comment]
I assume that your updated version will start but there is still no `am_proc_start` to let it work as service. When I found the root cause I will re-open the issue. Thanks anyway!

**Comment by liudongmiao** [comment]
@legendtang 

Please do this:

1. logcat in one console, this will logcat all events to /sdcard/events.log

```
logcat -f /sdcard/events.log -b events 
```

2. if you have play store, then force-stop it. And open Brevent, navigate into Settings. 
After it show play store, then ctrl-c in the step 1.  Search "com.android.vending" in events.log.

3. if you don't have play store, please check other apps, you can using sync accounts, or desktop widgets.
