### ISSUE TITLE
黑阈激活失败

### ISSUE THREAD

**Issue by Procyon-3** [brevent/Brevent#782]
/system/bin/sh: /data/app/~~daG_dygLbeB3WGuIDoty9g==/me.piebridge.brevent-bl1u4fBIqRAM1s0sGynFOw==/lib/arm64/libbrevent.so: inaccessible or not found
黑阈服务开启失败，请将日志与具体情况发至 https://github.com/brevent/Brevent/issues 来解决问题。

**Comment by Procyon-3** [comment]
先在黑阈中获取root后顺利激活

**Comment by vvb2060** [comment]
Android 11 及以上只能使用无线调试启动服务，使用USB调试请通过网页启动服务。
