### ISSUE TITLE
force stop not working

### ISSUE THREAD

**Issue by occupydims** [brevent/Brevent#784]
before stop option isn't working. I have it set to do that after 5 minutes but when I go to the settings after the time the application is still running

**Comment by vvb2060** [comment]
https://github.com/brevent/Brevent/blob/38bcdbf7d31644360a6b9b7c416831b13ece2920/brevent/src/main/res/values/strings.xml#L22

**Comment by vvb2060** [comment]
This issue is closed because there is no log.
