### ISSUE TITLE
how to solve this? 

### ISSUE THREAD

**Issue by SAJIBBH** [brevent/Brevent#787]
![114302097-2e4e3e00-9ae5-11eb-8416-acc09c6dd4a1](https://user-images.githubusercontent.com/76970482/194811841-a96cef32-6b5a-4f23-915f-ba5c07c1039d.jpg)

**Comment by AdenXie** [comment]
Disable Permission Monitoring or Open ADB debugging

**Comment by liudongmiao** [comment]
This should be xiaomi / oppo's rom. There are some experiment features, like securu adb, or "permission monitor".
