### ISSUE TITLE
OPPO Reno6 激活失败 Activation Failed

### ISSUE THREAD

**Issue by AdenXie** [brevent/Brevent#788]
ColorOS12.1 Android12
图一是我尝试使用Shizuku+Termux激活失败
Figure 1 is that I try to use Shizuku+Termux to active Brevent but failed
图二是我用无线调试失败，让我填写端口（不是配对码）显示失败
Figure 2 is that I failed to use wireless debugging, let me fill in the port (not the pairing code) display failure
![Screenshot_2022-10-23-08-38-54-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/89302318/197368082-b390dd8b-8db8-4568-aa02-aaf5cda73d06.jpg)
![Screenshot_2022-10-23-08-40-10-82_e88630c4e740b41437a1b6dc6436479a](https://user-images.githubusercontent.com/89302318/197368084-1eb3a065-abde-478a-92f3-aee2e033e652.jpg)
最后只能通过电脑端一键激活
Finally, it can only be activated by one key on the computer
有没有人有解决方案？
Does anyone have a solution?

**Comment by liudongmiao** [comment]
通常来说，认真阅读 黑阈提示 应当能解决问题....

**Comment by AdenXie** [comment]
> 通常来说，认真阅读 黑阈提示 应当能解决问题....

黑域提示？我按照黑域提示打开了禁止权限监控，而且这种情况只发生在本地激活黑域。电脑端的一键激活是可以用的，我只是想知道无法本地激活是什么原因

**Comment by vvb2060** [comment]
本地激活，是什么东西

**Comment by AdenXie** [comment]
> 本地激活，是什么东西

就是用无线调试或者Shizuku+Termux不用电脑激活

**Comment by vvb2060** [comment]
Android11起只支持无线调试

**Comment by vvb2060** [comment]
你好像把无线调试端口和配对端口搞混了

**Comment by vvb2060** [comment]
总之，认真阅读 黑阈提示 应当能解决问题。这里有图文教程 https://www.coolapk.com/feed/18348062?shareKey=M2M1ZDQyMTFhYzUzNjA0NDcyNjc

**Comment by AdenXie** [comment]
> Android11起只支持无线调试

主要是我在我的平板（ColorOS12 Android11）上可以用Termux+Shizuku的方式输入adb命令激活黑域，我以为手机也可以
当时手机是让我通过无线调试，然后输入端口，输入过端口以后出现了图二的错误

**Comment by AdenXie** [comment]
> 总之，认真阅读 黑阈提示 应当能解决问题。这里有图文教程 https://www.coolapk.com/feed/18348062?shareKey=M2M1ZDQyMTFhYzUzNjA0NDcyNjc

感谢指导，我明白了

**Comment by vvb2060** [comment]
> 主要是我在我的平板（ColorOS12 Android11）上可以用Termux+Shizuku的方式输入adb命令激活黑域

Android11是黑阈的软限制，Android12起是AOSP的硬限制
