### ISSUE TITLE
cannot listen port

### ISSUE THREAD

**Issue by czhsqqc** [brevent/Brevent#79]
--- crash start ---
>>> logcat -b crash -t '07-04 09:55:32.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-04 09:55:32.000' -d -s BreventLoader BreventServer
07-04 09:55:33.509 25712 25712 D BreventLoader: loader path: /data/app/me.piebri
dge.brevent-1/base.apk
07-04 09:55:34.014 25723 25723 D BreventServer: get service: package
07-04 09:55:34.017 25723 25723 I BreventServer: starting Brevent Server 1.3.2
07-04 09:55:34.023 25723 25723 D BreventServer: get service: package
07-04 09:55:34.027 25723 25723 I BreventServer: brevent user: 0, uid: 2000
07-04 09:55:34.028 25723 25723 I BreventServer: brevent data directory: /data/us
er_de/0/com.android.shell
07-04 09:55:34.089 25723 25723 I BreventServer: loading brevent list
07-04 09:55:34.093 25723 25723 I BreventServer: load /data/user_de/0/com.android
.shell/me.piebridge.brevent.list, size: 1
07-04 09:55:34.094 25723 25723 I BreventServer: loading brevent conf
07-04 09:55:34.099 25723 25723 D BreventServer: get service: appwidget
07-04 09:55:34.103 25723 25723 D BreventServer: get service: usagestats
07-04 09:55:34.544 25723 25723 D BreventServer: check and brevent
07-04 09:55:34.546 25723 25723 D BreventServer: get service: notification
07-04 09:55:34.663 25723 25723 D BreventServer: get service: activity
07-04 09:55:34.674 25723 25723 D BreventServer: get service: alarm
07-04 09:55:34.675 25723 25723 D BreventServer: get service: wallpaper
07-04 09:55:34.708 25723 25723 D BreventServer: get service: batterystats
07-04 09:55:34.832 25723 25723 D BreventServer: check again in 3600s
07-04 09:55:34.832 25723 25723 D BreventServer: check and brevent, took 287ms
07-04 09:55:34.912 25723 25723 E BreventServer: no events
07-04 09:55:34.964 25712 25712 E BreventLoader: worker 25723 exited with status
1
07-04 09:55:34.965 25712 25712 D BreventLoader: signal arrived, update: 0
07-04 09:55:34.966 25707 25707 D BreventLoader: worker 25712 exited with status
0
--- brevent end ---

**Comment by vvb2060** [comment]
> 07-04 09:55:34.912 25723 25723 E BreventServer: no events

Do not turn off Logger buffer sizes in the Developer options.

**Comment by czhsqqc** [comment]
@vvb2060 I have set up to 16M, still the same as before

**Comment by vvb2060** [comment]
@czhsqqc Do you run `logcat -b events -s am_proc_start` with any output?

Brevent assumes that there should be some `am_proc_start` in the events.
You can force-stop Brevent (or other app), then launch it, Android will emit a `am_proc_start` event.

**Comment by czhsqqc** [comment]
@vvb2060 I rebooted my phone and worked, thank you
