### ISSUE TITLE
安卓13bug

### ISSUE THREAD

**Issue by lj0307222** [brevent/Brevent#791]
升级到如图版本，就失效了，不会计时。
![Screenshot_20221213-170024_设置](https://user-images.githubusercontent.com/61595433/207273289-6bb1bd92-8ed1-457b-bfc3-25cdab2c61ee.png)

日志

[logs-v4.2.17.2-20221213.1657.zip](https://github.com/brevent/Brevent/files/10216133/logs-v4.2.17.2-20221213.1657.zip)

**Comment by Oblivion130** [comment]
12月更新后什么手机都一样，只能等大佬修了

**Comment by jayjd** [comment]
> 12月更新后什么手机都一样，只能等大佬修了

我也是昨天更新后 就用不了了 提示没有事件日志，无法自动工作。

**Comment by liudongmiao** [comment]
已发布 Beta 版，请前往测试：https://jianyu.io/br/beta/

**Comment by lj0307222** [comment]
> 已发布 Beta 版，请前往测试：https://jianyu.io/br/beta/

没问题了，一切正常。

**Comment by Kruegerrr** [comment]
Dear developer, please roll out the fixed version on Google Play for all countries ASAP.
