### ISSUE TITLE
sony xperia 1ii黑阈自动停止

### ISSUE THREAD

**Issue by lcn569451380** [brevent/Brevent#795]
国行索尼xperia 1ii ，黑阈只能无线调试启动，且一段时间后自动停止服务，这个是什么原因？怎么解决？

**Comment by vvb2060** [comment]
不要关闭 USB 调试

**Comment by lcn569451380** [comment]
确实没有关闭usb调试，我另外一个机器xperia pro 日版就没这个情况，国行这个马克兔只要无线调试启动之后，过一会就自动关闭服务了，又得重新调试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月22日(周日) 上午9:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [brevent/Brevent] sony xperia 1ii黑阈自动停止 (Issue #795)




 
不要关闭 USB 调试
