### ISSUE TITLE
“反馈”中的一个强迫症式的文本错误

### ISSUE THREAD

**Issue by jzl2163** [brevent/Brevent#8]
点击“反馈”后，弹出框第二个按钮的文本为“GITHUB”(大写)，而非GitHub官方所表述的“GitHub”。
虽然也不影响什么，但是作为强迫症患者的我(及可能存在的一大帮子人)看着总有些怪怪的。
如果这是文本错误，且可以修复的话，请将其修复，谢谢。

**Comment by liudongmiao** [comment]
根据规范，按钮都是大写，这是默认样式。

**Comment by liudongmiao** [comment]
https://github.com/brevent/Brevent/blob/master/brevent/src/main/res/values/strings.xml#L116

https://github.com/brevent/Brevent/blob/master/brevent/src/main/res/values-zh-rCN/strings.xml#L114

你可以看原始文本。我本人没有任何想法要去改系统的默认主题。
