### ISSUE TITLE
卡在“正在获取状态”

### ISSUE THREAD

**Issue by Jisxu** [brevent/Brevent#8]
[run.log.txt](https://github.com/brevent/Brevent/files/1026089/run.log.txt)
[crash.log.txt](https://github.com/brevent/Brevent/files/1026091/crash.log.txt)
- 系统：魔趣7.1.2 0523 夜版
- selinux状态：执行中
- 应用来源：play 1.1.11
- adb模式启动

**Comment by liudongmiao** [comment]
```
send broadcast timed out
```

继续等吧。如果一直等不到，就是真的无法使用。黑域当前依赖广播传递消息。

**Comment by liudongmiao** [comment]
我会在下个版本里，尝试解决这个问题。

**Comment by amdth** [comment]
@Jisxu 为什么不直接贴上日志呢？

**Comment by liudongmiao** [comment]
@amdth 有日志就行，不必非用贴上。

而且，他报的是一个已知问题，日志并不一定需要。
只是我还在想要怎么解决。

**Comment by liudongmiao** [comment]
@Jisxu 请看下最新测试版：https://piebridge.me/br/next/

**Comment by Jisxu** [comment]
@liudongmiao 问题解决，能快速响应服务。
