### ISSUE TITLE
如何添加其他用户（例如多开或工作资料产生的多用户）的App？

### ISSUE THREAD

**Issue by Mosney** [brevent/Brevent#802]
目前Brevent只允许在主用户使用，仅在其它用户安装的App会在列表中会显示为已卸载无法选中。

**Comment by Vstory** [comment]
黑阈不支持非主用户应用

**Comment by liudongmiao** [comment]
黑阈没有任何计划支持多用户，因为这些主要是给工作应用，以及实现起来非常复杂。
