### ISSUE TITLE
VIVO X90 PRO + 无法开启黑阀

### ISSUE THREAD

**Issue by zhongshangchi** [brevent/Brevent#803]
我都按步骤来了，可是最后都是提示这个！inaccessible or not found
/system/bin/sh: /data/app/~~pobGs4LsQingbdwbJwsZbA==/me.piebridge.brevent-RMTIuIVP8wi5dSChKxsI3w==/lib/arm64/libbrevent.so: inaccessible or not found
黑阈服务开启失败
[BreventLog.txt](https://github.com/brevent/Brevent/files/10778530/BreventLog.txt)

**Comment by vvb2060** [comment]
用浏览器打开 [brevent.sh](https://brevent.sh/) ，通过网页启动或换成网页显示的新命令
