### ISSUE TITLE
是否不支持鸿蒙3.0了，今天升级后始终无法启动。

### ISSUE THREAD

**Issue by leyan22** [brevent/Brevent#804]
手机是荣耀30pro+，黑阈版本4.2.18。今天升级了鸿蒙3.0后，无论是用电脑连接USB 还是用以前的黑阈启动器 都无法启动黑阈 只能进入只读模式。

**Comment by vvb2060** [comment]
按照应用内提示，访问 [brevent.sh](https://brevent.sh/) 启动服务。
