### ISSUE TITLE
android 12一直弹出toast

### ISSUE THREAD

**Issue by aaalzk** [brevent/Brevent#808]
［问题］底部会一直提示
“XXX（包名）已被放入受限存储分区”
且关闭通知权限后依然提示。
［发生时间］黑域 净化应用时。

版本4.2.17.2

[![ppfe99H.md.png](https://s1.ax1x.com/2023/04/02/ppfe99H.md.png)](https://imgse.com/i/ppfe99H)

**Comment by vvb2060** [comment]
非生产系统会提示，可以用appops禁止systemui发送toast
