### ISSUE TITLE
能不能写个一键脚本 先谢谢了

### ISSUE THREAD

**Issue by yangyou2000** [brevent/Brevent#81]
我在一键脚本里的阅读说明里面看到了大神的网址 我希望大神能抽空更新一下脚本 给我们这群不懂代码的小白一个工具来遏制国内的毒瘤应用 先谢谢了

**Comment by liudongmiao** [comment]
目前就一句话啊。但是，如果你电脑上有其它的 adb，就不是我能处理的事了。

**Comment by ghost** [comment]
就一句话的脚本，这么简单，我都会写🤒

**Comment by ghost** [comment]
先切换到你放adb的文件夹，再输入黑域的那个命令就好了。
