### ISSUE TITLE
Galaxy A13 I can't activate (fake:signature)

### ISSUE THREAD

**Issue by Desnecessauro22** [brevent/Brevent#812]
HELP MEEEEEEEEEEEEE 
fake:signature
![Screenshot_20230525_141642_Brevent](https://github.com/brevent/Brevent/assets/70909921/50af6690-7485-414f-a533-35f717eb4ba4)

**Comment by liudongmiao** [comment]
It seems there are issues on Samsung A13. Please contact via email, I'll send you test apk.

**Comment by liudongmiao** [comment]
I use Samsung A13 from https://developer.samsung.com/remotetestlab/devices/101/galaxy-mobile with Brevent 4.2.18.3 (https://jianyv.com/br/), and check Android 12 and Android 13, it works.

**Comment by Desnecessauro22** [comment]
> I use Samsung A13 from https://developer.samsung.com/remotetestlab/devices/101/galaxy-mobile with Brevent 4.2.18.3 (https://jianyv.com/br/), and check Android 12 and Android 13, it works.

whats your email?

**Comment by liudongmiao** [comment]
@Desnecessauro22 brevent@jianyu.io
please contact us, I'll send you test apk.

**Comment by liudongmiao** [comment]
@Desnecessauro22 any feedback?
