### ISSUE TITLE
crdroid适配

### ISSUE THREAD

**Issue by JamesLiu0802** [brevent/Brevent#813]
能否适配一下crdroid？只要用crdroid，不管哪款手机，都没办法自动工作，一年更新不了四次。

**Comment by JamesLiu0802** [comment]
![Uploading Screenshot_20230528-005438_黑阈.png…]()

**Comment by vvb2060** [comment]
可能是这个系统关闭了事件日志，无法支持，你应该要求系统维护者恢复正常的日志行为。 #708

**Comment by JamesLiu0802** [comment]
好的，谢谢
