### ISSUE TITLE
原生Android13开启动态gms后不断弹出“启用谷歌play服务”的弹窗

### ISSUE THREAD

**Issue by NiuHK** [brevent/Brevent#814]
![4a3f1e0194c9a706f6cfc9117e9e680](https://github.com/brevent/Brevent/assets/129147116/59aa1237-1cea-49b0-b9d5-93d57552f3fc)
我的安卓版本
为pep原生系统

//黑域为酷安最新版

![1c12d0b1fab6e06e7fc88cde4e0ffd1](https://github.com/brevent/Brevent/assets/129147116/dc6e69d5-ab47-4e7d-b292-48b96d9b219e)
开启动态gms不断弹窗-Google play的适用范围

//看日志说修复了安卓11的弹窗问题，希望可以修复安卓13的

**Comment by vvb2060** [comment]
日志呢，在应用内保存后上传到GitHub

**Comment by NiuHK** [comment]
> 日志呢，在应用内保存后上传到GitHub

[logs-v4.2.19-20230623.2321.zip](https://github.com/brevent/Brevent/files/11849860/logs-v4.2.19-20230623.2321.zip)

这样吗

**Comment by NiuHK** [comment]
非常感谢作者，这个小问题要是能修好那黑域在我设备上就是真的好使了，别的类似的试过，根本没这个好用。

**Comment by liudongmiao** [comment]
这就是这个功能正常的一个提示。

1. 动态GMS，会保证你主动打开时，**标识为GMS的应用**，自动启用GMS。
2. 至于通知，自己想办法，GMS相关的通知，都在一个通知渠道里（如果支持通知渠道），只能一个个关。

**Comment by NiuHK** [comment]
> 这就是这个功能正常的一个提示。
> 
> 1. 动态GMS，会保证你主动打开时，**标识为GMS的应用**，自动启用GMS。
> 2. 至于通知，自己想办法，GMS相关的通知，都在一个通知渠道里（如果支持通知渠道），只能一个个关。

可以一个一个关，但是下次还会弹通知

**Comment by liudongmiao** [comment]
@NiuHK 自己看设备吧，一般都是有一个通知渠道，叫 谷歌服务 之类的。

曾经有一次，黑阈想弄个功能，把这个通知渠道给关了，后面想了想，还是没有动它

**Comment by NiuHK** [comment]
> @NiuHK 自己看设备吧，一般都是有一个通知渠道，叫 谷歌服务 之类的。
> 
> 曾经有一次，黑阈想弄个功能，把这个通知渠道给关了，后面想了想，还是没有动它

谢谢，但是有可能因为我是pe系统，并没有通知渠道这个功能而且手动关闭后第二次还是会出现，现在已经找到合适的模块代替了，谢谢！
