### ISSUE TITLE
A13黑域无法 Root 开机自启

### ISSUE THREAD

**Issue by NiuHK** [brevent/Brevent#815]
![0b586b4aec98eb41a3e43e50f7484f6](https://github.com/brevent/Brevent/assets/129147116/e441e119-2464-4b4b-96e8-424a3cb25420)

**Comment by NiuHK** [comment]
如上图，开机后的提示，使用root模式，并且尝试过加固为系统应用

**Comment by vvb2060** [comment]
付费后可以root开机自动启动

**Comment by NiuHK** [comment]
> 付费后可以root开机自动启动

付费了，5二向泊，还是不行

**Comment by NiuHK** [comment]
[logs-v4.2.19-20230623.2321.zip](https://github.com/brevent/Brevent/files/11849865/logs-v4.2.19-20230623.2321.zip)
这是日志

**Comment by liudongmiao** [comment]
黑阈从来不保证可以开机自启，只是尽力尝试。

你的日志，也没有任何开机启动相关的信息。甚至你的信息，没有任何黑阈界面相关日志。

黑阈也不对 Root 提供任何提示支持。
