### ISSUE TITLE
realme x50pro 系统coloros12 自动黑阈不支持

### ISSUE THREAD

**Issue by yutouyes** [brevent/Brevent#816]
![Screenshot_2023-07-15-22-31-13-37_e88630c4e740b41437a1b6dc6436479a](https://github.com/brevent/Brevent/assets/17039457/6b828b69-8b16-42db-948c-3df2c02fecec)
![Screenshot_2023-07-15-22-29-28-97_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/brevent/Brevent/assets/17039457/5c0010a0-0779-4f05-8ff9-7e12311e858b)
按指导将日志区从256kb增至1M、重启黑阈服务，还是显示不支持自动黑阈，请问是否有解决办法

**Comment by liudongmiao** [comment]
最新版应当解决了这个问题
