### ISSUE TITLE
Galaxy S8 Snapdragon SamPawn root not working

### ISSUE THREAD

**Issue by jackie099** [brevent/Brevent#82]
Here is the log.
samsung/dream2qlteue/dream2qlteue:7.0/NRD90M/G955U1UEU1AQG2:user/release-keys
SELinux: false

WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '09-05 01:28:11.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-05 01:28:11.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
You should have see the title: please switch to another su.

Your su, cannot execute any command in su mode.
