### ISSUE TITLE
无法黑域带通知应用

### ISSUE THREAD

**Issue by mokongh** [brevent/Brevent#82]
无法正常黑域LastPass, Android O

**Comment by mokongh** [comment]
黑域版本：1.3.2
LastPass版本：4.2.507

**Comment by liudongmiao** [comment]
提示呢？

**Comment by mokongh** [comment]
其实有点标题党…
黑域应用的时候能黑域成功
主要是点击“全部清除”之后，黑域把其他的应用程序都给强行停止了，唯独LastPass还在运行(显示在通知栏提示正在运行)，要自己去关

**Comment by liudongmiao** [comment]
进黑域查看这个 APP，看是否有时间。
如果有时间，并且通知栏提示正在运行，不处理。（因为他明确告诉了你他在运行）
如果没有时间，回到桌面，数 1, 2, 3 ，再进入黑域，如果还在，提取调试级别日志发上来。

**Comment by liudongmiao** [comment]
没有进一步反馈，关闭。
