### ISSUE TITLE
自动清理桌面显示程序（BUZZ)

### ISSUE THREAD

**Issue by iceye2072** [brevent/Brevent#83]
Buzz主题会在进入其他app后被黑域清理掉，按Home键 会重启buzz，后台显示重新开始运行。试过更改设置没效果，删除黑域后恢复正常，重新安装黑域，经过一定时间后又会出现。

**Comment by vvb2060** [comment]
将buzz桌面设置为默认主屏幕应用，或者别黑域它。

**Comment by iceye2072** [comment]
没有黑域BUZZ，已设置成主屏应用。但还是会被清理

**Comment by vvb2060** [comment]
那带上黑域的工作日志，证明是黑域干的。
位置在/sdcard/Android/data/me.piebridge.brevent/server.txt
你也可以自己搜索buzz包名，看黑域有没有处理过它
