### ISSUE TITLE
1.3.3改完指令无法激活了

### ISSUE THREAD

**Issue by asdfeeshy** [brevent/Brevent#83]
批处理如下

`@echo off
adb devices
sh /data/data/me.piebridge.brevent/brevent.sh
pause`

不能激活黑域服务，失败后的提示

` List of devices attached
988678345445535649      device
'sh' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
请按任意键继续. . .
`

**Comment by liudongmiao** [comment]
界面上，提示的明明是 
```
adb shell sh ....
```
你输入成 `adb devices sh` 是要闹哪样？

**Comment by asdfeeshy** [comment]
什么鬼啊…昨天复制出来的指令少了个adb -d shell…两次都是点击界面上的copy啊，结果复制出来的代码都不一样……
（P.S.那个adb devices是上一行的，不知道为什么粘到github就不分行了）

**Comment by liudongmiao** [comment]
当你连上了 usb，就会放出 `adb -d shell`；
如果没有连上，你还可能使用 wifi 调试呢，就不带 `adb -d shell`。

如果你在电脑上，肯定得加上 `adb -d shell ` 啊。

**Comment by asdfeeshy** [comment]
这样哦…这么说昨天是先开的黑域后插的USB，今天先插了USB才开的黑域😂
