### ISSUE TITLE
黑阈

### ISSUE THREAD

**Issue by allaow** [brevent/Brevent#836]
![Screenshot_20231113_123918](https://github.com/brevent/Brevent/assets/150092108/7a617ca7-0eb2-4e55-855e-b71d2d2b4e11)
这个问题怎么解决

**Comment by vvb2060** [comment]
请重启黑阈服务，或者联系ROM提供商。

**Comment by allaow** [comment]
没看懂，我是手机的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 晚上10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [brevent/Brevent] 黑阈 (Issue #836)




 
Closed #836 as not planned.

**Comment by allaow** [comment]
重启也也这样，搞不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 晚上10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [brevent/Brevent] 黑阈 (Issue #836)




 
请重启黑阈服务，或者联系ROM提供商。

**Comment by vvb2060** [comment]
联系ROM提供商，我们无能为力

**Comment by allaow** [comment]
怎么联系他🤧，我找不到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [brevent/Brevent] 黑阈 (Issue #836)




 
联系ROM提供商，我们无能为力

**Comment by allaow** [comment]
怎么样联系ROM提供商



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [brevent/Brevent] 黑阈 (Issue #836)




 
联系ROM提供商，我们无能为力
