### ISSUE TITLE
root无法启动黑阈服务，有图和bug显示

### ISSUE THREAD

**Issue by u56987236** [brevent/Brevent#837]
OnePlus/OnePlus9Pro_EEA/OnePlus9Pro:13/TP1A.220905.001/R.12ee130-1f9aa-ffaae:user/release-keys

library: /data/app/~~S5iVA6HWlZnnsNPNEeYD0g==/me.piebridge.brevent-qshpciEWQMgIJeEKEKdipw==/lib/arm64/libbrevent.so
WARNING: run as root is experimental!!!
checking for server..fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '11-15 15:13:04.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '11-15 15:13:04.000' -d -s BreventLoader BreventServer
--------- beginning of main
11-15 15:13:04.254 23281 23281 I BreventLoader: sdk: 33
11-15 15:13:04.296 23288 23288 I BreventLoader: pm path me.piebridge.brevent
11-15 15:13:04.375 23288 23288 I BreventLoader: line: 
11-15 15:13:04.376 23288 23288 E BreventLoader: can't get path
11-15 15:13:04.377 23281 23281 E BreventLoader: worker 23288 exited with status 255
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

![Screenshot_2023-11-15-15-21-23-97_e88630c4e740b41437a1b6dc6436479a](https://github.com/brevent/Brevent/assets/69118567/6b54f869-0c3f-4e1d-8304-9541ef6fbd45)

**Comment by liudongmiao** [comment]
在任何设备上，pm path 应该返回数据，而你的系统没有。

根据系统提示，你系统有 Root，黑阈不对此提供任何技术支持。
