### ISSUE TITLE
Brevent

### ISSUE THREAD

**Issue by acem11552** [brevent/Brevent#841]
It doesn't let me use the command option and it always sends me to this page

**Comment by Davidjunior0** [comment]
Muito legal

**Comment by Davidjunior0** [comment]
Muito bom

**Comment by Davidjunior0** [comment]
Hshs

**Comment by Davidjunior0** [comment]
Zhzh

**Comment by Davidjunior0** [comment]
sh /sdcard/Android/data/com.panda.scriptpatcher/files/activate.sh

**Comment by Davidjunior0** [comment]
settings put global block_untrusted_touches 0

**Comment by liudongmiao** [comment]
we don't offer support for command exec.
