### ISSUE TITLE
黑域中某些不理解内容

### ISSUE THREAD

**Issue by antinomypa** [brevent/Brevent#85]
黑域中出现应用显示为“一个进程”的情况，既不是“一个服务进程”也不是“一个缓存（安全）进程”，请问一个进程表示应用处于一个什么样的状态呢？

**Comment by liudongmiao** [comment]
Android 里有多种状态，非常多。
我只把缓存，服务单独拿出来说，其它的就没说了。
去找找阻止运行中文档，我之前翻译过一段。
