### ISSUE TITLE
原来用的一版我安装了应用会自动黑域

### ISSUE THREAD

**Issue by jiushizhe** [brevent/Brevent#85]
屏幕下方会弹出来已黑域什么什么应用现在这个版本不行了   怎么回事  还有总感觉黑域没在运行

**Comment by liudongmiao** [comment]
这个功能，要求你不黑域黑域自身，或者黑域处于非强行停止状态（如系统支持设置停止状态，且黑域允许同步）。

**Comment by liudongmiao** [comment]
另外，有一点，自动黑域会工作，但并不一定有通知。

**Comment by jiushizhe** [comment]
好的     感谢坐着耐心回答
