### ISSUE TITLE
抱歉还有个问题可能你在Google强调看到了可能也回复我了

### ISSUE THREAD

**Issue by jiushizhe** [brevent/Brevent#86]
因为我不会在Google商店看自己评价也就看不到你的回复了   所以在这里提问了 手头没有电脑手机已经root  想知道和电脑启动有什么区别么

**Comment by jiushizhe** [comment]
还有关于Google服务的几个应用该怎么解决   黑域么？   会自动运行

**Comment by liudongmiao** [comment]
1. 黑域只有启动方式差别，一旦启动，没有任何区别，但是 root 模式可能不能正常工作（这大约是唯一一个 root 可能无法正常工作的应用...）。

2. 不黑域。黑域它们只会更费电，他们能强力被唤醒，或者被依赖唤醒。

**Comment by jiushizhe** [comment]
感谢   继续支持
