### ISSUE TITLE
ClassNotFoundException: Didn't find class "me.piebridge.brevent.server.BreventServer"

### ISSUE THREAD

**Issue by jw1415** [brevent/Brevent#87]
checking............cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-10 13:52:05.000' -d
07-10 13:52:06.560 23748 23748 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 23748 (main)
07-10 13:52:06.611   704   704 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-10 13:52:06.611   704   704 F DEBUG   : Build fingerprint: 'Xiaomi/markw/markw:6.0.1/MMB29M/V8.2.1.0.MBECNDL:user/release-keys'
07-10 13:52:06.612   704   704 F DEBUG   : Revision: '0'
07-10 13:52:06.612   704   704 F DEBUG   : ABI: 'arm64'
07-10 13:52:06.612   704   704 F DEBUG   : pid: 23748, tid: 23748, name: main  >>> brevent_server <<<
07-10 13:52:06.612   704   704 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-10 13:52:06.619   704   704 F DEBUG   : Abort message: 'art/runtime/thread.cc:1337] No pending exception expected: java.lang.ClassNotFoundException: Didn't find class "me.piebridge.brevent.server.BreventServer" on path: DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]'
07-10 13:52:06.619   704   704 F DEBUG   :     x0   0000000000000000  x1   0000000000005cc4  x2   0000000000000006  x3   0000000000000000
07-10 13:52:06.619   704   704 F DEBUG   :     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
07-10 13:52:06.619   704   704 F DEBUG   :     x8   0000000000000083  x9   0000007fb150aa70  x10  0000000000000003  x11  0000000000000100
07-10 13:52:06.619   704   704 F DEBUG   :     x12  000000000000000e  x13  0000000000004000  x14  0000000000000000  x15  0000000000000000
07-10 13:52:06.619   704   704 F DEBUG   :     x16  0000007fb15036a8  x17  0000007fb14c5bdc  x18  c000000000000000  x19  0000007fb1927088
07-10 13:52:06.619   704   704 F DEBUG   :     x20  0000007fb1926fc8  x21  0000000000000000  x22  0000000000000006  x23  0000007fae193000
07-10 13:52:06.619   704   704 F DEBUG   :     x24  000000558a75ec70  x25  000000558a764d20  x26  000000558a75f8d0  x27  0000007fae0b5000
07-10 13:52:06.619   704   704 F DEBUG   :     x28  000000558a75eb40  x29  0000007ff1526240  x30  0000007fb14c3378
07-10 13:52:06.619   704   704 F DEBUG   :     sp   0000007ff1526240  pc   0000007fb14c5be4  pstate 0000000020000000
07-10 13:52:06.627   704   704 F DEBUG   :
07-10 13:52:06.627   704   704 F DEBUG   : backtrace:
07-10 13:52:06.627   704   704 F DEBUG   :     #00 pc 000000000006abe4  /system/lib64/libc.so (tgkill+8)
07-10 13:52:06.627   704   704 F DEBUG   :     #01 pc 0000000000068374  /system/lib64/libc.so (pthread_kill+68)
07-10 13:52:06.627   704   704 F DEBUG   :     #02 pc 00000000000212f8  /system/lib64/libc.so (raise+28)
07-10 13:52:06.627   704   704 F DEBUG   :     #03 pc 000000000001ba98  /system/lib64/libc.so (abort+60)
07-10 13:52:06.627   704   704 F DEBUG   :     #04 pc 00000000004327d8  /system/lib64/libart.so (_ZN3art7Runtime5AbortEv+324)
07-10 13:52:06.627   704   704 F DEBUG   :     #05 pc 00000000001362a4  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
07-10 13:52:06.627   704   704 F DEBUG   :     #06 pc 0000000000130d48  /system/lib64/libart.so (_ZN3art7BarrierD2Ev+296)
07-10 13:52:06.627   704   704 F DEBUG   :     #07 pc 000000000046773c  /system/lib64/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+252)
07-10 13:52:06.627   704   704 F DEBUG   :     #08 pc 00000000004328c4  /system/lib64/libart.so (_ZN3art7Runtime5AbortEv+560)
07-10 13:52:06.627   704   704 F DEBUG   :     #09 pc 00000000001362a4  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
07-10 13:52:06.627   704   704 F DEBUG   :     #10 pc 0000000000457dc8  /system/lib64/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv.part.181+504)
07-10 13:52:06.627   704   704 F DEBUG   :     #11 pc 0000000000190cb8  /system/lib64/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+48)
07-10 13:52:06.628   704   704 F DEBUG   :     #12 pc 0000000000367e4c  /system/lib64/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+1172)
07-10 13:52:06.628   704   704 F DEBUG   :     #13 pc 0000000000091f8c  /system/lib64/libandroid_runtime.so (_ZN7android30register_android_util_SeempLogEP7_JNIEnv+36)
07-10 13:52:06.628   704   704 F DEBUG   :     #14 pc 0000000000092d2c  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime8startRegEP7_JNIEnv+84)
07-10 13:52:06.628   704   704 F DEBUG   :     #15 pc 00000000000948c8  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+336)
07-10 13:52:06.628   704   704 F DEBUG   :     #16 pc 0000000000001e78  /system/bin/app_process64
07-10 13:52:06.628   704   704 F DEBUG   :     #17 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
07-10 13:52:06.628   704   704 F DEBUG   :     #18 pc 0000000000002250  /system/bin/app_process64
07-10 13:52:06.709   704   704 F DEBUG   :
07-10 13:52:06.709   704   704 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_00
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-10 13:52:05.000' -d -s BreventLoader BreventServer
07-10 13:52:06.079 23726 23726 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
07-10 13:52:06.720 23726 23726 E BreventLoader: worker 23748 exited on signal 6
07-10 13:52:06.720 23726 23726 D BreventLoader: signal arrived, update: 0
07-10 13:52:06.721 23722 23722 D BreventLoader: worker 23726 exited with status 0
--- brevent end ---

**Comment by liudongmiao** [comment]
it seems you build Brevent from scratch.

Please read https://github.com/brevent/Brevent/blob/master/DEVELOP.md
