### ISSUE TITLE
Someone help me, I ended up disabling the android system shell >> com.android.shell

### ISSUE THREAD

**Issue by exoticzqy** [brevent/Brevent#872]
![Screenshot_2024-03-07-02-55-19-249_me piebridge brevent](https://github.com/brevent/Brevent/assets/162542994/d37b36fc-1c2d-4474-a5c9-df532de12ba3)
![Screenshot_2024-03-07-02-55-14-191_me piebridge brevent](https://github.com/brevent/Brevent/assets/162542994/1da1a292-492d-4929-ad0a-3422096d0b26)

**Comment by fillwithjoy1** [comment]
Good luck fixing that. You probably fucked over the system, and now adb commands will be broken. Just flash your OS entirely, you can't do anything now

**Comment by liudongmiao** [comment]
You shoudn't disable `com.android.shell`.
