### ISSUE TITLE
1.3.4导致SSR掉后台

### ISSUE THREAD

**Issue by SimonsQiu** [brevent/Brevent#88]
看了更新的commit感觉应该是无关的。。。。但是还是发生了。。。。
在1.3.3及之前版本链接SSR之后划掉，SSR还是能保持连接状态的
1.3.4之后过一段时间VPN就自己掉了。。。。
（已开启VPN优化。。。没黑域SSR，不划掉后台）
ADB模式
Android 7.0.1
我感觉Log应该没啥内容。。。先不上传了，要的话我再重装1.3.4

祝好

**Comment by vvb2060** [comment]
至少我这里SSR没有出现问题，需要你的日志。

**Comment by liudongmiao** [comment]
你肯定要日志，没日志我咋知道。

日志默认会记录得比较少，但对付你这个足够了。你看看 gms 之类的。

根据你的描述，大约是强行停止了 SSR 依赖的某个东西，然后它就挂了。
但抱歉，我无法提供是哪个依赖，大约是 gms 或之类。

任何时候，黑域不会处理非清单内容。

**Comment by SimonsQiu** [comment]
重装黑域后解决。。。。。issue closed

**Comment by SimonsQiu** [comment]
问题又出现了。。。。我把log post上来
~



C:\ADB>adb -d logcat -d -b main -s BreventServer BreventLoader
07-13 16:59:52.603   619   619 D BreventServer: update current to com.tencent.mm
07-13 16:59:55.025   619   619 D BreventServer: com.sec.android.app.shealth: widgets or system
07-13 16:59:55.294   619   619 D BreventServer: check and brevent
07-13 16:59:55.540   619   619 D BreventServer: ignore com.sec.android.app.shealth, wait for the service check
07-13 16:59:55.547   619   619 D BreventServer: Force stop com.netease.cloudmusic(previous running)
07-13 16:59:55.548   619   619 D BreventServer: check again in 780s
07-13 16:59:55.548   619   619 D BreventServer: check and brevent, took 251ms
07-13 17:00:15.916   619   619 D BreventServer: update current to com.sec.android.app.launcher
07-13 17:00:17.775   619   619 D BreventServer: update current to com.taobao.taobao
07-13 17:00:22.981   619   619 D BreventServer: check and brevent
07-13 17:00:23.232   619   619 D BreventServer: Force stop com.sec.android.app.shealth(service)
07-13 17:00:23.255   619   619 D BreventServer: Force stop com.eg.android.AlipayGphone(service)
07-13 17:00:23.257   619   619 D BreventServer: check again in 752s
07-13 17:00:23.257   619   619 D BreventServer: check and brevent, took 268ms
07-13 17:00:45.422   619   619 D BreventServer: update current to com.android.systemui
07-13 17:00:46.100   619   619 D BreventServer: update current to com.tencent.mm
07-13 17:01:07.939   619   619 D BreventServer: update current to com.android.systemui
07-13 17:01:08.625   619   619 D BreventServer: update current to com.taobao.taobao
07-13 17:01:43.276   619   619 D BreventServer: update current to com.sec.android.app.launcher
07-13 17:01:44.586   619   619 D BreventServer: update current to com.android.systemui
07-13 17:01:46.278   619   619 D BreventServer: check and brevent
07-13 17:01:46.535   619   619 D BreventServer: Force stop com.taobao.taobao(noRecent)
07-13 17:01:46.551   619   619 D BreventServer: check again in 669s
07-13 17:01:46.552   619   619 D BreventServer: check and brevent, took 273ms
07-13 17:01:46.927   619   619 D BreventServer: update current to tv.pps.mobile
07-13 17:02:15.474   619   619 D BreventServer: update current to com.android.systemui
07-13 17:02:17.364   619   619 D BreventServer: update current to com.mdroid.read
07-13 17:02:46.953   619   619 D BreventServer: check and brevent
07-13 17:02:47.143   619   619 D BreventServer: Force stop tv.pps.mobile(noRecent)
07-13 17:02:47.147   619   619 D BreventServer: check again in 1771s
07-13 17:02:47.147   619   619 D BreventServer: check and brevent, took 194ms
07-13 17:11:43.359   619   619 D BreventServer: com.netease.cloudmusic: priority
07-13 17:12:16.389   619   619 D BreventServer: check and brevent
07-13 17:12:16.858   619   619 D BreventServer: Force stop com.netease.cloudmusic(priority service)
07-13 17:12:16.861   619   619 D BreventServer: check again in 1201s
07-13 17:12:16.861   619   619 D BreventServer: check and brevent, took 467ms
07-13 17:21:30.726   619   619 D BreventServer: check and brevent
07-13 17:21:31.056   619   619 D BreventServer: Force stop com.netease.cloudmusic(previous running)
07-13 17:21:31.057   619   619 D BreventServer: check again in 1672s
07-13 17:21:31.058   619   619 D BreventServer: check and brevent, took 328ms
07-13 17:23:12.554   619   619 D BreventServer: com.netease.cloudmusic: priority
07-13 17:23:45.590   619   619 D BreventServer: check and brevent
07-13 17:23:45.993   619   619 D BreventServer: Force stop com.netease.cloudmusic(priority service)
07-13 17:23:45.996   619   619 D BreventServer: check again in 1538s
07-13 17:23:45.996   619   619 D BreventServer: check and brevent, took 401ms
07-13 17:28:08.920   619   619 D BreventServer: com.google.android.gms: widgets or system
07-13 17:28:09.545   619   619 D BreventServer: com.google.android.gms: widgets or system
07-13 17:28:42.552   619   619 D BreventServer: check and brevent
07-13 17:28:42.953   619   619 D BreventServer: Force stop com.google.android.gms(service)
07-13 17:28:42.984   619   619 D BreventServer: Force stop com.samsung.android.messaging(previous running)
07-13 17:28:42.993   619   619 D BreventServer: Force stop com.netease.cloudmusic(previous running)
07-13 17:28:42.995   619   619 D BreventServer: check again in 1241s
07-13 17:28:42.995   619   619 D BreventServer: check and brevent, took 439ms
07-13 17:32:04.463   619   619 D BreventServer: check and brevent
07-13 17:32:04.834   619   619 D BreventServer: check again in 1798s
07-13 17:32:04.835   619   619 D BreventServer: check and brevent, took 369ms
07-13 17:33:53.391   619   619 D BreventServer: update current to com.sec.android.app.launcher
07-13 17:33:55.410   619   619 D BreventServer: update current to com.taobao.taobao
07-13 17:34:00.031   619   619 D BreventServer: check and brevent
07-13 17:34:00.798   619   619 D BreventServer: Force stop com.eg.android.AlipayGphone(service)
07-13 17:34:00.802   619   619 D BreventServer: check again in 1793s
07-13 17:34:00.802   619   619 D BreventServer: check and brevent, took 622ms
07-13 17:34:31.180   619   619 D BreventServer: update current to com.android.systemui
07-13 17:34:34.815   619   619 D BreventServer: update current to com.sec.android.app.launcher
07-13 17:34:37.819   619   619 D BreventServer: check and brevent
07-13 17:34:38.190   619   619 D BreventServer: Force stop com.taobao.taobao(noRecent)
07-13 17:34:38.197   619   619 D BreventServer: check again in 1756s
07-13 17:34:38.198   619   619 D BreventServer: check and brevent, took 374ms
07-13 17:36:18.381   619   619 D BreventServer: update current to com.mdroid.read
07-13 17:36:19.692   619   619 D BreventServer: check and brevent
07-13 17:36:19.856   619   619 D BreventServer: check again in 1799s
07-13 17:36:19.856   619   619 D BreventServer: check and brevent, took 163ms
07-13 17:37:19.818   619   619 D BreventServer: update current to com.sec.android.app.launcher
07-13 17:37:22.647   619   619 D BreventServer: update current to com.quark.browser
07-13 17:37:22.817   619   619 D BreventServer: check and brevent
07-13 17:37:22.972   619   619 D BreventServer: check again in 1797s
07-13 17:37:22.972   619   619 D BreventServer: check and brevent, took 152ms
07-13 17:37:23.014   619   619 D BreventServer: com.google.android.gms: widgets or system
07-13 17:37:37.924   619   619 D BreventServer: update current to com.sec.android.app.launcher
07-13 17:37:42.371   619   619 D BreventServer: com.netease.cloudmusic: priority
07-13 17:37:42.914   619   619 D BreventServer: update current to com.android.systemui
07-13 17:37:43.672   619   619 D BreventServer: update current to com.quark.browser
07-13 17:37:45.649   619   619 D BreventServer: check and brevent
07-13 17:37:46.047   619   619 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr}
07-13 17:37:46.054   619   619 D BreventServer: ignore com.netease.cloudmusic, wait for the service check
07-13 17:37:46.057   619   619 D BreventServer: check again in 1773s
07-13 17:37:46.057   619   619 D BreventServer: check and brevent, took 407ms
07-13 17:37:56.022   619   619 D BreventServer: check and brevent
07-13 17:37:56.324   619   619 D BreventServer: Force stop com.google.android.gms(service)
07-13 17:37:56.332   619   619 D BreventServer: ignore com.netease.cloudmusic, wait for the service check
07-13 17:37:56.339   619   619 D BreventServer: check again in 1764s
07-13 17:37:56.339   619   619 D BreventServer: check and brevent, took 314ms
07-13 17:37:56.988   619   619 D BreventServer: com.sec.android.app.samsungapps: widgets or system
07-13 17:37:57.785   619   619 D BreventServer: com.google.android.gms: widgets or system
07-13 17:37:58.434   619   619 D BreventServer: com.google.android.gms: widgets or system
07-13 17:38:02.138   619   619 D BreventServer: check and brevent
07-13 17:38:02.302   619   619 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, com.zhihu.android}
07-13 17:38:02.310   619   619 D BreventServer: Force stop com.lovelycat(service)
07-13 17:38:02.317   619   619 D BreventServer: Force stop com.dianping.v1(service)
07-13 17:38:02.344   619   619 D BreventServer: Force stop com.sec.android.app.samsungapps(service)
07-13 17:38:02.362   619   619 D BreventServer: Force stop com.zhihu.android(service)
07-13 17:38:02.378   619   619 D BreventServer: Force stop com.jxedt(service)
07-13 17:38:02.395   619   619 D BreventServer: Force stop com.yueguanplaybox(service)
07-13 17:38:02.425   619   619 D BreventServer: Force stop com.dotamax.app(service)
07-13 17:38:02.427   619   619 D BreventServer: ignore com.netease.cloudmusic, wait for the service check
07-13 17:38:02.439   619   619 D BreventServer: Force stop tv.danmaku.bili(service)
07-13 17:38:02.441   619   619 D BreventServer: check again in 1758s
07-13 17:38:02.441   619   619 D BreventServer: check and brevent, took 302ms
07-13 17:38:11.901   619   619 D BreventServer: check and brevent
07-13 17:38:12.300   619   619 D BreventServer: ignore com.netease.cloudmusic, wait for the service check
07-13 17:38:12.301   619   619 D BreventServer: check again in 1748s
07-13 17:38:12.302   619   619 D BreventServer: check and brevent, took 397ms
07-13 17:38:15.378   619   619 D BreventServer: check and brevent
07-13 17:38:15.780   619   619 D BreventServer: Force stop com.netease.cloudmusic(priority service)
07-13 17:38:15.783   619   619 D BreventServer: check again in 1745s
07-13 17:38:15.783   619   619 D BreventServer: check and brevent, took 403ms
07-13 17:39:10.873   619   619 D BreventServer: check and brevent
07-13 17:39:11.266   619   619 D BreventServer: Force stop com.netease.cloudmusic(previous running)
07-13 17:39:11.269   619   619 D BreventServer: check again in 1689s
07-13 17:39:11.269   619   619 D BreventServer: check and brevent, took 394ms
07-13 17:40:14.757   619   619 D BreventServer: check and brevent
07-13 17:40:15.133   619   619 D BreventServer: check again in 1625s
07-13 17:40:15.133   619   619 D BreventServer: check and brevent, took 374ms
07-13 17:41:14.188   619   619 D BreventServer: check and brevent
07-13 17:41:14.539   619   619 D BreventServer: check again in 1566s
07-13 17:41:14.539   619   619 D BreventServer: check and brevent, took 346ms
07-13 17:41:44.779   619   619 D BreventServer: handle message: check(6)
07-13 17:41:44.780   619   619 D BreventServer: check and brevent
07-13 17:41:45.055   619   619 D BreventServer: widgets: {com.google.android.googlequicksearchbox, com.sec.android.daemonapp}
07-13 17:41:45.055   619   619 D BreventServer: running: {com.quark.browser=81367, com.mdroid.read=81135}
07-13 17:41:45.055   619   619 D BreventServer: recent: {com.quark.browser=3566, com.mdroid.read=3334}
07-13 17:41:45.087   619   619 D BreventServer: inactive for com.quark.browser: 33, timeout: 1800
07-13 17:41:45.087   619   619 D BreventServer: inactive for com.lovelycat: 0, timeout: 1800
07-13 17:41:45.087   619   619 D BreventServer: inactive for com.mdroid.read: 265, timeout: 1800
07-13 17:41:45.087   619   619 D BreventServer: inactive for com.google.android.gms: 0, timeout: 1800
07-13 17:41:45.087   619   619 D BreventServer: inactive for com.sec.android.app.sbrowser: 0, timeout: 1800
07-13 17:41:45.088   619   619 D BreventServer: avoid force-stop non-service com.sec.android.app.sbrowser in non-aggressive mode
07-13 17:41:45.088   619   619 D BreventServer: inactive for com.zhihu.android: 0, timeout: 1800
07-13 17:41:45.088   619   619 D BreventServer: avoid force-stop non-service com.zhihu.android in non-aggressive mode
07-13 17:41:45.088   619   619 D BreventServer: inactive for com.sec.android.sidesync30: 0, timeout: 1800
07-13 17:41:45.088   619   619 D BreventServer: avoid force-stop non-service com.sec.android.sidesync30 in non-aggressive mode
07-13 17:41:45.088   619   619 D BreventServer: inactive for com.yueguanplaybox: 0, timeout: 1800
07-13 17:41:45.088   619   619 D BreventServer: inactive for com.taobao.taobao: 0, timeout: 1800
07-13 17:41:45.088   619   619 D BreventServer: inactive for com.dotamax.app: 0, timeout: 1800
07-13 17:41:45.088   619   619 D BreventServer: inactive for com.samsung.android.contacts: 0, timeout: 1800
07-13 17:41:45.088   619   619 D BreventServer: avoid force-stop non-service com.samsung.android.contacts in non-aggressive mode
07-13 17:41:45.088   619   619 D BreventServer: inactive for com.eg.android.AlipayGphone: 0, timeout: 1800
07-13 17:41:45.222   619   619 D BreventServer: com.google.android.googlequicksearchbox depended by {com.sec.android.app.launcher}
07-13 17:41:45.222   619   619 D BreventServer: android depended by {com.android.providers.media, com.android.providers.downloads, com.sec.android.app.launcher, com.samsung.android.contacts}
07-13 17:41:45.222   619   619 D BreventServer: com.android.nfc depended by {com.android.systemui}
07-13 17:41:45.222   619   619 D BreventServer: com.android.providers.settings depended by {com.quark.browser, com.samsung.android.app.cocktailbarservice, com.lovelycat, com.google.android.googlequicksearchbox, com.osp.app.signin, com.android.providers.media, com.xinshuru.inputmethod, com.android.providers.downloads, com.sec.android.daemonapp, com.tencent.mm, com.mdroid.read, com.samsung.android.providers.context, com.samsung.android.service.peoplestripe, com.sec.android.app.launcher, com.sec.android.app.sbrowser, com.zhihu.android, com.suyashsrijan.forcedoze, com.yueguanplaybox, com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.systemui, com.taobao.taobao, com.dotamax.app, com.samsung.android.contacts, com.android.providers.contacts, com.eg.android.AlipayGphone}
07-13 17:41:45.222   619   619 D BreventServer: com.google.android.webview depended by {com.google.android.googlequicksearchbox, com.zhihu.android, com.taobao.taobao, com.eg.android.AlipayGphone}
07-13 17:41:45.222   619   619 D BreventServer: com.google.android.gms depended by {in.zhaoj.shadowsocksr, com.zhihu.android, com.dotamax.app}
07-13 17:41:45.222   619   619 D BreventServer: com.android.settings depended by {com.android.systemui}
07-13 17:41:45.222   619   619 D BreventServer: com.samsung.android.app.appsedge depended by {com.samsung.android.app.cocktailbarservice}
07-13 17:41:45.222   619   619 D BreventServer: com.android.bluetooth depended by {com.android.systemui}
07-13 17:41:45.223   619   619 I BreventServer: won't block com.google.android.gms, depended by {in.zhaoj.shadowsocksr, com.zhihu.android}
07-13 17:41:45.223   619   619 D BreventServer: service: {com.lovelycat, com.zhihu.android, com.yueguanplaybox, com.taobao.taobao, com.dotamax.app, com.eg.android.AlipayGphone}
07-13 17:41:45.223   619   619 D BreventServer: blocking: {com.lovelycat, com.google.android.gms, com.zhihu.android, com.yueguanplaybox, com.taobao.taobao, com.dotamax.app, com.eg.android.AlipayGphone}
07-13 17:41:45.226   619   619 D BreventServer: top: {com.quark.browser}
07-13 17:41:45.226   619   619 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
07-13 17:41:45.226   619   619 D BreventServer: current: com.quark.browser
07-13 17:41:45.226   619   619 D BreventServer: unsafe: {com.quark.browser, com.google.android.gms, com.sec.android.app.launcher, com.android.systemui}
07-13 17:41:45.226   619   619 D BreventServer: final blocking: {com.lovelycat, com.zhihu.android, com.yueguanplaybox, com.taobao.taobao, com.dotamax.app, com.eg.android.AlipayGphone}
07-13 17:41:45.227   619   619 D BreventServer: standby only: {com.sec.android.app.sbrowser, com.zhihu.android, com.sec.android.sidesync30, com.samsung.android.contacts}
07-13 17:41:45.227   619   619 D BreventServer: noRecent: {com.lovelycat, com.google.android.gms, com.sec.android.app.sbrowser, com.zhihu.android, com.sec.android.sidesync30, com.yueguanplaybox, com.taobao.taobao, com.dotamax.app, com.samsung.android.contacts, com.eg.android.AlipayGphone}
07-13 17:41:45.228   619   619 D BreventServer: full power list: {com.osp.app.signin, com.android.providers.downloads, com.samsung.android.email.provider, com.sec.android.daemonapp, com.sec.ims, in.zhaoj.shadowsocksr, com.tencent.mm, com.samsung.klmsagent, com.sec.imsservice, com.samsung.android.weather, com.google.android.gms, com.sec.spp.push, com.suyashsrijan.forcedoze, com.sec.enterprise.knox.cloudmdm.smdms}
07-13 17:41:45.249   619   619 D BreventServer: Force stop com.lovelycat(service)
07-13 17:41:45.293   619   619 D BreventServer: Force stop com.zhihu.android(service)
07-13 17:41:45.329   619   619 D BreventServer: Force stop com.yueguanplaybox(service)
07-13 17:41:45.365   619   619 D BreventServer: Force stop com.taobao.taobao(service)
07-13 17:41:45.438   619   619 D BreventServer: Force stop com.dotamax.app(service)
07-13 17:41:45.480   619   619 D BreventServer: Force stop com.eg.android.AlipayGphone(service)
07-13 17:41:45.486   619   619 D BreventServer: check again in 1535s
07-13 17:41:45.486   619   619 D BreventServer: check and brevent, took 680ms
07-13 17:41:45.486   619   619 D BreventServer: handle event notification_cancel_all(4)
07-13 17:41:45.486   619   619 D BreventServer: handle event notification_cancel_all(4)
07-13 17:41:45.519   619   619 D BreventServer: handle event notification_cancel_all(4)
07-13 17:41:45.520   619   619 D BreventServer: handle event notification_cancel_all(4)
07-13 17:41:45.521   619   619 D BreventServer: handle event notification_cancel_all(4)
07-13 17:41:45.536   619   619 D BreventServer: handle event notification_cancel_all(4)

**Comment by liudongmiao** [comment]
你看，黑域没有直接强行停止 shadowsocksr

然后，如果它依赖了某个东西，而被，我也无能为力。
所以，你得自己找系统日志。

**Comment by SimonsQiu** [comment]
不黑域GMS后问题解决。 issue closed
