### ISSUE TITLE
values strings, line #8

### ISSUE THREAD

**Issue by samforo** [brevent/Brevent#88]
In the string #8 .
File:
brevent/src/main/res/values/strings.xml

> <string name="fragment_guide_welcome_message">
> 
> Brevent recognizes whether you have opened or closed app by this way, preventing apps which are in the Brevent list from running in long time.

It is not correct "in long time", it should be, "At the designated time" in the settings of Brevent.

Regards.

**Comment by liudongmiao** [comment]
@liyufan

**Comment by liyufan** [comment]
@liudongmiao I hesitated while translating this sentence, untill I saw this in [README.md](https://github.com/brevent/Brevent/blob/master/README.md)
>Brevent, black prevent, can app-standby (Since Android 6.0) or force-stop apps without ROOT, prevent apps from running in long time.

So I just used it in translation...

**Comment by liyufan** [comment]
@samforo You probably misunderstood the meaning of the sentence. It means 
>prevent apps from running for extended periods

rather than 
>prevent apps from running at a time which was previously specified

**Comment by samforo** [comment]
The time to which it refers, is not the time that is adjusted in the configuration options?

If it isn't the time to configure in settings, perfect .

**Comment by liudongmiao** [comment]
Just keep it.

**Comment by liyufan** [comment]
@samforo No, it isn't.
The "time" in the sentence has nothing to do with the "time" in settings. It just means a long period.
Regards.
