### ISSUE TITLE
1.3.4无法黑域网易云音乐

### ISSUE THREAD

**Issue by heganyuliang** [brevent/Brevent#89]
打开网易云音乐再按 back 退出后，在黑域界面里看到的是服务依然存活，右侧闹钟上面的时间一直在走，重新打开应用也是秒开到退出时的界面，应该是完全没受到黑域的控制。只有从最近任务界面划掉之后才能在黑域和开发者选项正在运行的服务里消失。日志如下：

> 07-11 23:18:22.651  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:18:24.108  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:18:29.071  7714  7714 D BreventServer: update current to net.oneplus.launcher
07-11 23:18:32.087  7714  7714 D BreventServer: update current to com.tencent.mm
07-11 23:18:35.032  7714  7714 D BreventServer: check and brevent
07-11 23:18:35.509  7714  7714 D BreventServer: check again in 3600s
07-11 23:18:35.509  7714  7714 D BreventServer: check and brevent, took 475ms
07-11 23:18:43.313  7714  7714 D BreventServer: update current to net.oneplus.launcher
07-11 23:18:45.931  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:18:46.312  7714  7714 D BreventServer: check and brevent
07-11 23:18:46.746  7714  7714 D BreventServer: check again in 3600s
07-11 23:18:46.746  7714  7714 D BreventServer: check and brevent, took 433ms
07-11 23:18:57.390  7714  7714 D BreventServer: update current to net.oneplus.launcher
07-11 23:18:59.889  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:19:00.390  7714  7714 D BreventServer: check and brevent
07-11 23:19:00.801  7714  7714 D BreventServer: check again in 3600s
07-11 23:19:00.801  7714  7714 D BreventServer: check and brevent, took 407ms
07-11 23:19:01.017  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:19:09.888  7714  7714 D BreventServer: update current to net.oneplus.launcher
07-11 23:19:11.035  7714  7714 I BreventServer: reset home tid to 3255
07-11 23:19:12.890  7714  7714 D BreventServer: check and brevent
07-11 23:19:13.382  7714  7714 D BreventServer: check again in 3600s
07-11 23:19:13.382  7714  7714 D BreventServer: check and brevent, took 491ms
07-11 23:19:15.372  7714  7714 D BreventServer: update current to com.android.settings
07-11 23:19:26.049  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:19:27.950  7714  7714 D BreventServer: update current to com.tencent.mm
07-11 23:19:28.680  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:19:36.484  7714  7714 D BreventServer: update current to com.netease.cloudmusic
07-11 23:19:41.159  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:19:41.640  7714  7714 D BreventServer: update current to com.tencent.mm
07-11 23:19:42.705  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:19:43.612  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:19:46.842  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:19:48.453  7714  7714 D BreventServer: update current to com.netease.cloudmusic
07-11 23:19:49.364  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:19:52.024  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:19:55.466  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:19:56.631  7714  7714 D BreventServer: update current to com.android.settings
07-11 23:20:06.465  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:20:08.370  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:20:11.347  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:20:15.377  7714  7714 D BreventServer: check and brevent
07-11 23:20:15.821  7714  7714 D BreventServer: check again in 1774s
07-11 23:20:15.821  7714  7714 D BreventServer: check and brevent, took 442ms
07-11 23:20:17.128  7714  7714 D BreventServer: update current to com.netease.cloudmusic
07-11 23:20:20.155  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:20:21.392  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:20:23.401  7714  7714 D BreventServer: check and brevent
07-11 23:20:23.905  7714  7714 D BreventServer: Force stop com.google.android.keep(service)
07-11 23:20:23.929  7714  7714 D BreventServer: check again in 3600s
07-11 23:20:23.929  7714  7714 D BreventServer: check and brevent, took 526ms
07-11 23:20:43.504  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:20:44.652  7714  7714 D BreventServer: update current to com.android.settings
07-11 23:20:46.503  7714  7714 D BreventServer: check and brevent
07-11 23:20:46.890  7714  7714 D BreventServer: check again in 3600s
07-11 23:20:46.890  7714  7714 D BreventServer: check and brevent, took 385ms
07-11 23:20:51.094  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:20:52.472  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:20:54.096  7714  7714 D BreventServer: check and brevent
07-11 23:20:54.573  7714  7714 D BreventServer: check again in 3600s
07-11 23:20:54.573  7714  7714 D BreventServer: check and brevent, took 475ms
07-11 23:20:54.573  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:20:57.574  7714  7714 D BreventServer: check and brevent
07-11 23:20:58.109  7714  7714 D BreventServer: check again in 3600s
07-11 23:20:58.109  7714  7714 D BreventServer: check and brevent, took 533ms
07-11 23:21:57.510  7714  7714 D BreventServer: update current to com.netease.cloudmusic
07-11 23:22:03.156  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:22:06.158  7714  7714 D BreventServer: check and brevent
07-11 23:22:06.608  7714  7714 D BreventServer: check again in 1797s
07-11 23:22:06.608  7714  7714 D BreventServer: check and brevent, took 447ms
07-11 23:22:41.660  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:22:50.140  7714  7731 D BreventServer: check and brevent
07-11 23:22:50.574  7714  7731 D BreventServer: Force stop com.ruby.timetable(noRecent)
07-11 23:22:50.593  7714  7731 D BreventServer: check again in 1753s
07-11 23:22:50.593  7714  7731 D BreventServer: check and brevent, took 452ms
07-11 23:22:51.213  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:22:52.672  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:22:52.750  7714  7731 D BreventServer: check and brevent
07-11 23:22:53.182  7714  7731 D BreventServer: check again in 3600s
07-11 23:22:53.182  7714  7731 D BreventServer: check and brevent, took 431ms
07-11 23:22:55.514  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:22:57.633  7714  7714 D BreventServer: update current to com.netease.cloudmusic
07-11 23:22:58.516  7714  7714 D BreventServer: check and brevent
07-11 23:22:59.054  7714  7714 D BreventServer: check again in 1799s
07-11 23:22:59.054  7714  7714 D BreventServer: check and brevent, took 537ms
07-11 23:23:03.351  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:23:04.395  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:23:04.449  7714  7731 D BreventServer: check and brevent
07-11 23:23:04.808  7714  7731 D BreventServer: check again in 1799s
07-11 23:23:04.808  7714  7731 D BreventServer: check and brevent, took 358ms
07-11 23:23:07.817  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:23:10.818  7714  7714 D BreventServer: check and brevent
07-11 23:23:11.268  7714  7714 D BreventServer: check again in 1793s
07-11 23:23:11.268  7714  7714 D BreventServer: check and brevent, took 448ms
07-11 23:23:18.512  7714  7714 D BreventServer: update current to com.microsoft.office.powerpoint
07-11 23:23:20.501  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:23:21.816  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:23:21.916  7714  7731 D BreventServer: check and brevent
07-11 23:23:22.356  7714  7731 D BreventServer: check again in 1782s
07-11 23:23:22.356  7714  7731 D BreventServer: check and brevent, took 431ms
07-11 23:23:23.617  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:23:24.633  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:23:26.436  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:23:26.497  7714  7731 D BreventServer: check and brevent
07-11 23:23:26.893  7714  7731 D BreventServer: check again in 1777s
07-11 23:23:26.893  7714  7731 D BreventServer: check and brevent, took 394ms
07-11 23:23:26.947  7714  7714 D BreventServer: check and brevent
07-11 23:23:27.584  7714  7714 D BreventServer: check again in 1776s
07-11 23:23:27.584  7714  7714 D BreventServer: check and brevent, took 636ms
07-11 23:23:33.478  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:23:34.822  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:23:36.480  7714  7714 D BreventServer: check and brevent
07-11 23:23:36.855  7714  7714 D BreventServer: check again in 3600s
07-11 23:23:36.855  7714  7714 D BreventServer: check and brevent, took 373ms
07-11 23:23:36.855  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:23:38.619  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:23:41.621  7714  7714 D BreventServer: check and brevent
07-11 23:23:42.067  7714  7714 D BreventServer: check again in 3600s
07-11 23:23:42.067  7714  7714 D BreventServer: check and brevent, took 442ms
07-11 23:23:49.522  7714  7714 D BreventServer: update current to cn.wq.myandroidtoolspro
07-11 23:24:06.505  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:24:08.138  7714  7714 D BreventServer: update current to com.netease.cloudmusic
07-11 23:24:09.506  7714  7714 D BreventServer: check and brevent
07-11 23:24:10.039  7714  7714 D BreventServer: check again in 1800s
07-11 23:24:10.040  7714  7714 D BreventServer: check and brevent, took 528ms
07-11 23:24:21.348  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:24:24.351  7714  7714 D BreventServer: check and brevent
07-11 23:24:24.807  7714  7714 D BreventServer: check again in 1797s
07-11 23:24:24.807  7714  7714 D BreventServer: check and brevent, took 454ms
07-11 23:24:24.879  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:24:26.872  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:24:28.856  7714  7714 D BreventServer: update current to com.android.settings
07-11 23:24:29.873  7714  7714 D BreventServer: check and brevent
07-11 23:24:30.264  7714  7714 D BreventServer: check again in 1792s
07-11 23:24:30.264  7714  7714 D BreventServer: check and brevent, took 390ms
07-11 23:24:39.772  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:24:41.283  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:24:42.774  7714  7714 D BreventServer: check and brevent
07-11 23:24:43.244  7714  7714 D BreventServer: check again in 1779s
07-11 23:24:43.244  7714  7714 D BreventServer: check and brevent, took 468ms
07-11 23:24:46.511  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:24:49.511  7714  7714 D BreventServer: check and brevent
07-11 23:24:50.010  7714  7714 D BreventServer: check again in 1772s
07-11 23:24:50.010  7714  7714 D BreventServer: check and brevent, took 498ms
07-11 23:24:53.361  7714  7714 D BreventServer: update current to com.android.systemui
07-11 23:24:55.905  7714  7714 D BreventServer: update current to me.piebridge.brevent
07-11 23:24:57.461  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:25:00.464  7714  7714 D BreventServer: check and brevent
07-11 23:25:00.937  7714  7714 D BreventServer: check again in 3600s
07-11 23:25:00.938  7714  7714 D BreventServer: check and brevent, took 472ms
07-11 23:25:21.125  7714  7714 D BreventServer: update current to com.netease.cloudmusic
07-11 23:25:26.372  7714  7714 D BreventServer: update current to com.teslacoilsw.launcher
07-11 23:25:29.376  7714  7714 D BreventServer: check and brevent
07-11 23:25:29.905  7714  7714 D BreventServer: check again in 1797s
07-11 23:25:29.905  7714  7714 D BreventServer: check and brevent, took 527ms
07-11 23:25:30.369  7714  7714 D BreventServer: update current to me.piebridge.brevent

**Comment by liudongmiao** [comment]
如果有时间，表明为非正常返回，要等到后台应用超时才会（先待机后）强行停止。
如果能正确识别非正常返回，才不会等到后台应用超时，直接会（先待机后）强行停止。

**Comment by heganyuliang** [comment]
那就是识别非正常返回的问题了？这个功能在我这里好像一直有问题，最开始刚加入的时候我按 7 次 home 后出现过真正的主页那个 toast，后来刷机后很长一段时间按 home 没有反应，昨天再试的时候又出现了 toast，应该是成功了。但是今天手机出了些问题，重新刷机之后再设置黑域，开启这个选项之后连按 home 又没有提示了，不知道到底怎么回事。

**Comment by liudongmiao** [comment]
这个功能没法稳定。。

如果按没有提示，肯定是不会工作的。

**Comment by heganyuliang** [comment]
好吧……那就只能每次都从最近任务界面划掉了。
