### ISSUE TITLE
我是微信的付费用户，但现在的支付确认已经没有微信支付了。

### ISSUE THREAD

**Issue by zhaibingye** [brevent/Brevent#898]
我已经付费升级成会员版本了，但现在的支付确认只有play商店

**Comment by liudongmiao** [comment]
> 自 3.3.0 起，支持微信支付，仅限 **简体中文** 用户，需要微信 6.5.13 或更新版本。
> 同时，黑阈遵循 Play 开发者政策，Play 商店发布版本不支持微信支付。
> 特别提示：黑阈仅支持正版微信，不支持任何修改版微信。

“微信登录”即可获取相关支付信息。

**Comment by zhaibingye** [comment]
可下载的任何版本都没有微信微信登录选项

**Comment by liudongmiao** [comment]
认真阅读提示。
