### ISSUE TITLE
11.5天设置无效

### ISSUE THREAD

**Issue by chinen95** [brevent/Brevent#9]
切出去1分钟不到就被黑域了 很麻烦 之前1.1.6的时候就提过 到现在都没有修复 还是1.1好用 装回1.1后 因为新版本不知道对系统造成什么影响 root adb(命令显示成功 进入黑域依然转圈然后提示开启) 重启全部无效 服务根本没法启动  然后卸了1.1装1.1.11奇迹发生了 打开黑域没有提示开启 直接可用 所以我装回1.1开启的到底是1.1的服务还是1.1.11的服务 过程中看root开启不了 还把那个sh文件删除过一次 最后1.1.8之后的root问题要等多久才能修复啊 adb太麻烦了

**Comment by liudongmiao** [comment]
你至少得来个日志，来个截图吧。这个主要是指按 Home 切出去。
如果你按 Back，不会当计时的。

你没日志，怎么定位问题呢？

**Comment by chinen95** [comment]
我一般用方块切出 下次出现的时候弄日志 还有某个文件管理器偶尔无法黑域 划掉之后仍在计时

**Comment by liudongmiao** [comment]
计时，基本表明它是非正常 Back，这时黑域按 Home 处理逻辑。

有计时，按 Home 处理逻辑，对应后台应用超时，11.5 天也是这个。
没计时，按 Back 处理逻辑，策略按待机超时及最近列表。

**Comment by mmemi** [comment]
@liudongmiao 后台应用超时加个6小时和永久选项吧？

**Comment by liudongmiao** [comment]
6 小时没意义，等你超过了以后，再告诉我。
但这个时候，不如你把它“允许同步”。允许同步的话，只要你打开，不会处理它。

从另一点来说，6 小时也好，永久也好，都是永久。
永久，到底是多久？我认为，999999 秒就很好，大约 11.5 天。
你看，你要的 6 与 久，都有了。

**Comment by mmemi** [comment]
@liudongmiao 不加就不加吧！
另个问题，上次说过的，QQ和微信总是延迟接收信息好无耐！这三星机子设置里没有您说的电池未优化，QQ和微信中也没有这选项！黑域中又没有后台待机选项，选项中的允许同步功能只有把软件设置黑域后才能开启，但貌似没啥用，主要是开了黑域的话QQ和微信收信息就都会延时一到五分钟！在日志中总能看到这两个软件进程，柳大能不能把QQ微信加个白名单完全无视这两货？

**Comment by liudongmiao** [comment]
不加入黑域，就是白名单。

**Comment by mmemi** [comment]
看来我这问题真无解了！

**Comment by liudongmiao** [comment]
你可以对那两应用进行如下处理：
1. 允许后台数据
2. 电池未优化

**Comment by mmemi** [comment]
如上面所说的
后台数据始终是开的，自启也始终开的。
电池未优化在这手机上（6.0.1）没有这选项的。
因为不开黑域这两软件都没问题，开了收信息就都会延时几分钟！
刚看到v1.1.11+8，继续试用，感谢柳大这么强大的作品！

**Comment by chinen95** [comment]
终于又发生了 操作是这样的 从QQ按方框切换到微信 再用方框切回QQ QQ已经被强制关闭 连续发生了两次 看了下内存占用 1.1G可用(减去缓存进程 700M可用) 不存在低内存被系统杀的可能性


05-29 11:44:38.769 20337 20337 D BreventServer: check and brevent
05-29 11:44:39.036 20337 20337 D BreventServer: check again in 3600s
05-29 11:44:39.036 20337 20337 D BreventServer: check and brevent, took 264ms
05-29 11:46:48.708 20337 20337 D BreventServer: check and brevent
05-29 11:46:48.970 20337 20337 D BreventServer: check again in 3600s
05-29 11:46:48.970 20337 20337 D BreventServer: check and brevent, took 260ms
05-29 11:47:05.476 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:47:06.192 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:47:09.316 20337 20337 D BreventServer: check and brevent
05-29 11:47:09.599 20337 20337 D BreventServer: check again in 3600s
05-29 11:47:09.599 20337 20337 D BreventServer: check and brevent, took 283ms
05-29 11:48:03.339 20337 20337 D BreventServer: check and brevent
05-29 11:48:03.592 20337 20337 D BreventServer: check again in 3600s
05-29 11:48:03.592 20337 20337 D BreventServer: check and brevent, took 253ms
05-29 11:48:22.270 20337 20337 D BreventServer: check and brevent
05-29 11:48:22.516 20337 20337 D BreventServer: check again in 3600s
05-29 11:48:22.516 20337 20337 D BreventServer: check and brevent, took 245ms
05-29 11:49:06.154 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:06.422 20337 20337 D BreventServer: Force stop com.tencent.mobileqq(brevent request)
05-29 11:49:06.674 20337 20337 D BreventServer: update current to com.android.chrome
05-29 11:49:07.383 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:08.685 20337 20337 D BreventServer: update current to com.tencent.mm
05-29 11:49:11.003 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:11.529 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:49:14.420 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:49:19.080 20337 20337 D BreventServer: update current to rikka.notificationforqq
05-29 11:49:19.268 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:49:21.263 20337 20337 D BreventServer: check and brevent
05-29 11:49:21.613 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:21.613 20337 20337 D BreventServer: check and brevent, took 350ms
05-29 11:49:31.495 20337 20337 D BreventServer: check and brevent
05-29 11:49:31.737 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:31.737 20337 20337 D BreventServer: check and brevent, took 242ms
05-29 11:49:40.539 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:40.837 20337 20337 D BreventServer: Force stop com.tencent.mobileqq(brevent request)
05-29 11:49:41.042 20337 20337 D BreventServer: update current to com.tencent.mm
05-29 11:49:42.003 20337 20337 D BreventServer: check and brevent
05-29 11:49:42.289 20337 20337 D BreventServer: Force stop com.tencent.mobileqq(previous running)
05-29 11:49:42.290 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:42.290 20337 20337 D BreventServer: check and brevent, took 286ms
05-29 11:49:42.290 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:42.802 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:49:46.037 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:49:47.885 20337 20337 D BreventServer: update current to com.android.settings
05-29 11:49:56.413 20337 20337 D BreventServer: update current to com.android.systemui
05-29 11:49:56.595 20337 20337 D BreventServer: check and brevent
05-29 11:49:56.883 20337 20337 D BreventServer: check again in 3600s
05-29 11:49:56.883 20337 20337 D BreventServer: check and brevent, took 287ms
05-29 11:49:57.571 20337 20337 D BreventServer: update current to com.android.settings
05-29 11:50:01.503 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:50:02.619 20337 20337 D BreventServer: update current to rikka.notificationforqq
05-29 11:50:02.623 20337 20337 D BreventServer: update current to com.tencent.mobileqq
05-29 11:50:04.504 20337 20337 D BreventServer: check and brevent
05-29 11:50:04.746 20337 20337 D BreventServer: check again in 3600s
05-29 11:50:04.746 20337 20337 D BreventServer: check and brevent, took 240ms
05-29 11:50:30.702 20337 20337 D BreventServer: update current to com.google.android.apps.nexuslauncher
05-29 11:50:33.705 20337 20337 D BreventServer: check and brevent
05-29 11:50:33.988 20337 20337 D BreventServer: check again in 3600s
05-29 11:50:33.988 20337 20337 D BreventServer: check and brevent, took 281ms
05-29 11:50:37.046 20337 20337 D BreventServer: update current to com.termux
05-29 11:50:41.437 20337 20337 D BreventServer: Force stop eu.chainfire.supersu(brevent request)
05-29 11:50:53.693 20337 20337 D BreventServer: check and brevent
05-29 11:50:54.048 20337 20337 D BreventServer: check again in 3600s
05-29 11:50:54.048 20337 20337 D BreventServer: check and brevent, took 354ms
