### ISSUE TITLE
Exist isn't possible. 

### ISSUE THREAD

**Issue by samforo** [brevent/Brevent#90]
It is not possible to leave the screen, pressing return does nothing, only home button and delete of recent.

![img_20170909_192527](https://user-images.githubusercontent.com/30043041/30242448-00595f86-9597-11e7-99ea-9fd71f2f3ba1.jpg)

**Comment by liudongmiao** [comment]
Useless to exit.

**Comment by samforo** [comment]
Any solution coming soon?

**Comment by liudongmiao** [comment]
The exit is useless on this screen.
