### ISSUE TITLE
WARNING: run as root is experimental!!! checking...brevent_server started, pid: 4609 checking for stable..quited

### ISSUE THREAD

**Issue by fire-keeper** [brevent/Brevent#91]
--- crash start ---
>>> logcat -b crash -t '07-12 12:16:22.000' -d
07-12 12:16:23.490  4609  4609 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
07-12 12:16:23.490  4609  4609 E AndroidRuntime: java.lang.reflect.InvocationTargetException
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2070)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:265)
07-12 12:16:23.490  4609  4609 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException:  is not a constant in android.text.Layout$Alignment
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at java.lang.Enum.valueOf(Enum.java:200)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.text.Layout$Alignment.valueOf(Layout.java:2017)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpan.java:33)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.readFromParcel(ActivityManager.java:938)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:963)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:804)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:955)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:953)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at android.app.ActivityManagerProxy.getRecentTasks(ActivityManagerNative.java:3459)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at me.piebridge.brevent.override.HideApiOverrideM.getRecentTasks(HideApiOverrideM.java:22)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.m(BreventServer.java:1180)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.i(BreventServer.java:685)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1962)
07-12 12:16:23.490  4609  4609 E AndroidRuntime:        ... 4 more
07-12 12:16:23.491  4609  4609 E AndroidRuntime: Error reporting crash
07-12 12:16:23.491  4609  4609 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-12 12:16:23.491  4609  4609 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
07-12 12:16:23.491  4609  4609 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:536)
07-12 12:16:23.491  4609  4609 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4594)
07-12 12:16:23.491  4609  4609 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
07-12 12:16:23.491  4609  4609 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
07-12 12:16:23.491  4609  4609 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-12 12:16:22.000' -d -s BreventLoader BreventServer
07-12 12:16:22.402  4597  4597 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-12 12:16:22.771  4609  4609 D BreventServer: get service: package
07-12 12:16:22.805  4609  4609 I BreventServer: starting Brevent Server 1.3.4
07-12 12:16:22.819  4609  4609 D BreventServer: get service: package
07-12 12:16:22.826  4609  4609 I BreventServer: brevent user: 0, uid: 0
07-12 12:16:22.828  4609  4609 I BreventServer: brevent data directory: /data/user/0/com.android.shell
07-12 12:16:22.898  4609  4609 I BreventServer: loading brevent list
07-12 12:16:22.901  4609  4609 I BreventServer: loading brevent conf
07-12 12:16:22.913  4609  4609 D BreventServer: get service: appwidget
07-12 12:16:22.932  4609  4609 D BreventServer: get service: usagestats
07-12 12:16:23.369  4609  4609 D BreventServer: notification_cancel_all, tag: 2752, event: 4
07-12 12:16:23.372  4609  4609 D BreventServer: notification_panel_revealed, tag: 27500, event: 6
07-12 12:16:23.373  4609  4609 D BreventServer: notification_panel_hidden, tag: 27501, event: 7
07-12 12:16:23.374  4609  4609 D BreventServer: am_new_intent, tag: 30003, event: 8
07-12 12:16:23.375  4609  4609 D BreventServer: am_restart_activity, tag: 30006, event: 10
07-12 12:16:23.375  4609  4609 D BreventServer: am_resume_activity, tag: 30007, event: 2
07-12 12:16:23.376  4609  4609 D BreventServer: am_pause_activity, tag: 30013, event: 9
07-12 12:16:23.376  4609  4609 D BreventServer: am_proc_start, tag: 30014, event: 1
07-12 12:16:23.377  4609  4609 D BreventServer: am_switch_user, tag: 30041, event: 3
07-12 12:16:23.379  4609  4609 D BreventServer: screen_toggled, tag: 70000, event: 5
07-12 12:16:23.385  4609  4621 I BreventServer: Brevent Event, now: 1499832983
07-12 12:16:23.387  4609  4609 D BreventServer: check and brevent
07-12 12:16:23.390  4609  4609 D BreventServer: get service: notification
07-12 12:16:23.410  4609  4621 I BreventServer: system_server: 1352, now: 1499832983
07-12 12:16:23.462  4609  4609 D BreventServer: get service: activity
07-12 12:16:23.479  4609  4609 D BreventServer: get service: alarm
07-12 12:16:23.482  4609  4609 D BreventServer: get service: wallpaper
07-12 12:16:23.508  4597  4597 E BreventLoader: worker 4609 exited on signal 9
07-12 12:16:23.508  4597  4597 D BreventLoader: signal arrived, update: 0
07-12 12:16:23.512  4592  4592 D BreventLoader: worker 4597 exited with status 0
--- brevent end ---
cannot listen port

**Comment by liudongmiao** [comment]
>  07-12 12:16:23.490 4609 4609 E AndroidRuntime: at me.piebridge.brevent.override.HideApiOverrideM.getRecentTasks(HideApiOverrideM.java:22)

It seems that your rom doesn't allow to return `getRecentTasks`.
It's very important for Brevnet.
