### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by athallahaliffyandra** [brevent/Brevent#911]
Redmi/earth_global/earth:12/SP1A.210812.016/V13.0.5.0.SCVMIXM:user/release-keys

library: /data/app/~~1OYH_RjiiFMQv287-X4mTg==/me.piebridge.brevent-x-5GqW5AfZ8hP5EkbVHEBw==/base.apk!/lib/arm64-v8a/libbrevent.so
apk: /data/app/~~1OYH_RjiiFMQv287-X4mTg==/me.piebridge.brevent-x-5GqW5AfZ8hP5EkbVHEBw==/base.apk, name: lib/arm64-v8a/libbrevent.so
use exists /data/local/tmp/brevent
checking for server..started, pid: 15172
checking for stable...quited

[command] pm path me.piebridge.brevent
package:/data/app/~~1OYH_RjiiFMQv287-X4mTg==/me.piebridge.brevent-x-5GqW5AfZ8hP5EkbVHEBw==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '05-20 11:56:00.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '05-20 11:56:00.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by liudongmiao** [comment]
fail without detail log, we cannot do anything.
