### ISSUE TITLE
Inclusion into F-Droid repository

### ISSUE THREAD

**Issue by amo13** [brevent/Brevent#92]
Thanks for the great work on this app! It's really useful!
If you think your app fulfills the [inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy) for F-Droid, I am sure a lot of people would greatly appreciate to find your app there! Basically, you need everything to be FLOSS and to agree to the inclusion into the repository as the dev of the app. You can quickly file a packaging request [here](https://gitlab.com/fdroid/rfp/issues?scope=all&state=opened).

**Comment by liudongmiao** [comment]
The Brevent Server is not open source, so i don't think it fullfill f-droid.

**Comment by amo13** [comment]
Oh, I see... why not make it open source, too?
But still, there is a telegram client in f-droid while the server is closed source.
