### ISSUE TITLE
Falha ao iniciar o servidor Brevent

### ISSUE THREAD

**Issue by Joaomarcosjm6** [brevent/Brevent#921]
Redmi/spes_global/spes:13/TKQ1.221114.001/V816.0.5.0.TGCMIXM:user/release-keys

library: /data/app/~~bKMQUeToXAy5UvVeJaVPOA==/me.piebridge.brevent-jeSu3gPvdqWaaBb9tq8rBA==/base.apk!/lib/arm64-v8a/libbrevent.so
apk: /data/app/~~bKMQUeToXAy5UvVeJaVPOA==/me.piebridge.brevent-jeSu3gPvdqWaaBb9tq8rBA==/base.apk, name: lib/arm64-v8a/libbrevent.so
use exists /data/local/tmp/brevent
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/~~bKMQUeToXAy5UvVeJaVPOA==/me.piebridge.brevent-jeSu3gPvdqWaaBb9tq8rBA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '06-19 17:29:30.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '06-19 17:29:30.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

SE ALGUÉM SOUBER COMO RESOLVER ISSO AÍ

**Comment by Joaomarcosjm6** [comment]
Aparece essa mensagem quando eu tento conectar o servidor do Brevent, começou a ocorrer isso aí depois da segunda tentativa de conectar, a primeira foi de boa.

**Comment by liudongmiao** [comment]
fail with no log, we cannot do anything.
