### ISSUE TITLE
Brevent has no sufficient permissions in Realme

### ISSUE THREAD

**Issue by Ganvitto** [brevent/Brevent#926]
![Screenshot_2024-07-01-17-08-49-02_e88630c4e740b41437a1b6dc6436479a](https://github.com/brevent/Brevent/assets/108443112/91f80909-6a34-447f-b98b-3941b611108a)
Any solution please my device is a realme Android 14 Mtk processor

**Comment by liudongmiao** [comment]
oppo: Disable "Permission monitoring" in "Developer options".
