### ISSUE TITLE
Play版，点击显示捐赠提示“无法在Play应用内结算”然后高级功能都用不了

### ISSUE THREAD

**Issue by hhbluestar** [brevent/Brevent#93]
根据你在市场给我的回复“不要用任意程序阻制黑域唤醒Play市场”我想说的是，我没有装任何管理类软件。
然后我用其它版本，微信，支付宝均正常，就是Play市场不行。不知道是什么原因，我刷了二个不同的ROM都是同样的问题。机器是HTC10 ROM刷了国行，开发者版。固件是开发者版RUU....(不知道是不是跟这个有关系)

**Comment by liudongmiao** [comment]
那就打开 Play 放入后台，然后再看。

**Comment by hhbluestar** [comment]
依然不行。。。
