### ISSUE TITLE
黑域服务开启失败

### ISSUE THREAD

**Issue by RemDream** [brevent/Brevent#94]
checking............cannot listen port
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-13 14:26:22.000' -d
sh: logcat: not found
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-13 14:26:22.000' -d -s BreventLoader BreventServer
sh: logcat: not found
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above
黑域服务开启失败，请将日志与具体情况发至 https://github.com/brevent/Brevent/issues 来解决问题。

**Comment by liudongmiao** [comment]
需要  logcat ... 但好像你机器上连 logcat 都没有....
