### ISSUE TITLE
 brevent exit when USB disconnected on Android O/Nexus 6p

### ISSUE THREAD

**Issue by KunsLand** [brevent/Brevent#94]

**Comment by liyufan** [comment]
Please read store's details.
>In Android O, Brevent won't work if debugging is off or usb mode is changed. If you when you unplug the cable, debugging if off, you can run `adb tcpip 5555` to turn on network debug, then unplug the cable.

**Comment by liyufan** [comment]
请直接使用中文...
另外，你是酷安的`changleiy `吧？

**Comment by liyufan** [comment]
直接使用中文即可。

**Comment by liyufan** [comment]
@liudongmiao 这段的英文翻译有问题...
应该是：
>If debugging turns off when you unplug the cable

**Comment by KunsLand** [comment]
@liyufan 没关系，我理解他的意思，问题解决了，谢啦！
