### ISSUE TITLE
Brevent command is not working 

### ISSUE THREAD

**Issue by Abdulsxhil** [brevent/Brevent#942]
![Screenshot_20240728-084348](https://github.com/user-attachments/assets/463ad86e-f968-461b-8b2a-2309703d899f)

**Comment by Abdulsxhil** [comment]
Brevent command isn't working properly

**Comment by Abdulsxhil** [comment]
Anybody help me @breventofficial

**Comment by liudongmiao** [comment]
please note, we never offer support for `exec command`.

P.S. You input the wrong command, please contact command provider.
