### ISSUE TITLE
如何退款？

### ISSUE THREAD

**Issue by hanhaozi** [brevent/Brevent#948]
联系邮箱：han1231115611656549@outlook.com

**Comment by liudongmiao** [comment]
支付以后，1 个月内均可无条件退款。退款过后又支付的，不再退款。

微信支付的，关注公众号“简域工作室”（微信订单 - 联系商户 - 公众号联系），然后发送“退款”参照提示自助退款。
请仅回复引号内内容，如“退款100”之类。

Play 商店支付的，可联系 Google 自助退款。如果无法自助退款，请带上订单号发送邮件至 brevent@jianyu.io。

**Comment by hanhaozi** [comment]
“卸载（保留数据）”功能需要VIP吗？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
