### ISSUE TITLE
终端模拟器运行指令出错，直接root启动成功

### ISSUE THREAD

**Issue by Flammulinavelutipes** [brevent/Brevent#95]
shamu:/ $ su
shamu:/ # sh /data/data/me.piebridge.brevent/brevent.sh
WARNING: run as root is experimental!!!
checking....brevent_server started, pid: 7951
checking for stable...quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-14 01:29:34.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-14 01:29:34.000' -d -s BreventLoader BreventServer
07-14 01:29:34.978  7939  7939 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-14 01:29:35.934  7951  7951 D BreventServer: get service: package07-14 01:29:35.941  7951  7951 I BreventServer: starting Brevent Server 1.3.4
07-14 01:29:35.950  7951  7951 D BreventServer: get service: package07-14 01:29:35.952  7951  7951 I BreventServer: brevent user: 0, uid: 0
07-14 01:29:35.953  7951  7951 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-14 01:29:35.981  7951  7951 I BreventServer: loading brevent list07-14 01:29:35.985  7951  7951 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 68
07-14 01:29:36.005  7951  7951 I BreventServer: loading brevent conf07-14 01:29:36.009  7951  7951 D BreventServer: get service: appwidget
07-14 01:29:36.016  7951  7951 D BreventServer: get service: usagestats
07-14 01:29:36.992  7951  7966 I BreventServer: Brevent Event, now: 1499966976
07-14 01:29:36.992  7951  7951 D BreventServer: check and brevent
07-14 01:29:36.995  7951  7951 D BreventServer: get service: notification
07-14 01:29:37.015  7951  7966 I BreventServer: system_server: 1794, now: 1499966977
07-14 01:29:37.448  7951  7951 D BreventServer: get service: activity
07-14 01:29:37.476  7951  7951 D BreventServer: get service: alarm
07-14 01:29:37.478  7951  7951 D BreventServer: get service: wallpaper
07-14 01:29:37.519  7951  7951 D BreventServer: get service: batterystats
07-14 01:29:37.748  7951  7951 D BreventServer: get service: appops
07-14 01:29:37.755  7951  7951 D BreventServer: get service: deviceidle
07-14 01:29:37.765  7951  7951 D BreventServer: Force stop com.topjohnwu.magisk(noRecent)
07-14 01:29:37.767  7951  7951 D BreventServer: check again in 701s
07-14 01:29:37.768  7951  7951 D BreventServer: check and brevent, took 774ms
07-14 01:29:37.773  7951  7951 I BreventServer: charging: false
07-14 01:29:37.773  7951  7951 I BreventServer: support standby: true
07-14 01:29:37.773  7951  7951 I BreventServer: support stopped: true
07-14 01:29:37.783  7951  7951 E BreventServer: Can't be run as root, please open Brevent
07-14 01:29:37.807  7939  7939 E BreventLoader: worker 7951 exited with status 1
07-14 01:29:37.807  7939  7939 D BreventLoader: signal arrived, update: 0
07-14 01:29:37.808  7935  7935 D BreventLoader: worker 7939 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by vvb2060** [comment]
>07-14 01:29:37.783 7951 7951 E BreventServer: Can't be run as root, please open Brevent

要么去把允许 ROOT 运行打开，要么直接在应用内root开启。没事用终端干嘛

_使用 [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Google Nexus 6P 发送_
