### ISSUE TITLE
2.1.9 魅族mx6开启不成功

### ISSUE THREAD

**Issue by reenning** [brevent/Brevent#95]
adb和usb调试都正常的，输入启动命令以后提示permission denied。
具体日志见图，以前都可以正常使用的。
![image](https://user-images.githubusercontent.com/26995171/30356328-063d4c88-986b-11e7-86ed-13a958b4a193.png)

**Comment by vvb2060** [comment]
新安装或清空数据后，要读完向导，显示了“请启动黑域服务”，之后才能执行命令。

**Comment by reenning** [comment]
@vvb2060  这么一说发现其他问题了 我清除了数据重新装的 向导读完点进入黑域 又返回到向导首页了

**Comment by liudongmiao** [comment]
@reenning 自行看你的魔改系统，有没有使用任何方式阻止黑域创建自己的配置文件。
有些人提过这个问题，一般属于自行魔改，魔改到不让黑域读写任何配置文件。
如果机器没有 root，想办法发送日志；如果有 root，自行解决。

**Comment by reenning** [comment]
@liudongmiao  没有root过，也不懂魔改系统，麻烦看一下日志如下

09-13 10:29:47.431  2347  2347 E AndroidRuntime: FATAL EXCEPTION: main
09-13 10:29:47.431  2347  2347 E AndroidRuntime: Process: com.pl.getaway.getaway:monitor, PID: 2347
09-13 10:29:47.431  2347  2347 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.Intent android.app.ActivityThread$ActivityClientRecord.intent' on a null object reference
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3736)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6475)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: FATAL EXCEPTION: main
09-13 12:13:41.768 10254 10254 E AndroidRuntime: Process: com.pl.getaway.getaway:monitor, PID: 10254
09-13 12:13:41.768 10254 10254 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.Intent android.app.ActivityThread$ActivityClientRecord.intent' on a null object reference
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3736)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6475)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: FATAL EXCEPTION: main
09-13 10:29:47.431  2347  2347 E AndroidRuntime: Process: com.pl.getaway.getaway:monitor, PID: 2347
09-13 10:29:47.431  2347  2347 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.Intent android.app.ActivityThread$ActivityClientRecord.intent' on a null object reference
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3736)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6475)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
09-13 10:29:47.431  2347  2347 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: FATAL EXCEPTION: main
09-13 12:13:41.768 10254 10254 E AndroidRuntime: Process: com.pl.getaway.getaway:monitor, PID: 10254
09-13 12:13:41.768 10254 10254 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.Intent android.app.ActivityThread$ActivityClientRecord.intent' on a null object reference
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3736)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6475)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
09-13 12:13:41.768 10254 10254 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by liudongmiao** [comment]
那就卸载黑域，重来看看吧。

我的 meizu 没什么问题。你从魅族商店安装就好。

**Comment by LayneHe** [comment]
魅族应用商店更新到2.1.9e版本后就不能正常使用了。向导读完点进入黑域 又返回到向导首页，没有出现“请启动黑域服务”。

**Comment by liudongmiao** [comment]
请确认以下事件：

1. 2.1.7 可以工作

2. 请邮件我，我会给你一个测试版
