### ISSUE TITLE
 build this src code meet error

### ISSUE THREAD

**Issue by Eason-hf** [brevent/Brevent#97]
import this project to AndroidStudio,then build,I meet the error as follow
"What went wrong:
Execution failed for task ' :brevent:build:buildBootstrap'.
A problem occurred starting process 'command' C:\Users\Adminstrator-pc\AppData\Local\Android\Sdk\ndk-bundle/ndk-build''
"
anybody have solution to fix it.

Thanks

**Comment by liudongmiao** [comment]
Did you install ndk?

Brevent requires Android SDK for Java, and NDK for native.

**Comment by Eason-hf** [comment]
Thanks for your reply. but I have install the SDK and NDK already.

**Comment by Eason-hf** [comment]
thanks for your reply.but Android studio have installed sdk and ndk already . On 2017-07-14 22:42 , Liu DongMiao Wrote: Did you install ndk? Brevent requires Android SDK for Java, and NDK for native. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by liudongmiao** [comment]
1. upgrade to latest gradle.
It's confirmed that some version of gradle doesn't work.

2. There is no task named ":brevent:build:buildBootstrap", but ":brevent:buildBootstrap".

3. I don't use pc. however, it should work.
