### ISSUE TITLE
运行　brevent.sh　失败　（runing　brevent.sh　error）

### ISSUE THREAD

**Issue by Soul-MO** [brevent/Brevent#98]
![image](https://user-images.githubusercontent.com/5813768/28211660-68aa8810-68d0-11e7-9b71-7af6aa37d3cc.png)

ERROR: please open Brevent to make a new brevent.sh

怎么解决 (HOW　TO　FIX　IT　？)

**Comment by liudongmiao** [comment]
黑域指令已经更新，请按屏幕提示来的。
