### ISSUE TITLE
Script freefire 

### ISSUE THREAD

**Issue by A318-lgtm** [brevent/Brevent#987]
<ml>
<head>
<title>HTML Uordered List</title>
</html>
<body>
<p> bgmi hacks </p>
<ul>
<li> long jump - mod3.4 </li>
<li>shaktiman like speed - mod5.0</li>
<li>everything moded - 7.1</li>
<li>unlimited uc = 9999999999999 - mod 9.5 </li>
<li>auto free royal pass each season - 3.0</li>
<li>1million/per.sec damage of each weapon </li>

1. <li>only headshots</li>

### <li>godlike aimbot - mod 60.705</li>
<li>super AI esp - mod - 34.16</li>

<li>all these mod number contains its own individual powers - like if
it is 9.5 that means it is capable to do that task very smoothly, 
and if it is 60.705 then it has the capibility to destroy either 
the game or the players, only well performing pc and mobiles can handle it</li>
_`[](url)`_

**Comment by babu810181** [comment]
> <title>HTML Uordered List</title>
> bgmi hacks
> 
> * long jump - mod3.4
> * shaktiman like speed - mod5.0
> * everything moded - 7.1
> * unlimited uc = 9999999999999 - mod 9.5
> * auto free royal pass each season - 3.0
> * 1million/per.sec damage of each weapon
> 1. 
> 2. only headshots
> 
> ###
> * godlike aimbot - mod 60.705
> * super AI esp - mod - 34.16
> * all these mod number contains its own individual powers - like if
>   it is 9.5 that means it is capable to do that task very smoothly, 
>   and if it is 60.705 then it has the capibility to destroy either 
>   the game or the players, only well performing pc and mobiles can handle it
> _`[](url)`_
