### ISSUE TITLE
mi5 root開啟失敗

### ISSUE THREAD

**Issue by d3841217** [brevent/Brevent#99]
Xiaomi/gemini/gemini:7.0/NAACNED/MDB:user/release-keys
SELinux: false

WARNING: run as root is experimental!!!
checking for server..started, pid: 13762
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '09-14 18:27:16.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-14 18:27:16.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
这...没有任何日志...不正常啊...

**Comment by d3841217** [comment]
那請問怎麼解決這個問題..

**Comment by liudongmiao** [comment]
不要 root 使用看看...

**Comment by d3841217** [comment]
我只會root使用..

**Comment by liudongmiao** [comment]
没有任何日志，无法解决。
